Imports common
Imports System.Data.SqlClient

Public Class clsCityMaster
#Region "Variables"
    Public City_Code As String = Nothing
    Public City_Name As String = Nothing
    Public Comp_Code As String = Nothing
    Public STATE_CODE As String = Nothing
    Public STATE_NAME As String = Nothing
    Public regioncode As String = Nothing
    Public DISTRICT_Code As String = Nothing
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select City_Code as [Code],City_Name as [City Name],Created_By as [Created By],Created_Date as [Created Date],Modify_By as [Modify By],Modify_Date as [Modify Date],Comp_Code as [Company Code],STATE_CODE  as [State Code] from TSPL_CITY_MASTER  "
        str = clsCommon.ShowSelectForm("RPTCITYFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Function SaveData(ByVal obj As clsCityMaster, ByVal isNewEntry As Boolean) As Boolean
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "City_Name", obj.City_Name)
            clsCommon.AddColumnsForChange(coll, "STATE_CODE", obj.STATE_CODE)
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "Modify_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modify_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
            clsCommon.AddColumnsForChange(coll, "region_code", obj.regioncode)
            clsCommon.AddColumnsForChange(coll, "DISTRICT_Code", obj.DISTRICT_Code, True)
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_CITY_MASTER where City_Code='" & obj.City_Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.City_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.CityMaster, "", "")
                        If clsCommon.myLen(obj.City_Code) <= 0 Then
                            Throw New Exception("Error in City Code Generation")
                        End If
                    End If
                End If
                'If clsCommon.myLen(obj.City_Code) = 0 Then
                '    Throw New Exception("Please fill Code")
                'End If
                clsCommon.AddColumnsForChange(coll, "City_Code", obj.City_Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                Dim qry As String = "SELECT Count(*) FROM TSPL_CITY_MASTER where City_Code = '" & obj.City_Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry, trans)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_CITY_MASTER", OMInsertOrUpdate.Insert, "", trans)
                ElseIf check > 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_CITY_MASTER", OMInsertOrUpdate.Update, "City_Code='" + obj.City_Code + "'", trans)
                End If
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_CITY_MASTER", OMInsertOrUpdate.Update, "City_Code='" + obj.City_Code + "'", trans)
            End If
            trans.Commit()
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsCityMaster
        Dim obj As clsCityMaster = Nothing
        Dim dt As DataTable = Nothing
        Dim qst As String = " select TSPL_City_MASTER.region_code,TSPL_City_MASTER.City_Code, TSPL_City_MASTER.City_Name,TSPL_City_MASTER.DISTRICT_Code, TSPL_City_MASTER.STATE_CODE, TSPL_STATE_MASTER.STATE_NAME from TSPL_City_MASTER left outer join TSPL_STATE_MASTER on TSPL_STATE_MASTER.STATE_CODE = TSPL_City_MASTER.STATE_CODE where 2=2"
        Select Case NavType
            Case NavigatorType.Current
                qst += " and TSPL_City_MASTER.City_Code = '" + strCode + "' "
            Case NavigatorType.Next
                qst += " and TSPL_City_MASTER.City_Code in (select min(City_Code ) from TSPL_City_MASTER where City_Code  >'" + strCode + "')"
            Case NavigatorType.First
                qst += " and TSPL_City_MASTER .City_Code in (select MIN(City_Code ) from TSPL_City_MASTER)"
            Case NavigatorType.Last
                qst += " and TSPL_City_MASTER .City_Code in (select Max(City_Code ) from TSPL_City_MASTER)"
            Case NavigatorType.Previous
                qst += " and TSPL_City_MASTER .City_Code in (select Max(City_Code ) from TSPL_City_MASTER where City_Code  <'" + strCode + "')"
        End Select
        dt = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            obj = New clsCityMaster()
            obj.City_Code = clsCommon.myCstr(dt.Rows(0)("City_Code"))
            obj.City_Name = clsCommon.myCstr(dt.Rows(0)("City_Name"))
            obj.STATE_CODE = clsCommon.myCstr(dt.Rows(0)("STATE_CODE"))
            obj.STATE_NAME = clsCommon.myCstr(dt.Rows(0)("STATE_NAME"))
            obj.regioncode = clsCommon.myCstr(dt.Rows(0)("region_code"))
            obj.DISTRICT_Code = clsCommon.myCstr(dt.Rows(0)("DISTRICT_Code"))
        End If
        Return obj
    End Function

    Public Shared Function GetDataForCombo() As DataTable
        Dim qry As String = "Select City_Code as CODE,City_Name AS NAME from TSPL_CITY_MASTER order by City_Name"
        Return clsDBFuncationality.GetDataTable(qry)
    End Function

    Public Shared Function GetName(ByVal strCode As String) As String
        Dim qry As String = "Select City_Name from TSPL_CITY_MASTER where City_Code='" + strCode + "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry))
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim qry As String = "Delete from TSPL_CITY_MASTER where City_Code='" + strCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)
    End Function

    Public Shared Function GetCodeByName(ByVal strName As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = " Select City_Code from TSPL_CITY_MASTER where City_Name = '" + strName + "' "
        Dim StrCode As String = clsDBFuncationality.getSingleValue(qry, trans)
        Return StrCode
    End Function

End Class
