Imports common
Imports System.Data.SqlClient


Public Class clsAssetBookMaster
#Region "variables"
    Public Book_Code As String = Nothing    
    Public Book_Name As String = Nothing
    Public Dep_Method_Tax_Code As String = Nothing
    Public Dep_Method_Code As String = Nothing
    Public Dep_Period_Code As String = Nothing
    Public Start_Date As Date?
    Public Dep_Rate As Decimal
    Public Book_Estimated_Life As Decimal
    Public Book_Source_value As Decimal
    Public Book_Source_Original_value As Decimal
    Public Dep_Tax_Rate As Decimal
    Public Book_Salvage_Value As Decimal
    Public Book_Salvage_Rate As Decimal
    Public Book_Net_Value As Decimal
    Public Book_Dep_Type As String
    Public Tax_Dep_Type As String
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_FA_BOOK_MASTER.Book_Code as [Code] ,TSPL_FA_BOOK_MASTER.Book_Name as [Book_Name] ,Dep_Period_Code as [Dep Period_ Code]  , " & _
                            " TSPL_FA_BOOK_MASTER.Dep_Method_Tax_Code as Dep_Method_Tax_Code , " & _
                            " TSPL_FA_BOOK_MASTER.Created_By as [Created By] ,TSPL_FA_BOOK_MASTER.Created_Date as [Created Date] ,TSPL_FA_BOOK_MASTER.Modified_By as [Modified By] ," & _
                            " TSPL_FA_BOOK_MASTER.Modified_Date as [Modified Date]  From TSPL_FA_BOOK_MASTER   "
        str = clsCommon.ShowSelectForm("ASTGRPFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function SaveData(ByVal ArrSeg As List(Of clsAssetBookMaster)) As Boolean
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            If (ArrSeg IsNot Nothing AndAlso ArrSeg.Count > 0) Then
                For Each obj As clsAssetBookMaster In ArrSeg
                    Dim coll As New Hashtable()                    
                    clsCommon.AddColumnsForChange(coll, "Book_Name", obj.Book_Name)
                    clsCommon.AddColumnsForChange(coll, "Dep_Period_Code", obj.Dep_Period_Code, True)
                    clsCommon.AddColumnsForChange(coll, "Dep_Method_Tax_Code", obj.Dep_Method_Tax_Code, True)
                    clsCommon.AddColumnsForChange(coll, "Dep_Method_Code", obj.Dep_Method_Code, True)
                    clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
                    clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
                    clsCommon.AddColumnsForChange(coll, "Dep_Rate", obj.Dep_Rate)
                    clsCommon.AddColumnsForChange(coll, "Dep_Tax_Rate", obj.Dep_Tax_Rate)
                    clsCommon.AddColumnsForChange(coll, "Book_Estimated_Life", obj.Book_Estimated_Life)
                    clsCommon.AddColumnsForChange(coll, "Book_Source_value", obj.Book_Source_value)
                    clsCommon.AddColumnsForChange(coll, "Book_Source_Original_value", obj.Book_Source_Original_value)
                    
                    clsCommon.AddColumnsForChange(coll, "Book_Salvage_Value", obj.Book_Salvage_Value)
                    clsCommon.AddColumnsForChange(coll, "Book_Salvage_Rate", obj.Book_Salvage_Rate)
                    clsCommon.AddColumnsForChange(coll, "Book_Net_Value", obj.Book_Net_Value)
                    clsCommon.AddColumnsForChange(coll, "Book_Dep_Type", obj.Book_Dep_Type)
                    clsCommon.AddColumnsForChange(coll, "Tax_Dep_Type", obj.Tax_Dep_Type)
                    If Not obj.Start_Date Is Nothing Then
                        clsCommon.AddColumnsForChange(coll, "Start_Date", clsCommon.GetPrintDate(obj.Start_Date, "dd/MMM/yyyy"))
                    End If
                    clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))

                    Dim qry As String = "Select COUNT(*) from TSPL_FA_BOOK_MASTER WHERE Book_Code='" + obj.Book_Code + "'"
                    If clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qry, trans)) <= 0 Then       '----New Entry----

                        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                            obj.Book_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.AssetBook, "", "")
                        End If
                        If clsCommon.myLen(obj.Book_Code) <= 0 Then
                            Throw New Exception("Book Code can not be empty")
                        End If
                        clsCommon.AddColumnsForChange(coll, "Book_Code", obj.Book_Code)
                        clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                        clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_FA_BOOK_MASTER", OMInsertOrUpdate.Insert, "", trans)
                    Else                                                                                '-----Update Entry-----
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_FA_BOOK_MASTER", OMInsertOrUpdate.Update, "TSPL_FA_BOOK_MASTER.Book_Code = '" + obj.Book_Code + "'", trans)
                    End If
                Next
                trans.Commit()
            End If
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function
    Public Shared Function GetName(ByVal strCode As String, ByVal trans As SqlTransaction) As String
        Try
            Dim qry As String = "select Book_Name from TSPL_FA_BOOK_MASTER where Book_Code='" + strCode + "'"
            Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
    Public Shared Function DeleteData(ByVal strGroupCode As String) As Boolean
        If (clsCommon.myLen(strGroupCode) <= 0) Then
            Throw New Exception("Code not found to Delete")
        End If
        Dim qry As String = "delete from TSPL_FA_BOOK_MASTER where Book_Code='" + strGroupCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)

    End Function

    Public Shared Function GetData(ByVal strCategoryCode As String, ByVal NavType As NavigatorType) As clsAssetBookMaster
        Try
            Dim obj As New clsAssetBookMaster()
            Dim qry As String = " select Book_Code,Book_Name,Dep_Method_Code,Dep_Method_Tax_Code,Dep_Period_Code,Start_Date,Dep_Rate,Dep_Tax_Rate," & _
                                " Book_Source_Original_value,Book_Estimated_Life,Book_Source_value,Book_Salvage_Rate,Book_Salvage_Value,Book_Net_Value,Book_Dep_Type,Tax_Dep_Type from TSPL_FA_BOOK_MASTER Where 1=1"
            Select Case NavType
                Case NavigatorType.First
                    qry += " and TSPL_FA_BOOK_MASTER.Book_Code = (select MIN(TSPL_FA_BOOK_MASTER.Book_Code) from TSPL_FA_BOOK_MASTER )"
                Case NavigatorType.Last
                    qry += " and TSPL_FA_BOOK_MASTER.Book_Code = (select MAX(TSPL_FA_BOOK_MASTER.Book_Code) from TSPL_FA_BOOK_MASTER )"
                Case NavigatorType.Next
                    qry += " and TSPL_FA_BOOK_MASTER.Book_Code = (select MIN(TSPL_FA_BOOK_MASTER.Book_Code) from TSPL_FA_BOOK_MASTER where TSPL_FA_BOOK_MASTER.Book_Code > '" + strCategoryCode + "' )"
                Case NavigatorType.Previous
                    qry += " and TSPL_FA_BOOK_MASTER.Book_Code = (select MAX(TSPL_FA_BOOK_MASTER.Book_Code) from TSPL_FA_BOOK_MASTER where TSPL_FA_BOOK_MASTER.Book_Code < '" + strCategoryCode + "')"
                Case NavigatorType.Current
                    qry += " and TSPL_FA_BOOK_MASTER.Book_Code = '" + strCategoryCode + "'"
            End Select
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
            For Each dr As DataRow In dt.Rows
                obj.Book_Code = clsCommon.myCstr(dr("Book_Code"))
                obj.Book_Name = clsCommon.myCstr(dr("Book_Name"))
                obj.Dep_Method_Tax_Code = clsCommon.myCstr(dr("Dep_Method_Tax_Code"))                
                obj.Dep_Method_Code = clsCommon.myCstr(dr("Dep_Method_Code"))
                obj.Dep_Period_Code = clsCommon.myCstr(dr("Dep_Period_Code"))
                obj.Dep_Rate = clsCommon.myCdbl(dr("Dep_Rate"))
                obj.Dep_Tax_Rate = clsCommon.myCdbl(dr("Dep_Tax_Rate"))
                obj.Book_Estimated_Life = clsCommon.myCdbl(dr("Book_Estimated_Life"))
                obj.Book_Net_Value = clsCommon.myCdbl(dr("Book_Net_Value"))
                obj.Book_Salvage_Rate = clsCommon.myCdbl(dr("Book_Salvage_Rate"))
                obj.Book_Salvage_Value = clsCommon.myCdbl(dr("Book_Salvage_Value"))
                obj.Book_Source_Original_value = clsCommon.myCdbl(dr("Book_Source_Original_value"))
                obj.Book_Source_value = clsCommon.myCdbl(dr("Book_Source_value"))
                obj.Tax_Dep_Type = clsCommon.myCstr(dr("Tax_Dep_Type"))
                obj.Book_Dep_Type = clsCommon.myCstr(dr("Book_Dep_Type"))
                If Not IsDBNull(dr("Start_Date")) Then
                    obj.Start_Date = clsCommon.myCstr(dr("Start_Date"))
                End If
            Next
            Return obj
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
End Class


