Imports common
Imports System.Data.SqlClient


Public Class clsAssetGroups
#Region "variables"
    Public Group_Code As String = Nothing
    Public Is_Default As Char = "0"
    Public Description As String = Nothing
    Public Last_Maintained_Date As String = Nothing
    Public Inactive As Char = "0"
    Public Notes As String = Nothing
    Public Category_Code As String = Nothing
    Public precounter As String = Nothing
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "  select TSPL_ASSET_GROUP.Group_Code as [Code] ,TSPL_ASSET_GROUP.Description as [Description] ,Category_Code as [Category]  ,convert(varchar,TSPL_ASSET_GROUP.Last_Maintained_Date,103) as [Last Maintained Date]   ,TSPL_ASSET_GROUP.Comp_Code as [Company Code] ,TSPL_ASSET_GROUP.Created_By as [Created By] ,TSPL_ASSET_GROUP.Created_Date as [Created Date] ,TSPL_ASSET_GROUP.Modified_By as [Modified By] ,TSPL_ASSET_GROUP.Modified_Date as [Modified Date]  From TSPL_ASSET_GROUP   "
        str = clsCommon.ShowSelectForm("ASTGRPFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function SaveData(ByVal ArrSeg As List(Of clsAssetGroups)) As Boolean
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            If (ArrSeg IsNot Nothing AndAlso ArrSeg.Count > 0) Then
                For Each obj As clsAssetGroups In ArrSeg
                    Dim coll As New Hashtable()
                    clsCommon.AddColumnsForChange(coll, "Is_Default", obj.Is_Default)
                    clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
                    clsCommon.AddColumnsForChange(coll, "Category_Code", obj.Category_Code, True)
                    clsCommon.AddColumnsForChange(coll, "Last_Maintained_Date", obj.Last_Maintained_Date)
                    clsCommon.AddColumnsForChange(coll, "Inactive", obj.Inactive)
                    clsCommon.AddColumnsForChange(coll, "Notes", obj.Notes)
                    clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
                    clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
                    clsCommon.AddColumnsForChange(coll, "Prefix_Counter", obj.precounter)
                    clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                    Dim qry As String = "Select COUNT(*) from TSPL_ASSET_GROUP WHERE Group_Code='" + obj.Group_Code + "'"
                    If clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qry, trans)) <= 0 Then       '----New Entry----

                        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                            obj.Group_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.AssetGroups, "", "")
                        End If

                        clsCommon.AddColumnsForChange(coll, "Group_Code", obj.Group_Code)
                        clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                        clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_ASSET_GROUP", OMInsertOrUpdate.Insert, "", trans)
                    Else                                                                                '-----Update Entry-----
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_ASSET_GROUP", OMInsertOrUpdate.Update, "TSPL_ASSET_GROUP.Group_Code = '" + obj.Group_Code + "'", trans)
                    End If
                Next
                trans.Commit()
            End If
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function

    Public Shared Function DeleteData(ByVal strGroupCode As String) As Boolean
        If (clsCommon.myLen(strGroupCode) <= 0) Then
            Throw New Exception("Code not found to Delete")
        End If
        Dim qry As String = "delete from TSPL_ASSET_GROUP where Group_Code='" + strGroupCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)

    End Function

    Public Shared Function GetData(ByVal strCategoryCode As String, ByVal NavType As NavigatorType) As clsAssetGroups
        Try
            Dim obj As New clsAssetGroups()
            Dim qry As String = "Select TSPL_ASSET_GROUP.Group_Code,TSPL_ASSET_GROUP.Prefix_Counter, TSPL_ASSET_GROUP.Description,TSPL_ASSET_GROUP.Category_Code, TSPL_ASSET_GROUP.Is_Default, TSPL_ASSET_GROUP.Last_Maintained_Date, TSPL_ASSET_GROUP.Inactive, TSPL_ASSET_GROUP.Notes from TSPL_ASSET_GROUP Where 1=1"
            Select Case NavType
                Case NavigatorType.First
                    qry += " and TSPL_ASSET_GROUP.Group_Code = (select MIN(TSPL_ASSET_GROUP.Group_Code) from TSPL_ASSET_GROUP )"
                Case NavigatorType.Last
                    qry += " and TSPL_ASSET_GROUP.Group_Code = (select MAX(TSPL_ASSET_GROUP.Group_Code) from TSPL_ASSET_GROUP )"
                Case NavigatorType.Next
                    qry += " and TSPL_ASSET_GROUP.Group_Code = (select MIN(TSPL_ASSET_GROUP.Group_Code) from TSPL_ASSET_GROUP where TSPL_ASSET_GROUP.Group_Code > '" + strCategoryCode + "' )"
                Case NavigatorType.Previous
                    qry += " and TSPL_ASSET_GROUP.Group_Code = (select MAX(TSPL_ASSET_GROUP.Group_Code) from TSPL_ASSET_GROUP where TSPL_ASSET_GROUP.Group_Code < '" + strCategoryCode + "')"
                Case NavigatorType.Current
                    qry += " and TSPL_ASSET_GROUP.Group_Code = '" + strCategoryCode + "'"
            End Select
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
            For Each dr As DataRow In dt.Rows
                obj.Group_Code = clsCommon.myCstr(dr("Group_Code"))
                obj.Is_Default = clsCommon.myCstr(dr("Is_Default"))
                obj.Description = clsCommon.myCstr(dr("Description"))
                obj.Last_Maintained_Date = clsCommon.myCstr(dr("Last_Maintained_Date"))
                obj.Inactive = clsCommon.myCstr(dr("Inactive"))
                obj.Notes = clsCommon.myCstr(dr("Notes"))
                obj.Category_Code = clsCommon.myCstr(dr("Category_Code"))
                obj.precounter = clsCommon.myCstr(dr("Prefix_Counter"))
            Next
            Return obj
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
End Class


