Imports common
Imports System.Data.SqlClient
Public Class clsCategories
#Region "variables"
    Public precounter As String = Nothing
    Public Category_Code As String = Nothing
    Public Is_Default As Char = "0"
    Public Description As String = Nothing
    Public Last_Maintained_Date As String = Nothing
    Public Inactive As Char = "0"
    Public Notes As String = Nothing
    Public Default_Account_Set As String = Nothing
    Public Segment_Code As String = Nothing
    Public Next_Auto_No As Integer = 0
    Public Series As Integer = 0
    Public arrGroup As List(Of clsAssetCategoryGroups) = Nothing
#End Region

    Public Shared Function SaveData(ByVal ArrSeg As List(Of clsCategories)) As Boolean
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            If (ArrSeg IsNot Nothing AndAlso ArrSeg.Count > 0) Then
                For Each obj As clsCategories In ArrSeg
                    Dim coll As New Hashtable()
                    clsCommon.AddColumnsForChange(coll, "Is_Default", obj.Is_Default)
                    clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
                    clsCommon.AddColumnsForChange(coll, "Last_Maintained_Date", obj.Last_Maintained_Date)
                    clsCommon.AddColumnsForChange(coll, "Inactive", obj.Inactive)
                    clsCommon.AddColumnsForChange(coll, "Notes", obj.Notes)
                    clsCommon.AddColumnsForChange(coll, "Default_Account_Set", obj.Default_Account_Set)
                    clsCommon.AddColumnsForChange(coll, "Segment_Code", obj.Segment_Code)
                    clsCommon.AddColumnsForChange(coll, "Next_Auto_No", obj.Next_Auto_No)
                    clsCommon.AddColumnsForChange(coll, "Prefix_Counter", obj.precounter)
                    clsCommon.AddColumnsForChange(coll, "Series", obj.Series)
                    clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
                    clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
                    clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                    Dim qry As String = "Select COUNT(*) from TSPL_ASSET_CATEGORY WHERE Category_Code='" + obj.Category_Code + "'"
                    If clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qry, trans)) <= 0 Then       '----New Entry----

                        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                            obj.Category_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.Category, "", "")
                        End If

                        clsCommon.AddColumnsForChange(coll, "Category_Code", obj.Category_Code)
                        clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                        clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_ASSET_CATEGORY", OMInsertOrUpdate.Insert, "", trans)
                    Else                                                                                '-----Update Entry-----
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_ASSET_CATEGORY", OMInsertOrUpdate.Update, "TSPL_ASSET_CATEGORY.Category_Code='" + obj.Category_Code + "'", trans)
                    End If
                    clsAssetCategoryGroups.SaveData(obj, trans)
                Next
                trans.Commit()
            End If
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function

    Public Shared Function DeleteData(ByVal strCatCode As String) As Boolean
        If (clsCommon.myLen(strCatCode) <= 0) Then
            Throw New Exception("Code not found to Delete")
        End If
        Dim qry As String = "delete from TSPL_ASSET_CATEGORY where Category_Code='" + strCatCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)

    End Function

    Public Shared Function GetData(ByVal strCategoryCode As String, ByVal NavType As NavigatorType) As clsCategories
        Try
            Dim obj As New clsCategories()
            Dim qry As String = "Select TSPL_ASSET_CATEGORY.Prefix_Counter,TSPL_ASSET_CATEGORY.Category_Code,TSPL_ASSET_CATEGORY.Series, TSPL_ASSET_CATEGORY.Description, TSPL_ASSET_CATEGORY.Is_Default, TSPL_ASSET_CATEGORY.Last_Maintained_Date, TSPL_ASSET_CATEGORY.Inactive, TSPL_ASSET_CATEGORY.Notes, TSPL_ASSET_CATEGORY.Default_Account_Set, TSPL_ASSET_CATEGORY.Segment_Code , TSPL_ASSET_CATEGORY.Next_Auto_No from TSPL_ASSET_CATEGORY Where 1=1"
            Select Case NavType
                Case NavigatorType.First
                    qry += " and TSPL_ASSET_CATEGORY.Category_Code = (select MIN(TSPL_ASSET_CATEGORY.Category_Code) from TSPL_ASSET_CATEGORY )"
                Case NavigatorType.Last
                    qry += " and TSPL_ASSET_CATEGORY.Category_Code = (select MAX(TSPL_ASSET_CATEGORY.Category_Code) from TSPL_ASSET_CATEGORY )"
                Case NavigatorType.Next
                    qry += " and TSPL_ASSET_CATEGORY.Category_Code = (select MIN(TSPL_ASSET_CATEGORY.Category_Code) from TSPL_ASSET_CATEGORY where TSPL_ASSET_CATEGORY.Category_Code > '" + strCategoryCode + "' )"
                Case NavigatorType.Previous
                    qry += " and TSPL_ASSET_CATEGORY.Category_Code = (select MAX(TSPL_ASSET_CATEGORY.Category_Code) from TSPL_ASSET_CATEGORY where TSPL_ASSET_CATEGORY.Category_Code < '" + strCategoryCode + "')"
                Case NavigatorType.Current
                    qry += " and TSPL_ASSET_CATEGORY.Category_Code = '" + strCategoryCode + "'"
            End Select
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
            For Each dr As DataRow In dt.Rows
                obj.precounter = clsCommon.myCstr(dr("Prefix_Counter"))
                obj.Category_Code = clsCommon.myCstr(dr("Category_Code"))
                obj.Is_Default = clsCommon.myCstr(dr("Is_Default"))
                obj.Description = clsCommon.myCstr(dr("Description"))
                obj.Last_Maintained_Date = clsCommon.myCstr(dr("Last_Maintained_Date"))
                obj.Inactive = clsCommon.myCstr(dr("Inactive"))
                obj.Notes = clsCommon.myCstr(dr("Notes"))
                obj.Default_Account_Set = clsCommon.myCstr(dr("Default_Account_Set"))
                obj.Segment_Code = clsCommon.myCstr(dr("Segment_Code"))
                obj.Next_Auto_No = clsCommon.myCdbl(dr("Next_Auto_No"))
                obj.Series = clsCommon.myCdbl(dr("Series"))
            Next
            obj.arrGroup = clsAssetCategoryGroups.GetCategoryGroups(obj.Category_Code, Nothing)
            Return obj
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
End Class
Public Class clsAssetCategoryGroups
#Region "Variables"
    Public Category_Code As String = Nothing
    Public SNO As Integer = 0
    Public Group_Code As String = Nothing
   
#End Region

    Public Shared Function SaveData(ByVal obj As clsCategories, ByVal trans As SqlTransaction) As Boolean
        Try
            Dim isSaved As Boolean = True
            Dim qry As String = "delete from TSPL_ASSET_CATEGORY_GROUPS where Category_Code='" & obj.Category_Code & "'"
            clsDBFuncationality.ExecuteNonQuery(qry, trans)

            Dim coll As New Hashtable()
            If obj.arrGroup IsNot Nothing AndAlso obj.arrGroup.Count > 0 Then
                For Each objtr As clsAssetCategoryGroups In obj.arrGroup
                    coll = New Hashtable()
                    clsCommon.AddColumnsForChange(coll, "Category_Code", objtr.Category_Code)
                    clsCommon.AddColumnsForChange(coll, "SNO", objtr.SNO)
                    clsCommon.AddColumnsForChange(coll, "Group_Code", objtr.Group_Code)
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_ASSET_CATEGORY_GROUPS", OMInsertOrUpdate.Insert, "", trans)
                Next                
            End If

            Return isSaved
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
    Public Shared Function GetCategoryGroups(ByVal Category_Code As String, ByVal trans As SqlTransaction) As List(Of clsAssetCategoryGroups)
        Dim objGroupList As New List(Of clsAssetCategoryGroups)
        Dim qry As String = "select * from TSPL_ASSET_CATEGORY_GROUPS where Category_Code='" & Category_Code & "' order by sno"
        Dim dt1 As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If dt1 IsNot Nothing AndAlso dt1.Rows.Count > 0 Then
            For Each dr As DataRow In dt1.Rows
                Dim objtr As New clsAssetCategoryGroups()
                objtr.SNO = CInt(dr("SNO"))
                objtr.Category_Code = dr("Category_Code")
                objtr.Group_Code = dr("Group_Code")
                objGroupList.Add(objtr)
            Next
        End If
        Return objGroupList
    End Function
End Class