Imports common
Imports System.Data.SqlClient

Public Class clsDepreciationMethod
#Region "Variables"
    Public Code As String = Nothing
    Public Description As String = Nothing
    Public Formula As String = Nothing
    Public Type As String = Nothing
#End Region


    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "  select TSPL_DEPRECIATION_METHOD.Code as [Code] ,TSPL_DEPRECIATION_METHOD.Description as [Description] ,TSPL_DEPRECIATION_METHOD.Formula as [Formula] ,TSPL_DEPRECIATION_METHOD.Created_By as [Created By] ,TSPL_DEPRECIATION_METHOD.Created_Date as [Created Date] ,TSPL_DEPRECIATION_METHOD.Modified_By as [Modified By] ,TSPL_DEPRECIATION_METHOD.Modified_Date as [Modified Date]  From TSPL_DEPRECIATION_METHOD   "
        str = clsCommon.ShowSelectForm("DEPMETHFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Function SaveData(ByVal arr As List(Of clsDepreciationMethod), ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Dim trans As SqlTransaction = Nothing
        Try
            trans = clsDBFuncationality.GetTransactin()
            For Each obj As clsDepreciationMethod In arr
                Dim coll As New Hashtable()
                clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
                clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Formula", obj.Formula)
                clsCommon.AddColumnsForChange(coll, "Type", obj.Type)
                clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))

                If clsDBFuncationality.getSingleValue("Select count(*) from TSPL_DEPRECIATION_METHOD where Code='" + obj.Code + "' ", trans) <= 0 Then

                    If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                        obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.DepreciationMethod, "", "")
                    End If

                    clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                    clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                    clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_DEPRECIATION_METHOD", OMInsertOrUpdate.Insert, "", trans)
                Else
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_DEPRECIATION_METHOD", OMInsertOrUpdate.Update, "TSPL_DEPRECIATION_METHOD.Code='" + obj.Code + "'", trans)
                End If
            Next
            If isSaved Then
                trans.Commit()
            End If
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsDepreciationMethod
        Dim obj As clsDepreciationMethod = Nothing
        Dim qry As String = "SELECT TSPL_DEPRECIATION_METHOD.Code,TSPL_DEPRECIATION_METHOD.Description,TSPL_DEPRECIATION_METHOD.Formula,TSPL_DEPRECIATION_METHOD.Type FROM TSPL_DEPRECIATION_METHOD where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_DEPRECIATION_METHOD.Code = (select MIN(Code) from TSPL_DEPRECIATION_METHOD where 1=1 )"
            Case NavigatorType.Last
                qry += " and TSPL_DEPRECIATION_METHOD.Code = (select Max(Code) from TSPL_DEPRECIATION_METHOD where 1=1 )"
            Case NavigatorType.Next
                qry += " and TSPL_DEPRECIATION_METHOD.Code = (select Min(Code) from TSPL_DEPRECIATION_METHOD where Code>'" + strCode + "' )"
            Case NavigatorType.Previous
                qry += " and TSPL_DEPRECIATION_METHOD.Code = (select Max(Code) from TSPL_DEPRECIATION_METHOD where Code<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and TSPL_DEPRECIATION_METHOD.Code = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsDepreciationMethod()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
            obj.Formula = clsCommon.myCstr(dt.Rows(0)("Formula"))
            obj.Type = clsCommon.myCstr(dt.Rows(0)("Type"))
        End If
        Return obj
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        If (clsCommon.myLen(strCode) <= 0) Then
            Throw New Exception("Code not found to Delete")
        End If

        Dim qry As String = "delete from TSPL_DEPRECIATION_METHOD where Code='" + strCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)

    End Function
End Class
