
'--------Created By Richa 25/08/2014 Against Ticket No BM00000003507
Imports common
Imports System.Data
'--------Created By Richa 25/08/2014 Against Ticket No BM00000003507
Imports System.Data.SqlClient

Public Class ClsCostCentreGroupStores
#Region "Variables"
    Public CostCenter_Code As String = Nothing
    Public Description As String = Nothing
#End Region
    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_COST_CENTRE_GROUP_MASTER.CostCenter_Code as [Code] ,TSPL_COST_CENTRE_GROUP_MASTER.Description ,TSPL_COST_CENTRE_GROUP_MASTER.Created_By as [Created By] ,Convert(varchar,TSPL_COST_CENTRE_GROUP_MASTER.Created_Date,103) as [Created Date] ,TSPL_COST_CENTRE_GROUP_MASTER.Modified_By as [Modified By] ,Convert(varchar,TSPL_COST_CENTRE_GROUP_MASTER.Modified_Date,103) as [Modified Date]  From TSPL_COST_CENTRE_GROUP_MASTER   "
        str = clsCommon.ShowSelectForm("CostCentreMaster", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsCostCentreGroupStores
        Return GetData(strCode, NavType, Nothing)
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isSaved As Boolean

        Try
            isSaved = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_COST_CENTRE_GROUP_MASTER where CostCenter_Code ='" + strCode + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry)


        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsCostCentreGroupStores
        Dim obj As ClsCostCentreGroupStores = Nothing
        Dim qry As String = "select CostCenter_Code, Description from TSPL_COST_CENTRE_GROUP_MASTER where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and CostCenter_Code = (select MIN(CostCenter_Code) from TSPL_COST_CENTRE_GROUP_MASTER)"
            Case NavigatorType.Last
                qry += " and CostCenter_Code = (select Max(CostCenter_Code) from TSPL_COST_CENTRE_GROUP_MASTER)"
            Case NavigatorType.Next
                qry += " and CostCenter_Code = (select Min(CostCenter_Code) from TSPL_COST_CENTRE_GROUP_MASTER where  CostCenter_Code>'" + strCode + "')"
            Case NavigatorType.Previous
                qry += " and CostCenter_Code = (select Max(CostCenter_Code) from TSPL_COST_CENTRE_GROUP_MASTER where CostCenter_Code<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and CostCenter_Code = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsCostCentreGroupStores()
            obj.CostCenter_Code = clsCommon.myCstr(dt.Rows(0)("CostCenter_Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
        End If
        Return obj


    End Function
    Public Function SaveData(ByVal obj As ClsCostCentreGroupStores, ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    obj.CostCenter_Code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.CostCenterGroupStore, "", "")
                End If
                clsCommon.AddColumnsForChange(coll, "CostCenter_Code", obj.CostCenter_Code.ToUpper())
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
                Dim qry As String = "SELECT Count(*) FROM TSPL_COST_CENTRE_GROUP_MASTER where CostCenter_Code= '" & obj.CostCenter_Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_COST_CENTRE_GROUP_MASTER", OMInsertOrUpdate.Insert, "")
                Else
                    Throw New Exception("This Code Is Already Exist")
                End If
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_COST_CENTRE_GROUP_MASTER", OMInsertOrUpdate.Update, "CostCenter_Code='" + obj.CostCenter_Code + "'")
            End If

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select CostCenter_Code from TSPL_COST_CENTRE_GROUP_MASTER where CostCenter_Code ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function

End Class
