Imports common
Imports System.Data.SqlClient
Public Class clsItemchargecategorymaster
#Region "Variables"
    Public chrcategorycode As String = Nothing
    Public chrcategorydesc As String = Nothing
    Public glacccode As String = Nothing
    Public glaccdesc As String = Nothing
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "  select tspl_charge_category.Charge_Cat_Code as [Code] ,tspl_charge_category.Description as [Description] ,tspl_charge_category.GL_Code as [GL Code] ,tspl_charge_category.GL_Desc as [GL Description] ,tspl_charge_category.Created_By as [Created By] ,tspl_charge_category.Created_Date as [Created Date] ,tspl_charge_category.Modify_By as [Modify By] ,tspl_charge_category.Modify_Date as [Modify Date]  From tspl_charge_category  "
        str = clsCommon.ShowSelectForm("ITMCHRGCATMST", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function GetData(ByVal strcode As String, ByVal NavType As NavigatorType) As clsItemchargecategorymaster
        Dim obj As clsItemchargecategorymaster = Nothing
        Dim qry As String = "select TSPL_GL_Accounts.description,b.charge_cat_code,b.description as cat_desc,b.gl_code from tspl_charge_category b left outer join TSPL_GL_Accounts on TSPL_GL_Accounts.account_code=b.gl_code where "

        Select Case NavType
            Case NavigatorType.Current
                qry += "  b.charge_cat_code='" + strcode + "'"
            Case NavigatorType.Next
                qry += " b.charge_cat_code in (select min(t.charge_cat_code) from tspl_charge_category  as t where t.charge_cat_code  >'" + strcode + "')"
            Case NavigatorType.First
                qry += " b.charge_cat_code in (select min(t.charge_cat_code ) from tspl_charge_category  as t )"
            Case NavigatorType.Last
                qry += " b.charge_cat_code in (select max(t.charge_cat_code ) from tspl_charge_category  as t )"
            Case NavigatorType.Previous
                qry += " b.charge_cat_code in (select max(t.charge_cat_code ) from tspl_charge_category  as t where t.charge_cat_code  <'" + strcode + "')"
        End Select

        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            obj = New clsItemchargecategorymaster
            obj.chrcategorycode = clsCommon.myCstr(dt.Rows(0)("charge_cat_code"))
            obj.chrcategorydesc = clsCommon.myCstr(dt.Rows(0)("cat_desc"))
            obj.glacccode = clsCommon.myCstr(dt.Rows(0)("gl_code"))
            obj.glaccdesc = clsCommon.myCstr(dt.Rows(0)("description"))
        End If
        Return obj
    End Function
    Public Shared Function DeleteData(ByVal strcode As String) As Boolean
        Dim qry As String = "delete from tspl_charge_category where charge_cat_code='" + strcode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)
    End Function
    Public Shared Function SaveData(ByVal obj As clsItemchargecategorymaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "comp_code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "description", obj.chrcategorydesc)
            clsCommon.AddColumnsForChange(coll, "gl_code", obj.glacccode)
            clsCommon.AddColumnsForChange(coll, "gl_desc", obj.glaccdesc)
            clsCommon.AddColumnsForChange(coll, "modify_by", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "modify_date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"))

            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_Charge_Category where charge_cat_code='" & obj.chrcategorycode & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.chrcategorycode = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.ItemChargeCategoryMaster, "", "")
                        If clsCommon.myLen(obj.chrcategorycode) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "charge_cat_code", obj.chrcategorycode)
                clsCommon.AddColumnsForChange(coll, "created_by", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "created_date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"))

                If (clsCommon.myLen(obj.chrcategorycode) = 0) Then
                    Throw New Exception("Please Fill Charge Category Code")
                    isSaved = False
                End If
                If (clsCommon.myLen(obj.glacccode) = 0) Then
                    Throw New Exception("Please Fill GL Account Code")
                    isSaved = False
                End If

                Dim qry1 As String
                qry1 = "select count(*) from TSPL_Charge_Category where charge_cat_code='" + obj.chrcategorycode + "'"
                Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1)
                If check1 = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_Charge_Category", OMInsertOrUpdate.Insert, "", trans)
                Else
                    Throw New Exception("This Code Is Already Exist")

                End If
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_Charge_Category ", OMInsertOrUpdate.Update, "charge_cat_code='" + obj.chrcategorycode + "'", trans)
            End If

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function
End Class
