Imports common
Imports System.IO
Imports System.Data.SqlClient
Public Class clsLostDefectSealNoHead
    Public DOC_No As String = Nothing
    Public DOC_DATE As String = Nothing
    Public Doc_type As String = Nothing
    Public Location_code As String = Nothing
    Public Created_By As String = Nothing
    Public Created_Date As String = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As String = Nothing
    Public Comp_Code As String = Nothing
    Public arrObj As List(Of clsLostDefectSealNoDetails) = Nothing
    Public isNewEntry As Boolean = False
    Public isPosted As Integer = 0
    Public Posting_date As String = String.Empty
    Public qty As Integer = 0
    Public item_code As String = String.Empty
    Public remarks As String = String.Empty
    Public seal_type As String = String.Empty
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Try
            Dim qry As String = "  select Tspl_Lost_defect_sealNo_Head.DOC_No as [DocNo] ,Tspl_Lost_defect_sealNo_Head.DOC_DATE as [Doc Date] ,Tspl_Lost_defect_sealNo_Head.Doc_type as [Doc Type],case when  isnull(Tspl_Lost_defect_sealNo_Head.Isposted,0)=0 then 'Yes' else 'No'end as [Is Posted] ,Tspl_Lost_defect_sealNo_Head.Location_code as [Location Code] ,Tspl_Lost_defect_sealNo_Head.Created_By as [Created By] ,Tspl_Lost_defect_sealNo_Head.Created_Date as [Created Date] ,Tspl_Lost_defect_sealNo_Head.Modified_By as [Modified By] ,Tspl_Lost_defect_sealNo_Head.Modified_Date as [Modified Date] ,Tspl_Lost_defect_sealNo_Head.Comp_Code as [Comp Code],Tspl_Lost_defect_sealNo_Head.Seal_Type as [Seal Type]  From Tspl_Lost_defect_sealNo_Head  "
            str = clsCommon.ShowSelectForm("LostDefectSealNo", qry, "DocNo", whrcls, curcode, "DocNo", isButtonClicked)

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return str
    End Function
    Public Shared Function SaveData(ByVal obj As clsLostDefectSealNoHead, ByVal tran As SqlTransaction) As Boolean
        Dim issaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Doc_type", obj.Doc_type)
            clsCommon.AddColumnsForChange(coll, "DOC_DATE", clsCommon.GetPrintDate(obj.DOC_DATE, "dd/MMM/yyyy"))
            clsCommon.AddColumnsForChange(coll, "Location_code", obj.Location_code)
            clsCommon.AddColumnsForChange(coll, "item_code", obj.item_code)
            clsCommon.AddColumnsForChange(coll, "qty", clsCommon.myCdbl(obj.qty))
            clsCommon.AddColumnsForChange(coll, "Modified_By", obj.Modified_By)
            clsCommon.AddColumnsForChange(coll, "remarks", obj.remarks)
            clsCommon.AddColumnsForChange(coll, "seal_Type", obj.seal_type)
            'clsCommon.AddColumnsForChange(coll, "item_code", obj.item_code)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(obj.Modified_Date, "dd/MMM/yyyy"))
            clsCommon.AddColumnsForChange(coll, "isPosted", 0)
            clsCommon.AddColumnsForChange(coll, "Comp_Code", obj.Comp_Code)
            If obj.isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from Tspl_Lost_defect_sealNo_Head where DOC_No='" & obj.DOC_No & "'")
                    If ChkNewEntry = 0 Then
                        obj.DOC_No = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(obj.DOC_DATE, "dd/MM/yyyy"), clsDocType.LostDefectSealNo, "", "")
                        If clsCommon.myLen(obj.DOC_No) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "DOC_No", obj.DOC_No)
                clsCommon.AddColumnsForChange(coll, "Created_By", obj.Created_By)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(obj.Created_Date, "dd/MMM/yyyy"))
                issaved = issaved And clsCommonFunctionality.UpdateDataTable(coll, "Tspl_Lost_defect_sealNo_Head", OMInsertOrUpdate.Insert, "", tran)
            Else
                issaved = issaved And clsCommonFunctionality.UpdateDataTable(coll, "Tspl_Lost_defect_sealNo_Head", OMInsertOrUpdate.Update, "Tspl_Lost_defect_sealNo_Head.doc_no='" + obj.DOC_No + "'", tran)
            End If
            issaved = issaved And clsLostDefectSealNoDetails.SaveData(obj.arrObj, tran)

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return issaved
    End Function
    Public Shared Function getData(ByVal strCode As String, ByVal navtype As NavigatorType) As clsLostDefectSealNoHead
        Dim obj As New clsLostDefectSealNoHead
        Try

            Dim whrCls As String = String.Empty
            If clsCommon.myLen(objCommonVar.strCurrUserLocations) > 0 And clsCommon.myLen(strCode) <= 0 Then
                whrCls = " and Location_code in (" & objCommonVar.strCurrUserLocations & ") "
            End If
            obj.arrObj = New List(Of clsLostDefectSealNoDetails)
            Dim qst As String = " select *   From Tspl_Lost_defect_sealNo_Head   where 1=1 " & whrCls
            Select Case navtype
                Case NavigatorType.Current
                    qst += " and Tspl_Lost_defect_sealNo_Head.doc_no in ('" + strCode + "')"
                Case NavigatorType.Next
                    qst += " and Tspl_Lost_defect_sealNo_Head.doc_no in (select min(doc_no ) from Tspl_Lost_defect_sealNo_Head where doc_no  >'" + strCode + "' " & whrCls & ") "
                Case NavigatorType.First
                    qst += " and Tspl_Lost_defect_sealNo_Head.doc_no in (select MIN(doc_no ) from Tspl_Lost_defect_sealNo_Head where 1=1 " & whrCls & ") "
                Case NavigatorType.Last
                    qst += " and Tspl_Lost_defect_sealNo_Head.doc_no in (select Max(doc_no ) from Tspl_Lost_defect_sealNo_Head where 1=1 " & whrCls & ") "
                Case NavigatorType.Previous
                    qst += " and Tspl_Lost_defect_sealNo_Head.doc_no in (select Max(doc_no ) from Tspl_Lost_defect_sealNo_Head where doc_no  <'" + strCode + "' " & whrCls & ") "
            End Select
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
            If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                obj.DOC_No = clsCommon.myCstr(dt.Rows(0)("DOC_No"))
                obj.Doc_type = clsCommon.myCstr(dt.Rows(0)("Doc_type"))
                obj.item_code = clsCommon.myCstr(dt.Rows(0)("item_code"))
                obj.qty = clsCommon.myCdbl(dt.Rows(0)("qty"))
                obj.DOC_DATE = clsCommon.myCDate(dt.Rows(0)("DOC_DATE"))
                obj.Location_code = clsCommon.myCstr(dt.Rows(0)("Location_code"))
                obj.remarks = clsCommon.myCstr(dt.Rows(0)("remarks"))
                obj.seal_type = clsCommon.myCstr(dt.Rows(0)("seal_type"))
                obj.isPosted = clsCommon.myCdbl(dt.Rows(0)("isPosted"))
                If obj.isPosted = 1 Then
                    obj.Posting_Date = clsCommon.myCDate(dt.Rows(0)("Posting_Date"))
                End If
                obj.arrObj = clsLostDefectSealNoDetails.getData(obj.DOC_No)
            End If
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return obj
    End Function

    Public Shared Function PostData(ByVal FormId As String, ByVal strDocNo As String) As Boolean
        Dim trans As SqlTransaction = Nothing
        Try
            Dim isSaved As Boolean = True
            If (clsCommon.myLen(strDocNo) <= 0) Then
                Throw New Exception("Doc No not found to Post")
            End If

            Dim obj As clsLostDefectSealNoHead = clsLostDefectSealNoHead.getData(strDocNo, NavigatorType.Current)
            trans = clsDBFuncationality.GetTransactin()
            If (obj Is Nothing OrElse clsCommon.myLen(obj.DOC_No) <= 0) Then
                Throw New Exception("No Data found to Post")
            End If
            clsERPFuncationality.ValidateLocationCode(objCommonVar.CurrentCompanyCode, "Milk Procurement", "Lost Defect Seal No", obj.Location_code, clsCommon.myCDate(obj.DOC_DATE), trans)
            If (obj.isPosted = 1) Then
                Throw New Exception("Already Post on :" + obj.Posting_Date)
            End If

            '--------------------
            Dim isResult As Boolean = clsApprovalScreen.CheckApprovalLevel(FormId, "Tspl_Lost_defect_sealNo_Head", "doc_no", obj.DOC_No, trans)
            If isResult = False Then
                trans.Commit()
                Return False
            End If

            Dim strItemCode As String = String.Empty
            strItemCode = obj.item_code
            'If clsCommon.myLen(strItemCode) <= 0 Then
            '    Throw New Exception("No Item Found Of Type Seal No")
            'End If
            Dim qry As String = ""
            Dim ArrLocationDetails As List(Of clsItemLocationDetails) = New List(Of clsItemLocationDetails)()
            Dim ArrInventoryMovement As List(Of clsInventoryMovement) = New List(Of clsInventoryMovement)
            Dim strItemType As String = clsItemMaster.GetItemType(strItemCode, trans)
            Dim strItemTypeToSave As String = ""
            If clsCommon.CompairString(strItemType, "R") = CompairStringResult.Equal Then
                strItemTypeToSave = "RM"
            ElseIf clsCommon.CompairString(strItemType, "P") = CompairStringResult.Equal OrElse clsCommon.CompairString(strItemType, "O") = CompairStringResult.Equal Then
                strItemTypeToSave = "OT"
            ElseIf clsCommon.CompairString(strItemType, "F") = CompairStringResult.Equal Then
                strItemTypeToSave = "FT"
            ElseIf clsCommon.CompairString(strItemType, "A") = CompairStringResult.Equal Then
                strItemTypeToSave = "A"
            Else
                strItemTypeToSave = strItemType
                'Throw New Exception("Item Type not found: " + strItemType)
            End If
            Dim strItemUnitCode As String = clsItemMaster.GetStockUnit(strItemCode, trans)

            Dim objLocationDetails As New clsItemLocationDetails()
            Dim ConvFac As Double = clsItemMaster.GetConvertionFactor(strItemCode, strItemUnitCode, trans)
            If ConvFac = 0 Then
                Throw New Exception("Conversion Factor found zero for item :" + strItemCode + " and Uom:'" + strItemUnitCode)
            End If

            objLocationDetails.Item_Code = strItemCode
            objLocationDetails.Item_Desc = clsItemMaster.GetItemName(strItemCode, trans)
            objLocationDetails.Location_Code = obj.Location_code
            objLocationDetails.Location_Desc = clsLocation.GetName(obj.Location_code, trans)
            objLocationDetails.Item_Qty = obj.qty
            objLocationDetails.Amount = 0
            objLocationDetails.MRP = 0
            objLocationDetails.ItemType = strItemTypeToSave
            ArrLocationDetails.Add(objLocationDetails)

            Dim objInventoryMovemnt As New clsInventoryMovement()
            objInventoryMovemnt.InOut = "O"
            objInventoryMovemnt.Location_Code = obj.Location_code
            objInventoryMovemnt.Item_Code = obj.Item_Code
            objInventoryMovemnt.Item_Desc = clsItemMaster.GetItemName(obj.item_code, trans)

            objInventoryMovemnt.Qty = obj.qty
            objInventoryMovemnt.UOM = strItemUnitCode
            objInventoryMovemnt.MRP = 0
            objInventoryMovemnt.Add_Cost = 0
            objInventoryMovemnt.Net_Cost = 0
            If clsCommon.CompairString(strItemType, "R") = CompairStringResult.Equal Then
                objInventoryMovemnt.ItemType = "RM"
            ElseIf clsCommon.CompairString(strItemType, "P") = CompairStringResult.Equal OrElse clsCommon.CompairString(strItemType, "O") = CompairStringResult.Equal Then
                objInventoryMovemnt.ItemType = "OT"
            ElseIf clsCommon.CompairString(strItemType, "F") = CompairStringResult.Equal Then
                objInventoryMovemnt.ItemType = "FT"
            End If
            objInventoryMovemnt.ItemType = strItemTypeToSave
            objInventoryMovemnt.Basic_Cost = 0
            ArrInventoryMovement.Add(objInventoryMovemnt)
            isSaved = isSaved AndAlso clsItemLocationDetails.SaveData(clsCommon.GetPrintDate(obj.DOC_DATE, "dd/MM/yyyy"), ArrLocationDetails, trans)
            isSaved = isSaved AndAlso clsInventoryMovement.SaveData("LostDefectSeal", obj.DOC_No, obj.DOC_DATE, clsCommon.GetPrintDate(obj.DOC_DATE, "dd/MM/yyyy"), ArrInventoryMovement, trans)
            ''------------Create GL Entry
            'qry = " select TSPL_MCC_Dispatch_Challan.MCC_Code,TSPL_MCC_Dispatch_Challan.Mcc_Or_Plant_Code ,TSPL_PURCHASE_ACCOUNTS.Inv_Control_Account,TSPL_MCC_Dispatch_Challan.Transfer_Price*TSPL_MCC_Dispatch_Challan.Net_Qty as Amt   from TSPL_PURCHASE_ACCOUNTS left outer join TSPL_ITEM_MASTER on TSPL_ITEM_MASTER.Purchase_Class_Code =TSPL_PURCHASE_ACCOUNTS.Purchase_Class_Code left outer join TSPL_MCC_Dispatch_Challan  on TSPL_MCC_Dispatch_Challan .Item_Code=TSPL_ITEM_MASTER.Item_Code where TSPL_MCC_Dispatch_Challan.Chalan_NO ='" & obj.Chalan_NO & "' "
            'Dim ArryLst As ArrayList = New ArrayList()
            'Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)


            'If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            '    Dim qry1 As String = " select GL_Acc  from TSPL_ITEM_LOCATION_MAPPING where Frm_Location='" & dt.Rows(0)("MCC_Code") & "' and To_Location='" & dt.Rows(0)("Mcc_Or_Plant_Code") & "'"
            '    Dim dt1 As DataTable = clsDBFuncationality.GetDataTable(qry1, trans)
            '    If dt1 IsNot Nothing AndAlso dt1.Rows.Count > 0 Then
            '        Dim strStocktrnsfrAc As String = dt1.Rows(0)("GL_Acc")
            '        Dim strGITLoc As String = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select GIT_Location  from TSPL_LOCATION_MASTER where Location_Code='" & dt.Rows(0)("Mcc_Or_Plant_Code") & "'", trans))
            '        If clsCommon.myLen(strGITLoc) > 0 Then
            '            Dim strInvCntrlAcFrom As String = dt.Rows(0)("Inv_Control_Account")
            '            strInvCntrlAcFrom = clsERPFuncationality.ChangeGLAccountLocationSegment(strInvCntrlAcFrom, dt.Rows(0)("MCC_Code"), trans)
            '            Dim strInvCntrlAcTo As String = dt.Rows(0)("Inv_Control_Account")
            '            strInvCntrlAcTo = clsERPFuncationality.ChangeGLAccountLocationSegment(strInvCntrlAcTo, strGITLoc, trans)
            '            Dim strStkTrnsfAcFrom As String = strStocktrnsfrAc
            '            strStkTrnsfAcFrom = clsERPFuncationality.ChangeGLAccountLocationSegment(strStkTrnsfAcFrom, strGITLoc, trans)
            '            Dim strStkTrnsfAcTo As String = strStocktrnsfrAc
            '            strStkTrnsfAcTo = clsERPFuncationality.ChangeGLAccountLocationSegment(strStkTrnsfAcTo, dt.Rows(0)("MCC_Code"), trans)
            '            ArryLst.Add(New String() {strInvCntrlAcTo, dt.Rows(0)("Amt")})
            '            ArryLst.Add(New String() {strInvCntrlAcFrom, dt.Rows(0)("Amt") * -1})
            '            ArryLst.Add(New String() {strStkTrnsfAcTo, dt.Rows(0)("Amt")})
            '            ArryLst.Add(New String() {strStkTrnsfAcFrom, dt.Rows(0)("Amt") * -1})
            '        Else
            '            Throw New Exception("GIT Location is not Mapped with  " & dt.Rows(0)("Mcc_Or_Plant_Code"))
            '        End If
            '    Else
            '        Throw New Exception("Stock Transfer Locations are not Mapped   ")
            '    End If
            '    clsJournalMaster.FunGrnlEntryWithTrans(trans, clsCommon.GetPrintDate(obj.Dispatch_Date, "dd/MMM/yyyy"), " GL Entry Against Dispatch Challan No  -" + obj.Chalan_NO + "", "DI-CH", "Dispatch Challan", obj.Chalan_NO, "", "C", obj.Item_Code, obj.Item_Desc, objCommonVar.CurrentUserCode, objCommonVar.CurrentCompanyCode, ArryLst)
            'End If



            '--------------------------

            Dim strQry As String = " update Tspl_Lost_defect_sealNo_Head set isPosted='1', Posting_Date='" & clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy") & "' where doc_no='" & obj.DOC_No & "'"
            isSaved = isSaved AndAlso clsDBFuncationality.ExecuteNonQuery(strQry, trans)
            If isSaved Then
                trans.Commit()
            Else
                trans.Rollback()
            End If
            Return isSaved
        Catch ex As Exception
            trans.Rollback()
            Throw New Exception(ex.Message)
        End Try
        Return True
    End Function

    Public Shared Function deleteData(ByVal doc_No As String, ByVal tran As SqlTransaction) As Boolean
        Try
            Dim isDeleted As Boolean = True
            Dim qry As String = "delete from Tspl_Lost_defect_sealNo_Details where  doc_No='" & doc_No & "'"
            isDeleted = isDeleted AndAlso clsDBFuncationality.ExecuteNonQuery(qry, tran)
            qry = "delete from Tspl_Lost_defect_sealNo_Head where  doc_No='" & doc_No & "'"
            isDeleted = isDeleted AndAlso clsDBFuncationality.ExecuteNonQuery(qry, tran)
            Return isDeleted
        Catch ex As Exception
            Throw New Exception(ex.Message)
            Return False
        End Try
    End Function
End Class
Public Class clsLostDefectSealNoDetails
    Public DOC_No As String = Nothing
    Public Seal_No As String = Nothing


    Public Shared Function SaveData(ByVal arr As List(Of clsLostDefectSealNoDetails), ByVal tran As SqlTransaction) As Boolean
        Dim issaved As Boolean = True
        Try
            Dim i As Integer = 0
            If arr.Count > 0 Then
                Dim qry As String = "delete from Tspl_Lost_defect_sealNo_Details where  Doc_No='" & arr.Item(0).DOC_No & "'"
                clsDBFuncationality.ExecuteNonQuery(qry, tran)
                For i = 0 To arr.Count - 1
                    Dim coll As New Hashtable()
                    clsCommon.AddColumnsForChange(coll, "DOC_No", arr.Item(i).DOC_No)
                    clsCommon.AddColumnsForChange(coll, "Seal_No", arr.Item(i).Seal_No)
                    issaved = issaved And clsCommonFunctionality.UpdateDataTable(coll, "Tspl_Lost_defect_sealNo_Details", OMInsertOrUpdate.Insert, "", tran)
                Next
            End If
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return issaved
    End Function
    Public Shared Function getData(ByVal doc_no As String) As List(Of clsLostDefectSealNoDetails)
        Dim arr As New List(Of clsLostDefectSealNoDetails)
        Try
            Dim obj As New clsLostDefectSealNoDetails
            Dim q As String = "select * from Tspl_Lost_defect_sealNo_Details where doc_no='" & doc_no & "'"
            Dim dtbl As DataTable = clsDBFuncationality.GetDataTable(q)
            If dtbl IsNot Nothing AndAlso dtbl.Rows.Count > 0 Then
                For i As Integer = 0 To dtbl.Rows.Count - 1
                    obj = New clsLostDefectSealNoDetails
                    obj.DOC_No = clsCommon.myCstr(dtbl.Rows(i)("DOC_No"))
                    obj.Seal_No = clsCommon.myCstr(dtbl.Rows(i)("Seal_No"))
                    arr.Add(obj)
                Next
            End If
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return arr
    End Function

End Class