'--------Created By Richa 10/12/2014 Against Ticket No BM00000004964
''updation by richa agarwal againt ticket no BM00000006065 on 09/04/2015(Add CIF Type field in Drop Down)

Imports common
Imports System.Data.SqlClient
Public Class FrmMerchantPaymentTerms
    Inherits FrmMainTranScreen
#Region "Variables"
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String
#End Region
#Region "User Defined Functions and Subroutines"

    Public Sub New()
        InitializeComponent()
    End Sub
#End Region

    Private Sub FrmMerchantPaymentTerms_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            closeform()

        ElseIf e.Alt And e.KeyCode = Keys.N Then
            Reset()
        End If
    End Sub
    Public Sub closeform()
        Me.Close()
        GC.Collect()
    End Sub

    Private Sub FrmMerchantPaymentTerms_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        SetUserMgmtNew()
        Reset()
        LoadTermsType()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S/U for Save/Update Transaction")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D for Delete Transaction")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnnew, "Press Alt+N for New Transaction")
    End Sub
    Sub SaveData()
        Try
            If AllowToSave() Then
                Dim obj As New ClsMerchantPaymentTerms()
                obj.Code = fndTermsCode.Value
                obj.Description = TxtDescription.Text
                obj.TermsType = clsCommon.myCstr(cboTermsType.SelectedValue)

                If (ClsMerchantPaymentTerms.SaveData(obj, isNewEntry)) Then
                    clsCommon.MyMessageBoxShow("Data saved Successfully", Me.Text)
                    LoadData(obj.Code, NavigatorType.Current)
                End If
            End If
        Catch ex As Exception

            clsCommon.MyMessageBoxShow(ex.Message, Me.Text)
        End Try
    End Sub
    Private Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(fndTermsCode.Value) <= 0 Then
                fndTermsCode.Focus()
                Throw New Exception("Code cannot be left blank.")
            End If
        End If
        
        If clsCommon.myCstr(TxtDescription.Text) = "" Then
            TxtDescription.Focus()
            Throw New Exception("Description cannot be left blank.")
        End If
        If clsCommon.CompairString(cboTermsType.Text, "Select") = CompairStringResult.Equal Then
            cboTermsType.Focus()
            Throw New Exception("Please select Type")
        End If
        Return True
    End Function
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Dim obj As ClsMerchantPaymentTerms = ClsMerchantPaymentTerms.GetData(strCode, NavTyep)
        If obj IsNot Nothing Then
            isNewEntry = False
            fndTermsCode.Value = obj.Code
            TxtDescription.Text = obj.Description

            If clsCommon.myLen(obj.TermsType) > 0 Then
                If obj.TermsType = "A" Then
                    cboTermsType.Text = "Advance"
                ElseIf obj.TermsType = "O" Then
                    cboTermsType.Text = "On Account"
                ElseIf obj.TermsType = "L" Then
                    cboTermsType.Text = "LC"
                ElseIf obj.TermsType = "B" Then
                    cboTermsType.Text = "Balance Payment"
                ElseIf obj.TermsType = "R" Then
                    cboTermsType.Text = "Retained"
                ElseIf obj.TermsType = "C" Then
                    cboTermsType.Text = "CAD"
                ElseIf obj.TermsType = "CI" Then
                    cboTermsType.Text = "CIF"
                End If
            Else
                cboTermsType.Text = "Select"
            End If
            fndtermscode.MyReadOnly = True
            btnsave.Text = "Update"
            btndelete.Enabled = True
        Else
            Reset()

        End If
    End Sub
    Private Sub DeleteData()
        Try
            If (deleteConfirm()) Then
                If (ClsMerchantPaymentTerms.DeleteData(fndTermsCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    Reset()
                End If
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.FrmMerchantPaymentTerms)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")

        End If
        btnsave.Visible = MyBase.isModifyFlag

        If btnsave.Visible = True Then
            RMExport.Enabled = True
            RMImport.Enabled = True
        Else
            RMExport.Enabled = False
            RMImport.Enabled = False
        End If

        btndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Sub LoadTermsType()
        Dim dt As New DataTable
        dt.Columns.Add("Code", GetType(String))
        dt.Columns.Add("Name", GetType(String))
        dt.Rows.Add("", "Select")
        dt.Rows.Add("A", "Advance")
        dt.Rows.Add("O", "On Account")
        dt.Rows.Add("L", "LC")
        dt.Rows.Add("B", "Balance Payment")
        dt.Rows.Add("R", "Retained")
        dt.Rows.Add("C", "CAD")
        dt.Rows.Add("CI", "CIF")

        cboTermsType.DataSource = dt
        cboTermsType.ValueMember = "Code"
        cboTermsType.DisplayMember = "Name"
    End Sub

    Sub Reset()

        fndtermscode.Value = ""
        TxtDescription.Text = ""
        fndtermscode.MyReadOnly = False
        btnsave.Text = "Save"
        btndelete.Enabled = False
        isNewEntry = True
        Dim desc As String = ""
       
        cboTermsType.Text = "SELECT"
    End Sub
    Private Sub btnsave_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnsave.Click
        SaveData()
    End Sub

    Private Sub btndelete_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub

    Private Sub btnclose_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnclose.Click
        closeform()
    End Sub

    Private Sub btnnew_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnnew.Click
        Reset()
    End Sub

    Private Sub fndTermsCode__MYNavigator(ByVal sender As Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndTermsCode._MYNavigator
        Try
            LoadData(fndTermsCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try

    End Sub

    Private Sub fndTermsCode__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndTermsCode._MYValidating
        Dim str As String = "select count(*) from TSPL_PAYMENT_TERMS_MASTER_MT where Code ='" + fndTermsCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            fndTermsCode.MyReadOnly = False
        Else
            fndTermsCode.MyReadOnly = True
        End If
        If fndTermsCode.MyReadOnly OrElse isButtonClicked Then
            fndTermsCode.Value = ClsMerchantPaymentTerms.getFinder("", fndTermsCode.Value, isButtonClicked)
            If fndTermsCode.Value <> "" Then
                LoadData(fndTermsCode.Value, NavigatorType.Current)
            Else
                Reset()
            End If
        End If
    End Sub

    Private Sub RMExport_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles RMExport.Click
        Dim str As String
        str = "select Code,Description,CASE WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='A' THEN 'Advance' WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='O' THEN 'On Account' WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='L' THEN 'LC' WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='B' THEN 'Balance Payment' WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='R' THEN 'Retained' WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='C' THEN 'CAD'  WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='CI' THEN 'CIF' ELSE '' END AS [Terms Type] from TSPL_PAYMENT_TERMS_MASTER_MT"
        transportSql.ExporttoExcel(str, Me)
    End Sub

    Private Sub RMImport_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles RMImport.Click
        Dim gv As New RadGridView()
        Dim IsNewEntry As Boolean
        Dim trans As SqlTransaction = Nothing
        Me.Controls.Add(gv)

        If transportSql.importExcel(gv, "Code", "Description", "Terms Type") Then
            Dim linno As Integer = 1
            Try
                trans = clsDBFuncationality.GetTransactin()
                connectSql.OpenConnection()


                For Each grow As GridViewRowInfo In gv.Rows

                    Dim obj As New ClsMerchantPaymentTerms()

                    Dim strTermsCode As String = clsCommon.myCstr(grow.Cells("Code").Value)
                    Dim strTermsdescription As String = clsCommon.myCstr(grow.Cells("Description").Value)
                    Dim strtermstype As String = clsCommon.myCstr(grow.Cells("Terms Type").Value)


                    linno += 1

                    If strTermsCode = String.Empty Then
                        Throw New Exception("Terms Code cannot be left blank at Line No. " + clsCommon.myCstr(linno) + ".")
                    End If

                    If strTermsdescription = String.Empty Then
                        Throw New Exception("Terms Description cannot be left blank at Line No. " + clsCommon.myCstr(linno) + ".")
                    End If

                    If strTermsCode.Length > 12 Then
                        common.clsCommon.MyMessageBoxShow("Terms Code length cannot be more than 12")
                        trans.Rollback()
                        Exit Sub
                    End If
                    If strTermsdescription.Length > 200 Then
                        common.clsCommon.MyMessageBoxShow("Terms Description length cannot be more than 200")
                        trans.Rollback()
                        Exit Sub
                    End If


                   

                    If clsCommon.myLen(strtermstype) > 0 Then
                        If clsCommon.CompairString(strtermstype.ToUpper(), "ADVANCE") = CompairStringResult.Equal Then
                            obj.TermsType = "A"
                        ElseIf clsCommon.CompairString(strtermstype.ToUpper(), "ON ACCOUNT") = CompairStringResult.Equal Then
                            obj.TermsType = "O"
                        ElseIf clsCommon.CompairString(strtermstype.ToUpper(), "LC") = CompairStringResult.Equal Then
                            obj.TermsType = "L"
                        ElseIf clsCommon.CompairString(strtermstype.ToUpper(), "BALANCE PAYMENT") = CompairStringResult.Equal Then
                            obj.TermsType = "B"
                        ElseIf clsCommon.CompairString(strtermstype.ToUpper(), "RETAINED") = CompairStringResult.Equal Then
                            obj.TermsType = "R"
                        ElseIf clsCommon.CompairString(strtermstype.ToUpper(), "CAD") = CompairStringResult.Equal Then
                            obj.TermsType = "C"
                        ElseIf clsCommon.CompairString(strtermstype.ToUpper(), "CIF") = CompairStringResult.Equal Then
                            obj.TermsType = "CI"
                        Else
                            Throw New Exception("Sale Type is not correct At Line No. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    obj.Code = strTermsCode
                    obj.Description = strTermsdescription

                    If clsCommon.myLen(strTermsCode) > 0 AndAlso clsDBFuncationality.getSingleValue("Select count(*) from TSPL_PAYMENT_TERMS_MASTER_MT where Code='" + strTermsCode + "' ", trans) > 0 Then
                        IsNewEntry = False
                    Else
                        IsNewEntry = True

                    End If

                    Dim coll As New Hashtable()
                    clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
                    clsCommon.AddColumnsForChange(coll, "TermsType", obj.TermsType, True)
                    clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
                    clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
                    clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                    If IsNewEntry Then
                        clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                        clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                        clsCommon.AddColumnsForChange(coll, "Code", obj.Code.ToUpper())
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PAYMENT_TERMS_MASTER_MT", OMInsertOrUpdate.Insert, "", trans)
                    Else
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PAYMENT_TERMS_MASTER_MT", OMInsertOrUpdate.Update, "TSPL_PAYMENT_TERMS_MASTER_MT.Code='" + obj.Code + "'", trans)
                    End If

                Next
                trans.Commit()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                trans.Rollback()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub
End Class
