'--------Created By Richa 21/08/2014 Against Ticket No BM00000003438
'updation by richa agarwal against ticket no BM00000003766
Imports common
Imports System.Data.SqlClient
Imports common.Controls
Public Class FrmReceivableSettings
    Inherits FrmMainTranScreen
    Dim userCode, companyCode As String
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False

    Private Sub rdbtnclose_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles rdbtnclose.Click
        Me.Close()
        GC.Collect()
    End Sub

    Private Sub FrmReceivableSettings_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso rdbtnsave.Enabled AndAlso MyBase.isModifyFlag Then
            SaveData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            Me.Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            Reset()
        End If
    End Sub

    Private Sub FrmReceivableSettings_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        SetUserMgmtNew()
        isNewEntry = True
        ButtonToolTip.SetToolTip(rdbtnsave, "Press Alt+S for Save")
        ButtonToolTip.SetToolTip(rdbtnclose, "Press Alt+C Close the Window")
        SetControlsTag()
        LoadData()
    End Sub
    Sub SetControlsTag()

        chkshowsaletypeinpaymenttermsReceivable.Tag1 = clsFixedParameterCode.AllowToShowSaleTypeinPaymentTermsReceivable
        chkshowsaletypeinpaymenttermsReceivable.Tag = clsFixedParameterType.AllowToShowSaleTypeinPaymentTermsReceivable
        '' Anubhooti 03-Sep-2014
        ChkAllowAutoCustCode.Tag1 = clsFixedParameterCode.AutoGeneratedCustomerCode
        ChkAllowAutoCustCode.Tag = clsFixedParameterType.AutoGeneratedCustomerCode

        chkAllowCustomerGrpDetailMandatory.Tag1 = clsFixedParameterCode.IsCustomerGroupFieldsMandatory
        chkAllowCustomerGrpDetailMandatory.Tag = clsFixedParameterType.IsCustomerGroupFieldsMandatory

        chkAllowCustomerGrpDetailMandatory.Tag1 = clsFixedParameterCode.IsCustomerGroupFieldsMandatory
        chkAllowCustomerGrpDetailMandatory.Tag = clsFixedParameterType.IsCustomerGroupFieldsMandatory

        chkDoNotMergeAccountOfAPAR.Tag1 = clsFixedParameterCode.DoNotMergeAPARAccount
        chkDoNotMergeAccountOfAPAR.Tag = clsFixedParameterType.DoNotMergeAPARAccount

        CHKShowVisiDetail.Tag1 = clsFixedParameterCode.ShowVisiDetail
        CHKShowVisiDetail.Tag = clsFixedParameterType.ShowVisiDetail

        chkCustomerNameUnique.Tag1 = clsFixedParameterCode.CustomerNameUniqueOnCM
        chkCustomerNameUnique.Tag = clsFixedParameterType.CustomerNameUniqueOnCM
    End Sub
#Region "Functions"

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.FrmReceivableSettings)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
        End If
        rdbtnsave.Visible = MyBase.isModifyFlag

    End Sub
    Sub LoadData()
        Try

            For Each ctrl As Control In RadGroupBox1.Controls
                If ctrl.GetType Is GetType(MyCheckBox) Then
                    Dim chkBox As MyCheckBox = TryCast(ctrl, MyCheckBox)
                    If clsCommon.myLen(chkBox.Tag) >= 0 AndAlso clsCommon.myLen(chkBox.Tag1) >= 0 Then
                        chkBox.Checked = IIf(clsCommon.myCdbl(clsFixedParameter.GetData(chkBox.Tag, chkBox.Tag1, Nothing)) = 1, True, False)
                        '' Anubhooti 08-Oct-2014
                        If clsCommon.CompairString(ChkAllowAutoCustCode.Checked, "True") = CompairStringResult.Equal Then
                            txtdigits.Enabled = True
                            txtdigits.Value = clsCommon.myCdbl(clsFixedParameter.GetData(clsFixedParameterType.AutoGeneratedDigitsForCustomer, clsFixedParameterCode.AutoGeneratedDigitsForCustomer, Nothing))
                        Else
                            txtdigits.Enabled = False
                        End If
                    End If
                End If
            Next

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Sub SaveData()
        If MyBase.isModifyonPasswordFlag Then
            If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.FrmReceivableSettings, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
            Else
                Return
            End If
        End If
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try

            For Each ctrl As Control In RadGroupBox1.Controls
                If ctrl.GetType Is GetType(MyCheckBox) Then
                    Dim chkBox As MyCheckBox = TryCast(ctrl, MyCheckBox)
                    If clsCommon.myLen(chkBox.Tag) >= 0 AndAlso clsCommon.myLen(chkBox.Tag1) >= 0 Then
                        clsFixedParameter.UpdateData(chkBox.Tag, chkBox.Tag1, IIf(chkBox.Checked, "1", "0"), trans)
                    End If
                    '' Anubhooti 08-Oct-2014
                    If clsCommon.myLen(txtdigits.Value) > 0 Then
                        clsDBFuncationality.ExecuteNonQuery("UPDATE TSPL_FIXED_PARAMETER SET Description=" & clsCommon.myCdbl(txtdigits.Value) & " WHERE CODE ='AutoGeneratedDigitsForCustomer' AND TYPE ='AutoGeneratedDigitsForCustomer'", trans)
                    End If
                End If
            Next

            trans.Commit()
            clsCommon.MyMessageBoxShow(Me, "Data saved Successfully", Me.Text)

        Catch ex As Exception
            trans.Rollback()
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

#End Region

    Private Sub rdbtnsave_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles rdbtnsave.Click
        SaveData()
    End Sub

    Private Sub ChkAllowAutoCustCode_CheckStateChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ChkAllowAutoCustCode.CheckStateChanged
        If ChkAllowAutoCustCode.Checked = True Then
            txtdigits.Enabled = True
        Else
            txtdigits.Enabled = False
            txtdigits.Value = 0
        End If
    End Sub
End Class
