'--------Created By Richa 20/08/2014 Against Ticket No BM00000003438

Imports common
Imports System.Data.SqlClient
Public Class FrmReceivablePaymentTerms
    Inherits FrmMainTranScreen
#Region "Variables"


    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String
    Const colSelect As String = "SELECT"
    Const colCompCode As String = "COMPCODE"
    Const colCompName As String = "COMPNAME"
    Const colDataBaseName As String = "DATABASE"
#End Region
#Region "User Defined Functions and Subroutines"

    Public Sub New()
        InitializeComponent()
    End Sub
#End Region

    Private Sub FrmReceivablePaymentTerms_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            closeform()

        ElseIf e.Alt And e.KeyCode = Keys.N Then
            Reset()
        End If
    End Sub
    Public Sub closeform()
        Me.Close()
        GC.Collect()
    End Sub
    Private Sub FrmReceivablePaymentTerms_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        Reset()
        LoadSaleType()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S/U for Save/Update Transaction")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D for Delete Transaction")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnreset, "Press Alt+N for New Transaction")
    End Sub
    Sub SaveData()
        'Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            If AllowToSave() Then
                If MyBase.isModifyonPasswordFlag Then
                    If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.FrmReceivablePaymentTerms, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                    Else
                        Return
                    End If
                End If
                Dim obj As New ClsReceivablePaymentTerms()
                obj.Terms_Code = fndtermscode.Value
                obj.Terms_Desc = txt_desc.Text
                obj.No_Days = clsCommon.myCdbl(txtNoofDays.Value)
                obj.SaleType = clsCommon.myCstr(cboSaleType.SelectedValue)


                If (ClsReceivablePaymentTerms.SaveData(obj, isNewEntry)) Then
                    clsCommon.MyMessageBoxShow("Data saved Successfully", Me.Text)
                    LoadData(obj.Terms_Code, NavigatorType.Current)
                End If
            End If
        Catch ex As Exception

            clsCommon.MyMessageBoxShow(ex.Message, Me.Text)
        End Try
    End Sub
    Private Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(fndtermscode.Value) <= 0 Then
                fndtermscode.Focus()
                Throw New Exception("Terms Code cannot be left blank.")
            End If
        End If
        If clsCommon.myCstr(txt_desc.Text) = "" Then
            txt_desc.Focus()
            Throw New Exception("Terms Description cannot be left blank.")
        End If
        If clsCommon.myCdbl(txtNoofDays.Value) <= 0 Then
            txtNoofDays.Focus()
            Throw New Exception("No of days cannot be zero or blank")
        End If
        Return True
    End Function
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Dim obj As ClsReceivablePaymentTerms = ClsReceivablePaymentTerms.GetData(strCode, NavTyep)
        If obj IsNot Nothing Then
            isNewEntry = False
            fndtermscode.Value = obj.Terms_Code
            txt_desc.Text = obj.Terms_Desc
            txtNoofDays.Value = obj.No_Days
           
            If clsCommon.myLen(obj.SaleType) > 0 Then
                If obj.SaleType = "B" Then
                    cboSaleType.Text = "BULK"
                ElseIf obj.SaleType = "F" Then
                    cboSaleType.Text = "FRESH"
                ElseIf obj.SaleType = "E" Then
                    cboSaleType.Text = "EXPORT"
                ElseIf obj.SaleType = "P" Then
                    cboSaleType.Text = "PRODUCT"
                ElseIf obj.SaleType = "O" Then
                    cboSaleType.Text = "OTHER"
                End If
            Else
                cboSaleType.Text = "SELECT"
            End If
            fndtermscode.MyReadOnly = True
            btnsave.Text = "Update"
            btndelete.Enabled = True
        Else
            Reset()

        End If
    End Sub
    Private Sub DeleteData()
        Try
            If (deleteConfirm()) Then
                If (ClsReceivablePaymentTerms.DeleteData(fndtermscode.Value)) Then
                    common.clsCommon.MyMessageBoxShow("Data deleted successfully ")
                    Reset()
                End If
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.FrmReceivablePaymentTerms)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")

        End If
        btnsave.Visible = MyBase.isModifyFlag

        'If btnsave.Visible = True Then
        '    RmExport.Enabled = True
        '    RmImport.Enabled = True
        'Else
        '    RmExport.Enabled = False
        '    RmImport.Enabled = False
        'End If

        btndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Sub LoadSaleType()
        Dim dt As New DataTable
        dt.Columns.Add("Code", GetType(String))
        dt.Columns.Add("Name", GetType(String))
        dt.Rows.Add("", "SELECT")
        dt.Rows.Add("B", "BULK")
        dt.Rows.Add("F", "FRESH")
        dt.Rows.Add("E", "EXPORT")
        dt.Rows.Add("P", "PRODUCT")
        dt.Rows.Add("C", "CSA")
        dt.Rows.Add("O", "OTHER")

        cboSaleType.DataSource = dt
        cboSaleType.ValueMember = "Code"
        cboSaleType.DisplayMember = "Name"
    End Sub

    Sub Reset()

        fndtermscode.Value = ""
        txtNoofDays.Value = 0
        txt_desc.Text = ""
        fndtermscode.MyReadOnly = False
        btnsave.Text = "Save"
        btndelete.Enabled = False
        SetDataBaseGrid()
        isNewEntry = True
        Dim desc As String = ""
        desc = clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowToShowSaleTypeinPaymentTermsReceivable, clsFixedParameterCode.AllowToShowSaleTypeinPaymentTermsReceivable, Nothing))
        If clsCommon.CompairString(desc, "1") = CompairStringResult.Equal Then
            lblSaleType.Visible = True
            cboSaleType.Visible = True
        Else
            lblSaleType.Visible = False
            cboSaleType.Visible = False

        End If
        cboSaleType.Text = "SELECT"
    End Sub
    Sub SetDataBaseGrid()
        gvDB.Rows.Clear()
        gvDB.Columns.Clear()

        Dim repoSelect As GridViewCheckBoxColumn = New GridViewCheckBoxColumn()
        repoSelect.FormatString = ""
        repoSelect.HeaderText = "Select"
        repoSelect.Name = colSelect
        repoSelect.Width = 50
        repoSelect.ReadOnly = False
        repoSelect.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
        gvDB.MasterTemplate.Columns.Add(repoSelect)

        Dim repoCompCode As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoCompCode.FormatString = ""
        repoCompCode.HeaderText = "Company Code"
        repoCompCode.Name = colCompCode
        repoCompCode.Width = 150
        repoCompCode.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoCompCode)

        Dim repoCompName As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoCompName.FormatString = ""
        repoCompName.HeaderText = "Company Name"
        repoCompName.Name = colCompName
        repoCompName.Width = 150
        repoCompName.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoCompName)

        Dim repoDB As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoDB.FormatString = ""
        repoDB.HeaderText = "Database Name"
        repoDB.Name = colDataBaseName
        repoDB.IsVisible = False
        repoDB.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoDB)

        Dim qry As String = "SELECT Comp_Code,Comp_Name,DataBase_Name from TSPL_COMPANY_MASTER where len(isnull(DataBase_Name,''))>0 and Comp_Code not in ('" + objCommonVar.CurrentCompanyCode + "')"
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            For Each dr As DataRow In dt.Rows
                gvDB.Rows.AddNew()
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colSelect).Value = False
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colCompCode).Value = clsCommon.myCstr(dr("Comp_Code"))
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colCompName).Value = clsCommon.myCstr(dr("Comp_Name"))
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colDataBaseName).Value = clsCommon.myCstr(dr("DataBase_Name"))
            Next
        End If
    End Sub

    Private Sub btnsave_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnsave.Click
        SaveData()
    End Sub

    Private Sub btndelete_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub

    Private Sub btnclose_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnclose.Click
        closeform()
    End Sub

    Private Sub btnreset_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnreset.Click
        Reset()
    End Sub

    Private Sub fnd_termscode__MYNavigator(ByVal sender As Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndtermscode._MYNavigator
        Try
            LoadData(fndtermscode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message)
        End Try

    End Sub

    Private Sub fnd_termscode__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndtermscode._MYValidating
        Dim str As String = "select count(*) from TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER where Terms_Code ='" + fndtermscode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            fndtermscode.MyReadOnly = False
        Else
            fndtermscode.MyReadOnly = True
        End If
        If fndtermscode.MyReadOnly OrElse isButtonClicked Then
            fndtermscode.Value = ClsReceivablePaymentTerms.getFinder("", fndtermscode.Value, isButtonClicked)
            If fndtermscode.Value <> "" Then
                LoadData(fndtermscode.Value, NavigatorType.Current)
            Else
                Reset()
            End If
        End If
    End Sub

    Private Sub Export_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Export.Click
        Dim str As String
        str = "select Terms_Code as [Terms Code],Terms_Desc as [Terms Description],No_Days as [No of Days],CASE WHEN TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER.SaleType='E' THEN 'EXPORT' WHEN TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER.SaleType='B' THEN 'BULK' WHEN TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER.SaleType='F' THEN 'FRESH' WHEN TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER.SaleType='P' THEN 'PRODUCT' WHEN TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER.SaleType='O' THEN 'OTHER' ELSE '' END AS [Sale Type] from TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER"
        transportSql.ExporttoExcel(str, Me)
    End Sub

    Private Sub Import_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Import.Click
        Dim gv As New RadGridView()
        Dim IsNewEntry As Boolean
        Dim trans As SqlTransaction = Nothing
        Me.Controls.Add(gv)

        If transportSql.importExcel(gv, "Terms Code", "Terms Description", "No of Days", "Sale Type") Then
            Dim linno As Integer = 1
            Try
                trans = clsDBFuncationality.GetTransactin()
                connectSql.OpenConnection()


                For Each grow As GridViewRowInfo In gv.Rows

                    Dim obj As New ClsReceivablePaymentTerms()

                    Dim strTermsCode As String = clsCommon.myCstr(grow.Cells("Terms Code").Value)
                    Dim strTermsdescription As String = clsCommon.myCstr(grow.Cells("Terms Description").Value)
                    Dim Dblnoofdays As Double = clsCommon.myCdbl(grow.Cells("No of Days").Value)
                    Dim strsaletype As String = clsCommon.myCstr(grow.Cells("Sale Type").Value)
                   

                    linno += 1

                    If strTermsCode = String.Empty Then
                        Throw New Exception("Terms Code cannot be left blank at Line No. " + clsCommon.myCstr(linno) + ".")
                    End If

                    If strTermsdescription = String.Empty Then
                        Throw New Exception("Terms Description cannot be left blank at Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                 
                    If strTermsCode.Length > 12 Then
                        common.clsCommon.MyMessageBoxShow("Terms Code length cannot be more than 12")
                        trans.Rollback()
                        Exit Sub
                    End If
                    If strTermsdescription.Length > 500 Then
                        common.clsCommon.MyMessageBoxShow("Terms Description length cannot be more than 500")
                        trans.Rollback()
                        Exit Sub
                    End If


                    If clsCommon.myCdbl(Dblnoofdays) <= 0 Then
                        Throw New Exception("No of days should not be left blank or zero At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If

                    If clsCommon.myLen(strsaletype) > 0 Then
                        If clsCommon.CompairString(strsaletype.ToUpper(), "FRESH") = CompairStringResult.Equal Then
                            obj.SaleType = "F"
                        ElseIf clsCommon.CompairString(strsaletype.ToUpper(), "BULK") = CompairStringResult.Equal Then
                            obj.SaleType = "B"
                        ElseIf clsCommon.CompairString(strsaletype.ToUpper(), "PRODUCT") = CompairStringResult.Equal Then
                            obj.SaleType = "P"
                        ElseIf clsCommon.CompairString(strsaletype.ToUpper(), "OTHER") = CompairStringResult.Equal Then
                            obj.SaleType = "O"
                        ElseIf clsCommon.CompairString(strsaletype.ToUpper(), "EXPORT") = CompairStringResult.Equal Then
                            obj.SaleType = "E"
                        Else
                            Throw New Exception("Sale Type is not correct At Line No. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    obj.Terms_Code = strTermsCode
                    obj.Terms_Desc = strTermsdescription
                    obj.No_Days = Dblnoofdays

                    If clsCommon.myLen(strTermsCode) > 0 AndAlso clsDBFuncationality.getSingleValue("Select count(*) from TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER where Terms_Code='" + strTermsCode + "' ", trans) > 0 Then
                        IsNewEntry = False
                    Else
                        IsNewEntry = True

                    End If

                    Dim coll As New Hashtable()
                    clsCommon.AddColumnsForChange(coll, "Terms_Desc", obj.Terms_Desc)
                    clsCommon.AddColumnsForChange(coll, "No_Days", obj.No_Days)
                    clsCommon.AddColumnsForChange(coll, "SaleType", obj.SaleType, True)
                    clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
                    clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
                    clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                    If IsNewEntry Then
                        clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                        clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                        clsCommon.AddColumnsForChange(coll, "Terms_Code", obj.Terms_Code.ToUpper())
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER", OMInsertOrUpdate.Insert, "", trans)
                    Else
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER", OMInsertOrUpdate.Update, "TSPL_RECEIVABLE_PAYMENT_TERMS_MASTER.Terms_Code='" + obj.Terms_Code + "'", trans)
                    End If

                Next
                trans.Commit()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                trans.Rollback()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub


End Class
