Imports common
Imports System.Data.SqlClient
Imports System

Public Class FrmHirerachyLevelMaster
    Inherits FrmMainTranScreen

#Region "Variables"
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim HirerachyLevel As String = Nothing
    Dim EnableHirerachyCostCentre As Double = 0
#End Region

#Region "Functions"
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.FrmHirerachyLevelMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
        End If
        btnSave.Visible = MyBase.isModifyFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub
    Sub Reset()
        HirerachyLevel = ""
        txtCode.Value = ""
        txtDesc.Text = ""
        cmblevel.SelectedIndex = 0
        cmblevel.Text = "1"
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = False
        txtCode.MyReadOnly = False

        txtCode.Focus()
        txtCode.Select()
    End Sub
    Function AllowToSave() As Boolean
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
                If clsCommon.myLen(txtCode.Value) <= 0 Then
                    clsCommon.MyMessageBoxShow(Me, "Please fill Code", Me.Text)
                    txtCode.Focus()
                    txtCode.Select()
                    Return False
                End If
            End If
            If clsCommon.myLen(txtDesc.Text) <= 0 Then
                clsCommon.MyMessageBoxShow(Me, "Please fill description", Me.Text)
                txtDesc.Focus()
                txtDesc.Select()
                Return False
            End If
            If clsCommon.myLen(cmblevel.Text) <= 0 Then
                clsCommon.MyMessageBoxShow(Me, "Please select level", Me.Text)
                cmblevel.Focus()
                cmblevel.Select()
                Return False
            End If
            If clsCommon.CompairString(cmblevel.Text, HirerachyLevel) <> CompairStringResult.Equal Then
                If clsCommon.myCdbl(clsDBFuncationality.getSingleValue("select count(level) as LevelCount from TSPL_HIRERACHY_LEVEL_MASTER where level='" + cmblevel.Text + "'")) > 0 Then
                    clsCommon.MyMessageBoxShow(Me, "Level is Already Used with Other Hirerachy Code", Me.Text)
                    cmblevel.Focus()
                    cmblevel.Select()
                    Return False
                End If
            End If
            If clsCommon.CompairString(cmblevel.Text, HirerachyLevel) <> CompairStringResult.Equal Then
                Dim Qry As String = Nothing
                If EnableHirerachyCostCentre = 0 Then
                    Qry = "select count(Hirerachy_Level_Code) as HLC_Count  from TSPL_COST_CENTRE_FINANCIAL WHERE Hirerachy_Level_Code='" + txtCode.Value + "' and Hirerachy_Level ='" + HirerachyLevel + "'"
                Else
                    Qry = "select count(Hirerachy_Level_Code) as HLC_Count  from TSPL_COST_CENTRE_FINANCIAL_DETAIL WHERE Hirerachy_Level_Code='" + txtCode.Value + "' and Hirerachy_Level ='" + HirerachyLevel + "'"
                End If
                Dim CheckHirerchyLCode As Double = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(Qry))
                If CheckHirerchyLCode > 0 Then
                    clsCommon.MyMessageBoxShow(Me, "Level is in Use So you can not Update", Me.Text)
                    cmblevel.Focus()
                    cmblevel.Select()
                    Return False
                End If
            End If

            Return True
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Function
    Sub SaveData()
        Try
            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.FrmHirerachyLevelMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            Dim obj As New ClsHirerachyLevelMaster()

            obj.HIRERACHY_CODE = clsCommon.myCstr(txtCode.Value)
            obj.Description = clsCommon.myCstr(txtDesc.Text).Replace("'", "`")
            obj.Level = clsCommon.myCstr(cmblevel.Text)
            If ClsHirerachyLevelMaster.SaveData(obj, txtCode.Value) Then
                clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                btnSave.Text = "Update"
                btnDelete.Enabled = True
                txtCode.Value = obj.HIRERACHY_CODE
                LoadData(txtCode.Value, NavigatorType.Current)
                txtCode.MyReadOnly = True
            Else
                txtCode.MyReadOnly = False
                btnSave.Text = "Save"
                btnDelete.Enabled = False
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Public Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Try
            Dim obj As New ClsHirerachyLevelMaster()
            txtCode.Value = strCode
            obj = ClsHirerachyLevelMaster.GetData(strCode, NavTyep)

            If obj IsNot Nothing AndAlso clsCommon.myLen(obj.HIRERACHY_CODE) > 0 Then
                txtCode.Value = obj.HIRERACHY_CODE
                txtDesc.Text = obj.Description
                cmblevel.Text = obj.Level
                HirerachyLevel = obj.Level
                txtCode.MyReadOnly = True
                btnSave.Text = "Update"
                btnDelete.Enabled = True
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Private Sub DeleteData()
        '    If clsCommon.myLen(txtCode.Value) <= 0 Then
        '        clsCommon.MyMessageBoxShow("Please select code for deletion", Me.Text)
        '        Return
        '    End If

        '    Dim qry As String = "SELECT Count(*) FROM TSPL_HIRERACHY_LEVEL_MASTER WHERE HIRERACHY_CODE= '" & txtCode.Value & "'"
        '    Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
        '    If check > 0 Then
        '        If Not (common.clsCommon.MyMessageBoxShow("Delete hirerachy code " + txtCode.Value + "" + Environment.NewLine + "Are you sure?", Me.Text, MessageBoxButtons.YesNo, RadMessageIcon.Question) = DialogResult.Yes) Then
        '            Return
        '        End If
        '        qry = "DELETE FROM TSPL_HIRERACHY_LEVEL_MASTER WHERE HIRERACHY_CODE='" + txtCode.Value + "'"
        '        clsDBFuncationality.ExecuteNonQuery(qry)
        '        Reset()
        '    Else
        '        clsCommon.MyMessageBoxShow("No Record Found For Deletion", Me.Text)
        '    End If
        Try
            If (deleteConfirm()) Then
                If (ClsHirerachyLevelMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    Reset()
                End If
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
#End Region
#Region "Events"
    Private Sub btnSave_Click(sender As Object, e As EventArgs) Handles btnSave.Click
        If AllowToSave() Then
            SaveData()
        End If
    End Sub

    Private Sub btnDelete_Click(sender As Object, e As EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Private Sub btnClose_Click(sender As Object, e As EventArgs) Handles btnClose.Click
        Me.Close()
        GC.Collect()
    End Sub

    Private Sub FrmHirerachyLevelMaster_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N Then
            Reset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            If AllowToSave() Then
                SaveData()
            End If
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            deletedata()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C AndAlso btnClose.Enabled Then
            Me.Close()
            GC.Collect()
        End If
    End Sub
    Private Sub FrmHirerachyLevelMaster_Load(sender As Object, e As EventArgs) Handles Me.Load
        SetUserMgmtNew()
        EnableHirerachyCostCentre = clsCommon.myCdbl(clsFixedParameter.GetData(clsFixedParameterType.EnableHirerachyCostCentre, clsFixedParameterCode.EnableHirerachyCostCentre, Nothing))
        Reset()
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
    End Sub
    Private Sub txtCode__MYNavigator(sender As Object, e As EventArgs, NavType As NavigatorType) Handles txtCode._MYNavigator
        Try
            Dim qry As String = "select count(*) from TSPL_HIRERACHY_LEVEL_MASTER where HIRERACHY_CODE='" + txtCode.Value + "'"
            Dim check As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qry))
            If check > 0 Then
                txtCode.MyReadOnly = True
            ElseIf check <= 0 Then
                txtCode.MyReadOnly = False
            End If
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub txtCode__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtCode._MYValidating
        Try
            Dim str As String = "select count(*) from TSPL_HIRERACHY_LEVEL_MASTER where HIRERACHY_CODE ='" + txtCode.Value + "' "
            Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
            If no = 0 Then
                txtCode.MyReadOnly = False
            Else
                txtCode.MyReadOnly = True
            End If
            If txtCode.MyReadOnly OrElse isButtonClicked Then

                txtCode.Value = ClsHirerachyLevelMaster.getFinder("", txtCode.Value, isButtonClicked)
                If clsCommon.myLen(txtCode.Value) > 0 Then
                    btnDelete.Enabled = True
                    btnSave.Text = "Update"
                    txtCode.MyReadOnly = True
                Else
                    btnSave.Text = "Save"
                    btnDelete.Enabled = False
                    txtCode.MyReadOnly = False
                End If
            End If
            LoadData(txtCode.Value, NavigatorType.Current)
        Catch ex As Exception
        End Try
    End Sub

    Private Sub rmImport_Click(sender As Object, e As EventArgs) Handles rmImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        Dim linno As Integer = 0

        If transportSql.importExcel(gv, "Code", "Description", "Level") Then

            Try
                clsCommon.ProgressBarPercentShow()

                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New ClsHirerachyLevelMaster()
                    linno += 1
                    ' clsCommon.ProgressBarPercentUpdate((linno * 100) / gv.RowCount - 1, "Importing " + clsCommon.myCstr(linno) + "/" + clsCommon.myCstr(gv.RowCount - 1))
                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value.ToString().Replace("'", ""))
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect at line no. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.HIRERACHY_CODE = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells(1).Value.ToString().Replace("'", ""))
                    If strName.Length > 150 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Description can not be blank or incorrect at line no. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Description = strName

                    Dim strLevel As String = clsCommon.myCstr(grow.Cells(2).Value)
                    If clsCommon.myLen(strLevel) > 0 Then
                        If (clsCommon.CompairString(strLevel, "1") <> CompairStringResult.Equal) AndAlso (clsCommon.CompairString(strLevel, "2") <> CompairStringResult.Equal) AndAlso (clsCommon.CompairString(strLevel, "3") <> CompairStringResult.Equal) AndAlso (clsCommon.CompairString(strLevel, "4") <> CompairStringResult.Equal) AndAlso (clsCommon.CompairString(strLevel, "5") <> CompairStringResult.Equal) AndAlso (clsCommon.CompairString(strLevel, "6") <> CompairStringResult.Equal) AndAlso (clsCommon.CompairString(strLevel, "7") <> CompairStringResult.Equal) AndAlso (clsCommon.CompairString(strLevel, "8") <> CompairStringResult.Equal) AndAlso (clsCommon.CompairString(strLevel, "9") <> CompairStringResult.Equal) AndAlso (clsCommon.CompairString(strLevel, "10") <> CompairStringResult.Equal) Then
                            Throw New Exception("Level should be from '1' to '10' range at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    Else
                        Throw New Exception("Level can not be blank.")
                    End If
                    obj.Level = strLevel

                    ClsHirerachyLevelMaster.SaveData(obj, obj.HIRERACHY_CODE)
                Next
                clsCommon.ProgressBarPercentHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarPercentHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub rmExport_Click(sender As Object, e As EventArgs) Handles rmExport.Click
        Dim str As String
        str = "select HIRERACHY_CODE AS Code, Description as [Description],Level from TSPL_HIRERACHY_LEVEL_MASTER"
        transportSql.ExporttoExcel(str, Me)
    End Sub

    Private Sub btnNew_Click(sender As Object, e As EventArgs) Handles btnNew.Click
        Reset()
    End Sub
#End Region
End Class
