'--------Created By Anubhooti 02-Sep-2014 Against Ticket No BM00000003425
Imports common
Imports System.Data.SqlClient
Imports common.Controls

Public Class FrmPayableSettings
    Inherits FrmMainTranScreen
    Dim userCode, companyCode As String
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False

#Region "Events"
    Private Sub FrmPayableSettings_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso rdbtnsave.Enabled Then
            SaveData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            Me.Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            Reset()
        End If
    End Sub

    Private Sub FrmPayableSettings_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        SetUserMgmtNew()
        isNewEntry = True
        ButtonToolTip.SetToolTip(rdbtnsave, "Press Alt+S for Save")
        ButtonToolTip.SetToolTip(rdbtnclose, "Press Alt+C Close the Window")
        SetControlsTag()
        LoadData()
    End Sub

    Private Sub rdbtnsave_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles rdbtnsave.Click
        SaveData()
    End Sub

    Private Sub rdbtnclose_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles rdbtnclose.Click
        Me.Close()
        GC.Collect()
    End Sub
#End Region
#Region "Functions"
    Sub SetControlsTag()
        chkAutoGenerateVCode.Tag1 = clsFixedParameterCode.AutoGeneratedVendorCode
        chkAutoGenerateVCode.Tag = clsFixedParameterType.AutoGeneratedVendorCode

        ChkAllowMandFields.Tag1 = clsFixedParameterCode.AllowFieldsToBeManadatory
        ChkAllowMandFields.Tag = clsFixedParameterType.AllowFieldsToBeManadatory

        chkAllowVendorGrpDetailMandatory.Tag1 = clsFixedParameterCode.IsVendorGroupFieldsMandatory
        chkAllowVendorGrpDetailMandatory.Tag = clsFixedParameterType.IsVendorGroupFieldsMandatory
        chkPayVoucherAddressOnBankBasis.Tag1 = clsFixedParameterCode.AddressOnPaymentVoucherOnBankBasis
        chkPayVoucherAddressOnBankBasis.Tag = clsFixedParameterType.AddressOnPaymentVoucher
        'richa agarwal 17/03/2015 against ticket no BM00000005874
        chkManualEntryofBankDetailsinVM.Tag1 = clsFixedParameterCode.AllowBankDetailsManualinVM
        chkManualEntryofBankDetailsinVM.Tag = clsFixedParameterType.AllowBankDetailsManualinVM
        '===================Preeti Gupta Against Ticket no [BM00000009038]
        ChkShowCostCenterAndHierarchyLevelInAPInvoiceEntry.Tag1 = clsFixedParameterCode.ShowHierarchyAndCostCenterInAPInvoiceEntry
        ChkShowCostCenterAndHierarchyLevelInAPInvoiceEntry.Tag = clsFixedParameterType.ShowHierarchyAndCostCenterInAPInvoiceEntry
    End Sub
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.FrmPayableSettings)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
        End If
        rdbtnsave.Visible = MyBase.isModifyFlag
    End Sub
    Sub LoadData()
        Try
            For Each ctrl As Control In RadGroupBox1.Controls
                If ctrl.GetType Is GetType(MyCheckBox) Then
                    Dim chkBox As MyCheckBox = TryCast(ctrl, MyCheckBox)
                    If clsCommon.myLen(chkBox.Tag) >= 0 AndAlso clsCommon.myLen(chkBox.Tag1) >= 0 Then
                        chkBox.Checked = IIf(clsCommon.myCdbl(clsFixedParameter.GetData(chkBox.Tag, chkBox.Tag1, Nothing)) = 1, True, False)
                        '' Anubhooti 08-Oct-2014
                        If clsCommon.CompairString(chkAutoGenerateVCode.Checked, "True") = CompairStringResult.Equal Then
                            txtdigits.Enabled = True
                            txtdigits.Value = clsCommon.myCdbl(clsFixedParameter.GetData(clsFixedParameterType.AutoGeneratedDigitsForVendor, clsFixedParameterCode.AutoGeneratedDigitsForVendor, Nothing))
                        Else
                            txtdigits.Enabled = False
                        End If
                    End If
                End If
            Next
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Sub SaveData()
        If MyBase.isModifyonPasswordFlag Then
            If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.FrmPayableSettings, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
            Else
                Return
            End If
        End If
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            For Each ctrl As Control In RadGroupBox1.Controls
                If ctrl.GetType Is GetType(MyCheckBox) Then
                    Dim chkBox As MyCheckBox = TryCast(ctrl, MyCheckBox)
                    If clsCommon.myLen(chkBox.Tag) >= 0 AndAlso clsCommon.myLen(chkBox.Tag1) >= 0 Then
                        clsFixedParameter.UpdateData(chkBox.Tag, chkBox.Tag1, IIf(chkBox.Checked, "1", "0"), trans)
                    End If
                    '' Anubhooti 08-Oct-2014
                    If clsCommon.myLen(txtdigits.Value) > 0 Then
                        clsDBFuncationality.ExecuteNonQuery("UPDATE TSPL_FIXED_PARAMETER SET Description=" & clsCommon.myCdbl(txtdigits.Value) & " WHERE CODE ='AutoGeneratedDigitsForVendor' AND TYPE ='AutoGeneratedDigitsForVendor'", trans)
                    End If
                End If
            Next
            trans.Commit()
            clsCommon.MyMessageBoxShow(Me, "Data saved Successfully", Me.Text)
        Catch ex As Exception
            trans.Rollback()
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
#End Region

    Private Sub chkAutoGenerateVCode_CheckStateChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles chkAutoGenerateVCode.CheckStateChanged
        If chkAutoGenerateVCode.Checked = True Then
            txtdigits.Enabled = True
        Else
            txtdigits.Enabled = False
            txtdigits.Value = 0
        End If
    End Sub

   
End Class
