Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports System.Data
Imports System.Data.SqlClient
Imports System.Windows.Forms
Imports System.Configuration
Imports Telerik.Collections.Generic
Imports Excel = Microsoft.Office.Interop.Excel
Imports common
Public Class frmVendorType
    Inherits FrmMainTranScreen
    Dim userCode, companyCode As String
    Dim ButtonToolTip As ToolTip = New ToolTip()

    'This Cunstructer is used to send usercode and compcode data in table.
    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub
    Dim dr As SqlDataReader
    Private Sub frmVendorType_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        ' fndvendorid.Value.MaxLength = 12
        SetUserMgmtNew()
        text_changed()
        'fndvendorid.Value.CharacterCasing = CharacterCasing.Upper
        ' AddHandler fndvendorid.Value.KeyPress, AddressOf KeyPress1
        '   AddHandler fndvendorid.ValueChanged, AddressOf text_changed
        rdbtnDelete.Enabled = False
        ' globalFunc.mandatoryText(fndvendorid .Value)
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
        ButtonToolTip.SetToolTip(rdbtnSave, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(rdbtnDelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(rdbtnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(rdbtnreset, "Press Alt+N Adding New Trasnaction")
    End Sub
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt("VEN-TYPE")
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        rdbtnSave.Visible = MyBase.isModifyFlag
        'btnPost.Visible = MyBase.isPostFlag
        rdbtnDelete.Visible = MyBase.isDeleteFlag
    End Sub
    Private Sub KeyPress1(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If
    End Sub
    Private Sub text_changed()
        Dim var As String
        var = clsDBFuncationality.getSingleValue("select ven_type_code from tspl_vendor_type_master where ven_type_code='" + fndvendorid.Value + "'")

       
        If clsCommon.CompairString(var, fndvendorid.Value) <> CompairStringResult.Equal Then
            rdtxtvendordesc.Text = ""
            rdbtnSave.Text = "Save"
            rdbtnDelete.Enabled = False
                                ElseIf var <> "" Then

            funfill()
        Else
            rdtxtvendordesc.Text = ""
            rdbtnSave.Text = "Save"
            rdbtnDelete.Enabled = False
        End If
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub
    Private Sub funInsert()
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from tspl_vendor_type_master where ven_type_code='" & fndvendorid.Value & "'")
                If ChkNewEntry = 0 Then
                    fndvendorid.Value = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.VendorType, "", "")
                    If clsCommon.myLen(fndvendorid.Value) <= 0 Then
                        Throw New Exception("Error in Code Generation")
                    End If
                End If
            End If
            connectSql.RunSp("sp_vendortype_insert", New SqlParameter("@vendortype", fndvendorid.Value), New SqlParameter("@vendortypedesc", rdtxtvendordesc.Text), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate()), New SqlParameter("@ModifyBy", userCode), New SqlParameter("@ModifyDate", connectSql.serverDate()), New SqlParameter("@ComCode", companyCode))
            myMessages.insert()
            rdbtnSave.Text = "Update"
            rdbtnDelete.Enabled = True
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub rdbtnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnSave.Click
        SaveData()
    End Sub
    Sub SaveData()
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso fndvendorid.Value = "" Then
            myMessages.blankValue("Vendor Type")
            fndvendorid.Focus()
            Return
        Else
            If rdbtnSave.Text = "Save" Then
                funInsert()
            ElseIf rdbtnSave.Text = "Update" Then
                funUpdate()
            End If
        End If
    End Sub
    'update vendor Type Details
    Private Sub funUpdate()
        If fndvendorid.Value = "" Then
            myMessages.blankValue("Vendor Type")
        Else
            Try
                connectSql.RunSp("sp_vendortype_update", New SqlParameter("@vendortype", fndvendorid.Value), New SqlParameter("@vendortypedesc", rdtxtvendordesc.Text), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate()), New SqlParameter("@ModifyBy", userCode), New SqlParameter("@ModifyDate", connectSql.serverDate()), New SqlParameter("@ComCode", companyCode))
                myMessages.update()
                rdbtnSave.Text = "Update"
            Catch ex As Exception
                myMessages.myExceptions(ex)
            End Try
        End If
    End Sub
    Private Sub funReset()
        fndvendorid.Value = ""
        rdtxtvendordesc.Text = ""
        rdbtnSave.Text = "Save"
        rdbtnDelete.Enabled = False
        rdtxtvendordesc.Focus()
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub
    Private Sub funDelete()
        Try
            connectSql.RunSp("sp_vendortype_delete", New SqlParameter("@vendortype", fndvendorid.Value))
            myMessages.delete()
            rdbtnSave.Text = "Save"
            rdbtnDelete.Enabled = False
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Public Sub funfill()
        Dim dt As DataTable
        Dim query As String = "select ven_type_code ,ven_type_desc from tspl_vendor_type_master where ven_type_code='" + fndvendorid.Value() + "'"
        dt = clsDBFuncationality.GetDataTable(query)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

            For Each row As DataRow In dt.Rows
                fndvendorid.Value = row(0).ToString()
                rdtxtvendordesc.Text = row(1).ToString()
                rdbtnSave.Text = "Update"
                rdbtnDelete.Enabled = True
            Next
End if
    End Sub
    Private Sub rdbtnreset_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnreset.Click
        funReset()
    End Sub

    Private Sub rdbtnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If fndvendorid.Value <> "" Then
            If myMessages.deleteConfirm() Then
                funDelete()
            Else

            End If
        End If
    End Sub
    
    Private Sub fndvendorId_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndvendorid.ConnectionString = connectSql.SqlCon()
        'fndvendorid.Query = "select ven_Type_Code as [Vendor Type],ven_Type_Desc as [Description] from tspl_vendor_type_master"
        'fndvendorid.ValueToSelect = "Vendor Type"
        'fndvendorid.ValueToSelect1 = "Description"
        'fndvendorid.Caption = "Vendor Details"
    End Sub

    Private Sub rdmenuexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexport.Click
        Dim query As String = "select ven_Type_Code as [Vendor Type],ven_Type_Desc  as [Description] from TSPL_vendor_TYPE_MASTER "
        transportSql.ExporttoExcel(query, Me)
    End Sub

    Private Sub rdmenuimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuimport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        If transportSql.importExcel(gv, "Vendor Type", "Description") Then
            Dim trans As SqlTransaction = Nothing
            Try
                'connectSql.OpenConnection()
                trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim strvendorType As String
                    Dim strvendorTypeDesc As String
                    If String.IsNullOrEmpty(clsCommon.myCstr(grow.Cells(0).Value)) Then
                        Throw New Exception("Vendor Type can not be  Blank")
                        trans.Rollback()
                        Exit Sub
                    ElseIf clsCommon.myLen(grow.Cells(0).Value) > 12 Then
                        Throw New Exception("Vendor Type cannot be greater than 12 length.")
                        trans.Rollback()
                        Exit Sub
                    Else
                        strvendorType = grow.Cells(0).Value.ToString().ToUpper()
                    End If
                    If clsCommon.myLen(grow.Cells(1).Value) > 50 Then
                        Throw New Exception("Vendor Type Description cannot be greater than 50 length")
                        trans.Rollback()
                        Exit Sub
                    Else
                        strvendorTypeDesc = clsCommon.myCstr(grow.Cells(1).Value)
                    End If

                    Dim sql1 As String = "select COUNT(*) from TSPL_vendor_TYPE_MASTER  where Ven_Type_Code='" + strvendorType + "'"
                    Dim i As Integer = clsDBFuncationality.getSingleValue(sql1, trans)
                    If (i = 0) Then

                        connectSql.RunSpTransaction(trans, "sp_vendortype_insert", New SqlParameter("@vendortype", strvendorType), New SqlParameter("@vendorTypeDesc", strvendorTypeDesc), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate(trans)), New SqlParameter("@ModifyBy", userCode), New SqlParameter("@ModifyDate", connectSql.serverDate(trans)), New SqlParameter("@ComCode", companyCode))
                    Else
                        connectSql.RunSpTransaction(trans, "sp_vendortype_update", New SqlParameter("@vendorType", strvendorType), New SqlParameter("@vendorTypeDesc", strvendorTypeDesc), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate(trans)), New SqlParameter("@ModifyBy", userCode), New SqlParameter("@ModifyDate", connectSql.serverDate(trans)), New SqlParameter("@ComCode", companyCode))
                    End If
                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                trans.Rollback()
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)

            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub
    Private Sub rdbtnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnClose.Click
        Me.Close()
    End Sub
    'priti added on 01-06-2011 --- To implement the access control
    'Private Function funSetUserAccess() As Boolean
    '    Try
    '        'If funCheckLoginStatus() = False Then Exit Function
    '        Dim strRights As String
    '        Dim strTemp() As String
    '        Dim strProgCode = "VEN-TYPE"
    '        strRights = enuUserRights.enuRead & "," & enuUserRights.enuModify & "," & enuUserRights.enuDelete
    '        strRights = modUserMgt.funGetPermissions(strRights, strProgCode)
    '        strTemp = Split(strRights, ",")
    '        If strTemp(0) = "0" Then
    '            MsgBox("Permission Denied", MsgBoxStyle.Critical, Me.Text)
    '            funSetUserAccess = False
    '            blnRead = False
    '            Me.Close()
    '            Exit Function
    '        Else
    '            blnRead = True
    '        End If
    '        If strTemp(1) = "0" Then 'Grant modify access
    '            rdbtnSave.Enabled = False
    '        End If
    '        If strTemp(2) = "0" Then 'Grant modify access
    '            rdbtnDelete.Enabled = False
    '        End If
    '        funSetUserAccess = True
    '    Catch er As Exception

    '    End Try
    ' End Function

    Private Sub rdmenuexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexit.Click
        Me.Close()
    End Sub

    Private Sub frmVendorType_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso rdbtnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            'PostData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso rdbtnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub



    Private Sub fndvendorid__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndvendorid._MYValidating
        If isButtonClicked Then
            Dim qry As String = "select ven_Type_Code as [Vendor Type],ven_Type_Desc as [Description] from tspl_vendor_type_master"
            fndvendorid.Value = clsCommon.ShowSelectForm("FmVendorfndd", qry, "Vendor Type", "", fndvendorid.Value, "", isButtonClicked)
            rdtxtvendordesc.Text = clsDBFuncationality.getSingleValue("Select ven_Type_Desc from tspl_vendor_type_master where ven_Type_Code='" + fndvendorid.Value + "'")
            If fndvendorid.Value IsNot Nothing Then
                rdbtnDelete.Enabled = True
            Else
                rdbtnDelete.Enabled = False
            End If
            text_changed()
        ElseIf fndvendorid.MyReadOnly OrElse fndvendorid.Value IsNot Nothing Then
            Dim qry As String = "Select * from tspl_vendor_type_master where ven_Type_Code ='" + fndvendorid.Value + "' "
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
            If dt.Rows.Count <= 0 Then
                rdtxtvendordesc.Text = ""
                rdbtnSave.Text = "Save"
            Else
                text_changed()
                'rdtxtvendordesc.Text = clsDBFuncationality.getSingleValue("Select ven_Type_Desc from tspl_vendor_type_master where ven_Type_Code='" + fndvendorid.Value + "'")
            End If

                                    
        End If
                            End Sub

    Private Sub fndvendorid__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavigatorType As common.NavigatorType) Handles fndvendorid._MYNavigator
        Dim qst As String = "select ven_Type_Code as [Vendor Type],ven_Type_Desc as [Description] from tspl_vendor_type_master   where  2=2 "
        Select Case NavigatorType
            Case NavigatorType.Current
                '  qst += "and assign_to='" + txtassign.Value + "' "
                ' qst += "and job_code in ('" + txtcode1.Value + "')"
            Case NavigatorType.Next
                qst += "and ven_Type_Code in (select min(ven_Type_Code) from tspl_vendor_type_master where ven_Type_Code>'" + fndvendorid.Value + "'   ) "
            Case NavigatorType.First
                qst += "and ven_Type_Code in (select MIN(ven_Type_Code) from tspl_vendor_type_master  )"
            Case NavigatorType.Last
                qst += "and ven_Type_Code in (select Max(ven_Type_Code) from tspl_vendor_type_master  )"
            Case NavigatorType.Previous
                qst += "and ven_Type_Code in (select max(ven_Type_Code) from tspl_vendor_type_master where ven_Type_Code<'" + fndvendorid.Value + "'   )"
        End Select
        ' fun_gridfill()
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            fndvendorid.Value = clsCommon.myCstr(dt.Rows(0)("Vendor Type"))
            rdtxtvendordesc.Text = clsCommon.myCstr(dt.Rows(0)("Description"))
        End If
        'TextChanged()
        If fndvendorid.Value IsNot Nothing Then
            rdbtnDelete.Enabled = True
        Else
            rdbtnDelete.Enabled = False

        End If
        text_changed()
    End Sub
End Class



