Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports System.Data
Imports System.Data.SqlClient
Imports System.Windows.Forms
Imports System.Configuration
Imports Telerik.Collections.Generic
Imports Excel = Microsoft.Office.Interop.Excel
Imports common

Public Class frmvendoraccountset
    Inherits FrmMainTranScreen

    Dim userCode, companyCode As String
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub
    Dim dr As SqlDataReader
    Dim qry As String = ""
    Dim arrlist As New ArrayList()
    Dim whrcls As String = ""

    Private Sub frmvendoraccountset_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        If fndaccountsetcode.Value = "" Then
            rdbtndelete.Enabled = False
        End If
        textchangedsub()

        ButtonToolTip.SetToolTip(rdbtnsave, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(rdbtndelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(rdbtnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(rdbtnreset, "Press Alt+N Adding New Trasnaction")
        If CheckMultiCurrency() = True Then
            Me.fndBaseCurrency.Enabled = True
            Me.fndExchangeLoss.Enabled = True
            Me.fndExchangeGain.Enabled = True
        Else
            Me.fndBaseCurrency.Enabled = False
            Me.fndExchangeLoss.Enabled = False
            Me.fndExchangeGain.Enabled = False
        End If

        ' For dril down open 
        If clsCommon.myLen(Me.Tag) > 0 Then
            fndaccountsetcode.Value = clsCommon.myCstr(Me.Tag)
            textchangedsub()
        End If
        If clsCommon.CompairString(Form_ID, clsUserMgtCode.Farmeraccountset) = CompairStringResult.Equal Then
            chkFarmer.Visible = True
            rdlblpurchasediscount.Text = "Load Advance"
        Else
            chkFarmer.Visible = False
            rdlblpurchasediscount.Text = "Discount"
        End If
    End Sub
    Function CheckMultiCurrency() As Boolean
        Dim strq As String
        strq = "select * from tspl_module_currency_mapping where comp_code='" + objCommonVar.CurrentCompanyCode + "' and module_code='" & Me.Module_Code & "'"
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(strq)
        If dt.Rows.Count > 0 Then
            If dt.Rows(0).Item("Apply") = True Then
                Return True
            Else
                Return False
            End If
        Else
            Return False
        End If
    End Function
    Private Sub SetUserMgmtNew()
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
        End If
        rdbtnsave.Visible = MyBase.isModifyFlag
        If rdbtnsave.Visible = True Then
            rdmenuimport.Enabled = True
            rdmenuexport.Enabled = True
        Else
            rdmenuimport.Enabled = False
            rdmenuexport.Enabled = False
        End If
        rdbtndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Public Sub funinsert()
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_VENDOR_ACCOUNT_SET where Acct_Set_Code='" & fndaccountsetcode.Value & "'")
                If ChkNewEntry = 0 Then
                    fndaccountsetcode.Value = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.VendorAccountSet, "", "")
                    If clsCommon.myLen(fndaccountsetcode.Value) <= 0 Then
                        Throw New Exception("Error in Code Generation")
                    End If
                End If
            End If
            connectSql.RunSp("sp_vendoraccountset_insert", New SqlParameter("@acctsetcode", fndaccountsetcode.Value), New SqlParameter("@desc", rdtxtdescription.Text), New SqlParameter("@Payablescontrol", fndpayable.Value), New SqlParameter("@discountaccount", fndiscount.Value), New SqlParameter("@advance", txtadvance.Value), New SqlParameter("@createdby", userCode), New SqlParameter("createddate", connectSql.serverDate()), New SqlParameter("@modifyby", userCode), New SqlParameter("@modifydate", connectSql.serverDate()), New SqlParameter("@comcode", companyCode))
            UpdateNewColumns()
            myMessages.insert()


        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub

    Public Sub funupdate()
        Try
            clsCommonFunctionality.SaveHistoryData(objCommonVar.CurrentUserCode, fndaccountsetcode.Value, "TSPL_VENDOR_ACCOUNT_SET", "Acct_set_code", Nothing)
            connectSql.RunSp("sp_vendoraccountset_update", New SqlParameter("@acctsetcode", fndaccountsetcode.Value), New SqlParameter("@desc", rdtxtdescription.Text), New SqlParameter("@Payablescontrol", fndpayable.Value), New SqlParameter("@discountaccount", fndiscount.Value), New SqlParameter("@advance", txtadvance.Value), New SqlParameter("@createdby", userCode), New SqlParameter("createddate", connectSql.serverDate()), New SqlParameter("@modifyby", userCode), New SqlParameter("@modifydate", connectSql.serverDate()), New SqlParameter("@comcode", companyCode))
            UpdateNewColumns()
            myMessages.update()

            Dim STRQ As String
            STRQ = "UPDATE TSPL_VENDOR_MASTER SET CURRENCY_CODE=TSPL_VENDOR_ACCOUNT_SET.CURRENCY_CODE FROM  " &
                " TSPL_VENDOR_ACCOUNT_SET WHERE TSPL_VENDOR_MASTER.Vendor_Account=TSPL_VENDOR_ACCOUNT_SET.Acct_Set_Code AND TSPL_VENDOR_ACCOUNT_SET.Acct_Set_Code='" & fndaccountsetcode.Value & "' "
            clsDBFuncationality.ExecuteNonQuery(STRQ)

        Catch ex As Exception
            myMessages.myExceptions(ex)

        End Try
    End Sub

    Sub UpdateNewColumns()
        Dim coll As New Hashtable()
        clsCommon.AddColumnsForChange(coll, "CURRENCY_CODE", IIf(objCommonVar.IsMultiCurrencyCompany = False, objCommonVar.BaseCurrencyCode, Me.fndBaseCurrency.Value), True)
        clsCommon.AddColumnsForChange(coll, "EXCHANGE_LOSS_ACCOUNT", Me.fndExchangeLoss.Value, True)
        clsCommon.AddColumnsForChange(coll, "EXCHANGE_GAIN_ACCOUNT", Me.fndExchangeGain.Value, True)
        clsCommon.AddColumnsForChange(coll, "Commission_ACCOUNT", Me.FndCommission.Value, True)
        clsCommon.AddColumnsForChange(coll, "Incentive_ACCOUNT", Me.FndIncentive.Value, True)
        clsCommon.AddColumnsForChange(coll, "Security_ACCOUNT", Me.FndSecurity.Value, True)
        clsCommon.AddColumnsForChange(coll, "Retention_ACCOUNT", Me.txtRetention.Value, True)
        clsCommon.AddColumnsForChange(coll, "Own_Asset_ACCOUNT", Me.FndOwnAsset.Value, True)
        clsCommon.AddColumnsForChange(coll, "Head_Load_ACCOUNT", Me.FndHeadLoad.Value, True)
        clsCommon.AddColumnsForChange(coll, "Deduction_ACCOUNT", Me.FndDeduction.Value, True)
        clsCommon.AddColumnsForChange(coll, "Advance_Against_Salary", Me.fndAdvanceAgainstSalary.Value, True)
        clsCommon.AddColumnsForChange(coll, "Employee_Salary", Me.fndEmployeeSalary.Value, True)
        clsCommon.AddColumnsForChange(coll, "Advance_Against_Travelling", Me.fndAdvanceAgainstTravelling.Value, True)
        clsCommon.AddColumnsForChange(coll, "Advance_Against_Imprest", Me.fndAdvanceAgainstImprest.Value, True)
        clsCommon.AddColumnsForChange(coll, "Freight_Provision", Me.fndFreightProvision.Value, True)
        clsCommon.AddColumnsForChange(coll, "Handling_Charges", Me.txtHandlingCharges.Value, True)
        clsCommon.AddColumnsForChange(coll, "Round_Off", Me.txtRoundOff.Value, True)
        clsCommon.AddColumnsForChange(coll, "Short_Excess", Me.txtShortExcess.Value, True)
        clsCommon.AddColumnsForChange(coll, "Opening_Clearing", Me.fndVendorOpeningClearing.Value, True)
        clsCommon.AddColumnsForChange(coll, "Security_Opening_Clearing", Me.fndSecurityOpeningClearing.Value, True)
        clsCommon.AddColumnsForChange(coll, "Monthly_Rent_Account", txtMonthlyRent.Value, True)
        clsCommon.AddColumnsForChange(coll, "Profit_Loss_Account", txtProfitAndLossAccount.Value, True)
        clsCommon.AddColumnsForChange(coll, "PRO_DATA_ACCOUNT", txtProData.Value, True)
        clsCommon.AddColumnsForChange(coll, "Arrear_Account", txtArrear.Value, True)
        clsCommon.AddColumnsForChange(coll, "IsFarmer", IIf(chkFarmer.Checked = True, 1, 0))
        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_VENDOR_ACCOUNT_SET", OMInsertOrUpdate.Update, "TSPL_VENDOR_ACCOUNT_SET.Acct_Set_Code='" + fndaccountsetcode.Value + "'", Nothing)
    End Sub

    Public Sub fundelete()
        Try
            connectSql.RunSp("sp_vendoraccountset_delete", New SqlParameter("@acctsetcode", fndaccountsetcode.Value))
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Public Function accountqry() As String
        arrlist = clsERPFuncationality.glaccountquery(objCommonVar.CurrentUserCode)
        qry = arrlist.Item(0)
        whrcls = arrlist.Item(1)
        If whrcls <> "" Then
            qry = qry + " where " + whrcls + " and account_type <>'Retained Earnings'and ControlAccount  ='N' "
        Else
            qry = qry + " where account_type <>'Retained Earnings'and ControlAccount  ='N' "
        End If

        Return qry
    End Function

    Public Sub funfill()
        Try
            Dim query As String = "Select  acct_set_desc,payable_account,discount_account,advance_account, " &
            " TSPL_VENDOR_ACCOUNT_SET.CURRENCY_CODE,TSPL_VENDOR_ACCOUNT_SET.EXCHANGE_LOSS_ACCOUNT, " &
            " TSPL_CURRENCY_MASTER.currency_name,gl1.description as EXCHANGE_LOSS_ACCOUNT_Name,gl2.description as EXCHANGE_GAIN_ACCOUNT_Name" _
            & " ,TSPL_VENDOR_ACCOUNT_SET.EXCHANGE_GAIN_ACCOUNT,TSPL_VENDOR_ACCOUNT_SET.Commission_ACCOUNT,TSPL_VENDOR_ACCOUNT_SET.Incentive_ACCOUNT " _
            & " ,gl3.description as Commission_Name,gl4.description as Incentive_Name,Security_Account,gl5.description as Security_Name,RETENTION_ACCOUNT,gl13.description as Retention_Name " _
            & " ,Own_Asset_Account,gl6.description as Own_Asset_Account_Name,Head_Load_Account,gl7.description as Head_Load_Account_Name,Deduction_Account,gl8.description as Deduction_Account_Name ,gl9.description as Advance_Against_Salary_Name,tspl_vendor_account_set.Advance_Against_Salary,tspl_vendor_account_set.Employee_Salary,gl10.description as Employee_Salary_Name,tspl_vendor_account_set.Advance_Against_Travelling,gl11.description as Advance_Against_Travelling_Name,tspl_vendor_account_set.Advance_Against_Imprest ,gl12.description as Advance_Against_Imprest_Name,TSPL_VENDOR_ACCOUNT_SET.Freight_Provision,glFreight_account.description as Freight_Provision_Desc,TSPL_VENDOR_ACCOUNT_SET.Handling_Charges,TabGLHandlingCharge.description as Handling_Charges_Desc,TSPL_VENDOR_ACCOUNT_SET.Round_Off,TabRoundOff.description as Round_Off_Dess,TSPL_VENDOR_ACCOUNT_SET.Short_Excess,TabShortExcess.description as Short_Excess_Dess,TSPL_VENDOR_ACCOUNT_SET.Opening_Clearing,TabOpeningClearing.description as Opening_Clearing_Desc  , TSPL_VENDOR_ACCOUNT_SET .Security_Opening_Clearing ,TabSecurityOpeningClearing.description as Security_Opening_Clearing_Desc ,TSPL_VENDOR_ACCOUNT_SET.Monthly_Rent_Account ,TabMonthlyRentAccountName.description as Monthly_Rent_AccountName,TSPL_VENDOR_ACCOUNT_SET.Profit_Loss_Account ,Table_Profit_Loss_AccountName.description as Profit_Loss_AccountName,TSPL_VENDOR_ACCOUNT_SET.PRO_DATA_ACCOUNT,Table_PRO_DATA_ACCOUNTName.description as PRO_DATA_ACCOUNTName,TSPL_VENDOR_ACCOUNT_SET.IsFarmer,TSPL_VENDOR_ACCOUNT_SET.Arrear_Account,Table_ArrearName.description as Arrear_AccountName  from TSPL_VENDOR_ACCOUNT_SET " &
            " left join TSPL_CURRENCY_MASTER on TSPL_VENDOR_ACCOUNT_SET.currency_code=TSPL_CURRENCY_MASTER.currency_code " &
            " left join TSPL_GL_ACCOUNTS gl1 on TSPL_VENDOR_ACCOUNT_SET.EXCHANGE_LOSS_ACCOUNT=gl1.account_code " &
            " left join TSPL_GL_ACCOUNTS gl2 on TSPL_VENDOR_ACCOUNT_SET.EXCHANGE_GAIN_ACCOUNT=gl2.account_code " &
            " left join TSPL_GL_ACCOUNTS gl3 on TSPL_VENDOR_ACCOUNT_SET.Commission_ACCOUNT=gl3.account_code " &
            " left join TSPL_GL_ACCOUNTS gl4 on TSPL_VENDOR_ACCOUNT_SET.Incentive_ACCOUNT=gl4.account_code " &
            " left join TSPL_GL_ACCOUNTS gl5 on TSPL_VENDOR_ACCOUNT_SET.Security_ACCOUNT=gl5.account_code " &
            " left join TSPL_GL_ACCOUNTS gl6 on TSPL_VENDOR_ACCOUNT_SET.Own_Asset_ACCOUNT=gl6.account_code " &
            " left join TSPL_GL_ACCOUNTS gl7 on TSPL_VENDOR_ACCOUNT_SET.Head_Load_ACCOUNT=gl7.account_code " &
            " left join TSPL_GL_ACCOUNTS gl8 on TSPL_VENDOR_ACCOUNT_SET.Deduction_ACCOUNT=gl8.account_code " &
            " left join TSPL_GL_ACCOUNTS gl9 on TSPL_VENDOR_ACCOUNT_SET.Advance_Against_Salary=gl9.account_code" &
            " left join TSPL_GL_ACCOUNTS gl10 on TSPL_VENDOR_ACCOUNT_SET.Employee_Salary=gl10.account_code" &
            " left join TSPL_GL_ACCOUNTS gl11 on TSPL_VENDOR_ACCOUNT_SET.Advance_Against_Travelling=gl11.account_code" &
            " left join TSPL_GL_ACCOUNTS gl12 on TSPL_VENDOR_ACCOUNT_SET.Advance_Against_Imprest=gl12.account_code" &
            " left join TSPL_GL_ACCOUNTS gl13 on TSPL_VENDOR_ACCOUNT_SET.RETENTION_ACCOUNT=gl13.account_code" &
            " left join TSPL_GL_ACCOUNTS glFreight_account on TSPL_VENDOR_ACCOUNT_SET.Freight_Provision=glFreight_account.account_code " &
            " left join TSPL_GL_ACCOUNTS TabGLHandlingCharge on TSPL_VENDOR_ACCOUNT_SET.Handling_Charges=TabGLHandlingCharge.account_code " &
            " left join TSPL_GL_ACCOUNTS TabRoundOff on TSPL_VENDOR_ACCOUNT_SET.Round_Off=TabRoundOff.account_code " &
            " left join TSPL_GL_ACCOUNTS TabShortExcess on TSPL_VENDOR_ACCOUNT_SET.Short_Excess=TabShortExcess.account_code " &
            " left join TSPL_GL_ACCOUNTS TabOpeningClearing on TSPL_VENDOR_ACCOUNT_SET.Opening_Clearing=TabOpeningClearing.account_code " &
            " left join TSPL_GL_ACCOUNTS TabSecurityOpeningClearing on TSPL_VENDOR_ACCOUNT_SET.Security_Opening_Clearing=TabSecurityOpeningClearing.account_code " &
            " left join TSPL_GL_ACCOUNTS TabMonthlyRentAccountName on TabMonthlyRentAccountName.account_code  =TSPL_VENDOR_ACCOUNT_SET.Monthly_Rent_Account " &
            " left join TSPL_GL_ACCOUNTS Table_Profit_Loss_AccountName on Table_Profit_Loss_AccountName.account_code  =TSPL_VENDOR_ACCOUNT_SET.Profit_Loss_Account " &
            " left join TSPL_GL_ACCOUNTS Table_PRO_DATA_ACCOUNTName on Table_PRO_DATA_ACCOUNTName.account_code  =TSPL_VENDOR_ACCOUNT_SET.PRO_DATA_ACCOUNT " &
            " left join TSPL_GL_ACCOUNTS Table_ArrearName on Table_ArrearName.account_code  =TSPL_VENDOR_ACCOUNT_SET.Arrear_Account " &
            " where acct_set_code='" + fndaccountsetcode.Value + "'"
            Dim adp As New SqlDataAdapter(query, connectSql.SqlCon)
            Dim dt As New DataTable()
            adp.Fill(dt)
            Dim dr As DataRow = dt.Rows(0)
            rdtxtdescription.Text = dr(0).ToString()
            fndpayable.Value = dr(1).ToString()
            rdtxtpayablescontrol.Text = clsDBFuncationality.getSingleValue("select  Description  from TSPL_GL_ACCOUNTS where Account_Code='" + fndpayable.Value + "'")
            fndiscount.Value = dr(2).ToString()
            rdtxtpurchasediscount.Text = clsDBFuncationality.getSingleValue("select  Description  from TSPL_GL_ACCOUNTS where Account_Code='" + fndiscount.Value + "'")

            txtadvance.Value = dr(3).ToString()
            rdtxtadvance.Text = clsDBFuncationality.getSingleValue("select  Description  from TSPL_GL_ACCOUNTS where Account_Code='" + txtadvance.Value + "'")

            fndBaseCurrency.Value = Convert.ToString(dr("CURRENCY_CODE"))
            fndExchangeLoss.Value = Convert.ToString(dr("EXCHANGE_LOSS_ACCOUNT"))
            fndExchangeGain.Value = Convert.ToString(dr("EXCHANGE_GAIN_ACCOUNT"))
            lblCurrencyName.Text = Convert.ToString(dr("currency_name"))
            lblExchangeLossName.Text = Convert.ToString(dr("EXCHANGE_LOSS_ACCOUNT_Name"))
            lblExchangeGainName.Text = Convert.ToString(dr("EXCHANGE_GAIN_ACCOUNT_Name"))

            FndCommission.Value = Convert.ToString(dr("Commission_ACCOUNT"))
            FndIncentive.Value = Convert.ToString(dr("Incentive_ACCOUNT"))
            FndSecurity.Value = Convert.ToString(dr("Security_ACCOUNT"))
            txtRetention.Value = Convert.ToString(dr("Retention_ACCOUNT"))
            TxtCommission.Text = Convert.ToString(dr("Commission_name"))
            TxtIncentive.Text = Convert.ToString(dr("Incentive_Name"))
            LblSecurity.Text = Convert.ToString(dr("Security_Name"))
            lblRetention.Text = Convert.ToString(dr("Retention_Name"))

            FndOwnAsset.Value = Convert.ToString(dr("Own_Asset_ACCOUNT"))
            LblOwnAsset.Text = Convert.ToString(dr("Own_Asset_ACCOUNT_Name"))

            FndHeadLoad.Value = Convert.ToString(dr("Head_Load_ACCOUNT"))
            lblHeadLoad.Text = Convert.ToString(dr("Head_Load_ACCOUNT_Name"))

            FndDeduction.Value = Convert.ToString(dr("Deduction_ACCOUNT"))
            LblDeduction.Text = Convert.ToString(dr("Deduction_ACCOUNT_Name"))

            fndAdvanceAgainstSalary.Value = Convert.ToString(dr("Advance_Against_Salary"))
            lblAdvanceAgainstSalary.Text = Convert.ToString(dr("Advance_Against_Salary_Name"))

            fndEmployeeSalary.Value = Convert.ToString(dr("Employee_Salary"))
            lblEmployeeSalary.Text = Convert.ToString(dr("Employee_Salary_Name"))
            fndAdvanceAgainstTravelling.Value = Convert.ToString(dr("Advance_Against_Travelling"))
            lblAdvanceAgainstTravelling.Text = Convert.ToString(dr("Advance_Against_Travelling_Name"))
            fndAdvanceAgainstImprest.Value = Convert.ToString(dr("Advance_Against_Imprest"))
            lblAdvanceAgainstImprest.Text = Convert.ToString(dr("Advance_Against_Imprest_Name"))
            fndFreightProvision.Value = Convert.ToString(dr("Freight_Provision"))
            lblFreghtDesc.Text = Convert.ToString(dr("Freight_Provision_Desc"))
            txtHandlingCharges.Value = Convert.ToString(dr("Handling_Charges"))
            lblHandlingCharges.Text = Convert.ToString(dr("Handling_Charges_Desc"))
            txtRoundOff.Value = Convert.ToString(dr("Round_Off"))
            chkFarmer.Checked = clsCommon.myCBool(IIf(dr("IsFarmer") = 1, True, False))
            lblRoundOff.Text = Convert.ToString(dr("Round_Off_Dess"))
            txtShortExcess.Value = Convert.ToString(dr("Short_Excess"))
            lblShortExcess.Text = Convert.ToString(dr("Short_Excess_Dess"))
            fndVendorOpeningClearing.Value = Convert.ToString(dr("Opening_Clearing"))
            lblVenodrOpeningClearing.Text = Convert.ToString(dr("Opening_Clearing_Desc"))
            fndSecurityOpeningClearing.Value = Convert.ToString(dr("Security_Opening_Clearing"))
            lblSecurityOpeningClearing.Text = Convert.ToString(dr("Security_Opening_Clearing_Desc"))
            txtMonthlyRent.Value = clsCommon.myCstr(dr("Monthly_Rent_Account"))
            lblMonthlyRent.Text = clsCommon.myCstr(dr("Monthly_Rent_AccountName"))
            txtProfitAndLossAccount.Value = clsCommon.myCstr(dr("Profit_Loss_Account"))
            lblProfitAndLossAccount.Text = clsCommon.myCstr(dr("Profit_Loss_AccountName"))
            txtProData.Value = clsCommon.myCstr(dr("PRO_DATA_ACCOUNT"))
            lblProData.Text = clsCommon.myCstr(dr("PRO_DATA_ACCOUNTName"))

            txtArrear.Value = clsCommon.myCstr(dr("Arrear_Account"))
            lblArrear.Text = clsCommon.myCstr(dr("Arrear_AccountName"))
            rdbtnsave.Text = "Update"
            rdbtndelete.Enabled = True
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub
    Sub textchangedsub()
        Dim query As String = "select acct_set_code from tspl_vendor_account_set where acct_set_code ='" + fndaccountsetcode.Value() + "'"
        Dim var As String
        var = clsDBFuncationality.getSingleValue(query)
        If (var <> "") Then
            funfill()
            rdbtnsave.Text = "Update"
            rdbtndelete.Enabled = True
        Else
            rdbtnsave.Text = "Save"
            rdtxtdescription.Text = ""
            rdbtndelete.Enabled = False
            fndpayable.Value = ""
            fndiscount.Value = ""
            txtadvance.Value = ""
        End If
    End Sub
    Public Sub text_changed(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Public Sub funreset()
        chkFarmer.Checked = False
        txtRoundOff.Value = ""
        lblRoundOff.Text = ""
        txtShortExcess.Value = ""
        lblShortExcess.Text = ""
        fndaccountsetcode.Value = ""
        rdtxtdescription.Text = ""
        fndpayable.Value = ""
        fndiscount.Value = ""
        txtadvance.Value = ""
        rdtxtpayablescontrol.Text = ""
        rdtxtpurchasediscount.Text = ""
        rdtxtadvance.Text = ""
        rdbtndelete.Enabled = False

        fndBaseCurrency.Value = Nothing
        lblCurrencyName.Text = ""
        fndExchangeLoss.Value = Nothing
        lblExchangeLossName.Text = ""
        fndExchangeGain.Value = Nothing
        lblExchangeGainName.Text = ""

        FndCommission.Value = Nothing
        TxtCommission.Text = ""
        FndIncentive.Value = Nothing
        TxtIncentive.Text = ""
        FndSecurity.Value = Nothing
        txtRetention.Value = Nothing
        lblRetention.Text = ""
        LblSecurity.Text = ""

        FndOwnAsset.Value = Nothing
        LblOwnAsset.Text = ""
        FndHeadLoad.Value = Nothing
        lblHeadLoad.Text = ""
        FndDeduction.Value = Nothing
        LblDeduction.Text = ""
        fndAdvanceAgainstSalary.Value = ""
        lblAdvanceAgainstSalary.Text = ""
        fndEmployeeSalary.Value = Nothing
        lblEmployeeSalary.Text = ""
        fndAdvanceAgainstTravelling.Value = Nothing
        lblAdvanceAgainstTravelling.Text = ""
        fndAdvanceAgainstImprest.Value = Nothing
        lblAdvanceAgainstImprest.Text = ""
        fndFreightProvision.Value = Nothing
        lblFreghtDesc.Text = ""
        txtHandlingCharges.Value = Nothing
        lblHandlingCharges.Text = ""
        fndVendorOpeningClearing.Value = Nothing
        lblVenodrOpeningClearing.Text = ""
        fndSecurityOpeningClearing.Value = Nothing
        lblSecurityOpeningClearing.Text = ""
        txtMonthlyRent.Value = ""
        lblMonthlyRent.Text = ""
        txtProfitAndLossAccount.Value = ""
        lblProfitAndLossAccount.Text = ""
        txtProData.Value = ""
        lblProData.Text = ""
        txtArrear.Value = ""
        lblArrear.Text = ""
        If clsCommon.CompairString(Form_ID, clsUserMgtCode.Farmeraccountset) = CompairStringResult.Equal Then
            rdlblpurchasediscount.Text = "Load Advance"
        Else
            rdlblpurchasediscount.Text = "Discount"
        End If
        rdbtnsave.Text = "Save"
        rdtxtdescription.Focus()
    End Sub
    Private Function CheckControlAccount(ByVal AccountType As String, ByVal AccountCode As String) As Boolean
        Try
            If clsCommon.myLen(AccountCode) > 0 Then
                Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + AccountCode + "' AND ControlAccount ='Y'"
                Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1)
                If check1 <= 0 Then
                    clsCommon.MyMessageBoxShow("Filled " + AccountType + " (" & AccountCode & ") must be control account.", Me.Text)
                    Return False
                End If
            End If
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return True
    End Function
    Private Sub rdbtnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnsave.Click
        SaveData()
    End Sub
    Sub SaveData()
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso fndaccountsetcode.Value = "" Then
            myMessages.blankValue("Account Set Code")
            fndaccountsetcode.Focus()
        ElseIf (fndpayable.Value = "") Then
            myMessages.blankValue("Payables Control ")
            fndpayable.Focus()
        ElseIf (fndiscount.Value = "") Then
            myMessages.blankValue("Purchase Discount")
            fndiscount.Focus()
        ElseIf (txtadvance.Value = "") Then
            myMessages.blankValue("Advance")
            txtadvance.Focus()
        ElseIf CheckControlAccount("Payables Control", fndpayable.Value) = False Then
            fndpayable.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Discount", fndiscount.Value) = False Then
            fndiscount.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Advance", txtadvance.Value) = False Then
            txtadvance.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Exchange Loss", fndExchangeLoss.Value) = False Then
            fndExchangeLoss.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Exchange Gain", fndExchangeGain.Value) = False Then
            fndExchangeGain.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Commission", FndCommission.Value) = False Then
            FndCommission.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Incentive", FndIncentive.Value) = False Then
            FndIncentive.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Security", FndSecurity.Value) = False Then
            FndSecurity.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Retention", txtRetention.Value) = False Then
            txtRetention.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Head Load", FndHeadLoad.Value) = False Then
            FndHeadLoad.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Own Asset", FndOwnAsset.Value) = False Then
            FndOwnAsset.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Deduction", FndDeduction.Value) = False Then
            FndDeduction.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Advance Against Salary", fndAdvanceAgainstSalary.Value) = False Then
            fndAdvanceAgainstSalary.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Employee Salary ", fndEmployeeSalary.Value) = False Then
            fndEmployeeSalary.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Advance Against Travelling", fndAdvanceAgainstTravelling.Value) = False Then
            fndAdvanceAgainstTravelling.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Advance Against Imprest", fndAdvanceAgainstImprest.Value) = False Then
            fndAdvanceAgainstImprest.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Freight Provision", fndFreightProvision.Value) = False Then
            fndFreightProvision.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Profit/Loss Account", txtProfitAndLossAccount.Value) = False Then
            txtProfitAndLossAccount.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Pro Data Account", txtProData.Value) = False Then
            txtProData.Focus()
            Exit Sub
        ElseIf CheckControlAccount("Arrear", txtArrear.Value) = False Then
            txtArrear.Focus()
            Exit Sub
        Else
            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.vendoraccountset, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If
            If chkFarmer.Checked = True Then
                Dim farmercount As Integer = clsDBFuncationality.getSingleValue("SELECT count(IsFarmer) from TSPL_VENDOR_ACCOUNT_SET where Acct_Set_Code<>'" & fndaccountsetcode.Value & "' and IsFarmer=1")
                If farmercount > 0 Then
                    clsCommon.MyMessageBoxShow(Me, "Account set of Farmer type already exist", Me.Text)
                    Exit Sub
                End If
            End If
            If rdbtnsave.Text = "Save" Then
                    funinsert()
                    funfill()
                ElseIf (rdbtnsave.Text = "Update") Then
                    funupdate()

                End If
            End If
    End Sub
    Private Sub rdbtndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtndelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(fndaccountsetcode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "You Cannot Delete Record", Me.Text)
            Exit Sub
        End If
        If myMessages.deleteConfirm Then
            fundelete()
            myMessages.delete()
            rdbtnsave.Text = "Save"
            rdbtndelete.Enabled = False
            funreset()
        End If
    End Sub
    Private Sub rdbtnreset_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnreset.Click
        funreset()
    End Sub
    Public Sub payablefunfill()
        Dim query As String = "select account_code as [Account code],Description  from TSPL_GL_ACCOUNTS where account_type <>'Retained Earnings'and ControlAccount  ='N'and Account_Code ='" + fndpayable.Value + "'"
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(query)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            For Each row As DataRow In dt.Rows
                rdtxtpayablescontrol.Text = row(1).ToString
            Next
        End If
    End Sub
    Public Sub payables_textchanged(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Try
            Dim query As String = "select account_code as [Account code],Description  from TSPL_GL_ACCOUNTS where account_type <>'Retained Earnings'and ControlAccount  ='N'and Account_Code ='" + fndpayable.Value + "'"
            Dim dt As DataTable
            dt = clsDBFuncationality.GetDataTable(query)
            Dim var As String = ""
            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
                For Each row As DataRow In dt.Rows
                    var = row(0).ToString()
                Next
            End If
            If var <> "" Then
                payablefunfill()
            Else
                rdtxtpayablescontrol.Text = ""
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try


    End Sub

    Private Sub rdmenuimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuimport.Click
        Dim dgv As New RadGridView
        Me.Controls.Add(dgv)
        If transportSql.importExcel(dgv, "Account Set Code", "Description", "Payable Control Account", "Discount_Account", "Advance Account", "Currency", "Exchange Gain Account", "Exchange Loss Account", "Commission Account", "Incentive Account", "Security Account", "Head Load Account", "Own Asset Account", "Deduction Account", "Advance Against Salary", "Employee Salary", "Advance Against Travelling", "Advance Against Imprest", "Freight Provision Account", "Handling Charges", "Round Off", "Short Excess", "Opening Clearing", "Security Opening Clearing", "Monthly Rent Account", "Profit Loss Account", "PRO DATA ACCOUNT", "Arrear Account") Then
            Dim linno As Integer = 0
            Dim trans As SqlTransaction = Nothing
            Try
                trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each dgrv As GridViewRowInfo In dgv.Rows
                    linno += 1
                    Dim straccountsetcode As String = clsCommon.myCstr(dgrv.Cells(0).Value)
                    Dim strdisc As String = clsCommon.myCstr(dgrv.Cells(1).Value)
                    Dim strpayablecontrol As String = clsCommon.myCstr(dgrv.Cells(2).Value)
                    '' Anubhooti 06-Nov-2014
                    If clsCommon.myLen(strpayablecontrol) > 0 Then
                        Dim qry As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strpayablecontrol + "'"
                        Dim check As Integer = clsDBFuncationality.getSingleValue(qry, trans)
                        If check <= 0 Then
                            Throw New Exception("Filled payable control account (" & strpayablecontrol & ") does not exist" + Environment.NewLine + ".First make its entry first at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strpayablecontrol + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled payable control account (" & strpayablecontrol & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If
                    Dim strdiscount As String = clsCommon.myCstr(dgrv.Cells(3).Value)
                    If clsCommon.myLen(strdiscount) > 0 Then
                        Dim qry As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strdiscount + "'"
                        Dim check As Integer = clsDBFuncationality.getSingleValue(qry, trans)
                        If check <= 0 Then
                            Throw New Exception("Filled discount account (" & strdiscount & ") does not exist" + Environment.NewLine + ".First make its entry first at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strdiscount + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled discount account (" & strdiscount & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If
                    Dim stradvanceaccount As String = clsCommon.myCstr(dgrv.Cells(4).Value)
                    If clsCommon.myLen(stradvanceaccount) > 0 Then
                        Dim qry As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + stradvanceaccount + "'"
                        Dim check As Integer = clsDBFuncationality.getSingleValue(qry, trans)
                        If check <= 0 Then
                            Throw New Exception("Filled advance account (" & stradvanceaccount & ") does not exist" + Environment.NewLine + ".First make its entry first at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + stradvanceaccount + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled advance account (" & stradvanceaccount & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If
                    Dim strCurrancy As String = clsCommon.myCstr(dgrv.Cells(5).Value)
                    Dim qry3 As String = "select count(*) from TSPL_CURRENCY_MASTER where CURRENCY_CODE='" + strCurrancy + "'"
                    Dim check2 As Integer = clsDBFuncationality.getSingleValue(qry3, trans)
                    If check2 <= 0 Then
                        Throw New Exception("Filled Currancy (" & strCurrancy & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                    End If

                    Dim strExchangeGain As String = clsCommon.myCstr(dgrv.Cells(6).Value)
                    If clsCommon.myLen(strExchangeGain) > 0 Then
                        Dim qry4 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strExchangeGain + "'"
                        Dim check3 As Integer = clsDBFuncationality.getSingleValue(qry4, trans)
                        If check3 <= 0 Then
                            Throw New Exception("Filled Exchage Gain (" & strExchangeGain & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If

                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strExchangeGain + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Exchage Gain (" & strExchangeGain & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    Dim strExchangeLoss As String = clsCommon.myCstr(dgrv.Cells(7).Value)
                    If clsCommon.myLen(strExchangeLoss) > 0 Then
                        Dim qry5 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strExchangeLoss + "'"
                        Dim check4 As Integer = clsDBFuncationality.getSingleValue(qry5, trans)
                        If check4 <= 0 Then
                            Throw New Exception("Filled Exchange Loss (" & strExchangeLoss & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If


                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strExchangeLoss + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Exchange Loss (" & strExchangeLoss & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If
                    Dim strCommissionAc As String = clsCommon.myCstr(dgrv.Cells(8).Value)
                    If clsCommon.myLen(strCommissionAc) > 0 Then
                        Dim qry6 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strCommissionAc + "'"
                        Dim check5 As Integer = clsDBFuncationality.getSingleValue(qry6, trans)
                        If check5 <= 0 Then
                            Throw New Exception("Filled Commission Account (" & strCommissionAc & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If

                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strCommissionAc + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Commission Account (" & strCommissionAc & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If
                    ' End If
                    Dim strIncentiveACCOUNT As String = clsCommon.myCstr(dgrv.Cells(9).Value)
                    If clsCommon.myLen(strIncentiveACCOUNT) > 0 Then
                        Dim qry7 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strIncentiveACCOUNT + "'"
                        Dim check6 As Integer = clsDBFuncationality.getSingleValue(qry7, trans)
                        If check6 <= 0 Then
                            Throw New Exception("Filled Incentive Account (" & strIncentiveACCOUNT & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If

                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strIncentiveACCOUNT + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Incentive Account (" & strIncentiveACCOUNT & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    Dim strSECURITYACCOUNT As String = clsCommon.myCstr(dgrv.Cells(10).Value)
                    If clsCommon.myLen(strSECURITYACCOUNT) > 0 Then
                        Dim qry8 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strSECURITYACCOUNT + "'"
                        Dim check7 As Integer = clsDBFuncationality.getSingleValue(qry8, trans)
                        If check7 <= 0 Then
                            Throw New Exception("Filled Seccurity Account (" & strSECURITYACCOUNT & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(strSECURITYACCOUNT) > 0 Then
                            Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strSECURITYACCOUNT + "' AND ControlAccount ='Y'"
                            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                            If check1 <= 0 Then
                                Throw New Exception("Filled Seccurity Account (" & strSECURITYACCOUNT & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                            End If
                        End If
                    End If
                    Dim strHead_Load_ACCOUNT As String = clsCommon.myCstr(dgrv.Cells(11).Value)
                    If clsCommon.myLen(strHead_Load_ACCOUNT) > 0 Then
                        Dim qry9 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strHead_Load_ACCOUNT + "'"
                        Dim check8 As Integer = clsDBFuncationality.getSingleValue(qry9, trans)
                        If check8 <= 0 Then
                            Throw New Exception("Filled Head Load Account (" & strHead_Load_ACCOUNT & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If


                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strHead_Load_ACCOUNT + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Head Load Account (" & strHead_Load_ACCOUNT & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    Dim strOwn_Asset_ACCOUNT As String = clsCommon.myCstr(dgrv.Cells(12).Value)
                    If clsCommon.myLen(strOwn_Asset_ACCOUNT) > 0 Then
                        Dim qry10 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strOwn_Asset_ACCOUNT + "'"
                        Dim check9 As Integer = clsDBFuncationality.getSingleValue(qry10, trans)
                        If check9 <= 0 Then
                            Throw New Exception("Filled Own Assets Account (" & strOwn_Asset_ACCOUNT & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If

                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strOwn_Asset_ACCOUNT + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Own Assets Account (" & strOwn_Asset_ACCOUNT & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If
                    Dim strDeduction_ACCOUNT As String = clsCommon.myCstr(dgrv.Cells(13).Value)
                    If clsCommon.myLen(strDeduction_ACCOUNT) > 0 Then
                        Dim qry11 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strDeduction_ACCOUNT + "'"
                        Dim check10 As Integer = clsDBFuncationality.getSingleValue(qry11, trans)
                        If check10 <= 0 Then
                            Throw New Exception("Filled Deduction Account (" & strDeduction_ACCOUNT & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If

                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strDeduction_ACCOUNT + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Deduction Account (" & strDeduction_ACCOUNT & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    Dim strAdvance_Against_Salary As String = clsCommon.myCstr(dgrv.Cells(14).Value)
                    If clsCommon.myLen(strAdvance_Against_Salary) > 0 Then
                        Dim qry12 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strAdvance_Against_Salary + "'"
                        Dim check11 As Integer = clsDBFuncationality.getSingleValue(qry12, trans)
                        If check11 <= 0 Then
                            Throw New Exception("Filled Advance Against Salary (" & strAdvance_Against_Salary & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If


                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strAdvance_Against_Salary + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Advance Against Salary (" & strAdvance_Against_Salary & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    Dim strEmployee_Salary As String = clsCommon.myCstr(dgrv.Cells(15).Value)
                    If clsCommon.myLen(strEmployee_Salary) > 0 Then
                        Dim qry13 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strEmployee_Salary + "'"
                        Dim check13 As Integer = clsDBFuncationality.getSingleValue(qry13, trans)
                        If check13 <= 0 Then
                            Throw New Exception("Filled Employee Salary (" & strEmployee_Salary & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If

                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strEmployee_Salary + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Employee Salary (" & strEmployee_Salary & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    Dim strAdvance_Against_Travelling As String = clsCommon.myCstr(dgrv.Cells(16).Value)
                    If clsCommon.myLen(strAdvance_Against_Travelling) > 0 Then
                        Dim qry14 As String = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strAdvance_Against_Travelling + "'"
                        Dim check14 As Integer = clsDBFuncationality.getSingleValue(qry14, trans)
                        If check14 <= 0 Then
                            Throw New Exception("Filled Advance Against Travelling (" & strAdvance_Against_Travelling & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If


                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strAdvance_Against_Travelling + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Advance Against Travelling (" & strAdvance_Against_Travelling & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    Dim strAdvance_Against_Imprest As String = clsCommon.myCstr(dgrv.Cells(17).Value)
                    If clsCommon.myLen(strAdvance_Against_Imprest) > 0 Then
                        Dim qry15 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strAdvance_Against_Imprest + "'"
                        Dim check15 As Integer = clsDBFuncationality.getSingleValue(qry15, trans)
                        If check15 <= 0 Then
                            Throw New Exception("Filled Advance Against Imprest (" & strAdvance_Against_Imprest & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If


                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strAdvance_Against_Imprest + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Advance Against Imprest (" & strAdvance_Against_Imprest & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If
                    Dim qry16 As String
                    Dim check16 As Integer
                    Dim Freight_Provision As String = clsCommon.myCstr(dgrv.Cells(18).Value)
                    If clsCommon.myLen(Freight_Provision) > 0 Then
                        qry16 = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + Freight_Provision + "'"
                        check16 = clsDBFuncationality.getSingleValue(qry16, trans)
                        If check16 <= 0 Then
                            Throw New Exception("Filled Freight Provision (" & Freight_Provision & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If


                        Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + Freight_Provision + "' AND ControlAccount ='Y'"
                        Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                        If check1 <= 0 Then
                            Throw New Exception("Filled Freight Provision (" & Freight_Provision & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If




                    Dim HandlingCharges As String = clsCommon.myCstr(dgrv.Cells("Handling Charges").Value)
                    If clsCommon.myLen(HandlingCharges) > 0 Then
                        qry16 = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + HandlingCharges + "'"
                        check16 = clsDBFuncationality.getSingleValue(qry16, trans)
                        If check16 <= 0 Then
                            Throw New Exception("Filled Handling Charges (" & HandlingCharges & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(HandlingCharges) > 0 Then
                            Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + HandlingCharges + "' AND ControlAccount ='Y'"
                            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                            If check1 <= 0 Then
                                Throw New Exception("Filled Handling Charges (" & HandlingCharges & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                            End If
                        End If
                    End If
                    ' Round Off
                    Dim RoundOff As String = clsCommon.myCstr(dgrv.Cells("Round Off").Value)
                    If clsCommon.myLen(RoundOff) > 0 Then
                        qry16 = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + RoundOff + "'"
                        check16 = clsDBFuncationality.getSingleValue(qry16, trans)
                        If check16 <= 0 Then
                            Throw New Exception("Filled Round off (" & RoundOff & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(RoundOff) > 0 Then
                            Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + RoundOff + "' AND ControlAccount ='Y'"
                            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                            If check1 <= 0 Then
                                Throw New Exception("Filled Round off (" & RoundOff & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                            End If
                        End If
                    End If
                    ' Short Exccess 
                    Dim ShortExccess As String = clsCommon.myCstr(dgrv.Cells("Short Excess").Value)
                    If clsCommon.myLen(ShortExccess) > 0 Then
                        qry16 = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + ShortExccess + "'"
                        check16 = clsDBFuncationality.getSingleValue(qry16, trans)
                        If check16 <= 0 Then
                            Throw New Exception("Filled Short Exccess (" & ShortExccess & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(ShortExccess) > 0 Then
                            Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + ShortExccess + "' AND ControlAccount ='Y'"
                            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                            If check1 <= 0 Then
                                Throw New Exception("Filled Round off (" & ShortExccess & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                            End If
                        End If
                    End If

                    Dim OpeningClearing As String = clsCommon.myCstr(dgrv.Cells("Opening Clearing").Value)
                    If clsCommon.myLen(OpeningClearing) > 0 Then
                        qry16 = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + OpeningClearing + "'"
                        check16 = clsDBFuncationality.getSingleValue(qry16, trans)
                        If check16 <= 0 Then
                            Throw New Exception("Filled Opening Clearing (" & OpeningClearing & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(OpeningClearing) > 0 Then
                            Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + OpeningClearing + "' AND ControlAccount ='Y'"
                            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                            If check1 <= 0 Then
                                Throw New Exception("Filled Opening Clearing (" & OpeningClearing & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                            End If
                        End If
                    End If

                    ' Security_Opening_Clearing
                    Dim SecurityOpeningClearing As String = clsCommon.myCstr(dgrv.Cells("Security Opening Clearing").Value)
                    If clsCommon.myLen(SecurityOpeningClearing) > 0 Then
                        qry16 = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + SecurityOpeningClearing + "'"
                        check16 = clsDBFuncationality.getSingleValue(qry16, trans)
                        If check16 <= 0 Then
                            Throw New Exception("Filled Security Opening Clearing (" & SecurityOpeningClearing & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(SecurityOpeningClearing) > 0 Then
                            Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + SecurityOpeningClearing + "' AND ControlAccount ='Y'"
                            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                            If check1 <= 0 Then
                                Throw New Exception("Filled Security Opening Clearing (" & SecurityOpeningClearing & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                            End If
                        End If
                    End If
                    ' Monthly Rent Account
                    Dim strMonthlyRentAccount As String = clsCommon.myCstr(dgrv.Cells("Monthly Rent Account").Value)
                    If clsCommon.myLen(strMonthlyRentAccount) > 0 Then
                        qry16 = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strMonthlyRentAccount + "'"
                        check16 = clsDBFuncationality.getSingleValue(qry16, trans)
                        If check16 <= 0 Then
                            Throw New Exception("Filled Security Opening Clearing (" & strMonthlyRentAccount & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(strMonthlyRentAccount) > 0 Then
                            Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strMonthlyRentAccount + "' AND ControlAccount ='Y'"
                            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                            If check1 <= 0 Then
                                Throw New Exception("Filled Monthly Rent Account (" & strMonthlyRentAccount & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                            End If
                        End If
                    End If

                    ' Profit Loss Account
                    Dim strProfitLossAccount As String = clsCommon.myCstr(dgrv.Cells("Profit Loss Account").Value)
                    If clsCommon.myLen(strProfitLossAccount) > 0 Then
                        qry16 = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strProfitLossAccount + "'"
                        check16 = clsDBFuncationality.getSingleValue(qry16, trans)
                        If check16 <= 0 Then
                            Throw New Exception("Filled Profit Loss Account (" & strProfitLossAccount & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(strProfitLossAccount) > 0 Then
                            Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strProfitLossAccount + "' AND ControlAccount ='Y'"
                            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                            If check1 <= 0 Then
                                Throw New Exception("Filled Profit Loss Account (" & strProfitLossAccount & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                            End If
                        End If
                    End If

                    ' Pro Data Account
                    Dim strProDataAccount As String = clsCommon.myCstr(dgrv.Cells("PRO Data ACCOUNT").Value)
                    If clsCommon.myLen(strProDataAccount) > 0 Then
                        qry16 = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strProDataAccount + "'"
                        check16 = clsDBFuncationality.getSingleValue(qry16, trans)
                        If check16 <= 0 Then
                            Throw New Exception("Filled PRO Data ACCOUNT (" & strProDataAccount & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(strProDataAccount) > 0 Then
                            Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strProDataAccount + "' AND ControlAccount ='Y'"
                            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                            If check1 <= 0 Then
                                Throw New Exception("Filled PRO Data ACCOUNT (" & strProDataAccount & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                            End If
                        End If
                    End If


                    ' Arrear Account
                    Dim strArrear As String = clsCommon.myCstr(dgrv.Cells("Arrear Account").Value)
                    If clsCommon.myLen(strArrear) > 0 Then
                        qry16 = " select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strArrear + "'"
                        check16 = clsDBFuncationality.getSingleValue(qry16, trans)
                        If check16 <= 0 Then
                            Throw New Exception("Filled Arrear ACCOUNT (" & strArrear & ")  does not exist" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(strArrear) > 0 Then
                            Dim qry1 As String = "select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + strArrear + "' AND ControlAccount ='Y'"
                            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                            If check1 <= 0 Then
                                Throw New Exception("Filled Arrear ACCOUNT (" & strArrear & ") must be control account" + Environment.NewLine + " at line no. " + clsCommon.myCstr(linno) + ".")
                            End If
                        End If
                    End If

                    Dim Datee As String = clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy")
                    If String.IsNullOrEmpty(straccountsetcode) Or straccountsetcode.Length > 12 Then
                        Throw New Exception("Vendor Acccount has some incorrect values length")
                        trans.Rollback()
                        Exit Sub
                    End If
                    If (straccountsetcode.Length > 12) Or (strdisc.Length > 100) Then
                        Throw New Exception("Check the length of Description")
                        trans.Rollback()
                        Exit Sub
                    End If
                    If strpayablecontrol.Length > 50 Then
                        Throw New Exception("Check the length of Payables Control")
                        trans.Rollback()
                        Exit Sub
                    End If
                    If strdiscount.Length > 50 Then
                        Throw New Exception("Check the length of Discount Account")
                        trans.Rollback()
                        Exit Sub
                    End If
                    If stradvanceaccount.Length > 50 Then
                        Throw New Exception("Check the length of Advance Account")
                        trans.Rollback()
                        Exit Sub
                    End If
                    Dim sql1 As String = "select count(*)from tspl_vendor_account_set  where acct_set_code='" + straccountsetcode + "'"
                    Dim i As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(sql1, trans))
                    If (i = 0) Then
                        Dim query As String = "insert into tspl_vendor_account_set (Acct_Set_Code,Acct_Set_Desc,Payable_Account,Discount_Account,Advance_Account,CURRENCY_CODE,EXCHANGE_GAIN_ACCOUNT,EXCHANGE_LOSS_ACCOUNT,Commission_ACCOUNT,Incentive_ACCOUNT,SECURITY_ACCOUNT,Head_Load_ACCOUNT,Own_Asset_ACCOUNT,Deduction_ACCOUNT,Advance_Against_Salary,Employee_Salary,Advance_Against_Travelling,Advance_Against_Imprest,Created_By,Created_Date,Modify_By,Modify_Date,Comp_Code,Freight_Provision,Handling_Charges,Round_Off,Opening_Clearing,Security_Opening_Clearing,Monthly_Rent_Account,Profit_Loss_account,Arrear_Account) values ('" + straccountsetcode + "','" + strdisc + "','" + strpayablecontrol + "','" + strdiscount + "','" + stradvanceaccount + "','" + IIf(objCommonVar.IsMultiCurrencyCompany = False, objCommonVar.BaseCurrencyCode, strCurrancy) + "'," + IIf(clsCommon.myLen(strExchangeGain) > 0, "'" + strExchangeGain + "'", "null") + "," + IIf(clsCommon.myLen(strExchangeLoss) > 0, "'" + strExchangeLoss + "'", "null") + "," + IIf(clsCommon.myLen(strCommissionAc) > 0, "'" + strCommissionAc + "'", "null") + "," + IIf(clsCommon.myLen(strIncentiveACCOUNT) > 0, "'" + strIncentiveACCOUNT + "'", "null") + "," + IIf(clsCommon.myLen(strSECURITYACCOUNT) > 0, "'" + strSECURITYACCOUNT + "'", "null") + "," + IIf(clsCommon.myLen(strHead_Load_ACCOUNT) > 0, "'" + strHead_Load_ACCOUNT + "'", "null") + "," + IIf(clsCommon.myLen(strOwn_Asset_ACCOUNT) > 0, "'" + strOwn_Asset_ACCOUNT + "'", "null") + "," + IIf(clsCommon.myLen(strDeduction_ACCOUNT) > 0, "'" + strDeduction_ACCOUNT + "'", "null") + "," + IIf(clsCommon.myLen(strAdvance_Against_Salary) > 0, "'" + strAdvance_Against_Salary + "'", "null") + "," + IIf(clsCommon.myLen(strEmployee_Salary) > 0, "'" + strEmployee_Salary + "'", "null") + "," + IIf(clsCommon.myLen(strAdvance_Against_Travelling) > 0, "'" + strAdvance_Against_Travelling + "'", "null") + "," + IIf(clsCommon.myLen(strAdvance_Against_Imprest) > 0, "'" + strAdvance_Against_Imprest + "'", "null") + ",'" + userCode + "','" + Datee + "','" + userCode + "','" + Datee + "','" + companyCode + "'," + IIf(clsCommon.myLen(Freight_Provision) > 0, "'" + Freight_Provision + "'", "null") + "," + IIf(clsCommon.myLen(HandlingCharges) > 0, "'" + HandlingCharges + "'", "null") + "," + IIf(clsCommon.myLen(RoundOff) > 0, "'" + RoundOff + "'", "null") + ", " + IIf(clsCommon.myLen(OpeningClearing) > 0, "'" + OpeningClearing + "'", "null") + ", " + IIf(clsCommon.myLen(SecurityOpeningClearing) > 0, "'" + SecurityOpeningClearing + "'", "null") + ", " + IIf(clsCommon.myLen(strMonthlyRentAccount) > 0, "'" + strMonthlyRentAccount + "'", "null") + "," + IIf(clsCommon.myLen(strProfitLossAccount) > 0, "'" + strProfitLossAccount + "'", "null") + ", " + IIf(clsCommon.myLen(strArrear) > 0, "'" + strArrear + "'", "null") + ")"
                        clsDBFuncationality.ExecuteNonQuery(query, trans)
                    Else
                        clsCommonFunctionality.SaveHistoryData(objCommonVar.CurrentUserCode, straccountsetcode, "TSPL_VENDOR_ACCOUNT_SET", "Acct_set_code", trans)
                        Dim query1 As String = "update tspl_vendor_account_set set acct_set_desc='" + strdisc + "',Payable_account='" + strpayablecontrol + "',discount_account='" + strdiscount + "',Advance_account='" + stradvanceaccount + "',CURRENCY_CODE='" + IIf(objCommonVar.IsMultiCurrencyCompany = False, objCommonVar.BaseCurrencyCode, strCurrancy) + "',EXCHANGE_GAIN_ACCOUNT=" + IIf(clsCommon.myLen(strExchangeGain) > 0, "'" + strExchangeGain + "'", "null") + ",EXCHANGE_LOSS_ACCOUNT=" + IIf(clsCommon.myLen(strExchangeLoss) > 0, "'" + strExchangeLoss + "'", "null") + ",Commission_ACCOUNT=" + IIf(clsCommon.myLen(strCommissionAc) > 0, "'" + strCommissionAc + "'", "null") + ",Incentive_ACCOUNT=" + IIf(clsCommon.myLen(strIncentiveACCOUNT) > 0, "'" + strIncentiveACCOUNT + "'", "null") + ",SECURITY_ACCOUNT=" + IIf(clsCommon.myLen(strSECURITYACCOUNT) > 0, "'" + strSECURITYACCOUNT + "'", "null") + ",Head_Load_ACCOUNT=" + IIf(clsCommon.myLen(strHead_Load_ACCOUNT) > 0, "'" + strHead_Load_ACCOUNT + "'", "null") + ",Own_Asset_ACCOUNT=" + IIf(clsCommon.myLen(strOwn_Asset_ACCOUNT) > 0, "'" + strOwn_Asset_ACCOUNT + "'", "null") + ",Deduction_ACCOUNT=" + IIf(clsCommon.myLen(strDeduction_ACCOUNT) > 0, "'" + strDeduction_ACCOUNT + "'", "null") + ",Advance_Against_Salary=" + IIf(clsCommon.myLen(strAdvance_Against_Salary) > 0, "'" + strAdvance_Against_Salary + "'", "null") + " , Employee_Salary = " + IIf(clsCommon.myLen(strEmployee_Salary) > 0, "'" + strEmployee_Salary + "'", "null") + " ,Advance_Against_Travelling = " + IIf(clsCommon.myLen(strAdvance_Against_Travelling) > 0, "'" + strAdvance_Against_Travelling + "'", "null") + ", Advance_Against_Imprest = " + IIf(clsCommon.myLen(strAdvance_Against_Imprest) > 0, "'" + strAdvance_Against_Imprest + "'", "null") + ",Freight_Provision=(CASE WHEN " & clsCommon.myLen(Freight_Provision) & ">0 THEN '" + Freight_Provision + "' ELSE NULL END),Handling_Charges=(CASE WHEN " & clsCommon.myLen(HandlingCharges) & ">0 THEN '" + HandlingCharges + "' ELSE NULL END),   Round_Off=(CASE WHEN " & clsCommon.myLen(RoundOff) & ">0 THEN '" + RoundOff + "' ELSE NULL END)  , Opening_Clearing=(CASE WHEN " & clsCommon.myLen(OpeningClearing) & ">0 THEN '" + OpeningClearing + "' ELSE NULL END) , Security_Opening_Clearing=(CASE WHEN " & clsCommon.myLen(SecurityOpeningClearing) & ">0 THEN '" + SecurityOpeningClearing + "' ELSE NULL END), Monthly_Rent_Account=(CASE WHEN " & clsCommon.myLen(strMonthlyRentAccount) & ">0 THEN '" + strMonthlyRentAccount + "' ELSE NULL END) , Profit_Loss_account=(CASE WHEN " & clsCommon.myLen(strProfitLossAccount) & ">0 THEN '" + strProfitLossAccount + "' ELSE NULL END) , Arrear_Account=(CASE WHEN " & clsCommon.myLen(strArrear) & ">0 THEN '" + strArrear + "' ELSE NULL END ) where Acct_set_code='" + straccountsetcode + "' "
                        clsDBFuncationality.ExecuteNonQuery(query1, trans)
                    End If
                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transferred Completed", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                trans.Rollback()
                clsCommon.ProgressBarHide()

                myMessages.myExceptions(ex)

            End Try
        End If
        Me.Controls.Remove(dgv)
    End Sub
    Private Sub rdmenuexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexport.Click
        Dim query As String = "select acct_set_code as 'Account Set Code',acct_set_desc as 'Description',payable_account as 'Payable Control Account',discount_account as 'Discount_Account'"
        query += " ,Advance_account as 'Advance Account',CURRENCY_CODE  as 'Currency',EXCHANGE_GAIN_ACCOUNT as 'Exchange Gain Account',EXCHANGE_LOSS_ACCOUNT as 'Exchange Loss Account',Commission_ACCOUNT as 'Commission Account',Incentive_ACCOUNT as 'Incentive Account',SECURITY_ACCOUNT as 'Security Account',Head_Load_ACCOUNT as 'Head Load Account',Own_Asset_ACCOUNT as 'Own Asset Account',Deduction_ACCOUNT as  'Deduction Account',Advance_Against_Salary as 'Advance Against Salary' ,Employee_Salary as 'Employee Salary',Advance_Against_Travelling as 'Advance Against Travelling',Advance_Against_Imprest as 'Advance Against Imprest', Freight_Provision as 'Freight Provision Account',Handling_Charges as [Handling Charges],Round_Off as [Round Off],Short_Excess as [Short Excess], Opening_Clearing as [Opening Clearing], Security_Opening_Clearing as [Security Opening Clearing],Monthly_Rent_Account as [Monthly Rent Account],tspl_vendor_account_set.Profit_Loss_account as [Profit Loss Account],PRO_DATA_ACCOUNT as [PRO DATA ACCOUNT],Arrear_Account as [Arrear Account]"
        query += " from tspl_vendor_account_set"
        ListImpExpColumnsMandatory = New List(Of String)({"Account Set Code"})
        ListImpExpColumnsSuperMandatory = New List(Of String)({"Account Set Code"})
        transportSql.ExporttoExcel(query, "", "", Me, ListImpExpColumnsMandatory, ListImpExpColumnsSuperMandatory, MyBase.Form_ID)
    End Sub
    Private Sub rdbtnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnclose.Click
        Me.Close()
    End Sub
    Private Sub rdmenuexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexit.Click
        Me.Close()
    End Sub

    Private Sub frmvendoraccountset_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso rdbtnsave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            'PostData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso rdbtndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funreset()
        End If
    End Sub

    Private Sub fndaccountsetcode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndaccountsetcode._MYValidating

        If isButtonClicked Then
            Dim whrcls As String = String.Empty
            If clsCommon.CompairString(Form_ID, clsUserMgtCode.Farmeraccountset) = CompairStringResult.Equal Then
                whrcls = " tspl_vendor_account_set.IsFarmer=1 "
            Else
                whrcls = " tspl_vendor_account_set.IsFarmer=0 "
            End If
            fndaccountsetcode.Value = clsVendorAccountSet.getFinder(whrcls, fndaccountsetcode.Value, isButtonClicked)
            rdtxtdescription.Text = clsDBFuncationality.getSingleValue("Select acct_set_desc from tspl_vendor_account_set where acct_set_code='" + fndaccountsetcode.Value + "'")
            If fndaccountsetcode.Value IsNot Nothing Then
                rdbtndelete.Enabled = True
            Else
                rdbtndelete.Enabled = False
            End If
            textchangedsub()

        ElseIf fndaccountsetcode.MyReadOnly OrElse fndaccountsetcode.Value IsNot Nothing Then
            Dim qry As String = "Select * from TSPL_User_Group_Master where group_Code ='" + fndaccountsetcode.Value + "' "
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
            If dt.Rows.Count < 0 Then
                rdtxtdescription.Text = ""
                rdbtnsave.Text = "Save"
                rdtxtadvance.Text = ""
                rdtxtpayablescontrol.Text = ""
                rdtxtpurchasediscount.Text = ""
                fndiscount.Value = ""
                fndpayable.Value = ""
                txtadvance.Value = ""

            Else
                textchangedsub()
                rdbtndelete.Enabled = True

            End If

        End If
    End Sub

    Private Sub fndaccountsetcode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavigatorType As common.NavigatorType) Handles fndaccountsetcode._MYNavigator
        Dim whrcls As String = String.Empty
        If clsCommon.CompairString(Form_ID, clsUserMgtCode.Farmeraccountset) = CompairStringResult.Equal Then
            whrcls = " AND tspl_vendor_account_set.IsFarmer=1 "
        Else
            whrcls = " AND tspl_vendor_account_set.IsFarmer=0 "
        End If

        Dim qst As String = "select acct_set_code as [Account Set Code],acct_set_desc as [Description]  from tspl_vendor_account_set   where  2=2 " & whrcls & ""
        Select Case NavigatorType
            Case NavigatorType.Current
            Case NavigatorType.Next
                qst += "and acct_set_code in (select min(acct_set_code) from tspl_vendor_account_set where acct_set_code>'" + fndaccountsetcode.Value + "' " & whrcls & ") "
            Case NavigatorType.First
                qst += "and acct_set_code in (select MIN(acct_set_code) from tspl_vendor_account_set WHERE 1=1 " & whrcls & ")"
            Case NavigatorType.Last
                qst += "and acct_set_code in (select Max(acct_set_code) from tspl_vendor_account_set WHERE 1=1 " & whrcls & ")"
            Case NavigatorType.Previous
                qst += "and acct_set_code in (select max(acct_set_code) from tspl_vendor_account_set where acct_set_code<'" + fndaccountsetcode.Value + "' " & whrcls & ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            fndaccountsetcode.Value = clsCommon.myCstr(dt.Rows(0)("Account Set Code"))
            rdtxtdescription.Text = clsCommon.myCstr(dt.Rows(0)("Description"))
        End If
        If fndaccountsetcode.Value IsNot Nothing Then
            rdbtndelete.Enabled = True
        Else
            rdbtndelete.Enabled = False
        End If
        textchangedsub()
    End Sub

    Private Sub fndpayable__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndpayable._MYValidating
        Dim qry As String
        arrlist = clsERPFuncationality.glaccountqueryForControlAcc(objCommonVar.CurrentUserCode)
        qry = arrlist.Item(0)
        whrcls = arrlist.Item(1)
        If whrcls <> "" Then
            whrcls = "" + whrcls + " and account_type <>'Retained Earnings'and ControlAccount  ='Y' "
        Else
            whrcls = "  account_type <>'Retained Earnings'and ControlAccount  ='Y' "
        End If

        fndpayable.Value = clsCommon.ShowSelectForm("ACCODE", qry, "Account_Code", whrcls, fndpayable.Value, "Account_Code", isButtonClicked)
        rdtxtpayablescontrol.Text = clsDBFuncationality.getSingleValue("select  Description  from TSPL_GL_ACCOUNTS where Account_Code='" + fndpayable.Value + "'")
    End Sub

    Private Sub fndiscount__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndiscount._MYValidating
        Dim qry As String
        arrlist = clsERPFuncationality.glaccountqueryForControlAcc(objCommonVar.CurrentUserCode)
        qry = arrlist.Item(0)
        whrcls = arrlist.Item(1)
        If whrcls <> "" Then
            whrcls = "" + whrcls + " and account_type <>'Retained Earnings'and ControlAccount  ='Y' "
        Else
            whrcls = "  account_type <>'Retained Earnings'and ControlAccount  ='Y' "
        End If

        fndiscount.Value = clsCommon.ShowSelectForm("ACCODE", qry, "Account_Code", whrcls, fndiscount.Value, "Account_Code", isButtonClicked)
        rdtxtpurchasediscount.Text = clsDBFuncationality.getSingleValue("select  Description  from TSPL_GL_ACCOUNTS where Account_Code='" + fndiscount.Value + "'")
    End Sub

    Private Sub txtadvance__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtadvance._MYValidating
        Dim qry As String
        arrlist = clsERPFuncationality.glaccountqueryForControlAcc(objCommonVar.CurrentUserCode)
        qry = arrlist.Item(0)
        whrcls = arrlist.Item(1)
        If whrcls <> "" Then
            whrcls = "" + whrcls + " and account_type <>'Retained Earnings'and ControlAccount  ='Y' "
        Else
            whrcls = "  account_type <>'Retained Earnings'and ControlAccount  ='Y' "
        End If

        txtadvance.Value = clsCommon.ShowSelectForm("ACCODE", qry, "Account_Code", whrcls, txtadvance.Value, "Account_Code", isButtonClicked)
        rdtxtadvance.Text = clsDBFuncationality.getSingleValue("select  Description  from TSPL_GL_ACCOUNTS where Account_Code='" + txtadvance.Value + "'")
    End Sub

    Private Sub fndBaseCurrency__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndBaseCurrency._MYValidating
        Dim qry As String = "select CURRENCY_CODE AS Code, CURRENCY_NAME as Name from TSPL_CURRENCY_MASTER"
        fndBaseCurrency.Value = clsCommon.ShowSelectForm("CURRENCY_MASTER", qry, "Code", "", fndBaseCurrency.Value, "CURRENCY_CODE", isButtonClicked)
        lblCurrencyName.Text = clsDBFuncationality.getSingleValue("select currency_name from TSPL_CURRENCY_MASTER where currency_code='" + fndBaseCurrency.Value + "' ")
    End Sub

    Private Sub fndExchangeLoss__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndExchangeLoss._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        fndExchangeLoss.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", fndExchangeLoss.Value, "", isButtonClicked)
        lblExchangeLossName.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + fndExchangeLoss.Value + "' ")
    End Sub

    Private Sub fndExchangeGain__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndExchangeGain._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        fndExchangeGain.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", fndExchangeGain.Value, "", isButtonClicked)
        lblExchangeGainName.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + fndExchangeGain.Value + "' ")
    End Sub

    Private Sub FndCommission__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles FndCommission._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        FndCommission.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", FndCommission.Value, "", isButtonClicked)
        TxtCommission.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + FndCommission.Value + "' ")
    End Sub

    Private Sub FndIncentive__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles FndIncentive._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        FndIncentive.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", FndIncentive.Value, "", isButtonClicked)
        TxtIncentive.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + FndIncentive.Value + "' ")
    End Sub

    Private Sub FndSecurity__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles FndSecurity._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        FndSecurity.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", FndSecurity.Value, "", isButtonClicked)
        LblSecurity.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + FndSecurity.Value + "' ")
    End Sub

    Private Sub FndOwnAsset__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles FndOwnAsset._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        FndOwnAsset.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", FndOwnAsset.Value, "", isButtonClicked)
        LblOwnAsset.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + FndOwnAsset.Value + "' ")
    End Sub

    Private Sub FndHeadLoad__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles FndHeadLoad._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        FndHeadLoad.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", FndHeadLoad.Value, "", isButtonClicked)
        lblHeadLoad.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + FndHeadLoad.Value + "' ")
    End Sub

    Private Sub FndDeduction__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles FndDeduction._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        FndDeduction.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", FndDeduction.Value, "", isButtonClicked)
        LblDeduction.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + FndDeduction.Value + "' ")
    End Sub


    Private Sub fndAdvanceAgainstSalary__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles fndAdvanceAgainstSalary._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        fndAdvanceAgainstSalary.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", FndDeduction.Value, "", isButtonClicked)
        lblAdvanceAgainstSalary.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + fndAdvanceAgainstSalary.Value + "' ")
    End Sub


    Private Sub fndEmployeeSalary__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles fndEmployeeSalary._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        fndEmployeeSalary.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", fndEmployeeSalary.Value, "", isButtonClicked)
        lblEmployeeSalary.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + fndEmployeeSalary.Value + "' ")
    End Sub

    Private Sub fndAdvanceAgainstTravelling__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles fndAdvanceAgainstTravelling._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        fndAdvanceAgainstTravelling.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", fndAdvanceAgainstTravelling.Value, "", isButtonClicked)
        lblAdvanceAgainstTravelling.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + fndAdvanceAgainstTravelling.Value + "' ")
    End Sub

    Private Sub fndAdvanceAgainstImprest__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles fndAdvanceAgainstImprest._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        fndAdvanceAgainstImprest.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", fndAdvanceAgainstImprest.Value, "", isButtonClicked)
        lblAdvanceAgainstImprest.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + fndAdvanceAgainstImprest.Value + "' ")
    End Sub

    Private Sub fndFreightProvision__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles fndFreightProvision._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        fndFreightProvision.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", fndFreightProvision.Value, "", isButtonClicked)
        lblFreghtDesc.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + fndFreightProvision.Value + "' ")
    End Sub

    Private Sub btnHistory_Click(sender As Object, e As EventArgs) Handles btnHistory.Click
        Try
            If clsCommon.myLen(fndaccountsetcode.Value) <= 0 Then
                clsCommon.MyMessageBoxShow(Me, "Select Account Set", Me.Text)
                Exit Sub
            End If
            clsERPFuncationalityOLD.ShowHistoryData(fndaccountsetcode.Value, "acct_set_code", "TSPL_VENDOR_ACCOUNT_SET")
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Sub

    Private Sub txtHandlingCharges__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtHandlingCharges._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        txtHandlingCharges.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", txtHandlingCharges.Value, "", isButtonClicked)
        lblHandlingCharges.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + txtHandlingCharges.Value + "' ")
    End Sub
    Private Sub txtRoundOff__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtRoundOff._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        txtRoundOff.Value = clsCommon.ShowSelectForm("RECRound_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", txtRoundOff.Value, "", isButtonClicked)
        lblRoundOff.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + txtRoundOff.Value + "' ")
    End Sub

    Private Sub txtShortExcess__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtShortExcess._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        txtShortExcess.Value = clsCommon.ShowSelectForm("RECShoExcefnd", qry, "AccountCode", " ControlAccount ='Y' ", txtShortExcess.Value, "", isButtonClicked)
        lblShortExcess.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + txtShortExcess.Value + "' ")
    End Sub


    Private Sub lkRoundOff_Click(sender As Object, e As EventArgs) Handles lkRoundOff.Click

    End Sub

    Private Sub fndVendorOpeningClearing__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles fndVendorOpeningClearing._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        fndVendorOpeningClearing.Value = clsCommon.ShowSelectForm("RECRound_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", fndVendorOpeningClearing.Value, "", isButtonClicked)
        lblVenodrOpeningClearing.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + fndVendorOpeningClearing.Value + "' ")
    End Sub

    Private Sub fndSecurityOpeningClearing__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles fndSecurityOpeningClearing._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        fndSecurityOpeningClearing.Value = clsCommon.ShowSelectForm("RECRound_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", fndSecurityOpeningClearing.Value, "", isButtonClicked)
        lblSecurityOpeningClearing.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + fndSecurityOpeningClearing.Value + "' ")
    End Sub

    Private Sub txtMonthlyRent__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtMonthlyRent._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        txtMonthlyRent.Value = clsCommon.ShowSelectForm("RECRound_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", txtMonthlyRent.Value, "", isButtonClicked)
        lblMonthlyRent.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + txtMonthlyRent.Value + "' ")
    End Sub

    Private Sub txtProfitAndLossAccount__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtProfitAndLossAccount._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        txtProfitAndLossAccount.Value = clsCommon.ShowSelectForm("ProfitAndLossAccFndr", qry, "AccountCode", " ControlAccount ='Y' ", txtProfitAndLossAccount.Value, "", isButtonClicked)
        lblProfitAndLossAccount.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + txtProfitAndLossAccount.Value + "' ")
    End Sub

    Private Sub txtArrear__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtArrear._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        txtArrear.Value = clsCommon.ShowSelectForm("ProfitAndLossAccFndr", qry, "AccountCode", " ControlAccount ='Y' ", txtArrear.Value, "", isButtonClicked)
        lblArrear.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + txtArrear.Value + "' ")

    End Sub

    Private Sub txtRetention__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtRetention._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        txtRetention.Value = clsCommon.ShowSelectForm("REC_CONfnd", qry, "AccountCode", " ControlAccount ='Y' ", txtRetention.Value, "", isButtonClicked)
        lblRetention.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + txtRetention.Value + "' ")
    End Sub

    Private Sub txtProData__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtProData._MYValidating
        Dim qry As String = "select account_code as [AccountCode],description as [Description] from tspl_gl_accounts "
        txtProData.Value = clsCommon.ShowSelectForm("ProfitAndLossAccFndr", qry, "AccountCode", " ControlAccount ='Y' ", txtProData.Value, "", isButtonClicked)
        lblProData.Text = clsDBFuncationality.getSingleValue("select description from tspl_gl_accounts where account_code='" + txtProData.Value + "' ")

    End Sub



End Class
