'-03/04/2013:5:41PM--Updation By--Pankaj Kumar--Transaction Problem while importing-------------------Ashok
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports System.Data
Imports System.Data.SqlClient
Imports System.Windows.Forms
Imports System.Configuration
Imports Telerik.Collections.Generic
Imports Excel = Microsoft.Office.Interop.Excel
Imports common

'Start date =10/6/2011
'End date =10/6/2011
'Database =TSPlERP
' Tables=Tspl_Vendor_Group
'--Preeti Gupta--ticket no-[BM00000003143]
Public Class frmVendorGroup
    Inherits FrmMainTranScreen
    Dim userCode, companyCode As String
    Dim dr As SqlDataReader
    Dim ButtonToolTip As ToolTip = New ToolTip()
    
    'This Cunstructer is used to send usercode and compcode data in table.
    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub
    Private Sub frmVendorGroup_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        ' fndgroupcode.txtValue.MaxLength = 12
        SetUserMgmtNew()
        ' fndgroupcode.txtValue.CharacterCasing = CharacterCasing.Upper
        '   globalFunc.mandatoryText(fndaccountset.txtValue)
        ' globalFunc.mandatoryText(fndbankcode.txtValue)
        ' globalFunc.mandatoryText(fndgroupcode.txtValue)
        'globalFunc.mandatoryText(fndpayamentcode.txtValue)
        '  globalFunc.mandatoryText(fndtaxgroup.txtValue)
        '  globalFunc.mandatoryText(fndtermscode.txtValue)

        If fndgroupcode.Value = "" Then
            rdbtndelete.Enabled = False
            rdtxtaccountset.ReadOnly = True
            rdtxttermscode.ReadOnly = True
            rdtxtbankcode.ReadOnly = True
            rdtxttaxgroup.ReadOnly = True
        End If
        groupcode_textchanged()
        acctsetcode_textchanged()
        accountset_leave()
        termscode_textchanged()
        termscode_leave()
        bankcode_textchanged()
        bankcode_leave()
        payamentcode_textchanged()
        paymentcode_leave()
        taxgroup_textchanged()
        taxgroup_leave()
        ' AddHandler fndgroupcode.ValueChanged, AddressOf groupcode_textchanged
        ' AddHandler fndaccountset.ValueChanged, AddressOf acctsetcode_textchanged
        ' AddHandler fndaccountset.txtValue.Leave, AddressOf accountset_leave
        ' AddHandler fndtermscode.ValueChanged, AddressOf termscode_textchanged
        'AddHandler fndtermscode.txtValue.Leave, AddressOf termscode_leave
        ' AddHandler fndpayamentcode.ValueChanged, AddressOf payamentcode_textchanged
        '  AddHandler fndpayamentcode.txtValue.Leave, AddressOf paymentcode_leave
        '  AddHandler fndbankcode.ValueChanged, AddressOf bankcode_textchanged
        ' AddHandler fndbankcode.txtValue.Leave, AddressOf bankcode_leave
        '   AddHandler fndtaxgroup.ValueChanged, AddressOf taxgroup_textchanged
        '   AddHandler fndtaxgroup.txtValue.Leave, AddressOf taxgroup_leave
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
        ButtonToolTip.SetToolTip(rdbtnsave, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(rdbtndelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(rdbtnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(rdbtnreset, "Press Alt+N Adding New Trasnaction")
        ' For dril down open 
        If clsCommon.myLen(Me.Tag) > 0 Then
            fndgroupcode.Value = clsCommon.myCstr(Me.Tag)
            groupcode_textchanged()
        End If
    End Sub
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt("VEN-GRP")
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        rdbtnsave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 03/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If rdbtnsave.Visible = True Then
            rdmenuimport.Enabled = True
            rdmenuexport.Enabled = True
        Else
            rdmenuimport.Enabled = False
            rdmenuexport.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        rdbtndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Public Sub funinsert()
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_VENDOR_GROUP where Ven_Group_Code='" & fndgroupcode.Value & "'")
                If ChkNewEntry = 0 Then
                    fndgroupcode.Value = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.VendorGroup, "", "")
                    If clsCommon.myLen(fndgroupcode.Value) <= 0 Then
                        Throw New Exception("Error in Code Generation")
                    End If
                End If
            End If
            connectSql.RunSp("sp_vendorgroup_insert", New SqlParameter("@vendorgroupcode", fndgroupcode.Value), New SqlParameter("@groupdesc", rdtxtgroupdesc.Text), New SqlParameter("@acct_set_code", fndaccountset.Value), New SqlParameter("@acct_desc", rdtxtaccountset.Text), New SqlParameter("@termscode", fndtermscode.Value), New SqlParameter("@termsdesc", rdtxttermscode.Text), New SqlParameter("@paymentcode", fndpayamentcode.Value), New SqlParameter("@payamentdesc", rdtxtpayametcode.Text), New SqlParameter("@bankcode", fndbankcode.Value), New SqlParameter("@bankdesc", rdtxtbankcode.Text), New SqlParameter("@taxcode", fndtaxgroup.Value), New SqlParameter("@taxdesc", rdtxttaxgroup.Text), New SqlParameter("@createdby", userCode), New SqlParameter("@createddate", connectSql.serverDate()), New SqlParameter("@modifyby", userCode), New SqlParameter("@modifydate", connectSql.serverDate()), New SqlParameter("@comcode", companyCode), New SqlParameter("@isTDSApplicable", IIf(clsCommon.myCBool(chk_istdsapplicable.Checked) = True, 1, 0)))
            clsCommonFunctionality.SaveHistoryData(objCommonVar.CurrentUserCode, clsCommon.myCstr(fndgroupcode.Value), "TSPL_VENDOR_GROUP", "Ven_Group_Code", Nothing)
            '' changes by Parteek on 26/03/2018
            Dim strqry As String = ""
            strqry = " update TSPL_VENDOR_GROUP set Vendor_Sub_Group='" & clsCommon.myCstr(fndSubGroup.Value) & "' where Ven_Group_Code='" + fndgroupcode.Value + "'"
            clsDBFuncationality.ExecuteNonQuery(strqry)
            strqry = " update TSPL_VENDOR_GROUP set Default_VSP='" & IIf(clsCommon.myCBool(chkDefaultVSP.Checked) = True, 1, 0) & "' where Ven_Group_Code='" + fndgroupcode.Value + "'"
            clsDBFuncationality.ExecuteNonQuery(strqry)
            myMessages.insert()
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Public Sub funupdate()
        Try
            connectSql.RunSp("sp_vendorgroup_update", New SqlParameter("@vendorgroupcode", fndgroupcode.Value), New SqlParameter("@groupdesc", rdtxtgroupdesc.Text), New SqlParameter("@acct_set_code", fndaccountset.Value), New SqlParameter("@acct_desc", rdtxtaccountset.Text), New SqlParameter("@termscode", fndtermscode.Value), New SqlParameter("@termsdesc", rdtxttermscode.Text), New SqlParameter("@paymentcode", fndpayamentcode.Value), New SqlParameter("@payamentdesc", rdtxtpayametcode.Text), New SqlParameter("@bankcode", fndbankcode.Value), New SqlParameter("@bankdesc", rdtxtbankcode.Text), New SqlParameter("@taxcode", fndtaxgroup.Value), New SqlParameter("@taxdesc", rdtxttaxgroup.Text), New SqlParameter("@createdby", userCode), New SqlParameter("@createddate", connectSql.serverDate()), New SqlParameter("@modifyby", userCode), New SqlParameter("@modifydate", connectSql.serverDate()), New SqlParameter("@comcode", companyCode), New SqlParameter("@isTDSApplicable", IIf(clsCommon.myCBool(chk_istdsapplicable.Checked) = True, 1, 0)))
            clsCommonFunctionality.SaveHistoryData(objCommonVar.CurrentUserCode, clsCommon.myCstr(fndgroupcode.Value), "TSPL_VENDOR_GROUP", "Ven_Group_Code", Nothing)
            '' changes by Parteek on 26/03/2018
            Dim strqry As String = ""
            strqry = " update TSPL_VENDOR_GROUP set Vendor_Sub_Group='" & clsCommon.myCstr(fndSubGroup.Value) & "' where Ven_Group_Code='" + fndgroupcode.Value + "'"
            clsDBFuncationality.ExecuteNonQuery(strqry)
            strqry = " update TSPL_VENDOR_GROUP set Default_VSP='" & IIf(clsCommon.myCBool(chkDefaultVSP.Checked) = True, 1, 0) & "' where Ven_Group_Code='" + fndgroupcode.Value + "'"
            clsDBFuncationality.ExecuteNonQuery(strqry)
            myMessages.update()
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub
    Public Sub funddelete()
        Try
            connectSql.RunSp("sp_vendorgroup_delete", New SqlParameter("@vendorgroupcode", fndgroupcode.Value))
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Public Sub funreset()
        If fndgroupcode.Value <> "" Then
            fndgroupcode.Value = ""
            rdtxtgroupdesc.Text = ""
            fndaccountset.Value = ""
            rdtxtaccountset.Text = ""
            rdtxtaccountset.ReadOnly = True
            fndtermscode.Value = ""
            rdtxttermscode.Text = ""
            rdtxttermscode.ReadOnly = True
            fndbankcode.Value = ""
            rdtxtbankcode.Text = ""
            rdtxtbankcode.ReadOnly = True
            fndpayamentcode.Value = ""
            rdtxtpayametcode.Text = ""
            rdtxtpayametcode.ReadOnly = True
            fndtaxgroup.Value = ""
            rdtxttaxgroup.Text = ""
            rdbtndelete.Enabled = False
            rdbtnsave.Text = "Save"
            fndaccountset.Focus()
            chk_istdsapplicable.Checked = False
            chkDefaultVSP.Checked = False
            fndSubGroup.Value = ""
            txtSubGroup.Text = ""

        End If
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub
    Private Sub rdbtnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnsave.Click
        SaveData()
    End Sub
    Sub SaveData()
        Dim IsVendorGrpDetailMandatory As Boolean = False
        IsVendorGrpDetailMandatory = IIf(clsCommon.myCdbl(clsFixedParameter.GetData(clsFixedParameterType.IsVendorGroupFieldsMandatory, clsFixedParameterCode.IsVendorGroupFieldsMandatory, Nothing)) = 1, True, False)

        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(fndgroupcode.Value) <= 0 Then
            myMessages.blankValue(Me, "Group Code", Me.Text)
            fndgroupcode.Focus()
            Return
        ElseIf rdtxtgroupdesc.Text = "" Then
            myMessages.blankValue(Me, "Group Desc", Me.Text)
            fndgroupcode.Focus()
        ElseIf IsVendorGrpDetailMandatory Then
            If (fndaccountset.Value = "") Then
                myMessages.blankValue(Me, "Account Set Code", Me.Text)
                fndaccountset.Focus()
            ElseIf (fndtermscode.Value = "") Then
                myMessages.blankValue(Me, "Terms Code", Me.Text)
                fndtermscode.Focus()
            ElseIf (fndbankcode.Value = "") Then
                myMessages.blankValue(Me, "Bank Code", Me.Text)
                fndbankcode.Focus()
            ElseIf (fndpayamentcode.Value = "") Then
                myMessages.blankValue(Me, "Payamnet Code", Me.Text)
                fndpayamentcode.Focus()
            ElseIf (fndtaxgroup.Value = "") Then
                myMessages.blankValue(Me, "Tax Group", Me.Text)
                fndtaxgroup.Focus()
            End If


        Else
            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.vendorgroup, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            If rdbtnsave.Text = "Save" Then
                If chkDefaultVSP.Checked = True Then
                    Dim strDefaultVSP_Cust_Group_Code As String = clsCommon.myCstr(clsDBFuncationality.getSingleValue("Select Ven_Group_Code from TSPL_VENDOR_GROUP where Default_VSP = 1 "))
                    If clsCommon.myLen(strDefaultVSP_Cust_Group_Code) > 0 Then
                        clsCommon.MyMessageBoxShow("System Allow Only One Default VSP,Currently Vendor Group  " + strDefaultVSP_Cust_Group_Code + "  is Default VSP.", Me.Text)
                        Return
                    End If
                End If
                funinsert()
                funfill()
                rdbtndelete.Enabled = True
            ElseIf rdbtnsave.Text = "Update" Then
                If chkDefaultVSP.Checked = True Then
                    Dim strDefaultVSP_Cust_Group_Code As String = clsCommon.myCstr(clsDBFuncationality.getSingleValue("Select Ven_Group_Code from TSPL_VENDOR_GROUP where Default_VSP = 1 "))
                    If clsCommon.myLen(strDefaultVSP_Cust_Group_Code) > 0 Then
                        If clsCommon.CompairString(strDefaultVSP_Cust_Group_Code, fndgroupcode.Value) = CompairStringResult.Equal Then

                        Else
                            clsCommon.MyMessageBoxShow("System Allow Only One Default VSP,Currently Vendor Group  " + strDefaultVSP_Cust_Group_Code + "  is Default VSP.", Me.Text)
                            Return
                        End If
                    End If
                End If
                funupdate()
                rdbtndelete.Enabled = True

            End If
        End If
    End Sub
    Private Sub rdbtndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtndelete.Click
        If clsCommon.myLen(fndbankcode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "You Cannot Delete Record", Me.Text)
            Exit Sub
        End If
        If myMessages.deleteConfirm() Then
            funddelete()
            myMessages.delete()
            rdbtnsave.Text = "Save"
            rdbtndelete.Enabled = False
        End If
    End Sub

    Private Sub rdbtnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnclose.Click
        Me.Close()
    End Sub
    Private Sub fndgroupcode_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndgroupcode.Query = "select ven_group_code as [Vendor Group Code],group_desc as [Description] from tspl_vendor_group"
        'fndgroupcode.ConnectionString = connectSql.SqlCon()
        'fndgroupcode.Caption = "Group Code"
        'fndgroupcode.ValueToSelect = "Vendor Group Code"
        'fndgroupcode.ValueToSelect1 = "Description"
    End Sub
    Sub groupcode_textchanged()
        Dim query As String = "select ven_group_code from tspl_vendor_group where ven_group_code ='" + fndgroupcode.Value + "'"
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(query)
        Dim var As String = ""
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            For Each row As DataRow In dt.Rows
                var = row(0).ToString()
            Next
        End If
        If var <> "" Then
            funfill()
            rdbtnsave.Text = "Update"
            rdtxtaccountset.ReadOnly = True
            rdtxttermscode.ReadOnly = True
            rdtxtbankcode.ReadOnly = True
            rdtxtpayametcode.ReadOnly = True
            rdtxttaxgroup.ReadOnly = True
            rdbtndelete.Enabled = True
        Else
            rdbtnsave.Text = "Save"
            rdtxtgroupdesc.Text = ""
            fndaccountset.Value = ""
            rdtxtaccountset.Text = ""
            rdtxtaccountset.ReadOnly = True
            fndtermscode.Value = ""
            rdtxttermscode.Text = ""
            rdtxttermscode.ReadOnly = True
            fndbankcode.Value = ""
            rdtxtbankcode.Text = ""
            rdtxtbankcode.ReadOnly = True
            fndpayamentcode.Value = ""
            rdtxtpayametcode.Text = ""
            rdtxtpayametcode.ReadOnly = True
            fndtaxgroup.Value = ""
            rdtxttaxgroup.Text = ""
            rdbtndelete.Enabled = False
        End If
    End Sub
    Public Sub groupcode_textchanged(ByVal sender As System.Object, ByVal e As System.EventArgs)

        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub
    Public Sub funfill()
        Dim query As String = "Select group_desc,acct_set_code,acct_set_desc,terms_code,terms_desc,payment_code,payment_desc,bank_code,description,tax_group_code,tax_group_desc,Is_TDSApplicable,Vendor_Sub_Group,Default_VSP from tspl_vendor_group where ven_group_code='" + fndgroupcode.Value + "'"
        Dim adp As New SqlDataAdapter(query, connectSql.SqlCon())
        Dim dt As New DataTable()
        adp.Fill(dt)
        Dim dr As DataRow = dt.Rows(0)
        rdtxtgroupdesc.Text = dr(0).ToString()
        fndaccountset.Value = dr(1).ToString()
        rdtxtaccountset.Text = dr(2).ToString()
        fndtermscode.Value = dr(3).ToString()
        rdtxttermscode.Text = dr(4).ToString()
        fndpayamentcode.Value = dr(5).ToString()
        rdtxtpayametcode.Text = dr(6).ToString()
        fndbankcode.Value = dr(7).ToString()
        rdtxtbankcode.Text = dr(8).ToString()
        fndtaxgroup.Value = dr(9).ToString()
        rdtxttaxgroup.Text = dr(10).ToString()
        chk_istdsapplicable.Checked = IIf(clsCommon.myCstr(dr("Is_TDSApplicable").ToString()) = 1, True, False)
        fndSubGroup.Value = dr(12).ToString()
        txtSubGroup.Text = clsDBFuncationality.getSingleValue("Select SubGroup_Desc from TSPL_VENDOR_SUB_GROUP where Ven_Sub_Group_Code='" + fndSubGroup.Value + "'")
        chkDefaultVSP.Checked = IIf(clsCommon.myCstr(dr("Default_VSP").ToString()) = 1, True, False)
        rdbtnsave.Text = "Update"


    End Sub
    Private Sub fndaccountset_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndaccountset.Query = "Select acct_set_code as [Account Set],acct_set_desc as [Description] from tspl_vendor_account_set"
        'fndaccountset.ConnectionString = connectSql.SqlCon()
        'fndaccountset.Caption = "Account Set"
        'fndaccountset.ValueToSelect = "Account Set"
        'fndaccountset.ValueToSelect1 = "Description"
    End Sub
    Sub acctsetcode_textchanged()
        Try
            Dim query As String = "Select acct_set_code as [Account Set],acct_set_desc as [Description] from tspl_vendor_account_set where acct_set_code='" + fndaccountset.Value() + "'"
            Dim dt As DataTable
            dt = clsDBFuncationality.GetDataTable(query)
            Dim var As String = ""
            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
                For Each row As DataRow In dt.Rows
                    var = row(0).ToString()
                Next
            End If
            If var <> "" Then
                accountfunfill()
            Else
                rdtxtaccountset.Text = ""
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub
    Public Sub acctsetcode_textchanged(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Public Sub accountfunfill()
        Dim query As String = "Select acct_set_code as [Account Set],acct_set_desc as [Description] from tspl_vendor_account_set where acct_set_code='" + fndaccountset.Value() + "'"
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(query)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

            For Each row As DataRow In dt.Rows
                rdtxtaccountset.Text = row(1).ToString()
            Next
        End If
    End Sub
    Sub accountset_leave()
        If fndaccountset.Value = "" Then

        Else
            Try
                Dim query As String = "Select acct_set_code as [Account Set],acct_set_desc as [Description] from tspl_vendor_account_set where acct_set_code='" + fndaccountset.Value() + "'"
                Dim dt As DataTable
                Dim strvalue As String = ""

                dt = clsDBFuncationality.GetDataTable(query)
                If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

                    For Each row As DataRow In dt.Rows
                        strvalue = row(0).ToString()
                    Next
                End if



                If strvalue <> "" Then

                Else : query = ""

                    rdtxtaccountset.Text = ""
                    common.clsCommon.MyMessageBoxShow(Me, "This Account Set Code does not exist", Me.Text)
                    fndaccountset.Value = ""


                End If


            Catch ex As Exception
                myMessages.myExceptions(ex)
            End Try
        End If

    End Sub
    Public Sub accountset_leave(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Private Sub fndtermscode_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndtermscode.Query = "Select terms_code as [Terms Code],terms_desc as [Description] from tspl_terms_master"
        'fndtermscode.ConnectionString = connectSql.SqlCon()
        'fndtermscode.Caption = "Terms Code Account"
        'fndtermscode.ValueToSelect = "Terms Code"
        'fndtermscode.ValueToSelect1 = "Description"
    End Sub
    Sub termscode_textchanged()
        Try
            Dim query As String = "Select terms_code ,terms_desc  from tspl_terms_master where terms_code='" + fndtermscode.Value() + "'"
            Dim dt As DataTable
            dt = clsDBFuncationality.GetDataTable(query)
            Dim var As String = ""
            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

                For Each row As DataRow In dt.Rows
                    var = row(0).ToString()
                Next
            End If
            If var <> "" Then
                termscodefunfill()
            Else
                rdtxttermscode.Text = ""
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub
    Public Sub termscode_textchanged(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Public Sub termscodefunfill()
        Dim query As String = "Select terms_code as [Terms Code],terms_desc as [Description] from tspl_terms_master where terms_code='" + fndtermscode.Value() + "'"
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(query)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

            For Each row As DataRow In dt.Rows
                rdtxttermscode.Text = row(1).ToString()
            Next
End if
    End Sub
    Sub termscode_leave()
        If fndtermscode.Value = "" Then

        Else
            Try
                Dim query As String = "Select terms_code as [Terms Code],terms_desc as [Description] from tspl_terms_master where terms_code='" + fndtermscode.Value() + "'"
                Dim dt As DataTable
                Dim strvalue As String = ""
                dt = clsDBFuncationality.GetDataTable(query)
                If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

                    For Each row As DataRow In dt.Rows
                        strvalue = row(0).ToString()
                    Next
End if



                If strvalue <> "" Then

                Else : query = ""

                    rdtxttermscode.Text = ""
                    common.clsCommon.MyMessageBoxShow(Me, "This Terms Code does not exist", Me.Text)
                    fndtermscode.Value = ""


                End If


            Catch ex As Exception
                myMessages.myExceptions(ex)
            End Try
        End If

    End Sub
    Public Sub termscode_leave(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub

    Private Sub fndbankcode_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndbankcode.Query = "Select bank_code as [Bank Code],description as [Description] from tspl_bank_master"
        'fndbankcode.ConnectionString = connectSql.SqlCon()
        'fndbankcode.Caption = "Bank Code Account"
        'fndbankcode.ValueToSelect = "Bank Code"
        'fndbankcode.ValueToSelect1 = "Description"
    End Sub
    Sub bankcode_textchanged()
        Try
            Dim dt As DataTable
            Dim query As String = "Select bank_code as [Bank Code],description as [Description] from tspl_bank_master where bank_code='" + fndbankcode.Value() + "'"
            dt = clsDBFuncationality.GetDataTable(query)
            Dim var As String = ""
            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

                For Each row As DataRow In dt.Rows
                    var = row(0).ToString()
                Next
End if
            If var <> "" Then
                bankcodefunfill()
            Else
                rdtxtbankcode.Text = ""
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub
    Public Sub bankcode_textchanged(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Public Sub bankcodefunfill()
        Dim dt As DataTable
        Dim query As String = "Select bank_code as [Bank Code],description as [Description] from tspl_bank_master where bank_code='" + fndbankcode.Value() + "'"
        dt = clsDBFuncationality.GetDataTable(query)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

            For Each row As DataRow In dt.Rows
                rdtxtbankcode.Text = row(1).ToString()
            Next
End If 
    End Sub
    Sub bankcode_leave()
        If fndbankcode.Value = "" Then

        Else
            Try
                Dim query As String = "Select bank_code as [Bank Code],description as [Description] from tspl_bank_master where bank_code='" + fndbankcode.Value() + "'"
                Dim dt As DataTable
                Dim strvalue As String = ""

                dt = clsDBFuncationality.GetDataTable(query)
                If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

                    For Each row As DataRow In dt.Rows
                        strvalue = row(0).ToString()
                    Next
End if



                If strvalue <> "" Then

                Else : query = ""

                    rdtxtbankcode.Text = ""
                    common.clsCommon.MyMessageBoxShow(Me, "This Bank Code does not exist", Me.Text)
                    fndbankcode.Value = ""


                End If


            Catch ex As Exception
                myMessages.myExceptions(ex)
            End Try
        End If

    End Sub
    Public Sub bankcode_leave(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Private Sub fndpayamentcode_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndpayamentcode.Query = "Select payment_code as [Payment Code],payment_desc as [Description] from tspl_payment_code"
        'fndpayamentcode.ConnectionString = connectSql.SqlCon()
        'fndpayamentcode.Caption = "Payment Code Account"
        'fndpayamentcode.ValueToSelect = "Payment Code"
        'fndpayamentcode.ValueToSelect1 = "Description"
    End Sub
    Sub payamentcode_textchanged()
        Try
            Dim dt As DataTable
            Dim query As String = "Select payment_code as [Payment Code],payment_desc as [Description] from tspl_payment_code where payment_code='" + fndpayamentcode.Value() + "'"
            dt = clsDBFuncationality.GetDataTable(query)
            Dim var As String = ""
            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

                For Each row As DataRow In dt.Rows
                    var = row(0).ToString()
                Next
End if
            If var <> "" Then
                paymentcodefunfill()
            Else
                rdtxtpayametcode.Text = ""
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub
    Public Sub payamentcode_textchanged(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Public Sub paymentcodefunfill()
        Dim query As String = "Select payment_code as [Payment Code],payment_desc as [Description] from tspl_payment_code where payment_code='" + fndpayamentcode.Value() + "'"
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(query)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

            For Each row As DataRow In dt.Rows
                rdtxtpayametcode.Text = row(1).ToString()
            Next
        End if
    End Sub
    Sub paymentcode_leave()
        If fndpayamentcode.Value = "" Then

        Else
            Try
                Dim query As String = "Select payment_code as [Payment Code],payment_desc as [Description] from tspl_payment_code where payment_code='" + fndpayamentcode.Value() + "'"
                Dim dt As DataTable
                Dim strvalue As String = ""

                dt = clsDBFuncationality.GetDataTable(query)
                If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

                    For Each row As DataRow In dt.Rows
                        strvalue = row(0).ToString()
                    Next
End if

                If strvalue <> "" Then

                Else : query = ""

                    rdtxtpayametcode.Text = ""
                    common.clsCommon.MyMessageBoxShow(Me, "This Payment Code does not exist", Me.Text)
                    fndpayamentcode.Value = ""


                End If


            Catch ex As Exception
                myMessages.myExceptions(ex)
            End Try
        End If

    End Sub
    Public Sub paymentcode_leave(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Private Sub fndtaxgroup_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndtaxgroup.Query = "Select tax_group_code as [Tax Group Code],tax_group_desc as [Description] from tspl_tax_group_master"
        'fndtaxgroup.ConnectionString = connectSql.SqlCon()
        'fndtaxgroup.Caption = "Tax Group Code"
        'fndtaxgroup.ValueToSelect = "Tax Group Code"
        'fndtaxgroup.ValueToSelect1 = "Description"
    End Sub
    Sub taxgroup_textchanged()
        Try
            Dim dt As DataTable
            Dim query As String = "Select tax_group_code as [Tax Group Code],tax_group_desc as [Description] from tspl_tax_group_master where tax_group_code ='" + fndtaxgroup.Value() + "'"
            dt = clsDBFuncationality.GetDataTable(query)
            Dim var As String = ""
            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

                For Each row As DataRow In dt.Rows
                    var = row(0).ToString()
                Next
           End If 
            If var <> "" Then
                taxgroupfunfill()
            Else
                rdtxtgroupdesc.Text = ""
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub
    Public Sub taxgroup_textchanged(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Public Sub taxgroupfunfill()
        Dim query As String = " Select tax_group_code as [Tax Group Code],tax_group_desc as [Description] from tspl_tax_group_master where tax_group_code ='" + fndtaxgroup.Value() + "'"
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(query)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

            For Each row As DataRow In dt.Rows
                rdtxttaxgroup.Text = row(1).ToString()
            Next
End if
    End Sub
    Sub taxgroup_leave()
        If fndtaxgroup.Value = "" Then

        Else
            Try
                Dim query As String = "Select tax_group_code as [Tax Group Code],tax_group_desc as [Description] from tspl_tax_group_master where tax_group_code ='" + fndtaxgroup.Value() + "'"
                Dim dt As DataTable
                Dim strvalue As String = ""

                dt = clsDBFuncationality.GetDataTable(query)
                If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then

                    For Each row As DataRow In dt.Rows
                        strvalue = row(0).ToString()
                    Next
End if



                If strvalue <> "" Then

                Else : query = ""

                    rdtxttaxgroup.Text = ""
                    common.clsCommon.MyMessageBoxShow(Me, "This Tax Group Code does not exist", Me.Text)
                    fndtaxgroup.Value = ""


                End If


            Catch ex As Exception
                myMessages.myExceptions(ex)
            End Try
        End If

    End Sub
    Public Sub taxgroup_leave(ByVal sender As System.Object, ByVal e As System.EventArgs)
      
    End Sub
    Private Sub rdmenuimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuimport.Click
        Dim dgv As New RadGridView
        Me.Controls.Add(dgv)
        If transportSql.importExcel(dgv, "Vendor Group Code", "Description", "Account Set", "Account Set Description", "Terms Code", "Terms Descriptiion", "Payment Code", "Payment Code Description", "Bank Code", "Bank Code Description", "Tax Group", "Tax Group Description", "Is TDS Applicable", "Vendor Sub Group", "Is Default VSP") Then
            Dim trans As SqlTransaction = Nothing
            Try
                trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each dgrv As GridViewRowInfo In dgv.Rows
                    Dim ISTDS As Integer = 0
                    Dim ISDefaultVSP As Integer = 0
                    Dim strvendorgroupcode As String = clsCommon.myCstr(dgrv.Cells(0).Value)
                    Dim strdisc As String = clsCommon.myCstr(dgrv.Cells(1).Value)
                    Dim straccountset As String = clsCommon.myCstr(dgrv.Cells(2).Value)
                    Dim stracctsetdescription As String = clsCommon.myCstr(dgrv.Cells(3).Value)
                    Dim strtermscode As String = clsCommon.myCstr(dgrv.Cells(4).Value)
                    Dim strtermsdescription As String = clsCommon.myCstr(dgrv.Cells(5).Value)
                    Dim strpaymentcode As String = clsCommon.myCstr(dgrv.Cells(6).Value)
                    Dim strpaymentcodedescription As String = clsCommon.myCstr(dgrv.Cells(7).Value)
                    Dim strbankcode As String = clsCommon.myCstr(dgrv.Cells(8).Value)
                    Dim strbankcodedescription As String = clsCommon.myCstr(dgrv.Cells(9).Value)
                    Dim strtaxgroup As String = clsCommon.myCstr(dgrv.Cells(10).Value)
                    Dim strtaxdescription As String = clsCommon.myCstr(dgrv.Cells(11).Value)
                    Dim Datee As String = clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy")
                    Dim IsTDSApplicable As String = clsCommon.myCstr(dgrv.Cells("Is TDS Applicable").Value)
                    Dim VendorSubGroup As String = clsCommon.myCstr(dgrv.Cells(13).Value)
                    Dim strDefaultVSP As String = clsCommon.myCstr(dgrv.Cells("Is Default VSP").Value)
                    If String.IsNullOrEmpty(strvendorgroupcode) Or strvendorgroupcode.Length > 12 Then
                        Throw New Exception("Vendor Acccount has some incorrect values")
                        trans.Rollback()
                        Exit Sub
                    End If
                    If clsCommon.myLen(strdisc) > 50 Then
                        Throw New Exception("Check the length of Description")
                    End If
                    ' Ticket No : TEC/19/06/19-000554 By Prabhakar
                    If (clsCommon.myLen(straccountset) > 12) Or (clsCommon.myLen(stracctsetdescription) > 100) Then
                        Throw New Exception("Check the length of Account Set")
                    End If

                    If (clsCommon.myLen(strtermscode) > 12) Or (clsCommon.myLen(strtermsdescription) > 50) Then
                        Throw New Exception("Check the length of Terms Code")
                    End If

                    If (clsCommon.myLen(strpaymentcode) > 12) Or (clsCommon.myLen(strpaymentcodedescription) > 50) Then
                        Throw New Exception("Check the length of Payment Code")
                    End If

                    If (clsCommon.myLen(strbankcode) > 12) Or (clsCommon.myLen(strbankcodedescription) > 50) Then
                        Throw New Exception("Check the length of Bank Code")
                    End If

                    If (clsCommon.myLen(strtaxgroup) > 12) Or (clsCommon.myLen(strtaxdescription) > 50) Then
                        Throw New Exception("Check the length of Tax Group")
                    End If

                    If clsCommon.CompairString(clsCommon.myCstr(IsTDSApplicable), "Y") = CompairStringResult.Equal Then
                        ISTDS = 1
                    ElseIf clsCommon.CompairString(clsCommon.myCstr(IsTDSApplicable), "N") = CompairStringResult.Equal Then
                        ISTDS = 0
                    Else
                        Throw New Exception("Fill 'Is TDS Applicable' in 'Y/N' format")
                    End If

                    ' IsDefaultVSP
                    If clsCommon.CompairString(clsCommon.myCstr(strDefaultVSP), "Y") = CompairStringResult.Equal Then
                        ISDefaultVSP = 1
                    ElseIf clsCommon.CompairString(clsCommon.myCstr(strDefaultVSP), "N") = CompairStringResult.Equal Then
                        ISDefaultVSP = 0
                    Else
                        Throw New Exception("Fill 'Is Default VSP' in 'Y/N' format")
                    End If

                    Dim sql1 As String = "select count(*)from tspl_vendor_group  where ven_group_code='" + strvendorgroupcode + "'"
                    Dim i As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(sql1, trans))
                    If (i = 0) Then
                        If ISDefaultVSP = 1 Then
                            Dim chekDefaultVSP As String = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select ven_group_code from tspl_vendor_group  where Default_VSP=1", trans))
                            If clsCommon.myLen(chekDefaultVSP) > 0 Then
                                Throw New Exception("System Allow Only One Default VSP,Currently Vendor Group  " + chekDefaultVSP + "  is Default VSP.")
                            End If
                        End If
                        Dim query As String = "insert into tspl_vendor_group values('" + strvendorgroupcode + "','" + strdisc + "','" + straccountset + "','" + stracctsetdescription + "','" + strtermscode + "','" + strtermsdescription + "','" + strpaymentcode + "','" + strpaymentcodedescription + "','" + strbankcode + "','" + strbankcodedescription + "','" + strtaxgroup + "','" + strtaxdescription + "','" + userCode + "','" + Datee + "','" + userCode + "','" + Datee + "','" + companyCode + "','" + clsCommon.myCstr(ISTDS) + "','" + VendorSubGroup + "','" + clsCommon.myCstr(ISDefaultVSP) + "')"
                        connectSql.RunSqlTransaction(trans, query)
                        clsCommonFunctionality.SaveHistoryData(objCommonVar.CurrentUserCode, clsCommon.myCstr(strvendorgroupcode), "tspl_vendor_group", "ven_group_code", trans)
                        'Dim strqry As String = ""
                        'strqry = " update TSPL_VENDOR_GROUP set Vendor_Sub_Group='" & clsCommon.myCstr(VendorSubGroup) & "', Default_VSP = '" + clsCommon.myCstr(ISDefaultVSP) + "' where Ven_Group_Code='" + strvendorgroupcode + "'"
                        'clsDBFuncationality.ExecuteNonQuery(strqry, trans)
                    Else
                        If ISDefaultVSP = 1 Then
                            Dim chekDefaultVSP As String = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select ven_group_code from tspl_vendor_group  where Default_VSP=1", trans))
                            If clsCommon.CompairString(strvendorgroupcode, chekDefaultVSP) <> CompairStringResult.Equal Then
                                Throw New Exception("System Allow Only One Default VSP,Currently Vendor Group  " + chekDefaultVSP + "  is Default VSP.")
                            End If
                        End If
                        Dim query1 As String = "update tspl_vendor_group set group_desc ='" + strdisc + "',acct_set_code='" + straccountset + "',acct_set_desc ='" + stracctsetdescription + "',terms_code='" + strtermscode + "',terms_desc='" + strtermsdescription + "',payment_code='" + strpaymentcode + "',payment_desc='" + strpaymentcodedescription + "',bank_code='" + strbankcode + "',description='" + strbankcodedescription + "',tax_group_code='" + strtaxgroup + "',tax_group_desc ='" + strtaxdescription + "',Is_TDSApplicable='" + clsCommon.myCstr(ISTDS) + "' where ven_group_code='" + strvendorgroupcode + "'"
                        connectSql.RunSqlTransaction(trans, query1)
                        clsCommonFunctionality.SaveHistoryData(objCommonVar.CurrentUserCode, clsCommon.myCstr(strvendorgroupcode), "tspl_vendor_group", "ven_group_code", trans)
                        Dim strqry As String = ""
                        strqry = " update TSPL_VENDOR_GROUP set Vendor_Sub_Group='" & clsCommon.myCstr(VendorSubGroup) & "', Default_VSP = '" + clsCommon.myCstr(ISDefaultVSP) + "'  where Ven_Group_Code='" + strvendorgroupcode + "'"
                        clsDBFuncationality.ExecuteNonQuery(strqry, trans)
                    End If
                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transferred Completed", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                trans.Rollback()
                clsCommon.ProgressBarHide()

                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(dgv)
    End Sub
    Private Sub rdmenuexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexport.Click
        Dim query As String = "select ven_group_code as 'Vendor Group Code',group_desc as 'Description',acct_set_code as 'Account Set',acct_set_desc as 'Account Set Description',Terms_code as 'Terms Code',terms_desc as 'Terms Descriptiion',payment_code as 'Payment Code',payment_desc as 'Payment Code Description',Bank_Code as 'Bank Code',Description as 'Bank Code Description',tax_group_code as 'Tax Group',Tax_group_desc as 'Tax Group Description',(case when Is_TDSApplicable='1' then 'Y' else 'N' end) as 'Is TDS Applicable',Vendor_Sub_Group as [Vendor Sub Group] , (case when Default_VSP='1' then 'Y' else 'N' end) as 'Is Default VSP' from tspl_vendor_Group"
        ListImpExpColumnsMandatory = New List(Of String)({"Vendor Group Code"})
        ListImpExpColumnsSuperMandatory = New List(Of String)({"Vendor Group Code"})
        transportSql.ExporttoExcel(query, "", "", Me, ListImpExpColumnsMandatory, ListImpExpColumnsSuperMandatory, MyBase.Form_ID)
    End Sub

    Private Sub rdbtnreset_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnreset.Click
        funreset()
    End Sub

    Private Sub rdmenuexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexit.Click
        Me.Close()
    End Sub
    'priti added on 01-06-2011 --- To implement the access control
    'Private Function funSetUserAccess() As Boolean
    '    Try
    '        'If funCheckLoginStatus() = False Then Exit Function
    '        Dim strRights As String
    '        Dim strTemp() As String
    '        Dim strProgCode = "VEN-GRP"
    '        strRights = enuUserRights.enuRead & "," & enuUserRights.enuModify & "," & enuUserRights.enuDelete
    '        strRights = modUserMgt.funGetPermissions(strRights, strProgCode)
    '        strTemp = Split(strRights, ",")
    '        If strTemp(0) = "0" Then
    '            MsgBox("Permission Denied", MsgBoxStyle.Critical, Me.Text)
    '            funSetUserAccess = False
    '            blnRead = False
    '            Me.Close()
    '            Exit Function
    '        Else
    '            blnRead = True
    '        End If
    '        If strTemp(1) = "0" Then 'Grant modify access
    '            rdbtnsave.Enabled = False
    '        End If
    '        If strTemp(2) = "0" Then 'Grant modify access
    '            rdbtndelete.Enabled = False
    '        End If

    '        funSetUserAccess = True
    '    Catch er As Exception

    '    End Try
    'End Function

    Private Sub frmVendorGroup_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso rdbtnsave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            'PostData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso rdbtndelete.Enabled Then
            funddelete()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funreset()
        End If
    End Sub

    Private Sub fndgroupcode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndgroupcode._MYValidating

        If isButtonClicked Then

            'Dim qry As String = "select ven_group_code as [Vendor Group Code],group_desc as [Description] from tspl_vendor_group "
            'fndgroupcode.Value = clsCommon.ShowSelectForm("FmGpCd", qry, "Vendor Group Code", "", fndgroupcode.Value, "", isButtonClicked)
            fndgroupcode.Value = clsVendorGroupMaster.getFinder("", fndgroupcode.Value, isButtonClicked)
            rdtxtgroupdesc.Text = clsDBFuncationality.getSingleValue("Select group_desc from tspl_vendor_group where ven_group_code='" + fndgroupcode.Value + "'")
            If fndgroupcode.Value IsNot Nothing Then
                rdbtndelete.Enabled = True
            Else
                rdbtndelete.Enabled = False
            End If
            groupcode_textchanged()

        ElseIf fndgroupcode.MyReadOnly OrElse fndgroupcode.Value IsNot Nothing Then
            Dim qry As String = "Select * from TSPL_User_Group_Master where group_Code ='" + fndgroupcode.Value + "' "
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
            If dt.Rows.Count < 0 Then
                rdtxtaccountset.Text = ""
                rdtxtbankcode.Text = "'"
                rdtxtgroupdesc.Text = ""
                rdtxtpayametcode.Text = ""
                rdtxttaxgroup.Text = ""
                rdtxttermscode.Text = ""
                fndaccountset.Value = ""
                fndbankcode.Value = ""
                fndpayamentcode.Value = ""
                fndtaxgroup.Value = ""
                fndtermscode.Value = ""
                rdbtnsave.Text = "Save"
            Else
                groupcode_textchanged()
            End If

        End If
    End Sub

    Private Sub fndgroupcode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavigatorType As common.NavigatorType) Handles fndgroupcode._MYNavigator
        Dim qst As String = "select ven_group_code as [Vendor Group Code],group_desc as [Description] from tspl_vendor_group   where  2=2 "
        Select Case NavigatorType
            Case NavigatorType.Current
                '  qst += "and assign_to='" + txtassign.Value + "' "
                ' qst += "and job_code in ('" + txtcode1.Value + "')"
            Case NavigatorType.Next
                qst += "and ven_group_code in (select min(ven_group_code) from tspl_vendor_group where ven_group_code>'" + fndgroupcode.Value + "'   ) "
            Case NavigatorType.First
                qst += "and ven_group_code in (select MIN(ven_group_code) from tspl_vendor_group  )"
            Case NavigatorType.Last
                qst += "and ven_group_code in (select Max(ven_group_code) from tspl_vendor_group  )"
            Case NavigatorType.Previous
                qst += "and ven_group_code in (select max(ven_group_code) from tspl_vendor_group where ven_group_code<'" + fndgroupcode.Value + "'   )"
        End Select
        ' fun_gridfill()
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            fndgroupcode.Value = clsCommon.myCstr(dt.Rows(0)("Vendor Group Code"))
            rdtxtgroupdesc.Text = clsCommon.myCstr(dt.Rows(0)("Description"))
        End If
        'TextChanged()
        If fndgroupcode.Value IsNot Nothing Then
            rdbtndelete.Enabled = True
        Else
            rdbtndelete.Enabled = False

        End If
        groupcode_textchanged()

    End Sub

    Private Sub fndaccountset__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndaccountset._MYValidating
        ' If isButtonClicked Then
        Dim qry As String = "Select acct_set_code as [AccountSet],acct_set_desc as [Description] from tspl_vendor_account_set  "
        fndaccountset.Value = clsCommon.ShowSelectForm("FmAccSetfnd", qry, "AccountSet", "", fndaccountset.Value, "", isButtonClicked)
        rdtxtaccountset.Text = clsDBFuncationality.getSingleValue("Select acct_set_desc from tspl_vendor_account_set where acct_set_code='" + fndaccountset.Value + "'")

        acctsetcode_textchanged()
        accountset_leave()

        '  End If
    End Sub

    Private Sub fndtermscode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndtermscode._MYValidating
        'If isButtonClicked Then
        Dim qry As String = "Select terms_code as [TermsCode],terms_desc as [Description] from tspl_terms_master "
        fndtermscode.Value = clsCommon.ShowSelectForm("FmItemCdfnd", qry, "TermsCode", "", fndtermscode.Value, "", isButtonClicked)
        rdtxttermscode.Text = clsDBFuncationality.getSingleValue("Select terms_desc from tspl_terms_master where terms_code='" + fndtermscode.Value + "'")
        termscode_textchanged()
        termscode_leave()

        ' End If
    End Sub

    Private Sub fndbankcode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndbankcode._MYValidating
        ' If isButtonClicked Then
        'Dim qry As String = "Select bank_code as [BankCode],description as [Description] from tspl_bank_master "
        'fndbankcode.Value = clsCommon.ShowSelectForm("FmBankCdfndd", qry, "BankCode", "", fndbankcode.Value, "", isButtonClicked)
        'fndbankcode.Value = clsBankMaster.getFinder("", fndbankcode.Value, isButtonClicked)
        'rdtxtbankcode.Text = clsDBFuncationality.getSingleValue("Select description from tspl_bank_master where bank_code='" + fndbankcode.Value + "'")
        'bankcode_textchanged()
        'bankcode_leave()
        fndbankcode.Value = clsVendorBankMaster.GetFinder("", fndbankcode.Value, isButtonClicked)
        If clsCommon.myLen(fndbankcode.Value) > 0 Then
            Dim obj As clsVendorBankMaster = clsVendorBankMaster.GetData(fndbankcode.Value, NavigatorType.Current)
            If obj IsNot Nothing Then
                rdtxtbankcode.Text = clsCommon.myCstr(obj.Bank_Name)
            Else
                rdtxtbankcode.Text = ""
            End If
        Else
            rdtxtbankcode.Text = ""
        End If
        'End If
    End Sub

    Private Sub fndpayamentcode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndpayamentcode._MYValidating
        ' If isButtonClicked Then
        Dim qry As String = "Select payment_code as [PaymentCode],payment_desc as [Description] from tspl_payment_code"
        fndpayamentcode.Value = clsCommon.ShowSelectForm("FmPayCdid", qry, "PaymentCode", "", fndpayamentcode.Value, "", isButtonClicked)
        rdtxtpayametcode.Text = clsDBFuncationality.getSingleValue("Select payment_desc from tspl_payment_code where payment_code='" + fndpayamentcode.Value + "'")
        payamentcode_textchanged()
        paymentcode_leave()
        ' End If
    End Sub

    Private Sub fndtaxgroup__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndtaxgroup._MYValidating
        ' If isButtonClicked Then
        Dim qry As String = "Select tax_group_code as [TaxGroupCode],tax_group_desc as [Description] from tspl_tax_group_master"

        If objCommonVar.GSTApplicable And objCommonVar.GSTActiveTaxGroup Then
            fndtaxgroup.Value = clsCommon.ShowSelectForm("FmTaxGpifnd", qry, "TaxGroupCode", " Active=1", fndtaxgroup.Value, "", isButtonClicked)
        Else
            fndtaxgroup.Value = clsCommon.ShowSelectForm("FmTaxGpifnd", qry, "TaxGroupCode", "", fndtaxgroup.Value, "", isButtonClicked)
        End If
        rdtxttaxgroup.Text = clsDBFuncationality.getSingleValue("Select tax_group_desc from tspl_tax_group_master where tax_group_code='" + fndtaxgroup.Value + "'")
        taxgroup_textchanged()
        taxgroup_leave()
        ' End If
    End Sub

    Private Sub btnHistory_Click(sender As Object, e As EventArgs) Handles btnHistory.Click
        Try
            If clsCommon.myLen(fndgroupcode.Value) <= 0 Then
                clsCommon.MyMessageBoxShow(Me, "Select Vendor Group Code", Me.Text)
                Exit Sub
            End If
            clsERPFuncationalityOLD.ShowHistoryData(fndgroupcode.Value, "ven_group_code", "TSPL_VENDOR_GROUP")
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Sub
    Private Sub fndSubGroup__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndSubGroup._MYValidating
        Dim qry As String = "Select Ven_Sub_Group_Code as [Code],SubGroup_Desc as [Description] from TSPL_VENDOR_SUB_GROUP "
        fndSubGroup.Value = clsCommon.ShowSelectForm("FmItemsubfnd", qry, "Code", "", fndSubGroup.Value, "", isButtonClicked)
        txtSubGroup.Text = clsDBFuncationality.getSingleValue("Select SubGroup_Desc from TSPL_VENDOR_SUB_GROUP where Ven_Sub_Group_Code='" + fndSubGroup.Value + "'")
    End Sub
End Class
