Imports common
Imports System.Data
Imports System.Data.SqlClient
Public Class ClsSaleLevelHierarchy
    Public Level_Code As String
    Public Description As String
    Public Level_Type As String
    Public Is_First_Level As Boolean
    Public Is_Last_Level As Boolean
    Public Seq_No As Integer
    Public Sub_Type As String = ""
    Public Shared Function SaveData(ByVal obj As ClsSaleLevelHierarchy, ByVal isNewEntry As Boolean) As Boolean

        Dim isSaved As Boolean = True
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try

            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
            clsCommon.AddColumnsForChange(coll, "Is_First_Level", obj.Is_First_Level)
            clsCommon.AddColumnsForChange(coll, "Level_Type", obj.Level_Type)
            clsCommon.AddColumnsForChange(coll, "Sub_Type", obj.Sub_Type, True)
            clsCommon.AddColumnsForChange(coll, "Is_Last_Level", obj.Is_Last_Level)

            clsCommon.AddColumnsForChange(coll, "Seq_No", obj.Seq_No)
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))

            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_Sales_Hierarchy_Levels where Level_Code='" & obj.Level_Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Level_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.SalesLevelHierarchy, "", "")
                        If clsCommon.myLen(obj.Level_Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Level_Code", obj.Level_Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))

                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_Sales_Hierarchy_Levels", OMInsertOrUpdate.Insert, "", trans)
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_Sales_Hierarchy_Levels", OMInsertOrUpdate.Update, "TSPL_Sales_Hierarchy_Levels.Level_Code='" + obj.Level_Code + "'", trans)
            End If
            If isSaved Then
                trans.Commit()
            End If
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal trans As SqlTransaction, ByVal NavType As NavigatorType) As ClsSaleLevelHierarchy
        Dim obj As ClsSaleLevelHierarchy = Nothing
        Dim Arr As List(Of ClsSaleLevelHierarchy) = Nothing
        Dim qry As String = "select * from TSPL_Sales_Hierarchy_Levels where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_Sales_Hierarchy_Levels.Level_Code  = (select MIN(Level_Code ) from TSPL_Sales_Hierarchy_Levels WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_Sales_Hierarchy_Levels.Level_Code  = (select Max(Level_Code ) from TSPL_Sales_Hierarchy_Levels WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_Sales_Hierarchy_Levels.Level_Code  = (select TOP 1 Level_Code  from TSPL_Sales_Hierarchy_Levels WHERE 1=1 " + whrclas + " and Level_Code ='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_Sales_Hierarchy_Levels.Level_Code  = (select Min(Level_Code ) from TSPL_Sales_Hierarchy_Levels where Level_Code  > '" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_Sales_Hierarchy_Levels.Level_Code  = (select Max(Level_Code ) from TSPL_Sales_Hierarchy_Levels where Level_Code  < '" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsSaleLevelHierarchy()
            obj.Level_Code = clsCommon.myCstr(dt.Rows(0)("Level_Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
            obj.Level_Type = clsCommon.myCstr(dt.Rows(0)("Level_Type"))
            obj.Sub_Type = clsCommon.myCstr(dt.Rows(0)("Sub_Type"))
            obj.Is_First_Level = clsCommon.myCBool(dt.Rows(0)("Is_First_Level"))
            obj.Is_Last_Level = clsCommon.myCBool(dt.Rows(0)("Is_Last_Level"))
            obj.Seq_No = clsCommon.myCdbl(dt.Rows(0)("Seq_No"))

        End If

        Return obj
    End Function
End Class
