Imports System.Data
Imports System.Data.SqlClient
Imports common
Public Class clsSampling_Master
#Region "Variables"
    Public Code As String
    Public Description As String
    Public Account_Code As String
    Public Account_Description As String
#End Region

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsSampling_Master
        Return GetData(strCode, NavType, Nothing)
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsSampling_Master
        Dim obj As clsSampling_Master = Nothing
        Dim qry As String = "select Sampling_Code,Description,Account_Code,Account_Description from tspl_sampling_master where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and Sampling_Code = (select MIN(Sampling_Code) from tspl_sampling_master)"
            Case NavigatorType.Last
                qry += " and Sampling_Code = (select Max(Sampling_Code) from tspl_sampling_master)"
            Case NavigatorType.Next
                qry += " and Sampling_Code = (select Min(Sampling_Code) from tspl_sampling_master where  Sampling_Code>'" + strCode + "')"
            Case NavigatorType.Previous
                qry += " and Sampling_Code = (select Max(Sampling_Code) from tspl_sampling_master where Sampling_Code<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and Sampling_Code = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsSampling_Master()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Sampling_Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
            obj.Account_Code = clsCommon.myCstr(dt.Rows(0)("Account_Code"))
            obj.Account_Description = clsCommon.myCstr(dt.Rows(0)("Account_Description"))

        End If
        Return obj
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isSaved As Boolean

        Try
            isSaved = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If
            Dim obj As clsSampling_Master = clsSampling_Master.GetData(strCode, NavigatorType.Current)

            Dim qry As String
            qry = "delete from tspl_sampling_master where Sampling_Code='" + strCode + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry)


        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isSaved
    End Function
  

    Public Function SaveData(ByVal obj As clsSampling_Master, ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        'Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try

            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Account_Code", obj.Account_Code)
            clsCommon.AddColumnsForChange(coll, "Account_Description", obj.Account_Description)
            clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"))
            If isNewEntry Then

                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from tspl_sampling_master where Sampling_Code='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.SamplingMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Sampling_Code", obj.Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"))
                Dim qry As String = "SELECT Count(*)   FROM tspl_sampling_master  where Sampling_Code= '" & obj.Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "tspl_sampling_master", OMInsertOrUpdate.Insert, "")
                Else
                    Throw New Exception("This Code Is Already Exist")
                End If
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "tspl_sampling_master", OMInsertOrUpdate.Update, "Sampling_Code='" + obj.Code + "'")
            End If
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function

End Class
