Imports System.Data.SqlClient
Imports common
Public Class ClsTemplateMaster
#Region "variables"


    Public template_code As String = Nothing
    Public template_Name As String = Nothing

    Public category_code As String = Nothing
    Public category_Description As String = Nothing
    Public FA_Book_Code As String = Nothing
    Public group_code As String = Nothing
    Public group_Description As String = Nothing

    Public Acset_code As String = Nothing
    Public Acset_Description As String = Nothing

    Public CostCenter_Code As String = Nothing
    Public CostCenter_Description As String = Nothing

    Public Dep_Method_Code As String = Nothing
    Public Dep_Method_Tax_Code As String = Nothing

    Public Dep_Period_Code As String = Nothing
    Public Start_Date As Date = Nothing

    Public Dep_Rate As String = Nothing
    Public Book_Estimated_Life As String = Nothing

    Public Book_Source_value As String = Nothing
    Public Book_Source_Original_value As String = Nothing

    Public Dep_Tax_Rate As String = Nothing
    Public Book_Salvage_Value As String = Nothing
    Public Book_Salvage_Rate As Decimal

    Public Dep_Method_Name As String = Nothing ''Not a table column
    Public Dep_Period_Name As String = Nothing ''Not a table column
    Public Dep_Method_Tax_Name As String = Nothing ''Not a table column
    ''shivani[BM00000007834]
    Public Book_Net_Value As Decimal
    Public Book_Dep_Type As String = Nothing
    Public Tax_Dep_Type As String = Nothing
    ' preeti gupta 
    Public CapexSub_Code As String = Nothing
    Public Capex_Code As String = Nothing

    ''=================
    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing
#End Region
#Region "Functions"
    Public Shared Function SaveData(ByVal obj As ClsTemplateMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "template_Name", obj.template_Name)
            '' Anubhooti 21-July-2014
            clsCommon.AddColumnsForChange(coll, "Dep_Method_Code", obj.Dep_Method_Code, True)
            clsCommon.AddColumnsForChange(coll, "Dep_Method_Tax_Code", obj.Dep_Method_Tax_Code, True)
            clsCommon.AddColumnsForChange(coll, "Dep_Period_Code", obj.Dep_Period_Code, True)
            clsCommon.AddColumnsForChange(coll, "Start_Date", clsCommon.GetPrintDate(obj.Start_Date, "dd/MMM/yyyy"))
            clsCommon.AddColumnsForChange(coll, "Dep_Rate", obj.Dep_Rate)
            clsCommon.AddColumnsForChange(coll, "Book_Estimated_Life", obj.Book_Estimated_Life)
            clsCommon.AddColumnsForChange(coll, "Book_Source_value", obj.Book_Source_value)
            clsCommon.AddColumnsForChange(coll, "Book_Source_Original_value", obj.Book_Source_Original_value)
            clsCommon.AddColumnsForChange(coll, "Dep_Tax_Rate", obj.Dep_Tax_Rate)
            clsCommon.AddColumnsForChange(coll, "Book_Salvage_Value", obj.Book_Salvage_Value)
            clsCommon.AddColumnsForChange(coll, "Book_Salvage_Rate", obj.Book_Salvage_Rate)
            clsCommon.AddColumnsForChange(coll, "category_code", obj.category_code)
            clsCommon.AddColumnsForChange(coll, "group_code", obj.group_code)
            clsCommon.AddColumnsForChange(coll, "Acset_code", obj.Acset_code)
            clsCommon.AddColumnsForChange(coll, "FA_Book_Code", obj.FA_Book_Code, True)
            'clsCommon.AddColumnsForChange(coll, "Book_Salvage_Rate", obj.Book_Salvage_Rate)


            clsCommon.AddColumnsForChange(coll, "CostCenter_Code", obj.CostCenter_Code, True)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            clsCommon.AddColumnsForChange(coll, "Book_Net_Value", obj.Book_Net_Value)
            clsCommon.AddColumnsForChange(coll, "Book_Dep_Type", obj.Book_Dep_Type)
            clsCommon.AddColumnsForChange(coll, "Tax_Dep_Type", obj.Tax_Dep_Type)
            ' preeti gupta
            clsCommon.AddColumnsForChange(coll, "CapexSub_Code", obj.CapexSub_Code, True)
            clsCommon.AddColumnsForChange(coll, "Capex_Code", obj.Capex_Code, True)

            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_FA_TEMPLATE_MASTER where template_code='" & obj.template_code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.template_code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.TemplateMaster, "", "")
                        If clsCommon.myLen(obj.template_code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "template_code", obj.template_code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_FA_TEMPLATE_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else

                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_FA_TEMPLATE_MASTER", OMInsertOrUpdate.Update, "TSPL_FA_TEMPLATE_MASTER.template_code='" + obj.template_code + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsTemplateMaster
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsTemplateMaster
        Dim obj As ClsTemplateMaster = Nothing
        Dim Arr As List(Of ClsTemplateMaster) = Nothing
        Dim qry As String = "select template_code,template_Name,FA_Book_Code,category_code,group_code,Acset_code,CostCenter_Code,Dep_Method_Tax_Code,Dep_Method_Code,Dep_Period_Code,isnull(Start_Date,null) as Start_Date,Dep_Rate,Book_Estimated_Life,Book_Source_value,Book_Source_Original_value,Dep_Tax_Rate,Book_Salvage_Value,TSPL_DEPRECIATION_METHOD.Description as Dep_Method_Name,TSPL_DEPRECIATION_PERIODS.period_Desc as Dep_Period_Name,DepMethodTax.Description as  Dep_Method_Tax_Name,Book_Salvage_Rate, Book_Dep_Type ,Book_Net_Value,Tax_Dep_Type,CapexSub_Code,Capex_Code  from  TSPL_FA_TEMPLATE_MASTER " & _
         " left outer join TSPL_DEPRECIATION_METHOD on TSPL_DEPRECIATION_METHOD.Code=TSPL_FA_TEMPLATE_MASTER.Dep_Method_Code " & _
         " left outer join TSPL_DEPRECIATION_METHOD as DepMethodTax on DepMethodTax.Code=TSPL_FA_TEMPLATE_MASTER.Dep_Method_Tax_Code " & _
         " left outer join TSPL_DEPRECIATION_PERIODS on TSPL_DEPRECIATION_PERIODS.period_Code=TSPL_FA_TEMPLATE_MASTER.Dep_Period_Code " & _
         " where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_FA_TEMPLATE_MASTER.template_code = (select MIN(template_code) from TSPL_FA_TEMPLATE_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_FA_TEMPLATE_MASTER.template_code = (select Max(template_code) from TSPL_FA_TEMPLATE_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_FA_TEMPLATE_MASTER.template_code = (select top 1 template_code from TSPL_FA_TEMPLATE_MASTER WHERE 1=1 " + whrclas + " and template_code='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_FA_TEMPLATE_MASTER.template_code = (select Min(template_code) from TSPL_FA_TEMPLATE_MASTER where template_code>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_FA_TEMPLATE_MASTER.template_code = (select Max(template_code) from TSPL_FA_TEMPLATE_MASTER where template_code<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsTemplateMaster()
            obj.template_code = clsCommon.myCstr(dt.Rows(0)("template_code"))
            obj.template_Name = clsCommon.myCstr(dt.Rows(0)("template_Name"))
            obj.category_code = clsCommon.myCstr(dt.Rows(0)("category_code"))
            obj.group_code = clsCommon.myCstr(dt.Rows(0)("group_code"))
            obj.Acset_code = clsCommon.myCstr(dt.Rows(0)("Acset_code"))
            obj.CostCenter_Code = clsCommon.myCstr(dt.Rows(0)("CostCenter_Code"))
            obj.category_Description = clsDBFuncationality.getSingleValue("Select Description from TSPL_ASSET_CATEGORY where Category_Code='" + obj.category_code + "' ")
            obj.group_Description = clsDBFuncationality.getSingleValue("Select Description from TSPL_ASSET_GROUP where Group_Code='" + obj.group_code + "' ")
            obj.Acset_Description = clsCommon.myCstr(clsDBFuncationality.getSingleValue("Select AcSet_Desc from TSPL_Dep_AccountSet WHERE AcSet_Code ='" + obj.Acset_code + "'"))
            obj.CostCenter_Description = clsCommon.myCstr(clsDBFuncationality.getSingleValue("Select CostCenter_name from TSPL_FA_COST_CENTER_MASTER WHERE CostCenter_Code ='" + obj.CostCenter_Code + "'"))

            obj.Dep_Method_Code = clsDBFuncationality.getSingleValue("select Description from TSPL_DEPRECIATION_METHOD where Code='" + obj.Dep_Method_Code + "' ")
            obj.Dep_Method_Tax_Code = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Description from TSPL_DEPRECIATION_METHOD where Code='" + obj.Dep_Method_Tax_Code + "'"))
            obj.Dep_Period_Code = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select  period_Desc from TSPL_DEPRECIATION_PERIODS where period_Code ='" + obj.Dep_Period_Code + "'"))
            obj.Dep_Method_Code = clsCommon.myCstr(dt.Rows(0)("Dep_Method_Code"))
            obj.Dep_Method_Name = clsCommon.myCstr(dt.Rows(0)("Dep_Method_Name"))
            obj.Dep_Method_Tax_Code = clsCommon.myCstr(dt.Rows(0)("Dep_Method_Tax_Code"))
            obj.Dep_Method_Tax_Name = clsCommon.myCstr(dt.Rows(0)("Dep_Method_Tax_Name"))
            obj.Dep_Period_Code = clsCommon.myCstr(dt.Rows(0)("Dep_Period_Code"))
            obj.FA_Book_Code = clsCommon.myCstr(dt.Rows(0)("FA_Book_Code"))
            obj.Dep_Period_Name = clsCommon.myCstr(dt.Rows(0)("Dep_Period_Name"))
            If clsCommon.myLen(dt.Rows(0)("Start_Date")) > 0 Then
                obj.Start_Date = clsCommon.myCDate(dt.Rows(0)("Start_Date"))
            End If
            obj.Dep_Rate = clsCommon.myCdbl(dt.Rows(0)("Dep_Rate"))
            obj.Book_Estimated_Life = clsCommon.myCdbl(dt.Rows(0)("Book_Estimated_Life"))
            obj.Book_Source_value = clsCommon.myCdbl(dt.Rows(0)("Book_Source_value"))
            obj.Book_Source_Original_value = clsCommon.myCdbl(dt.Rows(0)("Book_Source_Original_value"))
            obj.Book_Salvage_Value = clsCommon.myCdbl(dt.Rows(0)("Book_Salvage_Value"))
            obj.Book_Salvage_Rate = clsCommon.myCdbl(dt.Rows(0)("Book_Salvage_Rate"))
            obj.Dep_Tax_Rate = clsCommon.myCdbl(dt.Rows(0)("Dep_Tax_Rate"))
            obj.Book_Net_Value = clsCommon.myCdbl(dt.Rows(0)("Book_Net_Value"))
            obj.Book_Dep_Type = clsCommon.myCstr(dt.Rows(0)("Book_Dep_Type"))
            obj.Tax_Dep_Type = clsCommon.myCstr(dt.Rows(0)("Tax_Dep_Type"))
            obj.CapexSub_Code = clsCommon.myCstr(dt.Rows(0)("CapexSub_Code"))
            obj.Capex_Code = clsCommon.myCstr(dt.Rows(0)("Capex_Code"))
        End If
        Return obj
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isDelete As Boolean
        Try
            isDelete = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_FA_TEMPLATE_MASTER where template_code ='" + strCode + "'"
            isDelete = clsDBFuncationality.ExecuteNonQuery(qry)
        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isDelete
    End Function
    Public Shared Function GetName(ByVal strCode As String, ByVal trans As SqlTransaction) As String
        Try
            Dim qry As String = "select template_Name from TSPL_FA_TEMPLATE_MASTER where Template_Code='" + strCode + "'"
            Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
#End Region
End Class
