Imports System.Data.SqlClient
Imports common
Public Class clsWarranty
#Region "variables"
    Public Code As String = Nothing
    Public Name As String = Nothing
    Public Is_Lift_Time As Boolean = False
    Public Warranty_Days As Integer = 0
    Public Effective_Days As Integer = 0
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_WARRANTY_MASTER.Code as [Code] ,TSPL_WARRANTY_MASTER.Name as [Name] ,TSPL_WARRANTY_MASTER.Is_Lift_Time as [Is Lift Time] ,TSPL_WARRANTY_MASTER.Warranty_Days as [Warranty Days] ,TSPL_WARRANTY_MASTER.Effective_Days as [Effective Days] ,TSPL_WARRANTY_MASTER.Created_By as [Created By] ,TSPL_WARRANTY_MASTER.Created_Date as [Created Date] ,TSPL_WARRANTY_MASTER.Modified_By as [Modified By] ,TSPL_WARRANTY_MASTER.Modified_Date as [Modified Date] ,TSPL_WARRANTY_MASTER.Comp_Code as [Company Code]  From TSPL_WARRANTY_MASTER   "
        str = clsCommon.ShowSelectForm("WRNMST", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Function SaveData(ByVal obj As clsWarranty, ByVal isNew As Boolean) As Boolean
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            SaveData(obj, isNew, trans)
            trans.Commit()
        Catch ex As Exception
            trans.Rollback()
            Throw New Exception(ex.Message)
        End Try
        Return True
    End Function

    Public Function SaveData(ByVal obj As clsWarranty, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Name", obj.Name)
            clsCommon.AddColumnsForChange(coll, "Is_Lift_Time", IIf(obj.Is_Lift_Time, 1, 0))
            clsCommon.AddColumnsForChange(coll, "Warranty_Days", obj.Warranty_Days)
            clsCommon.AddColumnsForChange(coll, "Effective_Days", obj.Effective_Days)
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode, True)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_WARRANTY_MASTER where Code='" & obj.Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.Warranty, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_WARRANTY_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_WARRANTY_MASTER", OMInsertOrUpdate.Update, "TSPL_WARRANTY_MASTER.Code='" + obj.Code + "'", trans)
            End If
        Catch err As Exception

            Throw New Exception(err.Message)
        End Try
        Return True
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsWarranty
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsWarranty
        Dim obj As clsWarranty = Nothing
        Dim Arr As List(Of clsWarranty) = Nothing
        Dim qry As String = " select * from TSPL_WARRANTY_MASTER "
        qry += " where 2=2 "

        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_WARRANTY_MASTER.Code = (select MIN(Code) from TSPL_WARRANTY_MASTER where Comp_Code = '" + objCommonVar.CurrentCompanyCode + "' )"
            Case NavigatorType.Last
                qry += " and TSPL_WARRANTY_MASTER.Code = (select Max(Code) from TSPL_WARRANTY_MASTER where Comp_Code = '" + objCommonVar.CurrentCompanyCode + "' )"
            Case NavigatorType.Current
                qry += " and TSPL_WARRANTY_MASTER.Code =  '" + strCode + "' and TSPL_WARRANTY_MASTER.Comp_Code = '" + objCommonVar.CurrentCompanyCode + "'  "
            Case NavigatorType.Next
                qry += " and TSPL_WARRANTY_MASTER.Code = (select Min(Code) from TSPL_WARRANTY_MASTER where Code>'" + strCode + "' and Comp_Code = '" + objCommonVar.CurrentCompanyCode + "' )"
            Case NavigatorType.Previous
                qry += " and TSPL_WARRANTY_MASTER.Code = (select Max(Code) from TSPL_WARRANTY_MASTER where Code<'" + strCode + "'  and Comp_Code = '" + objCommonVar.CurrentCompanyCode + "' )"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsWarranty()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("Name"))
            obj.Is_Lift_Time = IIf(clsCommon.myCdbl(dt.Rows(0)("Is_Lift_Time")) = 1, True, False)
            obj.Warranty_Days = clsCommon.myCstr(dt.Rows(0)("Warranty_Days"))
            obj.Effective_Days = clsCommon.myCstr(dt.Rows(0)("Effective_Days"))
        End If
        Return obj
    End Function
End Class

