Imports common
Public Class FrmDeductionMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim isInsideLoadData As Boolean = False
    Dim isnewentry As Boolean = False
    Dim Errorcontrol As clsErrorControl = New clsErrorControl()
    Private Sub SetUserMgmtNew()
        ''MyBase.SetUserMgmt(clsUserMgtCode.FrmExpiryDate)
        If Not (MyBase.isReadFlag) Then
            clsCommon.MyMessageBoxShow(Me, "Permission Denied", Me.Text)
            Me.Close()
            Exit Sub
        End If
        btnSave.Visible = MyBase.isModifyFlag
        btnDelete.Visible = MyBase.isDeleteFlag
        'RadMenu1.Visible = MyBase.isExport
        If MyBase.isExport = True Then
            rmImport.Enabled = True
            rmExport.Enabled = True
        Else
            rmImport.Enabled = False
            rmExport.Enabled = False
        End If


    End Sub

    Private Sub FrmDeductionMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isnewentry = True
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        AddNew()
    End Sub

    Sub AddNew()
        ChkSecurity.Checked = False
        fndCode.Value = ""
        txtName.Text = ""
        txtNameHindi.Text = ""
        fndDedGrp.Value = ""
        lblDedGrpName.Text = ""
        FndGLAcct.Value = ""
        lblGLAcctName.Text = ""
        txtDeductionType.Value = ""
        lblDeductionType.Text = ""
        btnSave.Text = "Save"
        fndCode.MyReadOnly = False
        chkCompany.Checked = False
        ChkSecurity.Checked = False
        chkTranporter.Checked = False
        chkDefaultSecurity.Checked = False
        chkAssetInstallment.Checked = False
        chkAssetLost.Checked = False
        chkStdDeduction.Checked = False
        chkLocalSale.Checked = False
        chkAdvanceInterest.Checked = False
        chkPasuVikashKos.Checked = False
        chkOwnBMCShortage.Checked = False
        chkNegativeSRN.Checked = False
        chkOwnBMCExcess.Checked = False
        chkTIP.Checked = False
        chkVSP.Checked = False
        chkPROData.Checked = False
        chkVSPQualityDeduction.Checked = False
        chkHO.Checked = False
        chkVLC.Checked = False
        chkOTHERS.Checked = False
        txtSeqNo.Text = ""
        chkMILK.Checked = False
        chkFEED.Checked = False
        chkGHEE.Checked = False
        chkAddition.Checked = False
        chkOwnBMCMilkRejectType.Checked = False
        txtOwnBMCMilkRejectType.Value = ""
        'loadTransType()
    End Sub
    Private Function AllowToSave() As Boolean
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
                If clsCommon.myLen(clsCommon.myCstr(fndCode.Value)) <= 0 Or clsCommon.myLen(clsCommon.myCstr(fndCode.Value)) > 30 Then
                    myMessages.blankValue(Me, "Code", Me.Text)
                    fndCode.Focus()
                    fndCode.Select()
                    Errorcontrol.SetError(fndCode, "Code")
                    Return False
                Else
                    Errorcontrol.ResetError(fndCode)
                End If
            End If
            If clsCommon.myLen(clsCommon.myCstr(txtName.Text)) <= 0 Or clsCommon.myLen(clsCommon.myCstr(txtName.Text)) > 100 Then
                myMessages.blankValue(Me, "Description", Me.Text)

                txtName.Focus()
                txtName.Select()
                Errorcontrol.SetError(txtName, "Description")
                Return False
            Else
                Errorcontrol.ResetError(txtName)
            End If
            If clsCommon.myLen(clsCommon.myCstr(fndDedGrp.Value)) <= 0 Or clsCommon.myLen(clsCommon.myCstr(fndDedGrp.Value)) > 30 Then
                myMessages.blankValue(Me, "Deduction Group", Me.Text)

                txtName.Focus()
                txtName.Select()
                Errorcontrol.SetError(fndDedGrp, "Deduction Group")
                Return False
            Else
                Errorcontrol.ResetError(fndDedGrp)
            End If
            If clsCommon.myLen(clsCommon.myCstr(FndGLAcct.Value)) <= 0 Or clsCommon.myLen(clsCommon.myCstr(FndGLAcct.Value)) > 50 Then
                myMessages.blankValue(Me, "GL Account", Me.Text)

                txtName.Focus()
                txtName.Select()
                Errorcontrol.SetError(FndGLAcct, "GL Account")
                Return False
            Else
                Errorcontrol.ResetError(FndGLAcct)
            End If
            If chkOwnBMCMilkRejectType.Checked Then
                If clsCommon.myLen(txtOwnBMCMilkRejectType.Value) <= 0 Then
                    Throw New Exception("Please select Own BMC Milk Reject Type")
                End If
            End If

            If clsCommon.myLen(txtSeqNo.Text) > 0 And clsCommon.myCdbl(txtSeqNo.Text) > 0 Then
                Dim recCount As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue("select COUNT(*) from tspl_deduction_master where Sequence_No=" & clsCommon.myCdbl(txtSeqNo.Text) & " and  code<>'" & fndCode.Value & "'"))
                If recCount > 0 Then
                    clsCommon.MyMessageBoxShow(Me, "Duplicate Sequence No", Me.Text)
                    txtSeqNo.Focus()
                    txtSeqNo.Select()
                    Return False
                End If
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
        Return True
    End Function
    Sub SaveData()
        If AllowToSave() = True Then

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.FrmExpiryDate, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            Dim obj As New ClsDeductionMaster()
            obj.Code = fndCode.Value
            obj.Description = txtName.Text
            obj.Description_Hindi = txtNameHindi.Text
            obj.Ded_Grp_Code = fndDedGrp.Value
            obj.GL_Account_Code = FndGLAcct.Value
            obj.Deduction_Type = txtDeductionType.Value
            obj.Deduction_Type_Hindi = lblDeductionType.Text
            If ChkSecurity.Checked Then
                obj.Security = 1
            Else
                obj.Security = 0
            End If
            obj.Is_Default_Company_Deduction = chkCompany.Checked
            obj.Is_Default_Transporter_Deduction = chkTranporter.Checked
            obj.Is_Default_VSP_Deduction = chkVSP.Checked
            obj.Is_Default_VSP_Quality_Deduction = chkVSPQualityDeduction.Checked
            obj.Is_Default_Security_Deduction = chkDefaultSecurity.Checked
            obj.Is_Default_Asset_Installment = chkAssetInstallment.Checked
            obj.Is_Default_Asset_Lost = chkAssetLost.Checked
            obj.Is_Default_Std_Deduction = chkStdDeduction.Checked
            obj.Is_Default_Local_Sale = chkLocalSale.Checked
            obj.Is_Default_Pashu_Vikash_Kos = chkPasuVikashKos.Checked
            obj.Is_Own_BMC_Shortage = chkOwnBMCShortage.Checked
            obj.Is_Negative_SRN = chkNegativeSRN.Checked
            obj.Is_Own_BMC_Excess = chkOwnBMCExcess.Checked
            obj.Is_Default_Advance_Interest = chkAdvanceInterest.Checked
            obj.Is_Default_PRO_Data = chkPROData.Checked
            obj.Is_Default_TIP = chkTIP.Checked
            obj.Is_Transfer_To_Saving = chkTransferToSaving.Checked
            obj.Show_FAT_SNF = chkShowFATSNF.Checked
            obj.HO_TYPE = chkHO.Checked
            obj.VLC_TYPE = chkVLC.Checked
            obj.OTHERS_TYPE = chkOTHERS.Checked
            obj.Sequence_No = clsCommon.myCdbl(txtSeqNo.Text)
            'obj.Trans_Type = clsCommon.myCstr(ddlType.SelectedValue)
            obj.Is_MILK = chkMILK.Checked
            obj.Is_FEED = chkFEED.Checked
            obj.IS_GHEE = chkGHEE.Checked
            obj.Is_Addition = chkAddition.Checked
            If chkOwnBMCMilkRejectType.Checked Then
                obj.Own_BMC_Milk_Reject_Type = txtOwnBMCMilkRejectType.Value
            End If

            Dim qry As Integer = clsDBFuncationality.getSingleValue("select count(Code) from TSPL_DEDUCTION_MASTER where Code='" + obj.Code + "'")
            If (qry = 0) Then
                isnewentry = True
            Else
                isnewentry = False
            End If
            If (ClsDeductionMaster.SaveData(obj, isnewentry)) Then
                clsCommon.MyMessageBoxShow(Me, "Data saved Successfully", Me.Text)
                LoadData(obj.Code, NavigatorType.Current)
                btnSave.Text = "Update"
                btnDelete.Enabled = True
            Else
                btnSave.Text = "Save"
                btnDelete.Enabled = False
            End If
        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavType As NavigatorType)
        Try

            Dim obj As ClsDeductionMaster = ClsDeductionMaster.getdata(strCode, NavType)
            If obj IsNot Nothing Then
                fndCode.Value = obj.Code
                txtName.Text = obj.Description
                txtNameHindi.Text = obj.Description_Hindi
                fndDedGrp.Value = obj.Ded_Grp_Code
                FndGLAcct.Value = obj.GL_Account_Code
                txtDeductionType.Value = obj.Deduction_Type
                If obj.Security = 1 Then
                    ChkSecurity.Checked = True
                Else
                    ChkSecurity.Checked = False
                End If
                chkShowFATSNF.Checked = obj.Show_FAT_SNF
                chkHO.Checked = obj.HO_TYPE
                chkVLC.Checked = obj.VLC_TYPE
                chkOTHERS.Checked = obj.OTHERS_TYPE
                chkCompany.Checked = obj.Is_Default_Company_Deduction
                chkTranporter.Checked = obj.Is_Default_Transporter_Deduction
                chkVSP.Checked = obj.Is_Default_VSP_Deduction
                chkVSPQualityDeduction.Checked = obj.Is_Default_VSP_Quality_Deduction
                chkDefaultSecurity.Checked = obj.Is_Default_Security_Deduction
                chkAssetInstallment.Checked = obj.Is_Default_Asset_Installment
                chkAssetLost.Checked = obj.Is_Default_Asset_Lost
                chkStdDeduction.Checked = obj.Is_Default_Std_Deduction
                chkLocalSale.Checked = obj.Is_Default_Local_Sale
                chkPasuVikashKos.Checked = obj.Is_Default_Pashu_Vikash_Kos
                chkOwnBMCShortage.Checked = obj.Is_Own_BMC_Shortage
                chkNegativeSRN.Checked = obj.Is_Negative_SRN
                chkOwnBMCExcess.Checked = obj.Is_Own_BMC_Excess
                chkAdvanceInterest.Checked = obj.Is_Default_Advance_Interest
                chkTIP.Checked = obj.Is_Default_TIP
                chkTransferToSaving.Checked = obj.Is_Transfer_To_Saving
                chkPROData.Checked = obj.Is_Default_PRO_Data
                chkMILK.Checked = obj.Is_MILK
                chkGHEE.Checked = obj.IS_GHEE
                chkFEED.Checked = obj.Is_FEED
                chkAddition.Checked = obj.Is_Addition
                txtSeqNo.Text = obj.Sequence_No
                lblDedGrpName.Text = clsDBFuncationality.getSingleValue("select Ded_Description from TSPL_DEDUCTION_GROUP where Ded_Code='" & fndDedGrp.Value & "'")
                lblGLAcctName.Text = clsDBFuncationality.getSingleValue("select Description from TSPL_GL_ACCOUNTS where Account_Code='" & FndGLAcct.Value & "'")
                lblDeductionType.Text = obj.Deduction_Type_Hindi
                'lblDeductionType.Text = clsDBFuncationality.getSingleValue("select Description from TSPL_DEDUCTION_TYPE_MASTER where Document_No='" & txtDeductionType.Value & "'")
                If clsCommon.myLen(obj.Own_BMC_Milk_Reject_Type) > 0 Then
                    txtOwnBMCMilkRejectType.Value = obj.Own_BMC_Milk_Reject_Type
                    chkOwnBMCMilkRejectType.Checked = True
                Else
                    chkOwnBMCMilkRejectType.Checked = False
                End If
                'ddlType.SelectedValue = obj.Trans_Type
                fndCode.MyReadOnly = True
                btnSave.Text = "Update"
                btnDelete.Enabled = True
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Private Sub fndCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndCode._MYNavigator
        Try
            LoadData(fndCode.Value, NavType)
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub fndCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndCode._MYValidating
        If isButtonClicked = True Then
            Dim ary As String = " select Code,Description,Ded_Grp_Code,GL_Account_Code,Security,Sequence_No as [Sequence No] from TSPL_DEDUCTION_MASTER "
            fndCode.Value = clsCommon.ShowSelectForm("Deduction1", ary, "Code", "", fndCode.Value, "TSPL_DEDUCTION_MASTER.Code", isButtonClicked)
            If clsCommon.myLen(fndCode.Value) > 0 Then
                LoadData(fndCode.Value, NavigatorType.Current)
            End If
        End If
    End Sub

    Private Sub fndDedGrp__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndDedGrp._MYValidating
        Dim qry As String = "select Ded_Code as [Code],Ded_Description From TSPL_DEDUCTION_GROUP "
        fndDedGrp.Value = clsCommon.ShowSelectForm("Group", qry, "Code", "", fndDedGrp.Value, "Code", isButtonClicked)
        If clsCommon.myLen(fndDedGrp.Value) > 0 Then
            lblDedGrpName.Text = clsCommon.myCstr(clsDBFuncationality.getSingleValue("SELECT Ded_Description FROM TSPL_DEDUCTION_GROUP Where Ded_Code='" + fndDedGrp.Value + "'"))
        Else
            lblDedGrpName.Text = ""
        End If
    End Sub

    Private Sub FndGLAcct__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles FndGLAcct._MYValidating
        Dim Qry As String = "select  Account_Code , Description  from TSPL_GL_ACCOUNTS "
        FndGLAcct.Value = clsCommon.ShowSelectForm("FndGLAcct", Qry, "Account_Code", " ControlAccount ='Y' ", FndGLAcct.Value, "Account_Code", isButtonClicked)
        lblGLAcctName.Text = clsDBFuncationality.getSingleValue("Select Description from TSPL_GL_ACCOUNTS Where Account_Code='" + FndGLAcct.Value + "' ")


    End Sub
    Private Sub DeleteData()
        Try
            If clsCommon.myLen(fndCode.Value) <= 0 Then
                Throw New Exception("Code not found to delete")
            End If
            If clsCommon.MyMessageBoxShow(Me, "are you sure? do you want to delete this Code ('" + fndCode.Value + "')", Me.Text, MessageBoxButtons.YesNo) = System.Windows.Forms.DialogResult.Yes Then

                Dim qry As String = "DELETE FROM TSPL_DEDUCTION_MASTER WHERE Code='" + fndCode.Value + "'"
                clsDBFuncationality.ExecuteNonQuery(qry)
                clsCommon.MyMessageBoxShow(Me, "Deleted Successfully", Me.Text)
                AddNew()
            End If
        Catch ex As Exception
            If (clsCommon.CompairString(clsCommon.myCstr(ex.Message), "Code not found to delete") <> CompairStringResult.Equal) Then
                clsCommon.MyMessageBoxShow(Me, "Current Code is in use", Me.Text)
            Else
                clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
            End If
        End Try
    End Sub
    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        SaveData()
    End Sub

    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        Me.Close()
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        AddNew()
    End Sub



    Private Sub FrmDeductionMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            'DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            AddNew()
        End If
    End Sub

    Private Sub rmImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmImport.Click
        Dim gv As New RadGridView()
        Dim IsNewEntry As Boolean
        Me.Controls.Add(gv)
        If transportSql.importExcel(gv, "Code", "Description", "Deduction Group Code", "GL Account", "Security", "Company", "VSP", "Tranporter", "Default Security", "Default TIP", "Sequence No") Then
            Dim i As Integer = 1
            Try
                For Each grow As GridViewRowInfo In gv.Rows

                    Dim obj As New ClsDeductionMaster()
                    i = i + 1
                    Dim strCode As String = clsCommon.myCstr(grow.Cells("Code").Value)
                    Dim strDescription As String = clsCommon.myCstr(grow.Cells("Description").Value)
                    Dim strDedGroupCode As String = clsCommon.myCstr(grow.Cells("Deduction Group Code").Value)
                    Dim strGLAccount As String = clsCommon.myCstr(grow.Cells("GL Account").Value)
                    Dim strSecurity As String = clsCommon.myCstr(grow.Cells("Security").Value)

                    If clsCommon.myLen(strCode) <= 0 Then
                        Throw New Exception("Code should not be left blank")
                    End If
                    If clsCommon.myLen(strCode) > 30 Then
                        Throw New Exception("Code can not be larger then 30 charachter")
                    End If
                    If clsCommon.myLen(strDescription) <= 0 Then
                        Throw New Exception("Description should not be left blank")
                    End If
                    If clsCommon.myLen(strDescription) > 100 Then
                        Throw New Exception("Description can not be larger then 100 charachter")
                    End If
                    If clsCommon.myLen(strDedGroupCode) <= 0 Then
                        Throw New Exception("Deduction Group Code can not be left blank")
                    End If
                    If clsCommon.myLen(strDedGroupCode) > 30 Then
                        Throw New Exception("Deduction Group Code can not be larger then 30 charachter")
                    End If
                    If clsDBFuncationality.getSingleValue("select count(*) from TSPL_DEDUCTION_GROUP where Ded_Code='" & strDedGroupCode & "'") = 0 Then
                        Throw New Exception("Deduction Group Code could not found in master")
                    End If
                    If clsCommon.myLen(strGLAccount) <= 0 Then
                        Throw New Exception("Deduction Group Code can not be left blank")
                    End If
                    If clsCommon.myLen(strGLAccount) > 50 Then
                        Throw New Exception("GL Account can not be larger then 50 charachter")
                    End If
                    If clsDBFuncationality.getSingleValue("select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" & strGLAccount & "'") = 0 Then
                        Throw New Exception("GL Account Code could not found in master")
                    End If
                    If clsCommon.CompairString(strSecurity, "0") <> CompairStringResult.Equal AndAlso clsCommon.CompairString(strSecurity, "1") <> CompairStringResult.Equal Then
                        Throw New Exception("Status Of Security Should Be Either 0 Or 1")
                    End If

                    Dim reccount As Integer = 0
                    Dim seqNo As Int64 = 0
                    seqNo = clsCommon.myCdbl(grow.Cells("Sequence No").Value)
                    If seqNo > 0 Then
                        reccount = clsCommon.myCdbl(clsDBFuncationality.getSingleValue("select COUNT(*) from tspl_deduction_master where Sequence_No=" & seqNo & " and code<>'" & strCode & "'"))
                        If reccount > 0 Then
                            Throw New Exception("Duplicate Sequence No")
                        End If
                    End If

                    If clsCommon.myLen(strCode) > 0 AndAlso clsDBFuncationality.getSingleValue("Select count(*) from TSPL_DEDUCTION_MASTER where Code='" + strCode + "' ") > 0 Then
                        IsNewEntry = False
                    Else
                        IsNewEntry = True

                    End If
                    obj.Code = strCode
                    obj.Description = strDescription
                    obj.Ded_Grp_Code = strDedGroupCode
                    obj.GL_Account_Code = strGLAccount
                    obj.Security = strSecurity
                    obj.Is_Default_Company_Deduction = IIf(clsCommon.myCdbl(grow.Cells("Company").Value) > 0, True, False)
                    obj.Is_Default_VSP_Deduction = IIf(clsCommon.myCdbl(grow.Cells("VSP").Value) > 0, True, False)
                    obj.Is_Default_Transporter_Deduction = IIf(clsCommon.myCdbl(grow.Cells("Tranporter").Value) > 0, True, False)
                    obj.Is_Default_Security_Deduction = IIf(clsCommon.myCdbl(grow.Cells("Default Security").Value) > 0, True, False)
                    obj.Is_Default_TIP = IIf(clsCommon.myCdbl(grow.Cells("Default TIP").Value) > 0, True, False)
                    obj.Sequence_No = seqNo
                    ClsDeductionMaster.SaveData(obj, IsNewEntry)
                Next

                clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception

                clsCommon.MyMessageBoxShow(Me, ex.Message & " At Line No : " & i, Me.Text)
            End Try
        End If
    End Sub

    Private Sub rmExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmExport.Click
        Dim str As String
        str = "select Code as [Code],Description As [Description],Ded_Grp_Code as [Deduction Group Code],GL_Account_Code as [GL Account],Security,Is_Default_Company_Deduction as Company,Is_Default_VSP_Deduction as VSP,Is_Default_Transporter_Deduction as Tranporter,Is_Default_Security_Deduction as [Default Security],Is_Default_TIP as [Default TIP],Sequence_No as [Sequence No]  from TSPL_DEDUCTION_MASTER "
        ListImpExpColumnsMandatory = New List(Of String)({"Code", "Description", "Deduction Group Code", "GL Account"})
        ListImpExpColumnsSuperMandatory = New List(Of String)({"Code"})
        transportSql.ExporttoExcel(str, "", "", Me, ListImpExpColumnsMandatory, ListImpExpColumnsSuperMandatory, MyBase.Form_ID)
    End Sub

    'Private Sub loadTransType()
    '    Dim dt As New DataTable
    '    dt.Columns.Add("Code", GetType(String))
    '    dt.Columns.Add("Value", GetType(String))

    '    dt.Rows.Add("Deduction", "Deduction")
    '    dt.Rows.Add("Addition", "Addition")

    '    ddlType.DataSource = dt
    '    ddlType.DisplayMember = "Code"
    '    ddlType.ValueMember = "Value"
    'End Sub

    Private Sub chkFEED_ToggleStateChanged(sender As Object, args As StateChangedEventArgs) Handles chkFEED.ToggleStateChanged
        If chkFEED.Checked = True Then
            chkGHEE.Checked = False
            chkMILK.Checked = False
        End If
    End Sub

    Private Sub chkGHEE_ToggleStateChanged(sender As Object, args As StateChangedEventArgs) Handles chkGHEE.ToggleStateChanged
        If chkGHEE.Checked = True Then
            chkFEED.Checked = False
            chkMILK.Checked = False
        End If
    End Sub

    Private Sub chkMILK_ToggleStateChanged(sender As Object, args As StateChangedEventArgs) Handles chkMILK.ToggleStateChanged
        If chkMILK.Checked = True Then
            chkFEED.Checked = False
            chkGHEE.Checked = False
        End If
    End Sub

    Private Sub chkOwnBMCMilkReject_ToggleStateChanged(sender As Object, args As StateChangedEventArgs) Handles chkOwnBMCMilkRejectType.ToggleStateChanged
        txtOwnBMCMilkRejectType.Visible = chkOwnBMCMilkRejectType.Checked
    End Sub

    Private Sub OwnBMCMilkRejectType__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtOwnBMCMilkRejectType._MYValidating
        Dim qry As String = "select Code,Description from TSPL_MILK_REJECT_TYPE"
        Dim Whr As String = " not exists(select 1 from TSPL_DEDUCTION_MASTER where TSPL_DEDUCTION_MASTER.Own_BMC_Milk_Reject_Type=TSPL_MILK_REJECT_TYPE.Code and TSPL_DEDUCTION_MASTER.Code not in ('" + fndCode.Value + "'))"
        txtOwnBMCMilkRejectType.Value = clsCommon.ShowSelectForm("fn@Ded@Mre", qry, "Code", Whr, txtOwnBMCMilkRejectType.Value, "Code", isButtonClicked)
    End Sub

    Private Sub txtDeductionType__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtDeductionType._MYValidating
        Dim Qry As String = "SELECT Document_No,Description	 FROM TSPL_DEDUCTION_TYPE_MASTER "
        txtDeductionType.Value = clsCommon.ShowSelectForm("txtDeductionType", Qry, "Document_No", "", txtDeductionType.Value, "Document_No", isButtonClicked)
        lblDeductionType.Text = clsDBFuncationality.getSingleValue("Select isnull(Description_Hindi,'') as Description_Hindi  from TSPL_DEDUCTION_TYPE_MASTER Where Document_No='" + txtDeductionType.Value + "' ")

    End Sub
End Class
