'Created By---> Priti Sharma
'Created Date---> 12 /08 /2016
Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.OleDb
Imports System.Drawing
Imports System.IO
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls.Data
Imports Telerik.Data
Imports Telerik.WinControls.Enumerations
Imports Telerik.WinControls
Imports System.Text.RegularExpressions
Imports Telerik.WinControls.UI.Export
Imports Telerik.WinControls.UI.Export.ExportToExcelML
Imports Excel = Microsoft.Office.Interop.Excel
Imports System.Globalization
Imports common
Imports System.Threading
Public Class frmDivertedContractor
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim ReasonCode, Description, CompGroupCode, CompDesc As String
    Dim obj As New clsDivertedContractor
    Private Sub frmPrimaryReasonMaster_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso rbtnSave.Enabled Then
                saveData()

            ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso rbtnDelete.Enabled Then
                deleteData()
            ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
                Close()
            ElseIf e.Alt And e.KeyCode = Keys.N Then
                Reset()
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub


    Private Sub frmPrimaryReasonMaster_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            SetUserMgmtNew()
            fndContractCode.MyMaxLength = 30
            txtDescription.MaxLength = 200

            ButtonToolTip.SetToolTip(rbtnSave, "Press Alt+S for Save/Update ")
            ButtonToolTip.SetToolTip(rbtnDelete, "Press Alt+D  for Delete ")
            ButtonToolTip.SetToolTip(rbtnClose, "Press Alt+C Close the Window")
            Reset()
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub
    Private Sub Reset()
        Try
            fndContractCode.Value = ""
            txtDescription.Text = ""
            chkIsDiverted.Checked = False
            rbtnDelete.Enabled = False
            fndContractCode.Focus()
            rbtnSave.Text = "Save"
            fndContractCode.MyReadOnly = False
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub SetUserMgmtNew()
        ''MyBase.SetUserMgmt(clsUserMgtCode.frmDivertedContractor)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        rbtnSave.Visible = MyBase.isModifyFlag
        rbtnDelete.Visible = MyBase.isDeleteFlag
    End Sub


    Private Sub rbtnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnClose.Click
        Me.Close()
    End Sub

    Private Sub rbtnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnSave.Click
        If AllowToSave() Then saveData()
    End Sub
    Public Function AllowToSave() As Boolean
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
                If clsCommon.myLen(fndContractCode.Value) = 0 Then
                    common.clsCommon.MyMessageBoxShow("Please Enter Contractor Code")
                    Return False
                End If
            End If
            Return True
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message)
        End Try
    End Function
    Sub saveData()
        Try

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmDivertedContractor, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            obj = New clsDivertedContractor()
            obj.CONTRACTOR_CODE = fndContractCode.Value
            obj.description = txtDescription.Text
            obj.IS_DIVERTED = IIf(chkIsDiverted.Checked = True, 1, 0)

            Dim isSaved As Boolean = obj.SaveData(obj, IIf(rbtnSave.Text = "Save", True, False), Nothing)
            If isSaved Then
                common.clsCommon.MyMessageBoxShow("Data Saved Successfully")
                fndContractCode.Value = obj.CONTRACTOR_CODE
                rbtnSave.Text = "Update"
                rbtnDelete.Enabled = True
            Else
                rbtnSave.Text = "Save"
                rbtnDelete.Enabled = False
                common.clsCommon.MyMessageBoxShow("Data Could Not Saved")
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try

    End Sub
    Function deleteData() As Boolean
        Try
            If clsCommon.myLen(fndContractCode.Value) <= 0 Then
                common.clsCommon.MyMessageBoxShow("No Reason Code found to Delete", Me.Name)
                Return False
            ElseIf Not (common.clsCommon.MyMessageBoxShow("Delete the Contractor Code " + fndContractCode.Value + Environment.NewLine + " Are you sure?", Me.Text, MessageBoxButtons.YesNo, RadMessageIcon.Question) = DialogResult.Yes) Then
                Return False
            End If
            If (clsDivertedContractor.DeleteData(fndContractCode.Value)) Then
                common.clsCommon.MyMessageBoxShow("Data Deleted Sucessfully", Me.Name)
                Reset()
                Return True
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try

    End Function
    Private Sub loadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Try
            obj = New clsDivertedContractor()
            obj = clsDivertedContractor.GetData(strCode, NavTyep)
            If obj IsNot Nothing AndAlso clsCommon.myLen(obj.CONTRACTOR_CODE) > 0 Then
                Reset()
                rbtnSave.Text = "Update"
                fndContractCode.MyReadOnly = True
                fndContractCode.Value = obj.CONTRACTOR_CODE
                txtDescription.Text = obj.description
                chkIsDiverted.Checked = IIf(obj.IS_DIVERTED = 1, True, False)
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub fndReasonID__MYNavigator(ByVal sender As Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndContractCode._MYNavigator
        Try
            Dim Qry = "select count(*) from TSPL_DIVERTED_CONTRACTOR_MASTER where CONTRACTOR_CODE='" + fndContractCode.Value + "'"
            Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(Qry))
            If count = 0 Then
                fndContractCode.MyReadOnly = False
            Else
                fndContractCode.MyReadOnly = True
            End If
            loadData(fndContractCode.Value, NavType)
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try

    End Sub

    Private Sub fndReasonID__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndContractCode._MYValidating
        Try
            Dim str As String = "select TSPL_DIVERTED_CONTRACTOR_MASTER.CONTRACTOR_CODE as [Code] ,TSPL_DIVERTED_CONTRACTOR_MASTER.DESCRIPTION as [Description] ,TSPL_DIVERTED_CONTRACTOR_MASTER.IS_DIVERTED as [Is Diverted] ,TSPL_DIVERTED_CONTRACTOR_MASTER.Created_By as [Created By] ,TSPL_DIVERTED_CONTRACTOR_MASTER.Created_Date as [Created Date] ,TSPL_DIVERTED_CONTRACTOR_MASTER.Modified_By as [Modified By] ,TSPL_DIVERTED_CONTRACTOR_MASTER.Modified_Date as [Modified Date]  From TSPL_DIVERTED_CONTRACTOR_MASTER where CONTRACTOR_CODE='" + fndContractCode.Value + "' "
            Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
            If no = 0 Then
                fndContractCode.MyReadOnly = False
            Else
                fndContractCode.MyReadOnly = True
            End If
            If fndContractCode.MyReadOnly OrElse isButtonClicked Then
                fndContractCode.Value = clsDivertedContractor.getFinder("", fndContractCode.Value, isButtonClicked)
                loadData(fndContractCode.Value, NavigatorType.Current)
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub rbtnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnDelete.Click
        deleteData()
    End Sub

    Private Sub rbtnReset_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnReset.Click
        Reset()
    End Sub

   


    Private Sub rdmenuexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexit.Click
        Me.Close()
    End Sub

    Private Sub rdmenuexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexport.Click
        Try
            Dim str As String
            str = "select TSPL_DIVERTED_CONTRACTOR_MASTER.CONTRACTOR_CODE as [CONTRACTOR CODE] ,TSPL_DIVERTED_CONTRACTOR_MASTER.Description, TSPL_DIVERTED_CONTRACTOR_MASTER.IS_DIVERTED as [IS DIVERTED] from   TSPL_DIVERTED_CONTRACTOR_MASTER "
            transportSql.ExporttoExcel(str, Me)
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub rdmenuimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuimport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "CONTRACTOR CODE", "Description", "IS DIVERTED") Then
            ' Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsDivertedContractor()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells("CONTRACTOR CODE").Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Contractor Code can not be blank or incorrect.")
                    End If
                    obj.CONTRACTOR_CODE = strCode

                    Dim strDec As String = clsCommon.myCstr(grow.Cells("Description").Value)
                    If clsCommon.myLen(strDec) > 100 Then
                        Throw New Exception("Description Length can not be greater than 100.")
                    End If
                    obj.description = strDec
                    Dim IS_DIVERTED As Integer = 0
                    IS_DIVERTED = clsCommon.myCdbl(grow.Cells("IS DIVERTED").Value)
                    If Not (clsCommon.CompairString(IS_DIVERTED, "1") = CompairStringResult.Equal Or clsCommon.CompairString(IS_DIVERTED, "0") = CompairStringResult.Equal) Then
                        'Throw New Exception("[Is Purchaseable] can not be other than ('1' or '0') at line '" + LineNo + "'")
                        Throw New Exception("Is Diverted can not be other than ('1' or '0')")               
                    End If
                    obj.IS_DIVERTED = IS_DIVERTED
                    obj.SaveData(obj, clsDivertedContractor.CheckNewEntry(obj.CONTRACTOR_CODE), Nothing)
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub RadMenufile_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenufile.Click

    End Sub
End Class
