'Created By---> priti sharma
'Created Date---> 17 /08/2016
Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.OleDb
Imports System.Drawing
Imports System.IO
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls.Data
Imports Telerik.Data
Imports Telerik.WinControls.Enumerations
Imports Telerik.WinControls
Imports System.Text.RegularExpressions
Imports Telerik.WinControls.UI.Export
Imports Telerik.WinControls.UI.Export.ExportToExcelML
Imports Excel = Microsoft.Office.Interop.Excel
Imports System.Globalization
Imports common
Imports System.Threading
Public Class frmMilkTypeMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim ReasonCode, Description, CompGroupCode, CompDesc As String
    Dim obj As New clsMilkTypeMaster


    Private Sub frmPrimaryReasonMaster_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso rbtnSave.Enabled Then
                saveData()

            ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso rbtnDelete.Enabled Then
                deleteData()
            ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
                Close()
            ElseIf e.Alt And e.KeyCode = Keys.N Then
                Reset()
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub


    Private Sub frmPrimaryReasonMaster_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            SetUserMgmtNew()
            fndMilkTypeCode.MyMaxLength = 30
            txtDescription.MaxLength = 200

            ButtonToolTip.SetToolTip(rbtnSave, "Press Alt+S for Save/Update ")
            ButtonToolTip.SetToolTip(rbtnDelete, "Press Alt+D  for Delete ")
            ButtonToolTip.SetToolTip(rbtnClose, "Press Alt+C Close the Window")
            LoadMilkType()
            Reset()
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Sub LoadMilkType()
        cmbMilkType.DataSource = Nothing
        Dim dt As New DataTable()
        dt.Columns.Add("Code", GetType(String))
        dt.Columns.Add("Name", GetType(String))

        Dim dr As DataRow = Nothing
        dr = dt.NewRow()
        dr("Code") = ""
        dr("Name") = "Select"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "Cow"
        dr("Name") = "Cow"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "Buffalo"
        dr("Name") = "Buffalo"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "Goat"
        dr("Name") = "Goat"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "Camel"
        dr("Name") = "Camel"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "Mix"
        dr("Name") = "Mix"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "Others"
        dr("Name") = "Others"
        dt.Rows.Add(dr)

        cmbMilkType.DataSource = dt
        cmbMilkType.DisplayMember = "Name"
        cmbMilkType.ValueMember = "Code"
    End Sub
    Private Sub Reset()
        Try
            fndMilkTypeCode.Value = ""
            txtDescription.Text = ""
            cmbMilkType.SelectedValue = ""
            rbtnDelete.Enabled = False
            fndMilkTypeCode.Focus()
            rbtnSave.Text = "Save"
            fndMilkTypeCode.MyReadOnly = False
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub SetUserMgmtNew()
        ''MyBase.SetUserMgmt(clsUserMgtCode.frmMilkTypeMast)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow(Me, "Permission Denied", Me.Text)
            Me.Close()
            Exit Sub
        End If
        rbtnSave.Visible = MyBase.isModifyFlag
        rbtnDelete.Visible = MyBase.isDeleteFlag
    End Sub


    Private Sub rbtnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnClose.Click
        Me.Close()
    End Sub

    Private Sub rbtnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnSave.Click
        If AllowToSave() Then saveData()
    End Sub
    Public Function AllowToSave() As Boolean
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(fndMilkTypeCode.Value) = 0 Then
                common.clsCommon.MyMessageBoxShow(Me, "Please Enter Milk Type Code", Me.Text)
                Return False
            ElseIf cmbMilkType.SelectedValue = "" Then
                common.clsCommon.MyMessageBoxShow(Me, "Please Enter Milk Type", Me.Text)
                Return False
            End If

            Return True
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Function
    Sub saveData()
        Try

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmMilkTypeMast, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            obj = New clsMilkTypeMaster()
            obj.MILK_TYPE_CODE = fndMilkTypeCode.Value
            obj.DESCRIPTION = txtDescription.Text
            obj.MILK_TYPE = cmbMilkType.SelectedValue

            Dim isSaved As Boolean = obj.SaveData(obj, IIf(rbtnSave.Text = "Save", True, False), Nothing)
            If isSaved Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                fndMilkTypeCode.Value = obj.MILK_TYPE_CODE
                loadData(obj.MILK_TYPE_CODE, NavigatorType.Current)
                rbtnSave.Text = "Update"
                rbtnDelete.Enabled = True
            Else
                rbtnSave.Text = "Save"
                rbtnDelete.Enabled = False
                common.clsCommon.MyMessageBoxShow(Me, "Data Could Not Saved", Me.Text)
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Function deleteData() As Boolean
        Try
            If clsCommon.myLen(fndMilkTypeCode.Value) <= 0 Then
                common.clsCommon.MyMessageBoxShow(Me, "No Milk Type Code found to Delete", Me.Name)
                Return False
            ElseIf Not (common.clsCommon.MyMessageBoxShow("Delete the Milk Type Code " + fndMilkTypeCode.Value + Environment.NewLine + " Are you sure?", Me.Text, MessageBoxButtons.YesNo, RadMessageIcon.Question) = DialogResult.Yes) Then
                Return False
            End If
            If (clsMilkTypeMaster.DeleteData(fndMilkTypeCode.Value)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Sucessfully", Me.Name)
                Reset()
                Return True
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try

    End Function
    Private Sub loadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Try
            obj = New clsMilkTypeMaster()
            obj = clsMilkTypeMaster.GetData(strCode, NavTyep)
            If obj IsNot Nothing AndAlso clsCommon.myLen(obj.MILK_TYPE_CODE) > 0 Then
                Reset()
                rbtnSave.Text = "Update"
                fndMilkTypeCode.MyReadOnly = True
                fndMilkTypeCode.Value = obj.MILK_TYPE_CODE
                txtDescription.Text = obj.DESCRIPTION
                    cmbMilkType.SelectedValue = obj.MILK_TYPE
                End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub fndReasonID__MYNavigator(ByVal sender As Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndMilkTypeCode._MYNavigator
        Try
            Dim Qry = "select count(*) from TSPL_MILK_TYPE_MASTER where MILK_TYPE_CODE='" + fndMilkTypeCode.Value + "'"
            Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(Qry))
            If count = 0 Then
                fndMilkTypeCode.MyReadOnly = False
            Else
                fndMilkTypeCode.MyReadOnly = True
            End If
            loadData(fndMilkTypeCode.Value, NavType)
        Catch ex As Exception
            MessageBox.Show(Me, ex.Message, Me.Text)
        End Try

    End Sub

    Private Sub fndReasonID__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndMilkTypeCode._MYValidating
        Try
            Dim str As String = "select count(*) from TSPL_MILK_TYPE_MASTER where MILK_TYPE_CODE='" + fndMilkTypeCode.Value + "'"
            Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
            If no = 0 Then
                fndMilkTypeCode.MyReadOnly = False
            Else
                fndMilkTypeCode.MyReadOnly = True
            End If
            If fndMilkTypeCode.MyReadOnly OrElse isButtonClicked Then
                fndMilkTypeCode.Value = clsMilkTypeMaster.getFinder("", fndMilkTypeCode.Value, isButtonClicked)
                loadData(fndMilkTypeCode.Value, NavigatorType.Current)
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub rbtnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnDelete.Click
        deleteData()
    End Sub

    Private Sub rbtnReset_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnReset.Click
        Reset()
    End Sub




    Private Sub rdmenuexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexit.Click
        Me.Close()
    End Sub

    Private Sub rdmenuexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexport.Click
        Try
            Dim str As String
            str = "select TSPL_MILK_TYPE_MASTER.MILK_TYPE_CODE as [CODE] ,TSPL_MILK_TYPE_MASTER.Description, TSPL_MILK_TYPE_MASTER.MILK_TYPE as [MILK TYPE] from   TSPL_MILK_TYPE_MASTER "
            ListImpExpColumnsMandatory = New List(Of String)({"CODE"})
            ListImpExpColumnsSuperMandatory = New List(Of String)({"CODE"})
            transportSql.ExporttoExcel(str, "", "", Me, ListImpExpColumnsMandatory, ListImpExpColumnsSuperMandatory, MyBase.Form_ID)
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub rdmenuimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuimport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "CODE", "Description", "MILK TYPE") Then
            ' Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsMilkTypeMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells("CODE").Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.MILK_TYPE_CODE = strCode

                    Dim strDec As String = clsCommon.myCstr(grow.Cells("Description").Value)
                    If clsCommon.myLen(strDec) > 100 Then
                        Throw New Exception("Description Length can not be greater than 100.")
                    End If
                    obj.DESCRIPTION = strDec
                    Dim MILK_TYPE As String = ""
                    MILK_TYPE = clsCommon.myCstr(grow.Cells("MILK TYPE").Value)
                    If Not (clsCommon.CompairString(MILK_TYPE, "Cow") = CompairStringResult.Equal OrElse clsCommon.CompairString(MILK_TYPE, "Buffalo") = CompairStringResult.Equal OrElse clsCommon.CompairString(MILK_TYPE, "Camel") = CompairStringResult.Equal OrElse clsCommon.CompairString(MILK_TYPE, "Goat") = CompairStringResult.Equal OrElse clsCommon.CompairString(MILK_TYPE, "Mix") = CompairStringResult.Equal OrElse clsCommon.CompairString(MILK_TYPE, "Others") = CompairStringResult.Equal) Then
                        Throw New Exception("Milk Type Should be one of these ( Cow , Buffalo , Goat , Camel , Mix , Others) ")
                    End If
                    If clsCommon.CompairString(MILK_TYPE, "Cow") = CompairStringResult.Equal Then
                        MILK_TYPE = "Cow"
                    ElseIf clsCommon.CompairString(MILK_TYPE, "Buffalo") = CompairStringResult.Equal Then
                        MILK_TYPE = "Buffalo"
                    ElseIf clsCommon.CompairString(MILK_TYPE, "Goat") = CompairStringResult.Equal Then
                        MILK_TYPE = "Goat"
                    ElseIf clsCommon.CompairString(MILK_TYPE, "Camel") = CompairStringResult.Equal Then
                        MILK_TYPE = "Camel"
                    ElseIf clsCommon.CompairString(MILK_TYPE, "mix") = CompairStringResult.Equal Then
                        MILK_TYPE = "Mix"
                    ElseIf clsCommon.CompairString(MILK_TYPE, "Others") = CompairStringResult.Equal Then
                        MILK_TYPE = "Others"
                    End If
                    obj.MILK_TYPE = MILK_TYPE
                    obj.SaveData(obj, clsMilkTypeMaster.CheckNewEntry(obj.MILK_TYPE_CODE), Nothing)
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub RadMenufile_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenufile.Click

    End Sub
End Class
