Imports common
Imports System.Data
Imports System.Data.SqlClient
'ERO/07/05/18-000292 by balwinder on 07/05/2018
Public Class frmPaymentCycleMaster
    Inherits FrmMainTranScreen

#Region "Variable"
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String
#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        Save()
    End Sub

    Public Sub Save()
        If AllowToSave() Then
            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmPaymentCycleMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If
            Dim obj As New clsPaymentCycleMaster()
            obj.PC_CODE = txtCode.Value
            obj.Description = txtDescription.Text
            obj.PC_TYPE = cboPCType.SelectedValue
            If clsCommon.CompairString(clsCommon.myCstr(cboPCType.SelectedValue), "Week") = CompairStringResult.Equal Then
                obj.PC_VALUE = clsCommon.myCstr(CboFirstDay.SelectedValue)
            Else
                obj.PC_VALUE = clsCommon.myCdbl(txtValue.Text)
            End If
            obj.IsDefault = IIf(chkIsDefault.Checked = True, 1, 0)
            If (obj.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                LoadData(obj.PC_CODE, NavigatorType.Current)
            End If
        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnSave.Enabled = True
        btnDelete.Enabled = True
        Dim obj As New clsPaymentCycleMaster()
        obj = clsPaymentCycleMaster.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.PC_CODE) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            txtCode.Value = obj.PC_CODE
            txtDescription.Text = obj.Description
            cboPCType.SelectedValue = obj.PC_TYPE
            chkIsDefault.Checked = IIf(obj.IsDefault = 1, True, False)
            setValueSplicContrainer()
            If clsCommon.CompairString(clsCommon.myCstr(cboPCType.SelectedValue), "Week") = CompairStringResult.Equal Then
                CboFirstDay.SelectedValue = clsCommon.myCstr(obj.PC_VALUE)
            Else
                txtValue.Text = obj.PC_VALUE
            End If
        End If
    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
            myMessages.blankValue("Code")
            txtCode.Focus()
            Return False
        ElseIf clsCommon.myLen(cboPCType.Text) <= 0 Then
            myMessages.blankValue("Type")
            cboPCType.Focus()
            Return False
        End If
        If clsCommon.CompairString(clsCommon.myCstr(cboPCType.SelectedValue), "Week") = CompairStringResult.Equal Then
            If clsCommon.myLen(CboFirstDay.SelectedValue) <= 0 Then
                myMessages.blankValue("First Day")
                cboPCType.Focus()
                Return False
            End If
        Else
            If clsCommon.myLen(txtValue.Text) <= 0 Then
                myMessages.blankValue("Value")
                txtValue.Focus()
                Return False
            End If
        End If
        Return True
    End Function

    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub

    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "Select Code", Me.Text)
            Exit Sub
        End If
        
        funDelete()
    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsPaymentCycleMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub frmPaymentCycleMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isNewEntry = True
        funReset()
        loadPCType()
        loadFirstDay()
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
    End Sub

    Sub loadPCType()
        Dim dt As DataTable = New DataTable()
        dt.Columns.Add("Code", GetType(String))
        dt.Columns.Add("Name", GetType(String))

        Dim dr As DataRow
        dr = dt.NewRow()
        dr("Code") = "Day"
        dr("Name") = "Day"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "Week"
        dr("Name") = "Week"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "Month"
        dr("Name") = "Month"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "Year"
        dr("Name") = "Year"
        dt.Rows.Add(dr)

        dt.AcceptChanges()
        Me.cboPCType.DataSource = dt
        Me.cboPCType.ValueMember = "Code"
        Me.cboPCType.DisplayMember = "Name"
    End Sub

    Sub loadFirstDay()
        Dim dt As DataTable = New DataTable()
        dt.Columns.Add("Code", GetType(String))
        dt.Columns.Add("Name", GetType(String))

        Dim dr As DataRow
        dr = dt.NewRow()
        dr("Code") = "1"
        dr("Name") = "Sunday"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "2"
        dr("Name") = "Monday"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "3"
        dr("Name") = "Tuesday"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "4"
        dr("Name") = "Wednesday "
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "5"
        dr("Name") = "Thursday"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "6"
        dr("Name") = "Friday"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "7"
        dr("Name") = "Saturday"
        dt.Rows.Add(dr)

        dt.AcceptChanges()
        CboFirstDay.DataSource = dt
        CboFirstDay.ValueMember = "Code"
        CboFirstDay.DisplayMember = "Name"
    End Sub

    Private Sub SetUserMgmtNew()
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
        End If
        btnSave.Visible = MyBase.isModifyFlag
        If btnSave.Visible = True Then
            MenuItemImport.Enabled = True
            MenuItemExport.Enabled = True
        Else
            MenuItemImport.Enabled = False
            MenuItemExport.Enabled = False
        End If
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        txtValue.Text = ""
        txtDescription.Text = ""
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = True
        cboPCType.SelectedValue = "Day"
        setValueSplicContrainer()
        CboFirstDay.SelectedValue = "1"
        chkIsDefault.Checked = False
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
       funClose()
    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating

        Dim str As String = "select count(*) from TSPL_PAYMENT_CYCLE_MASTER where PC_CODE ='" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtCode.MyReadOnly = False
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            txtCode.Value = clsPaymentCycleMaster.getFinder("", txtCode.Value, isButtonClicked)

            If txtCode.Value <> "" Then
                LoadData(txtCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If

    End Sub

    Private Sub txtCode_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCode.KeyPress
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub frmPaymentCycleMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub MenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Description", "Type", "Value") Then
            Dim trans As SqlTransaction = Nothing
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsPaymentCycleMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.PC_CODE = strCode

                    Dim strDes As String = clsCommon.myCstr(grow.Cells(1).Value)
                    If strDes.Length > 200 Then
                        Throw New Exception("Description can not be blank or incorrect.")
                    End If
                    obj.Description = strDes

                    Dim strTYPE As String = clsCommon.myCstr(grow.Cells(2).Value)
                    If strTYPE.Length > 30 Then
                        Throw New Exception("Type can not be blank or incorrect.")
                    End If
                    obj.PC_TYPE = strTYPE

                    Dim strvalue As String = clsCommon.myCdbl(grow.Cells(3).Value)
                    obj.PC_VALUE = strvalue

                    obj.SaveData(obj, clsPaymentCycleMaster.CheckNewEntry(obj.PC_CODE))
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub MenuItemExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemExport.Click
        Dim str As String
        str = "select PC_CODE AS Code, DESCRIPTION AS Description,PC_TYPE AS [Type],PC_VALUE AS [Value] from TSPL_PAYMENT_CYCLE_MASTER"
        ListImpExpColumnsMandatory = New List(Of String)({"Code"})
        ListImpExpColumnsSuperMandatory = New List(Of String)({"Code"})
        transportSql.ExporttoExcel(str, "", "", Me, ListImpExpColumnsMandatory, ListImpExpColumnsSuperMandatory, MyBase.Form_ID)
    End Sub

    Private Sub MenuItemClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemClose.Click
        funClose()
    End Sub

    Private Sub cboPCType_SelectedValueChanged(sender As Object, e As EventArgs) Handles cboPCType.SelectedValueChanged
        setValueSplicContrainer()
    End Sub

    Private Sub cboPCType_SelectedIndexChanged(sender As Object, e As UI.Data.PositionChangedEventArgs) Handles cboPCType.SelectedIndexChanged
        setValueSplicContrainer()
    End Sub

    Sub setValueSplicContrainer()
        If clsCommon.CompairString(clsCommon.myCstr(cboPCType.SelectedValue), "Week") = CompairStringResult.Equal Then
            SplitContainer2.Panel1Collapsed = True
            SplitContainer2.Panel2Collapsed = False
        Else
            SplitContainer2.Panel1Collapsed = False
            SplitContainer2.Panel2Collapsed = True
        End If
    End Sub
End Class
