'Created By---> priti sharma
'Created Date--->12/Aug/2016
Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.OleDb
Imports System.Drawing
Imports System.IO
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls.Data
Imports Telerik.Data
Imports Telerik.WinControls.Enumerations
Imports Telerik.WinControls
Imports System.Text.RegularExpressions
Imports Telerik.WinControls.UI.Export
Imports Telerik.WinControls.UI.Export.ExportToExcelML
Imports Excel = Microsoft.Office.Interop.Excel
Imports System.Globalization
Imports common
Imports System.Threading
Public Class frmSupplierMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim ReasonCode, Description, CompGroupCode, CompDesc As String
    Dim obj As New clsSupplierMaster
    Private Sub frmPrimaryReasonMaster_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso rbtnSave.Enabled Then
                saveData()

            ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso rbtnDelete.Enabled Then
                deleteData()
            ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
                Close()
            ElseIf e.Alt And e.KeyCode = Keys.N Then
                Reset()
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub


    Private Sub frmPrimaryReasonMaster_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            SetUserMgmtNew()
            fndSupplierCode.MyMaxLength = 30
            txtDescription.MaxLength = 200
            ButtonToolTip.SetToolTip(rbtnSave, "Press Alt+S for Save/Update ")
            ButtonToolTip.SetToolTip(rbtnDelete, "Press Alt+D  for Delete ")
            ButtonToolTip.SetToolTip(rbtnClose, "Press Alt+C Close the Window")
            Reset()
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub
    Private Sub Reset()
        Try
            fndSupplierCode.Value = ""
            txtDescription.Text = ""
            txtVendorCode.Value = ""
            lblVendor.Text = ""
            rbtnDelete.Enabled = True
            fndSupplierCode.Focus()
            rbtnSave.Text = "Save"
            fndSupplierCode.MyReadOnly = False
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub SetUserMgmtNew()
        ''MyBase.SetUserMgmt(clsUserMgtCode.FrmSupplierMaster)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        rbtnSave.Visible = MyBase.isModifyFlag
        rbtnDelete.Visible = MyBase.isDeleteFlag
    End Sub


    Private Sub rbtnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnClose.Click
        Me.Close()
    End Sub

    Private Sub rbtnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnSave.Click
        If AllowToSave() Then saveData()
    End Sub
    Public Function AllowToSave() As Boolean
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
                 If clsCommon.myLen(fndSupplierCode.Value) = 0 Then
                    common.clsCommon.MyMessageBoxShow("Please Enter Supplier Code")
                    Return False
                End If
            End If
            If clsCommon.myLen(txtVendorCode.Value) = 0 Then
                common.clsCommon.MyMessageBoxShow("Please Enter Vendor Code")
                Return False
            End If
            Dim qry1 As String = "SELECT Count(*) FROM tspl_vendor_master where Vendor_Code = '" & txtVendorCode.Value & "'"
            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1)
            If check1 = 0 Then
                common.clsCommon.MyMessageBoxShow("Invalid Vendor Code")
                Return False
            End If
            Return True
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Function
    Sub saveData()
        Try

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.FrmSupplierMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If
            obj = New clsSupplierMaster()
            obj.SUPPLIER_CODE = fndSupplierCode.Value
            obj.description = txtDescription.Text.Trim
            obj.Vendor_Code = txtVendorCode.Value
            Dim isSaved As Boolean = obj.SaveData(obj, IIf(rbtnSave.Text = "Save", True, False), Nothing)
            If isSaved Then
                common.clsCommon.MyMessageBoxShow("Data Saved Successfully")
                fndSupplierCode.Value = obj.SUPPLIER_CODE
                rbtnSave.Text = "Update"
                rbtnDelete.Enabled = True
            Else
                rbtnSave.Text = "Save"
                rbtnDelete.Enabled = False
                common.clsCommon.MyMessageBoxShow("Data Could Not Saved")
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try

    End Sub
    Function deleteData() As Boolean
        Try
            If clsCommon.myLen(fndSupplierCode.Value) <= 0 Then
                common.clsCommon.MyMessageBoxShow("No Supplier Code found to Delete", Me.Name)
                Return False
            ElseIf Not (common.clsCommon.MyMessageBoxShow("Delete the Supplier Code " + fndSupplierCode.Value + Environment.NewLine + " Are you sure?", Me.Text, MessageBoxButtons.YesNo, RadMessageIcon.Question) = DialogResult.Yes) Then
                Return False
            End If
            If (clsSupplierMaster.DeleteData(fndSupplierCode.Value)) Then
                common.clsCommon.MyMessageBoxShow("Data Deleted Sucessfully", Me.Name)
                Reset()
                Return True
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try

    End Function
    Private Sub loadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Try
            obj = New clsSupplierMaster()
            obj = clsSupplierMaster.GetData(strCode, NavTyep)
            If obj IsNot Nothing AndAlso clsCommon.myLen(obj.SUPPLIER_CODE) > 0 Then
                Reset()
                rbtnSave.Text = "Update"
                fndSupplierCode.MyReadOnly = True
                fndSupplierCode.Value = obj.SUPPLIER_CODE
                txtDescription.Text = obj.description
                txtVendorCode.Value = obj.Vendor_Code
                lblVendor.Text = clsDBFuncationality.getSingleValue("select Vendor_Name from tspl_vendor_master where Vendor_Code='" & txtVendorCode.Value & "'")
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub fndReasonID__MYNavigator(ByVal sender As Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndSupplierCode._MYNavigator
        Try
            Dim Qry = "select count(*) from TSPL_SUPPLIER_MASTER where SUPPLIER_CODE='" + fndSupplierCode.Value + "'"
            Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(Qry))
            If count = 0 Then
                fndSupplierCode.MyReadOnly = False
            Else
                fndSupplierCode.MyReadOnly = True
            End If
            loadData(fndSupplierCode.Value, NavType)
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Sub

    Private Sub fndReasonID__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndSupplierCode._MYValidating
        Try
            Dim str As String = "select TSPL_SUPPLIER_MASTER.SUPPLIER_CODE as [Code] ,TSPL_SUPPLIER_MASTER.DESCRIPTION as [Description] ,TSPL_SUPPLIER_MASTER.Vendor_Code as [Is Diverted] ,TSPL_SUPPLIER_MASTER.Created_By as [Created By] ,TSPL_SUPPLIER_MASTER.Created_Date as [Created Date] ,TSPL_SUPPLIER_MASTER.Modified_By as [Modified By] ,TSPL_SUPPLIER_MASTER.Modified_Date as [Modified Date]  From TSPL_SUPPLIER_MASTER  where SUPPLIER_CODE='" + fndSupplierCode.Value + "'"
            Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
            If no = 0 Then
                fndSupplierCode.MyReadOnly = False
            Else
                fndSupplierCode.MyReadOnly = True
            End If
            If fndSupplierCode.MyReadOnly OrElse isButtonClicked Then
                fndSupplierCode.Value = clsSupplierMaster.getFinder("", fndSupplierCode.Value, isButtonClicked)
                loadData(fndSupplierCode.Value, NavigatorType.Current)
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try

    End Sub

    Private Sub rbtnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnDelete.Click
        deleteData()
    End Sub

    Private Sub rbtnReset_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnReset.Click
        Reset()
    End Sub

    Private Sub txtComplaintGroupCode__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles txtVendorCode._MYValidating
        Try
            Dim qry As String = "select Vendor_Code as Code ,Vendor_Name as Name from   tspl_vendor_master "
            Dim whrCls = " tspl_vendor_master.Status='N' "
            txtVendorCode.Value = clsCommon.ShowSelectForm("SuppVendCode", qry, "Code", whrCls, txtVendorCode.Value, "", isButtonClicked)
            lblVendor.Text = clsDBFuncationality.getSingleValue("Select Vendor_Name from tspl_vendor_master where tspl_vendor_master.Status='N' and  Vendor_Code='" + txtVendorCode.Value + "'")
        Catch ex As Exception
        End Try

    End Sub


    Private Sub rdmenuexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexit.Click
        Me.Close()
    End Sub

    Private Sub rdmenuexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexport.Click
        Try
            Dim str As String
            str = "select SUPPLIER_CODE as 'Supplier Code' ,Description, Vendor_Code as 'Vendor Code' from   TSPL_SUPPLIER_MASTER "
            transportSql.ExporttoExcel(str, Me)
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub rdmenuimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuimport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Supplier Code", "Description", "Vendor Code") Then
            ' Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsSupplierMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells("Supplier Code").Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception(" Supplier Code can not be blank or incorrect.")
                    End If
                    obj.SUPPLIER_CODE = strCode

                    Dim strDec As String = clsCommon.myCstr(grow.Cells("Description").Value)
                    If clsCommon.myLen(strDec) > 100 Then
                        Throw New Exception("Description Length can not be greater than 100.")
                    End If
                    obj.description = strDec
                    Dim Vendor_Code As String = clsCommon.myCstr(grow.Cells("Vendor Code").Value)
                    If clsDBFuncationality.getSingleValue("SELECT Count(*) FROM tspl_vendor_master where Vendor_Code = '" & Vendor_Code & "'") = 0 Then
                        Throw New Exception(" Invalid Vendor Code ")
                    End If
                    obj.Vendor_Code = Vendor_Code

                    obj.SaveData(obj, clsSupplierMaster.CheckNewEntry(obj.SUPPLIER_CODE), Nothing)
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub RadMenufile_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenufile.Click

    End Sub
End Class
