Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports Telerik.WinControls.Data
Imports System.Text.RegularExpressions
Imports common


Public Class frmBreakDownMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim str As String

    Private Sub SetUserMgmtNew()
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
        End If
        btnsave.Visible = MyBase.isModifyFlag
        If btnsave.Visible = True Then
            import.Enabled = True
            export.Enabled = True
        Else
            import.Enabled = False
            export.Enabled = False
        End If
        '--------------------------------------------------
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub frmBreakDownMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        funreset()
        SetUserMgmtNew()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnnew, "Press Alt+N Adding New Trasnaction")
        ToolTipcity.SetToolTip(btnnew, "New")
        btnsave.Enabled = True
        btndelete.Enabled = False
    End Sub

    'Keypress validation on finder and converting lower case to upper case
    Public Sub key_press(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If
    End Sub
    'Validation on save button click and calling funinsert,funupdate
    Private Sub btnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click
        SaveData()
    End Sub
    Public Sub SaveData()
        Dim trans As SqlTransaction = Nothing
        Try
            If AllowToSave() Then

                'If MyBase.isModifyonPasswordFlag Then
                '    If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmProfitCenter, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                '    Else
                '        Return
                '    End If
                'End If
                trans = clsDBFuncationality.GetTransactin()
                Dim obj As New ClsBreakDownMaster()
                obj.Code = txtCode.Value
                obj.Name = txtdes.Text

                If (obj.SaveData(obj, isNewEntry, trans)) Then
                    trans.Commit()
                    common.clsCommon.MyMessageBoxShow("Data Saved Successfully")
                    LoadData(obj.Code, NavigatorType.Current)
                End If
            End If

        Catch ex As Exception
            trans.Rollback()
            myMessages.myExceptions(ex)
        End Try
    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
            myMessages.blankValue("Break Down Code")
            txtCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtdes.Text) <= 0 Then
            myMessages.blankValue("Description")
            txtdes.Focus()
            Return False
        End If
        Return True
    End Function

    'Delete funtion call on delete button
    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub
    Public Sub DeleteData()
        If btndelete.Enabled = False Then
            Exit Sub
        End If
        If txtCode.Value = "" Then
            myMessages.blankValue("Break Down code")
            txtCode.Focus()
        ElseIf myMessages.deleteConfirm() Then
            If (ClsBreakDownMaster.DeleteData(txtCode.Value)) Then
                common.clsCommon.MyMessageBoxShow("Data Deleted Successfully ")
                funreset()
            End If
        End If
    End Sub

    Private Sub btnnew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnnew.Click
        funreset()
    End Sub
    'It will reset all the controls in screens
    Public Sub funreset()
        txtCode.Value = Nothing
        txtCode.MyReadOnly = False
        isNewEntry = True
        txtdes.Text = ""
        btnsave.Text = "Save"
        btnsave.Enabled = True
        btndelete.Enabled = True
    End Sub
    'closing of current window form
    Private Sub btnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        Me.Close()
    End Sub

    'For Import functionality 
    Private Sub import_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles import.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Break Down Code", "Break Down Name") Then
            Dim trans As SqlTransaction = Nothing

            Dim linno As Integer = 0
            Dim TempNewRecord As Boolean = False
            Try
                ' connectSql.OpenConnection()
                trans = clsDBFuncationality.GetTransactin()

                clsCommon.ProgressBarShow()

                Dim strcode As String = ""
                Dim strname As String = ""

                For Each grow As GridViewRowInfo In gv.Rows
                    linno += 1
                    strcode = clsCommon.myCstr(grow.Cells(0).Value)
                    If (String.IsNullOrEmpty(strcode)) Or clsCommon.myLen(strcode) > 30 Then
                        Throw New Exception("Length of Break Down Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    strname = clsCommon.myCstr(grow.Cells(1).Value)
                    If (String.IsNullOrEmpty(strname)) Or clsCommon.myLen(strname) > 200 Then
                        Throw New Exception("Length of Break Down Name should be max. 200 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If

                    Dim obj As New ClsBreakDownMaster()
                    obj.Code = strcode
                    obj.Name = strname


                    Dim Count1 As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue("Select COunt(*) from TSPL_BREAK_DOWN_MASTER WHERE code='" + clsCommon.myCstr(grow.Cells(0).Value) + "'", trans))
                    If Count1 <= 0 Then
                        obj.SaveData(obj, True, trans)
                    Else
                        obj.SaveData(obj, False, trans)
                    End If


                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                trans.Rollback()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub
    'For closing current screen by menu strip Close
    Private Sub cityclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cityclose.Click
        closeform()
    End Sub
    Public Sub closeform()
        Me.Close()
    End Sub

    Private Sub frmBreakDownMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            closeform()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funreset()
        ElseIf e.Alt AndAlso e.Shift AndAlso e.Control And e.KeyCode = Keys.F12 Then
            ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update Trasnaction" + Environment.NewLine +
                                                             "TSPL_BREAK_DOWN_MASTER ")
        End If
    End Sub


    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        Dim qst As String = "select count(*) from TSPL_BREAK_DOWN_MASTER where Code='" + txtCode.Value + "'"
        Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qst))
        If count = 0 Then
            txtCode.MyReadOnly = False
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then
            Dim whrClas As String = ""
            Dim qry As String = " select Code as [Code],Name as [Name],Created_By as [Created By],Created_Date as [Created Date],Modify_By as [Modify By],Modify_Date as [Modify Date],Comp_Code as [Company Code] from TSPL_BREAK_DOWN_MASTER  "
            txtCode.Value = clsCommon.ShowSelectForm("RPTBDMST", qry, "Code", whrClas, txtCode.Value, "Code", isButtonClicked)
            LoadData(txtCode.Value, NavigatorType.Current)
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message)
        End Try

    End Sub
    Public Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Try
            txtCode.MyReadOnly = True
            btnsave.Enabled = True
            btndelete.Enabled = True
            isNewEntry = False
            Dim obj As New ClsBreakDownMaster()
            obj = ClsBreakDownMaster.GetData(strCode, NavTyep)
            If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
                funreset()
                isNewEntry = False
                btnsave.Text = "Update"
                txtCode.Value = obj.Code
                txtdes.Text = obj.Name
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub


    Private Sub export_Click(sender As Object, e As EventArgs) Handles export.Click
        Dim str As String
        str = " select TSPL_BREAK_DOWN_MASTER.Code as [Break Down Code] ,TSPL_BREAK_DOWN_MASTER.Name as [Break Down Name] from TSPL_BREAK_DOWN_MASTER "
        transportSql.ExporttoExcel(str, Me)
    End Sub


    Private Sub btnHistory_Click(sender As Object, e As EventArgs) Handles btnHistory.Click
        Try
            If clsCommon.myLen(txtCode.Value) <= 0 Then
                clsCommon.MyMessageBoxShow("Select Break Down Code", Me.Text)
                Exit Sub
            End If
            clsERPFuncationality.ShowHistoryData(txtCode.Value, "Code", "TSPL_BREAK_DOWN_MASTER")
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Sub
End Class

