Imports common
Imports System.Data
Imports System.Data.SqlClient
Public Class clsCastCategoryMaster


#Region "Variables"
    Public Code As String
    Public Description As String
    Public Name As String
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_CAST_CATEGORY_MASTER.CAST_CATEGORY_CODE as [Code] ,TSPL_CAST_CATEGORY_MASTER.CAST_CATEGORY_NAME as [Cast Category Name] ,TSPL_CAST_CATEGORY_MASTER.DESCRIPTION as [Description] ,TSPL_CAST_CATEGORY_MASTER.Created_By as [Created By] ,TSPL_CAST_CATEGORY_MASTER.Created_Date as [Created Date] ,TSPL_CAST_CATEGORY_MASTER.Modified_By as [Modified By] ,TSPL_CAST_CATEGORY_MASTER.Modified_Date as [Modified Date]  From TSPL_CAST_CATEGORY_MASTER   "
        str = clsCommon.ShowSelectForm("CASTCATMST", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsCastCategoryMaster
        Return GetData(strCode, NavType, Nothing)
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isSaved As Boolean

        Try
            isSaved = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_CAST_CATEGORY_MASTER where CAST_CATEGORY_CODE ='" + strCode + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry)


        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsCastCategoryMaster
        Dim obj As clsCastCategoryMaster = Nothing
        Dim qry As String = "select CAST_CATEGORY_CODE, CAST_CATEGORY_NAME, DESCRIPTION from TSPL_CAST_CATEGORY_MASTER where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and CAST_CATEGORY_CODE = (select MIN(CAST_CATEGORY_CODE) from TSPL_CAST_CATEGORY_MASTER)"
            Case NavigatorType.Last
                qry += " and CAST_CATEGORY_CODE = (select Max(CAST_CATEGORY_CODE) from TSPL_CAST_CATEGORY_MASTER)"
            Case NavigatorType.Next
                qry += " and CAST_CATEGORY_CODE = (select Min(CAST_CATEGORY_CODE) from TSPL_CAST_CATEGORY_MASTER where  CAST_CATEGORY_CODE>'" + strCode + "')"
            Case NavigatorType.Previous
                qry += " and CAST_CATEGORY_CODE = (select Max(CAST_CATEGORY_CODE) from TSPL_CAST_CATEGORY_MASTER where CAST_CATEGORY_CODE<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and CAST_CATEGORY_CODE = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsCastCategoryMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("CAST_CATEGORY_CODE"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("CAST_CATEGORY_NAME"))
        End If
        Return obj


    End Function

    Public Function SaveData(ByVal obj As clsCastCategoryMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "CAST_CATEGORY_NAME", obj.Name)
            clsCommon.AddColumnsForChange(coll, "DESCRIPTION", obj.Description)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_CAST_CATEGORY_MASTER where CAST_CATEGORY_CODE='" & obj.Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.CastCategory, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "CAST_CATEGORY_CODE", obj.Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
                Dim qry As String = "SELECT Count(*) FROM TSPL_CAST_CATEGORY_MASTER where CAST_CATEGORY_CODE= '" & obj.Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_CAST_CATEGORY_MASTER", OMInsertOrUpdate.Insert, "", trans)
                Else
                    Throw New Exception("This Code Is Already Exist")

                End If

            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_CAST_CATEGORY_MASTER", OMInsertOrUpdate.Update, "CAST_CATEGORY_CODE='" + obj.Code + "'", trans)
            End If

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function
    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select CAST_CATEGORY_CODE from TSPL_CAST_CATEGORY_MASTER where CAST_CATEGORY_CODE ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function

End Class
