Imports System.Data.SqlClient
Imports common

Public Class clsfrmSalaryAccountSetting
#Region "variables"
    Public ACCOUNT_SET_CODE As String = Nothing
    Public DESCRIPTION As String = Nothing
    Public GL_SALARY_PAYABLE As String = Nothing
    Public GL_SALARY_PAYABLE_Desc As String = Nothing
    Public BANK_CODE As String = Nothing
    Public SourceCode As String = Nothing
    Public SourceCodeDesc As String = Nothing
    '' newly added columns
    Public GL_Employer_PF_PAYABLE As String
    Public GL_Employer_PF_PAYABLE_Desc As String

    Public GL_Employer_ESI_PAYABLE As String
    Public GL_Employer_ESI_PAYABLE_Desc As String

    Public GL_EMPLOYER_OTHERS_PAYABLE As String
    Public GL_EMPLOYER_OTHERS_PAYABLE_Desc As String

    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing
#End Region
#Region "Functions"
    Public Shared Function SaveData(ByVal obj As clsfrmSalaryAccountSetting, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "DESCRIPTION", obj.DESCRIPTION)
            clsCommon.AddColumnsForChange(coll, "GL_SALARY_PAYABLE", obj.GL_SALARY_PAYABLE)
            clsCommon.AddColumnsForChange(coll, "BANK_CODE", obj.BANK_CODE)
            clsCommon.AddColumnsForChange(coll, "SourceCode", obj.SourceCode)
            clsCommon.AddColumnsForChange(coll, "GL_Employer_PF_PAYABLE", obj.GL_Employer_PF_PAYABLE, True)
            clsCommon.AddColumnsForChange(coll, "GL_Employer_ESI_PAYABLE", obj.GL_Employer_ESI_PAYABLE, True)
            clsCommon.AddColumnsForChange(coll, "GL_EMPLOYER_OTHERS_PAYABLE", obj.GL_EMPLOYER_OTHERS_PAYABLE, True)

            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_PAYROLL_ACCOUNTSETS where ACCOUNT_SET_CODE='" & obj.ACCOUNT_SET_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.ACCOUNT_SET_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.SalaryAccountSetting, "", "")
                        If clsCommon.myLen(obj.ACCOUNT_SET_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "ACCOUNT_SET_CODE", obj.ACCOUNT_SET_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PAYROLL_ACCOUNTSETS", OMInsertOrUpdate.Insert, "", trans)
            Else

                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PAYROLL_ACCOUNTSETS", OMInsertOrUpdate.Update, "TSPL_PAYROLL_ACCOUNTSETS.ACCOUNT_SET_CODE='" + obj.ACCOUNT_SET_CODE + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsfrmSalaryAccountSetting
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsfrmSalaryAccountSetting
        Dim obj As clsfrmSalaryAccountSetting = Nothing
        Dim Arr As List(Of clsfrmSalaryAccountSetting) = Nothing
        Dim qry As String = "select TSPL_PAYROLL_ACCOUNTSETS.ACCOUNT_SET_CODE ,TSPL_PAYROLL_ACCOUNTSETS.DESCRIPTION,TSPL_GL_ACCOUNTS.Description as GL_SALARY_PAYABLE_Desc," & _
        " TSPL_GL_SOURCECODE.sourcedescription as SourceCodeDesc,TSPL_PAYROLL_ACCOUNTSETS.GL_SALARY_PAYABLE,TSPL_PAYROLL_ACCOUNTSETS.BANK_CODE,TSPL_PAYROLL_ACCOUNTSETS.SourceCode, " & _
        " TSPL_PAYROLL_ACCOUNTSETS.GL_Employer_PF_PAYABLE,GL_PF.Description as GL_Employer_PF_PAYABLE_Desc,TSPL_PAYROLL_ACCOUNTSETS.GL_Employer_ESI_PAYABLE, " & _
        " GL_ESI.Description as GL_Employer_ESI_PAYABLE_Desc,TSPL_PAYROLL_ACCOUNTSETS.GL_EMPLOYER_OTHERS_PAYABLE,GL_Othr.Description as GL_EMPLOYER_OTHERS_PAYABLE_Desc " & _
        " from TSPL_PAYROLL_ACCOUNTSETS " & _
        " left join TSPL_GL_ACCOUNTS on TSPL_PAYROLL_ACCOUNTSETS.GL_SALARY_PAYABLE=TSPL_GL_ACCOUNTS.account_code " & _
        " left join TSPL_GL_ACCOUNTS as GL_PF  on TSPL_PAYROLL_ACCOUNTSETS.GL_Employer_PF_PAYABLE=GL_PF.account_code " & _
        " left join TSPL_GL_ACCOUNTS as GL_ESI on TSPL_PAYROLL_ACCOUNTSETS.GL_Employer_ESI_PAYABLE=GL_ESI.account_code " & _
        " left join TSPL_GL_ACCOUNTS as GL_Othr on TSPL_PAYROLL_ACCOUNTSETS.GL_EMPLOYER_OTHERS_PAYABLE=GL_Othr.account_code " & _
        " left join TSPL_GL_SOURCECODE on TSPL_PAYROLL_ACCOUNTSETS.SourceCode=TSPL_GL_SOURCECODE.SourceCode where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_PAYROLL_ACCOUNTSETS.ACCOUNT_SET_CODE = (select MIN(ACCOUNT_SET_CODE) from TSPL_PAYROLL_ACCOUNTSETS WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_PAYROLL_ACCOUNTSETS.ACCOUNT_SET_CODE = (select Max(ACCOUNT_SET_CODE) from TSPL_PAYROLL_ACCOUNTSETS WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_PAYROLL_ACCOUNTSETS.ACCOUNT_SET_CODE = (select top 1 ACCOUNT_SET_CODE from TSPL_PAYROLL_ACCOUNTSETS WHERE 1=1 " + whrclas + " and ACCOUNT_SET_CODE='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_PAYROLL_ACCOUNTSETS.ACCOUNT_SET_CODE = (select Min(ACCOUNT_SET_CODE) from TSPL_PAYROLL_ACCOUNTSETS where ACCOUNT_SET_CODE>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_PAYROLL_ACCOUNTSETS.ACCOUNT_SET_CODE = (select Max(ACCOUNT_SET_CODE) from TSPL_PAYROLL_ACCOUNTSETS where ACCOUNT_SET_CODE<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsfrmSalaryAccountSetting()
            obj.ACCOUNT_SET_CODE = clsCommon.myCstr(dt.Rows(0)("ACCOUNT_SET_CODE"))
            obj.DESCRIPTION = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.GL_SALARY_PAYABLE = clsCommon.myCstr(dt.Rows(0)("GL_SALARY_PAYABLE"))
            obj.BANK_CODE = clsCommon.myCstr(dt.Rows(0)("BANK_CODE"))
            obj.SourceCode = clsCommon.myCstr(dt.Rows(0)("SourceCode"))
            obj.SourceCodeDesc = clsCommon.myCstr(dt.Rows(0)("SourceCodeDesc"))
            obj.GL_SALARY_PAYABLE_Desc = clsCommon.myCstr(dt.Rows(0)("GL_SALARY_PAYABLE_Desc"))

            '' newly added column by Panch Raj
            obj.GL_Employer_PF_PAYABLE = clsCommon.myCstr(dt.Rows(0)("GL_Employer_PF_PAYABLE"))
            obj.GL_Employer_PF_PAYABLE_Desc = clsCommon.myCstr(dt.Rows(0)("GL_Employer_PF_PAYABLE_Desc"))

            obj.GL_Employer_ESI_PAYABLE = clsCommon.myCstr(dt.Rows(0)("GL_Employer_ESI_PAYABLE"))
            obj.GL_Employer_ESI_PAYABLE_Desc = clsCommon.myCstr(dt.Rows(0)("GL_Employer_ESI_PAYABLE_Desc"))

            obj.GL_EMPLOYER_OTHERS_PAYABLE = clsCommon.myCstr(dt.Rows(0)("GL_EMPLOYER_OTHERS_PAYABLE"))
            obj.GL_EMPLOYER_OTHERS_PAYABLE_Desc = clsCommon.myCstr(dt.Rows(0)("GL_EMPLOYER_OTHERS_PAYABLE_Desc"))

        End If
        Return obj
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isDelete As Boolean
        Try
            isDelete = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_PAYROLL_ACCOUNTSETS where ACCOUNT_SET_CODE ='" + strCode + "'"
            isDelete = clsDBFuncationality.ExecuteNonQuery(qry)
        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isDelete
    End Function
#End Region
End Class
