Imports common
Imports System.Data
Imports System.Data.SqlClient
Public Class clsLeaveMaster

#Region "Variables"
    Public Code As String
    Public PRINT_NAME As String
    Public Name As String
    Public AFFECTS_SALARY As Int16
    Public LEAVE_TYPE As String
    Public APPLY_LEAVE_TYPE_DED As Int16
#End Region


    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_LEAVE_MASTER.LEAVE_CODE as [Code],Leave_Type as [Leave Type] ,TSPL_LEAVE_MASTER.LEAVE_NAME as [Leave Name] ,TSPL_LEAVE_MASTER.PRINT_NAME as [Print Name] ,TSPL_LEAVE_MASTER.AFFECTS_SALARY as [Affects Salary] ,TSPL_LEAVE_MASTER.Created_By as [Created By] ,TSPL_LEAVE_MASTER.Created_Date as [Created Date] ,TSPL_LEAVE_MASTER.Modified_By as [Modified By] ,TSPL_LEAVE_MASTER.Modified_Date as [Modified Date]  From TSPL_LEAVE_MASTER   "
        str = clsCommon.ShowSelectForm("LEAVMST", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsLeaveMaster
        Return GetData(strCode, NavType, Nothing)
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isSaved As Boolean

        Try
            isSaved = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_LEAVE_MASTER where LEAVE_CODE ='" + strCode + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry)

        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsLeaveMaster
        Dim obj As clsLeaveMaster = Nothing
        Dim qry As String = "select LEAVE_CODE, LEAVE_NAME, PRINT_NAME, convert(int, AFFECTS_SALARY) as AFFECTS_SALARY,LEAVE_TYPE,APPLY_LEAVE_TYPE_DED  from TSPL_LEAVE_MASTER where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and LEAVE_CODE = (select MIN(LEAVE_CODE) from TSPL_LEAVE_MASTER)"
            Case NavigatorType.Last
                qry += " and LEAVE_CODE = (select Max(LEAVE_CODE) from TSPL_LEAVE_MASTER)"
            Case NavigatorType.Next
                qry += " and LEAVE_CODE = (select Min(LEAVE_CODE) from TSPL_LEAVE_MASTER where  LEAVE_CODE>'" + strCode + "')"
            Case NavigatorType.Previous
                qry += " and LEAVE_CODE = (select Max(LEAVE_CODE) from TSPL_LEAVE_MASTER where LEAVE_CODE<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and LEAVE_CODE = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsLeaveMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("LEAVE_CODE"))
            obj.PRINT_NAME = clsCommon.myCstr(dt.Rows(0)("PRINT_NAME"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("LEAVE_NAME"))
            obj.AFFECTS_SALARY = Convert.ToInt16(clsCommon.myCdbl(dt.Rows(0)("AFFECTS_SALARY")))
            obj.LEAVE_TYPE = clsCommon.myCstr(dt.Rows(0)("LEAVE_TYPE"))
            obj.APPLY_LEAVE_TYPE_DED = Convert.ToInt16(clsCommon.myCdbl(dt.Rows(0)("APPLY_LEAVE_TYPE_DED")))
        End If
        Return obj


    End Function

    Public Function SaveData(ByVal obj As clsLeaveMaster, ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "LEAVE_NAME", obj.Name)
            clsCommon.AddColumnsForChange(coll, "PRINT_NAME", obj.PRINT_NAME)
            clsCommon.AddColumnsForChange(coll, "AFFECTS_SALARY", obj.AFFECTS_SALARY)
            clsCommon.AddColumnsForChange(coll, "LEAVE_TYPE", obj.LEAVE_TYPE)
            clsCommon.AddColumnsForChange(coll, "APPLY_LEAVE_TYPE_DED", obj.APPLY_LEAVE_TYPE_DED)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_LEAVE_MASTER where LEAVE_CODE='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.LeaveMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "LEAVE_CODE", obj.Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
                Dim qry As String = "SELECT Count(*) FROM TSPL_LEAVE_MASTER where LEAVE_CODE= '" & obj.Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_LEAVE_MASTER", OMInsertOrUpdate.Insert, "")
                Else
                    Throw New Exception("This Code Is Already Exist")

                End If

            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_LEAVE_MASTER", OMInsertOrUpdate.Update, "LEAVE_CODE='" + obj.Code + "'")
            End If

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function GetName(ByVal strCode As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "select PRINT_NAME from TSPL_LEAVE_MASTER where LEAVE_CODE = '" + strCode + "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
    End Function
    Public Shared Function GetLeaveType(ByVal strCode As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "select LEAVE_TYPE from TSPL_LEAVE_MASTER where LEAVE_CODE = '" + strCode + "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
    End Function
    Public Shared Function GetLeaveCodeByLeaveType(ByVal strLeaveType As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "select TOP 1 LEAVE_CODE from TSPL_LEAVE_MASTER where LEAVE_TYPE = '" + strLeaveType + "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
    End Function

    Public Shared Function GetLeaveRegisterDT(ByVal strPayPeriod As String, ByRef Qrystring As String) As DataTable
        Dim dt As DataTable
        Try
            Dim qry As String = ""
            qry += " select Leave_Fun.EMP_CODE,emp.Emp_Name,Leave_Fun.Leave_Code,Leave.Leave_Name,OPENING,ALLOTED,AVAILED,ADJUSTMENT_PLUS,ADJUSTMENT_MINUS,BALANCE from TSPL_FUN_LEAVE_STATUS('" + strPayPeriod + "') AS Leave_Fun " & _
                " left join tspl_employee_master emp on Leave_Fun.Emp_Code=emp.Emp_Code " & _
                " left join TSPL_LEAVE_MASTER Leave on Leave.Leave_Code=Leave_Fun.Leave_Code "
            Qrystring = qry
            dt = clsDBFuncationality.GetDataTable(qry)

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return dt
    End Function
    Public Shared Function GetLeaveLedgerBaseQry(ByVal arrLoc As ArrayList, ByVal arrDiv As ArrayList, arrEmp As ArrayList, ByVal arrLeave As ArrayList, ByVal arrDept As ArrayList, ByVal ShowResgnEmp As Boolean, ByVal FromDate As Date, ByVal ToDate As Date) As String
        Dim qry As String = ""
        Dim EmpCond As String = ""
        If ShowResgnEmp = False Then
            EmpCond = " and emp.RELIEVING_DATE is null "
        End If
        qry = " select *,row_number() over (partition by empcode,leavecode order by empcode,leavecode,TransDate) as Tr_id from ("
        '" select lv.EMP_CODE as empcode,emp.Emp_Name as empname,emp.DEPARTMENT_CODE as departmentcode,emp.Location_Code as loccode,emp.Devision_Code as divcode,Null as Month,lv.LEAVE_CODE as Leavecode," & _
        '" Null as TransDate,Null TransCode,'Opening' as Remarks,sum(lv.ALLOTED-lv.AVAILED) as Alloted,0 as Taken,sum(lv.ALLOTED-lv.AVAILED) as Balance " & _
        '" from TSPL_VIEW_LEAVE_LEDGER as lv " & _
        '" left join TSPL_EMPLOYEE_MASTER emp on lv.EMP_CODE=emp.EMP_CODE " & _
        '" where lv.DATE_FROM <'" & clsCommon.GetPrintDate(FromDate, "dd/MMM/yyyy") & "' " & EmpCond & " " & _
        '" group by emp.LOCATION_CODE,emp.Devision_Code,lv.EMP_CODE,emp.DEPARTMENT_CODE,emp.Emp_Name,lv.LEAVE_CODE " & _
        '" union all " & _
        qry += " select lv.EMP_CODE as empcode,emp.Emp_Name as empname,emp.DEPARTMENT_CODE as departmentcode,emp.Location_Code as loccode,emp.Devision_Code as divcode,lv.PAY_PERIOD_CODE as Month,lv.LEAVE_CODE as Leavecode, " & _
              " coalesce(lv.TR_DATE,lv.DATE_FROM) as TransDate,lv.TR_CODE,lv.REMARKS,lv.ALLOTED as Alloted,lv.AVAILED as Taken,(lv.ALLOTED-lv.AVAILED) as Balance " & _
              " from TSPL_VIEW_LEAVE_LEDGER as lv " & _
              " left join TSPL_EMPLOYEE_MASTER emp on lv.EMP_CODE=emp.EMP_CODE " & _
              " where lv.DATE_FROM >='" & clsCommon.GetPrintDate(FromDate, "dd/MMM/yyyy") & "' and lv.DATE_FROM <='" & clsCommon.GetPrintDate(ToDate, "dd/MMM/yyyy") & "' " & EmpCond & " " & _
              "  and (lv.ALLOTED >0 or lv.AVAILED>0) ) as Final where 2=2 "
        If Not arrLoc Is Nothing AndAlso arrLoc.Count > 0 Then
            qry = qry & " and Final.loccode in (" & clsCommon.GetMulcallString(arrLoc) & ")"
        End If
        If Not arrDiv Is Nothing AndAlso arrDiv.Count > 0 Then
            qry = qry & " and Final.divcode in (" & clsCommon.GetMulcallString(arrDiv) & ")"
        End If
        If Not arrEmp Is Nothing AndAlso arrEmp.Count > 0 Then
            qry = qry & " and Final.empcode in (" & clsCommon.GetMulcallString(arrEmp) & ")"
        End If
        If Not arrLeave Is Nothing AndAlso arrLeave.Count > 0 Then
            qry = qry & " and Final.leavecode in (" & clsCommon.GetMulcallString(arrLeave) & ")"
        End If
        If Not arrDept Is Nothing AndAlso arrDept.Count > 0 Then
            qry = qry & " and Final.departmentcode in (" & clsCommon.GetMulcallString(arrDept) & ")"
        End If
        
        Return qry
    End Function
    Public Shared Function GetLeaveLedgerDetailQry(ByVal arrLoc As ArrayList, ByVal arrDiv As ArrayList, arrEmp As ArrayList, ByVal arrLeave As ArrayList, ByVal arrDept As ArrayList, ByVal ShowResgnEmp As Boolean, ByVal FromDate As Date, ByVal ToDate As Date) As String
        'Outermost.TransCode, Outermost.Alloted
        Dim qry As String = GetLeaveLedgerBaseQry(arrLoc, arrDiv, arrEmp, arrLeave, arrDept, ShowResgnEmp, FromDate, ToDate)
        qry = " select Outermost.empcode,Outermost.empname,emp.Joining_date as doj,convert(varchar,emp.RELIEVING_DATE,103) as dol,Outermost.departmentcode,Dept.Department_Name as departmentname,emp.location_code as location,loc.Location_desc as locationDesc,emp.Devision_code as Divisioncode,Div.Devision_Name as DevisionDesc,Outermost.Month,Outermost.Leavecode,Outermost.TransDate," & _
              " Outermost.Remarks,(case when Outermost.Alloted>0 then Outermost.Alloted else sum(outermost.Balance) over (partition by outermost.empcode,outermost.leavecode order by outermost.empcode,outermost.leavecode,outermost.Tr_Id)+Outermost.Taken end) as Alloted " & _
              ",Outermost.Taken,Outermost.Balance, " & _
              " sum(outermost.Balance) over (partition by outermost.empcode,outermost.leavecode order by outermost.empcode,outermost.leavecode,outermost.Tr_Id) as RunningBalance from " & _
              " (" & qry & ") as Outermost " & _
              " left join tspl_employee_master emp on Outermost.empcode=emp.emp_code " & _
              " left join tspl_location_master loc on emp.location_code=loc.location_code " & _
              " left join TSPL_DEVISION_MASTER Div on emp.devision_code=Div.Devision_code " & _
              " left join TSPL_DEPARTMENT_MASTER Dept on emp.department_code=Dept.department_code " & _
              " order by Outermost.empcode,Outermost.Leavecode,Outermost.TransDate"
        Return qry
    End Function
    Public Shared Function GetLeaveLedgerSummaryQry(ByVal arrLoc As ArrayList, ByVal arrDiv As ArrayList, arrEmp As ArrayList, ByVal arrLeave As ArrayList, ByVal arrDept As ArrayList, ByVal ShowResgnEmp As Boolean, ByVal FromDate As Date, ByVal ToDate As Date) As String
        Dim qry As String = GetLeaveLedgerBaseQry(arrLoc, arrDiv, arrEmp, arrLeave, arrDept, ShowResgnEmp, FromDate, ToDate)
        qry = " select Outermost.empcode,Outermost.empname,emp.Joining_date as doj,convert(varchar,emp.RELIEVING_DATE,103) as dol,Outermost.departmentcode,Dept.Department_Name as departmentname,emp.location_code as location,loc.Location_desc as locationDesc,emp.Devision_code as Divisioncode,Div.Devision_Name as DevisionDesc,Outermost.Leavecode,sum(Outermost.Balance) as Balance from " & _
              " (" & qry & ") as Outermost " & _
              " left join tspl_employee_master emp on Outermost.empcode=emp.emp_code " & _
              " left join tspl_location_master loc on emp.location_code=loc.location_code " & _
              " left join TSPL_DEVISION_MASTER Div on emp.devision_code=Div.Devision_code " & _
              " left join TSPL_DEPARTMENT_MASTER Dept on emp.department_code=Dept.department_code " & _
              " group by Outermost.empcode,Outermost.empname,emp.Joining_date,emp.RELIEVING_DATE,Outermost.Leavecode,emp.location_code,loc.Location_desc,emp.Devision_code,Div.Devision_Name,Outermost.departmentcode,Dept.Department_Name " & _
              " order by Outermost.empcode,Outermost.Leavecode"
        Return qry
    End Function
    Public Shared Function GetLeaveLedgerDetaildt(ByVal arrLoc As ArrayList, ByVal arrDiv As ArrayList, arrEmp As ArrayList, ByVal arrLeave As ArrayList, ByVal arrDept As ArrayList, ByVal ShowResgnEmp As Boolean, ByVal FromDate As Date, ByVal ToDate As Date) As DataTable
        Dim qry As String = GetLeaveLedgerDetailQry(arrLoc, arrDiv, arrEmp, arrLeave, arrDept, ShowResgnEmp, FromDate, ToDate)
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        Return dt
    End Function
    Public Shared Function GetLeaveLedgerSummarydt(ByVal arrLoc As ArrayList, ByVal arrDiv As ArrayList, arrEmp As ArrayList, ByVal arrLeave As ArrayList, ByVal arrDept As ArrayList, ByVal ShowResgnEmp As Boolean, ByVal FromDate As Date, ByVal ToDate As Date) As DataTable
        Dim qry As String = GetLeaveLedgerSummaryQry(arrLoc, arrDiv, arrEmp, arrLeave, arrDept, ShowResgnEmp, FromDate, ToDate)
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        Return dt
    End Function
    Public Shared Function GetLeaveRegisterDTPeriod(ByVal arrLoc As ArrayList, ByVal arrDivision As ArrayList, ByVal arrEmp As ArrayList, ByVal strfromdate As Date, ByVal strTodate As Date, ByRef Qrystring As String) As DataTable
        Dim dt As DataTable
        Try
            Dim qry As String = ""
            qry = qry & " select Leave_Fun.EMP_CODE,emp.Emp_Name,emp.Location_Code,emp.Devision_Code,Leave_Fun.Leave_Code,Leave.Leave_Name,OPENING,ALLOTED,AVAILED,ADJUSTMENT_PLUS,ADJUSTMENT_MINUS,BALANCE from TSPL_FUN_LEAVE_STATUS_PERIOD(convert(date,'" + strfromdate + "',103),convert(date,'" + strTodate + "',103)) AS Leave_Fun " & _
                " left join tspl_employee_master emp on Leave_Fun.Emp_Code=emp.Emp_Code " & _
                " left join TSPL_LEAVE_MASTER Leave on Leave.Leave_Code=Leave_Fun.Leave_Code where 2=2 "
            If Not arrLoc Is Nothing AndAlso arrLoc.Count > 0 Then
                qry = qry & " and emp.Location_Code in (" & clsCommon.GetMulcallString(arrLoc) & ")"
            End If
            If Not arrDivision Is Nothing AndAlso arrDivision.Count > 0 Then
                qry = qry & " and emp.Devision_Code in (" & clsCommon.GetMulcallString(arrDivision) & ")"
            End If
            If Not arrEmp Is Nothing AndAlso arrEmp.Count > 0 Then
                qry = qry & " and emp.Devision_Code in (" & clsCommon.GetMulcallString(arrEmp) & ")"
            End If

            Qrystring = qry
            dt = clsDBFuncationality.GetDataTable(qry)

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return dt
    End Function
    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select LEAVE_CODE from TSPL_LEAVE_MASTER where LEAVE_CODE ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
    Public Shared Function GetCboLeaveTypeDataTable() As DataTable
        Dim DT As DataTable = New DataTable
        DT.Columns.Add("Code", GetType(String))
        DT.Columns.Add("Name", GetType(String))
        Dim DR As DataRow = DT.NewRow()
        DR("Code") = "EL"
        DR("Name") = "Earned Leave"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "CL"
        DR("Name") = "Casual Leave"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "MED"
        DR("Name") = "Medical Leave"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "COFF"
        DR("Name") = "Compensatory Off"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "MATRL"
        DR("Name") = "Maternity Leave"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "Other"
        DR("Name") = "Other"
        DT.Rows.Add(DR)
        DT.AcceptChanges()
        Return DT
    End Function
End Class
