
Imports System.Data.SqlClient
Imports common


Public Class clsPayrollPaymentMode
#Region "Variables"
    Public Code As String = Nothing
    Public Name As String = Nothing
#End Region

    Public Shared Function SaveData(ByVal obj As clsPayrollPaymentMode, ByVal isNewEntry As Boolean) As Boolean
        Dim qry As String = ""
        Dim IsSaved As Boolean = False
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Name", obj.Name)
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_Payment_MODE where Code='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.PayrollPaymentMode, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy hh:mm tt"))
                clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_Payment_MODE", OMInsertOrUpdate.Insert, "")
            Else
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_Payment_MODE", OMInsertOrUpdate.Update, "TSPL_Payment_MODE.Code='" + obj.Code + "'")
            End If
            'trans.Commit()
        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return IsSaved
    End Function
    'Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsRelationMaster
    '    Return GetData(strCode, NavType, Nothing)
    'End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsPayrollPaymentMode
        Dim obj As clsPayrollPaymentMode = Nothing
        Dim Arr As List(Of clsPayrollPaymentMode) = Nothing
        Dim qry As String = "select Code ,Name from TSPL_Payment_MODE where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_Payment_MODE.Code = (select MIN(Code) from TSPL_Payment_MODE WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_Payment_MODE.Code = (select Max(Code) from TSPL_Payment_MODE WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_Payment_MODE.Code = (select TOP 1 Code from TSPL_Payment_MODE WHERE 1=1 " + whrclas + " and Code='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_Payment_MODE.Code = (select Min(Code) from TSPL_Payment_MODE where Code > '" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_Payment_MODE.Code = (select Max(Code) from TSPL_Payment_MODE where Code < '" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsPayrollPaymentMode()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("Name"))
        End If
        Return obj
    End Function


End Class
