Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports System.Data
Imports XpertERPEngine
Imports System.Data.SqlClient
Imports System.Windows.Forms
Imports System.Configuration
Imports Telerik.Collections.Generic
Imports Excel = Microsoft.Office.Interop.Excel
Imports common
'Start date =18/5/2011
'End date =20/5/2011
'Last modify date = 30/5/2011
'Database =TSPlERP
' Tables=Tspl_channel_category_master
'End Date -'--preeti gupta-ticket no.[BM00000003133]
Public Class frmchannelCategory
    Inherits FrmMainTranScreen
    Dim userCode, companyCode As String
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim dr As DataTable
    'This Cunstructer is used to send usercode and compcode data in table.
    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub
    Private Sub frmchannelCategory_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        fndID.MyMaxLength = 12
        rdtxtcategoryname1.MaxLength = 50
        text_changed()
        fndID_Leave()
        SetUserMgmtNew()
        fndID.Text = ""
        rdtxtcategoryname.Text = ""
        fndID.Enabled = True
        rdtxtcategoryname1.Enabled = True
        rdbtnsave.Enabled = True
        rdbtndelete.Enabled = False
        rdbtnclose.Enabled = True
        fndID.TabIndex = 0
        rdtxtcategoryname1.TabIndex = 1
        ButtonToolTip.SetToolTip(rdbtnsave, "Press Alt+S for Save/Update ")
        'ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(rdbtndelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(rdbtnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(rdreset, "Press Alt+N Adding New ")
        ' ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")



        'AddHandler fndID.ValueChanged, AddressOf text_changed
        'AddHandler fndID.txtValue.KeyPress, AddressOf fndID_KeyPress
        'AddHandler fndID.txtValue.Leave, AddressOf fndID_Leave
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.channelCategory)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        rdbtnsave.Visible = MyBase.isModifyFlag
        'btnPost.Visible = MyBase.isPostFlag
        rdbtndelete.Visible = MyBase.isDeleteFlag
    End Sub
    ' This Function is used for insert.
    Public Sub funinsert()
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from tspl_channel_category_master where channel_category_id='" & fndID.Value & "'")
                If ChkNewEntry = 0 Then
                    fndID.Value = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.ChannelCategory, "", "")
                    If clsCommon.myLen(fndID.Value) <= 0 Then
                        Throw New Exception("Error in Code Generation")
                    End If
                End If
            End If
            'connectSql.RunSp("sp_channelcategorymaster", New SqlParameter("@type", rdbtnsave.Text), New SqlParameter("@channelcategoryid", fndID.Value), New SqlParameter("@channelcategoryname", rdtxtcategoryname1.Text), New SqlParameter("@createdby", userCode), New SqlParameter("@createddate", connectSql.serverDate()), New SqlParameter("@modifyby", userCode), New SqlParameter("@modifydate", connectSql.serverDate()), New SqlParameter("@compcode", companyCode))
            clsDBFuncationality.UpdateInAllDatabase("sp_channelcategorymaster", New SqlParameter("@type", rdbtnsave.Text), New SqlParameter("@channelcategoryid", fndID.Value), New SqlParameter("@channelcategoryname", rdtxtcategoryname1.Text), New SqlParameter("@createdby", userCode), New SqlParameter("@createddate", connectSql.serverDate()), New SqlParameter("@modifyby", userCode), New SqlParameter("@modifydate", connectSql.serverDate()), New SqlParameter("@compcode", companyCode))


            myMessages.insert()

        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub
    ' This function is used for Update.
    Public Sub funupdate()
        Try
            clsDBFuncationality.UpdateInAllDatabase("sp_channelcategorymaster", New SqlParameter("@type", rdbtnsave.Text), New SqlParameter("@channelcategoryid", fndID.Value), New SqlParameter("@channelcategoryname", rdtxtcategoryname1.Text), New SqlParameter("@createdby", userCode), New SqlParameter("@createddate", connectSql.serverDate()), New SqlParameter("@modifyby", userCode), New SqlParameter("@modifydate", connectSql.serverDate()), New SqlParameter("@compcode", companyCode))
            myMessages.update()
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub
    'This Function is used for delete.
    Public Sub fundelete()
        Try
            clsDBFuncationality.UpdateInAllDatabase("sp_channelcategorymaster", New SqlParameter("@type", rdbtndelete.Text), New SqlParameter("@channelcategoryid", fndID.Value), New SqlParameter("@createddate", connectSql.serverDate()), New SqlParameter("@modifydate", connectSql.serverDate()))

        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub
    'This function is used for reset all Control.
    Public Sub funreset()
        fndID.MyReadOnly = False
        fndID.Value = ""
        fndID.Enabled = True
        rdtxtcategoryname1.Text = ""
        fndID.Enabled = True
        rdtxtcategoryname1.Enabled = True
        rdbtnsave.Enabled = True
        rdbtnsave.Text = "Save"
        rdbtndelete.Enabled = False
        rdbtnclose.Enabled = True
    End Sub
    Private Sub rdbtnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnsave.Click
        SaveData()
    End Sub
    Sub SaveData()
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso fndID.Value = "" Then
            myMessages.blankValue(Me, "Category ID", Me.Text)
        ElseIf (rdtxtcategoryname1.Text = "") Then
            myMessages.blankValue(Me, "Category Name", Me.Text)

        Else
            If rdbtnsave.Text = "Save" Then
                funinsert()
                funfill()
            ElseIf (rdbtnsave.Text = "Update") Then
                funupdate()
            End If
        End If
    End Sub
    Private Sub rdreset_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdreset.Click
        funreset()
    End Sub

    Private Sub rdbtndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtndelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(fndID.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow("You Cannot Delete Record")
            Exit Sub
        End If
        If myMessages.deleteConfirm() Then
            fundelete()
            common.clsCommon.MyMessageBoxShow("Deleted Sucessfully")
            rdbtnsave.Text = "Save"
            rdbtndelete.Enabled = False

        End If

    End Sub

    Private Sub rdbtnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnclose.Click
        Me.Close()
    End Sub
    Sub text_changed()
        Try
            Dim query As String = "Select Channel_category_id from tspl_channel_category_master where channel_category_id ='" + fndID.Value.Trim() + "'"
            Dim dr As DataTable
            dr = clsDBFuncationality.GetDataTable(query)
            Dim value As String = String.Empty
            If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                value = dr.Rows(0)(0).ToString()
            End If
            If (value <> "") Then
                funfill()
                rdbtnsave.Text = "Update"
                rdbtnsave.Enabled = True
                rdbtndelete.Enabled = True
                rdtxtcategoryname1.Enabled = True
                rdbtndelete.Enabled = True
            Else
                rdbtndelete.Enabled = False
                rdbtnsave.Text = "Save"
                rdbtnsave.Enabled = True
                rdtxtcategoryname1.Text = ""
                rdtxtcategoryname1.Enabled = True
            End If
            'If userCode <> "ADMIN" Then
            '    If funSetUserAccess() = False Then Exit Sub
            'End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub
    ' This function is used to retrive data text_changed of finder.
    Public Sub funfill()
        Try
            Dim query As String = " Select Channel_category_id,channel_category_name from tspl_channel_category_master where channel_category_id ='" + fndID.Value.Trim() + "'"
            dr = clsDBFuncationality.GetDataTable(query)

            If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                fndID.Value = dr.Rows(0)(0).ToString().Trim()
                rdtxtcategoryname1.Text = dr.Rows(0)(1).ToString()
                rdbtnsave.Text = "Update"
                rdbtndelete.Enabled = True
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Sub fndID_Leave()
        If fndID.Value <> "" Then
            rdtxtcategoryname1.Enabled = True
            rdbtnsave.Enabled = True
            rdbtnclose.Enabled = True
        End If
    End Sub

    Private Sub fndID_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndID.Query = "Select Channel_category_id as [Channel Category Id],channel_category_name[Channel Category Name] from TSPL_CHANNEL_CATEGORY_MASTER"
        'fndID.ConnectionString = connectSql.SqlCon()
        'fndID.Caption = "Channel Category "
        'fndID.ValueToSelect = "Channel Category Id"
        'fndID.ValueToSelect1 = "Channel Category Name"
    End Sub
    ' This event is used for validate (')in Finder.
    Private Sub fndID_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
        If e.KeyChar = Chr(39) Then
            e.Handled = True
        End If
    End Sub

    Private Sub rdmenuexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexport.Click
        Dim query As String = "select channel_category_id as [Channel Category Id],channel_category_name as [Channel Category Name]from TSPL_CHANNEL_CATEGORY_MASTER "
        transportSql.ExporttoExcel(query, Me)
    End Sub

    Private Sub rdmenuexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexit.Click
        Me.Close()
    End Sub
    ' This event is Used for Import Data from excel sheet to database.
    Private Sub rdmenuimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuimport.Click
        Dim dgv As New RadGridView
        Me.Controls.Add(dgv)
        If transportSql.importExcel(dgv, "Channel Category Id", "Channel Category Name") Then
            Dim trans As SqlTransaction = Nothing
            Try
                connectSql.OpenConnection()
                trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each dgrv As GridViewRowInfo In dgv.Rows

                    Dim strchannelcategoryid As String = clsCommon.myCstr(dgrv.Cells(0).Value)
                    If clsCommon.myLen(strchannelcategoryid) > 12 Then
                        Throw New Exception("Check the length of channel category id")
                    End If

                    Dim strchannelcategoryname As String = clsCommon.myCstr(dgrv.Cells(1).Value)
                    If clsCommon.myLen(strchannelcategoryname) > 50 Then
                        Throw New Exception("Check the length of channel category name")
                    End If

                    If String.IsNullOrEmpty(strchannelcategoryid) Or clsCommon.myLen(strchannelcategoryid) > 12 Then
                        Throw New Exception("Channel Category Id has some incorrect values")
                    End If

                    Dim sql1 As String = "select count(*)from tspl_channel_category_master where channel_category_id='" + strchannelcategoryid + "'"
                    Dim i As Integer = CInt(connectSql.RunScalar(trans, sql1))
                    If (i = 0) Then
                        Dim query As String = "insert into tspl_channel_category_master values('" + strchannelcategoryid + "','" + strchannelcategoryname + "','" + userCode + "','" + connectSql.serverDate(trans) + "','" + userCode + "','" + connectSql.serverDate(trans) + "','" + companyCode + "')"
                        connectSql.RunSqlTransaction(trans, query)
                    Else
                        Dim query1 As String = "update tspl_channel_category_master set channel_category_name ='" + strchannelcategoryname + "' where channel_category_id='" + strchannelcategoryid + "' "
                        connectSql.RunSqlTransaction(trans, query1)
                    End If
                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transferred Completed", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                trans.Rollback()
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)


            End Try
        End If
        Me.Controls.Remove(dgv)
    End Sub
    'This leave event is used for check data in table which is exist or not.
    Public Sub channelid_leave(ByVal sender As System.Object, ByVal e As System.EventArgs)
        If fndID.Value = "" Then

        Else
            Try
                Dim str As String = "Select Channel_category_id as [Channel Category Id],channel_category_name[Channel Category Name] from TSPL_CHANNEL_CATEGORY_MASTER where Channel_category_id='" + fndID.Value + "'"
                Dim dr As DataTable
                Dim strvalue As String = String.Empty

                dr = clsDBFuncationality.GetDataTable(str)

                If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                    strvalue = dr.Rows(0)(0).ToString()
                End If

                If strvalue <> "" Then

                Else : str = ""

                    rdtxtcategoryname1.Text = ""
                    common.clsCommon.MyMessageBoxShow("This Channel Category Id does not exist")
                    fndID.Value = ""


                End If


            Catch ex As Exception
                myMessages.myExceptions(ex)
            End Try
        End If
    End Sub
    ' priti added on 01-06-2011 --- To implement the access control
    'Private Function funSetUserAccess() As Boolean
    '    Try
    '        'If funCheckLoginStatus() = False Then Exit Function
    '        Dim strRights As String
    '        Dim strTemp() As String
    '        Dim strProgCode = "CHANNEL-CAT"
    '        strRights = enuUserRights.enuRead & "," & enuUserRights.enuModify & "," & enuUserRights.enuDelete
    '        strRights = modUserMgt.funGetPermissions(strRights, strProgCode)
    '        strTemp = Split(strRights, ",")
    '        If strTemp(0) = "0" Then
    '            MsgBox("Permission Denied", MsgBoxStyle.Critical, Me.Text)
    '            funSetUserAccess = False
    '            blnRead = False
    '            Me.Close()
    '            Exit Function
    '        Else
    '            blnRead = True
    '        End If
    '        If strTemp(1) = "0" Then 'Grant modify access
    '            'rdbtnsave.Enabled = False
    '        End If
    '        If strTemp(2) = "0" Then 'Grant modify access
    '            ' rdbtndelete.Enabled = False
    '        End If

    '        funSetUserAccess = True
    '    Catch er As Exception

    '    End Try
    'End Function

    Private Sub frmchannelCategory_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso rdbtnsave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            'PostData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso rdbtndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funreset()
        End If
    End Sub

    Private Sub fndID__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndID._MYValidating
        Dim str As String = "select count(*) from TSPL_CHANNEL_CATEGORY_MASTER where Channel_category_id ='" + fndID.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 Then
            fndID.MyReadOnly = False
        Else
            fndID.MyReadOnly = True
        End If
        If fndID.MyReadOnly OrElse isButtonClicked Then
            Dim qry As String = "Select Channel_category_id as [ChannelCategoryId],channel_category_name[Channel Category Name] from TSPL_CHANNEL_CATEGORY_MASTER"
            fndID.Value = clsCommon.ShowSelectForm("POProject3", qry, "ChannelCategoryId", "", fndID.Value, "", isButtonClicked)
            ' rdtxtgroupdesc.Text = clsDBFuncationality.getSingleValue("Select group_desc from tspl_vendor_group where ven_group_code='" + fndgroupcode.Value + "'")
        End If
        If fndID.Value IsNot Nothing Then
            rdbtndelete.Enabled = True
        Else
            rdbtndelete.Enabled = False
        End If
        text_changed()
        fndID_Leave()
    End Sub

    Private Sub fndID__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavigatorType As common.NavigatorType) Handles fndID._MYNavigator
        Dim qst As String = "Select Channel_category_id as [Channel Category Id],channel_category_name[Channel Category Name] from TSPL_CHANNEL_CATEGORY_MASTER where  2=2 "
        Select Case NavigatorType
            Case NavigatorType.Current
                '  qst += "and assign_to='" + txtassign.Value + "' "
                ' qst += "and job_code in ('" + txtcode1.Value + "')"
            Case NavigatorType.Next
                qst += "and Channel_category_id in (select min(Channel_category_id) from TSPL_CHANNEL_CATEGORY_MASTER where Channel_category_id>'" + fndID.Value + "'   ) "
            Case NavigatorType.First
                qst += "and Channel_category_id in (select MIN(Channel_category_id) from TSPL_CHANNEL_CATEGORY_MASTER  )"
            Case NavigatorType.Last
                qst += "and Channel_category_id in (select Max(Channel_category_id) from TSPL_CHANNEL_CATEGORY_MASTER  )"
            Case NavigatorType.Previous
                qst += "and Channel_category_id in (select max(Channel_category_id) from TSPL_CHANNEL_CATEGORY_MASTER where Channel_category_id<'" + fndID.Value + "'   )"
        End Select
        ' fun_gridfill()
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            fndID.Value = clsCommon.myCstr(dt.Rows(0)("Channel Category Id"))

        End If
        'TextChanged()
        If fndID.Value IsNot Nothing Then
            rdbtndelete.Enabled = True
        Else
            rdbtndelete.Enabled = False

        End If
        text_changed()
        fndID_Leave()

    End Sub
End Class


