'Developed By -BibhuPrasad Parida
'Database - TSPLERP
'Table - tspl_customer_category_master
'Start Date -
'End Date -

''''17/10/2011'''''[Pankaj Kumar Chaudhary]''''added new Field(Shelf LIfe) with the Functionalities.'''''''''''''''''''''
'--20/12/2012--Updation By --Pankaj Kumar--- Applied Validations
'--preeti gupta-ticket no-[BM00000003128]
Imports Telerik.WinControls
Imports Telerik.WinControls.UI
Imports System.Data
Imports System.Data.SqlClient
Imports common
Imports XpertERPEngine

Public Class frmCustomerCategory
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim strSql As String

#Region "Variables"
    Dim sql As String
    Dim ds As DataSet
    Dim dr As SqlDataReader
    Dim tableName As String = "TSPL_TAX_MASTER"
    Dim tableCode As String = "Tax_Code"
    Dim codePrefix As String = "TAX"
    Dim userCode, companyCode As String

    Const colSelect As String = "SELECT"
    Const colCompCode As String = "COMPCODE"
    Const colCompName As String = "COMPNAME"
    Const colDataBaseName As String = "DATABASE"

#End Region
#Region "Constructor"
    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub
#End Region
#Region "ButtonClick Event"
    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        SaveData()
    End Sub
    Sub SaveData()
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso fndCustomerId.Value = "" Then
            myMessages.blankValue("Customer Category")
            fndCustomerId.Focus()
        Else
            If fndCustomerId.Value <> "" Then
                If MyBase.isModifyonPasswordFlag Then
                    If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.CustomeCategory, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                    Else
                        Return
                    End If
                End If
                If btnSave.Text = "Save" Then
                    funInsert()
                Else
                    funUpdate()


                End If
            End If
        End If
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funreset()
    End Sub
    Sub funreset()
        fndCustomerId.Value = ""
        txtCustomerDesc.Text = ""
        fndPriceCode.Value = ""
        txtPriceCodeDesc.Text = ""
        fndRoute.Value = ""
        txtRouteDesc.Text = ""
        btnSave.Enabled = True
        fndPriceCode.Enabled = True
        btnSave.Text = "Save"
        btnDelete.Enabled = False
        fndCustomerId.Focus()
        TxtShfLife.Text = ""
        fndPriceCodeNon.Value = ""
        txtPriceCodeNon.Text = ""
        fndCustomerId.MyReadOnly = False
        SetDataBaseGrid()
    End Sub
    Delegate Sub del()
    Sub hello()
        MsgBox("vfvc")
    End Sub
    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(fndCustomerId.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow("You Cannot Delete Record")
            Exit Sub
        End If
        If myMessages.deleteConfirm Then
            funDelete()
        End If
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        Me.Close()
    End Sub

#End Region
#Region "TextChanged Event"
    Sub fndRouteTextChanged()
        ' txtRouteDesc.Text = fndRoute.txtValue.Tag
        txtRouteDesc.Text = connectSql.RunScalar("select Route_Desc as [Route Description]from TSPL_ROUTE_MASTER where  Route_No ='" + fndRoute.Value + "'")
        'dr = connectSql.RunSqlReturnDR("select Price_Code,Price_Code_Desc,NonPrice_Code from TSPL_ROUTE_MASTER where Route_No='" + fndRoute.Value + "'")
        strSql = "select Price_Code,Price_Code_Desc,NonPrice_Code from TSPL_ROUTE_MASTER where Route_No='" + fndRoute.Value + "'"


        Dim dt1 As DataTable = clsDBFuncationality.GetDataTable(strSql)
        If dt1 IsNot Nothing AndAlso dt1.Rows.Count > 0 Then
            For Each dr As DataRow In dt1.Rows
                fndPriceCode.Value = dr(0).ToString()
                txtPriceCodeDesc.Text = dr(1).ToString()
                fndPriceCodeNon.Value = Convert.ToString(dr("NonPrice_Code"))
                txtPriceCodeNon.Text = connectSql.RunScalar("select Price_Code_Desc  from TSPL_PRICE_COMPONENT_MAPPING where Price_Code  ='" + fndPriceCodeNon.Value + "'")
            Next
        End If
        If fndPriceCode.Value = String.Empty Then
            fndPriceCode.Enabled = True
        Else
            fndPriceCode.Enabled = True

        End If
    End Sub
    Private Sub fndRoute_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Sub fndpricecodetextchanged()
        'txtPriceCodeDesc.Text = fndPriceCode.txtValue.Tag

        txtPriceCodeDesc.Text = connectSql.RunScalar("select Price_Code_Desc  from TSPL_PRICE_COMPONENT_MAPPING where Price_Code  ='" + fndPriceCode.Value + "'")
    End Sub
    Private Sub fndPriceCode_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
    Sub fndPriceCodeNonTextChanged()
        'txtPriceCodeDesc.Text = fndPriceCode.txtValue.Tag

        txtPriceCodeNon.Text = connectSql.RunScalar("select Price_Code_Desc  from TSPL_PRICE_COMPONENT_MAPPING where Price_Code  ='" + fndPriceCodeNon.Value + "'")
    End Sub
    Private Sub fndPriceCodeNon_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs)
       
    End Sub
    Private Sub fndCustomerId_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs)
        
        LoadData()

    End Sub
    Sub LoadData()
        Dim s As String
        If fndCustomerId.Value <> "" Then
            'dr = connectSql.RunSqlReturnDR("select Cust_Category_Code from tspl_customer_category_master where Cust_Category_Code='" + fndCustomerId.Value + "'")
            'Dim s As String
            'While dr.Read()
            '    s = dr(0).ToString()
            'End While
            'dr.Close()
            strSql = "select Cust_Category_Code from tspl_customer_category_master where Cust_Category_Code='" + fndCustomerId.Value + "'"
            S = clsDBFuncationality.getSingleValue(strSql)
            If s <> fndCustomerId.Value Then
                txtCustomerDesc.Text = ""
                btnSave.Text = "Save"
                btnDelete.Enabled = False
            Else
                funFill()

            End If
        End If
    End Sub
#End Region
#Region "KeyPress Event"

    Private Sub fndRoute_keypress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)

        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If
    End Sub
    Private Sub fndCustomerId_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)

        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If
    End Sub

    Private Sub fndPriceCode_keypress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
        'fndPriceCode.txtValue.CharacterCasing = CharacterCasing.Upper
        'If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
        '    e.Handled = True
        'End If
    End Sub
    'Private Sub fndCustomerId_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles fndCustomerId.KeyPress
    '    fndCustomerId.txtValue.CharacterCasing = CharacterCasing.Upper
    'End Sub
#End Region
#Region "Methods"
    'fill Customer Category Details
    Private Sub funFill()
        If fndCustomerId.Value <> "" Then

            ''''17/10/2011'''''Updated By'''''''''Pankaj Kumar Chaudhary
            ds = connectSql.RunSQLReturnDS("select Cust_Category_Desc,Price_Code,Price_Code_Desc,Route_No,Route_Desc, Shelf_life,Price_CodeNon,Price_Code_DescNon from tspl_customer_category_master where Cust_Category_Code='" + fndCustomerId.Value + "'")

            Dim dt As New DataTable()
            dt = ds.Tables(0)
            Dim dr As DataRow = dt.Rows(0)
            'RemoveHandler fndRoute.Value, AddressOf fndRoute_TextChanged
            fndRouteTextChanged()
            txtCustomerDesc.Text = dr(0).ToString()
            fndPriceCode.Value = dr(1).ToString()
            txtPriceCodeDesc.Text = dr(2).ToString()
            fndRoute.Value = dr(3).ToString()
            txtRouteDesc.Text = dr(4).ToString()
            TxtShfLife.Text = dr(5).ToString() '''''''' Added By Pankaj Kumar Chaudhary'''''17/10/2011
            fndPriceCodeNon.Value = dr(6).ToString()
            txtPriceCodeNon.Text = dr(7).ToString()
            btnSave.Enabled = True
            btnSave.Text = "Update"
            btnDelete.Enabled = True
        Else
            btnSave.Enabled = True
            btnSave.Text = "Save"
        End If
        fndRouteTextChanged()
        'AddHandler fndRoute.Value, AddressOf fndRoute_TextChanged
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub


    'insert Customer Category Details
    Private Sub funInsert()
        If fndPriceCode.Value = "" Then
            myMessages.blankValue("Price Code")
            fndPriceCode.Focus()
            'ElseIf  fndRoute.Value   = "" Then
            '    myMessages.blankValue("Route Id")

        Else
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from tspl_customer_master where Cust_Category_Code='" & fndCustomerId.Value & "'")
                If ChkNewEntry = 0 Then
                    fndCustomerId.Value = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.CustomerCategory, "", "")
                    If clsCommon.myLen(fndCustomerId.Value) <= 0 Then
                        Throw New Exception("Error in Code Generation")
                    End If
                End If
            End If
            Try
                clsDBFuncationality.SaveAStorePorcedure("sp_tspl_Customer_Category_Master_insert", New SqlParameter("@CustCategoryCode", fndCustomerId.Value), New SqlParameter("@CustCategoryDesc", txtCustomerDesc.Text), New SqlParameter("@PriceCode", fndPriceCode.Value), New SqlParameter("@PriceCodeDesc", txtPriceCodeDesc.Text), New SqlParameter("@RouteId", fndRoute.Value), New SqlParameter("@RouteDesc", txtRouteDesc.Text), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate()), New SqlParameter("@ModifiedBy", userCode), New SqlParameter("@ModifiedDate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode), New SqlParameter("@ShelfLife", TxtShfLife.Text), New SqlParameter("@PriceCodeNon", Me.fndPriceCodeNon.Value), New SqlParameter("@PriceCodeDescNon", Me.txtPriceCodeNon.Text))
                myMessages.insert()
                btnSave.Text = "Update"
                btnDelete.Enabled = True
                txtCustomerDesc.Enabled = True
            Catch ex As Exception
                myMessages.myExceptions(ex)

            End Try
        End If
    End Sub
    'delete Customer Category Details
    Private Sub funDelete()
        Try
            clsDBFuncationality.SaveAStorePorcedure("sp_tspl_Customer_Category_Master_delete", New SqlParameter("@CustCategoryCode", fndCustomerId.Value))
            myMessages.delete()
            btnSave.Text = "Save"
            btnDelete.Enabled = False
            txtCustomerDesc.Enabled = True
        Catch ex As Exception
            myMessages.myExceptions(ex)

        End Try
    End Sub



    'update Customer Category Details
    Private Sub funUpdate()
        If fndPriceCode.Value = "" Then
            ' common.clsCommon.MyMessageBoxShow("Price Code cannot be blank.")
            myMessages.blankValue("Price Code")
        Else
            Try
                clsDBFuncationality.SaveAStorePorcedure("sp_tspl_Customer_Category_Master_update", New SqlParameter("@CustCategoryCode", fndCustomerId.Value), New SqlParameter("@CustCategoryDesc", txtCustomerDesc.Text), New SqlParameter("@PriceCode", fndPriceCode.Value), New SqlParameter("@PriceCodeDesc", txtPriceCodeDesc.Text), New SqlParameter("@RouteId", fndRoute.Value), New SqlParameter("@RouteDesc", txtRouteDesc.Text), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate()), New SqlParameter("@ModifiedBy", userCode), New SqlParameter("@ModifiedDate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode), New SqlParameter("@ShelfLife", TxtShfLife.Text), New SqlParameter("@PriceCodeNon", Me.fndPriceCodeNon.Value), New SqlParameter("@PriceCodeDescNon", Me.txtPriceCodeNon.Text))
                If common.clsCommon.MyMessageBoxShow("Do you want to Update Price Code In Customer's Master too?", "", MessageBoxButtons.YesNo, RadMessageIcon.Question) = DialogResult.Yes Then
                    Dim strConfirm As String = "update tspl_customer_master set Price_Code ='" + fndPriceCode.Value + "' , price_CodeNon ='" + fndPriceCodeNon.Value + "', Route_No='" + fndRoute.Value + "' where Cust_Category_Code ='" + fndCustomerId.Value + "' and Route_No='" + fndRoute.Value + "'"
                    connectSql.RunSql(strConfirm)
                End If
                myMessages.update()
                btnSave.Text = "Update"
                btnDelete.Enabled = True
                txtCustomerDesc.Enabled = True
            Catch ex As Exception
                myMessages.myExceptions(ex)

            End Try
        End If

    End Sub
    'priti added on 01-06-2011 --- To implement the access control
    'Private Function funSetUserAccess() As Boolean
    '    Try
    '        'If funCheckLoginStatus() = False Then Exit Function
    '        Dim strRights As String
    '        Dim strTemp() As String
    '        Dim strProgCode = "CUST-CAT-M"
    '        strRights = enuUserRights.enuRead & "," & enuUserRights.enuModify & "," & enuUserRights.enuDelete
    '        strRights = modUserMgt.funGetPermissions(strRights, strProgCode)
    '        strTemp = Split(strRights, ",")
    '        If strTemp(0) = "0" Then
    '            MsgBox("Permission Denied", MsgBoxStyle.Critical, Me.Text)
    '            funSetUserAccess = False
    '            blnRead = False
    '            Me.Close()
    '            Exit Function
    '        Else
    '            blnRead = True
    '        End If
    '        If strTemp(1) = "0" Then 'Grant modify access
    '            btnSave.Enabled = False
    '        End If
    '        If strTemp(2) = "0" Then 'Grant modify access
    '            btnDelete.Enabled = False
    '        End If

    '        funSetUserAccess = True
    '    Catch er As Exception

    '    End Try
    'End Function
    'Code ends here
#End Region
#Region "Finder Load"
    Private Sub fndCustomerId_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndCustomerId.ConnectionString = connectSql.SqlCon()
        'fndCustomerId.Query = "select Cust_Category_Code as [Customer Category Code],Cust_Category_Desc as [Customer Code Description] from tspl_Customer_Category_Master  order by Cust_Category_Code"
        'fndCustomerId.ValueToSelect = "Customer Category Code"
        'fndCustomerId.ValueToSelect1 = "Customer Code Description"
        'fndCustomerId.Caption = "Customer Details"
    End Sub
#End Region
#Region "MenuClose Event"
    Private Sub MenuClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuClose.Click
        Me.Close()
    End Sub

#End Region
#Region "Finder Leave Event"

    Private Sub fndCustomerId_Leave(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'If fndCustomerId.txtValue.Text <> "" Then
        '    txtCustomerDesc.Enabled = True
        '    txtCustomerDesc.Focus()
        '    btnSave.Enabled = True

        'Else
        '    btnClose.Focus()

        'End If
    End Sub
#End Region
#Region "Import/Export"
    Private Sub MenuImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        If transportSql.importExcel(gv, "CUST_CATEGORY_CODE", "CUST_CATEGORY_DESC", "Price_Code", "Price_Code_Desc", "Route_No", "Route_Desc", "Price Code Non-Excise", "Price Code Non-Excise Description") Then
            Dim trans As SqlTransaction = Nothing
            Try
                trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim strCustCode As String
                    Dim strCustDesc As String
                    Dim strPCode As String
                    ' Dim strPCodeDesc As String
                    Dim strRouteId As String
                    Dim strRouteDesc As String
                    If String.IsNullOrEmpty(clsCommon.myCstr(grow.Cells(0).Value)) Then
                        Throw New Exception("Customer Category can not be blank")
                    ElseIf clsCommon.myLen(grow.Cells(0).Value) > 12 Then
                        Throw New Exception("Customer Category cannot be greater than 12 length.")
                    Else
                        strCustCode = clsCommon.myCstr(grow.Cells(0).Value)
                    End If

                    If clsCommon.myLen(grow.Cells(1).Value) > 50 Then
                        Throw New Exception("Customer Category Description cannot be greater than 50 length.")
                    Else
                        strCustDesc = clsCommon.myCstr(grow.Cells(1).Value)
                    End If

                    If String.IsNullOrEmpty(clsCommon.myCstr(grow.Cells(2).Value)) Then
                        Throw New Exception("Price Code cannot be blank")
                    ElseIf clsCommon.myLen(grow.Cells(2).Value) > 12 Then
                        Throw New Exception("Price Code cannot be greater than 12 length.")
                    Else
                        strPCode = clsCommon.myCstr(grow.Cells(2).Value)
                    End If

                    If clsCommon.myLen(grow.Cells(3).Value) > 100 Then
                        Throw New Exception("Price Code Description cannot be greater than 100 length.")
                    Else
                        strRouteDesc = clsCommon.myCstr(grow.Cells(3).Value)
                    End If

                    If clsCommon.myLen(grow.Cells(4).Value) > 12 Then
                        Throw New Exception("Route Id cannot be greater than 12 length.")
                    Else
                        strRouteId = clsCommon.myCstr(grow.Cells(4).Value)
                    End If

                    If clsCommon.myLen(grow.Cells(5).Value) > 50 Then
                        Throw New Exception("Route Description cannot be greater than 50 length.")
                    Else
                        strRouteDesc = (grow.Cells(5).Value)
                    End If

                    Dim strPriceCodeNon As String = clsCommon.myCstr(grow.Cells(6).Value)
                    Dim strPriceCodeNonDesc As String = clsCommon.myCstr(grow.Cells(7).Value)
                    Dim Datee As String = clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans))
                    Dim sql1 As String = "select COUNT(*) from TSPL_CUSTOMER_CATEGORY_MASTER  where CUST_CATEGORY_CODE='" + strCustCode + "'"
                    Dim i As Integer = CInt(clsDBFuncationality.getSingleValue(sql1, trans))
                    If (i = 0) Then
                        connectSql.RunSpTransaction(trans, "sp_tspl_Customer_Category_Master_insert", New SqlParameter("@CustCategoryCode", strCustCode), New SqlParameter("@CustCategoryDesc", strCustDesc), New SqlParameter("@PriceCode", strPCode), New SqlParameter("@PriceCodeDesc", strRouteDesc), New SqlParameter("@RouteId", strRouteId), New SqlParameter("@RouteDesc", strRouteDesc), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", Datee), New SqlParameter("@ModifiedBy", userCode), New SqlParameter("@ModifiedDate", Datee), New SqlParameter("@CompCode", companyCode), New SqlParameter("@PriceCodeNon", strPriceCodeNon), New SqlParameter("@PriceCodeDescNon", strPriceCodeNonDesc), New SqlParameter("@ShelfLife", ""))
                    Else
                        connectSql.RunSpTransaction(trans, "sp_tspl_Customer_Category_Master_update", New SqlParameter("@CustCategoryCode", strCustCode), New SqlParameter("@CustCategoryDesc", strCustDesc), New SqlParameter("@PriceCode", strPCode), New SqlParameter("@PriceCodeDesc", strRouteDesc), New SqlParameter("@RouteId", strRouteId), New SqlParameter("@RouteDesc", strRouteDesc), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", Datee), New SqlParameter("@ModifiedBy", userCode), New SqlParameter("@ModifiedDate", Datee), New SqlParameter("@CompCode", companyCode), New SqlParameter("@PriceCodeNon", strPriceCodeNon), New SqlParameter("@PriceCodeDescNon", strPriceCodeNonDesc), New SqlParameter("@ShelfLife", ""))
                    End If
                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                trans.Rollback()
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)

            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub MenuExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuExport.Click
        sql = "SELECT CUST_CATEGORY_CODE,CUST_CATEGORY_DESC ,Price_Code,Price_Code_Desc ,Route_No,Route_Desc,Price_CodeNon as [Price Code Non-Excise] ,Price_Code_DescNon as [Price Code Non-Excise Description] FROM TSPL_CUSTOMER_CATEGORY_MASTER "
        transportSql.ExporttoExcel(sql, Me)
    End Sub
#End Region
#Region "Finder Load"
    Private Sub fndPriceCode_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndPriceCode.ConnectionString = connectSql.SqlCon()
        'fndPriceCode.Query = "SELECT DISTINCT TSPL_ITEM_PRICE_MASTER.Price_Code as [Price Code], TSPL_PRICE_COMPONENT_MAPPING.Price_Code_Desc as [Price Code Description], TSPL_ITEM_PRICE_MASTER.Tax_group as [Tax Group] FROM TSPL_ITEM_PRICE_MASTER INNER JOIN TSPL_PRICE_COMPONENT_MAPPING ON TSPL_ITEM_PRICE_MASTER.Price_Code = TSPL_PRICE_COMPONENT_MAPPING.Price_Code INNER JOIN TSPL_TAX_GROUP_MASTER ON TSPL_ITEM_PRICE_MASTER.Tax_group = TSPL_TAX_GROUP_MASTER.Tax_Group_Code where TSPL_TAX_GROUP_MASTER.Excisable ='Y'"
        'fndPriceCode.ValueToSelect = "Price Code"
        'fndPriceCode.ValueToSelect1 = "Price Code Description"
        'fndPriceCode.Caption = "Price Code Details"
    End Sub
#End Region
#Region "Finder Leave Event"
    Private Sub fndPriceCode_Leave(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim s As String
        If fndPriceCode.Value <> "" Then
            'dr = connectSql.RunSqlReturnDR("select Price_Code from TSPL_PRICE_COMPONENT_MAPPING where Price_Code='" + fndPriceCode.Value + "'")
            'Dim s As String
            'While dr.Read()
            '    s = dr(0).ToString()
            'End While
            strSql = "select Price_Code from TSPL_PRICE_COMPONENT_MAPPING where Price_Code='" + fndPriceCode.Value + "'"
            s = clsDBFuncationality.getSingleValue(strSql)
            If s <> fndPriceCode.Value Then
                common.clsCommon.MyMessageBoxShow("Price Code doesn't exist")
                fndPriceCode.Value = ""
                txtPriceCodeDesc.Text = ""
                fndPriceCode.Focus()
            Else
            End If
        Else
            ' btnSave.Focus()
        End If
    End Sub
    Private Sub fndPriceCodeNon_leave(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim s As String
        If fndPriceCodeNon.Value <> "" Then
            'dr = connectSql.RunSqlReturnDR("select Price_Code from TSPL_PRICE_COMPONENT_MAPPING where Price_Code='" + fndPriceCodeNon.Value + "'")
            'Dim s As String
            'While dr.Read()
            '    s = dr(0).ToString()
            'End While
            strSql = "select Price_Code from TSPL_PRICE_COMPONENT_MAPPING where Price_Code='" + fndPriceCodeNon.Value + "'"
            s = clsDBFuncationality.getSingleValue(strSql)
            If s <> fndPriceCodeNon.Value Then
                common.clsCommon.MyMessageBoxShow("Price Code(Non-Excisable) doesn't exist")
                fndPriceCodeNon.Value = ""
                txtPriceCodeNon.Text = ""
                fndPriceCodeNon.Focus()
            Else
            End If
        Else

        End If
    End Sub
#End Region
#Region "Page Load"
    Private Sub frmCustomerCategory_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetDataBaseGrid()
        gvDB.AllowDeleteRow = False
        SetUserMgmtNew()

        ThemeResolutionService.ApplicationThemeName = "Office2010Blue"
        btnSave.Enabled = True
        btnDelete.Enabled = False
        TxtShfLife.Text = ""
        TxtShfLife.Visible = False  ''''Added By Pankaj Kumar Chaudhary
        LblShlfLife.Visible = False ''''Added By Pankaj Kumar Chaudhary
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New Trasnaction")
        fndRouteTextChanged()
        fndpricecodetextchanged()
        fndPriceCodeNonTextChanged()
        fndpricecodetextchanged()
        fndRouteTextChanged()
        fndPriceCodeNonTextChanged()
    End Sub

    Private Sub ValidateLength()
        fndCustomerId.MyMaxLength = 12
        txtCustomerDesc.MaxLength = 50
        TxtShfLife.MaxLength = 15
    End Sub
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.CustomeCategory)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 02/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            MenuImport.Enabled = True
            MenuExport.Enabled = True
        Else
            MenuImport.Enabled = False
            MenuExport.Enabled = False
        End If
        '--------------------------------------------------
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub
#End Region


    Private Sub fndRoute_Leave(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim s As String
        If fndRoute.Value <> "" Then
            'dr = connectSql.RunSqlReturnDR("select Route_No from TSPL_ROUTE_MASTER where Route_No='" + fndRoute.Value + "'")
            'Dim s As String
            'While dr.Read()
            '    s = dr(0).ToString()
            'End While
            strSql = "select Route_No from TSPL_ROUTE_MASTER where Route_No='" + fndRoute.Value + "'"
            s = clsDBFuncationality.getSingleValue(strSql)

            If s <> fndRoute.Value Then
                common.clsCommon.MyMessageBoxShow("Route Id doesn't exist")
                fndRoute.Value = ""
                txtRouteDesc.Text = ""
                fndRoute.Focus()
            Else
            End If
        Else
            'btnSave.Focus()
        End If
    End Sub

    Private Function GetReplecateCompaniesDataBase() As List(Of String)
        Dim arrDBName As New List(Of String)
        arrDBName.Add(objCommonVar.CurrDatabase)
        For ii As Integer = 0 To gvDB.Rows.Count - 1
            If (clsCommon.myCBool(gvDB.Rows(ii).Cells(colSelect).Value)) Then
                arrDBName.Add(clsCommon.myCstr(gvDB.Rows(ii).Cells(colDataBaseName).Value))
            End If
        Next
        Return arrDBName
    End Function

    Sub SetDataBaseGrid()
        gvDB.Rows.Clear()
        gvDB.Columns.Clear()

        Dim repoSelect As GridViewCheckBoxColumn = New GridViewCheckBoxColumn()
        repoSelect.FormatString = ""
        repoSelect.HeaderText = "Select"
        repoSelect.Name = colSelect
        repoSelect.Width = 50
        repoSelect.ReadOnly = False
        repoSelect.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
        gvDB.MasterTemplate.Columns.Add(repoSelect)

        Dim repoCompCode As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoCompCode.FormatString = ""
        repoCompCode.HeaderText = "Company Code"
        repoCompCode.Name = colCompCode
        repoCompCode.Width = 150
        repoCompCode.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoCompCode)

        Dim repoCompName As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoCompName.FormatString = ""
        repoCompName.HeaderText = "Company Name"
        repoCompName.Name = colCompName
        repoCompName.Width = 150
        repoCompName.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoCompName)

        Dim repoDB As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoDB.FormatString = ""
        repoDB.HeaderText = "Database Name"
        repoDB.Name = colDataBaseName
        repoDB.IsVisible = False
        repoDB.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoDB)

        Dim qry As String = "SELECT Comp_Code,Comp_Name,DataBase_Name from TSPL_COMPANY_MASTER where len(isnull(DataBase_Name,''))>0 and Comp_Code not in ('" + objCommonVar.CurrentCompanyCode + "')"
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            For Each dr As DataRow In dt.Rows
                gvDB.Rows.AddNew()
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colSelect).Value = False
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colCompCode).Value = clsCommon.myCstr(dr("Comp_Code"))
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colCompName).Value = clsCommon.myCstr(dr("Comp_Name"))
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colDataBaseName).Value = clsCommon.myCstr(dr("DataBase_Name"))
            Next
        End If
    End Sub
    Private Sub Finder1_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndPriceCodeNon.ConnectionString = connectSql.SqlCon()
        'fndPriceCodeNon.Query = "SELECT DISTINCT TSPL_ITEM_PRICE_MASTER.Price_Code as [Price Code], TSPL_PRICE_COMPONENT_MAPPING.Price_Code_Desc as [Price Code Description], TSPL_ITEM_PRICE_MASTER.Tax_group as [Tax Group] FROM TSPL_ITEM_PRICE_MASTER INNER JOIN TSPL_PRICE_COMPONENT_MAPPING ON TSPL_ITEM_PRICE_MASTER.Price_Code = TSPL_PRICE_COMPONENT_MAPPING.Price_Code INNER JOIN TSPL_TAX_GROUP_MASTER ON TSPL_ITEM_PRICE_MASTER.Tax_group = TSPL_TAX_GROUP_MASTER.Tax_Group_Code where TSPL_TAX_GROUP_MASTER.Excisable ='N'"
        'fndPriceCodeNon.ValueToSelect = "Price Code"
        'fndPriceCodeNon.ValueToSelect1 = "Price Code Description"
        'fndPriceCodeNon.Caption = "Price Code Details"
    End Sub

    Private Sub frmCustomerCategory_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            'PostData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funreset()
        End If
    End Sub

    
    Private Sub fndRoute__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndRoute._MYValidating
        Dim qry As String = "select Route_No as [RouteID],Route_Desc as [Route Description]from TSPL_ROUTE_MASTER "
        fndRoute.Value = clsCommon.ShowSelectForm("fndrou", qry, "RouteID", "Status='A'", fndRoute.Value, "Route_No", isButtonClicked)
        txtRouteDesc.Text = clsDBFuncationality.getSingleValue("select Route_Desc  from TSPL_ROUTE_MASTER where Route_No ='" + fndRoute.Value + "' ")
        fndRouteTextChanged()

    End Sub

    Private Sub fndPriceCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndPriceCode._MYValidating
        Dim qry As String = "SELECT DISTINCT TSPL_ITEM_PRICE_MASTER.Price_Code as Code, TSPL_PRICE_COMPONENT_MAPPING.Price_Code_Desc as [Price Code Description], TSPL_ITEM_PRICE_MASTER.Tax_group as [Tax Group] FROM TSPL_ITEM_PRICE_MASTER INNER JOIN TSPL_PRICE_COMPONENT_MAPPING ON TSPL_ITEM_PRICE_MASTER.Price_Code = TSPL_PRICE_COMPONENT_MAPPING.Price_Code INNER JOIN TSPL_TAX_GROUP_MASTER ON TSPL_ITEM_PRICE_MASTER.Tax_group = TSPL_TAX_GROUP_MASTER.Tax_Group_Code "
        If objCommonVar.GSTApplicable Then
            fndPriceCode.Value = clsCommon.ShowSelectForm("PRICECODECODEFND", qry, "Code", "", fndPriceCode.Value, "", isButtonClicked)
        Else
            fndPriceCode.Value = clsCommon.ShowSelectForm("PRICECODECODEFND", qry, "Code", "TSPL_TAX_GROUP_MASTER.Excisable ='Y'", fndPriceCode.Value, "", isButtonClicked)
        End If
        txtPriceCodeDesc.Text = clsDBFuncationality.getSingleValue("SELECT TSPL_PRICE_COMPONENT_MAPPING.Price_Code_Desc  FROM TSPL_ITEM_PRICE_MASTER INNER JOIN TSPL_PRICE_COMPONENT_MAPPING ON TSPL_ITEM_PRICE_MASTER.Price_Code = TSPL_PRICE_COMPONENT_MAPPING.Price_Code INNER JOIN TSPL_TAX_GROUP_MASTER ON TSPL_ITEM_PRICE_MASTER.Tax_group = TSPL_TAX_GROUP_MASTER.Tax_Group_Code where  TSPL_ITEM_PRICE_MASTER.Price_Code='" + fndPriceCode.Value + "' ")
        fndpricecodetextchanged()
    End Sub

  
    Private Sub fndPriceCodeNon__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndPriceCodeNon._MYValidating
        Dim qry As String = "SELECT DISTINCT TSPL_ITEM_PRICE_MASTER.Price_Code as [PriceCode], TSPL_PRICE_COMPONENT_MAPPING.Price_Code_Desc as [Price Code Description], TSPL_ITEM_PRICE_MASTER.Tax_group as [Tax Group] FROM TSPL_ITEM_PRICE_MASTER INNER JOIN TSPL_PRICE_COMPONENT_MAPPING ON TSPL_ITEM_PRICE_MASTER.Price_Code = TSPL_PRICE_COMPONENT_MAPPING.Price_Code INNER JOIN TSPL_TAX_GROUP_MASTER ON TSPL_ITEM_PRICE_MASTER.Tax_group = TSPL_TAX_GROUP_MASTER.Tax_Group_Code "
        If objCommonVar.GSTApplicable Then
            fndPriceCodeNon.Value = clsCommon.ShowSelectForm("REPORTNONFND", qry, "PriceCode", "", fndPriceCodeNon.Value, "", isButtonClicked)
        Else
            fndPriceCodeNon.Value = clsCommon.ShowSelectForm("REPORTNONFND", qry, "PriceCode", "TSPL_TAX_GROUP_MASTER.Excisable ='N'", fndPriceCodeNon.Value, "", isButtonClicked)
        End If
        txtPriceCodeNon.Text = clsDBFuncationality.getSingleValue("SELECT TSPL_PRICE_COMPONENT_MAPPING.Price_Code_Desc  FROM TSPL_ITEM_PRICE_MASTER INNER JOIN TSPL_PRICE_COMPONENT_MAPPING ON TSPL_ITEM_PRICE_MASTER.Price_Code = TSPL_PRICE_COMPONENT_MAPPING.Price_Code INNER JOIN TSPL_TAX_GROUP_MASTER ON TSPL_ITEM_PRICE_MASTER.Tax_group = TSPL_TAX_GROUP_MASTER.Tax_Group_Code  where TSPL_ITEM_PRICE_MASTER.Price_Code ='" + fndPriceCodeNon.Value + "' ")
        fndPriceCodeNonTextChanged()
    End Sub

    Private Sub grpCustomerCategory_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles grpCustomerCategory.Click

    End Sub

    Private Sub fndCustomerId__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndCustomerId._MYNavigator
        Dim qst As String = "select Cust_Category_Code as [Customer Category Code],Cust_Category_Desc as [Customer Code Description] from tspl_Customer_Category_Master where 2=2  "
        Select Case NavType
            Case NavigatorType.Current
                qst += " and tspl_Customer_Category_Master .Cust_Category_Code in ('" + fndCustomerId.Value + "')"
            Case NavigatorType.Next
                qst += " and tspl_Customer_Category_Master .Cust_Category_Code in (select min(Cust_Category_Code ) from tspl_Customer_Category_Master where tspl_Customer_Category_Master.Cust_Category_Code   >'" + fndCustomerId.Value + "')"
            Case NavigatorType.First
                qst += " and tspl_Customer_Category_Master .Cust_Category_Code in (select MIN(Cust_Category_Code ) from tspl_Customer_Category_Master)"

            Case NavigatorType.Last
                qst += " and tspl_Customer_Category_Master .Cust_Category_Code in (select Max(Cust_Category_Code ) from tspl_Customer_Category_Master)"
            Case NavigatorType.Previous
                qst += " and tspl_Customer_Category_Master .Cust_Category_Code in (select Max(Cust_Category_Code ) from tspl_Customer_Category_Master where tspl_Customer_Category_Master.Cust_Category_Code   <'" + fndCustomerId.Value + "')"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            fndCustomerId.Value = clsCommon.myCstr(dt.Rows(0)("Customer Category Code"))
            txtCustomerDesc.Text = clsCommon.myCstr(dt.Rows(0)("Customer Code Description"))
        End If
        LoadData()
    End Sub

    Private Sub fndCustomerId__MYValidating_1(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndCustomerId._MYValidating
        Dim str As String = "select count(*) from tspl_Customer_Category_Master   where  Cust_Category_Code ='" + fndCustomerId.Value + "' "

        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))

        If no = 0 Then
            fndCustomerId.MyReadOnly = False
        Else
            fndCustomerId.MyReadOnly = True
        End If

        If fndCustomerId.MyReadOnly OrElse isButtonClicked Then
            'Dim qry As String = "select Cust_Category_Code as [CustomerCategoryCode],Cust_Category_Desc as [Customer Code Description] from tspl_Customer_Category_Master  "
            'fndCustomerId.Value = clsCommon.ShowSelectForm("CUSTCATEGRYFND", qry, "CustomerCategoryCode", "", fndCustomerId.Value, "Cust_Category_Code", isButtonClicked)
            fndCustomerId.Value = clsCustomerCategory.getFinder("", fndCustomerId.Value, isButtonClicked)
            txtCustomerDesc.Text = clsDBFuncationality.getSingleValue("select Cust_Category_Desc  from tspl_Customer_Category_Master  where Cust_Category_Code='" + fndCustomerId.Value + "'")
            LoadData()
        End If
    End Sub

    Private Sub txtPriceCodeNon_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles txtPriceCodeNon.TextChanged

    End Sub
End Class
