'Developed By -BibhuPrasad Parida
'Database - TSPLERP
'Table - TSPL_EXCISABLE_PROFILE
'Start Date -27-06-2011 3.30PM
'End Date -
'' Code Added By Abhishek as on 19/10/2012 11:29 am  For Check If Exist SettlementCode in TSPL_TRANSFER_HEAD,TSPL_SHIPMENT_MASTER then Don't Delete
'--preeti gupta-ticket no.[BM00000003133]
''updation by richa agarwal againt ticket no BM00000004424

Imports System.Data
Imports XpertERPEngine
Imports System.Data.SqlClient
Imports System.Configuration
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports System.Text.RegularExpressions
Imports System.Globalization

Imports common

'' updation by richa agarwal on 30/10/2014 change route master code to sales man code in finder and in import/export
Public Class FrmSalesManHierarchy
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()

#Region "Constructor"
    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub
#End Region
#Region "Variables"
    Dim userCode, companyCode As String
    Dim sql As String
    Dim ds As DataSet
    Dim dr As DataTable

    Dim objstr As String = "Tecxpert Software Pvt Ltd."

    Const colSelect As String = "SELECT"
    Const colCompCode As String = "COMPCODE"
    Const colCompName As String = "COMPNAME"
    Const colDataBaseName As String = "DATABASE"
    ' Dim dt1 As Date = Date.Today
    ' Dim dt As Date = connectSql.serverDate()
    ' Dim realDate As Date = Date.ParseExact(dt, "mm/dd/yyyy", culture)
#End Region


    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        SaveData()
    End Sub
    Sub SaveData()
        Dim ddltype As String = ddlUserType.Text
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso fndSalesmancode.Value = "" Then
           myMessages.blankValue("Route Code")
            fndSalesmancode.Focus()
        Else
            If btnSave.Text = "Save" Then
                funInsert()
            Else
                funUpdate()
            End If
        End If

    End Sub
    Private Sub funInsert()
        'Dim strcomrate As Decimal
        'If txtCommissionRate.Text = "" Then
        '    strcomrate = 0.0
        'Else
        '    strcomrate = txtCommissionRate.Text
        'End If
        'Dim str As String = ddlUserType.Text
        'Try
        '    If str = "----Select----" Then

        '        connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode))
        '        myMessages.insert()
        '        btnSave.Text = "Update"
        '        btnDelete.Enabled = True
        '    End If
        '    If str = "HOS" Then
        '        Try
        '            connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode))
        '            myMessages.insert()
        '            btnSave.Text = "Update"
        '            btnDelete.Enabled = True
        '        Catch ex As Exception
        '            myMessages.myExceptions(ex.Message.ToString())
        '        End Try
        '    End If

        '    If str = "TDM" Then
        '        If fndLevel1.txtValue.Text = "" Then
        '            common.clsCommon.MyMessageBoxShow("HOS cannot be blank.")
        '        Else
        '            Try
        '                connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode))
        '                myMessages.insert()
        '                btnSave.Text = "Update"
        '                btnDelete.Enabled = True
        '            Catch ex As Exception
        '                myMessages.myExceptions(ex.Message.ToString())
        '            End Try
        '        End If

        '    ElseIf str = "ADC" Then
        '        If fndLevel1.txtValue.Text = "" Then
        '            common.clsCommon.MyMessageBoxShow("HOS cannot be blank.")
        '        ElseIf fndLevel2.txtValue.Text = "" Then
        '            common.clsCommon.MyMessageBoxShow("TDM cannot be blank.")
        '        Else
        '            Try
        '                connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode))
        '                myMessages.insert()
        '                btnSave.Text = "Update"
        '                btnDelete.Enabled = True
        '            Catch ex As Exception
        '                myMessages.myExceptions(ex.Message.ToString())
        '            End Try
        '        End If
        '    ElseIf str = "CE" Then
        '        If fndLevel1.txtValue.Text = "" Then
        '            common.clsCommon.MyMessageBoxShow("HOS cannot be blank.")
        '        ElseIf fndLevel2.txtValue.Text = "" Then
        '            common.clsCommon.MyMessageBoxShow("TDM cannot be blank.")
        '        ElseIf fndLevel3.txtValue.Text = "" Then
        '            common.clsCommon.MyMessageBoxShow("ADC cannot be blank.")
        '        Else
        '            Try
        '                connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode))
        '                myMessages.insert()
        '                btnSave.Text = "Update"
        '                btnDelete.Enabled = True
        '                btnDelete.Enabled = True
        '            Catch ex As Exception
        '                myMessages.myExceptions(ex.Message.ToString())
        '            End Try
        '        End If
        '    ElseIf str = "RA" Then
        '        If fndLevel1.txtValue.Text = "" Then
        '            common.clsCommon.MyMessageBoxShow("HOS cannot be blank.")
        '        ElseIf fndLevel2.txtValue.Text = "" Then
        '            common.clsCommon.MyMessageBoxShow("TDM cannot be blank.")
        '        ElseIf fndLevel3.txtValue.Text = "" Then
        '            common.clsCommon.MyMessageBoxShow("ADC cannot be blank.")
        '        ElseIf fndLevel4.txtValue.Text = "" Then
        '            common.clsCommon.MyMessageBoxShow("CE cannot be blank.")
        '        Else
        '            Try
        '                connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode))
        '                myMessages.insert()
        '                btnSave.Text = "Update"
        '                btnDelete.Enabled = True
        '                btnDelete.Enabled = True


        '            Catch ex As Exception
        '                myMessages.myExceptions(ex.Message.ToString())


        '            End Try
        '        End If
        '    End If



        '    connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode))
        '    myMessages.insert()
        '    btnSave.Text = "Update"
        '    btnDelete.Enabled = True
        Dim strcomrate As Decimal
        If txtCommissionRate.Text = "" Then
            strcomrate = 0.0
        Else
            strcomrate = txtCommissionRate.Text
        End If
        Try

            If ddlUserType.Text = "----Select----" Then
                ddlUserType.Text = ""
            End If
            If fndLevel1.txtValue.Text = "" And fndLevel1.Enabled = True Then
                common.clsCommon.MyMessageBoxShow("HOS cannot be blank.")
                fndLevel1.Focus()
            ElseIf fndLevel2.txtValue.Text = "" And fndLevel2.Enabled = True Then
                common.clsCommon.MyMessageBoxShow("TDM cannot be blank.")
                fndLevel2.Focus()
            ElseIf fndLevel3.txtValue.Text = "" And fndLevel3.Enabled = True Then
                common.clsCommon.MyMessageBoxShow("ADC cannot be blank.")
                fndLevel3.Focus()
            ElseIf fndLevel4.txtValue.Text = "" And fndLevel4.Enabled = True Then
                common.clsCommon.MyMessageBoxShow("CE cannot be blank.")
                fndLevel4.Focus()
            Else
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_SALESMAN_MAPPING where Salesman_Code='" & fndSalesmancode.Value & "'")
                    If ChkNewEntry = 0 Then
                        fndSalesmancode.Value = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.SalesManHierarchy, "", "")
                        If clsCommon.myLen(fndSalesmancode.Value) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsDBFuncationality.UpdateInSelectedDatabase(GetReplecateCompaniesDataBase(), "sp_TSPL_SALESMAN_MAPPING_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode), New SqlParameter("@L1SDate", SDateL1.Value), New SqlParameter("@L2SDate", SDateL2.Value), New SqlParameter("@L3SDate", SDateL3.Value), New SqlParameter("@L4SDate", SDateL4.Value))
                myMessages.insert()
                btnSave.Text = "Update"
                btnDelete.Enabled = True
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub funUpdate()
        Dim strcomrate As Decimal
        If txtCommissionRate.Text = "" Then
            strcomrate = 0.0
        Else
            strcomrate = txtCommissionRate.Text
        End If
        Try

            Dim strqry As String = "select  Salesman_Name,Commission_Rate,TYPE,Level1_Code,Level2_Code,Level3_Code,Level4_Code ,convert(varchar(10),L1SDate,103) as L1SDate ,convert(varchar(10),L2SDate,103) as L2SDate ,convert(varchar(10),L3SDate,103) as L3SDate,convert(varchar(10),L4SDate,103) as L4SDate from TSPL_SALESMAN_MAPPING where Salesman_Code='" + fndSalesmancode.Value + "'"
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(strqry)

            'If dt.Rows(0) Is Nothing Then
            '    common.clsCommon.MyMessageBoxShow("You Cannot Change the Value of Route Code")
            '    Return
            'End If


            If ddlUserType.Text = "----Select----" Then
                ddlUserType.Text = ""
            End If
            If fndLevel1.txtValue.Text = "" And fndLevel1.Enabled = True Then
                common.clsCommon.MyMessageBoxShow("HOS cannot be blank.")
                fndLevel1.Focus()
            ElseIf fndLevel2.txtValue.Text = "" And fndLevel2.Enabled = True Then
                common.clsCommon.MyMessageBoxShow("TDM cannot be blank.")
                fndLevel2.Focus()
            ElseIf fndLevel3.txtValue.Text = "" And fndLevel3.Enabled = True Then
                common.clsCommon.MyMessageBoxShow("ADC cannot be blank.")
                fndLevel3.Focus()
            ElseIf fndLevel4.txtValue.Text = "" And fndLevel4.Enabled = True Then
                common.clsCommon.MyMessageBoxShow("CE cannot be blank.")
                fndLevel4.Focus()
            Else
                'clsDBFuncationality.UpdateInSelectedDatabase(GetReplecateCompaniesDataBase(), "sp_TSPL_SALESMAN_MAPPING_update", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode), New SqlParameter("@L1SDate", SDateL1.Value), New SqlParameter("@L2SDate", SDateL2.Value), New SqlParameter("@L3SDate", SDateL3.Value), New SqlParameter("@L4SDate", SDateL4.Value))

                ''If dt.Rows(0)("Salesman_Name").ToString() = txtSalesmanName.Text And dt.Rows(0)("Level1_Code").ToString = fndLevel1.txtValue.Text And dt.Rows(0)("Level2_Code").ToString = fndLevel2.txtValue.Text And dt.Rows(0)("Level3_Code").ToString = fndLevel3.txtValue.Text And dt.Rows(0)("Level4_Code").ToString = fndLevel4.txtValue.Text And dt.Rows(0)("L1SDate") = clsCommon.GetPrintDate((SDateL1.Value), "dd/MM/yyyy") And dt.Rows(0)("L2SDate") = clsCommon.GetPrintDate((SDateL2.Value), "dd/MM/yyyy") And dt.Rows(0)("L3SDate") = clsCommon.GetPrintDate((SDateL3.Value), "dd/MM/yyyy") And dt.Rows(0)("L4SDate") = clsCommon.GetPrintDate((SDateL4.Value), "dd/MM/yyyy") Then
                ''Else
                ''    Dim L1ED As Date? = Nothing
                ''    Dim L2ED As Date? = Nothing
                ''    Dim L3ED As Date? = Nothing
                ''    Dim L4ED As Date? = Nothing
                ''    Dim L1SD As Date = dt.Rows(0)("L1SDate")
                ''    Dim L2SD As Date = dt.Rows(0)("L2SDate")
                ''    Dim L3SD As Date = dt.Rows(0)("L3SDate")
                ''    Dim L4SD As Date = dt.Rows(0)("L4SDate")

                ''    If dt.Rows(0)("L1SDate") = clsCommon.GetPrintDate((SDateL1.Value), "dd/MM/yyyy") Then

                ''        If dt.Rows(0)("Level1_Code").ToString <> fndLevel1.txtValue.Text Then
                ''            L1ED = clsCommon.myCDate(clsCommon.GETSERVERDATE)
                ''        End If

                ''    Else

                ''        If dt.Rows(0)("Level1_Code").ToString = fndLevel1.txtValue.Text Then
                ''            L1ED = clsCommon.myCDate(SDateL1.Value).AddDays(-1)
                ''        Else
                ''            L1ED = clsCommon.myCDate(clsCommon.GETSERVERDATE)
                ''        End If

                ''    End If

                ''    If dt.Rows(0)("L2SDate") = clsCommon.GetPrintDate((SDateL2.Value), "dd/MM/yyyy") Then
                ''        If dt.Rows(0)("Level2_Code").ToString <> fndLevel2.txtValue.Text Then
                ''            L2ED = clsCommon.myCDate(clsCommon.GETSERVERDATE)
                ''        End If
                ''    Else
                ''        If dt.Rows(0)("Level2_Code").ToString = fndLevel2.txtValue.Text Then
                ''            L2ED = clsCommon.myCDate(SDateL2.Value).AddDays(-1)
                ''        Else
                ''            L2ED = clsCommon.myCDate(clsCommon.GETSERVERDATE)
                ''        End If

                ''    End If

                ''    If dt.Rows(0)("L3SDate") = clsCommon.GetPrintDate((SDateL3.Value), "dd/MM/yyyy") Then

                ''        If dt.Rows(0)("Level3_Code").ToString <> fndLevel3.txtValue.Text Then
                ''            L3ED = clsCommon.myCDate(clsCommon.GETSERVERDATE)
                ''        End If
                ''    Else
                ''        If dt.Rows(0)("Level3_Code").ToString = fndLevel3.txtValue.Text Then
                ''            L3ED = clsCommon.myCDate(SDateL3.Value).AddDays(-1)
                ''        Else
                ''            L3ED = clsCommon.myCDate(clsCommon.GETSERVERDATE)
                ''        End If
                ''        'L3ED = clsCommon.myCDate(SDateL3.Value).AddDays(-1)
                ''    End If

                ''    If dt.Rows(0)("L4SDate") = clsCommon.GetPrintDate((SDateL4.Value), "dd/MM/yyyy") Then

                ''        If dt.Rows(0)("Level4_Code").ToString <> fndLevel4.txtValue.Text Then
                ''            L4ED = clsCommon.myCDate(clsCommon.GETSERVERDATE)
                ''        End If
                ''    Else
                ''        If dt.Rows(0)("Level4_Code").ToString = fndLevel4.txtValue.Text Then
                ''            L4ED = clsCommon.myCDate(SDateL4.Value).AddDays(-1)
                ''        Else
                ''            L4ED = clsCommon.myCDate(clsCommon.GETSERVERDATE)
                ''        End If

                ''        'L4ED = clsCommon.myCDate(SDateL4.Value).AddDays(-1)
                ''    End If


                ''    'Dim qry As String = "insert into TSPL_SALESMAN_MAPPING_HISTORY (Salesman_Code,Salesman_Name,Level1_Code,Level2_Code,Level3_Code,Level4_Code,Created_By,Created_Date,Comp_Code,L1SDate,L1EDate,L2SDate,L2EDate,L3SDate,L3EDate,L4SDate,L4EDate) values('" + fndSalesmancode.Value+ "','" + txtSalesmanName.Text + "','" + fndLevel1.txtValue.Text + "','" + fndLevel2.txtValue.Text + "','" + fndLevel3.txtValue.Text + "','" + fndLevel4.txtValue.Text + "','" + userCode + "','" + connectSql.serverDate() + "','" + companyCode + "','" + SDateL1.Value + "'," + L1ED + ",'" + SDateL2.Value + "'," + L2ED + ",'" + SDateL3.Value + "'," + L3ED + ",'" + SDateL4.Value + "'," + L4ED + ") "
                ''    'clsDBFuncationality.ExecuteNonQuery(qry)
                ''    ' clsDBFuncationality.UpdateInSelectedDatabase(GetReplecateCompaniesDataBase(), "sp_TSPL_SALESMAN_MAPPING_update", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode), New SqlParameter("@L1SDate", SDateL1.Value), New SqlParameter("@L2SDate", SDateL2.Value), New SqlParameter("@L3SDate", SDateL3.Value), New SqlParameter("@L4SDate", SDateL4.Value))

                ''    'connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_HISTORY_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode), New SqlParameter("@L1SDate", SDateL1.Value), New SqlParameter("@L2SDate", SDateL2.Value), New SqlParameter("@L3SDate", SDateL3.Value), New SqlParameter("@L4SDate", SDateL4.Value), New SqlParameter("@L1EDate", L1ED), New SqlParameter("@L2EDate", L2ED), New SqlParameter("@L3EDate", L3ED), New SqlParameter("@L4EDate", L4ED))

                ''    'connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_HISTORY_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode), New SqlParameter("@L1SDate", clsCommon.GetPrintDate((dt.Rows(0)("L1SDate")), "dd/MM/yyyy")), New SqlParameter("@L2SDate", clsCommon.GetPrintDate((dt.Rows(0)("L2SDate")), "dd/MM/yyyy")), New SqlParameter("@L3SDate", clsCommon.GetPrintDate((dt.Rows(0)("L3SDate")), "dd/MM/yyyy")), New SqlParameter("@L4SDate", clsCommon.GetPrintDate((dt.Rows(0)("L4SDate")), "dd/MM/yyyy")), New SqlParameter("@L1EDate", L1ED), New SqlParameter("@L2EDate", L2ED), New SqlParameter("@L3EDate", L3ED), New SqlParameter("@L4EDate", L4ED))

                ''    connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_HISTORY_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", dt.Rows(0)("Salesman_Name").ToString()), New SqlParameter("@Level1", dt.Rows(0)("Level1_Code").ToString), New SqlParameter("@Level2", dt.Rows(0)("Level2_Code").ToString), New SqlParameter("@Level3", dt.Rows(0)("Level3_Code").ToString), New SqlParameter("@Level4", dt.Rows(0)("Level4_Code").ToString), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode), New SqlParameter("@L1SDate", L1SD), New SqlParameter("@L2SDate", L2SD), New SqlParameter("@L3SDate", L3SD), New SqlParameter("@L4SDate", L4SD), New SqlParameter("@L1EDate", L1ED), New SqlParameter("@L2EDate", L2ED), New SqlParameter("@L3EDate", L3ED), New SqlParameter("@L4EDate", L4ED))
                ''End If

              
                If dt.Rows(0)("Salesman_Name").ToString() = txtSalesmanName.Text And dt.Rows(0)("Level1_Code").ToString = fndLevel1.txtValue.Text And dt.Rows(0)("Level2_Code").ToString = fndLevel2.txtValue.Text And dt.Rows(0)("Level3_Code").ToString = fndLevel3.txtValue.Text And dt.Rows(0)("Level4_Code").ToString = fndLevel4.txtValue.Text And dt.Rows(0)("L1SDate") = clsCommon.GetPrintDate((SDateL1.Value), "dd/MM/yyyy") And dt.Rows(0)("L2SDate") = clsCommon.GetPrintDate((SDateL2.Value), "dd/MM/yyyy") And dt.Rows(0)("L3SDate") = clsCommon.GetPrintDate((SDateL3.Value), "dd/MM/yyyy") And dt.Rows(0)("L4SDate") = clsCommon.GetPrintDate((SDateL4.Value), "dd/MM/yyyy") Then
                Else
                    Dim L1ED As Date? = Nothing
                    Dim L2ED As Date? = Nothing
                    Dim L3ED As Date? = Nothing
                    Dim L4ED As Date? = Nothing
                    Dim L1SD As Date = dt.Rows(0)("L1SDate")
                    Dim L2SD As Date = dt.Rows(0)("L2SDate")
                    Dim L3SD As Date = dt.Rows(0)("L3SDate")
                    Dim L4SD As Date = dt.Rows(0)("L4SDate")


                    If dt.Rows(0)("L1SDate") <> clsCommon.GetPrintDate((SDateL1.Value), "dd/MM/yyyy") And dt.Rows(0)("Level1_Code").ToString <> fndLevel1.txtValue.Text Then
                        L1ED = clsCommon.myCDate(SDateL1.Value).AddDays(-1)
                    ElseIf dt.Rows(0)("L1SDate") = clsCommon.GetPrintDate((SDateL1.Value), "dd/MM/yyyy") And dt.Rows(0)("Level1_Code").ToString = fndLevel1.txtValue.Text Then
                    Else
                        common.clsCommon.MyMessageBoxShow("Change the value for HOS and StartDate")

                        Exit Sub
                    End If


                    If dt.Rows(0)("L2SDate") <> clsCommon.GetPrintDate((SDateL2.Value), "dd/MM/yyyy") And dt.Rows(0)("Level2_Code").ToString <> fndLevel2.txtValue.Text Then
                        L2ED = clsCommon.myCDate(SDateL2.Value).AddDays(-1)
                    ElseIf dt.Rows(0)("L2SDate") = clsCommon.GetPrintDate((SDateL2.Value), "dd/MM/yyyy") And dt.Rows(0)("Level2_Code").ToString = fndLevel2.txtValue.Text Then
                    Else
                        common.clsCommon.MyMessageBoxShow("Change the value for both TDM and StartDate")
                        Exit Sub
                    End If

                    If dt.Rows(0)("L3SDate") <> clsCommon.GetPrintDate((SDateL3.Value), "dd/MM/yyyy") And dt.Rows(0)("Level3_Code").ToString <> fndLevel3.txtValue.Text Then
                        L3ED = clsCommon.myCDate(SDateL3.Value).AddDays(-1)
                    ElseIf dt.Rows(0)("L3SDate") = clsCommon.GetPrintDate((SDateL3.Value), "dd/MM/yyyy") And dt.Rows(0)("Level3_Code").ToString = fndLevel3.txtValue.Text Then
                    Else
                        common.clsCommon.MyMessageBoxShow("Change the value for both ADC and StartDate")
                        Exit Sub
                    End If


                    If dt.Rows(0)("L4SDate") <> clsCommon.GetPrintDate((SDateL4.Value), "dd/MM/yyyy") And dt.Rows(0)("Level4_Code").ToString <> fndLevel4.txtValue.Text Then
                        L4ED = clsCommon.myCDate(SDateL4.Value).AddDays(-1)
                    ElseIf dt.Rows(0)("L4SDate") = clsCommon.GetPrintDate((SDateL4.Value), "dd/MM/yyyy") And dt.Rows(0)("Level4_Code").ToString = fndLevel4.txtValue.Text Then
                    Else
                        common.clsCommon.MyMessageBoxShow("Change the value for both CE and StartDate")
                        Exit Sub
                    End If
                    connectSql.RunSp("sp_TSPL_SALESMAN_MAPPING_HISTORY_insert", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", dt.Rows(0)("Salesman_Name").ToString()), New SqlParameter("@Level1", dt.Rows(0)("Level1_Code").ToString), New SqlParameter("@Level2", dt.Rows(0)("Level2_Code").ToString), New SqlParameter("@Level3", dt.Rows(0)("Level3_Code").ToString), New SqlParameter("@Level4", dt.Rows(0)("Level4_Code").ToString), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode), New SqlParameter("@L1SDate", L1SD), New SqlParameter("@L2SDate", L2SD), New SqlParameter("@L3SDate", L3SD), New SqlParameter("@L4SDate", L4SD), New SqlParameter("@L1EDate", L1ED), New SqlParameter("@L2EDate", L2ED), New SqlParameter("@L3EDate", L3ED), New SqlParameter("@L4EDate", L4ED))
                End If




                clsDBFuncationality.UpdateInSelectedDatabase(GetReplecateCompaniesDataBase(), "sp_TSPL_SALESMAN_MAPPING_update", New SqlParameter("@SalesManCode", fndSalesmancode.Value), New SqlParameter("@SalesmanName", txtSalesmanName.Text), New SqlParameter("@CommissionRate", strcomrate), New SqlParameter("@UserType", ddlUserType.Text), New SqlParameter("@Level1", fndLevel1.txtValue.Text), New SqlParameter("@Level2", fndLevel2.txtValue.Text), New SqlParameter("@Level3", fndLevel3.txtValue.Text), New SqlParameter("@Level4", fndLevel4.txtValue.Text), New SqlParameter("@Createdby", userCode), New SqlParameter("@Createddate", connectSql.serverDate()), New SqlParameter("@Modifiedby", userCode), New SqlParameter("@Modifieddate", connectSql.serverDate()), New SqlParameter("@CompCode", companyCode), New SqlParameter("@L1SDate", SDateL1.Value), New SqlParameter("@L2SDate", SDateL2.Value), New SqlParameter("@L3SDate", SDateL3.Value), New SqlParameter("@L4SDate", SDateL4.Value))
                myMessages.update()
            End If

        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub funDelete()
        Try
            clsDBFuncationality.UpdateInSelectedDatabase(GetReplecateCompaniesDataBase(), "sp_TSPL_SALESMAN_MAPPING_delete", New SqlParameter("@SalesManCode", fndSalesmancode.Value))
            myMessages.delete()
            btnSave.Text = "Save"
            btnDelete.Enabled = False
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Public Sub SetLength()
        fndSalesmancode.MyMaxLength = 12
        txtSalesmanName.MaxLength = 50

    End Sub
    Private Sub FrmSalesManHierarchy_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetLength()
        SetDataBaseGrid()
        SetUserMgmtNew()
        fndSalesmancode_TextChanged()
ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnnew, "Press Alt+N Adding New ")
       '  ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")

        'globalFunc.mandatoryText(fndSalesmancode.txtValue)
        'AddHandler fndSalesmancode.ValueChanged, AddressOf fndSalesmancode_TextChanged
        'AddHandler fndSalesmancode.txtValue.KeyPress, AddressOf fndSalesmancode_KeyPress
        AddHandler fndLevel1.txtValue.TextChanged, AddressOf fndLevel1_TextChanged
        AddHandler fndLevel2.txtValue.TextChanged, AddressOf fndLevel2_TextChanged
        AddHandler fndLevel3.txtValue.TextChanged, AddressOf fndLevel3_TextChanged
        AddHandler fndLevel4.txtValue.TextChanged, AddressOf fndLevel4_TextChanged



        AddHandler fndLevel1.txtValue.KeyPress, AddressOf fndLevel1_KeyPress
        AddHandler fndLevel2.txtValue.KeyPress, AddressOf fndLevel2_KeyPress
        AddHandler fndLevel3.txtValue.KeyPress, AddressOf fndLevel3_KeyPress
        AddHandler fndLevel4.txtValue.KeyPress, AddressOf fndLevel4_KeyPress
        'fndSalesmancode.txtValue.MaxLength = 12
        fndLevel1.txtValue.MaxLength = 12
        fndLevel2.txtValue.MaxLength = 12
        fndLevel3.txtValue.MaxLength = 12
        fndLevel4.txtValue.MaxLength = 12
        'fndSalesmancode.txtValue.CharacterCasing = CharacterCasing.Upper
        'fndSalesmancode.txtValue.CharacterCasing = CharacterCasing.Upper
        'fndSalesmancode.txtValue.CharacterCasing = CharacterCasing.Upper
        'fndSalesmancode.txtValue.CharacterCasing = CharacterCasing.Upper
        'fndSalesmancode.txtValue.CharacterCasing = CharacterCasing.Upper
        btnDelete.Enabled = False
        'fndLevel1.Enabled = False
        'fndLevel2.Enabled = False
        'fndLevel3.Enabled = False
        'fndLevel4.Enabled = False
        'txtlevel1.Enabled = False
        'txtlevel2.Enabled = False
        'txtlevel3.Enabled = False
        'txtlevel4.Enabled = False
        fndLevel1.Enabled = True
        fndLevel2.Enabled = True
        fndLevel3.Enabled = True
        fndLevel4.Enabled = True
        txtlevel1.Enabled = True
        txtlevel2.Enabled = True
        txtlevel3.Enabled = True
        txtlevel4.Enabled = True

        SDateL1.Value = clsCommon.GETSERVERDATE()
        SDateL2.Value = clsCommon.GETSERVERDATE()
        SDateL3.Value = clsCommon.GETSERVERDATE()
        SDateL4.Value = clsCommon.GETSERVERDATE()


        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If

    End Sub
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmSalesManHierarchy)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        btnSave.Visible = MyBase.isModifyFlag
        'btnPost.Visible = MyBase.isPostFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub fndLevel1_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'txtlevel1.Text = fndLevel1.txtValue.Tag
        Try
            'Dim strquery As String = "select Salesman_Code,Salesman_Name  from TSPL_SALESMAN_MAPPING where Type ='HOS' and Salesman_Code='" + fndLevel1.txtValue.Text + "'"
            Dim strquery As String = "select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master where emp_code='" + fndLevel1.txtValue.Text + "'"
            Dim dr As DataTable
            Dim strvalue As String = ""
            Dim txt As String = ""
            dr = clsDBFuncationality.GetDataTable(strquery)

            If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                strvalue = dr.Rows(0)(0).ToString()
                txt = dr.Rows(0)(1).ToString()
            End If

            If strvalue <> "" Then
                txtlevel1.Text = txt
            Else
                txtlevel1.Text = ""
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub fndLevel2_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'txtlevel2.Text = fndLevel2.txtValue.Tag
        Try
            'Dim strquery As String = "select Salesman_Code,Salesman_Name  from TSPL_SALESMAN_MAPPING where Type ='TDM' and Salesman_Code='" + fndLevel1.txtValue.Text + "'"
            Dim strquery As String = "select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master where emp_code='" + fndLevel2.txtValue.Text + "'"
            Dim dr As DataTable
            Dim strvalue As String = ""
            Dim txt As String = ""

            dr = clsDBFuncationality.GetDataTable(strquery)

            If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                strvalue = dr.Rows(0)(0).ToString()
                txt = dr.Rows(0)(1).ToString()
            End If
            If strvalue <> "" Then
                txtlevel2.Text = txt
            Else
                txtlevel2.Text = ""
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub fndLevel3_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'txtlevel3.Text = fndLevel3.txtValue.Tag
        Try
            'Dim strquery As String = "select Salesman_Code,Salesman_Name  from TSPL_SALESMAN_MAPPING where Type ='ADC' and Salesman_Code='" + fndLevel1.txtValue.Text + "'"
            Dim strquery As String = "select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master where emp_code='" + fndLevel3.txtValue.Text + "'"
            Dim dr As DataTable
            Dim strvalue As String = ""
            Dim txt As String = ""
            dr = clsDBFuncationality.GetDataTable(strquery)

            If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                strvalue = dr.Rows(0)(0).ToString()
                txt = dr.Rows(0)(1).ToString()
            End If

            If strvalue <> "" Then
                txtlevel3.Text = txt
            Else
                txtlevel3.Text = ""
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub fndLevel4_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'txtlevel4.Text = fndLevel4.txtValue.Tag
        Try
            'Dim strquery As String = "select Salesman_Code,Salesman_Name  from TSPL_SALESMAN_MAPPING where Type ='CE' and Salesman_Code='" + fndLevel1.txtValue.Text + "'"
            Dim strquery As String = "select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master where emp_code='" + fndLevel4.txtValue.Text + "'"
            Dim dr As DataTable
            Dim strvalue As String = ""
            Dim txt As String = ""
            dr = clsDBFuncationality.GetDataTable(strquery)

            If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                strvalue = dr.Rows(0)(0).ToString()
                txt = dr.Rows(0)(1).ToString()
            End If

            If strvalue <> "" Then
                txtlevel4.Text = txt
            Else
                txtlevel4.Text = ""
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    'priti added on 01-06-2011 --- To implement the access control
    'Private Function funSetUserAccess() As Boolean
    '    Try
    '        'If funCheckLoginStatus() = False Then Exit Function
    '        Dim strRights As String
    '        Dim strTemp() As String
    '        Dim strProgCode = "SalesMan-H"
    '        strRights = enuUserRights.enuRead & "," & enuUserRights.enuModify & "," & enuUserRights.enuDelete
    '        strRights = modUserMgt.funGetPermissions(strRights, strProgCode)
    '        strTemp = Split(strRights, ",")
    '        If strTemp(0) = "0" Then
    '            MsgBox("Permission Denied", MsgBoxStyle.Critical, Me.Text)
    '            funSetUserAccess = False
    '            blnRead = False
    '            Me.Close()
    '            Exit Function
    '        Else
    '            blnRead = True
    '        End If
    '        If strTemp(1) = "0" Then 'Grant modify access
    '            btnSave.Enabled = False
    '        End If
    '        If strTemp(2) = "0" Then 'Grant modify access
    '            btnDelete.Enabled = False
    '        End If

    '        funSetUserAccess = True
    '    Catch er As Exception

    '    End Try
    'End Function
    'Code ends here

    Public Sub fndSalesmancode_TextChanged()

        'txtSalesmanName.Text = fndSalesmancode.Tag

        Dim strsalescode As String = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select  Salesman_Code from TSPL_SALESMAN_MAPPING  where Salesman_Code ='" + fndSalesmancode.Value + "' "))

        If strsalescode <> "" Then
            funfill()
        Else
            txtCommissionRate.Text = ""
            ddlUserType.Text = "----Select----"
            fndLevel1.txtValue.Text = ""
            fndLevel2.txtValue.Text = ""
            fndLevel3.txtValue.Text = ""
            fndLevel4.txtValue.Text = ""
            'fndLevel1.Enabled = False
            'fndLevel2.Enabled = False
            'fndLevel3.Enabled = False
            'fndLevel4.Enabled = False

            fndLevel1.Enabled = True
            fndLevel2.Enabled = True
            fndLevel3.Enabled = True
            fndLevel4.Enabled = True
            btnSave.Text = "Save"
            btnDelete.Enabled = False
        End If

        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub

    Private Sub funfill()
        dr = clsDBFuncationality.GetDataTable("select  Salesman_Name,Commission_Rate,TYPE,Level1_Code,Level2_Code,Level3_Code,Level4_Code ,L1SDate,L2SDate,L3SDate,L4SDate  from TSPL_SALESMAN_MAPPING  where Salesman_Code ='" + fndSalesmancode.Value + "' ")

        If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
            txtSalesmanName.Text = dr.Rows(0)(0).ToString()
            txtCommissionRate.Text = dr.Rows(0)(1).ToString()
            ddlUserType.Text = dr.Rows(0)(2).ToString()
            fndLevel1.txtValue.Text = dr.Rows(0)(3).ToString()
            fndLevel2.txtValue.Text = dr.Rows(0)(4).ToString()
            fndLevel3.txtValue.Text = dr.Rows(0)(5).ToString()
            fndLevel4.txtValue.Text = dr.Rows(0)(6).ToString()

            SDateL1.Value = dr.Rows(0)(7)
            SDateL2.Value = dr.Rows(0)(8)
            SDateL3.Value = dr.Rows(0)(9)
            SDateL4.Value = dr.Rows(0)(10)

            'If dr(3).ToString() <> "" Then
            '    fndLevel1.Enabled = True
            '    fndLevel1.txtValue.Text = dr(3).ToString()
            'End If
            'If dr(4).ToString() <> "" Then
            '    fndLevel2.Enabled = True
            '    fndLevel2.txtValue.Text = dr(4).ToString()
            'End If
            'If dr(5).ToString() <> "" Then
            '    fndLevel3.Enabled = True
            '    fndLevel3.txtValue.Text = dr(5).ToString()

            'End If
            'If dr(6).ToString() <> "" Then
            '    fndLevel4.Enabled = True
            '    fndLevel4.txtValue.Text = dr(6).ToString()
            'End If
        End If
         
        btnDelete.Enabled = True
        btnSave.Text = "Update"
    End Sub

    Private Sub fndLevel1_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)

        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If
    End Sub

    Private Sub fndLevel2_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)

        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If
    End Sub
    Private Sub fndLevel3_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)

        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If
    End Sub
    Private Sub fndLevel4_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)

        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If
    End Sub
    Private Sub fndSalesmancode_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)

        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If
    End Sub


    Private Sub fndSalesmancode_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'fndSalesmancode.ConnectionString = connectSql.SqlCon()
        'fndSalesmancode.Query = "select Route_No as [Route Number],Route_Desc as Description from TSPL_ROUTE_MASTER where Status='A'  order by [Route Number] "
        'fndSalesmancode.ValueToSelect = "Route Number"
        'fndSalesmancode.ValueToSelect1 = "Description"
        'fndSalesmancode.Caption = "Route Details"
    End Sub

    Private Sub txtCommissionRate_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCommissionRate.KeyPress
        If (Microsoft.VisualBasic.Asc(e.KeyChar) >= 48 And Microsoft.VisualBasic.Asc(e.KeyChar) <= 57) Then
            e.Handled = False
        ElseIf Microsoft.VisualBasic.Asc(e.KeyChar) = 8 Then
            e.Handled = False
        Else
            e.Handled = True
        End If

    End Sub

    Private Sub ddlUserType_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As Telerik.WinControls.UI.Data.PositionChangedEventArgs) Handles ddlUserType.SelectedIndexChanged
        If ddlUserType.Text = "HOS" Then
            fndLevel1.Enabled = False
            fndLevel2.Enabled = False
            fndLevel3.Enabled = False
            fndLevel4.Enabled = False

            txtlevel1.Enabled = False
            txtlevel2.Enabled = False
            txtlevel3.Enabled = False
            txtlevel4.Enabled = False


        ElseIf ddlUserType.Text = "TDM" Then
            fndLevel1.Enabled = False
            fndLevel2.Enabled = False
            fndLevel3.Enabled = False
            fndLevel4.Enabled = False

            txtlevel1.Enabled = False
            txtlevel2.Enabled = False
            txtlevel3.Enabled = False
            txtlevel4.Enabled = False

            fndLevel1.Enabled = True
            txtlevel1.Enabled = True
            globalFunc.mandatoryText(fndLevel1.txtValue, txtlevel1)
        ElseIf ddlUserType.Text = "ADC" Then

            fndLevel1.Enabled = False
            fndLevel2.Enabled = False
            fndLevel3.Enabled = False
            fndLevel4.Enabled = False

            txtlevel1.Enabled = False
            txtlevel2.Enabled = False
            txtlevel3.Enabled = False
            txtlevel4.Enabled = False


            fndLevel1.Enabled = True
            fndLevel2.Enabled = True
            txtlevel1.Enabled = True
            txtlevel2.Enabled = True
            globalFunc.mandatoryText(fndLevel1.txtValue, fndLevel2.txtValue, txtlevel1, txtlevel2)
        ElseIf ddlUserType.Text = "CE" Then

            fndLevel1.Enabled = False
            fndLevel2.Enabled = False
            fndLevel3.Enabled = False
            fndLevel4.Enabled = False


            txtlevel1.Enabled = False
            txtlevel2.Enabled = False
            txtlevel3.Enabled = False
            txtlevel4.Enabled = False

            fndLevel1.Enabled = True
            fndLevel2.Enabled = True
            fndLevel3.Enabled = True

            txtlevel1.Enabled = True
            txtlevel2.Enabled = True
            txtlevel3.Enabled = True
            globalFunc.mandatoryText(fndLevel1.txtValue, fndLevel2.txtValue, fndLevel3.txtValue, txtlevel1, txtlevel2, txtlevel3)
        ElseIf ddlUserType.Text = "RA" Then

            fndLevel1.Enabled = False
            fndLevel2.Enabled = False
            fndLevel3.Enabled = False
            fndLevel4.Enabled = False

            txtlevel1.Enabled = False
            txtlevel2.Enabled = False
            txtlevel3.Enabled = False
            txtlevel4.Enabled = False

            fndLevel1.Enabled = True
            fndLevel2.Enabled = True
            fndLevel3.Enabled = True
            fndLevel4.Enabled = True

            txtlevel1.Enabled = True
            txtlevel2.Enabled = True
            txtlevel3.Enabled = True
            txtlevel4.Enabled = True
            globalFunc.mandatoryText(fndLevel1.txtValue, fndLevel2.txtValue, fndLevel3.txtValue, fndLevel4.txtValue, txtlevel1, txtlevel2, txtlevel3, txtlevel4)
        Else
        End If
    End Sub

    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(fndSalesmancode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow("You Cannot Delete Record")
            Exit Sub
        End If
        '' Code Added By Abhishek as on 19/10/2012 11:29 am  For Check If Exist SettlementCode in TSPL_TRANSFER_HEAD,TSPL_SHIPMENT_MASTER then Don't Delete
        Dim SalesemenCode As String
        Dim SalesemenCode1 As String
        SalesemenCode = clsDBFuncationality.getSingleValue(" select Route_No  from TSPL_TRANSFER_HEAD  where Route_No ='" & fndSalesmancode.Value & "'")
        SalesemenCode1 = clsDBFuncationality.getSingleValue(" select Route_No  from TSPL_SHIPMENT_MASTER where Route_No='" & fndSalesmancode.Value & "'")
        If clsCommon.myLen(SalesemenCode) > 0 Or clsCommon.myLen(SalesemenCode1) > 0 Then
            common.clsCommon.MyMessageBoxShow("This record can't be deleted.It is used in another process")
            Exit Sub
        End If
        '' Code Ends 

        If myMessages.deleteConfirm() Then
            funDelete()
        Else

        End If


    End Sub

    Private Sub btnnew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnnew.Click
        funReset()
    End Sub
    Private Sub funReset()
        fndSalesmancode.Value = ""
        fndSalesmancode.MyReadOnly = False
        txtSalesmanName.Text = ""
        txtCommissionRate.Text = ""
        ddlUserType.Text = "----Select----"
        fndLevel1.txtValue.Text = ""
        fndLevel2.txtValue.Text = ""
        fndLevel3.txtValue.Text = ""
        fndLevel4.txtValue.Text = ""
        txtlevel1.Text = ""
        txtlevel2.Text = ""
        txtlevel3.Text = ""
        txtlevel4.Text = ""
        'fndLevel1.Enabled = False
        'fndLevel2.Enabled = False
        'fndLevel3.Enabled = False
        'fndLevel4.Enabled = False
        fndLevel1.Enabled = True
        fndLevel2.Enabled = True
        fndLevel3.Enabled = True
        fndLevel4.Enabled = True

        SetDataBaseGrid()
        SDateL1.Value = clsCommon.GETSERVERDATE()
        SDateL2.Value = clsCommon.GETSERVERDATE()
        SDateL3.Value = clsCommon.GETSERVERDATE()
        SDateL4.Value = clsCommon.GETSERVERDATE()
        btnSave.Text = "Save"
        btnDelete.Enabled = False
    End Sub

    Private Sub txtCommissionRate_Leave(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles txtCommissionRate.Leave
        If txtCommissionRate.Text <> "" Then
            Dim m As Double = clsCommon.myCdbl(txtCommissionRate.Text)
            If m > 100 Then
                common.clsCommon.MyMessageBoxShow("Percentage cannot be greater than 100.")
                txtCommissionRate.Text = 100
                ' txtPercentage.Text = ""
                'txtPercentage.Focus()
            Else

            End If
        End If
    End Sub

    Private Sub fndLevel1_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles fndLevel1.Load

        'fndLevel1.Query = "select Salesman_Code as [SalesMan Code] ,Salesman_Name as [SalesMan Name] from TSPL_SALESMAN_MAPPING where Type ='HOS' order by Salesman_Code"
        fndLevel1.ConnectionString = connectSql.SqlCon()
        fndLevel1.Query = "select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master "
        fndLevel1.ValueToSelect = "Employee Code"
        fndLevel1.ValueToSelect1 = "Employee Name"
        fndLevel1.Caption = "SalesMan Details"
    End Sub

    Private Sub fndLevel2_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles fndLevel2.Load
        'fndLevel2.ConnectionString = connectSql.SqlCon()
        'fndLevel2.Query = "select Salesman_Code as [SalesMan Code] ,Salesman_Name as [SalesMan Name] from TSPL_SALESMAN_MAPPING where Type ='TDM' order by Salesman_Code"
        'fndLevel2.ValueToSelect = "SalesMan Code"
        'fndLevel2.Caption = "SalesMan Details"
        'fndLevel2.ValueToSelect1 = "SalesMan Name"
        fndLevel2.ConnectionString = connectSql.SqlCon()
        fndLevel2.Query = "select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master "
        fndLevel2.ValueToSelect = "Employee Code"
        fndLevel2.ValueToSelect1 = "Employee Name"
        fndLevel2.Caption = "SalesMan Details"


    End Sub

    Private Sub fndLevel3_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles fndLevel3.Load
        'fndLevel3.ConnectionString = connectSql.SqlCon()
        'fndLevel3.Query = "select Salesman_Code as [SalesMan Code] ,Salesman_Name as [SalesMan Name] from TSPL_SALESMAN_MAPPING where Type ='ADC' order by Salesman_Code"
        'fndLevel3.ValueToSelect = "SalesMan Code"
        'fndLevel3.Caption = "SalesMan Details"
        'fndLevel3.ValueToSelect1 = "SalesMan Name"

        fndLevel3.ConnectionString = connectSql.SqlCon()
        fndLevel3.Query = "select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master "
        fndLevel3.ValueToSelect = "Employee Code"
        fndLevel3.ValueToSelect1 = "Employee Name"
        fndLevel3.Caption = "SalesMan Details"
    End Sub

    Private Sub fndLevel4_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles fndLevel4.Load
        'fndLevel4.ConnectionString = connectSql.SqlCon()
        'fndLevel4.Query = "select Salesman_Code as [SalesMan Code] ,Salesman_Name as [SalesMan Name] from TSPL_SALESMAN_MAPPING where Type ='CE' order by Salesman_Code"
        'fndLevel4.ValueToSelect = "SalesMan Code"
        'fndLevel4.Caption = "SalesMan Details"
        'fndLevel4.ValueToSelect1 = "SalesMan Name"

        fndLevel4.ConnectionString = connectSql.SqlCon()
        fndLevel4.Query = "select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master "
        fndLevel4.ValueToSelect = "Employee Code"
        fndLevel4.ValueToSelect1 = "Employee Name"
        fndLevel4.Caption = "SalesMan Details"
    End Sub

    Private Sub fndLevel1_Leave(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles fndLevel1.Leave
        If fndLevel1.txtValue.Text <> "" Then
            dr = clsDBFuncationality.GetDataTable("select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master where emp_code='" + fndLevel1.txtValue.Text + "'")
            Dim s As String = ""
            If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                s = dr.Rows(0)(0).ToString()
            End If

            If s <> fndLevel1.txtValue.Text Then
                common.clsCommon.MyMessageBoxShow("HOS doesn't exist.")
                fndLevel1.txtValue.Text = ""
                fndLevel1.txtValue.Focus()
            Else

            End If
        End If

    End Sub

    Private Sub fndLevel2_Leave(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles fndLevel2.Leave
        If fndLevel2.txtValue.Text <> "" Then
            dr = clsDBFuncationality.GetDataTable("select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master where emp_code='" + fndLevel2.txtValue.Text + "'")
            Dim s As String = ""
            If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                s = dr.Rows(0)(0).ToString()
            End If
            If s <> fndLevel2.txtValue.Text Then
                common.clsCommon.MyMessageBoxShow("TDM doesn't exist.")
                fndLevel2.txtValue.Text = ""
                fndLevel2.txtValue.Focus()
            Else

            End If
        End If
    End Sub

    Private Sub fndLevel3_Leave(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles fndLevel3.Leave
        If fndLevel3.txtValue.Text <> "" Then
            dr = clsDBFuncationality.GetDataTable("select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master where emp_code='" + fndLevel3.txtValue.Text + "'")
            Dim s As String = ""
            If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                s = dr.Rows(0)(0).ToString()
            End If
            If s <> fndLevel3.txtValue.Text Then
                common.clsCommon.MyMessageBoxShow("ADC doesn't exist.")
                fndLevel3.txtValue.Text = ""
                fndLevel3.txtValue.Focus()
            Else
            End If
        End If
    End Sub

    Private Sub fndLevel4_Leave(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles fndLevel4.Leave
        If fndLevel4.txtValue.Text <> "" Then
            dr = clsDBFuncationality.GetDataTable("select emp_Code as [Employee Code] ,emp_Name as [Employee Name] from TSPL_employee_master where emp_code='" + fndLevel4.txtValue.Text + "'")
            Dim s As String = ""

            If dr IsNot Nothing AndAlso dr.Rows.Count > 0 Then
                s = dr.Rows(0)(0).ToString()
            End If
            If s <> fndLevel4.txtValue.Text Then
                common.clsCommon.MyMessageBoxShow("CE doesn't exist.")
                fndLevel4.txtValue.Text = ""
                fndLevel4.txtValue.Focus()
            Else

            End If
        End If
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        Me.Close()

    End Sub

    Private Sub fndSalesmancode_Leave(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'If fndSalesmancode.Value<> "" Then
        '    dr = connectSql.RunSqlReturnDR(" select emp_code from TSPL_EMPLOYEE_MASTER  where emp_code='" + fndSalesmancode.Value+ "'")
        '    Dim s As String
        '    While dr.Read()
        '        s = dr(0).ToString()
        '    End While
        '    If s <> fndSalesmancode.ValueThen
        '        common.clsCommon.MyMessageBoxShow("Employee doesn't exist.")
        '        fndSalesmancode.Value= ""
        '        txtSalesmanName.Text = ""
        '        fndSalesmancode.txtValue.Focus()
        '    Else

        '    End If
        ' End If
    End Sub

    Private Function GetReplecateCompaniesDataBase() As List(Of String)
        Dim arrDBName As New List(Of String)
        arrDBName.Add(objCommonVar.CurrDatabase)
        For ii As Integer = 0 To gvDB.Rows.Count - 1
            If (clsCommon.myCBool(gvDB.Rows(ii).Cells(colSelect).Value)) Then
                arrDBName.Add(clsCommon.myCstr(gvDB.Rows(ii).Cells(colDataBaseName).Value))
            End If
        Next
        Return arrDBName
    End Function

    Sub SetDataBaseGrid()
        gvDB.Rows.Clear()
        gvDB.Columns.Clear()

        Dim repoSelect As GridViewCheckBoxColumn = New GridViewCheckBoxColumn()
        repoSelect.FormatString = ""
        repoSelect.HeaderText = "Select"
        repoSelect.Name = colSelect
        repoSelect.Width = 50
        repoSelect.ReadOnly = False
        repoSelect.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
        gvDB.MasterTemplate.Columns.Add(repoSelect)

        Dim repoCompCode As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoCompCode.FormatString = ""
        repoCompCode.HeaderText = "Company Code"
        repoCompCode.Name = colCompCode
        repoCompCode.Width = 150
        repoCompCode.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoCompCode)

        Dim repoCompName As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoCompName.FormatString = ""
        repoCompName.HeaderText = "Company Name"
        repoCompName.Name = colCompName
        repoCompName.Width = 150
        repoCompName.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoCompName)

        Dim repoDB As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoDB.FormatString = ""
        repoDB.HeaderText = "Database Name"
        repoDB.Name = colDataBaseName
        repoDB.IsVisible = False
        repoDB.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoDB)

        Dim qry As String = "SELECT Comp_Code,Comp_Name,DataBase_Name from TSPL_COMPANY_MASTER where len(isnull(DataBase_Name,''))>0 and Comp_Code not in ('" + objCommonVar.CurrentCompanyCode + "')"
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            For Each dr As DataRow In dt.Rows
                gvDB.Rows.AddNew()
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colSelect).Value = False
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colCompCode).Value = clsCommon.myCstr(dr("Comp_Code"))
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colCompName).Value = clsCommon.myCstr(dr("Comp_Name"))
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colDataBaseName).Value = clsCommon.myCstr(dr("DataBase_Name"))
            Next
        End If
    End Sub


    Private Sub Export_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Export.Click
        Dim str As String
        str = "select salesman_code as [Salesman code],level1_code as [HOS],level2_code as [TDM],level3_code as [ADC],level4_code as [CE],L1SDate as [HOS StartDate],L2SDate as [TDM StartDate],L3SDate as [ADC StartDate],L4SDate as [CE StartDate] from TSPL_SALESMAN_MAPPING"
        transportSql.ExporttoExcel(str, Me)
    End Sub




    Private Sub Import_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Import.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        If transportSql.importExcel(gv, "Salesman code", "HOS", "TDM", "ADC", "CE", "HOS StartDate", "TDM StartDate", "ADC StartDate", "CE StartDate") Then
            Dim trans As SqlTransaction = Nothing
            Try
                connectSql.OpenConnection()
                trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()

                For Each grow As GridViewRowInfo In gv.Rows
                    Dim strcode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If clsCommon.myLen(strcode) > 12 Then
                        Throw New Exception("Check the length of 'Code'.")
                    End If
                    ''richa agarwal
                    ' Dim acc1 As String = "SELECT count(*)  FROM [dbo].[TSPL_ROUTE_MASTER] where route_no='" + strcode + "'"
                    Dim acc1 As String = "SELECT count(*)  FROM [dbo].[TSPL_EMPLOYEE_MASTER] where EMP_CODE='" + strcode + "' and Emp_type ='EMP01'"
                    Dim no1 As Integer = CInt(connectSql.RunScalar(trans, acc1))
                    If no1 = 0 Then
                        Throw New Exception("This  " + strcode + "  Salesman Code does not exist")
                    End If



                    Dim strhos As String = clsCommon.myCstr(grow.Cells("HOS").Value)
                    Dim LS1DATE As String = clsCommon.GetPrintDate(clsCommon.myCstr(grow.Cells("HOS StartDate").Value), "dd/MM/yyyy")
                    Dim LS2DATE As String = clsCommon.GetPrintDate(clsCommon.myCstr(grow.Cells("TDM StartDate").Value), "dd/MM/yyyy")
                    Dim LS3DATE As String = clsCommon.GetPrintDate(clsCommon.myCstr(grow.Cells("ADC StartDate").Value), "dd/MM/yyyy")
                    Dim LS4DATE As String = clsCommon.GetPrintDate(clsCommon.myCstr(grow.Cells("CE StartDate").Value), "dd/MM/yyyy")
                    If clsCommon.myLen(strhos) > 12 Then
                        Throw New Exception("Check the length of 'HOS'.")
                    End If
                    Dim acc2 As String = "SELECT count(*)  FROM [dbo].[TSPL_employee_master] where emp_code='" + strhos + "'"
                    Dim no2 As Integer = CInt(connectSql.RunScalar(trans, acc2))
                    If no2 = 0 Then
                        Throw New Exception("This  " + strhos + "   Code does not exist")
                    End If

                    Dim strtdm As String = clsCommon.myCstr(grow.Cells("TDM").Value)
                    If clsCommon.myLen(strtdm) > 12 Then
                        Throw New Exception("Check the length of 'TDM'.")
                    End If
                    Dim acc3 As String = "SELECT count(*)  FROM [dbo].[TSPL_employee_master] where emp_code='" + strtdm + "'"
                    Dim no3 As Integer = CInt(connectSql.RunScalar(trans, acc3))
                    If no3 = 0 Then
                        Throw New Exception("This  " + strtdm + "   Code does not exist")
                    End If


                    Dim stradc As String = clsCommon.myCstr(grow.Cells("ADC").Value)
                    If clsCommon.myLen(stradc) > 12 Then
                        Throw New Exception("Check the length of 'ADC'.")
                    End If
                    Dim acc4 As String = "SELECT count(*)  FROM [dbo].[TSPL_employee_master] where emp_code='" + stradc + "'"
                    Dim no4 As Integer = CInt(connectSql.RunScalar(trans, acc4))
                    If no4 = 0 Then
                        Throw New Exception("This  " + stradc + "   Code does not exist")
                    End If


                    Dim strce As String = clsCommon.myCstr(grow.Cells("CE").Value)
                    If clsCommon.myLen(strce) > 12 Then
                        Throw New Exception("Check the length of 'TDM'.")
                    End If
                    Dim acc5 As String = "SELECT count(*)  FROM [dbo].[TSPL_employee_master] where emp_code='" + strce + "'"
                    Dim no5 As Integer = CInt(connectSql.RunScalar(trans, acc5))
                    If no5 = 0 Then
                        Throw New Exception("This  " + strce + "   Code does not exist")
                    End If

                    Dim createddate As String = CDate(connectSql.serverDate(trans)).ToString("dd/MM/yyyy ")
                    Dim modifydate As String = CDate(connectSql.serverDate(trans)).ToString("dd/MM/yyyy ")
                    'Dim createddate As String = (clsCommon.GETSERVERDATE).ToString("dd/MM/yyyy")
                    'Dim modifydate As String = (clsCommon.GETSERVERDATE).ToString("dd/MM/yyyy")
                    Dim commision As Decimal = 0
                    Dim type As String = ""
                    ' Dim SalesName As String = connectSql.RunScalar(trans, "SELECT TSPL_ROUTE_MASTER.Employee_Name FROM TSPL_ROUTE_MASTER  where Route_No='" + strcode + "' ")
                    Dim SalesName As String = connectSql.RunScalar(trans, "SELECT TSPL_EMPLOYEE_MASTER.Emp_Name FROM TSPL_EMPLOYEE_MASTER  where EMP_CODE='" + strcode + "' ")
                    ''=====================
                    Dim sql1 As String = "select count(*) from TSPL_SALESMAN_MAPPING where salesman_code='" + strcode + "' "
                    Dim i As Integer = CInt(connectSql.RunScalar(trans, sql1))
                    If (i = 0) Then
                        Dim Sql As String = "insert into TSPL_SALESMAN_MAPPING(salesman_code,salesman_name,commission_rate,type,level1_code,level2_code,level3_code,level4_code,created_by,created_date,modify_by,modify_date,comp_code,L1SDATE,L2SDATE,L3SDATE,L4SDATE) values ('" + strcode.ToString() + "', '" + SalesName + "', '" + clsCommon.myCstr(commision) + "','" + clsCommon.myCstr(type) + "','" + clsCommon.myCstr(strhos) + "','" + clsCommon.myCstr(strtdm) + "', '" + clsCommon.myCstr(stradc) + "','" + clsCommon.myCstr(strce) + "','" + userCode + "' ,'" + createddate + "','" + userCode + "', '" + modifydate + "', '" + companyCode + "' ,Convert(date,'" + LS1DATE + "', 103),COnvert(Date,'" + LS2DATE + "', 103),COnvert(Date,'" + LS3DATE + "', 103),COnvert(Date, '" + LS4DATE + "', 103))"
                        connectSql.RunSqlTransaction(trans, Sql)
                    Else
                        Dim sql As String = "update TSPL_SALESMAN_MAPPING set salesman_name='" + clsCommon.myCstr(SalesName) + "',commission_rate='" + clsCommon.myCstr(commision) + "',type='" + clsCommon.myCstr(type) + "',level1_code='" + clsCommon.myCstr(strhos) + "',level2_code='" + clsCommon.myCstr(strtdm) + "',level3_code='" + clsCommon.myCstr(stradc) + "',level4_code='" + clsCommon.myCstr(strce) + "',modify_by='" + userCode + "',modify_date='" + modifydate + "',comp_code='" + companyCode + "' ,L1SDATE=Convert(Date,'" + LS1DATE + "', 103) ,L2SDATE=Convert(Date,'" + LS2DATE + "', 103),L3SDATE=COnvert(date,'" + LS3DATE + "', 103),L4SDATE=Convert(Date,'" + LS4DATE + "', 103) where salesman_code = '" + strcode + "' "
                        connectSql.RunSqlTransaction(trans, sql)
                    End If
                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
8:          Catch ex As Exception
                trans.Rollback()
                clsCommon.ProgressBarHide()

                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub



    Private Sub FrmSalesManHierarchy_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            'PostData() 
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub fndSalesmancode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndSalesmancode._MYValidating

        Dim str As String = "select count(*) from TSPL_SALESMAN_MAPPING where Salesman_Code ='" + fndSalesmancode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 Then
            fndSalesmancode.MyReadOnly = False
            'common.clsCommon.MyMessageBoxShow("value does not exists")
            fndSalesmancode.Value = ""
        Else
            fndSalesmancode.MyReadOnly = True
        End If
        If fndSalesmancode.MyReadOnly OrElse isButtonClicked Then
            'Dim qry As String = "select Route_No as [RouteNumber],Route_Desc as Description ,Level1_Code as HOS,L1.Emp_Name as [HOS Name],Level2_Code as TDM,l2.Emp_Name as [TDS Name],Level3_Code as ADC,l2.Emp_Name as [ADC Name],Level4_Code as CE,L4.Emp_Name as [CE Name]"
            'qry += " from TSPL_ROUTE_MASTER "
            'qry += " left outer join TSPL_SALESMAN_MAPPING on TSPL_SALESMAN_MAPPING.Salesman_Code=Route_No"
            'qry += " left outer join TSPL_EMPLOYEE_MASTER  as L1 on L1.EMP_CODE=Level1_Code"
            'qry += " left outer join TSPL_EMPLOYEE_MASTER  as L2 on L2.EMP_CODE=Level2_Code"
            'qry += " left outer join TSPL_EMPLOYEE_MASTER  as L3 on L3.EMP_CODE=Level3_Code"
            'qry += " left outer join TSPL_EMPLOYEE_MASTER  as L4 on L4.EMP_CODE=Level4_Code  "
            'fndSalesmancode.Value = clsCommon.ShowSelectForm("SalesManCodFND", qry, "RouteNumber", "Status='A'", fndSalesmancode.Value, "[RouteNumber]", isButtonClicked)
            'txtSalesmanName.Text = clsDBFuncationality.getSingleValue("Select Route_Desc from TSPL_ROUTE_MASTER where Route_No='" + fndSalesmancode.Value + "'")
            ''richa agarwal
            Dim qry As String = "select TSPL_EMPLOYEE_MASTER.EMP_CODE ,TSPL_EMPLOYEE_MASTER.Emp_Name ,Level1_Code as HOS,L1.Emp_Name as [HOS Name],Level2_Code as TDM,l2.Emp_Name as [TDS Name],Level3_Code as ADC,l2.Emp_Name as [ADC Name],Level4_Code as CE,L4.Emp_Name as [CE Name]"
            qry += " from TSPL_EMPLOYEE_MASTER "
            qry += " left outer join TSPL_SALESMAN_MAPPING on TSPL_SALESMAN_MAPPING.Salesman_Code=TSPL_EMPLOYEE_MASTER.EMP_CODE"
            qry += " left outer join TSPL_EMPLOYEE_MASTER  as L1 on L1.EMP_CODE=Level1_Code"
            qry += " left outer join TSPL_EMPLOYEE_MASTER  as L2 on L2.EMP_CODE=Level2_Code"
            qry += " left outer join TSPL_EMPLOYEE_MASTER  as L3 on L3.EMP_CODE=Level3_Code"
            qry += " left outer join TSPL_EMPLOYEE_MASTER  as L4 on L4.EMP_CODE=Level4_Code  "
            fndSalesmancode.Value = clsCommon.ShowSelectForm("SalesManCodFND", qry, "EMP_CODE", " TSPL_EMPLOYEE_MASTER.Emp_type ='EMP01'", fndSalesmancode.Value, "", isButtonClicked)
            txtSalesmanName.Text = clsDBFuncationality.getSingleValue("Select Emp_Name from TSPL_EMPLOYEE_MASTER where EMP_CODE='" + fndSalesmancode.Value + "'")

            ''===============

            If fndSalesmancode.Value IsNot Nothing Then
                btnDelete.Enabled = True
            Else
                btnDelete.Enabled = False
            End If

        End If
        fndSalesmancode_TextChanged()
    End Sub

    Private Sub fndSalesmancode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavigatorType As common.NavigatorType) Handles fndSalesmancode._MYNavigator
        'Dim qst As String = "select Route_No as [Route Number],Route_Desc as [Description] from TSPL_ROUTE_MASTER where  2=2 "
        'Select Case NavigatorType
        '    Case NavigatorType.Current
        '        '  qst += "and assign_to='" + txtassign.Value + "' "
        '        ' qst += "and job_code in ('" + txtcode1.Value + "')"
        '    Case NavigatorType.Next
        '        qst += "and Route_No in (select min(Route_No) from TSPL_ROUTE_MASTER where Route_No>'" + fndSalesmancode.Value + "'  and Status='A'   ) "
        '    Case NavigatorType.First
        '        qst += "and Route_No in (select MIN(Route_No) from TSPL_ROUTE_MASTER where Status='A'   )"
        '    Case NavigatorType.Last
        '        qst += "and Route_No in (select Max(Route_No) from TSPL_ROUTE_MASTER where Status='A'   )"
        '    Case NavigatorType.Previous
        '        qst += "and Route_No in (select max(Route_No) from TSPL_ROUTE_MASTER where Route_No<'" + fndSalesmancode.Value + "' and  Status='A'    )"
        'End Select
        '' fun_gridfill()
        'Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        'If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
        '    fndSalesmancode.Value = clsCommon.myCstr(dt.Rows(0)("Route Number"))
        '    txtSalesmanName.Text = clsCommon.myCstr(dt.Rows(0)("Description"))
        'End If
        ''TextChanged()
        'If fndSalesmancode.Value IsNot Nothing Then
        '    btnDelete.Enabled = True
        'Else
        '    btnDelete.Enabled = False

        'End If
        Dim qst As String = "Select EMP_CODE ,Emp_Name from TSPL_EMPLOYEE_MASTER where 2=2  "
        Select Case NavigatorType
            Case NavigatorType.Current
                '  qst += "and assign_to='" + txtassign.Value + "' "
                ' qst += "and job_code in ('" + txtcode1.Value + "')"
            Case NavigatorType.Next
                qst += "and EMP_CODE in (select min(EMP_CODE) from TSPL_EMPLOYEE_MASTER where EMP_CODE>'" + fndSalesmancode.Value + "'  and Emp_type ='EMP01'   ) "
            Case NavigatorType.First
                qst += "and EMP_CODE in (select MIN(EMP_CODE) from TSPL_EMPLOYEE_MASTER where Emp_type ='EMP01'   )"
            Case NavigatorType.Last
                qst += "and EMP_CODE in (select Max(EMP_CODE) from TSPL_EMPLOYEE_MASTER where Emp_type ='EMP01'   )"
            Case NavigatorType.Previous
                qst += "and EMP_CODE in (select max(EMP_CODE) from TSPL_EMPLOYEE_MASTER where EMP_CODE<'" + fndSalesmancode.Value + "' and Emp_type ='EMP01'    )"
        End Select
        ' fun_gridfill()
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            fndSalesmancode.Value = clsCommon.myCstr(dt.Rows(0)("EMP_CODE"))
            txtSalesmanName.Text = clsCommon.myCstr(dt.Rows(0)("Emp_Name"))
        End If
        'TextChanged()
        If fndSalesmancode.Value IsNot Nothing Then
            btnDelete.Enabled = True
        Else
            btnDelete.Enabled = False

        End If
        fndSalesmancode_TextChanged()
    End Sub
End Class
