'--16/09/2013--form Add By- Pradeep Sharma-------- Ticket no :BM00000000473---------
Imports common
Imports System.Data
Imports System.Data.SqlClient

Public Class frmResourceMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String

#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        Save()
    End Sub

    Public Sub Save()
        Try
            If AllowToSave() Then
                Dim obj As New clsResourceMaster()
                obj.RESOURCE_CODE = txtCode.Value
                obj.DESCRIPTION = txtDescription.Text
                obj.COMMENTS = txtComments.Text
                obj.STATUS = clsCommon.myCstr(cboStatus.SelectedValue)
                obj.RESOURCE_TYPE = clsCommon.myCstr(cboType.SelectedValue)
                obj.UNIT_CODE = clsCommon.myCstr(cboUOM.SelectedValue)
                obj.UNIT_CODE_OTHER = txtOtherUOM.Text
                obj.COST = txtCost.Value

                If (obj.SaveData(obj, isNewEntry, False)) Then
                    common.clsCommon.MyMessageBoxShow("Data Saved Successfully")
                    LoadData(obj.RESOURCE_CODE, NavigatorType.Current)
                End If
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
        
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnSave.Enabled = True
        btnDelete.Enabled = True
        isNewEntry = False
        Dim obj As New clsResourceMaster()
        obj = clsResourceMaster.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.RESOURCE_CODE) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            txtCode.Value = obj.RESOURCE_CODE
            txtComments.Text = obj.COMMENTS
            txtDescription.Text = obj.DESCRIPTION
            cboStatus.SelectedValue = clsCommon.myCstr(obj.STATUS)
            cboType.SelectedValue = clsCommon.myCstr(obj.RESOURCE_TYPE)
            cboType.Enabled = False
            cboUOM.SelectedValue = clsCommon.myCstr(obj.UNIT_CODE)
            cboUOM.Enabled = False
            txtOtherUOM.Text = obj.UNIT_CODE_OTHER
            txtOtherUOM.ReadOnly = True
            txtCost.Value = clsCommon.myCdbl(obj.COST)
            txtLastMaintained.Text = obj.Modified_Date
            txtMaintainedBy.Text = obj.Modified_By
        End If
    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
            myMessages.blankValue("Resource Code")
            txtCode.Focus()
            Return False
        ElseIf clsUOMInfo.CheckUnitCode(Me.cboUOM.Text, Nothing) = False Then
            clsCommon.MyMessageBoxShow("UOM " & Me.cboUOM.Text & " does not exist. create it first.")
            Return False
        ElseIf (clsCommon.CompairString(clsCommon.myCstr(cboType.SelectedValue), "Setup Labor") = CompairStringResult.Equal) Or (clsCommon.CompairString(clsCommon.myCstr(cboType.SelectedValue), "Run Labor") = CompairStringResult.Equal) Then
            If clsCommon.CompairString(clsCommon.myCstr(cboUOM.SelectedValue), "Others") = CompairStringResult.Equal Then
                clsCommon.MyMessageBoxShow("Invalid Input. For resource with setup labor or run labor types, the UOM must be either per hour or per minute.")
                cboUOM.Focus()
                Return False
            End If
        
        End If

        Return True
    End Function

    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow("You Cannot Delete Record")
            Exit Sub
        End If
        funDelete()
    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsResourceMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow("Data Deleted Successfully ")
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub frmResourceMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isNewEntry = True

        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        '  ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")
        funReset()
    End Sub

    Private Sub SetUserMgmtNew()
        ''MyBase.SetUserMgmt(clsUserMgtCode.frmResourceMaster)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 02/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            MenuItemImport.Enabled = True
            MenuItemExport.Enabled = True
        Else
            MenuItemImport.Enabled = False
            MenuItemExport.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        txtComments.Text = ""
        txtDescription.Text = ""
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = True

        cboStatus.DataSource = GetCboStatusDataTable()
        cboStatus.ValueMember = "RESOURCE_CODE"
        cboStatus.DisplayMember = "Value"
        cboStatus.SelectedIndex = -1

        cboUOM.DataSource = GetCboUOMDataTable()
        cboUOM.ValueMember = "RESOURCE_CODE"
        cboUOM.DisplayMember = "Value"
        cboUOM.SelectedIndex = -1
        cboUOM.Enabled = True

        cboType.DataSource = GetCboTypeDataTable()
        cboType.ValueMember = "RESOURCE_CODE"
        cboType.DisplayMember = "Value"
        cboType.SelectedIndex = -1
        cboType.Enabled = True
        txtCost.Value = 0
        txtLastMaintained.Text = ""
        txtMaintainedBy.Text = ""
        txtOtherUOM.Text = ""
        txtOtherUOM.Enabled = False
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()
    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        Dim str As String = "select count(*) from TSPL_MF_RESOURCE_MASTER where RESOURCE_CODE ='" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtCode.MyReadOnly = False
            'txtCode.Value = ""
            '' common.clsCommon.MyMessageBoxShow("Value doesn't exist ")
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then


            ' Dim qry As String = "select RESOURCE_CODE as [Code], STATUS AS [Status], DESCRIPTION as [Description], RESOURCE_TYPE as [Type], UNIT_CODE as [Unit Code], COST as [Cost], COMMENTS as [COMMENTS]  from TSPL_MF_RESOURCE_MASTER "
            'txtCode.Value = clsCommon.ShowSelectForm("RESOURCE_MASTER", qry, "Code", "", txtCode.Value, "Code", isButtonClicked)
            txtCode.Value = clsResourceMaster.getFinder("", txtCode.Value, isButtonClicked)
            If txtCode.Value <> "" Then
                LoadData(txtCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub frmResourceMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub MenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "RESOURCE_CODE", "Description", "Status", "Type", "UOM", "Uom_Other", "Cost", "Comments", "LAST_MAIN", "MAIN_BY") Then
            '  Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsResourceMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("RESOURCE_CODE can not be blank or incorrect.")
                    End If
                    obj.RESOURCE_CODE = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells(1).Value)
                    If strName.Length > 200 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Description can not be blank or incorrect.")
                    End If
                    obj.DESCRIPTION = strName

                    Dim strDes As String = clsCommon.myCstr(grow.Cells(2).Value)
                    If strDes.Length > 15 Then
                        Throw New Exception("Status can not be blank or incorrect.")
                    End If
                    obj.STATUS = strDes

                    strDes = clsCommon.myCstr(grow.Cells(3).Value)
                    If strDes.Length > 12 Then
                        Throw New Exception("Type can not be blank or incorrect.")
                    End If
                    obj.RESOURCE_TYPE = strDes

                    strDes = clsCommon.myCstr(grow.Cells(4).Value)
                    If strDes.Length > 12 Then
                        Throw New Exception("UOM can not be blank or incorrect.")
                    End If
                    obj.UNIT_CODE = strDes

                    strDes = clsCommon.myCstr(grow.Cells(5).Value)
                    If strDes.Length > 50 Then
                        Throw New Exception("Uom_Other can not be blank or incorrect.")
                    End If
                    obj.UNIT_CODE_OTHER = strDes

                    Dim strCost As Double = clsCommon.myCdbl(grow.Cells(6).Value)
                    If strCost < 0 Then
                        Throw New Exception("Cost can not be blank or incorrect.")
                    End If
                    obj.COST = strCost

                    strDes = clsCommon.myCstr(grow.Cells(7).Value)
                    If strDes.Length > 200 Then
                        Throw New Exception("Comments can not be blank or incorrect.")
                    End If
                    obj.COMMENTS = strDes
                    
                    strDes = clsCommon.myCstr(grow.Cells(8).Value)
                    If strDes.Length < 0 Then
                        Throw New Exception("LAST_MAIN can not be blank or incorrect.")
                    End If
                    obj.Modified_Date = strDes

                    strDes = clsCommon.myCstr(grow.Cells(9).Value)
                    If strDes.Length > 12 Then
                        Throw New Exception("MAIN_BY can not be blank or incorrect.")
                    End If
                    obj.Modified_By = strDes

                    obj.SaveData(obj, True, True)
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub MenuItemExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemExport.Click
        Dim str As String
        str = "select RESOURCE_CODE, DESCRIPTION as [Description], STATUS as [Status], RESOURCE_TYPE as [Type], UNIT_CODE as [UOM] , UNIT_CODE_OTHER as [Uom_Other], COST as [Cost],COMMENTS as [Comments],  Modified_Date as [LAST_MAIN], Modified_By as [MAIN_BY] from TSPL_MF_RESOURCE_MASTER"
        transportSql.ExporttoExcel(str, Me)
    End Sub

    Private Sub MenuItemClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemClose.Click
        funClose()
    End Sub

    Private Sub cboUOM_Enter(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cboUOM.Enter
        Dim Selected_val As String = String.Empty

        If cboUOM.SelectedIndex > -1 Then
            Selected_val = cboUOM.SelectedValue
        End If

        cboUOM.DataSource = GetCboUOMDataTable()
        cboUOM.ValueMember = "RESOURCE_CODE"
        cboUOM.DisplayMember = "Value"

        If Selected_val.Length > 0 Then
            cboUOM.SelectedValue = Selected_val
        End If
    End Sub

    Private Sub cboStatus_Enter(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cboStatus.Enter
        Dim Selected_val As String = String.Empty

        If cboStatus.SelectedIndex > -1 Then
            Selected_val = cboStatus.SelectedValue
        End If

        cboStatus.DataSource = GetCboStatusDataTable()
        cboStatus.ValueMember = "RESOURCE_CODE"
        cboStatus.DisplayMember = "Value"
        If Selected_val.Length > 0 Then
            cboStatus.SelectedValue = Selected_val
        End If

    End Sub

    Private Sub cboType_Enter(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cboType.Enter
        Dim Selected_val As String = String.Empty

        If cboType.SelectedIndex > -1 Then
            Selected_val = cboType.SelectedValue
        End If

        cboType.DataSource = GetCboTypeDataTable()
        cboType.ValueMember = "RESOURCE_CODE"
        cboType.DisplayMember = "Value"
        If Selected_val.Length > 0 Then
            cboType.SelectedValue = Selected_val
        End If

    End Sub

    Private Function GetCboStatusDataTable() As DataTable
        Dim dt As New DataTable
        dt.Columns.Add("RESOURCE_CODE", GetType(String))
        dt.Columns.Add("Value", GetType(String))

        Dim dr As DataRow
        dr = dt.NewRow()
        dr("RESOURCE_CODE") = "Active"
        dr("Value") = "Active"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("RESOURCE_CODE") = "Inactive"
        dr("Value") = "Inactive"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("RESOURCE_CODE") = "Discontinued"
        dr("Value") = "Discontinued"
        dt.Rows.Add(dr)

        dt.AcceptChanges()
        Return dt
    End Function

    Private Function GetCboUOMDataTable() As DataTable
        Dim dt As New DataTable
        dt.Columns.Add("RESOURCE_CODE", GetType(String))
        dt.Columns.Add("Value", GetType(String))

        Dim dr As DataRow
        dr = dt.NewRow()
        dr("RESOURCE_CODE") = "Hour"
        dr("Value") = "Hour"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("RESOURCE_CODE") = "Minute"
        dr("Value") = "Minute"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("RESOURCE_CODE") = "Others"
        dr("Value") = "Others"
        dt.Rows.Add(dr)

        dt.AcceptChanges()
        Return dt
    End Function

    Private Function GetCboTypeDataTable() As DataTable
        Dim dt As New DataTable
        dt.Columns.Add("RESOURCE_CODE", GetType(String))
        dt.Columns.Add("Value", GetType(String))

        Dim dr As DataRow
        dr = dt.NewRow()
        dr("RESOURCE_CODE") = "Setup Labor"
        dr("Value") = "Setup Labor"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("RESOURCE_CODE") = "Run Labor"
        dr("Value") = "Run Labor"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("RESOURCE_CODE") = "Overhead"
        dr("Value") = "Overhead"
        dt.Rows.Add(dr)

        dt.AcceptChanges()
        Return dt
    End Function

    Private Sub cboUOM_SelectedValueChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cboUOM.SelectedValueChanged
        If (clsCommon.CompairString(clsCommon.myCstr(cboType.SelectedValue), "Setup Labor") = CompairStringResult.Equal) Or (clsCommon.CompairString(clsCommon.myCstr(cboType.SelectedValue), "Run Labor") = CompairStringResult.Equal) Then
            If clsCommon.CompairString(clsCommon.myCstr(cboUOM.SelectedValue), "Others") = CompairStringResult.Equal Then
                clsCommon.MyMessageBoxShow("Invalid Input. For resource with setup labor or run labor types, the UOM must be either per hour or per minute.")
                cboUOM.SelectedText = ""
                cboUOM.SelectedIndex = -1
                txtOtherUOM.Enabled = False
                txtOtherUOM.Text = ""
            End If
        End If
        If (clsCommon.CompairString(clsCommon.myCstr(cboUOM.SelectedValue), "Others") = CompairStringResult.Equal AndAlso clsCommon.CompairString(clsCommon.myCstr(cboType.SelectedValue), "Overhead") = CompairStringResult.Equal) Then
            txtOtherUOM.Enabled = True
            txtOtherUOM.Text = ""
        Else
            txtOtherUOM.Enabled = False
            txtOtherUOM.Text = clsCommon.myCstr(cboUOM.SelectedValue)
        End If
    End Sub

End Class
