Imports common
Imports System.Data.SqlClient

Public Class clsDivertedContractor
#Region "veriables"
    Public CONTRACTOR_CODE As String = Nothing
    Public description As String = Nothing
    Public IS_DIVERTED As Integer = 0
    Public CompCode As String = Nothing
    Public CompDesc As String = Nothing
#End Region
    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_DIVERTED_CONTRACTOR_MASTER.CONTRACTOR_CODE as [Code] ,TSPL_DIVERTED_CONTRACTOR_MASTER.DESCRIPTION as [Description] ,TSPL_DIVERTED_CONTRACTOR_MASTER.IS_DIVERTED as [Is Diverted] ,TSPL_DIVERTED_CONTRACTOR_MASTER.Created_By as [Created By] ,TSPL_DIVERTED_CONTRACTOR_MASTER.Created_Date as [Created Date] ,TSPL_DIVERTED_CONTRACTOR_MASTER.Modified_By as [Modified By] ,TSPL_DIVERTED_CONTRACTOR_MASTER.Modified_Date as [Modified Date]  From TSPL_DIVERTED_CONTRACTOR_MASTER   "
        str = clsCommon.ShowSelectForm("DiverContractMST", qry, "Code", whrcls, curcode, "Code", isButtonClicked, "TSPL_DIVERTED_CONTRACTOR_MASTER.Created_Date")
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    '' This Code For Retriving Data from TSPL_DIVERTED_CONTRACTOR_MASTER


    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsDivertedContractor
        Dim obj As clsDivertedContractor = Nothing
        Dim qst As String = "select  TSPL_DIVERTED_CONTRACTOR_MASTER.CONTRACTOR_CODE , TSPL_DIVERTED_CONTRACTOR_MASTER.description , TSPL_DIVERTED_CONTRACTOR_MASTER.IS_DIVERTED  from  TSPL_DIVERTED_CONTRACTOR_MASTER where 2=2 "
        Select Case NavType
            Case NavigatorType.Current
                qst += " and  CONTRACTOR_CODE ='" & strCode & "' "
            Case NavigatorType.Next
                qst += " and  CONTRACTOR_CODE in (select min(t.CONTRACTOR_CODE ) from TSPL_DIVERTED_CONTRACTOR_MASTER  as t where t.CONTRACTOR_CODE  >'" + strCode + "')"
            Case NavigatorType.First
                qst += " and  CONTRACTOR_CODE in (select min(t.CONTRACTOR_CODE ) from TSPL_DIVERTED_CONTRACTOR_MASTER  as t )"
            Case NavigatorType.Last
                qst += " and  CONTRACTOR_CODE in (select max(t.CONTRACTOR_CODE ) from TSPL_DIVERTED_CONTRACTOR_MASTER  as t )"
            Case NavigatorType.Previous
                qst += " and  CONTRACTOR_CODE in (select max(t.CONTRACTOR_CODE ) from TSPL_DIVERTED_CONTRACTOR_MASTER  as t where t.CONTRACTOR_CODE  <'" + strCode + "')"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            obj = New clsDivertedContractor
            obj.CONTRACTOR_CODE = clsCommon.myCstr(dt.Rows(0)("CONTRACTOR_CODE"))
            obj.description = clsCommon.myCstr(dt.Rows(0)("description"))
            obj.IS_DIVERTED = clsCommon.myCdbl(dt.Rows(0)("IS_DIVERTED"))
        End If
        Return obj
    End Function
    '' For Delete of Data in TSPL_DIVERTED_CONTRACTOR_MASTER
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim qry As String = "Delete from TSPL_DIVERTED_CONTRACTOR_MASTER where CONTRACTOR_CODE='" + strCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)
    End Function
    '' For Save Data in TSPL_DIVERTED_CONTRACTOR_MASTER
    Public Function SaveData(ByVal obj As clsDivertedContractor, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Description", obj.description)
            clsCommon.AddColumnsForChange(coll, "IS_DIVERTED", obj.IS_DIVERTED)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
            clsCommon.AddColumnsForChange(coll, "comp_code", objCommonVar.CurrentCompanyCode)
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_DIVERTED_CONTRACTOR_MASTER where CONTRACTOR_CODE='" & obj.CONTRACTOR_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.CONTRACTOR_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.DivertedContractor, "", "")
                        If clsCommon.myLen(obj.CONTRACTOR_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "CONTRACTOR_CODE", obj.CONTRACTOR_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))

                Dim qry As String = "SELECT Count(*) FROM TSPL_DIVERTED_CONTRACTOR_MASTER where CONTRACTOR_CODE = '" & obj.CONTRACTOR_CODE & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry, trans)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_DIVERTED_CONTRACTOR_MASTER", OMInsertOrUpdate.Insert, "", trans)
                Else
                    Throw New Exception("This Code Is Already Exist")
                End If
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_DIVERTED_CONTRACTOR_MASTER ", OMInsertOrUpdate.Update, " CONTRACTOR_CODE='" + obj.CONTRACTOR_CODE + "'", trans)
            End If
        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select CONTRACTOR_CODE from TSPL_DIVERTED_CONTRACTOR_MASTER where CONTRACTOR_CODE ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
End Class
