Imports common
Imports System.Data.SqlClient

Public Class clsSupplierMaster
#Region "veriables"
    Public SUPPLIER_CODE As String = Nothing
    Public description As String = Nothing
    Public Vendor_Code As String = Nothing
    Public CompCode As String = Nothing
    Public CompDesc As String = Nothing
#End Region
    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_SUPPLIER_MASTER.SUPPLIER_CODE as [Code] ,TSPL_SUPPLIER_MASTER.DESCRIPTION as [Description] ,TSPL_SUPPLIER_MASTER.Vendor_Code as [Vendor Code] ,TSPL_SUPPLIER_MASTER.Created_By as [Created By] ,TSPL_SUPPLIER_MASTER.Created_Date as [Created Date] ,TSPL_SUPPLIER_MASTER.Modified_By as [Modified By] ,TSPL_SUPPLIER_MASTER.Modified_Date as [Modified Date]  From TSPL_SUPPLIER_MASTER   "
        str = clsCommon.ShowSelectForm("SupplierMst", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    Public Shared Function getSupplierName(ByVal strCode As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim strDesc As String = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select TSPL_SUPPLIER_MASTER.DESCRIPTION from TSPL_SUPPLIER_MASTER where SUPPLIER_CODE='" & strCode & "'", trans))
        Return strDesc
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    '' This Code For Retriving Data from TSPL_SUPPLIER_MASTER


    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsSupplierMaster
        Dim obj As clsSupplierMaster = Nothing
        Dim qst As String = "select TSPL_SUPPLIER_MASTER.SUPPLIER_CODE , TSPL_SUPPLIER_MASTER.description , TSPL_SUPPLIER_MASTER.Vendor_Code  from  TSPL_SUPPLIER_MASTER where 2=2  "
        Select Case NavType
            Case NavigatorType.Current
                qst += " and  SUPPLIER_CODE ='" & strCode & "' "
            Case NavigatorType.Next
                qst += " and  SUPPLIER_CODE in (select min(t.SUPPLIER_CODE ) from TSPL_SUPPLIER_MASTER  as t where t.SUPPLIER_CODE  >'" + strCode + "')"
            Case NavigatorType.First
                qst += " and  SUPPLIER_CODE in (select min(t.SUPPLIER_CODE ) from TSPL_SUPPLIER_MASTER  as t )"
            Case NavigatorType.Last
                qst += " and  SUPPLIER_CODE in (select max(t.SUPPLIER_CODE ) from TSPL_SUPPLIER_MASTER  as t )"
            Case NavigatorType.Previous
                qst += " and  SUPPLIER_CODE in (select max(t.SUPPLIER_CODE ) from TSPL_SUPPLIER_MASTER  as t where t.SUPPLIER_CODE  <'" + strCode + "')"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            obj = New clsSupplierMaster
            obj.SUPPLIER_CODE = clsCommon.myCstr(dt.Rows(0)("SUPPLIER_CODE"))
            obj.description = clsCommon.myCstr(dt.Rows(0)("description"))
            obj.Vendor_Code = clsCommon.myCstr(dt.Rows(0)("Vendor_Code"))
           
        End If
        Return obj
    End Function
    '' For Delete of Data in TSPL_SUPPLIER_MASTER
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim qry As String = "Delete from TSPL_SUPPLIER_MASTER where SUPPLIER_CODE='" + strCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)
    End Function
    '' For Save Data in TSPL_SUPPLIER_MASTER
    Public Function SaveData(ByVal obj As clsSupplierMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "Vendor_Code", obj.Vendor_Code)
            clsCommon.AddColumnsForChange(coll, "Description", obj.description)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
            clsCommon.AddColumnsForChange(coll, "comp_code", objCommonVar.CurrentCompanyCode)
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_SUPPLIER_MASTER where SUPPLIER_CODE='" & obj.SUPPLIER_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.SUPPLIER_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.SupplierMaster, "", "")
                        If clsCommon.myLen(obj.SUPPLIER_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "SUPPLIER_CODE", obj.SUPPLIER_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
                Dim qry As String = "SELECT Count(*) FROM TSPL_SUPPLIER_MASTER where SUPPLIER_CODE = '" & obj.SUPPLIER_CODE & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry, trans)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_SUPPLIER_MASTER", OMInsertOrUpdate.Insert, "", trans)
                Else
                    Throw New Exception("This Code Is Already Exist")
                End If
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_SUPPLIER_MASTER ", OMInsertOrUpdate.Update, " SUPPLIER_CODE='" + obj.SUPPLIER_CODE + "'", trans)
            End If
        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select SUPPLIER_CODE from TSPL_SUPPLIER_MASTER where SUPPLIER_CODE ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
End Class
