Imports common
Imports System.Data.SqlClient
Imports System.Windows.Forms

Public Class clsTankerMasterSaleHead

#Region "Variables"
    Public Tanker_Code As String = Nothing
    Public Tanker_No As String = Nothing
    Public Tare_Weight As Double = 0
    Public No_Of_Chamber As Integer = 0
    Public isNewEntry As Boolean = False
    Public Arr As List(Of clsTankerMasterSaleDetail) = Nothing
    Public ArrDriver As List(Of clsTankerMasterSaleDriverDetail) = Nothing
#End Region
    
    Public Function SaveData(ByVal obj As clsTankerMasterSaleHead) As Boolean
        Dim issaved As Boolean = True
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            Dim qry As String = "delete from TSPL_TANKER_MASTER_SALE_DETAIL where Tanker_Code='" + obj.Tanker_Code + "'"
            issaved = issaved AndAlso clsDBFuncationality.ExecuteNonQuery(qry, trans)

            qry = "delete from TSPL_TANKER_MASTER_SALE_DRIVER_DETAIL where Tanker_Code='" + obj.Tanker_Code + "'"
            issaved = issaved AndAlso clsDBFuncationality.ExecuteNonQuery(qry, trans)

            Dim dt As Date = clsCommon.GETSERVERDATE(trans, "dd/MMM/yyyy")

            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Tanker_No", obj.Tanker_No)
            clsCommon.AddColumnsForChange(coll, "No_Of_Chamber", obj.No_Of_Chamber)
            clsCommon.AddColumnsForChange(coll, "Tare_Weight", obj.Tare_Weight)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode, True)
            If obj.isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_TANKER_MASTER_SALE where Tanker_Code='" & obj.Tanker_Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Tanker_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.TankerMasterSale, "", "")
                        If clsCommon.myLen(obj.Tanker_Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Tanker_Code", obj.Tanker_Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                issaved = issaved And clsCommonFunctionality.UpdateDataTable(coll, "TSPL_TANKER_MASTER_SALE", OMInsertOrUpdate.Insert, "", trans)
            Else
                issaved = issaved And clsCommonFunctionality.UpdateDataTable(coll, "TSPL_TANKER_MASTER_SALE", OMInsertOrUpdate.Update, "TSPL_TANKER_MASTER_SALE.Tanker_Code='" + obj.Tanker_Code + "'", trans)
            End If
            issaved = issaved And clsTankerMasterSaleDetail.SaveData(obj.Tanker_Code, obj.Arr, trans)
            issaved = issaved And clsTankerMasterSaleDriverDetail.SaveData(obj.Tanker_Code, obj.ArrDriver, trans)
            If issaved Then
                trans.Commit()
            End If
        Catch ex As Exception
            trans.Rollback()
            Throw New Exception(ex.Message)
        End Try
        Return issaved
    End Function

    Public Shared Function GetData(ByVal strTankerCode As String, ByVal NavType As NavigatorType) As clsTankerMasterSaleHead
        Dim obj As clsTankerMasterSaleHead = Nothing
        Dim Qry As String = "Select * from TSPL_TANKER_MASTER_SALE where 2=2"
        Dim whrClas As String = ""

        Select Case NavType
            Case NavigatorType.First
                Qry += " and TSPL_TANKER_MASTER_SALE.TANKER_CODE = (select MIN(TANKER_CODE) from TSPL_TANKER_MASTER_SALE where 1=1 " + whrClas + ")"
            Case NavigatorType.Last
                Qry += " and TSPL_TANKER_MASTER_SALE.TANKER_CODE = (select Max(TANKER_CODE) from TSPL_TANKER_MASTER_SALE where 1=1 " + whrClas + ")"
            Case NavigatorType.Next
                Qry += " and TSPL_TANKER_MASTER_SALE.TANKER_CODE = (select Min(TANKER_CODE) from TSPL_TANKER_MASTER_SALE where TANKER_CODE>'" + strTankerCode + "' " + whrClas + ")"
            Case NavigatorType.Previous
                Qry += " and TSPL_TANKER_MASTER_SALE.TANKER_CODE = (select Max(TANKER_CODE) from TSPL_TANKER_MASTER_SALE where TANKER_CODE<'" + strTankerCode + "' " + whrClas + ")"
            Case NavigatorType.Current
                Qry += " and TSPL_TANKER_MASTER_SALE.TANKER_CODE = '" + strTankerCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(Qry)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsTankerMasterSaleHead
            obj.Tanker_Code = clsCommon.myCstr(dt.Rows(0)("Tanker_Code"))
            obj.Tanker_No = clsCommon.myCstr(dt.Rows(0)("Tanker_No"))
            obj.No_Of_Chamber = clsCommon.myCdbl(dt.Rows(0)("No_Of_Chamber"))
            obj.Tare_Weight = clsCommon.myCdbl(dt.Rows(0)("Tare_Weight"))

            Qry = "Select * from TSPL_TANKER_MASTER_SALE_DETAIL where TSPL_TANKER_MASTER_SALE_DETAIL.TANKER_CODE='" & obj.Tanker_Code & "' order by TSPL_TANKER_MASTER_SALE_DETAIL.Line_No asc "
            dt = New DataTable()
            dt = clsDBFuncationality.GetDataTable(Qry)
            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
                obj.Arr = New List(Of clsTankerMasterSaleDetail)
                Dim objTr As clsTankerMasterSaleDetail
                For Each dr As DataRow In dt.Rows
                    objTr = New clsTankerMasterSaleDetail
                    objTr.Line_No = clsCommon.myCdbl(clsCommon.myCdbl(dr("Line_No")))
                    objTr.Chamber_Desc = clsCommon.myCstr(clsCommon.myCstr(dr("Chamber_Desc")))
                    objTr.Chamber_Capacity = clsCommon.myCstr(clsCommon.myCstr(dr("Chamber_Capacity")))
                    objTr.Capacity_Uom = clsCommon.myCstr(clsCommon.myCstr(dr("Capacity_Uom")))
                    obj.Arr.Add(objTr)
                Next
            End If
        End If

        Return obj
    End Function

    Public Shared Function getTankerFinderBasedonVendor(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim Qry As String = "select  TSPL_TANKER_MASTER_SALE.TANKER_CODE as Code,TSPL_TANKER_MASTER_SALE.TANKER_NO as [Tanker No],NO_OF_CHAMBER as [No Of Chamber],TSPL_CONTRACT_TANKER_VENDOR_DETAIL.Vendor_Code as [Vendor Code],TSPL_VENDOR_MASTER.Vendor_Name as [Vendor Name]  from TSPL_TANKER_MASTER_SALE left outer join TSPL_CONTRACT_TANKER_VENDOR_DETAIL on TSPL_TANKER_MASTER_SALE.TANKER_CODE=TSPL_CONTRACT_TANKER_VENDOR_DETAIL.TANKER_CODE left outer join TSPL_VENDOR_MASTER ON TSPL_CONTRACT_TANKER_VENDOR_DETAIL.Vendor_Code=TSPL_VENDOR_MASTER.Vendor_Code "
        str = clsCommon.ShowSelectForm("ContracttabkerMST", Qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function

    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TANKER_CODE as Code,TANKER_NO as [Tanker No],Tare_Weight as [Tare Weight],NO_OF_CHAMBER as [No Of Chamber]  from TSPL_TANKER_MASTER_SALE  "
        str = clsCommon.ShowSelectForm("ContracttabkerMST", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function

    Public Shared Function getTankerNo(ByVal strTankerCode As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim strDesc As String = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select TSPL_TANKER_MASTER_SALE.TANKER_NO from TSPL_TANKER_MASTER_SALE where TANKER_CODE='" & strTankerCode & "'", trans))
        Return strDesc
    End Function

    Public Shared Function DeleteData(ByVal strTankerCode As String) As Boolean
        Dim isSaved As Boolean = False
        If (clsCommon.myLen(strTankerCode) <= 0) Then
            Throw New Exception("Tanker Code not found to Delete")
        End If
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()

        Dim qry As String = "delete from TSPL_TANKER_MASTER_SALE_DRIVER_DETAIL where TANKER_CODE='" + strTankerCode + "'"
        isSaved = clsDBFuncationality.ExecuteNonQuery(qry, trans)

        qry = "delete from TSPL_TANKER_MASTER_SALE_DETAIL where TANKER_CODE='" + strTankerCode + "'"
        isSaved = clsDBFuncationality.ExecuteNonQuery(qry, trans)

        qry = "delete from TSPL_TANKER_MASTER_SALE where TANKER_CODE='" + strTankerCode + "'"
        isSaved = isSaved AndAlso clsDBFuncationality.ExecuteNonQuery(qry, trans)

        If (isSaved) Then
            trans.Commit()
        Else
            trans.Rollback()
        End If

        Return isSaved
    End Function

End Class

Public Class clsTankerMasterSaleDetail

#Region "Variables"
    Public Line_No As Integer = Nothing
    Public Chamber_Desc As String = Nothing
    Public Chamber_Capacity As Double = 0
    Public Capacity_Uom As String = Nothing
#End Region

    Public Shared Function SaveData(ByVal strTankerCode As String, ByVal arr As List(Of clsTankerMasterSaleDetail), ByVal trans As SqlTransaction) As Boolean
        Dim issaved As Boolean = True
        If (arr IsNot Nothing AndAlso arr.Count > 0) Then
            For Each obj As clsTankerMasterSaleDetail In arr
                Dim coll As New Hashtable()
                clsCommon.AddColumnsForChange(coll, "Tanker_Code", strTankerCode)
                clsCommon.AddColumnsForChange(coll, "Line_No", obj.Line_No)
                clsCommon.AddColumnsForChange(coll, "Chamber_Desc", obj.Chamber_Desc)
                clsCommon.AddColumnsForChange(coll, "Chamber_Capacity", obj.Chamber_Capacity)
                clsCommon.AddColumnsForChange(coll, "Capacity_Uom", obj.Capacity_Uom, True)
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_TANKER_MASTER_SALE_DETAIL", OMInsertOrUpdate.Insert, "", trans)
            Next
        End If
        Return issaved
    End Function

End Class

Public Class clsTankerMasterSaleDriverDetail

#Region "Variables"
    Public Driver_Code As String = Nothing
#End Region

    Public Shared Function SaveData(ByVal strTankerCode As String, ByVal arr As List(Of clsTankerMasterSaleDriverDetail), ByVal trans As SqlTransaction) As Boolean
        Dim issaved As Boolean = True
        If (arr IsNot Nothing AndAlso arr.Count > 0) Then
            For Each obj As clsTankerMasterSaleDriverDetail In arr
                Dim coll As New Hashtable()
                clsCommon.AddColumnsForChange(coll, "TANKER_CODE", strTankerCode)
                clsCommon.AddColumnsForChange(coll, "Driver_Code", obj.Driver_Code, True)
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_TANKER_MASTER_SALE_DRIVER_DETAIL", OMInsertOrUpdate.Insert, "", trans)
            Next
        End If
        Return issaved
    End Function

End Class
