Imports System.Data.SqlClient
Public Class clsMISItemMaster
#Region "Variables"
    Public Code As String
    Public Name As String
    Public GroupCode As String
    Public ItemUOM As String
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal itemcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select Item_Code as [Code],Item_Name as [ Item Name],Group_Code as [Group Code],Item_UOM as [UOM],Created_By as [Created By],Created_Date as [Created Date],Modify_By as [Modify By],Modify_Date as [Modify Date] from TSPL_MIS_ITEM_MASTER "
        str = clsCommon.ShowSelectForm("ITEMGPFND", qry, "Code", whrcls, itemcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsMISItemMaster
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isSaved As Boolean

        Try
            isSaved = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_MIS_ITEM_MASTER where Item_Code ='" + strCode + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry)


        Catch ex As Exception

            Throw New Exception(ex.Message.ToString())
        End Try
        Return isSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsMISItemMaster
        Dim obj As clsMISItemMaster = Nothing
        Dim qry As String = "select Item_Code, Item_Name, Group_Code,Item_UOM from TSPL_MIS_ITEM_MASTER where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and Item_Code = (select MIN(Item_Code) from TSPL_MIS_ITEM_MASTER)"
            Case NavigatorType.Last
                qry += " and Item_Code = (select Max(Item_Code) from TSPL_MIS_ITEM_MASTER)"
            Case NavigatorType.Next
                qry += " and Item_Code = (select Min(Item_Code) from TSPL_MIS_ITEM_MASTER where  Item_Code>'" + strCode + "')"
            Case NavigatorType.Previous
                qry += " and Item_Code = (select Max(Item_Code) from TSPL_MIS_ITEM_MASTER where Item_Code<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and Item_Code = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsMISItemMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Item_Code"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("Item_Name"))
            obj.GroupCode = clsCommon.myCstr(dt.Rows(0)("Group_Code"))
            obj.ItemUOM = clsCommon.myCstr(dt.Rows(0)("Item_UOM"))
        End If
        Return obj


    End Function

    Public Shared Function GetName(ByVal strCode As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "select Item_Name from TSPL_MIS_ITEM_MASTER where Item_Code='" + strCode + "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
    End Function

    Public Function SaveData(ByVal obj As clsMISItemMaster, ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Item_Name", obj.Name)
            clsCommon.AddColumnsForChange(coll, "Group_Code", obj.GroupCode)
            clsCommon.AddColumnsForChange(coll, "Item_UOM", obj.ItemUOM)
            clsCommon.AddColumnsForChange(coll, "Modify_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modify_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_MIS_ITEM_MASTER where Item_Code='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.MISItemMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Item_Code", obj.Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy hh:mm tt"))
                Dim qry As String = "SELECT Count(*) FROM TSPL_MIS_ITEM_MASTER where Item_Code= '" & obj.Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_MIS_ITEM_MASTER", OMInsertOrUpdate.Insert, "")
                Else
                    Throw New Exception("This Code Is Already Exist")
                End If

            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_MIS_ITEM_MASTER", OMInsertOrUpdate.Update, "Item_Code='" + obj.Code + "'")
            End If

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function
    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select Item_Code from TSPL_MIS_ITEM_MASTER where Item_Code ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
End Class
