Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports Telerik.WinControls.Data
Imports System.Text.RegularExpressions
Imports common
'''' <summary>
'''' ''''''''''''''''''''''''TicketNo='BM00000001528''''''''''''''''''''''''''''''''''''''''
'''' </summary>
'''' <remarks></remarks>

Public Class frmCostType
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String
#Region "Functions"

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmCostTypes)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        btnsave.Visible = MyBase.isModifyFlag
        'btnPost.Visible = MyBase.isPostFlag
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Dim obj As clsCostType = clsCostType.GetData(strCode, NavTyep)
        If obj IsNot Nothing Then
            isNewEntry = False
            txtCode.Value = obj.COST_TYPE_CODE
            txtDesc.Text = obj.DESCRIPTION
            Me.cboCostClass.SelectedValue = obj.COST_CLASS
            txtCode.MyReadOnly = True
        End If
    End Sub
    Sub SaveData()
        Dim trans As SqlTransaction = Nothing
        Try
            If AllowToSave() Then
                trans = clsDBFuncationality.GetTransactin()
                Dim obj As New clsCostType()
                obj.COST_TYPE_CODE = txtCode.Value
                obj.DESCRIPTION = txtDesc.Text
                obj.COST_CLASS = Me.cboCostClass.SelectedValue
                Dim qry As Integer = clsDBFuncationality.getSingleValue("select count(COST_TYPE_CODE) from TSPL_PJC_COST_TYPE where COST_TYPE_CODE='" + obj.COST_TYPE_CODE + "'", trans)
                If (qry = 0) Then
                    isNewEntry = True
                Else
                    isNewEntry = False
                End If
                If (clsCostType.SaveData(obj, isNewEntry, trans)) Then
                    trans.Commit()
                    clsCommon.MyMessageBoxShow("Data saved Successfully", Me.Text)
                    LoadData(obj.COST_TYPE_CODE, NavigatorType.Current)

                End If
            End If
        Catch ex As Exception
            trans.Rollback()
            clsCommon.MyMessageBoxShow(ex.Message, Me.Text)
        End Try
    End Sub

    Private Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(clsCommon.myCstr(txtCode.Value)) <= 0 Then
                txtCode.Focus()
                clsCommon.MyMessageBoxShow("Please Fill  Code")
                Return False
            End If
        End If
        If clsCommon.myLen(clsCommon.myCstr(txtDesc.Text)) <= 0 Then
            txtDesc.Focus()
            clsCommon.MyMessageBoxShow("Please Fill  Description")
            Return False
        End If
        Return True
    End Function
    Private Sub DeleteData()
        Try
            If clsCommon.myLen(txtCode.Value) <= 0 Then
                Throw New Exception("  Code not found to delete")

            End If
            If clsCommon.MyMessageBoxShow("Do you want to delete  Code '" + txtCode.Value + "'", Me.Text, MessageBoxButtons.YesNo) = System.Windows.Forms.DialogResult.Yes Then

                Dim qry As String = "delete from TSPL_PJC_COST_TYPE where COST_TYPE_CODE='" + txtCode.Value + "'"
                clsDBFuncationality.ExecuteNonQuery(qry)
                clsCommon.MyMessageBoxShow("Successfully Deleted", Me.Text)
                AddNew()
            End If
        Catch ex As Exception
            If (clsCommon.CompairString(clsCommon.myCstr(ex.Message), "Cost Code not found to delete") <> CompairStringResult.Equal) Then
                clsCommon.MyMessageBoxShow("Current Cost Code is in use")

            Else
                clsCommon.MyMessageBoxShow(ex.Message)
            End If
        End Try
    End Sub
    Sub AddNew()
        txtCode.Value = ""
        'txtDesc.Text = ""
        txtCode.MyReadOnly = False
        txtDesc.Text = ""
        Me.cboCostClass.DataSource = clsCostType.GetCostTypeTable
        Me.cboCostClass.DisplayMember = "Name"
        Me.cboCostClass.ValueMember = "Code"
    End Sub

#End Region
#Region "Events"

    Private Sub btnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click
        SaveData()
    End Sub

    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub

    Private Sub btnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        Me.Close()
    End Sub

    Private Sub btnnew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnnew.Click
        AddNew()
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        LoadData(txtCode.Value, NavType)
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = "select COST_TYPE_CODE as Code,DESCRIPTION as Name from  TSPL_PJC_COST_TYPE"
            'txtCode.Value = clsCommon.ShowSelectForm("TSPL_PJC_COST_TYPE", qry, "Code", "", txtCode.Value, "", isButtonClicked)
            txtCode.Value = clsCostType.getFinder("", txtCode.Value, isButtonClicked)
            LoadData(txtCode.Value, NavigatorType.Current)
        End If
    End Sub
    Private Sub frmCostType_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update ")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D Delete ")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnnew, "Press Alt+N Adding New ")
        ' globalFunc.mandatoryText(fnddesig.txtValue, txtdes)
        AddNew()
    End Sub

    Private Sub frmCostType_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
            'ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            '    PostData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            AddNew()
        End If
    End Sub
#End Region

    '' Anubhooti 19-June-2014
    Private Sub rmExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmExport.Click
        Dim str As String
        str = "Select COST_TYPE_CODE As [COST TYPE CODE],DESCRIPTION As [DESCRIPTION],COST_CLASS As [COST CLASS] From TSPL_PJC_COST_TYPE"
        transportSql.ExporttoExcel(str, Me)
    End Sub
    '' Anubhooti 19-June-2014
    Private Sub rmImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmImport.Click
        Dim trans As SqlTransaction = Nothing
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "COST TYPE CODE", "DESCRIPTION", "COST CLASS") Then
            Dim linno As Integer = 0
            Try
                'connectSql.OpenConnection()
                clsCommon.ProgressBarShow()
                trans = clsDBFuncationality.GetTransactin()
                For Each grow As GridViewRowInfo In gv.Rows

                    Dim obj As New clsCostType()

                    linno += 1
                    Dim strcode As String = clsCommon.myCstr(grow.Cells("COST TYPE CODE").Value)
                    If (String.IsNullOrEmpty(strcode)) Or clsCommon.myLen(strcode) > 30 Then
                        Throw New Exception("Length of Cost Type Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.COST_TYPE_CODE = strcode

                    Dim strname As String = clsCommon.myCstr(grow.Cells("DESCRIPTION").Value)
                    'If (String.IsNullOrEmpty(strname)) Or clsCommon.myLen(strname) > 50 Then
                    '    Throw New Exception("Length of Description should be max. 50 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    'End If
                    obj.DESCRIPTION = strname

                    Dim strType As String = clsCommon.myCstr(grow.Cells("COST CLASS").Value)
                    If (String.IsNullOrEmpty(strType)) Or clsCommon.myLen(strType) > 30 Then
                        Throw New Exception("Length of Cost Class should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If

                    obj.COST_CLASS = strType
                    If clsCommon.myLen(strType) = 0 Then
                        Throw New Exception("Cost Class can not be left blank")
                    ElseIf clsCommon.CompairString(strType, "Labour") = CompairStringResult.Equal Or clsCommon.CompairString(strType, "Material") = CompairStringResult.Equal Or clsCommon.CompairString(strType, "Equipment") = CompairStringResult.Equal Or clsCommon.CompairString(strType, "SubContractor") = CompairStringResult.Equal Or clsCommon.CompairString(strType, "Overhead") = CompairStringResult.Equal Or clsCommon.CompairString(strType, "Miscellaneous") = CompairStringResult.Equal Then
                    Else
                        Throw New Exception("Cost Class should be amoung 'Labour','Material','Equipment','SubContractor','Overhead','Miscellaneous' At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    If clsCommon.myLen(strcode) > 0 AndAlso clsDBFuncationality.getSingleValue("Select COUNT(*) From TSPL_PJC_COST_TYPE  Where COST_TYPE_CODE = '" & strcode & "'", trans) Then
                        isNewEntry = False
                    Else
                        isNewEntry = True
                    End If
                    clsCostType.SaveData(obj, isNewEntry, trans)
                    'SaveData()
                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                trans.Rollback()
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub
End Class
