Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports Telerik.WinControls.Data
Imports System.Text.RegularExpressions
Imports common
'''' <summary>
'''' ''''''''''''''''''''''''TicketNo='BM00000001530''''''''''''''''''''''''''''''''''''''''
'''' </summary>
'''' <remarks></remarks>

Public Class frmJobMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String
#Region "Functions"
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmJobMaster)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow(Me, "Permission Denied", Me.Text)
            Me.Close()
            Exit Sub
        End If
        btnsave.Visible = MyBase.isModifyFlag
        'btnPost.Visible = MyBase.isPostFlag
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Dim obj As clsJobMaster = clsJobMaster.GetData(strCode, NavTyep)
        If obj IsNot Nothing Then
            isNewEntry = False
            txtCode.Value = obj.JOB_CODE
            txtDesc.Text = obj.DESCRIPTION
            Me.cboJobType.Text = obj.JOB_TYPE
            Me.cboAccountingMethod.Text = obj.ACCOUNTING_METHOD
            Me.cboBillingType.Text = obj.BILLING_TYPE
            Me.chkAutoCreateTask.Checked = obj.AUTO_CREATE_TASK
            Me.cboJobType.Text = obj.JOB_TYPE

            txtCode.MyReadOnly = True

            ''For Custom Fields
            If MyBase.customFieldTabProperty = ElementVisibility.Visible Then
                UcCustomFields1.LoadData(obj.JOB_CODE)
            End If
            ''End of For Custom Fields
        End If
    End Sub
    Sub SaveData()
        Dim trans As SqlTransaction = Nothing
        Try
            If AllowToSave() Then
                trans = clsDBFuncationality.GetTransactin()
                Dim obj As New clsJobMaster()
                obj.JOB_CODE = txtCode.Value
                obj.DESCRIPTION = txtDesc.Text
                obj.JOB_TYPE = Me.cboJobType.Text
                obj.ACCOUNTING_METHOD = Me.cboAccountingMethod.Text
                obj.BILLING_TYPE = Me.cboBillingType.Text
                obj.AUTO_CREATE_TASK = Me.chkAutoCreateTask.Checked
                Dim qry As Integer = clsDBFuncationality.getSingleValue("select count(JOB_CODE) from TSPL_PJC_JOB where JOB_CODE='" + obj.JOB_CODE + "'", trans)
                If (qry = 0) Then
                    isNewEntry = True
                Else
                    isNewEntry = False
                End If

                ''For Custom Fields
                obj.Form_ID = MyBase.Form_ID
                obj.arrCustomFields = New List(Of clsCustomFieldValues)
                If MyBase.customFieldTabProperty = ElementVisibility.Visible Then
                    UcCustomFields1.GetData(obj.arrCustomFields)
                End If
                ''End of For Custom Fields

                If (clsJobMaster.SaveData(obj, isNewEntry, trans)) Then
                    If obj.AUTO_CREATE_TASK = True Then
                        Dim objTask As New clsTaskMaster()
                        objTask.TASK_CODE = txtCode.Value
                        objTask.DESCRIPTION = txtDesc.Text
                        objTask.JOB_CODE = clsCommon.myCstr(Me.txtCode.Value)

                        Dim qryTask As Integer = clsDBFuncationality.getSingleValue("select count(TASK_CODE) from TSPL_PJC_TASK where TASK_CODE='" + obj.JOB_CODE + "'", trans)
                        If (qry = 0) Then
                            isNewEntry = True
                        Else
                            isNewEntry = False
                        End If
                        clsTaskMaster.SaveData(objTask, isNewEntry, trans)
                    End If
                    trans.Commit()
                    clsCommon.MyMessageBoxShow(Me, "Data saved Successfully", Me.Text)
                    LoadData(obj.JOB_CODE, NavigatorType.Current)

                End If
            End If
        Catch ex As Exception
            trans.Rollback()
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(clsCommon.myCstr(txtCode.Value)) <= 0 Then
                txtCode.Focus()
                clsCommon.MyMessageBoxShow(Me, "Please Fill  Code", Me.Text)
                Return False
            End If
        End If
        If clsCommon.myLen(clsCommon.myCstr(txtDesc.Text)) <= 0 Then
            txtDesc.Focus()
            clsCommon.MyMessageBoxShow(Me, "Please Fill  Description", Me.Text)
            Return False
        End If
        If clsCommon.myLen(clsCommon.myCstr(cboJobType.Text)) <= 0 Then
            cboJobType.Focus()
            clsCommon.MyMessageBoxShow(Me, "Please Select  Job Type", Me.Text)
            Return False
        End If
        If clsCommon.myLen(clsCommon.myCstr(cboAccountingMethod.Text)) <= 0 Then
            cboAccountingMethod.Focus()
            clsCommon.MyMessageBoxShow(Me, "Please Select  Accounting Method", Me.Text)
            Return False
        End If
        If clsCommon.myLen(clsCommon.myCstr(cboBillingType.Text)) <= 0 Then
            cboBillingType.Focus()
            clsCommon.MyMessageBoxShow(Me, "Please Select  Billing Type", Me.Text)
            Return False
        End If
        UcCustomFields1.AllowToSave()
        Return True
    End Function
    Private Sub DeleteData()
        Dim trans As SqlTransaction = Nothing
        Try
            trans = clsDBFuncationality.GetTransactin
            If clsCommon.myLen(txtCode.Value) <= 0 Then
                Throw New Exception("  Code not found to delete")

            End If
            If clsCommon.MyMessageBoxShow("Do you want to delete  Code '" + txtCode.Value + "'", Me.Text, MessageBoxButtons.YesNo) = System.Windows.Forms.DialogResult.Yes Then

                Dim qry As String = "delete from TSPL_PJC_JOB where JOB_CODE='" + txtCode.Value + "'"
                clsDBFuncationality.ExecuteNonQuery(qry, trans)
                '' custom fields
                clsCustomFieldValues.DeleteData(Me.Form_ID, txtCode.Value, trans)
                trans.Commit()
                clsCommon.MyMessageBoxShow(Me, "Successfully Deleted", Me.Text)
                AddNew()
            End If
        Catch ex As Exception
            If (clsCommon.CompairString(clsCommon.myCstr(ex.Message), "Cost Code not found to delete") <> CompairStringResult.Equal) Then
                clsCommon.MyMessageBoxShow(Me, "Current Cost Code is in use")
            Else
                clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
            End If
            trans.Rollback()
        End Try
    End Sub
    Sub AddNew()
        txtCode.Value = ""
        'txtDesc.Text = ""
        txtCode.MyReadOnly = False
        txtDesc.Text = ""
        Me.cboJobType.DataSource = clsJobMaster.GetJobTypeTable
        Me.cboJobType.DisplayMember = "Name"
        Me.cboJobType.ValueMember = "Code"
        cboJobType.SelectedIndex = -1

        Me.cboAccountingMethod.DataSource = clsJobMaster.GetAccountingMethodTable
        Me.cboAccountingMethod.DisplayMember = "Name"
        Me.cboAccountingMethod.ValueMember = "Code"
        cboAccountingMethod.SelectedIndex = -1

        Me.cboBillingType.DataSource = clsJobMaster.GetBillingTypeTable
        Me.cboBillingType.DisplayMember = "Name"
        Me.cboBillingType.ValueMember = "Code"
        cboBillingType.SelectedIndex = -1
        Me.chkAutoCreateTask.Checked = False
    End Sub

#End Region
#Region "Events"

    Private Sub btnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click

        SaveData()
    End Sub

    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub

    Private Sub btnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        Me.Close()
    End Sub

    Private Sub btnnew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnnew.Click
        AddNew()
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        LoadData(txtCode.Value, NavType)
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = "select JOB_CODE as Code,DESCRIPTION as Name from  TSPL_PJC_JOB"
            'txtCode.Value = clsCommon.ShowSelectForm("TSPL_PJC_JOB", qry, "Code", "", txtCode.Value, "", isButtonClicked)
            txtCode.Value = clsJobMaster.getFinder("", txtCode.Value, isButtonClicked)
            LoadData(txtCode.Value, NavigatorType.Current)
        End If
    End Sub
    Private Sub frmJobMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update ")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D Delete ")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnnew, "Press Alt+N Adding New ")
        ' globalFunc.mandatoryText(fnddesig.txtValue, txtdes)

        ''For Custom Fields
        RadPageView1.Pages("pvpCustomFields").Item.Visibility = MyBase.customFieldTabProperty
        If MyBase.customFieldTabProperty = ElementVisibility.Visible Then
            UcCustomFields1.Report_ID = MyBase.Form_ID
            UcCustomFields1.LoadCustomControls()
        End If
        ''End of For Custom Fields
        AddNew()
    End Sub

    Private Sub frmJobMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
            'ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            '    PostData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            AddNew()
        End If
    End Sub
#End Region


    Private Sub RadMenuItem2_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenuItem2.Click
        Dim str As String
        str = " SELECT JOB_CODE AS [Code],DESCRIPTION AS [Description],JOB_TYPE AS [Job Type],ACCOUNTING_METHOD AS [Accounting Method]," & _
              " BILLING_TYPE AS [Billing Type],(case when AUTO_CREATE_TASK=1 then 'Yes' else 'No' end) AS [Auto Create Task] FROM TSPL_PJC_JOB "
        transportSql.ExporttoExcel(str, Me)
    End Sub

    Private Sub RadMenuItem1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenuItem1.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Description", "Job Type", "Accounting Method", "Billing Type", "Auto Create Task") Then
            Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsJobMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells("Code").Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.JOB_CODE = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells("Description").Value)
                    If strName.Length > 200 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Description can not be blank or incorrect.")
                    End If
                    obj.DESCRIPTION = strName

                    strCode = clsCommon.myCstr(grow.Cells("Job Type").Value)
                    obj.JOB_TYPE = strCode
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Job Type can not be blank or incorrect.")
                    End If

                    strCode = clsCommon.myCstr(grow.Cells("Accounting Method").Value)
                    obj.ACCOUNTING_METHOD = strCode
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Accounting Method can not be blank or incorrect.")
                    End If

                    strCode = clsCommon.myCstr(grow.Cells("Billing Type").Value)
                    obj.BILLING_TYPE = strCode
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Billing Type can not be blank or incorrect.")
                    End If

                    strCode = clsCommon.myCstr(grow.Cells("Auto Create Task").Value)
                    If clsCommon.CompairString(strCode, "Yes") = CompairStringResult.Equal Or clsCommon.CompairString(strCode, "1") = CompairStringResult.Equal Then
                        obj.AUTO_CREATE_TASK = True
                    Else
                        obj.AUTO_CREATE_TASK = False
                    End If



                    '' check for new entry
                    Dim isNewEntry As Boolean = False
                    Dim qry As Integer = clsDBFuncationality.getSingleValue("select count(JOB_CODE) from TSPL_PJC_JOB where JOB_CODE='" + obj.JOB_CODE + "'", trans)
                    If (qry = 0) Then
                        isNewEntry = True
                    Else
                        isNewEntry = False
                    End If
                    clsJobMaster.SaveData(obj, isNewEntry, trans)

                    '' automatic create task
                    If obj.AUTO_CREATE_TASK = True Then
                        Dim objTask As New clsTaskMaster()
                        objTask.TASK_CODE = obj.JOB_CODE
                        objTask.DESCRIPTION = obj.DESCRIPTION
                        objTask.JOB_CODE = obj.JOB_CODE


                        Dim qryTask As Integer = clsDBFuncationality.getSingleValue("select count(TASK_CODE) from TSPL_PJC_TASK where TASK_CODE='" + obj.JOB_CODE + "'", trans)
                        If (qryTask = 0) Then
                            isNewEntry = True
                        Else
                            isNewEntry = False
                        End If
                        clsTaskMaster.SaveData(objTask, isNewEntry, trans)
                    End If
                Next
                trans.Commit()

                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
                trans.Rollback()
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub
End Class
