Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports Telerik.WinControls.Data
Imports System.Text.RegularExpressions
Imports common
'''' <summary>
'''' ''''''''''''''''''''''''TicketNo='BM000000001526''''''''''''''''''''''''''''''''''''''''
'''' </summary>
'''' <remarks></remarks>

Public Class frmPJCSettings
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String
#Region "Functions"
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmPJCSettings)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        btnsave.Visible = MyBase.isModifyFlag
        'btnPost.Visible = MyBase.isPostFlag
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Dim obj As clsPJCSettings = clsPJCSettings.GetData(strCode, NavTyep)
        If obj IsNot Nothing Then
            isNewEntry = False
            txtCode.Value = obj.SETTING_CODE
            Me.cboLevel.Text = obj.LEVEL
            Me.chkAutoCreateTask.Checked = obj.AUTO_TASK_CREATE
            Me.fndBankAccount.Value = obj.BANK_CODE
            Me.txtBankAccountName.Text = obj.BANK_NAME
            txtCode.MyReadOnly = True
        End If
    End Sub
    Sub SaveData()
        Dim trans As SqlTransaction = Nothing
        Try
            If AllowToSave() Then
                trans = clsDBFuncationality.GetTransactin()
                Dim obj As New clsPJCSettings()
                obj.SETTING_CODE = txtCode.Value
                obj.LEVEL = Me.cboLevel.Text
                obj.AUTO_TASK_CREATE = chkAutoCreateTask.Checked
                obj.BANK_CODE = clsCommon.myCstr(Me.fndBankAccount.Value)
                Dim qry As Integer = clsDBFuncationality.getSingleValue("select count(SETTING_CODE) from TSPL_PJC_SETTINGS where SETTING_CODE='" + obj.SETTING_CODE + "'", trans)
                If (qry = 0) Then
                    isNewEntry = True
                Else
                    isNewEntry = False
                End If
                If (clsPJCSettings.SaveData(obj, isNewEntry, trans)) Then
                    trans.Commit()
                    clsCommon.MyMessageBoxShow("Data saved Successfully", Me.Text)
                    LoadData(obj.SETTING_CODE, NavigatorType.Current)

                End If
            End If
        Catch ex As Exception
            trans.Rollback()
            clsCommon.MyMessageBoxShow(ex.Message, Me.Text)
        End Try
    End Sub

    Private Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(clsCommon.myCstr(txtCode.Value)) <= 0 Then
                txtCode.Focus()
                clsCommon.MyMessageBoxShow("Please Fill Code")
                Return False
            End If
        End If

        If clsCommon.myLen(clsCommon.myCstr(cboLevel.Text)) <= 0 Then
            cboLevel.Focus()
            clsCommon.MyMessageBoxShow("Please Fill  Level")
            Return False
        End If
        Return True
    End Function
    Private Sub DeleteData()
        Try
            If clsCommon.myLen(txtCode.Value) <= 0 Then
                Throw New Exception("  Code not found to delete")

            End If
            If clsCommon.MyMessageBoxShow("Do you want to delete  Code '" + txtCode.Value + "'", Me.Text, MessageBoxButtons.YesNo) = System.Windows.Forms.DialogResult.Yes Then

                Dim qry As String = "delete from TSPL_PJC_SETTINGS where SETTING_CODE='" + txtCode.Value + "'"
                clsDBFuncationality.ExecuteNonQuery(qry)
                clsCommon.MyMessageBoxShow("Successfully Deleted", Me.Text)
                AddNew()
            End If
        Catch ex As Exception
            If (clsCommon.CompairString(clsCommon.myCstr(ex.Message), "Cost Code not found to delete") <> CompairStringResult.Equal) Then
                clsCommon.MyMessageBoxShow("Current Cost Code is in use")

            Else
                clsCommon.MyMessageBoxShow(ex.Message)
            End If
        End Try
    End Sub
    Sub AddNew()
        txtCode.Value = ""
        txtCode.MyReadOnly = False
        Me.chkAutoCreateTask.Checked = False
        Me.cboLevel.DataSource = clsPJCSettings.GetLevelsTable
        cboLevel.SelectedIndex = -1
        Me.cboLevel.DisplayMember = "Name"
        Me.cboLevel.ValueMember = "Code"
        Me.fndBankAccount.Value = Nothing
        Me.txtBankAccountName.Text = ""
    End Sub

#End Region
#Region "Events"

    Private Sub btnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click
        SaveData()
    End Sub

    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub

    Private Sub btnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        Me.Close()
    End Sub

    Private Sub btnnew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnnew.Click
        AddNew()
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        LoadData(txtCode.Value, NavType)
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = "select SETTING_CODE as Code,LEVEL as Name,BANK_CODE AS [Bank Code] from  TSPL_PJC_SETTINGS"
            'txtCode.Value = clsCommon.ShowSelectForm("TSPL_PJC_SETTINGS", qry, "Code", "", txtCode.Value, "", isButtonClicked)
            txtCode.Value = clsPJCSettings.getFinder("", txtCode.Value, isButtonClicked)
            LoadData(txtCode.Value, NavigatorType.Current)
        End If
    End Sub
    Private Sub frmPJCSettings_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update ")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D Delete ")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnnew, "Press Alt+N Adding New ")
        ' globalFunc.mandatoryText(fnddesig.txtValue, txtdes)
        AddNew()
    End Sub

    Private Sub frmPJCSettings_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
            'ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            '    PostData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            AddNew()
        End If
    End Sub
#End Region


    Private Sub fndBankAccount__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndBankAccount._MYValidating
        Dim qry As String = "select BANK_CODE AS Code,DESCRIPTION as Name,BANKACC from TSPL_BANK_MASTER "
        fndBankAccount.Value = clsCommon.ShowSelectForm("Bank", qry, "Code", "", fndBankAccount.Value, "", isButtonClicked)
        Dim dt As DataTable
        qry = qry & " where BANK_CODE='" & clsCommon.myCstr(fndBankAccount.Value) & "'"

        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            txtBankAccountName.Text = clsCommon.myCstr(dt.Rows(0).Item("Name"))
        Else
            txtBankAccountName.Text = ""
        End If
    End Sub
End Class
