Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports Telerik.WinControls.Data
Imports System.Text.RegularExpressions
Imports common
'''' <summary>
'''' ''''''''''''''''''''''''TicketNo='BM00000001531''''''''''''''''''''''''''''''''''''''''
'''' </summary>
'''' <remarks></remarks>

Public Class frmTaskMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String
#Region "Functions"
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmTaskMaster)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        btnsave.Visible = MyBase.isModifyFlag
        'btnPost.Visible = MyBase.isPostFlag
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Dim obj As clsTaskMaster = clsTaskMaster.GetData(strCode, NavTyep)
        If obj IsNot Nothing Then
            isNewEntry = False
            txtCode.Value = obj.TASK_CODE
            txtDesc.Text = obj.DESCRIPTION
            Me.fnduom.Value = obj.UNIT_CODE
            Me.lblUomName.Text = obj.UNIT_DESC
            Me.txtBillingRate.Text = obj.BILLING_RATE
            Me.txtUnitCost.Text = obj.UNIT_COST
            Me.fndCostType.Value = obj.COST_TYPE_CODE
            Me.txtCostTypeDesc.Text = obj.COST_TYPE_DESC
            Me.cboTaskType.Text = obj.TASK_TYPE
            Me.txtJobCode.Text = obj.JOB_CODE
            txtCode.MyReadOnly = True
            ''For Custom Fields
            If MyBase.customFieldTabProperty = ElementVisibility.Visible Then
                UcCustomFields1.LoadData(obj.TASK_CODE)
            End If
            ''End of For Custom Fields

        End If
    End Sub
    Sub SaveData()
        Dim trans As SqlTransaction = Nothing
        Try
            If AllowToSave() Then
                trans = clsDBFuncationality.GetTransactin()
                Dim obj As New clsTaskMaster()
                obj.TASK_CODE = txtCode.Value
                obj.DESCRIPTION = txtDesc.Text
                obj.UNIT_CODE = clsCommon.myCstr(Me.fnduom.Value)
                obj.BILLING_RATE = clsCommon.myCdbl(Me.txtBillingRate.Text)
                obj.UNIT_COST = clsCommon.myCdbl(Me.txtUnitCost.Text)
                obj.COST_TYPE_CODE = clsCommon.myCstr(Me.fndCostType.Value)
                obj.TASK_TYPE = clsCommon.myCstr(Me.cboTaskType.Text)
                obj.JOB_CODE = clsCommon.myCstr(Me.txtJobCode.Text)

                Dim qry As Integer = clsDBFuncationality.getSingleValue("select count(TASK_CODE) from TSPL_PJC_TASK where TASK_CODE='" + obj.TASK_CODE + "'", trans)
                If (qry = 0) Then
                    isNewEntry = True
                Else
                    isNewEntry = False
                End If

                ''For Custom Fields
                obj.Form_ID = MyBase.Form_ID
                obj.arrCustomFields = New List(Of clsCustomFieldValues)
                If MyBase.customFieldTabProperty = ElementVisibility.Visible Then
                    UcCustomFields1.GetData(obj.arrCustomFields)
                End If
                ''End of For Custom Fields


                If (clsTaskMaster.SaveData(obj, isNewEntry, trans)) Then
                    trans.Commit()
                    clsCommon.MyMessageBoxShow("Data saved Successfully", Me.Text)
                    LoadData(obj.TASK_CODE, NavigatorType.Current)

                End If
            End If
        Catch ex As Exception
            trans.Rollback()
            clsCommon.MyMessageBoxShow(ex.Message, Me.Text)
        End Try
    End Sub

    Private Function AllowToSave() As Boolean
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
                If clsCommon.myLen(clsCommon.myCstr(txtCode.Value)) <= 0 Then
                    txtCode.Focus()
                    clsCommon.MyMessageBoxShow("Please Fill  Code")
                    Return False
                End If
            End If
            If clsCommon.myLen(clsCommon.myCstr(txtDesc.Text)) <= 0 Then
                txtDesc.Focus()
                clsCommon.MyMessageBoxShow("Please Fill  Description")
                Return False
            End If
            UcCustomFields1.AllowToSave()
            Return True
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
            Return False
        End Try
    End Function
    Private Sub DeleteData()
        Dim trans As SqlTransaction = Nothing
        Try
            trans = clsDBFuncationality.GetTransactin
            If clsCommon.myLen(txtCode.Value) <= 0 Then
                Throw New Exception("  Code not found to delete")

            End If

            If clsCommon.MyMessageBoxShow("Do you want to delete  Code '" + txtCode.Value + "'", Me.Text, MessageBoxButtons.YesNo) = System.Windows.Forms.DialogResult.Yes Then
                Dim qry As String = "delete from TSPL_PJC_TASK where TASK_CODE='" + txtCode.Value + "'"
                clsDBFuncationality.ExecuteNonQuery(qry, trans)
                '' custom fields
                clsCustomFieldValues.DeleteData(Me.Form_ID, txtCode.Value, trans)
                trans.Commit()
                clsCommon.MyMessageBoxShow("Successfully Deleted", Me.Text)
                AddNew()
            End If
        Catch ex As Exception
            If (clsCommon.CompairString(clsCommon.myCstr(ex.Message), "Cost Code not found to delete") <> CompairStringResult.Equal) Then
                clsCommon.MyMessageBoxShow("Current Cost Code is in use")

            Else
                clsCommon.MyMessageBoxShow(ex.Message)
            End If
            trans.Rollback()
        End Try
    End Sub
    Sub AddNew()
        txtCode.Value = ""
        txtCode.MyReadOnly = False
        txtDesc.Text = ""
        Me.fnduom.Value = Nothing
        Me.lblUomName.Text = ""
        Me.txtBillingRate.Text = 0
        Me.txtUnitCost.Text = 0
        Me.fndCostType.Value = Nothing
        txtCostTypeDesc.Text = ""

        Me.cboTaskType.DataSource = clsTaskMaster.GetTaskTypeTable
        Me.cboTaskType.DisplayMember = "Name"
        Me.cboTaskType.ValueMember = "Code"
        cboTaskType.SelectedIndex = -1
        Me.txtJobCode.Text = ""

        ''For Custom Fields
        If MyBase.customFieldTabProperty = ElementVisibility.Visible Then
            UcCustomFields1.BlankAllControls()
        End If
        ''End of For Custom Fields

    End Sub

#End Region
#Region "Events"

    Private Sub btnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click

        SaveData()
    End Sub

    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub

    Private Sub btnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        Me.Close()
    End Sub

    Private Sub btnnew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnnew.Click
        AddNew()
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        LoadData(txtCode.Value, NavType)
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = "select TASK_CODE as Code,DESCRIPTION as Name,JOB_CODE AS [Job Code] from  TSPL_PJC_TASK"
            'txtCode.Value = clsCommon.ShowSelectForm("TSPL_PJC_TASK", qry, "Code", "", txtCode.Value, "", isButtonClicked)
            txtCode.Value = clsTaskMaster.getFinder("", txtCode.Value, isButtonClicked)
            LoadData(txtCode.Value, NavigatorType.Current)
        End If
    End Sub
    Private Sub frmTaskMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update ")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D Delete ")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnnew, "Press Alt+N Adding New ")
        ' globalFunc.mandatoryText(fnddesig.txtValue, txtdes)

        ''For Custom Fields
        RadPageView1.Pages("pvpCustomFields").Item.Visibility = MyBase.customFieldTabProperty
        If MyBase.customFieldTabProperty = ElementVisibility.Visible Then
            UcCustomFields1.Report_ID = MyBase.Form_ID
            UcCustomFields1.LoadCustomControls()
        End If
        ''End of For Custom Fields
        AddNew()

    End Sub

    Private Sub frmTaskMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
            'ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            '    PostData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnsave.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            AddNew()
        End If
    End Sub
#End Region


    Private Sub fnduom__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fnduom._MYValidating
        Dim qry As String = "select Unit_Code as [Code],UNIT_DESC as [Name] from TSPL_UNIT_MASTER "
        fnduom.Value = clsCommon.ShowSelectForm("TSPL_UNIT_MASTER", qry, "Code", "", fnduom.Value.ToString, "Unit_Code", isButtonClicked)
        lblUomName.Text = clsDBFuncationality.getSingleValue("select unit_desc from TSPL_UNIT_MASTER where unit_code='" + fnduom.Value + "' ")
    End Sub

    Private Sub fndCostType__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndCostType._MYValidating
        Dim qry As String = "select cost_type_code as [Code],description as [Description] from TSPL_PJC_COST_TYPE "
        fndCostType.Value = clsCommon.ShowSelectForm("TSPL_PJC_COST_TYPE", qry, "Code", "", fndCostType.Value, "", isButtonClicked)
        txtCostTypeDesc.Text = clsDBFuncationality.getSingleValue("select description from TSPL_PJC_COST_TYPE where cost_type_code='" + fndCostType.Value + "' ")
    End Sub
    Private Sub RadMenuItem2_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenuItem2.Click
        Dim str As String
        str = " select TASK_CODE as [Code],DESCRIPTION as [Description],UNIT_CODE as [Unit Code],BILLING_RATE as [Billing Rate],UNIT_COST as [Unit Cost]," & _
              " COST_TYPE_CODE as [Cost Type Code],TASK_TYPE as [Task Type] from TSPL_PJC_TASK "
        transportSql.ExporttoExcel(str, Me)
    End Sub

    Private Sub RadMenuItem1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenuItem1.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Description", "Unit Code", "Billing Rate", "Unit Cost", "Cost Type Code", "Task Type") Then
            Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
            Try

                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsTaskMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells("Code").Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.TASK_CODE = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells("Description").Value)
                    If strName.Length > 200 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Description can not be blank or incorrect.")
                    End If
                    obj.DESCRIPTION = strName

                    strCode = clsCommon.myCstr(grow.Cells("Unit Code").Value)
                    obj.UNIT_CODE = strCode

                    If clsCommon.myLen(strCode) > 0 Then
                        If clsTaskMaster.CheckUom(obj.UNIT_CODE, trans) = False Then
                            Throw New Exception("Unit Code '" & obj.UNIT_CODE & "' does not exist.")
                        End If
                    End If

                    strCode = clsCommon.myCdbl(grow.Cells("Billing Rate").Value)
                    obj.BILLING_RATE = strCode
                    
                    strCode = clsCommon.myCdbl(grow.Cells("Unit Cost").Value)
                    obj.UNIT_COST = strCode
                    
                    strCode = clsCommon.myCstr(grow.Cells("Cost Type Code").Value)
                    obj.COST_TYPE_CODE = strCode
                    If clsCommon.myLen(strCode) > 0 Then
                        If clsCostType.CheckCostType(obj.COST_TYPE_CODE, trans) = False Then
                            Throw New Exception("Cost Type Code  '" & obj.COST_TYPE_CODE & "' does not exist.")
                        End If
                    End If

                    strCode = clsCommon.myCstr(grow.Cells("Task Type").Value)
                    If strCode.Length > 30 Then
                        Throw New Exception("Task Type is incorrect.")
                    End If
                    obj.TASK_TYPE = strCode

                    '' check for new entry
                    Dim isNewEntry As Boolean = False
                    Dim qry As Integer = clsDBFuncationality.getSingleValue("select count(TASK_CODE) from TSPL_PJC_TASK where TASK_CODE='" + obj.TASK_CODE + "'", trans)
                    If (qry = 0) Then
                        isNewEntry = True
                    Else
                        isNewEntry = False
                    End If
                    clsTaskMaster.SaveData(obj, isNewEntry, trans)

                   
                Next
                trans.Commit()

                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
                trans.Rollback()
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub
End Class
