Imports common
Imports System.Data.SqlClient
Public Class clsJWFormula
#Region "Variables"
    Public Code As String = Nothing
    Public Description As String = Nothing
    Public Formula As String = Nothing
    Public Structure_Code As String = Nothing
    Public Arr As List(Of clsJWFormulaDetails) = Nothing
#End Region

    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "  select TSPL_JW_FORMULA.Code as [Code] ,TSPL_JW_FORMULA.Description as [Description] ,TSPL_JW_FORMULA.Formula as [Formula] ,TSPL_JW_FORMULA.Created_By as [Created By] ,TSPL_JW_FORMULA.Created_Date as [Created Date] ,TSPL_JW_FORMULA.Modified_By as [Modified By] ,TSPL_JW_FORMULA.Modified_Date as [Modified Date]  From TSPL_JW_FORMULA   "
        str = clsCommon.ShowSelectForm("JWFORMULA@FND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Function SaveData(ByVal arr As List(Of clsJWFormula), ByVal Arr2 As List(Of clsJWFormulaDetails), ByVal isNewEntry As Boolean) As Boolean

        Dim isSaved As Boolean = True
        Dim trans As SqlTransaction = Nothing
        Try
            trans = clsDBFuncationality.GetTransactin()
            isSaved = SaveData(arr, Arr2, isNewEntry, trans)
            If isSaved Then
                trans.Commit()
            End If
        Catch ex As Exception
            trans.Rollback()
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function

    Public Function SaveData(ByVal arr As List(Of clsJWFormula), ByVal Arr2 As List(Of clsJWFormulaDetails), ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim isSaved As Boolean = True
        'Dim trans As SqlTransaction = Nothing
        Try
            ' trans = clsDBFuncationality.GetTransactin()
            For Each obj As clsJWFormula In arr
                Dim coll As New Hashtable()
                '=================
                Try
                    Dim qry As String = "delete from TSPL_JW_FORMULA_DETAILS where Code='" + obj.Code + "'"
                    clsDBFuncationality.ExecuteNonQuery(qry, trans)
                Catch ex As Exception

                End Try

                '========================
                clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
                clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Formula", obj.Formula)
                clsCommon.AddColumnsForChange(coll, "Structure_Code", obj.Structure_Code)
                clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))

                If clsDBFuncationality.getSingleValue("Select count(*) from TSPL_JW_FORMULA where Code='" + obj.Code + "' ", trans) <= 0 Then

                    'If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.JWInwardFormula, "", "")
                    'End If

                    clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                    clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                    clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_JW_FORMULA", OMInsertOrUpdate.Insert, "", trans)
                Else
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_JW_FORMULA", OMInsertOrUpdate.Update, "TSPL_JW_FORMULA.Code='" + obj.Code + "'", trans)
                End If
                isSaved = isSaved AndAlso clsJWFormulaDetails.SaveData(obj.Code, Arr2, trans)
            Next
            'If isSaved Then
            '    trans.Commit()
            'End If
        Catch err As Exception
            ' trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsJWFormula
        Dim obj As clsJWFormula = Nothing
        Dim qry As String = "SELECT TSPL_JW_FORMULA.Code,TSPL_JW_FORMULA.Description,TSPL_JW_FORMULA.Formula,TSPL_JW_FORMULA.Structure_Code FROM TSPL_JW_FORMULA where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_JW_FORMULA.Code = (select MIN(Code) from TSPL_JW_FORMULA where 1=1 )"
            Case NavigatorType.Last
                qry += " and TSPL_JW_FORMULA.Code = (select Max(Code) from TSPL_JW_FORMULA where 1=1 )"
            Case NavigatorType.Next
                qry += " and TSPL_JW_FORMULA.Code = (select Min(Code) from TSPL_JW_FORMULA where Code>'" + strCode + "' )"
            Case NavigatorType.Previous
                qry += " and TSPL_JW_FORMULA.Code = (select Max(Code) from TSPL_JW_FORMULA where Code<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and TSPL_JW_FORMULA.Code = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsJWFormula()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
            obj.Formula = clsCommon.myCstr(dt.Rows(0)("Formula"))
            obj.Structure_Code = clsCommon.myCstr(dt.Rows(0)("Structure_Code"))

            qry = "select Code,Parameter_Code,Value from TSPL_JW_FORMULA_DETAILS where Code = '" + obj.Code + "'  "
            dt = clsDBFuncationality.GetDataTable(qry, trans)
            If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                obj.Arr = New List(Of clsJWFormulaDetails)
                For Each dr As DataRow In dt.Rows
                    Dim objtr As clsJWFormulaDetails = New clsJWFormulaDetails()
                    objtr.Code = clsCommon.myCstr(dr("Code"))
                    objtr.Parameter_Code = clsCommon.myCstr(dr("Parameter_Code"))
                    objtr.Value = clsCommon.myCstr(dr("Value")) 'clsCommon.myCstr(clsDBFuncationality.getSingleValue(" select Program_Name from TSPL_PROGRAM_MASTER where Program_Code = '" + objtr.Program_Code + "' "))
                    obj.Arr.Add(objtr)
                Next
            End If
        End If
        Return obj
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        If (clsCommon.myLen(strCode) <= 0) Then
            Throw New Exception("Code not found to Delete")
        End If

        Dim qry As String = "delete from TSPL_JW_FORMULA_DETAILS where Code='" + strCode + "'"
        clsDBFuncationality.ExecuteNonQuery(qry)

        qry = "delete from TSPL_JW_FORMULA where Code='" + strCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)

    End Function

    Public Shared Function GetName(ByVal strCode As String) As String
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Description from TSPL_JW_FORMULA where Code='" + strCode + "'"))
    End Function
End Class

Public Class clsJWFormulaDetails
    Public Code As String = Nothing
    Public Parameter_Code As String
    Public Value As String

    Public Shared Function SaveData(ByVal strCode As String, ByVal Arr As List(Of clsJWFormulaDetails), ByVal trans As SqlTransaction) As Boolean
        If (Arr IsNot Nothing AndAlso Arr.Count > 0) Then
            For Each obj As clsJWFormulaDetails In Arr
                Dim coll As New Hashtable()
                clsCommon.AddColumnsForChange(coll, "Code", strCode)
                clsCommon.AddColumnsForChange(coll, "Parameter_Code", obj.Parameter_Code)
                clsCommon.AddColumnsForChange(coll, "Value", obj.Value)
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_JW_FORMULA_DETAILS", OMInsertOrUpdate.Insert, "", trans)
            Next
        End If
        Return True
    End Function
    

End Class
Public Class clsVendorFormulaMapping
#Region "Variables"
    Public DocCode As String = Nothing
    Public Formulacode As String = Nothing
    Public DocDate As DateTime = Nothing
    Public Formula As String = Nothing
    Public ItemStructure As String = Nothing
    Public VenderCode As String = Nothing
    Public arrVendor As ArrayList
    Public Arr As List(Of clsVendorFormulaMapping) = Nothing
#End Region

    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "  select distinct TSPL_VENDOR_FORMULA_MAPPING.DocCode as [Code] ,TSPL_VENDOR_FORMULA_MAPPING.DocDate as [Date] ,TSPL_VENDOR_FORMULA_MAPPING.Formulacode as [Formula Code] ,TSPL_VENDOR_FORMULA_MAPPING.Created_By as [Created By] ,TSPL_VENDOR_FORMULA_MAPPING.Created_Date as [Created Date]   From TSPL_VENDOR_FORMULA_MAPPING   "
        str = clsCommon.ShowSelectForm("JWVM@FND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    Public Function SaveData(ByVal arr As List(Of clsVendorFormulaMapping), ByVal isNewEntry As String) As Boolean
        Dim tran As SqlTransaction = clsDBFuncationality.GetTransactin()
        Dim qry As String
        Try
            If arr IsNot Nothing AndAlso arr.Count > 0 Then
                For Each obj As clsVendorFormulaMapping In arr
                    qry = "select top 1 DocCode from TSPL_VENDOR_FORMULA_MAPPING where DocCode='" + obj.DocCode + "' and posted=1"
                    Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, tran)
                    If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                        Throw New Exception("Some posted vendor mapping found for Formula code :" + obj.Formulacode + "'")
                    End If

                    If isNewEntry = True Then
                        For Each StrVendor As String In obj.arrVendor
                            Dim qrycheck As String = "select TSPL_VENDOR_FORMULA_MAPPING.DocCode from TSPL_VENDOR_FORMULA_MAPPING"
                            qrycheck += " left outer join TSPL_VENDOR_FORMULA_MAPPING_DETAIL on TSPL_VENDOR_FORMULA_MAPPING_DETAIL.DocCode=TSPL_VENDOR_FORMULA_MAPPING.DocCode where TSPL_VENDOR_FORMULA_MAPPING_DETAIL.VendorCode='" + StrVendor + "' and convert(date,TSPL_VENDOR_FORMULA_MAPPING.DocDate,103)='" + clsCommon.GetPrintDate(obj.DocDate, "dd/MMM/yyyy") + "' and TSPL_VENDOR_FORMULA_MAPPING.FormulaCode='" + obj.Formulacode + "'"
                            Dim dt1 As DataTable = clsDBFuncationality.GetDataTable(qrycheck, tran)
                            If dt1 IsNot Nothing AndAlso dt1.Rows.Count > 0 Then
                                Throw New Exception("Vendor Mapping found for Formula code : " + obj.Formulacode + "' for date : " + clsCommon.myCDate(obj.DocDate) + "")
                            End If
                        Next


                    End If




                    qry = "delete from TSPL_VENDOR_FORMULA_MAPPING_Detail where DocCode='" + obj.DocCode + "'"
                    clsDBFuncationality.ExecuteNonQuery(qry, tran)
                    'For Each StrVendor As String In obj.arrVendor
                    Dim coll As New Hashtable()

                    clsCommon.AddColumnsForChange(coll, "FormulaCode", obj.Formulacode)
                    clsCommon.AddColumnsForChange(coll, "DocDate", clsCommon.GetPrintDate(obj.DocDate, "dd/MMM/yyyy hh:mm tt"))

                    If isNewEntry Then
                        clsCommon.AddColumnsForChange(coll, "DocCode", obj.DocCode)
                        clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                        clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(tran), "dd/MMM/yyyy hh:mm tt"))
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_VENDOR_FORMULA_MAPPING", OMInsertOrUpdate.Insert, "", tran)
                    Else
                        clsCommonFunctionality.UpdateDataTable(coll, "TSPL_VENDOR_FORMULA_MAPPING", OMInsertOrUpdate.Update, "TSPL_VENDOR_FORMULA_MAPPING.DocCode='" + obj.DocCode + "'", tran)
                    End If

                    'Next
                    clsVendorFormulaMappingDetail.SaveData(arr, arrVendor, tran)
                Next
            End If
            tran.Commit()
        Catch ex As Exception
            tran.Rollback()
            Throw New Exception(ex.Message)
        End Try
        Return True
    End Function

    Public Function DeleteData(ByVal arr As List(Of clsVendorFormulaMapping)) As Boolean
        Dim tran As SqlTransaction = clsDBFuncationality.GetTransactin()
        Dim qry As String
        Try
            If arr IsNot Nothing AndAlso arr.Count > 0 Then
                For Each obj As clsVendorFormulaMapping In arr
                    qry = "select top 1 PriceCode from TSPL_VENDOR_PRICE_CHART_MAPPING where PriceCode='" + obj.Formulacode + "' and posted=1"
                    Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, tran)
                    If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                        Throw New Exception("Some posted vendor mapping found for Price code :" + obj.Formulacode + "")
                    End If
                    qry = "delete from Tspl_Vendor_Price_Chart_mapping where PriceCode='" + obj.Formulacode + "'"
                    clsDBFuncationality.ExecuteNonQuery(qry, tran)
                Next
            End If
            tran.Commit()
        Catch ex As Exception
            tran.Rollback()
            Throw New Exception(ex.Message)
        End Try
        Return True
    End Function

    Public Function PostData(ByVal arr As List(Of clsVendorFormulaMapping)) As Boolean
        Dim tran As SqlTransaction = clsDBFuncationality.GetTransactin()
        Dim qry As String
        Try
            If arr IsNot Nothing AndAlso arr.Count > 0 Then
                For Each obj As clsVendorFormulaMapping In arr
                    'qry = "select top 1 DocCode from TSPL_VENDOR_FORMULA_MAPPING where DocCode='" + obj.DocCode + "' and posted=1"
                    'Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, tran)
                    'If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                    '    Throw New Exception("Some posted vendor mapping found for Formula code :" + obj.Formulacode + "")
                    'End If
                    qry = "Update TSPL_VENDOR_FORMULA_MAPPING set posted='1',Posted_By='" + objCommonVar.CurrentUserCode + "',Posted_Date='" + clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(tran), "dd/MMM/yyyy hh:mm tt") + "'  where DocCode='" + obj.DocCode + "'"
                    clsDBFuncationality.ExecuteNonQuery(qry, tran)
                Next
            End If
            tran.Commit()
        Catch ex As Exception
            tran.Rollback()
            Throw New Exception(ex.Message)
        End Try
        Return True
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsVendorFormulaMapping
        Dim obj As clsVendorFormulaMapping = Nothing
        Dim qry As String = "select TSPL_VENDOR_FORMULA_MAPPING.DocCode,TSPL_VENDOR_FORMULA_MAPPING.DocDate,TSPL_VENDOR_FORMULA_MAPPING.VendorCode,TSPL_JW_FORMULA.Code,TSPL_JW_FORMULA.Formula,TSPL_JW_FORMULA.Structure_Code from TSPL_VENDOR_FORMULA_MAPPING "
        qry += " left outer join TSPL_JW_FORMULA on TSPL_JW_FORMULA.Code=TSPL_VENDOR_FORMULA_MAPPING.FormulaCode where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_VENDOR_FORMULA_MAPPING.DocCode = (select MIN(TSPL_VENDOR_FORMULA_MAPPING.DocCode) from TSPL_JW_FORMULA where 1=1 )"
            Case NavigatorType.Last
                qry += " and TSPL_VENDOR_FORMULA_MAPPING.DocCode = (select Max(TSPL_VENDOR_FORMULA_MAPPING.DocCode) from TSPL_JW_FORMULA where 1=1 )"
            Case NavigatorType.Next
                qry += " and TSPL_VENDOR_FORMULA_MAPPING.DocCode = (select Min(TSPL_VENDOR_FORMULA_MAPPING.DocCode) from TSPL_JW_FORMULA where Code>'" + strCode + "' )"
            Case NavigatorType.Previous
                qry += " and TSPL_VENDOR_FORMULA_MAPPING.DocCode = (select Max(TSPL_VENDOR_FORMULA_MAPPING.DocCode) from TSPL_JW_FORMULA where Code<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and TSPL_VENDOR_FORMULA_MAPPING.DocCode = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsVendorFormulaMapping()
            obj.DocCode = clsCommon.myCstr(dt.Rows(0)("DocCode"))
            obj.DocDate = clsCommon.myCstr(dt.Rows(0)("DocDate"))
            obj.Formulacode = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Formula = clsCommon.myCstr(dt.Rows(0)("Formula"))
            obj.ItemStructure = clsCommon.myCstr(dt.Rows(0)("Structure_Code"))
            obj.VenderCode = clsCommon.myCstr(dt.Rows(0)("VendorCode"))


        End If
        Return obj
    End Function

End Class

Public Class clsVendorFormulaMappingDetail
    Public Shared Function SaveData(ByVal arr As List(Of clsVendorFormulaMapping), ByVal Arrvendor As ArrayList, ByVal trans As SqlTransaction) As Boolean

        If (arr IsNot Nothing AndAlso arr.Count > 0) Then
            For Each obj As clsVendorFormulaMapping In arr
                For Each StrVendor As String In obj.arrVendor
                    Dim coll As New Hashtable()
                    clsCommon.AddColumnsForChange(coll, "DocCode", obj.DocCode)
                    clsCommon.AddColumnsForChange(coll, "VendorCode", StrVendor)
                    clsCommonFunctionality.UpdateDataTable(coll, "TSPL_VENDOR_FORMULA_MAPPING_DETAIL", OMInsertOrUpdate.Insert, "", trans)
                Next
            Next
        End If
        Return True
    End Function
End Class

Public Class clsJWFormulaSoln
    Public Type As Integer ''1-FAT,2-SNF
    Public EstFATKG As Decimal
    Public EstSNFKG As Decimal

    Public Shared Function CalculateEstimate(ByVal dtDocDate As DateTime, ByVal StrStructreCode As String, ByVal strLocationCode As String, ByVal FatKG As Decimal, ByVal SNFKg As Decimal) As clsJWFormulaSoln
        Return CalculateEstimate(dtDocDate, StrStructreCode, strLocationCode, FatKG, SNFKg, Nothing)
    End Function
    Public Shared Function CalculateEstimate(ByVal dtDocDate As DateTime, ByVal StrStructreCode As String, ByVal strLocationCode As String, ByVal FatKG As Decimal, ByVal SNFKg As Decimal, ByVal ArrQCParam As Dictionary(Of String, String)) As clsJWFormulaSoln
       

        Dim qry As String = "select top 1  FormulaCode from TSPL_VENDOR_FORMULA_MAPPING_DETAIL" + Environment.NewLine + _
        "left outer join TSPL_VENDOR_FORMULA_MAPPING on TSPL_VENDOR_FORMULA_MAPPING.DocCode=TSPL_VENDOR_FORMULA_MAPPING_DETAIL.DocCode" + Environment.NewLine + _
        "left outer join TSPL_JW_FORMULA on TSPL_JW_FORMULA.Code=TSPL_VENDOR_FORMULA_MAPPING.FormulaCode" + Environment.NewLine + _
        "where TSPL_VENDOR_FORMULA_MAPPING.Posted=1 and TSPL_VENDOR_FORMULA_MAPPING.DocDate <='" + clsCommon.GetPrintDate(clsCommon.GetDateWithEndTime(dtDocDate), "dd/MMM/yyyy hh:mm:ss tt") + "' and TSPL_JW_FORMULA.Structure_Code in ('" + StrStructreCode + "')" + Environment.NewLine + _
        "and TSPL_VENDOR_FORMULA_MAPPING_DETAIL.VendorCode in (select Jobwork_Vendor from TSPL_LOCATION_MASTER where Location_Code ='" + strLocationCode + "') order by TSPL_VENDOR_FORMULA_MAPPING.DocDate desc"
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            Dim strFormulaCode As String = clsCommon.myCstr(dt.Rows(0)("FormulaCode"))
            If clsCommon.myLen(strFormulaCode) > 0 Then
                Return CalculateFormula(strFormulaCode, FatKG, SNFKg, ArrQCParam)
            End If
        End If
        Return Nothing
    End Function

    Public Shared Function CalculateFormula(ByVal strFormulaCode As String, ByVal FatKG As Decimal, ByVal SNFKg As Decimal, ByVal ArrQCParam As Dictionary(Of String, String))
        Dim FATType As Boolean
        Dim SNFType As Boolean
        Dim obj As clsJWFormulaSoln = Nothing
        Dim qry As String = "select TSPL_JW_FORMULA.Formula, TSPL_JW_FORMULA_DETAILS.Parameter_Code,TSPL_JW_FORMULA_DETAILS.Value,TSPL_JW_PARAMETER_MASTER.Type,TSPL_PARAMETER_MASTER.Code as MainParameterCode from TSPL_JW_FORMULA_DETAILS " + Environment.NewLine + _
                "left outer join TSPL_JW_PARAMETER_MASTER on TSPL_JW_PARAMETER_MASTER.Code=TSPL_JW_FORMULA_DETAILS.Parameter_Code" + Environment.NewLine + _
                "left outer join TSPL_JW_FORMULA on TSPL_JW_FORMULA.code=TSPL_JW_FORMULA_DETAILS.Code" + Environment.NewLine + _
                "left outer join TSPL_PARAMETER_MASTER on TSPL_PARAMETER_MASTER.Code=TSPL_JW_FORMULA_DETAILS.Parameter_Code and TSPL_JW_PARAMETER_MASTER.Type='N'" + Environment.NewLine + _
                "where TSPL_JW_FORMULA_DETAILS.Code='" + strFormulaCode + "' and TSPL_JW_FORMULA.Formula   like  '%'+TSPL_JW_FORMULA_DETAILS.Parameter_Code+'%'"
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            obj = New clsJWFormulaSoln()
            qry = clsCommon.myCstr(dt.Rows(0)("Formula"))
            For Each dr As DataRow In dt.Rows
                If clsCommon.CompairString(clsCommon.myCstr(dr("Type")), "F") = CompairStringResult.Equal Then
                    FATType = True
                    qry = qry.Replace(clsCommon.myCstr(dr("Parameter_Code")), clsCommon.myCstr(FatKG))
                ElseIf clsCommon.CompairString(clsCommon.myCstr(dr("Type")), "S") = CompairStringResult.Equal Then
                    SNFType = True
                    qry = qry.Replace(clsCommon.myCstr(dr("Parameter_Code")), clsCommon.myCstr(SNFKg))
                Else
                    If clsCommon.myLen(dr("MainParameterCode")) > 0 Then
                        ''BHA/22/10/18-000634 by balwinder on 24/10/2018
                        If ArrQCParam IsNot Nothing AndAlso ArrQCParam.Count > 0 Then
                            If ArrQCParam.ContainsKey(clsCommon.myCstr(dr("Parameter_Code"))) Then
                                qry = qry.Replace(clsCommon.myCstr(dr("Parameter_Code")), ArrQCParam.Item(clsCommon.myCstr(dr("Parameter_Code"))))
                            Else
                                qry = qry.Replace(clsCommon.myCstr(dr("Parameter_Code")), clsCommon.myCstr(dr("Value")))
                            End If
                        Else
                            qry = qry.Replace(clsCommon.myCstr(dr("Parameter_Code")), clsCommon.myCstr(dr("Value")))
                        End If
                    Else
                        qry = qry.Replace(clsCommon.myCstr(dr("Parameter_Code")), clsCommon.myCstr(dr("Value")))
                    End If
                End If
            Next
            qry = "select (" + qry + ") "
            If FATType AndAlso SNFType Then
                Throw New Exception("Formula - [" + strFormulaCode + "] has FAT And SNF both type parameters")
            ElseIf Not FATType AndAlso Not SNFType Then
                Throw New Exception("Formula - [" + strFormulaCode + "] has at least one FAT And SNF type parameters")
            Else
                If FATType Then
                    obj.Type = 1
                    Try
                        obj.EstFATKG = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qry))
                    Catch ex As Exception
                    End Try
                ElseIf SNFType Then
                    obj.Type = 2
                    Try
                        obj.EstSNFKG = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qry))
                    Catch ex As Exception
                    End Try
                Else
                    Throw New Exception("Formula - [" + strFormulaCode + "] something is wrong")
                End If
            End If
        End If
        Return obj
    End Function
End Class