Imports common
Imports System.Data.SqlClient
Public Class clsAcquisitionCodes
#Region "Variables"
    Public Code As String = Nothing
    Public Description As String = Nothing
    Public Acqu_with As String = Nothing
    Public Type As String = Nothing
    Public Default_Account As String = Nothing
    Public Vendor_Code As String = Nothing
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_ACQUISITION_CODES.Code as [Code] ,TSPL_ACQUISITION_CODES.Description as [Description] ,TSPL_ACQUISITION_CODES.Acqu_with as [Acquisition With] ,TSPL_ACQUISITION_CODES.Type as [Type] ,TSPL_ACQUISITION_CODES.Default_Account as [Default Account] ,TSPL_ACQUISITION_CODES.Created_By as [Created By] ,TSPL_ACQUISITION_CODES.Created_Date as [Created Date] ,TSPL_ACQUISITION_CODES.Modified_By as [Modified By] ,TSPL_ACQUISITION_CODES.Modified_Date as [Modified Date]  From TSPL_ACQUISITION_CODES    "
        str = clsCommon.ShowSelectForm("ACQCODEFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'

    Public Function SaveData(ByVal obj As clsAcquisitionCodes, ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Dim Trans As SqlTransaction = clsDBFuncationality.GetTransactin
        Try
            Dim Col1 As New Hashtable
            clsCommon.AddColumnsForChange(Col1, "Description", obj.Description)
            clsCommon.AddColumnsForChange(Col1, "Acqu_with", obj.Acqu_with)
            clsCommon.AddColumnsForChange(Col1, "Type", obj.Type)
            clsCommon.AddColumnsForChange(Col1, "Default_Account", obj.Default_Account)
            clsCommon.AddColumnsForChange(Col1, "Vendor_Code", obj.Vendor_Code)
            clsCommon.AddColumnsForChange(Col1, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(Col1, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(Trans), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_ACQUISITION_CODES where Code='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(Trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(Trans), "dd/MM/yyyy"), clsDocType.AcquisitionCodes, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(Col1, "Code", obj.Code)
                clsCommon.AddColumnsForChange(Col1, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(Col1, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(Trans), "dd/MMM/yyyy hh:mm tt"))
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(Col1, "TSPL_ACQUISITION_CODES", OMInsertOrUpdate.Insert, "", Trans)
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(Col1, "TSPL_ACQUISITION_CODES", OMInsertOrUpdate.Update, "TSPL_ACQUISITION_CODES.Code='" + obj.Code + "'", Trans)
            End If
            If isSaved Then
                Trans.Commit()
            End If
        Catch ex As Exception
            Trans.Rollback()
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsAcquisitionCodes
        Dim obj As clsAcquisitionCodes = Nothing
        Dim qry As String = "SELECT TSPL_ACQUISITION_CODES.Code,TSPL_ACQUISITION_CODES.Description,Acqu_with,Type,Default_Account,Vendor_Code FROM TSPL_ACQUISITION_CODES where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_ACQUISITION_CODES.Code = (select MIN(Code) from TSPL_ACQUISITION_CODES where 1=1 )"
            Case NavigatorType.Last
                qry += " and TSPL_ACQUISITION_CODES.Code = (select Max(Code) from TSPL_ACQUISITION_CODES where 1=1 )"
            Case NavigatorType.Next
                qry += " and TSPL_ACQUISITION_CODES.Code = (select Min(Code) from TSPL_ACQUISITION_CODES where Code>'" + strCode + "' )"
            Case NavigatorType.Previous
                qry += " and TSPL_ACQUISITION_CODES.Code = (select Max(Code) from TSPL_ACQUISITION_CODES where Code<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and TSPL_ACQUISITION_CODES.Code = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsAcquisitionCodes()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
            obj.Acqu_with = clsCommon.myCstr(dt.Rows(0)("Acqu_with"))
            obj.Type = clsCommon.myCstr(dt.Rows(0)("Type"))
            obj.Default_Account = clsCommon.myCstr(dt.Rows(0)("Default_Account"))
            obj.Vendor_Code = clsCommon.myCstr(dt.Rows(0)("Vendor_Code"))
        End If
        Return obj
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        If (clsCommon.myLen(strCode) <= 0) Then
            Throw New Exception("Code not found to Delete")
        End If

        Dim qry As String = "delete from TSPL_ACQUISITION_CODES where Code='" + strCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)

    End Function



End Class



