Imports System.Data.SqlClient
Imports common
Public Class clsJobMaster
#Region "variables"
    Public JOB_CODE As String = ""
    Public DESCRIPTION As String = ""
    Public JOB_TYPE As String = ""
    Public ACCOUNTING_METHOD As String = ""
    Public BILLING_TYPE As String = ""
    Public AUTO_CREATE_TASK As Boolean = False
    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing

    Public Form_ID As String = ""
    Public arrCustomFields As List(Of clsCustomFieldValues) = Nothing
#End Region
#Region "Functions"

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_PJC_JOB.JOB_CODE as [Code] ,TSPL_PJC_JOB.DESCRIPTION as [Description] ,TSPL_PJC_JOB.JOB_TYPE as [Job Type] ,TSPL_PJC_JOB.ACCOUNTING_METHOD as [Accounting Method] ,TSPL_PJC_JOB.BILLING_TYPE as [Billing Type] ,TSPL_PJC_JOB.AUTO_CREATE_TASK as [Auto Create Task] ,TSPL_PJC_JOB.Created_By as [Created By] ,TSPL_PJC_JOB.Created_Date as [Created Date] ,TSPL_PJC_JOB.Modified_By as [Modified By] ,TSPL_PJC_JOB.Modified_Date as [Modified Date]  From TSPL_PJC_JOB   "
        str = clsCommon.ShowSelectForm("PJCJOBMST", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function SaveData(ByVal obj As clsJobMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""

        Try

            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "Description", obj.DESCRIPTION)
            clsCommon.AddColumnsForChange(coll, "JOB_TYPE", obj.JOB_TYPE)
            clsCommon.AddColumnsForChange(coll, "ACCOUNTING_METHOD", obj.ACCOUNTING_METHOD)
            clsCommon.AddColumnsForChange(coll, "BILLING_TYPE", obj.BILLING_TYPE)
            clsCommon.AddColumnsForChange(coll, "AUTO_CREATE_TASK", obj.AUTO_CREATE_TASK)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_PJC_JOB where JOB_CODE='" & obj.JOB_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.JOB_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.JobMaster, "", "")
                        If clsCommon.myLen(obj.JOB_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "JOB_CODE", obj.JOB_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PJC_JOB", OMInsertOrUpdate.Insert, "", trans)
            Else
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PJC_JOB", OMInsertOrUpdate.Update, "TSPL_PJC_JOB.JOB_CODE='" + obj.JOB_CODE + "'", trans)
            End If
            '' custom fields
            clsCustomFieldValues.SaveData(obj.Form_ID, obj.JOB_CODE, obj.arrCustomFields, trans)
        Catch err As Exception

            Throw New Exception(err.Message)
        End Try
        Return True
    End Function


    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsJobMaster
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsJobMaster
        Dim obj As clsJobMaster = Nothing
        Dim Arr As List(Of clsJobMaster) = Nothing
        Dim qry As String = "select JOB_CODE ,DESCRIPTION,JOB_TYPE,ACCOUNTING_METHOD,BILLING_TYPE,AUTO_CREATE_TASK from TSPL_PJC_JOB where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_PJC_JOB.JOB_CODE = (select MIN(JOB_CODE) from TSPL_PJC_JOB WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_PJC_JOB.JOB_CODE = (select Max(JOB_CODE) from TSPL_PJC_JOB WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_PJC_JOB.JOB_CODE = (select top 1 JOB_CODE from TSPL_PJC_JOB WHERE 1=1 " + whrclas + " and JOB_CODE='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_PJC_JOB.JOB_CODE = (select Min(JOB_CODE) from TSPL_PJC_JOB where JOB_CODE>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_PJC_JOB.JOB_CODE = (select Max(JOB_CODE) from TSPL_PJC_JOB where JOB_CODE<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsJobMaster()
            obj.JOB_CODE = clsCommon.myCstr(dt.Rows(0)("JOB_CODE"))
            obj.DESCRIPTION = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.JOB_TYPE = clsCommon.myCstr(dt.Rows(0)("JOB_TYPE"))
            obj.ACCOUNTING_METHOD = clsCommon.myCstr(dt.Rows(0)("ACCOUNTING_METHOD"))
            obj.BILLING_TYPE = clsCommon.myCstr(dt.Rows(0)("BILLING_TYPE"))
            obj.AUTO_CREATE_TASK = clsCommon.myCdbl(dt.Rows(0)("AUTO_CREATE_TASK"))
        End If
        Return obj
    End Function
    Public Shared Function GetJobTypeTable() As DataTable
        Dim DT_JobType As DataTable = New DataTable
        DT_JobType.Columns.Add("Code", GetType(String))
        DT_JobType.Columns.Add("Name", GetType(String))

        Dim DR As DataRow = DT_JobType.NewRow()
        DR("Name") = "Time and Material"
        DR("Code") = "Time and Material"
        DT_JobType.Rows.Add(DR)

        'DR = DT_JobType.NewRow()
        'DR("Name") = "Material"
        'DR("Code") = "Material"
        'DT_JobType.Rows.Add(DR)

        DR = DT_JobType.NewRow()
        DR("Name") = "Fixed Price"
        DR("Code") = "Fixed Price"
        DT_JobType.Rows.Add(DR)

        DR = DT_JobType.NewRow()
        DR("Name") = "Cost Plus"
        DR("Code") = "Cost Plus"
        DT_JobType.Rows.Add(DR)

        DT_JobType.AcceptChanges()

        Return DT_JobType
    End Function
    Public Shared Function GetAccountingMethodTable() As DataTable
        Dim DT_AccMethod As DataTable = New DataTable
        DT_AccMethod.Columns.Add("Code", GetType(String))
        DT_AccMethod.Columns.Add("Name", GetType(String))

        Dim DR As DataRow = DT_AccMethod.NewRow()
        DR("Name") = "Completed Project"
        DR("Code") = "Completed Project"
        DT_AccMethod.Rows.Add(DR)

        DR = DT_AccMethod.NewRow()
        DR("Name") = "Billing and Cost"
        DR("Code") = "Billing and Cost"
        DT_AccMethod.Rows.Add(DR)

        DT_AccMethod.AcceptChanges()

        Return DT_AccMethod
    End Function

    Public Shared Function GetBillingTypeTable() As DataTable
        Dim DT_BillingType As DataTable = New DataTable
        DT_BillingType.Columns.Add("Code", GetType(String))
        DT_BillingType.Columns.Add("Name", GetType(String))

        Dim DR As DataRow = DT_BillingType.NewRow()
        DR("Name") = "Billable"
        DR("Code") = "Billable"
        DT_BillingType.Rows.Add(DR)

        DR = DT_BillingType.NewRow()
        DR("Name") = "Non Billable"
        DR("Code") = "Non Billable"
        DT_BillingType.Rows.Add(DR)

        DR = DT_BillingType.NewRow()
        DR("Name") = "No Charge"
        DR("Code") = "No Charge"
        DT_BillingType.Rows.Add(DR)

        DT_BillingType.AcceptChanges()

        Return DT_BillingType
    End Function


#End Region

End Class
