Imports System.Data.SqlClient
Imports common
Public Class clsUnitMaster
#Region "Variables"
    Public Code As String = Nothing
    Public Description As String = Nothing

#End Region

    Public Shared Function SaveData(ByVal obj As clsUnitMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Dim IsSaved As Boolean = False
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
            ' clsCommon.AddColumnsForChange(coll, "Zone_Code", obj.Zone_Code, True)
            clsCommon.AddColumnsForChange(coll, "Modify_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modify_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_COST_CENTER_UNIT_MASTER where Code='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.AreaMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_COST_CENTER_UNIT_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_COST_CENTER_UNIT_MASTER", OMInsertOrUpdate.Update, "Code='" + obj.Code + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return IsSaved
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsUnitMaster
        Dim obj As clsUnitMaster = Nothing
        Dim qry As String = "select TSPL_COST_CENTER_UNIT_MASTER.* from TSPL_COST_CENTER_UNIT_MASTER   where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_COST_CENTER_UNIT_MASTER.Code = (select MIN(Code) from TSPL_COST_CENTER_UNIT_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_COST_CENTER_UNIT_MASTER.Code = (select Max(Code) from TSPL_COST_CENTER_UNIT_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_COST_CENTER_UNIT_MASTER.Code = (select TOP 1 Code from TSPL_COST_CENTER_UNIT_MASTER WHERE 1=1 " + whrclas + " and Code='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_COST_CENTER_UNIT_MASTER.Code = (select Min(Code) from TSPL_COST_CENTER_UNIT_MASTER where Code > '" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_COST_CENTER_UNIT_MASTER.Code = (select Max(Code) from TSPL_COST_CENTER_UNIT_MASTER where Code < '" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsUnitMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))

        End If
        Return obj
    End Function

    Public Shared Function GetName(ByVal strCode As String) As String
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Description from TSPL_COST_CENTER_UNIT_MASTER where Code='" + strCode + "'"))
    End Function

    Public Shared Function GetUnitName(ByVal strCode As String) As String
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Unit_Desc from TSPL_UNIT_MASTER where Unit_Code='" + strCode + "'"))
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim qry As String = ""
        Try
            qry = "Delete from TSPL_COST_CENTER_UNIT_MASTER where TSPL_COST_CENTER_UNIT_MASTER.Code='" + strCode + "'"
            clsDBFuncationality.ExecuteNonQuery(qry)
        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function
    Public Shared Function getUnitFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "select Unit_Code as Code,Unit_Desc as Name from TSPL_UNIT_MASTER"
        str = clsCommon.ShowSelectForm("UnitFnd", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "select TSPL_COST_CENTER_UNIT_MASTER.Code,TSPL_COST_CENTER_UNIT_MASTER.Description from TSPL_COST_CENTER_UNIT_MASTER "
        str = clsCommon.ShowSelectForm("AreaFnd", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    Public Shared Function Finder(ByVal strCode As String, ByVal isButtonClicked As Boolean) As clsUnitMaster
        Dim obj As clsUnitMaster = Nothing
        Dim qry As String = "select TSPL_COST_CENTER_UNIT_MASTER.Code,TSPL_COST_CENTER_UNIT_MASTER.Description from TSPL_COST_CENTER_UNIT_MASTER"
        Dim WhrCls As String = Nothing
        strCode = clsCommon.ShowSelectForm("UnitMaster", qry, "Code", WhrCls, strCode, "Code", isButtonClicked)
        If clsCommon.myLen(strCode) > 0 Then
            qry = "select TSPL_COST_CENTER_UNIT_MASTER.Description from TSPL_COST_CENTER_UNIT_MASTER where TSPL_COST_CENTER_UNIT_MASTER.Code='" + strCode + "' "
            obj = New clsUnitMaster()
            obj.Code = strCode
            obj.Description = clsDBFuncationality.getSingleValue(qry)
        End If
        Return obj
    End Function
    Public Shared Function CheckNewEntry(ByVal Code As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "select Code from TSPL_COST_CENTER_UNIT_MASTER where Code ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry, trans)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function

End Class
