Imports common
Imports System.Data
Imports System.Data.SqlClient
Public Class clsCountryMaster
#Region "Variables"
    Public Code As String
    Public Name As String
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select COUNTRY_CODE as [Code],COUNTRY_NAME as [Country Name],Created_By as [Created By],Created_Date as [Created Date],Modified_By as [Modified By],Modified_Date as [Modified Date] from tspl_country_master "
        str = clsCommon.ShowSelectForm("CNTRYMSTFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsCountryMaster
        Return GetData(strCode, NavType, Nothing)
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isSaved As Boolean

        Try
            isSaved = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_COUNTRY_MASTER where COUNTRY_CODE ='" + strCode + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry)


        Catch ex As Exception

            Throw New Exception(ex.Message.ToString())
        End Try
        Return isSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsCountryMaster
        Dim obj As clsCountryMaster = Nothing
        Dim qry As String = "select COUNTRY_CODE, COUNTRY_NAME from TSPL_COUNTRY_MASTER where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and COUNTRY_CODE = (select MIN(COUNTRY_CODE) from TSPL_COUNTRY_MASTER)"
            Case NavigatorType.Last
                qry += " and COUNTRY_CODE = (select Max(COUNTRY_CODE) from TSPL_COUNTRY_MASTER)"
            Case NavigatorType.Next
                qry += " and COUNTRY_CODE = (select Min(COUNTRY_CODE) from TSPL_COUNTRY_MASTER where  COUNTRY_CODE>'" + strCode + "')"
            Case NavigatorType.Previous
                qry += " and COUNTRY_CODE = (select Max(COUNTRY_CODE) from TSPL_COUNTRY_MASTER where COUNTRY_CODE<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and COUNTRY_CODE = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsCountryMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("COUNTRY_CODE"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("COUNTRY_NAME"))
        End If
        Return obj


    End Function

    Public Shared Function GetName(ByVal strCode As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "select COUNTRY_NAME from TSPL_COUNTRY_MASTER where COUNTRY_CODE='" + strCode + "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
    End Function

    Public Function SaveData(ByVal obj As clsCountryMaster, ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "COUNTRY_NAME", obj.Name)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_COUNTRY_MASTER where COUNTRY_CODE='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.CountryMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "COUNTRY_CODE", obj.Code)
                clsCommon.AddColumnsForChange(coll, "Posted", "N")
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy hh:mm tt"))
                Dim qry As String = "SELECT Count(*) FROM TSPL_COUNTRY_MASTER where COUNTRY_CODE= '" & obj.Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_COUNTRY_MASTER", OMInsertOrUpdate.Insert, "")
                Else
                    Throw New Exception("This Code Is Already Exist")
                End If

            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_COUNTRY_MASTER", OMInsertOrUpdate.Update, "COUNTRY_CODE='" + obj.Code + "'")
            End If

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select COUNTRY_CODE from TSPL_COUNTRY_MASTER where COUNTRY_CODE ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function

End Class
