'===========================BM00000007850===============================
Imports common
Imports System.Data
Imports System.Data.SqlClient
Public Class clsDepartmentMaster


#Region "Variables"
    Public Code As String
    Public Description As String
    Public Name As String
    Public DEPARTMENT_TYPE As String
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_DEPARTMENT_MASTER.DEPARTMENT_CODE as [Code] ,TSPL_DEPARTMENT_MASTER.DEPARTMENT_NAME as [Department Name] , " & _
        " TSPL_DEPARTMENT_MASTER.DESCRIPTION as [Description],TSPL_DEPARTMENT_MASTER.DEPARTMENT_TYPE as [Department Type], " & _
        " TSPL_DEPARTMENT_MASTER.Created_By as [Created By] ,TSPL_DEPARTMENT_MASTER.Created_Date as [Created Date] , " & _
        " TSPL_DEPARTMENT_MASTER.Modified_By as [Modified By] ,TSPL_DEPARTMENT_MASTER.Modified_Date as [Modified Date]  From TSPL_DEPARTMENT_MASTER   "
        str = clsCommon.ShowSelectForm("DEPTMSTFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsDepartmentMaster
        Return GetData(strCode, NavType, Nothing)
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isSaved As Boolean

        Try
            isSaved = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Department Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_DEPARTMENT_MASTER where DEPARTMENT_CODE='" + strCode + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry)


        Catch ex As Exception

            Throw New Exception(ex.Message.ToString())
        End Try
        Return isSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsDepartmentMaster
        Dim obj As clsDepartmentMaster = Nothing
        Dim qry As String = "select DEPARTMENT_CODE, DEPARTMENT_NAME, DESCRIPTION,DEPARTMENT_TYPE from TSPL_DEPARTMENT_MASTER where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and DEPARTMENT_CODE = (select MIN(DEPARTMENT_CODE) from TSPL_DEPARTMENT_MASTER)"
            Case NavigatorType.Last
                qry += " and DEPARTMENT_CODE = (select Max(DEPARTMENT_CODE) from TSPL_DEPARTMENT_MASTER)"
            Case NavigatorType.Next
                qry += " and DEPARTMENT_CODE = (select Min(DEPARTMENT_CODE) from TSPL_DEPARTMENT_MASTER where  DEPARTMENT_CODE>'" + strCode + "')"
            Case NavigatorType.Previous
                qry += " and DEPARTMENT_CODE = (select Max(DEPARTMENT_CODE) from TSPL_DEPARTMENT_MASTER where DEPARTMENT_CODE<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and DEPARTMENT_CODE = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsDepartmentMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("DEPARTMENT_CODE"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("DEPARTMENT_NAME"))
            obj.DEPARTMENT_TYPE = clsCommon.myCstr(dt.Rows(0)("DEPARTMENT_TYPE"))
        End If
        Return obj


    End Function

    Public Function SaveData(ByVal obj As clsDepartmentMaster, ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "comp_code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "DEPARTMENT_NAME", obj.Name)
            clsCommon.AddColumnsForChange(coll, "DESCRIPTION", obj.Description)
            clsCommon.AddColumnsForChange(coll, "DEPARTMENT_TYPE", obj.DEPARTMENT_TYPE)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_DEPARTMENT_MASTER where DEPARTMENT_CODE='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.DepartmentMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "DEPARTMENT_CODE", obj.Code)
                clsCommon.AddColumnsForChange(coll, "Posted", 1)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
                Dim qry As String = "SELECT Count(*) FROM TSPL_DEPARTMENT_MASTER where DEPARTMENT_CODE= '" & obj.Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_DEPARTMENT_MASTER", OMInsertOrUpdate.Insert, "")
                Else
                    Throw New Exception("This Code Is Already Exist")
                End If
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_DEPARTMENT_MASTER", OMInsertOrUpdate.Update, "DEPARTMENT_CODE='" + obj.Code + "'")
            End If
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function GetCodeByName(ByVal strName As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = " Select DEPARTMENT_CODE from TSPL_DEPARTMENT_MASTER where DEPARTMENT_NAME = '" + strName + "' "
        Dim StrCode As String = clsDBFuncationality.getSingleValue(qry, trans)
        Return StrCode
    End Function
    Public Shared Function GetName(ByVal strCode As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = " Select DEPARTMENT_NAME from TSPL_DEPARTMENT_MASTER where DEPARTMENT_CODE = '" + strCode + "' "
        Dim StrDesc As String = clsDBFuncationality.getSingleValue(qry, trans)
        Return StrDesc
    End Function
    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select DEPARTMENT_CODE from TSPL_DEPARTMENT_MASTER where DEPARTMENT_CODE ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
    Public Shared Function GetCboDepartmentTypeDataTable() As DataTable
        Dim DT As DataTable = New DataTable
        DT.Columns.Add("Code", GetType(String))
        DT.Columns.Add("Name", GetType(String))
        Dim DR As DataRow = DT.NewRow()
        DR("Code") = "Purchase"
        DR("Name") = "Purchase"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "Sales"
        DR("Name") = "Sales"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "Production"
        DR("Name") = "Production"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "Procurement"
        DR("Name") = "Procurement"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "Finance"
        DR("Name") = "Finance"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "HR"
        DR("Name") = "Human Resource"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "IT"
        DR("Name") = "Information Technology"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "Other"
        DR("Name") = "Other"
        DT.Rows.Add(DR)
        DT.AcceptChanges()
        Return DT
    End Function
End Class
