
Imports common
Imports System.Data.SqlClient

Public Class ClsDeprAccountSet
#Region "variables"
    Public AcSet_Code As String = Nothing
    Public AcSet_Desc As String = Nothing

    Public Inactive As Char = Nothing
    Public Ac_Control As String = Nothing
    Public Ac_Control_YearDisposal As String = Nothing
    Public Ac_Control_YearAdj As String = Nothing
    Public Ac_WIP As String = Nothing
    Public Ac_Accum_Dep As String = Nothing
    Public Ac_Accum_Dep_YearDisposal As String = Nothing
    Public Ac_Accum_Dep_YearAdj As String = Nothing
    Public Modify_By As DateTime
    Public Modify_Date As DateTime
    Public Created_By As DateTime
    Public Created_Date As DateTime
    Public Comp_Code As String
    Public Ac_Dep_Account As String = Nothing

    Public Disposal_Account As String = Nothing
    Public Disposal_Proceed_Account As String = Nothing
    Public Transfer_Clearing_Account As String = Nothing
    Public Disposal_Cost_Account As String = Nothing
    Public WIP_AC As String = Nothing
    Public PROFIT_AC As String = Nothing
    Public LOSS_AC As String = Nothing
#End Region
    Public Shared Function SaveData(ByVal Arr As List(Of ClsDeprAccountSet)) As Boolean
        Dim isSaved As Boolean = True
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            For Each obj As ClsDeprAccountSet In Arr
                Dim coll As New Hashtable()
                clsCommon.AddColumnsForChange(coll, "AcSet_Desc", obj.AcSet_Desc)

                clsCommon.AddColumnsForChange(coll, "Inactive", obj.Inactive)
                clsCommon.AddColumnsForChange(coll, "Ac_Control", obj.Ac_Control)
                clsCommon.AddColumnsForChange(coll, "Ac_Control_YearDisposal", obj.Ac_Control_YearDisposal, True)
                clsCommon.AddColumnsForChange(coll, "Ac_Control_YearAdj", obj.Ac_Control_YearAdj, True)
                clsCommon.AddColumnsForChange(coll, "Ac_WIP", obj.Ac_WIP, True)
                clsCommon.AddColumnsForChange(coll, "Ac_Accum_Dep", obj.Ac_Accum_Dep, True)
                clsCommon.AddColumnsForChange(coll, "Ac_Accum_Dep_YearDisposal", obj.Ac_Accum_Dep_YearDisposal, True)
                clsCommon.AddColumnsForChange(coll, "Ac_Accum_Dep_YearAdj", obj.Ac_Accum_Dep_YearAdj, True)
                clsCommon.AddColumnsForChange(coll, "Ac_Dep_Account", obj.Ac_Dep_Account, True)

                clsCommon.AddColumnsForChange(coll, "Disposal_Account", obj.Disposal_Account, True)
                clsCommon.AddColumnsForChange(coll, "Disposal_Proceed_Account", obj.Disposal_Proceed_Account, True)
                clsCommon.AddColumnsForChange(coll, "Transfer_Clearing_Account", obj.Transfer_Clearing_Account, True)
                clsCommon.AddColumnsForChange(coll, "Disposal_Cost_Account", obj.Disposal_Cost_Account, True)

                clsCommon.AddColumnsForChange(coll, "WIP_AC", obj.WIP_AC, True)
                clsCommon.AddColumnsForChange(coll, "PROFIT_AC", obj.PROFIT_AC, True)
                clsCommon.AddColumnsForChange(coll, "LOSS_AC", obj.LOSS_AC, True)

                clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
                clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                If clsDBFuncationality.getSingleValue("Select COUNT(*) from TSPL_Dep_AccountSet WHERE AcSet_Code='" + obj.AcSet_Code + "'", trans) <= 0 Then

                    If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                        obj.AcSet_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.DeprAccountSet, "", "")
                    End If

                    clsCommon.AddColumnsForChange(coll, "AcSet_Code", obj.AcSet_Code)
                    clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                    clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_Dep_AccountSet", OMInsertOrUpdate.Insert, "", trans)
                Else
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_Dep_AccountSet", OMInsertOrUpdate.Update, "TSPL_Dep_AccountSet.AcSet_Code='" + obj.AcSet_Code + "'", trans)
                End If
                clsCommonFunctionality.SaveHistoryData(objCommonVar.CurrentUserCode, clsCommon.myCstr(obj.AcSet_Code), "TSPL_Dep_AccountSet", "AcSet_Code", trans)
            Next
            If isSaved Then
                trans.Commit()
            End If
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function GetData(ByVal strDocumentNo As String, ByVal NavType As NavigatorType) As ClsDeprAccountSet
        Return GetData(strDocumentNo, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strPONo As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsDeprAccountSet
        Dim obj As ClsDeprAccountSet = Nothing
        Dim qry As String = "select AcSet_Code,AcSet_Desc,Inactive,Ac_Control,Ac_Control_YearDisposal,Ac_Control_YearAdj,Ac_WIP,Ac_Accum_Dep,Ac_Accum_Dep_YearDisposal,Ac_Accum_Dep_YearAdj,Ac_Dep_Account,Disposal_Account,Disposal_Proceed_Account,Transfer_Clearing_Account,Disposal_Cost_Account,WIP_AC,PROFIT_AC,LOSS_AC from TSPL_Dep_AccountSet where 2=2"
        Dim whrClas As String = ""

        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_Dep_AccountSet.AcSet_Code = (select MIN(AcSet_Code) from TSPL_Dep_AccountSet where 1=1 " + whrClas + ")"
            Case NavigatorType.Last
                qry += " and TSPL_Dep_AccountSet.AcSet_Code = (select Max(AcSet_Code) from TSPL_Dep_AccountSet where 1=1 " + whrClas + ")"
            Case NavigatorType.Next
                qry += " and TSPL_Dep_AccountSet.AcSet_Code = (select Min(AcSet_Code) from TSPL_Dep_AccountSet where AcSet_Code>'" + strPONo + "' " + whrClas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_Dep_AccountSet.AcSet_Code = (select Max(AcSet_Code) from TSPL_Dep_AccountSet where AcSet_Code<'" + strPONo + "' " + whrClas + ")"
            Case NavigatorType.Current
                qry += "  and TSPL_Dep_AccountSet.AcSet_Code = '" + strPONo + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsDeprAccountSet()
            obj.AcSet_Code = clsCommon.myCstr(dt.Rows(0)("AcSet_Code"))
            obj.AcSet_Desc = clsCommon.myCstr(dt.Rows(0)("AcSet_Desc"))
            obj.Inactive = clsCommon.myCstr(dt.Rows(0)("Inactive"))
            obj.Ac_Control = clsCommon.myCstr(dt.Rows(0)("Ac_Control"))
            obj.Ac_Control_YearDisposal = clsCommon.myCstr(dt.Rows(0)("Ac_Control_YearDisposal"))
            obj.Ac_Control_YearAdj = clsCommon.myCstr(dt.Rows(0)("Ac_Control_YearAdj"))
            obj.Ac_WIP = clsCommon.myCstr(dt.Rows(0)("Ac_WIP"))
            obj.Ac_Accum_Dep = clsCommon.myCstr(dt.Rows(0)("Ac_Accum_Dep"))
            obj.Ac_Accum_Dep_YearDisposal = clsCommon.myCstr(dt.Rows(0)("Ac_Accum_Dep_YearDisposal"))
            obj.Ac_Accum_Dep_YearAdj = clsCommon.myCstr(dt.Rows(0)("Ac_Accum_Dep_YearAdj"))
            obj.Ac_Dep_Account = clsCommon.myCstr(dt.Rows(0)("Ac_Dep_Account"))

            obj.Disposal_Account = clsCommon.myCstr(dt.Rows(0)("Disposal_Account"))
            obj.Disposal_Proceed_Account = clsCommon.myCstr(dt.Rows(0)("Disposal_Proceed_Account"))
            obj.Transfer_Clearing_Account = clsCommon.myCstr(dt.Rows(0)("Transfer_Clearing_Account"))
            obj.Disposal_Cost_Account = clsCommon.myCstr(dt.Rows(0)("Disposal_Cost_Account"))

            obj.WIP_AC = clsCommon.myCstr(dt.Rows(0)("WIP_AC"))
            obj.PROFIT_AC = clsCommon.myCstr(dt.Rows(0)("PROFIT_AC"))
            obj.LOSS_AC = clsCommon.myCstr(dt.Rows(0)("LOSS_AC"))

        End If

        Return obj
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean

        Dim isSaved As Boolean = True
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try


            Dim qry As String = "delete from TSPL_Dep_AccountSet where AcSet_Code='" + strCode + "'"
            isSaved = isSaved AndAlso clsDBFuncationality.ExecuteNonQuery(qry, trans)

            If (isSaved) Then
                trans.Commit()
            Else
                trans.Rollback()
            End If
        Catch ex As Exception
            trans.Rollback()
            Throw New Exception(ex.Message)
        End Try

        Return isSaved
    End Function



End Class
