Imports common
Imports System.Data
Imports System.Data.SqlClient
Public Class clsGradeMaster

#Region "Variables"
    Public Code As String
    Public Description As String
    Public Name As String
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_GRADE_MASTER.GRADE_CODE as [Code] ,TSPL_GRADE_MASTER.GRADE_NAME as [Grade Name] ,TSPL_GRADE_MASTER.DESCRIPTION as [Description] ,TSPL_GRADE_MASTER.Created_By as [Created By] ,TSPL_GRADE_MASTER.Created_Date as [Created Date] ,TSPL_GRADE_MASTER.Modified_By as [Modified By] ,TSPL_GRADE_MASTER.Modified_Date as [Modified Date]  From TSPL_GRADE_MASTER   "
        str = clsCommon.ShowSelectForm("GRDMSTFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsGradeMaster
        Return GetData(strCode, NavType, Nothing)
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isSaved As Boolean

        Try
            isSaved = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_GRADE_MASTER where GRADE_CODE ='" + strCode + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry)


        Catch ex As Exception

            Throw New Exception(ex.Message.ToString())
        End Try
        Return isSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsGradeMaster
        Dim obj As clsGradeMaster = Nothing
        Dim qry As String = "select GRADE_CODE, GRADE_NAME, DESCRIPTION from TSPL_GRADE_MASTER where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and GRADE_CODE = (select MIN(GRADE_CODE) from TSPL_GRADE_MASTER)"
            Case NavigatorType.Last
                qry += " and GRADE_CODE = (select Max(GRADE_CODE) from TSPL_GRADE_MASTER)"
            Case NavigatorType.Next
                qry += " and GRADE_CODE = (select Min(GRADE_CODE) from TSPL_GRADE_MASTER where  GRADE_CODE>'" + strCode + "')"
            Case NavigatorType.Previous
                qry += " and GRADE_CODE = (select Max(GRADE_CODE) from TSPL_GRADE_MASTER where GRADE_CODE<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and GRADE_CODE = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsGradeMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("GRADE_CODE"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("GRADE_NAME"))
        End If
        Return obj


    End Function

    Public Function SaveData(ByVal obj As clsGradeMaster, ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "GRADE_NAME", obj.Name)
            clsCommon.AddColumnsForChange(coll, "DESCRIPTION", obj.Description)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_GRADE_MASTER where GRADE_CODE='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.GradeMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "GRADE_CODE", obj.Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
                Dim qry As String = "SELECT Count(*) FROM TSPL_GRADE_MASTER where GRADE_CODE= '" & obj.Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_GRADE_MASTER", OMInsertOrUpdate.Insert, "")
                Else
                    Throw New Exception("This Code Is Already Exist")
                End If
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_GRADE_MASTER", OMInsertOrUpdate.Update, "GRADE_CODE='" + obj.Code + "'")
            End If
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function GetCodeByName(ByVal strName As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = " Select GRADE_CODE from TSPL_GRADE_MASTER where GRADE_NAME = '" + strName + "' "
        Dim StrCode As String = clsDBFuncationality.getSingleValue(qry, trans)
        Return StrCode
    End Function

    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select GRADE_CODE from TSPL_GRADE_MASTER where GRADE_CODE ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
End Class
