'----Add By- Sanjay 29/08/2018 Ticket No- BHA/28/08/18-000490
Imports System.Data.SqlClient
Imports common

Public Class clsJWParameterMaster
    ''check In Prabhakar 19/06/2020
#Region "Variables"
    Public Code As String = Nothing
    Public Description As String = Nothing
    Public Type As String = Nothing
    Public IS_MOISTURE As Boolean = False
#End Region
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "  select TSPL_JW_Parameter_MASTER.Code,TSPL_JW_Parameter_MASTER.Description from TSPL_JW_Parameter_MASTER   "
        str = clsCommon.ShowSelectForm("JWParameter@FND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function

    Public Function SaveData(ByVal arr As List(Of clsJWParameterMaster), ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Dim trans As SqlTransaction = Nothing
        Try
            trans = clsDBFuncationality.GetTransactin()
            For Each obj As clsJWParameterMaster In arr
                Dim coll As New Hashtable()
                clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
                clsCommon.AddColumnsForChange(coll, "Type", obj.Type)
                clsCommon.AddColumnsForChange(coll, "IS_MOISTURE", IIf(obj.IS_MOISTURE = True, 1, 0))
                clsCommon.AddColumnsForChange(coll, "Modify_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Modify_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))

                If clsDBFuncationality.getSingleValue("Select count(*) from  TSPL_JW_Parameter_MASTER where Code='" + obj.Code + "' ", trans) <= 0 Then

                    'If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    ' obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.JWInwardFormula, "", "")
                    'End If

                    clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                    clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                    clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_JW_Parameter_MASTER", OMInsertOrUpdate.Insert, "", trans)
                Else
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_JW_Parameter_MASTER", OMInsertOrUpdate.Update, "TSPL_JW_Parameter_MASTER.Code='" + obj.Code + "'", trans)
                End If
            Next
            If isSaved Then
                trans.Commit()
            End If
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function


    'Public Shared Function SaveData(ByVal obj As clsJWParameterMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
    '    Dim qry As String = ""
    '    Dim IsSaved As Boolean = False
    '    Try
    '        Dim coll As New Hashtable()
    '        clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
    '        clsCommon.AddColumnsForChange(coll, "Modify_By", objCommonVar.CurrentUserCode)
    '        clsCommon.AddColumnsForChange(coll, "Modify_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
    '        If isNewEntry Then
    '            'If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
    '            '    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_SAC_MASTER where Code='" & obj.Code & "'")
    '            '    If ChkNewEntry = 0 Then
    '            '        obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.AreaMaster, "", "")
    '            '        If clsCommon.myLen(obj.Code) <= 0 Then
    '            '            Throw New Exception("Error in Code Generation")
    '            '        End If
    '            '    End If
    '            'End If
    '            clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
    '            clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
    '            clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
    '            IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_JW_Parameter_MASTER", OMInsertOrUpdate.Insert, "", trans)
    '        Else
    '            IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_JW_Parameter_MASTER", OMInsertOrUpdate.Update, "Code='" + obj.Code + "'", trans)
    '        End If

    '    Catch err As Exception
    '        Throw New Exception(err.Message)
    '    End Try
    '    Return IsSaved
    'End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsJWParameterMaster
        Dim obj As clsJWParameterMaster = Nothing
        Dim qry As String = "select TSPL_JW_Parameter_MASTER.* from TSPL_JW_Parameter_MASTER   where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_JW_Parameter_MASTER.Code = (select MIN(Code) from TSPL_JW_Parameter_MASTER where 1=1 )"
            Case NavigatorType.Last
                qry += " and TSPL_JW_Parameter_MASTER.Code = (select Max(Code) from TSPL_JW_Parameter_MASTER where 1=1 )"
            Case NavigatorType.Next
                qry += " and TSPL_JW_Parameter_MASTER.Code = (select Min(Code) from TSPL_JW_Parameter_MASTER where Code>'" + strCode + "' )"
            Case NavigatorType.Previous
                qry += " and TSPL_JW_Parameter_MASTER.Code = (select Max(Code) from TSPL_JW_Parameter_MASTER where Code<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and TSPL_JW_Parameter_MASTER.Code = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsJWParameterMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
            obj.Type = clsCommon.myCstr(dt.Rows(0)("Type"))
            obj.IS_MOISTURE = clsCommon.myCBool(dt.Rows(0)("IS_MOISTURE"))
        End If
        Return obj
    End Function

    'Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsJWParameterMaster
    '    Dim obj As clsJWParameterMaster = Nothing
    '    Dim qry As String = "select TSPL_JW_Parameter_MASTER.* from TSPL_JW_Parameter_MASTER   where 2=2 "
    '    Dim whrclas As String = ""
    '    Select Case NavType
    '        Case NavigatorType.First
    '            qry += " and TSPL_JW_Parameter_MASTER.Code = (select MIN(Code) from TSPL_JW_Parameter_MASTER WHERE 1=1 " + whrclas + " )"
    '        Case NavigatorType.Last
    '            qry += " and TSPL_JW_Parameter_MASTER.Code = (select Max(Code) from TSPL_JW_Parameter_MASTER WHERE 1=1 " + whrclas + " )"
    '        Case NavigatorType.Current
    '            qry += " and TSPL_JW_Parameter_MASTER.Code = (select TOP 1 Code from TSPL_JW_Parameter_MASTER WHERE 1=1 " + whrclas + " and Code='" + strCode + "' )"
    '        Case NavigatorType.Next
    '            qry += " and TSPL_JW_Parameter_MASTER.Code = (select Min(Code) from TSPL_JW_Parameter_MASTER where Code > '" + strCode + "' " + whrclas + ")"
    '        Case NavigatorType.Previous
    '            qry += " and TSPL_JW_Parameter_MASTER.Code = (select Max(Code) from TSPL_JW_Parameter_MASTER where Code < '" + strCode + "' " + whrclas + ")"
    '    End Select
    '    Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
    '    If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
    '        obj = New clsJWParameterMaster()
    '        obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
    '        obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))

    '    End If
    '    Return obj
    'End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        If (clsCommon.myLen(strCode) <= 0) Then
            Throw New Exception("Code not found to Delete")
        End If

        Dim qry As String = "delete from TSPL_JW_Parameter_MASTER where Code='" + strCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)

    End Function

    Public Shared Function GetName(ByVal strCode As String) As String
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Description from TSPL_JW_Parameter_MASTER where Code='" + strCode + "'"))
    End Function

    'Public Shared Function DeleteData(ByVal strCode As String) As Boolean
    '    Dim qry As String = ""
    '    Try
    '        qry = "Delete from TSPL_JW_Parameter_MASTER where TSPL_JW_Parameter_MASTER.Code='" + strCode + "'"
    '        clsDBFuncationality.ExecuteNonQuery(qry)
    '    Catch err As Exception
    '        Throw New Exception(err.Message)
    '    End Try
    '    Return True
    'End Function

    'Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
    '    Dim str As String = ""
    '    Dim qry As String = "select TSPL_JW_Parameter_MASTER.Code,TSPL_JW_Parameter_MASTER.Description from TSPL_JW_Parameter_MASTER "
    '    str = clsCommon.ShowSelectForm("AreaFnd", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
    '    Return str

    'End Function

    'Public Shared Function CheckNewEntry(ByVal Code As String, ByVal trans As SqlTransaction) As String
    '    Dim qry As String = "select Code from TSPL_JW_Parameter_MASTER where Code ='" + Code + "'   "
    '    Dim dt As DataTable
    '    dt = clsDBFuncationality.GetDataTable(qry, trans)
    '    If dt.Rows.Count > 0 Then
    '        Return False
    '    Else
    '        Return True
    '    End If

    'End Function

End Class
