Imports common
Imports System.Data.SqlClient

Public Class clsPrimaryReasonMaster
#Region "veriables"
    Public Reason_Code As String = Nothing
    Public description As String = Nothing
    Public CompCode As String = Nothing
    Public CompDesc As String = Nothing
#End Region
    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_PRIMARY_REASON_MASTER.REASON_CODE as [Code] ,TSPL_PRIMARY_REASON_MASTER.DESCRIPTION as [Description] ,TSPL_PRIMARY_REASON_MASTER.COMPLAINT_CODE as [Complaint Code] ,TSPL_PRIMARY_REASON_MASTER.Created_By as [Created By] ,TSPL_PRIMARY_REASON_MASTER.Created_Date as [Created Date] ,TSPL_PRIMARY_REASON_MASTER.Modified_By as [Modified By] ,TSPL_PRIMARY_REASON_MASTER.Modified_Date as [Modified Date]  From TSPL_PRIMARY_REASON_MASTER   "
        str = clsCommon.ShowSelectForm("PRMRRSNMST", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    '' This Code For Retriving Data from TSPL_PRIMARY_REASON_MASTER


    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsPrimaryReasonMaster
        Dim obj As clsPrimaryReasonMaster = Nothing
        Dim qst As String = "select  a.Reason_Code , a.description AS Reason_Description, a.Complaint_Code as rComplaint_Code,b.Complaint_Code as cComplaint_Code,b.description as Comp_Group_Desc  from  TSPL_PRIMARY_REASON_MASTER as a, TSPL_COMPLAINT_GROUP_MASTER as b where a.COMPLAINT_CODE=b.COMPLAINT_CODE "
        Select Case NavType
            Case NavigatorType.Current
                qst += " and  a.reason_code ='" & strCode & "' "
            Case NavigatorType.Next
                qst += " and  a.Reason_code in (select min(t.reason_Code ) from TSPL_PRIMARY_REASON_MASTER  as t where t.reason_Code  >'" + strCode + "')"
            Case NavigatorType.First
                qst += " and  a.Reason_code in (select min(t.reason_Code ) from TSPL_PRIMARY_REASON_MASTER  as t )"
            Case NavigatorType.Last
                qst += " and  a.Reason_code in (select max(t.reason_Code ) from TSPL_PRIMARY_REASON_MASTER  as t )"
            Case NavigatorType.Previous
                qst += " and  a.Reason_code in (select max(t.reason_Code ) from TSPL_PRIMARY_REASON_MASTER  as t where t.reason_Code  <'" + strCode + "')"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            obj = New clsPrimaryReasonMaster
            obj.Reason_Code = clsCommon.myCstr(dt.Rows(0)("reason_Code"))
            obj.description = clsCommon.myCstr(dt.Rows(0)("Reason_Description"))
            obj.CompCode = clsCommon.myCstr(dt.Rows(0)("rComplaint_Code"))
            obj.CompDesc = clsCommon.myCstr(dt.Rows(0)("Comp_Group_Desc"))
        End If
        Return obj
    End Function
    '' For Delete of Data in TSPL_PRIMARY_REASON_MASTER
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim qry As String = "Delete from TSPL_PRIMARY_REASON_MASTER where Reason_Code='" + strCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)
    End Function
    '' For Save Data in TSPL_PRIMARY_REASON_MASTER
    Public Function SaveData(ByVal obj As clsPrimaryReasonMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "comp_code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "Description", obj.description)
            clsCommon.AddColumnsForChange(coll, "Complaint_Code", obj.CompCode)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))

            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_PRIMARY_REASON_MASTER where Reason_Code='" & obj.Reason_Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Reason_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.PrimaryReasonMaster, "", "")
                        If clsCommon.myLen(obj.Reason_Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Reason_code", obj.Reason_Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
                If clsCommon.myLen(obj.Reason_Code) = 0 Then
                    Throw New Exception("Please fill Reason Code")

                ElseIf clsCommon.myLen(obj.CompCode) = 0 Then
                    Throw New Exception("Please fill Complaint Group Code")
                End If
                Dim qry1 As String = "SELECT Count(*) FROM TSPL_COMPLAINT_GROUP_MASTER where COMPLAINT_Code = '" & obj.CompCode & "'"
                Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1, trans)
                If check1 = 0 Then
                    isSaved = False
                    Throw New Exception("Invalid Complaint Group Code")
                End If
                Dim qry As String = "SELECT Count(*) FROM TSPL_PRIMARY_REASON_MASTER where Reason_Code = '" & obj.Reason_Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry, trans)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PRIMARY_REASON_MASTER", OMInsertOrUpdate.Insert, "", trans)
                Else
                    Throw New Exception("This Code Is Already Exist")
                End If
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PRIMARY_REASON_MASTER ", OMInsertOrUpdate.Update, " Reason_Code='" + obj.Reason_Code + "'", trans)
            End If
        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select reason_code from TSPL_PRIMARY_REASON_MASTER where REASON_CODE ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
End Class
