Imports common
Imports System.Data
Imports System.Data.SqlClient

Public Class clsRevenueVillageMaster
#Region "Variables"
    Public code As String = Nothing
    Public name As String = Nothing
    Public Revenue_Village_Name_Hindi As String = Nothing
#End Region
    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "select TSPL_REVENUE_VILLAGE_MASTER.REVENUE_VILLAGE_CODE as [Code] ,TSPL_REVENUE_VILLAGE_MASTER.REVENUE_VILLAGE_NAME as [Revenue Village Name] ,TSPL_REVENUE_VILLAGE_MASTER.Created_By as [Created By] ,TSPL_REVENUE_VILLAGE_MASTER.Created_Date as [Created Date] ,TSPL_REVENUE_VILLAGE_MASTER.Modified_By as [Modified By] ,TSPL_REVENUE_VILLAGE_MASTER.Modified_Date as [Modified Date]  From TSPL_REVENUE_VILLAGE_MASTER  "
        str = clsCommon.ShowSelectForm("RGNFND@RevenueVillage@MAster", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'

    Public Shared Function SaveData(ByVal obj As clsRevenueVillageMaster, ByVal strCode As String) As Boolean
        Try

            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_REVENUE_VILLAGE_MASTER where REVENUE_VILLAGE_CODE='" & obj.code & "'")
                If ChkNewEntry = 0 Then
                    obj.code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.RevenueVillageMaster, "", "")
                    If clsCommon.myLen(obj.code) <= 0 Then
                        Throw New Exception("Error in Revenue Village Code Generation")
                    End If
                End If
            End If

            Dim coll As New Hashtable()
            Dim qry As String = "SELECT Count(*) FROM TSPL_REVENUE_VILLAGE_MASTER where REVENUE_VILLAGE_CODE= '" & obj.code & "'"
            Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
            clsCommon.AddColumnsForChange(coll, "REVENUE_VILLAGE_NAME", obj.name)
            clsCommon.AddColumnsForChange(coll, "REVENUE_VILLAGE_NAME_HINDI", obj.Revenue_Village_Name_Hindi, False, True)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))

            clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
            If check > 0 Then
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_REVENUE_VILLAGE_MASTER", OMInsertOrUpdate.Update, "REVENUE_VILLAGE_CODE='" + obj.code + "'")
            Else
                clsCommon.AddColumnsForChange(coll, "REVENUE_VILLAGE_CODE", obj.code)
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_REVENUE_VILLAGE_MASTER", OMInsertOrUpdate.Insert, "")
            End If
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return True
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsRevenueVillageMaster
        Try
            Dim obj As clsRevenueVillageMaster = Nothing
            Dim qry As String = "select REVENUE_VILLAGE_CODE, REVENUE_VILLAGE_NAME from TSPL_REVENUE_VILLAGE_MASTER where 2=2"
            Select Case NavType
                Case NavigatorType.First
                    qry += " and REVENUE_VILLAGE_CODE = (select MIN(REVENUE_VILLAGE_CODE) from TSPL_REVENUE_VILLAGE_MASTER)"
                Case NavigatorType.Last
                    qry += " and REVENUE_VILLAGE_CODE = (select Max(REVENUE_VILLAGE_CODE) from TSPL_REVENUE_VILLAGE_MASTER)"
                Case NavigatorType.Next
                    qry += " and REVENUE_VILLAGE_CODE = (select Min(REVENUE_VILLAGE_CODE) from TSPL_REVENUE_VILLAGE_MASTER where  REVENUE_VILLAGE_CODE>'" + strCode + "')"
                Case NavigatorType.Previous
                    qry += " and REVENUE_VILLAGE_CODE = (select Max(REVENUE_VILLAGE_CODE) from TSPL_REVENUE_VILLAGE_MASTER where REVENUE_VILLAGE_CODE<'" + strCode + "')"
                Case NavigatorType.Current
                    qry += " and REVENUE_VILLAGE_CODE = '" + strCode + "'"

            End Select
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)


            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
                obj = New clsRevenueVillageMaster()
                obj.code = clsCommon.myCstr(dt.Rows(0)("REVENUE_VILLAGE_CODE"))
                obj.name = clsCommon.myCstr(dt.Rows(0)("REVENUE_VILLAGE_NAME"))
                obj.Revenue_Village_Name_Hindi = clsCommon.myCstr(dt.Rows(0)("Revenue_Village_Name_Hindi"))
            End If
            Return obj
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function

    Public Shared Function GetName(ByVal strCode As String) As String
        Dim qry As String = "Select REVENUE_VILLAGE_NAME from TSPL_REVENUE_VILLAGE_MASTER where REVENUE_VILLAGE_CODE='" + strCode + "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry))
    End Function

End Class