Imports System.Data.SqlClient
Imports common

Public Class ClsZoneMaster

#Region "Variables"
    Public Zone_Code As String = Nothing
    Public Description As String = Nothing
    Public Description_Hindi As String = Nothing
    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing
    Public City_Code As String = Nothing
    Public RSM_CODE As String = Nothing
    Public Location_CODE As String = Nothing
#End Region
    'Anand Ticket no:BM00000003994
    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        'Dim qry As String = "select Zone_Code as [Code],Description as [Zone Name],Created_By as [Created By],Created_Date as [Created Date],Modified_By as [Modify By],Modified_Date as [Modify Date],Comp_Code as [Company Code] from TSPL_ZONE_MASTER  "
        Dim qry As String = "select Zone_Code as [Code],Description as [Zone Name],Location_Code as [Location Code] from TSPL_ZONE_MASTER  "
        str = clsCommon.ShowSelectForm("RPTZONEFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'

    Public Shared Function SaveData(ByVal obj As ClsZoneMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Dim IsSaved As Boolean = False
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
            clsCommon.AddColumnsForChange(coll, "Description_Hindi", obj.Description_Hindi, True, True)
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "City_Code", obj.City_Code, True)
            clsCommon.AddColumnsForChange(coll, "RSM_CODE", obj.RSM_CODE, True)
            clsCommon.AddColumnsForChange(coll, "Location_CODE", obj.Location_CODE, True)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_ZONE_MASTER where Zone_Code='" & obj.Zone_Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Zone_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.ZoneMaster, "", "")
                        If clsCommon.myLen(obj.Zone_Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                clsCommon.AddColumnsForChange(coll, "Zone_Code", obj.Zone_Code)
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_ZONE_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_ZONE_MASTER", OMInsertOrUpdate.Update, "TSPL_ZONE_MASTER.Zone_Code='" + obj.Zone_Code + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return IsSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsZoneMaster
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsZoneMaster
        Dim obj As ClsZoneMaster = Nothing
        Dim Arr As List(Of ClsZoneMaster) = Nothing
        Dim qry As String = "select Zone_Code ,Description,City_Code,RSM_CODE,Location_Code, Description_Hindi from TSPL_ZONE_MASTER where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_ZONE_MASTER.Zone_Code = (select MIN(Zone_Code) from TSPL_ZONE_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_ZONE_MASTER.Zone_Code = (select Max(Zone_Code) from TSPL_ZONE_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_ZONE_MASTER.Zone_Code = (select TOP 1 Zone_Code from TSPL_ZONE_MASTER WHERE 1=1 " + whrclas + " and Zone_Code='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_ZONE_MASTER.Zone_Code = (select Min(Zone_Code) from TSPL_ZONE_MASTER where Zone_Code > '" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_ZONE_MASTER.Zone_Code = (select Max(Zone_Code) from TSPL_ZONE_MASTER where Zone_Code < '" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsZoneMaster()
            obj.Zone_Code = clsCommon.myCstr(dt.Rows(0)("Zone_Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
            obj.City_Code = clsCommon.myCstr(dt.Rows(0)("City_Code"))
            obj.RSM_CODE = clsCommon.myCstr(dt.Rows(0)("RSM_CODE"))
            obj.Location_CODE = clsCommon.myCstr(dt.Rows(0)("Location_CODE"))
            obj.Description_Hindi = clsCommon.myCstr(dt.Rows(0)("Description_Hindi"))
        End If
        Return obj
    End Function

    Public Shared Function GetName(ByVal strCode As String) As String
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Description from TSPL_ZONE_MASTER where Zone_Code='" + strCode + "'"))
    End Function
End Class


Public Class clsDistrictMaster
#Region "Variables"
    Public Code As String = Nothing
    Public Name As String = Nothing
    Public State_Code As String = Nothing
    Public State_Name As String = Nothing
    Public Region_Code As String = Nothing
    Public Region_Name As String = Nothing
#End Region

    Public Shared Function SaveData(ByVal obj As clsDistrictMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Dim IsSaved As Boolean = False
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Name", obj.Name)
            clsCommon.AddColumnsForChange(coll, "State_Code", obj.State_Code, True)
            clsCommon.AddColumnsForChange(coll, "Region_Code", obj.Region_Code, True)
            clsCommon.AddColumnsForChange(coll, "Modify_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modify_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_DISTRICT_MASTER where Code='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.DistrictMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_DISTRICT_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_DISTRICT_MASTER", OMInsertOrUpdate.Update, "Code='" + obj.Code + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return IsSaved
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsDistrictMaster
        Dim obj As clsDistrictMaster = Nothing
        Dim qry As String = "select TSPL_DISTRICT_MASTER.*,TSPL_STATE_MASTER.STATE_NAME,TSPL_REGION_MASTER.REGION_NAME from TSPL_DISTRICT_MASTER  left outer join  TSPL_STATE_MASTER on TSPL_STATE_MASTER.STATE_CODE=TSPL_DISTRICT_MASTER.State_Code left outer join TSPL_REGION_MASTER on TSPL_REGION_MASTER.REGION_CODE=TSPL_DISTRICT_MASTER.Region_Code  where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_DISTRICT_MASTER.Code = (select MIN(Code) from TSPL_DISTRICT_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_DISTRICT_MASTER.Code = (select Max(Code) from TSPL_DISTRICT_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_DISTRICT_MASTER.Code = (select TOP 1 Code from TSPL_DISTRICT_MASTER WHERE 1=1 " + whrclas + " and Code='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_DISTRICT_MASTER.Code = (select Min(Code) from TSPL_DISTRICT_MASTER where Code > '" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_DISTRICT_MASTER.Code = (select Max(Code) from TSPL_DISTRICT_MASTER where Code < '" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsDistrictMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("Name"))
            obj.State_Code = clsCommon.myCstr(dt.Rows(0)("State_Code"))
            obj.State_Name = clsCommon.myCstr(dt.Rows(0)("STATE_NAME"))
            obj.Region_Code = clsCommon.myCstr(dt.Rows(0)("Region_Code"))
            obj.Region_Name = clsCommon.myCstr(dt.Rows(0)("REGION_NAME"))
        End If
        Return obj
    End Function

    Public Shared Function GetName(ByVal strCode As String) As String
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Name from TSPL_DISTRICT_MASTER where Code='" + strCode + "'"))
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim qry As String = ""
        Try
            qry = "Delete from TSPL_DISTRICT_MASTER where TSPL_DISTRICT_MASTER.Code='" + strCode + "'"
            clsDBFuncationality.ExecuteNonQuery(qry)
        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function

    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_DISTRICT_MASTER.Code,TSPL_DISTRICT_MASTER.Name,TSPL_DISTRICT_MASTER.State_Code,TSPL_State_MASTER.STATE_NAME from TSPL_DISTRICT_MASTER left outer join TSPL_State_MASTER on TSPL_State_MASTER.STATE_CODE=TSPL_DISTRICT_MASTER.State_Code "
        str = clsCommon.ShowSelectForm("DistciFnd", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str

    End Function

    Public Shared Function CheckNewEntry(ByVal Code As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "select Code from TSPL_DISTRICT_MASTER where Code ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry, trans)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
End Class


Public Class clsAreaMaster
#Region "Variables"
    Public Code As String = Nothing
    Public Name As String = Nothing
    Public Zone_Code As String = Nothing
    Public Zone_Name As String = Nothing
#End Region

    Public Shared Function SaveData(ByVal obj As clsAreaMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Dim IsSaved As Boolean = False
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Name", obj.Name)
            clsCommon.AddColumnsForChange(coll, "Zone_Code", obj.Zone_Code, True)
            clsCommon.AddColumnsForChange(coll, "Modify_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modify_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_AREA_MASTER where Code='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.AreaMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_AREA_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_AREA_MASTER", OMInsertOrUpdate.Update, "Code='" + obj.Code + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return IsSaved
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsAreaMaster
        Dim obj As clsAreaMaster = Nothing
        Dim qry As String = "select TSPL_AREA_MASTER.*,TSPL_ZONE_MASTER.Description as ZoneName from TSPL_AREA_MASTER  left outer join  TSPL_ZONE_MASTER on TSPL_ZONE_MASTER.Zone_Code=TSPL_AREA_MASTER.Zone_Code  where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_AREA_MASTER.Code = (select MIN(Code) from TSPL_AREA_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_AREA_MASTER.Code = (select Max(Code) from TSPL_AREA_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_AREA_MASTER.Code = (select TOP 1 Code from TSPL_AREA_MASTER WHERE 1=1 " + whrclas + " and Code='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_AREA_MASTER.Code = (select Min(Code) from TSPL_AREA_MASTER where Code > '" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_AREA_MASTER.Code = (select Max(Code) from TSPL_AREA_MASTER where Code < '" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsAreaMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("Name"))
            obj.Zone_Code = clsCommon.myCstr(dt.Rows(0)("Zone_Code"))
            obj.Zone_Name = clsCommon.myCstr(dt.Rows(0)("ZoneName"))
        End If
        Return obj
    End Function

    Public Shared Function GetName(ByVal strCode As String) As String
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Name from TSPL_AREA_MASTER where Code='" + strCode + "'"))
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim qry As String = ""
        Try
            qry = "Delete from TSPL_AREA_MASTER where TSPL_AREA_MASTER.Code='" + strCode + "'"
            clsDBFuncationality.ExecuteNonQuery(qry)
        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function

    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "select TSPL_AREA_MASTER.Code,TSPL_AREA_MASTER.Name,TSPL_AREA_MASTER.Zone_Code,TSPL_ZONE_MASTER.Description as ZoneName from TSPL_AREA_MASTER  left outer join  TSPL_ZONE_MASTER on TSPL_ZONE_MASTER.Zone_Code=TSPL_AREA_MASTER.Zone_Code "
        str = clsCommon.ShowSelectForm("AreaFnd", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str

    End Function

    Public Shared Function CheckNewEntry(ByVal Code As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "select Code from TSPL_AREA_MASTER where Code ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry, trans)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
End Class
