'----Add By- Sanjay 29/08/2018 Ticket No- BHA/28/08/18-000490
Imports System.Data.SqlClient
Imports common

Public Class clsCustomerComplaintMaster
#Region "Variables"
    Public Code As String = Nothing
    Public Description As String = Nothing
    Public Type As String = Nothing

#End Region
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "  select TSPL_CUSTOMER_COMPLAINT_MASTER.Code,TSPL_CUSTOMER_COMPLAINT_MASTER.Description from TSPL_CUSTOMER_COMPLAINT_MASTER   "
        str = clsCommon.ShowSelectForm("ComplaintMst@FND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function

    Public Function SaveData(ByVal arr As List(Of clsCustomerComplaintMaster), ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Dim trans As SqlTransaction = Nothing
        Try
            trans = clsDBFuncationality.GetTransactin()
            For Each obj As clsCustomerComplaintMaster In arr
                Dim coll As New Hashtable()
                clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
                clsCommon.AddColumnsForChange(coll, "Type", obj.Type)
                clsCommon.AddColumnsForChange(coll, "Modify_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Modify_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))

                If clsDBFuncationality.getSingleValue("Select count(*) from  TSPL_CUSTOMER_COMPLAINT_MASTER where Code='" + obj.Code + "' ", trans) <= 0 Then

                    'If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    ' obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.JWInwardFormula, "", "")
                    'End If

                    clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                    clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                    clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_CUSTOMER_COMPLAINT_MASTER", OMInsertOrUpdate.Insert, "", trans)
                Else
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_CUSTOMER_COMPLAINT_MASTER", OMInsertOrUpdate.Update, "TSPL_CUSTOMER_COMPLAINT_MASTER.Code='" + obj.Code + "'", trans)
                End If
            Next
            If isSaved Then
                trans.Commit()
            End If
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function




    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsCustomerComplaintMaster
        Dim obj As clsCustomerComplaintMaster = Nothing
        Dim qry As String = "select TSPL_CUSTOMER_COMPLAINT_MASTER.* from TSPL_CUSTOMER_COMPLAINT_MASTER   where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_CUSTOMER_COMPLAINT_MASTER.Code = (select MIN(Code) from TSPL_CUSTOMER_COMPLAINT_MASTER where 1=1 )"
            Case NavigatorType.Last
                qry += " and TSPL_CUSTOMER_COMPLAINT_MASTER.Code = (select Max(Code) from TSPL_CUSTOMER_COMPLAINT_MASTER where 1=1 )"
            Case NavigatorType.Next
                qry += " and TSPL_CUSTOMER_COMPLAINT_MASTER.Code = (select Min(Code) from TSPL_CUSTOMER_COMPLAINT_MASTER where Code>'" + strCode + "' )"
            Case NavigatorType.Previous
                qry += " and TSPL_CUSTOMER_COMPLAINT_MASTER.Code = (select Max(Code) from TSPL_CUSTOMER_COMPLAINT_MASTER where Code<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and TSPL_CUSTOMER_COMPLAINT_MASTER.Code = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsCustomerComplaintMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
            obj.Type = clsCommon.myCstr(dt.Rows(0)("Type"))

        End If
        Return obj
    End Function


    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        If (clsCommon.myLen(strCode) <= 0) Then
            Throw New Exception("Code not found to Delete")
        End If

        Dim qry As String = "delete from TSPL_CUSTOMER_COMPLAINT_MASTER where Code='" + strCode + "'"
        Return clsDBFuncationality.ExecuteNonQuery(qry)

    End Function

    Public Shared Function GetName(ByVal strCode As String) As String
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Description from TSPL_CUSTOMER_COMPLAINT_MASTER where Code='" + strCode + "'"))
    End Function



End Class
