Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.Data
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports common
Public Class frmBatchManufacturingMaster
    Inherits FrmMainTranScreen
    Private isNewEntry As Boolean = False

    Private Sub frmBatchManufacturingMaster_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub

    Private Sub btnclose_Click(sender As Object, e As EventArgs) Handles btnclose.Click
        Me.Close()
    End Sub

    Private Sub btnReset_Click(sender As Object, e As EventArgs) Handles btnReset.Click
        funreset()
    End Sub
    Public Sub funreset()
        isNewEntry = True

        fndCode.MyReadOnly = False
        fndCode.Value = ""
        txtname.Text = ""
        btnsave.Text = "Save"
        btndelete.Enabled = False
    End Sub

    Private Sub btnsave_Click(sender As Object, e As EventArgs) Handles btnsave.Click
        Try
            If AllowToSave() Then
                Dim obj As New ClsbatchmanufacturingMaster()
                obj.CODE = fndCode.Value
                obj.Name = txtname.Text
                Dim trans As SqlTransaction = Nothing
                If (obj.SaveData(obj, True, trans)) Then
                    trans = clsDBFuncationality.GetTransactin()
                    trans.Commit()
                    common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                    LoadData(obj.CODE, NavigatorType.Current)
                Else
                    trans.Rollback()
                End If
            End If

        Catch ex As Exception
            'trans.Rollback()
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(fndCode.Value) <= 0 Then
            myMessages.blankValue(Me, "Code", Me.Text)
            fndCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtname.Text) <= 0 Then
            myMessages.blankValue(Me, "Name", Me.Text)
            txtname.Focus()
            Return False
        End If
        Return True
    End Function
    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub
    Public Sub DeleteData()
        If btndelete.Enabled = False Then
            Exit Sub
        End If
        If fndCode.Value = "" Then
            myMessages.blankValue(Me, fndCode.MyLinkLable1.Text, Me.Text)
            fndCode.Focus()
        ElseIf myMessages.deleteConfirm() Then
            If (ClsbatchmanufacturingMaster.DeleteData(fndCode.Value)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully", Me.Text)
                funreset()
            End If
        End If
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndCode._MYValidating
        Dim qst As String = "select count(*) from TSPL_BATCH_MANUFECTURING_MASTER where CODE='" + fndCode.Value + "'"
        Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qst))
        If count = 0 Then
            fndCode.MyReadOnly = False
        Else
            fndCode.MyReadOnly = True
        End If
        If fndCode.MyReadOnly OrElse isButtonClicked Then
            Dim whrClas As String = ""
            Dim qry As String = " select CODE as [CODE],NAME as [DESCRIPTION],Created_Date as [Created Date],Modify_Date as [Modify Date] from TSPL_BATCH_MANUFECTURING_MASTER  "
            fndCode.Value = clsCommon.ShowSelectForm("RPTBDMST", qry, "CODE", whrClas, fndCode.Value, "CODE", isButtonClicked)
            LoadData(fndCode.Value, NavigatorType.Current)
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndCode._MYNavigator
        Try
            LoadData(fndCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try

    End Sub

    Public Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Try
            fndCode.MyReadOnly = True
            btnsave.Enabled = True
            btndelete.Enabled = True
            isNewEntry = False
            Dim obj As Object = New ClsbatchmanufacturingMaster()
            obj = ClsbatchmanufacturingMaster.GetData(strCode, NavTyep)
            If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.CODE) > 0) Then
                'funreset()
                isNewEntry = False

                btnsave.Text = "Update"
                fndCode.Value = obj.CODE
                txtname.Text = obj.Name
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub

    Private Sub fndCode__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles fndCode._MYValidating
        Dim qst As String = "select count(*) from TSPL_BATCH_MANUFECTURING_MASTER where Code='" + fndCode.Value + "'"
        Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qst))
        If count = 0 Then
            fndCode.MyReadOnly = False
        Else
            fndCode.MyReadOnly = True
        End If
        If fndCode.MyReadOnly OrElse isButtonClicked Then
            'Dim whrClas As String = ""
            'Dim qry As String = " select Code as [Code],Name as [Name],Created_Date as [Created Date],Modify_Date as [Modify Date] from TSPL_BATCH_MANUFECTURING_MASTER  "
            ' fndCode.Value = clsCommon.ShowSelectForm("RPTBDMST", qry, "Code", whrClas, fndCode.Value, "Code", isButtonClicked)
            LoadData(fndCode.Value, NavigatorType.Current)
        End If
    End Sub

    Private Sub fndCode__MYNavigator(sender As Object, e As EventArgs, NavType As NavigatorType) Handles fndCode._MYNavigator
        Try
            LoadData(fndCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
End Class