Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports System.Data
Imports System.Data.SqlClient
Imports System.Windows.Forms
Imports System.Configuration
Imports Telerik.Collections.Generic
Imports common
Imports Excel = Microsoft.Office.Interop.Excel
'Start date =12/6/2011
'End date =12/6/2011
'Database =TSPlERP
' Tables=Tspl_Chapter_head

Public Class frmChapterHead

    Inherits FrmMainTranScreen

    Dim userCode, companyCode As String
    'This Cunstructer is used to send usercode and compcode data in table.
    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub
    Dim dt As DataTable
    Private Sub SetUserMgmtNew()
        ''MyBase.SetUserMgmt(clsUserMgtCode.chapterhead)
        If Not (MyBase.isReadFlag) Then
            '--------richa Ticket no. BM00000003121 15/07/2014 
            Throw New Exception("Permission Denied")
        End If
        rdbtnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 02/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If rdbtnSave.Visible = True Then
            rdmenuimport.Enabled = True
            rdmenuexport.Enabled = True
        Else
            rdmenuimport.Enabled = False
            rdmenuexport.Enabled = False
        End If
        '--------------------------------------------------
        '         btnclose.Visible = MyBase.isDeleteFlag 
        rdbtnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub frmChapterHead_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso rdbtnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso rdbtnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            Close()
        End If
    End Sub
    Private Sub frmChapterHead_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        fndchapterhead.MyMaxLength = 20
        fndchapterhead.MyCharacterCasing = CharacterCasing.Upper
        'globalFunc.mandatoryText(fndchapterhead.Value)
        AddHandler fndchapterhead.KeyPress, AddressOf KeyPress1
        AddHandler fndchapterhead.TextChanged, AddressOf text_changed
        If fndchapterhead.Value = "" Then
            rdtxtchapterdesc.Text = ""
            rdbtnDelete.Enabled = False
        End If
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub
    Private Sub KeyPress1(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If
    End Sub
    Private Sub text_changed(ByVal sender As System.Object, ByVal e As System.EventArgs)
        'changes by abhishek as on 15/10/2012 for sqldatareader
        Dim var As String
        var = clsDBFuncationality.getSingleValue("select chapter_head_code from tspl_chapter_head where chapter_head_code='" + fndchapterhead.Value + "'")

        If var <> fndchapterhead.Value Then
            rdtxtchapterdesc.Text = ""
            rdbtnSave.Text = "Save"
            fndchapterhead.MyReadOnly = False
            rdbtnDelete.Enabled = False
        ElseIf var <> "" Then

            funfill()
        Else
            rdtxtchapterdesc.Text = ""
            rdbtnSave.Text = "Save"
            fndchapterhead.MyReadOnly = False
            rdbtnDelete.Enabled = False

        End If

        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub
    Private Sub funInsert()
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from tspl_chapter_head where chapter_head_code='" & fndchapterhead.Value & "'")
                If ChkNewEntry = 0 Then
                    fndchapterhead.Value = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.ChapterHead, "", "")
                    If clsCommon.myLen(fndchapterhead.Value) <= 0 Then
                        Throw New Exception("Error in Code Generation")
                    End If
                End If
            End If
            connectSql.RunSp("sp_chapterhead_insert", New SqlParameter("@chapterhead", fndchapterhead.Value), New SqlParameter("@chapterheaddesc", rdtxtchapterdesc.Text), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate()), New SqlParameter("@ModifyBy", userCode), New SqlParameter("@ModifyDate", connectSql.serverDate()), New SqlParameter("@ComCode", companyCode))
            myMessages.insert()
            rdbtnSave.Text = "Update"
            rdbtnDelete.Enabled = True
            'If userCode <> "ADMIN" Then
            '    If funSetUserAccess() = False Then Exit Sub
            'End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub rdbtnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnSave.Click
        SaveData()
    End Sub
    Sub SaveData()

        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso fndchapterhead.Value = "" Then
            myMessages.blankValue(Me, "Code", Me.Text)
            fndchapterhead.Focus()
        Else
            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.chapterhead, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If
            If rdbtnSave.Text = "Save" Then
                funInsert()
            ElseIf rdbtnSave.Text = "Update" Then
                funUpdate()
            End If
        End If
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub
    'update vendor Type Details
    Private Sub funUpdate()
        If fndchapterhead.Value = "" Then
            myMessages.blankValue(Me, "Code", Me.Text)
        Else
            Try
                connectSql.RunSp("sp_chapterhead_update", New SqlParameter("@chapterhead", fndchapterhead.Value), New SqlParameter("@chapterheaddesc", rdtxtchapterdesc.Text), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate()), New SqlParameter("@ModifyBy", userCode), New SqlParameter("@ModifyDate", connectSql.serverDate()), New SqlParameter("@ComCode", companyCode))
                myMessages.update()
                rdbtnSave.Text = "Update"
                fndchapterhead.MyReadOnly = True
            Catch ex As Exception
                myMessages.myExceptions(ex)
            End Try
        End If
    End Sub
    Private Sub funReset()
        fndchapterhead.Value = ""
        fndchapterhead.MyReadOnly = False
        rdtxtchapterdesc.Text = ""
        rdbtnSave.Text = "Save"
        fndchapterhead.MyReadOnly = False
        rdbtnDelete.Enabled = False
        fndchapterhead.Focus()
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub
    Private Sub funDelete()
        Try
            connectSql.RunSp("sp_chapterhead_delete", New SqlParameter("@chapterhead", fndchapterhead.Value))
            myMessages.delete()
            rdbtnSave.Text = "Save"
            fndchapterhead.MyReadOnly = False
            rdbtnDelete.Enabled = False
            'If userCode <> "ADMIN" Then
            '    If funSetUserAccess() = False Then Exit Sub
            'End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Public Sub funfill()
        'changes by abhishek as on 15/10/2012 for sqldatareader
        Dim query As String = "select description from tspl_chapter_head where chapter_head_code='" + fndchapterhead.Value() + "'"
        dt = clsDBFuncationality.GetDataTable(query)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            For Each dr As DataRow In dt.Rows
                rdtxtchapterdesc.Text = dr(0).ToString()
                rdbtnSave.Text = "Update"
                fndchapterhead.MyReadOnly = True
                rdbtnDelete.Enabled = True

            Next

        End If

        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
    End Sub
    Private Sub rdbtnreset_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnreset.Click
        funReset()
    End Sub


    Private Sub rdbtnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If fndchapterhead.Value <> "" Then
            If myMessages.deleteConfirm() Then
                funDelete()
            Else

            End If
        End If
    End Sub
    'Private Sub fndvendorId_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
    '    fndchapterhead.ConnectionString = connectSql.SqlCon()
    '    fndchapterhead.Query = "select chapter_head_Code as [Chapter Head Code],Description as [Description] from tspl_chapter_head"
    '    fndchapterhead.ValueToSelect = "Chapter Head Code"
    '    fndchapterhead.ValueToSelect1 = "Description"
    '    fndchapterhead.Caption = "Chapter Head Details"
    'End Sub

    Private Sub rdmenuexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexport.Click
        Dim query As String = "select chapter_head_Code as [Code],Description  as [Description] from TSPL_chapter_head "
        transportSql.ExporttoExcel(query, Me)
    End Sub

    Private Sub rdmenuimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuimport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        If transportSql.importExcel(gv, "Code", "Description") Then
            Dim trans As SqlTransaction = Nothing
            Try
                connectSql.OpenConnection()
                trans = clsDBFuncationality.GetTransactin()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim strchapterhead As String
                    Dim strDesc As String
                    If String.IsNullOrEmpty(grow.Cells(0).Value.ToString()) Then
                        myMessages.blankValue(Me, "Code", Me.Text)
                        trans.Rollback()
                        Exit Sub
                    ElseIf grow.Cells(0).Value.ToString().Length > 12 Then
                        common.clsCommon.MyMessageBoxShow(Me, "Code cannot be greater than 12 length.", Me.Text)
                        trans.Rollback()
                        Exit Sub
                    Else
                        strchapterhead = grow.Cells(0).Value.ToString().ToUpper()
                    End If
                    If grow.Cells(1).Value.ToString().Length > 50 Then
                        common.clsCommon.MyMessageBoxShow(Me, "Description cannot be greater than 50 length", Me.Text)
                        trans.Rollback()
                        Exit Sub
                    Else
                        strDesc = grow.Cells(1).Value.ToString()
                    End If

                    'Dim sql1 As String = "select COUNT(*) from TSPL_CHAPTER_HEAD  where chapter_head_Code='" + strchapterhead + "'"
                    'Dim i As Integer = CInt(connectSql.RunScalar(sql1))
                    'If (i = 0) Then
                    Try
                        connectSql.RunSpTransaction(trans, "sp_chapterhead_insert", New SqlParameter("@chapterhead", strchapterhead), New SqlParameter("chapterheaddesc", strDesc), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate(trans)), New SqlParameter("@ModifyBy", userCode), New SqlParameter("@ModifyDate", connectSql.serverDate(trans)), New SqlParameter("@ComCode", companyCode))
                    Catch ex As Exception
                        Dim s1 As String = ex.ToString().Substring(0, 46)
                        If ex.ToString().Substring(0, 46) = "System.Data.SqlClient.SqlException: Violation " Then
                            connectSql.RunSpTransaction(trans, "sp_chapterhead_update", New SqlParameter("@chapterhead", strchapterhead), New SqlParameter("@chapterheaddesc", strDesc), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate(trans)), New SqlParameter("@ModifyBy", userCode), New SqlParameter("@ModifyDate", connectSql.serverDate(trans)), New SqlParameter("@ComCode", companyCode))
                        End If
                    End Try

                Next
                trans.Commit()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                myMessages.myExceptions(ex)
                trans.Rollback()

            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub
    Private Sub rdbtnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbtnClose.Click
        Me.Close()
    End Sub
    'priti added on 01-06-2011 --- To implement the access control
    'Private Function funSetUserAccess() As Boolean
    '    Try
    '        'If funCheckLoginStatus() = False Then Exit Function
    '        Dim strRights As String
    '        Dim strTemp() As String
    '        Dim strProgCode = "CHAP-M"
    '        strRights = enuUserRights.enuRead & "," & enuUserRights.enuModify & "," & enuUserRights.enuDelete
    '        strRights = modUserMgt.funGetPermissions(strRights, strProgCode)
    '        strTemp = Split(strRights, ",")
    '        If strTemp(0) = "0" Then
    '            MsgBox("Permission Denied", MsgBoxStyle.Critical, Me.Text)
    '            funSetUserAccess = False
    '            blnRead = False
    '            Me.Close()
    '            Exit Function
    '        Else
    '            blnRead = True
    '        End If
    '        If strTemp(1) = "0" Then 'Grant modify access
    '            rdbtnSave.Enabled = False
    '        End If
    '        If strTemp(2) = "0" Then 'Grant modify access
    '            rdbtnDelete.Enabled = False
    '        End If
    '        funSetUserAccess = True
    '    Catch er As Exception

    '    End Try
    'End Function

    Private Sub rdmenuexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexit.Click
        Me.Close()
    End Sub

    

    Private Sub fndchapterhead__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndchapterhead._MYValidating
        Dim str As String = "select count(*) from tspl_chapter_head where chapter_head_Code ='" + fndchapterhead.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 Then
            fndchapterhead.MyReadOnly = False
        Else
            fndchapterhead.MyReadOnly = True
        End If

        If fndchapterhead.MyReadOnly OrElse isButtonClicked Then
            Dim qry As String = "select chapter_head_Code as Code,Description as [Description] from tspl_chapter_head"
            fndchapterhead.Value = clsCommon.ShowSelectForm("fmItemLocation", qry, "Code", "", fndchapterhead.Value, "", isButtonClicked)
            LoadData()
        End If
    End Sub
    Sub LoadData()
        'changes by abhishek as on 15/10/2012 for sqldatareader
        Dim var As String
        var = clsDBFuncationality.getSingleValue("select chapter_head_code from tspl_chapter_head where chapter_head_code='" + fndchapterhead.Value + "'")
        If var <> fndchapterhead.Value Then
            rdtxtchapterdesc.Text = ""
            rdbtnSave.Text = "Save"
            rdbtnDelete.Enabled = False
        ElseIf var <> "" Then

            funfill()
        Else
            rdtxtchapterdesc.Text = ""
            rdbtnSave.Text = "Save"
            rdbtnDelete.Enabled = False

        End If

    End Sub

    Private Sub fndchapterhead__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndchapterhead._MYNavigator
        Dim qst As String = "select chapter_head_Code as Code,Description as [Description] from tspl_chapter_head where 2=2 "
        Select Case NavType
            Case NavigatorType.Current
                qst += " and tspl_chapter_head .chapter_head_Code in ('" + fndchapterhead.Value + "')"
            Case NavigatorType.Next
                qst += " and tspl_chapter_head .chapter_head_Code in (select min(chapter_head_Code ) from tspl_chapter_head where chapter_head_Code  >'" + fndchapterhead.Value + "')"
            Case NavigatorType.First
                qst += " and tspl_chapter_head .chapter_head_Code in (select MIN(chapter_head_Code ) from tspl_chapter_head)"

            Case NavigatorType.Last
                qst += " and tspl_chapter_head .chapter_head_Code in (select Max(chapter_head_Code ) from tspl_chapter_head)"
            Case NavigatorType.Previous
                qst += " and tspl_chapter_head .chapter_head_Code in (select Max(chapter_head_Code ) from tspl_chapter_head where chapter_head_Code  <'" + fndchapterhead.Value + "')"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            fndchapterhead.Value = clsCommon.myCstr(dt.Rows(0)("Code"))
            rdtxtchapterdesc.Text = clsCommon.myCstr(dt.Rows(0)("Description"))
        End If
        LoadData()
    End Sub
End Class
