'--18/11/2013--form Add By- Panch Raj ---------
'--------------BM00000003305----------------------common form made for vendor/customer/location/item
Imports common
Imports System.Data
Imports System.Data.SqlClient
Public Class frmItemCategoryStructure
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim userCode, companyCode, FormType As String
    Dim strCatStrPass As String = ""

#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String
    Const colCategoryLevelCode As String = "CategoryLevelCode"
    Const colDescription As String = "Description"
    Const colCategoryLevel As String = "CategoryLevel"
    Const colLineNo As String = "LineNo"

    Dim CategoryLevelCode As GridViewTextBoxColumn
    Dim Description As GridViewTextBoxColumn
    Dim CategoryLevel As GridViewTextBoxColumn

    Dim Errorcontrol As clsErrorControl = New clsErrorControl()
#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click
        Save()
    End Sub
    Public Sub New(ByVal user As String, ByVal company As String, ByVal form_type As String)
        InitializeComponent()
        userCode = user
        companyCode = company
        FormType = form_type
    End Sub
    Public Sub Save()
        If AllowToSave() Then

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(strCatStrPass, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If
            Dim obj As New clsItemCategoryStructure()
            obj.ITEM_CATEGORY_STRUCT_CODE = txtCode.Value
            obj.DESCRIPTION = Me.txtDescription.Text
            obj.ObjList = New List(Of clsItemCategoryStructureDetails)
            obj.formtype = FormType

            For Each grow As GridViewRowInfo In gvStructLevels.Rows
                Dim objTr As New clsItemCategoryStructureDetails()
                objTr.ITEM_CATEGORY_STRUCT_CODE = clsCommon.myCstr(Me.txtCode.Value)
                objTr.ITEM_CATEGORY_CODE = clsCommon.myCstr(grow.Cells(colCategoryLevelCode).Value)
                objTr.CATEGORY_LEVEL = clsCommon.myCstr(grow.Cells(colCategoryLevel).Value)
                objTr.formtype_detail = FormType
                objTr.Line_No = CInt(clsCommon.myCdbl(grow.Cells(colLineNo).Value))

                obj.ObjList.Add(objTr)
            Next
            Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
            If (obj.SaveData(obj, isNewEntry, trans)) Then
                trans.Commit()
                common.clsCommon.MyMessageBoxShow("Data Saved Successfully")
                LoadData(obj.ITEM_CATEGORY_STRUCT_CODE, NavigatorType.Current)
            Else
                trans.Rollback()
                '    common.clsCommon.MyMessageBoxShow("This '" & obj.Code & "' already exist ")
            End If

        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnsave.Enabled = True
        btndelete.Enabled = False
        isNewEntry = False


        Dim obj As New clsItemCategoryStructure()
        obj = clsItemCategoryStructure.GetData(strCode, FormType, NavTyep)

        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.ITEM_CATEGORY_STRUCT_CODE) > 0) Then
            funReset()
            isNewEntry = False
            btnsave.Text = "Update"
            btndelete.Enabled = True
            txtCode.Value = obj.ITEM_CATEGORY_STRUCT_CODE
            txtDescription.Text = obj.DESCRIPTION

            txtCode.MyReadOnly = True
            LoadItemCategoryLevels()
            Dim ii As Int16 = 0
            If obj.ObjList IsNot Nothing AndAlso obj.ObjList.Count > 0 Then
                LoadGridColumns(gvStructLevels)
                For Each objTr As clsItemCategoryStructureDetails In obj.ObjList
                    gvStructLevels.Rows.AddNew()
                    ii = ii + 1
                    gvStructLevels.Rows(gvStructLevels.Rows.Count - 1).Cells(colCategoryLevelCode).Value = objTr.ITEM_CATEGORY_CODE
                    gvStructLevels.Rows(gvStructLevels.Rows.Count - 1).Cells(colDescription).Value = objTr.ITEM_CATEGORY_DESCRIPTION
                    gvStructLevels.Rows(gvStructLevels.Rows.Count - 1).Cells(colCategoryLevel).Value = objTr.CATEGORY_LEVEL
                    gvStructLevels.Rows(gvStructLevels.Rows.Count - 1).Cells(colLineNo).Value = objTr.Line_No
                Next
            End If
        End If
    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(txtCode.Value) <= 0 Then
                clsCommon.MyMessageBoxShow("Fill Code", Me.Text)
                txtCode.Focus()
                txtCode.Select()
                Errorcontrol.SetError(txtCode, "Fill Code")
                Return False
            Else
                Errorcontrol.ResetError(txtCode)
            End If
        End If
        
        If clsCommon.myLen(txtDescription.Text) <= 0 Then
            clsCommon.MyMessageBoxShow("Fill Description", Me.Text)
            txtDescription.Focus()
            txtDescription.Select()
            Errorcontrol.SetError(txtDescription, "Fill Description")
            Return False
        Else
            Errorcontrol.ResetError(txtDescription)
        End If
        If Me.gvStructLevels.Rows.Count = 0 Then
            myMessages.blankValue("Second List is Empty")
            gvStructLevels.Focus()
            Errorcontrol.SetError(gvStructLevels, "Second List is Empty")
            Return False
        Else
            Errorcontrol.ResetError(gvStructLevels)
        End If

        RefershLineNo()

        Return True
    End Function

    'Function CheckExistingLevel()
    '    Dim strq As String
    '    If isNewEntry = True Then
    '        strq = "select category_level from TSPL_ITEM_CATEGORY_STRUCTURE where category_level=" & Me.txtCategoryLevel.Value & ""
    '    Else
    '        strq = "select category_level from TSPL_ITEM_CATEGORY_STRUCTURE where category_level=" & Me.txtCategoryLevel.Value & " and ITEM_CATEGORY_STRUCT_CODE !='" & clsCommon.myCstr(Me.txtCode.Value) & "'"
    '    End If

    '    Dim dt As DataTable
    '    dt = clsDBFuncationality.GetDataTable(strq)
    '    If dt.Rows.Count > 0 Then
    '        Return False
    '    End If
    '    Return True
    'End Function

    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub

    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow("You Cannot Delete Record")
            Exit Sub
        End If
        'Dim discCode As String
        'discCode = clsDBFuncationality.getSingleValue("select Discount_Code  from TSPL_SHIPMENT_DETAILS  where Discount_Code ='" & txtCode.Value & "'")
        'If clsCommon.myLen(discCode) > 0 Then
        '    common.clsCommon.MyMessageBoxShow("This record can't be deleted.It is used in another process")
        '    Exit Sub
        'End If

        funDelete()


    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsItemCategoryStructure.DeleteData(txtCode.Value, FormType)) Then
                    common.clsCommon.MyMessageBoxShow("Data Deleted Successfully ")
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub txtCode_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCode.KeyPress
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If
    End Sub

    Private Sub frmItemCategoryStructure_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        LoadGridColumns(gvCategoryLevels)
        LoadGridColumns(gvStructLevels)
        isNewEntry = True
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        '  ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")
        funReset()
    End Sub

    Private Sub SetUserMgmtNew()

        If clsCommon.CompairString(FormType, "ITEM") = CompairStringResult.Equal Then
            ''MyBase.SetUserMgmt(clsUserMgtCode.frmItemCategoryStructure)
            strCatStrPass = clsUserMgtCode.frmItemCategoryStructure
        ElseIf clsCommon.CompairString(FormType, "VENDOR") = CompairStringResult.Equal Then
            ''MyBase.SetUserMgmt(clsUserMgtCode.frmVendorCategoryStructure)
            strCatStrPass = clsUserMgtCode.frmVendorCategoryStructure
        ElseIf clsCommon.CompairString(FormType, "CUSTOMER") = CompairStringResult.Equal Then
            ''MyBase.SetUserMgmt(clsUserMgtCode.frmCustomerCategoryStructure)
            strCatStrPass = clsUserMgtCode.frmCustomerCategoryStructure
        ElseIf clsCommon.CompairString(FormType, "LOCATION") = CompairStringResult.Equal Then
            ''MyBase.SetUserMgmt(clsUserMgtCode.frmLocationCategoryStructure)
            strCatStrPass = clsUserMgtCode.frmLocationCategoryStructure
        End If
        If Not (MyBase.isReadFlag) Then
            '--------richa Ticket no. BM00000003121 15/07/2014 
            Throw New Exception("Permission Denied")
        End If
        btnsave.Visible = MyBase.isModifyFlag
        'btnPost.Visible = MyBase.isPostFlag
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtDescription.ReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        txtDescription.Text = ""
        Me.gvCategoryLevels.Rows.Clear()
        Me.gvStructLevels.Rows.Clear()
        Me.gvCategoryLevels.Rows.AddNew()
        LoadItemCategoryLevels()

        btnsave.Text = "Save"
        btnsave.Enabled = True
        btndelete.Enabled = False
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        funClose()

    End Sub

    Sub funClose()
        clsERPFuncationality.closeForm(Me)
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        Try
            Dim str As String = "select count(*) from TSPL_ITEM_CATEGORY_STRUCTURE where ITEM_CATEGORY_STRUCT_CODE ='" + txtCode.Value + "' and isnull(form_type,'item')='" + FormType + "' "
            Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
            If no = 0 AndAlso isButtonClicked = False Then
                txtCode.MyReadOnly = False
                'txtCode.Value = ""
                '' common.clsCommon.MyMessageBoxShow("Value doesn't exist ")
            Else
                txtCode.MyReadOnly = True
            End If
            If txtCode.MyReadOnly OrElse isButtonClicked Then

                'Dim qry As String = " select ITEM_CATEGORY_STRUCT_CODE as Code,  description from TSPL_ITEM_CATEGORY_STRUCTURE "
                'txtCode.Value = clsCommon.ShowSelectForm("TSPL_ITEM_CATEGORY_STRUCTURE", qry, "Code", "", txtCode.Value, "ITEM_CATEGORY_STRUCT_CODE", isButtonClicked)
                txtCode.Value = clsItemCategoryStructure.getFinder(" isnull(form_type,'item')='" + FormType + "'", txtCode.Value, isButtonClicked)
                txtCode.Text = clsItemCategoryStructure.GetData(txtCode.Value, FormType, Nothing).ITEM_CATEGORY_STRUCT_CODE
                If txtCode.Value <> "" Then
                    LoadData(txtCode.Value, NavigatorType.Current)
                Else
                    funReset()
                End If
            End If
        Catch ex As Exception

        End Try
       
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub frmItemCategoryStructure_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Sub LoadGridColumns(ByVal gv As RadGridView)
        gv.DataSource = Nothing
        gv.Rows.Clear()
        gv.Columns.Clear()

        'gv.ReadOnly = True

        CategoryLevelCode = New GridViewTextBoxColumn()
        CategoryLevelCode.FormatString = ""
        CategoryLevelCode.HeaderText = "S.No."
        CategoryLevelCode.Name = colLineNo
        CategoryLevelCode.Width = 60
        CategoryLevelCode.ReadOnly = True
        CategoryLevelCode.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft
        gv.Columns.Add(CategoryLevelCode)

        CategoryLevelCode = New GridViewTextBoxColumn()
        CategoryLevelCode.FormatString = ""
        CategoryLevelCode.HeaderText = "Category Level"
        CategoryLevelCode.Name = colCategoryLevelCode
        CategoryLevelCode.Width = 100
        CategoryLevelCode.ReadOnly = True
        CategoryLevelCode.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft
        gv.Columns.Add(CategoryLevelCode)

        Description = New GridViewTextBoxColumn()
        Description.FormatString = ""
        Description.HeaderText = "Description"
        Description.Name = colDescription
        Description.Width = 150
        Description.ReadOnly = True
        Description.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft
        gv.Columns.Add(Description)

        CategoryLevel = New GridViewTextBoxColumn()
        CategoryLevel.FormatString = ""
        CategoryLevel.HeaderText = "CategoryLevel"
        CategoryLevel.Name = colCategoryLevel
        CategoryLevel.Width = 100
        CategoryLevel.ReadOnly = True
        CategoryLevel.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft
        gv.Columns.Add(CategoryLevel)


    End Sub
    Sub LoadItemCategoryLevels()
        Dim strq As String
        If isNewEntry = True Then
            strq = " select * from TSPL_ITEM_CATEGORY_LEVEL where isnull(form_type,'item')='" + FormType + "'"
        Else
            strq = " select * from TSPL_ITEM_CATEGORY_LEVEL WHERE isnull(form_type,'item')='" + FormType + "' and CATEGORY_LEVEL NOT IN (SELECT CATEGORY_LEVEL FROM  TSPL_ITEM_CATEGORY_STRUCT_DETAIL WHERE ITEM_CATEGORY_STRUCT_CODE='" & clsCommon.myCstr(Me.txtCode.Value) & "' and isnull(form_type,'item')='" + FormType + "')"
        End If

        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(strq)
        Me.gvCategoryLevels.Rows.Clear()

        For intloop As Integer = 0 To dt.Rows.Count - 1
            Me.gvCategoryLevels.Rows.AddNew()
            Me.gvCategoryLevels.Rows(intloop).Cells(colLineNo).Value = Me.gvCategoryLevels.Rows.Count
            Me.gvCategoryLevels.Rows(intloop).Cells(colCategoryLevelCode).Value = dt.Rows(intloop).Item("ITEM_CATEGORY_CODE")
            Me.gvCategoryLevels.Rows(intloop).Cells(colDescription).Value = dt.Rows(intloop).Item("DESCRIPTION")
            Me.gvCategoryLevels.Rows(intloop).Cells(colCategoryLevel).Value = dt.Rows(intloop).Item("CATEGORY_LEVEL")
        Next
    End Sub




    'Function CheckForExisingRecord() As Boolean
    '    If clsCommon.myLen(txtPayPeriodCode.Value) > 0 And clsCommon.myLen(txtEmpCode.Value) > 0 Then
    '        Dim str As String = "select LVALLOTMENT_CODE from TSPL_LEAVE_ALLOTMENT where PAY_PERIOD_CODE ='" + txtPayPeriodCode.Value + "' and EMP_CODE ='" + txtEmpCode.Value + "' and LVALLOTMENT_CODE <>'" + txtCode.Value + "' "
    '        Dim Code As String = clsCommon.myCstr(clsDBFuncationality.getSingleValue(str))
    '        If clsCommon.myLen(Code) > 0 Then
    '            Dim strmessage As String = "Record Exists for Selected Employee for Selected Pay Period on Allotment Code " + Code + ", New Record can not be genrated on same. Do you want to open Previous Saved ? "
    '            If clsCommon.MyMessageBoxShow(strmessage, Me.Text, MessageBoxButtons.YesNo, RadMessageIcon.Question) = System.Windows.Forms.DialogResult.Yes Then
    '                LoadData(Code, NavigatorType.Current)
    '            End If
    '            Return False
    '        End If
    '    End If
    '    Return True
    'End Function

    Private Sub rdbNext_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdbNext.Click
        Try
            If gvCategoryLevels.CurrentRow.Index >= 0 Then
                Me.gvStructLevels.Rows.AddNew()
                Me.gvStructLevels.Rows(Me.gvStructLevels.Rows.Count - 1).Cells(colLineNo).Value = Me.gvStructLevels.Rows.Count
                Me.gvStructLevels.Rows(Me.gvStructLevels.Rows.Count - 1).Cells(colCategoryLevelCode).Value = Me.gvCategoryLevels.CurrentRow.Cells(colCategoryLevelCode).Value
                Me.gvStructLevels.Rows(Me.gvStructLevels.Rows.Count - 1).Cells(colDescription).Value = Me.gvCategoryLevels.CurrentRow.Cells(colDescription).Value
                Me.gvStructLevels.Rows(Me.gvStructLevels.Rows.Count - 1).Cells(colCategoryLevel).Value = Me.gvCategoryLevels.CurrentRow.Cells(colCategoryLevel).Value
                gvCategoryLevels.Rows.RemoveAt(Me.gvCategoryLevels.CurrentRow.Index)
            End If
        Catch ex As Exception
        End Try
    End Sub

    Private Sub btnBack_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnBack.Click
        Try
            If gvStructLevels.CurrentRow.Index >= 0 Then
                Me.gvCategoryLevels.Rows.AddNew()
                Me.gvCategoryLevels.Rows(Me.gvCategoryLevels.Rows.Count - 1).Cells(colCategoryLevelCode).Value = Me.gvStructLevels.CurrentRow.Cells(colCategoryLevelCode).Value
                Me.gvCategoryLevels.Rows(Me.gvCategoryLevels.Rows.Count - 1).Cells(colDescription).Value = Me.gvStructLevels.CurrentRow.Cells(colDescription).Value
                Me.gvCategoryLevels.Rows(Me.gvCategoryLevels.Rows.Count - 1).Cells(colCategoryLevel).Value = Me.gvStructLevels.CurrentRow.Cells(colCategoryLevel).Value
                gvStructLevels.Rows.RemoveAt(Me.gvStructLevels.CurrentRow.Index)
                RefershLineNo()
            End If
        Catch ex As Exception
        End Try

    End Sub

    Private Sub RefershLineNo()
        For Each grow As GridViewRowInfo In gvStructLevels.Rows
            grow.Cells(colLineNo).Value = grow.Index + 1
        Next
        For Each grow As GridViewRowInfo In gvCategoryLevels.Rows
            grow.Cells(colLineNo).Value = grow.Index + 1
        Next
    End Sub
End Class
