''Added By Pankaj Kumar Chaudhary
''Date-25/09/2011
''

Imports common
Imports System.Data.SqlClient
Public Class FrmItemCategory1
    Inherits FrmMainTranScreen
#Region "Variables"
    Public Category_Code As String = Nothing
    Dim iStxtTaxGroup_TxtChangedComplete As Boolean = True
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False


    Const colLineNo As String = "LNO"
    Const colComplete As String = "COMPLETE"
    Const colICode As String = "ICODE"
    Const colIName As String = "INAME"
    Const colBalanceQty As String = "BALANCEQTY"
    Const colQty As String = "QTY"
    Const colUnit As String = "COLTAX3"
    Const colRate As String = "RATE"
    Const colAmt As String = "AMT"
    Const colVendorCode As String = "VCODE"
    Const colVendorName As String = "VNAME"
    ''Const colLocationCode As String = "LOCATION"
    ''Const colLocationName As String = "LOCATIONNAME"
    Const colVendorItemNo As String = "VENDORITEMNO"
    Const colOrderNo As String = "ORDERNO"
    Dim ButtonToolTip As ToolTip = New ToolTip()

    Dim repoBalQty As GridViewDecimalColumn
    Dim repoComplete As GridViewTextBoxColumn
    Dim userCode, companyCode As String     ''Added On Date 30/09/2011
    Dim Qry As String                       ''Added On Date 30/09/2011
#End Region


    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub

    Private Sub FrmItemCategory1_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        'If Not clsCommon.CompairString(objCommonVar.CurrentUserCode, "ADMIN") = CompairStringResult.Equal Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
        SetUserMgmtNew()
        'TxtCategoryCode.Value.CharacterCasing = CharacterCasing.Upper
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnAddNew, "Press Alt+N Adding New Trasnaction")
        TxtCategoryCode.MyReadOnly = True
        TxtCategoryCode.MyMaxLength = 30        ''''Valiadets The Length Of Finder(txtCategoryCode)
        tbCategoryName.MaxLength = 200          ''''Validates The Length Of TextBox(tbCategoryName)
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If


        AddNew()
    End Sub

    Sub BlankAllControls()
        TxtCategoryCode.Value = Nothing
        tbCategoryName.Text = ""
    End Sub
    Private Sub SetUserMgmtNew()
        ''MyBase.SetUserMgmt(clsUserMgtCode.mbtnItemCategory)
        If Not (MyBase.isReadFlag) Then
            '--------richa Ticket no. BM00000003121 15/07/2014 
            Throw New Exception("Permission Denied")
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 02/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            RadMenuItemImport.Enabled = True
            RadMenuItemExportt.Enabled = True
        Else
            RadMenuItemImport.Enabled = False
            RadMenuItemExportt.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub
    Private Sub btnAddNew_Click_1(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnAddNew.Click
        AddNew()
    End Sub


    Sub AddNew()
        BlankAllControls()
        TxtCategoryCode.Focus()
        TxtCategoryCode.MyReadOnly = False
        isNewEntry = True
        btnSave.Text = "Save"
        btnSave.Enabled = True
        'btnPost.Enabled = True
        btnDelete.Enabled = True

    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(TxtCategoryCode.Value) <= 0 Then
                common.clsCommon.MyMessageBoxShow(Me, "Please Enter Category Code", Me.Text)
                TxtCategoryCode.Focus()
                Return False
            End If
        End If
        Return True
    End Function


    Private Sub btnSave_Click_1(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        SaveData()
    End Sub

    Sub SaveData()
        Try
            If (AllowToSave()) Then

                If MyBase.isModifyonPasswordFlag Then
                    If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.mbtnItemCategory, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                    Else
                        Return
                    End If
                End If
                Dim obj As New ClsItemCategory()
                obj.Category_Code = (TxtCategoryCode.Value).ToString
                obj.Category_Name = tbCategoryName.Text
                If (obj.SaveData(obj, isNewEntry)) Then
                    If btnSave.Text = "Save" Then
                        common.clsCommon.MyMessageBoxShow(Me, "Data Has Been Saved Successfully", Me.Text)
                    Else
                        common.clsCommon.MyMessageBoxShow(Me, "Data Has Been Updated Successfully", Me.Text)
                    End If

                    LoadData(obj.Category_Code, NavigatorType.Current)
                End If
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Sub LoadData(ByVal Category_Code As String, ByVal navType As common.NavigatorType)
        Try
            btnSave.Enabled = True
            'btnPost.Enabled = True
            btnDelete.Enabled = True
            isInsideLoadData = True
            isNewEntry = False
            btnSave.Text = "Update"
            BlankAllControls()
            TxtCategoryCode.MyReadOnly = True

            Dim obj As New ClsItemCategory()
            obj = ClsItemCategory.GetData(Category_Code, navType)
            If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Category_Code) > 0) Then
                TxtCategoryCode.Value = obj.Category_Code
                tbCategoryName.Text = obj.Category_Name

            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        Finally
            isInsideLoadData = False
        End Try
    End Sub

    Private Sub btnClose_Click_1(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        CloseForm()
    End Sub

    Private Sub RadMenuItemExit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenuItemExit.Click
        CloseForm()
    End Sub

    Sub CloseForm()
        Me.Close()
    End Sub

    'Private Sub btnPost_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnPost.Click
    '    PostData()
    'End Sub

    'Sub PostData()
    '    Try
    '        If (myMessages.postConfirm()) Then
    '            If (clsRequistionHead.PostData(txtItemCode.Value)) Then
    '                common.clsCommon.MyMessageBoxShow("Data Posted Successfully ")
    '                LoadData(txtReqNo.Value, NavigatorType.Current)
    '            End If
    '        End If
    '    Catch ex As Exception
    '        common.clsCommon.MyMessageBoxShow(ex.Message)
    '    End Try
    'End Sub

    Private Sub btnDelete_Click_1(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub

    Sub DeleteData()
        Try
            If (myMessages.deleteConfirm()) Then
                If (ClsItemCategory.DeleteData(TxtCategoryCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    AddNew()
                End If
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    'Private Function funSetUserAccess() As Boolean
    '    Try
    '        btnSave.Visible = True
    '        btnDelete.Visible = True
    '        'btnPost.Visible = True

    '        Dim strRights As String
    '        Dim strTemp() As String
    '        Dim strProgCode = "ITEM-CAT"
    '        strRights = enuUserRights.enuRead & "," & enuUserRights.enuModify & "," & enuUserRights.enuDelete & "," & enuUserRights.enuAuthorised
    '        strRights = modUserMgt.funGetPermissions(strRights, strProgCode)
    '        strTemp = Split(strRights, ",")
    '        If strTemp(0) = "0" Then
    '            MsgBox("Permission Denied", MsgBoxStyle.Critical, Me.Text)
    '            funSetUserAccess = False
    '            blnRead = False
    '            Me.Close()
    '            Exit Function
    '        Else
    '            blnRead = True
    '        End If
    '        If strTemp(1) = "0" Then 'Grant modify access
    '            btnSave.Visible = False
    '        End If
    '        If strTemp(2) = "0" Then 'Grant modify access
    '            btnDelete.Visible = False
    '        End If
    '        If strTemp(3) = "0" Then 'Grant Authorize access
    '            'btnPost.Visible = False
    '        End If
    '        funSetUserAccess = True
    '    Catch er As Exception

    '    End Try
    'End Function


    Private Sub TxtCategoryCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles TxtCategoryCode._MYNavigator
        Try
            LoadData(TxtCategoryCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub



    '   Private Sub btnPrint_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnPrint.Click
    '       If txtItemCode.Value = "" Then
    '           myMessages.blankValue("Requisition Number")
    '       Else
    '           funPrint()
    '       End If

    '   End Sub

    '   Private Sub funPrint()
    '       Dim qry As String = "select TSPL_REQUISITION_HEAD.Requisition_Id ,TSPL_REQUISITION_HEAD.Requisition_Date ,TSPL_REQUISITION_HEAD.Expire_Date ,TSPL_REQUISITION_HEAD.Require_Date ,TSPL_REQUISITION_HEAD.Ref_No ,TSPL_REQUISITION_HEAD.Description,TSPL_REQUISITION_HEAD.Remarks ,TSPL_REQUISITION_DETAIL.Item_Code ,TSPL_REQUISITION_DETAIL.Item_Desc ,TSPL_REQUISITION_DETAIL.Unit_Code ,TSPL_REQUISITION_DETAIL.Requisition_Qty ,TSPL_VENDOR_MASTER.Vendor_Name,TSPL_REQUISITION_HEAD.Comments ,TSPL_COMPANY_MASTER.Comp_Name ,TSPL_COMPANY_MASTER.Logo_Img ,TSPL_COMPANY_MASTER.Logo_Img2  from TSPL_REQUISITION_HEAD join TSPL_REQUISITION_DETAIL on TSPL_REQUISITION_HEAD.Requisition_Id =TSPL_REQUISITION_DETAIL.Requisition_Id " & _
    '" left outer join TSPL_COMPANY_MASTER on  TSPL_REQUISITION_HEAD.Comp_Code = TSPL_COMPANY_MASTER.Comp_Code left outer join TSPL_VENDOR_MASTER on TSPL_REQUISITION_DETAIL.Vendor_Code =TSPL_VENDOR_MASTER.Vendor_Code  where  2=2 "
    '       If txtItemCode.Value <> "" Then
    '           qry += " and  TSPL_REQUISITION_HEAD.Requisition_Id='" + txtItemCode.Value + "'"
    '       End If

    '       Try
    '           Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
    '           PurchaseOrderViewer.funreport(dt, "PurchaseRequisition", "Purchase Requisition")
    '       Catch ex As Exception
    '           common.clsCommon.MyMessageBoxShow(ex.Message)
    '       End Try
    '   End Sub

    Private Sub TxtCategoryCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles TxtCategoryCode._MYValidating
        Dim str As String = "select count(*) from TSPL_Item_Category where Category_Code ='" + TxtCategoryCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 Then
            TxtCategoryCode.MyReadOnly = False
        Else
            TxtCategoryCode.MyReadOnly = True
        End If
        If TxtCategoryCode.MyReadOnly OrElse isButtonClicked Then
            Dim qry As String = "select Category_Code as CategoryCode,Category_Name as CategoryName  from TSPL_Item_Category "
            TxtCategoryCode.Value = clsCommon.ShowSelectForm("Category_Selector", qry, "CategoryCode", "", TxtCategoryCode.Value, "CategoryCode", isButtonClicked)
            'tbCategoryName.Text = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select category_name from tspl_Item_category where category_code='" + TxtCategoryCode.Value + "'"))
            LoadData(TxtCategoryCode.Value, NavigatorType.Current)
        End If
    End Sub


    Private Sub tbCategoryName_TextChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles tbCategoryName.TextChanged
        tbCategoryName.MaxLength = 200
    End Sub


    Private Sub TxtCategoryCode_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles TxtCategoryCode.KeyPress
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If

    End Sub

    Private Sub FrmItemCategory1_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnAddNew.Enabled Then
            AddNew()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            CloseForm()
        End If
    End Sub

    Private Sub RadMenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenuItemImport.Click
        Import()
    End Sub

    Private Sub RadMenuItemExportt_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenuItemExportt.Click
        Export()
    End Sub

    ''
    ''Added On Date 30/09/2011 by Pankaj Kumar Chaudhary
    ''
    Public Sub Import()
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Category Code", "Category Name") Then
            Dim trans As SqlTransaction = Nothing
            Try
                'connectSql.OpenConnection()
                trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim strCtgryCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    Dim strCtgryName As String = clsCommon.myCstr(grow.Cells(1).Value)

                    If (String.IsNullOrEmpty(strCtgryCode)) Or clsCommon.myLen(strCtgryCode) > 12 Then
                        Throw New Exception("Category Code can not be blank or incorrect")
                    End If

                    If (String.IsNullOrEmpty(strCtgryName)) Or clsCommon.myLen(strCtgryName) > 50 Then
                        Throw New Exception(" Category Name  can not be blank or incorrect")
                    End If

                    Dim sql1 As String = "select count(*) from TSPL_Item_Category where Category_Code='" + strCtgryCode + "'"
                    Dim i As Integer = CInt(clsDBFuncationality.getSingleValue(sql1, trans))
                    If (i = 0) Then
                        Qry = "INSERT Into TSPL_Item_Category values('" + strCtgryCode + "','" + strCtgryName + "','" + userCode + "','" + clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy") + "','" + userCode + "','" + clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy") + "','" + companyCode + "')"
                        clsDBFuncationality.ExecuteNonQuery(Qry, trans)
                        'connectSql.RunSql(Qry)
                        'connectSql.RunSpTransaction(trans, "sp_DesignationMaster_insert", New SqlParameter("@Category Code", strCtgryCode), New SqlParameter("@Category Name", strCtgryName), New SqlParameter("@createdby", userCode), New SqlParameter("@createddate", connectSql.serverDate()), New SqlParameter("@modifiedby", userCode), New SqlParameter("@modifieddate", connectSql.serverDate()), New SqlParameter("@compcode", companyCode))
                    Else
                        Qry = "UPDATE TSPL_Item_CAtegory set Category_Code='" + strCtgryCode + "', Category_Name='" + strCtgryName + "', Modify_By='" + userCode + "', Modify_Date='" + clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy") + "', Comp_Code='" + companyCode + "' WHERE Category_Code='" + strCtgryCode + "'"
                        clsDBFuncationality.ExecuteNonQuery(Qry, trans)
                        'connectSql.RunSql(Qry)
                        'connectSql.RunSpTransaction(trans, "sp_DesignationMaster_update", New SqlParameter("@CAtegory Code", strCtgryCode), New SqlParameter("@Category Name", strCtgryName), New SqlParameter("@modifiedby", userCode), New SqlParameter("@modifieddate", connectSql.serverDate()), New SqlParameter("@compcode", companyCode))

                    End If
                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                trans.Rollback()
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)

            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    ''
    ''Added On Date 30/09/2011 by Pankaj Kumar Chaudhary
    ''
    Public Sub Export()
        Dim str As String
        str = "select Category_Code As [Category Code],Category_Name as [Category Name] from TSPL_Item_Category"
        transportSql.ExporttoExcel(str, Me)
    End Sub


End Class
