
'--------Created By Richa 25/08/2014 Against Ticket No BM00000003507
'' updation by Richa Agarwal Against Ticket No BM00000003929

Imports common
Imports System.Data.SqlClient
Public Class FrmCostCentreGroupStores
    Inherits FrmMainTranScreen
#Region "Variables"


    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String

#End Region


#Region "User Defined Functions and Subroutines"

    Public Sub New()
        InitializeComponent()
    End Sub
#End Region

    Private Sub FrmCostCentreGroupStores_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub
    Private Sub FrmCostCentreGroupStores_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        funReset()
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update Transaction")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D for Delete Transaction")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(rdbtnreset, "Press Alt+N for New Transaction")
    End Sub


    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.FrmCostCentreGroupStores)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")

        End If
        btnSave.Visible = MyBase.isModifyFlag

        If btnSave.Visible = True Then
            RmExport.Enabled = True
            RmImport.Enabled = True
        Else
            RmExport.Enabled = False
            RmImport.Enabled = False
        End If

        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub
    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(fndCode.Value) <= 0 Then
                myMessages.blankValue(Me, "Code", Me.Text)
                fndCode.Focus()
                Return False
            End If
        End If

        If clsCommon.myLen(txtdescription.Text) <= 0 Then
            myMessages.blankValue(Me, "Description", Me.Text)
            txtdescription.Focus()
            Return False
        End If
        Return True
    End Function
    Private Sub DeleteData()
        Try
            If (deleteConfirm()) Then
                If (ClsCostCentreGroupStores.DeleteData(fndCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Private Sub RmImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RmImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Cost Center Code", "Description") Then
            ' Dim trans As SqlTransaction
            Try
                
                'clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New ClsCostCentreGroupStores()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells("Cost Center Code").Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.CostCenter_Code = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells("Description").Value)
                    If strName.Length > 100 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Description can not be blank or incorrect.")
                    End If
                    obj.Description = strName

                    obj.SaveData(obj, ClsCostCentreGroupStores.CheckNewEntry(obj.CostCenter_Code))
                Next
                'clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                'clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub RmExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RmExport.Click
        Dim str As String
        str = "select CostCenter_Code as [Cost Center Code],Description from TSPL_COST_CENTRE_GROUP_MASTER"
        transportSql.ExporttoExcel(str, Me)
    End Sub
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        'fndCode.MyReadOnly = True
        'btnSave.Enabled = True
        'btnDelete.Enabled = True
        Dim obj As New ClsCostCentreGroupStores()
        obj = ClsCostCentreGroupStores.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.CostCenter_Code) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            fndCode.Value = obj.CostCenter_Code
            txtdescription.Text = obj.Description
            btnSave.Enabled = True
            btnDelete.Enabled = True
            fndCode.MyReadOnly = True
        End If

    End Sub
    Private Sub SaveData()
        If AllowToSave() Then

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.FrmCostCentreGroupStores, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If
            Dim obj As New ClsCostCentreGroupStores()
            'If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
            '    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("select  count(*) from  TSPL_COST_CENTRE_GROUP_MASTER where CostCenter_Code='" & fndCode.Value & "'")
            '    If ChkNewEntry = 0 Then
            '        obj.CostCenter_Code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.CostCenterGroupStore, "", "")
            '        If clsCommon.myLen(obj.CostCenter_Code) <= 0 Then
            '            clsCommon.MyMessageBoxShow("Error In Document No Genertion")
            '            Exit Sub
            '        End If
            '    Else
            '        obj.CostCenter_Code = fndCode.Value
            '    End If
            'Else
            '    obj.CostCenter_Code = fndCode.Value
            'End If
           
            obj.CostCenter_Code = fndCode.Value
            obj.Description = txtdescription.Text

            If (obj.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow("Data Saved Successfully")
                LoadData(obj.CostCenter_Code, NavigatorType.Current)
            End If
        End If
    End Sub
    Private Sub rdbtnreset_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles rdbtnreset.Click
        funReset()
    End Sub
    Sub funReset()
        isNewEntry = True
        fndCode.MyReadOnly = False
        fndCode.Value = Nothing
        fndCode.Focus()
        txtdescription.Text = ""
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = False
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()
    End Sub
    Sub funClose()
        Me.Close()
        GC.Collect()
    End Sub

    Private Sub fndCode__MYNavigator(ByVal sender As Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndCode._MYNavigator
        Try
            LoadData(fndCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try

    End Sub

    Private Sub fndCode__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndCode._MYValidating
        Dim str As String = "select count(*) from TSPL_COST_CENTRE_GROUP_MASTER where CostCenter_Code ='" + fndCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            fndCode.MyReadOnly = False
        Else
            fndCode.MyReadOnly = True
        End If
        If fndCode.MyReadOnly OrElse isButtonClicked Then
            fndCode.Value = ClsCostCentreGroupStores.getFinder("", fndCode.Value, isButtonClicked)
            If fndCode.Value <> "" Then
                LoadData(fndCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If
    End Sub

    Private Sub btnDelete_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub

    Private Sub btnSave_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnSave.Click
        SaveData()
    End Sub
End Class
