Imports common
Imports System.Data.SqlClient
Public Class FrmRequisitSubTypeMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.RequisitSubTypeMaster)
        If Not (MyBase.isReadFlag) Then
            '--------------richa 15/07/2014 Ticket No BM00000003124---------
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 03/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            rmExport.Enabled = True
            rmImport.Enabled = True
        Else
            rmExport.Enabled = False
            rmImport.Enabled = False
        End If
        '--------------------------------------------------
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub
    Private Sub FrmRequisitSubTypeMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        LoadRequestType()
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update Trasnaction")
          ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnAddNew, "Press Alt+N Adding New Trasnaction")
    End Sub

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        SaveData()
    End Sub
    Private Sub SaveData()
        Try
            If AllowToSave() Then

                If MyBase.isModifyonPasswordFlag Then
                    If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.RequisitSubTypeMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                    Else
                        Return
                    End If
                End If
                Dim obj As New ClsRequisitSubTypeMaster()
                obj.Code = clsCommon.myCstr(txtCode.Value)
                obj.Description = clsCommon.myCstr(txtDesc.Text)
                obj.Type = clsCommon.myCstr(cboItemType.SelectedValue)
                Dim count As Integer = clsDBFuncationality.getSingleValue("select count(code) from TSPL_Requisit_SubType_Master where code='" + obj.Code + "' ")
                Dim isNewEntry As Boolean = True
                If (count <> 0) Then
                    isNewEntry = False
                End If
                If (obj.SaveData(obj, isNewEntry)) Then
                    RadMessageBox.Show("Data Saved Successfully")
                    LoadData(obj.Code, NavigatorType.Current)
                End If
            End If
        Catch ex As Exception
            RadMessageBox.Show(ex.Message)
        End Try
    End Sub
    Private Sub LoadRequestType()
        Dim dtLevel As New DataTable
        dtLevel.Columns.Add("Code", GetType(String))
        dtLevel.Columns.Add("Desc", GetType(String))
        dtLevel.Rows.Add("0", "Others")
        dtLevel.Rows.Add("1", "IT Goods")
        dtLevel.Rows.Add("2", "Non IT Goods")
        dtLevel.Rows.Add("3", "IT Services")
        dtLevel.Rows.Add("4", " Non IT Services")
        cboItemType.DataSource = dtLevel
        cboItemType.ValueMember = "Code"
        cboItemType.DisplayMember = "Desc"
    End Sub
    Sub LoadData(ByVal strDocumentNo As String, ByVal navType As common.NavigatorType)
        Try
            Reset()
            Dim obj As New ClsRequisitSubTypeMaster()
            obj = ClsRequisitSubTypeMaster.GetData(strDocumentNo, navType)
            If (obj IsNot Nothing) Then
                txtCode.Value = obj.Code
                txtDesc.Text = obj.Description
                cboItemType.SelectedValue = clsCommon.myCstr(obj.Type)
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Private Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myCstr(txtCode.Value) = "" Then
                clsCommon.MyMessageBoxShow("Please enter Code")
                Return False
            End If
        End If
        If clsCommon.myCstr(txtDesc.Text) = "" Then
            clsCommon.MyMessageBoxShow("Please enter Description")
            Return False
        End If
        Return True
    End Function

   
    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            Dim qst As String = "select count(*) from TSPL_Requisit_SubType_Master where code='" + txtCode.Value + "'"
            Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qst))
            If count = 0 Then
                txtCode.MyReadOnly = False
            Else
                txtCode.MyReadOnly = True
            End If
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating


       

        Dim str As String = "select count(*) from TSPL_Requisit_SubType_Master where code ='" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 Then
            txtCode.MyReadOnly = False
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = "select Code, Description as [Description]  from TSPL_Requisit_SubType_Master "
            'txtCode.Value = clsCommon.ShowSelectForm("SubTY", qry, "Code", "", txtCode.Value, "Code", isButtonClicked)
            txtCode.Value = ClsRequisitSubTypeMaster.getFinder("", txtCode.Value, isButtonClicked)
            'FillData()
            LoadData(txtCode.Value, NavigatorType.Current)
        End If
    End Sub

    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Sub AddNew()
        txtCode.Value = ""
        txtDesc.Text = ""
        LoadRequestType()
        txtCode.MyReadOnly = False
    End Sub
    Sub DeleteData()
        Try
            If (myMessages.deleteConfirm()) Then
                If (ClsRequisitSubTypeMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    AddNew()
                End If
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow("Currently Code is in use")
        End Try
    End Sub

    Private Sub btnAddNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnAddNew.Click
        AddNew()
    End Sub

    Private Sub FrmRequisitSubTypeMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnAddNew.Enabled Then
            AddNew()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            Me.Close()
        End If
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        Me.Close()
    End Sub

    Private Sub rmExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmExport.Click
        Dim str As String
        str = "select Code,DESCRIPTION ,Type  from TSPL_Requisit_SubType_Master "
        transportSql.ExporttoExcel(str, Me)
    End Sub
    ' ------------------------- preeti Gupta------------------BM00000002845---------
    Private Sub rmImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "DESCRIPTION", "Type") Then
            Dim linno As Integer = 0
            Try
                connectSql.OpenConnection()


                clsCommon.ProgressBarShow()


                For Each grow As GridViewRowInfo In gv.Rows
                    'Dim trans As SqlTransaction
                    'trans = clsDBFuncationality.GetTransactin()
                    Dim obj As New ClsRequisitSubTypeMaster()

                    linno += 1
                    Dim strcode As String = clsCommon.myCstr(grow.Cells("Code").Value)
                    If (String.IsNullOrEmpty(strcode)) Or clsCommon.myLen(strcode) > 30 Then
                        Throw New Exception("Length of  Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Code = strcode

                    Dim strDescription As String = clsCommon.myCstr(grow.Cells("DESCRIPTION").Value)
                    If (String.IsNullOrEmpty(strDescription)) Or clsCommon.myLen(strDescription) > 200 Then
                        Throw New Exception("Length of Description should be max. 200 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Description = strDescription

                    Dim strType As String = clsCommon.myCstr(grow.Cells("Type").Value)
                    If (String.IsNullOrEmpty(strType)) Or clsCommon.myLen(strType) > 30 Then
                        Throw New Exception("Length of Type should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    ElseIf clsCommon.CompairString(strType, "Others") = CompairStringResult.Equal Or clsCommon.CompairString(strType, "IT Goods") = CompairStringResult.Equal Or clsCommon.CompairString(strType, "Non IT Goods") = CompairStringResult.Equal Or clsCommon.CompairString(strType, "It Services") = CompairStringResult.Equal Or clsCommon.CompairString(strType, "Non It Services") = CompairStringResult.Equal Then

                    Else
                        Throw New Exception("Type should be amoung 'Others','IT Goods','Non IT Goods','IT Services','Non IT Services' At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Type = strType

                    

                    obj.SaveData(obj, True)
                Next
                ' trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception

                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub
End Class
