'--24/06/2013--form Add By- Pradeep Sharma ---------
Imports common
Imports System.Data
Imports XpertERPEngine
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI

Public Class frmLeaveMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String

#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click
        Save()
    End Sub

    Public Sub Save()
        If AllowToSave() Then

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmLeaveMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            Dim obj As New clsLeaveMaster()
            obj.Code = txtCode.Value
            obj.Name = txtName.Text
            obj.PRINT_NAME = txtPrintName.Text
            obj.AFFECTS_SALARY = CboAffectsSal.SelectedValue
            obj.LEAVE_TYPE = cboLeaveType.SelectedValue
            obj.APPLY_LEAVE_TYPE_DED = cboLeaveTypeDed.SelectedValue
            If (obj.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                LoadData(obj.Code, NavigatorType.Current)
                'Else
                '    common.clsCommon.MyMessageBoxShow("This '" & obj.Code & "' already exist ")
            End If

        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        ''txtCode.MyReadOnly = True
        btnsave.Enabled = True
        btndelete.Enabled = True
        isNewEntry = False
        Dim obj As New clsLeaveMaster()
        obj = clsLeaveMaster.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
            funReset()
            isNewEntry = False
            btnsave.Text = "Update"
            txtCode.Value = obj.Code
            txtName.Text = obj.Name
            txtPrintName.Text = obj.PRINT_NAME
            CboAffectsSal.SelectedValue = obj.AFFECTS_SALARY
            cboLeaveType.SelectedValue = obj.LEAVE_TYPE
            cboLeaveTypeDed.SelectedValue = obj.APPLY_LEAVE_TYPE_DED
        End If

    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
            myMessages.blankValue(Me, " Code ", Me.Text)
            txtCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtName.Text) <= 0 Then
            myMessages.blankValue(Me, " Name ", Me.Text)
            txtName.Focus()
            Return False
        ElseIf clsCommon.myLen(txtPrintName.Text) <= 0 Then
            myMessages.blankValue(Me, " Print Name ", Me.Text)
            txtPrintName.Focus()
            Return False
        ElseIf clsCommon.myLen(CboAffectsSal.SelectedIndex) <= -1 Then
            myMessages.blankValue(Me, " Affects Salary ", Me.Text)
            CboAffectsSal.Focus()
            Return False
        ElseIf clsCommon.myLen(cboLeaveType.SelectedIndex) <= -1 Then
            myMessages.blankValue(Me, " Leave Type ", Me.Text)
            cboLeaveType.Focus()
            Return False
        End If
        Return True
    End Function

    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub

    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "You Cannot Delete Record", Me.Text)
            Exit Sub
        End If
        'Dim discCode As String
        'discCode = clsDBFuncationality.getSingleValue("select LEAVE_CODE  from TSPL_SHIPMENT_DETAILS  where LEAVE_CODE ='" & txtCode.Value & "'")
        'If clsCommon.myLen(discCode) > 0 Then
        '    common.clsCommon.MyMessageBoxShow("This record can't be deleted.It is used in another process")
        '    Exit Sub
        'End If
        '' Code Ends 
        funDelete()
    End Sub

    Sub funDelete()
        Try
            Dim Reason As String = ""
            If (myMessages.deleteConfirm()) Then
                If clsCancelLog.CheckForReasonOnDelete() Then
                    '' REASON FOR DELETE 
                    Dim frm As New FrmFreeTxtBox1
                    frm.Text = "Remarks for Delete"
                    frm.ShowDialog()
                    If clsCommon.myLen(frm.strRmks) <= 0 Then
                        Exit Sub
                    Else
                        Reason = frm.strRmks
                    End If
                End If
                If (clsLeaveMaster.DeleteData(txtCode.Value)) Then
                    saveCancelLog(Reason, "Delete", Nothing)
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub
    Function saveCancelLog(ByVal Reason As String, ByVal Activity_Type As String, Optional ByVal trans As System.Data.SqlClient.SqlTransaction = Nothing) As Boolean
        Dim obj As New clsCancelLog
        obj.Program_Code = Form_ID
        obj.DOCUMENT_NO = clsCommon.myCstr(Me.txtCode.Value)
        obj.REASON = Reason
        obj.ACTIVITY_TYPE = Activity_Type
        Return clsCancelLog.SaveData(obj, True, trans)
    End Function

    Private Sub frmLeaveMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isNewEntry = True
        funReset()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        '  ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")
        createtable()
    End Sub


    Sub createtable()
        Dim coll As Dictionary(Of String, String)
        coll = New Dictionary(Of String, String)()
        coll.Add("APPLY_LEAVE_TYPE_DED", "BIT NOT NULL Default 0")
        clsCommonFunctionality.CreateOrAlterTable("TSPL_LEAVE_MASTER", coll)
    End Sub

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmLeaveMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnsave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 02/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnsave.Visible = True Then
            MenuItemImport.Enabled = True
            MenuItemExport.Enabled = True
        Else
            MenuItemImport.Enabled = False
            MenuItemExport.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        cboLeaveType.DataSource = clsLeaveMaster.GetCboLeaveTypeDataTable()
        cboLeaveType.ValueMember = "Code"
        cboLeaveType.DisplayMember = "Name"
        cboLeaveType.SelectedValue = "Other"

        txtName.Text = ""
        txtPrintName.Text = ""
        CboAffectsSal.DataSource = GetCboAffectsSalDataTable()
        CboAffectsSal.ValueMember = "Code"
        CboAffectsSal.DisplayMember = "Name"
        CboAffectsSal.SelectedIndex = -1

        cboLeaveTypeDed.DataSource = GetCboLeaveTypeDedDataTable()
        cboLeaveTypeDed.ValueMember = "Code"
        cboLeaveTypeDed.DisplayMember = "Name"
        cboLeaveTypeDed.SelectedIndex = 1

        btnsave.Text = "Save"
        btnsave.Enabled = True
        btndelete.Enabled = True
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        funClose()

    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        Try
            Dim str As String = "select count(*) from TSPL_LEAVE_MASTER where LEAVE_CODE ='" + txtCode.Value + "' "
            Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
            If no = 0 AndAlso isButtonClicked = False Then
                txtCode.MyReadOnly = False
                'txtCode.Value = ""
                '' common.clsCommon.MyMessageBoxShow("Value doesn't exist ")
            Else
                txtCode.MyReadOnly = True
            End If
            If txtCode.MyReadOnly OrElse isButtonClicked Then

                'Dim qry As String = "select LEAVE_CODE AS Code, LEAVE_NAME as Name, PRINT_NAME as 'Print Name', AFFECTS_SALARY as 'Is Affects Salary'  from TSPL_LEAVE_MASTER"
                'txtCode.Value = clsCommon.ShowSelectForm("LEAVE_MASTER", qry, "Code", "", txtCode.Value, "LEAVE_CODE", isButtonClicked)
                txtCode.Value = clsLeaveMaster.getFinder("", txtCode.Value, isButtonClicked)
                If txtCode.Value <> "" Then
                    LoadData(txtCode.Value, NavigatorType.Current)
                Else
                    funReset()
                End If
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub frmLeaveMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub


    Private Sub MenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Name", "Print Name", "Leave Type", "Is Affects Salary") Then
            '  Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsLeaveMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells("Code").Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.Code = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells("Name").Value)
                    If strName.Length > 100 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Name can not be blank or incorrect.")
                    End If
                    obj.Name = strName

                    strName = clsCommon.myCstr(grow.Cells("Print Name").Value)
                    If strName.Length > 100 Then
                        Throw New Exception("Print Name can not be blank or incorrect.")
                    End If
                    obj.PRINT_NAME = strName

                    strName = clsCommon.myCstr(grow.Cells("Leave Type").Value)
                    If strName.Length > 30 Then
                        Throw New Exception("Leave Type can not be blank or incorrect.")
                    End If
                    obj.LEAVE_TYPE = strName

                    Dim AffectsSalary = Convert.ToInt16(clsCommon.myCdbl(grow.Cells("Is Affects Salary").Value))
                    If AffectsSalary = 0 Or AffectsSalary = 1 Then
                        obj.AFFECTS_SALARY = AffectsSalary
                    Else
                        Throw New Exception("Is Affects Salary can be 0 or 1 Only.")
                    End If

                    obj.SaveData(obj, clsLeaveMaster.CheckNewEntry(obj.Code))
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub MenuItemExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemExport.Click
        Dim str As String
        str = "select LEAVE_CODE AS Code, LEAVE_NAME as Name, PRINT_NAME as 'Print Name',Leave_Type as [Leave Type], AFFECTS_SALARY as 'Is Affects Salary'  from TSPL_LEAVE_MASTER"
        transportSql.ExporttoExcel(str, Me)

    End Sub

    Private Sub MenuItemClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemClose.Click
        funClose()

    End Sub

    Private Sub CboAffectsSal_Enter(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim Selected_val As String = String.Empty

        If CboAffectsSal.SelectedIndex > -1 Then
            Selected_val = CboAffectsSal.SelectedValue
        End If

        CboAffectsSal.DataSource = GetCboAffectsSalDataTable()
        CboAffectsSal.ValueMember = "Code"
        CboAffectsSal.DisplayMember = "Name"

        If Selected_val.Length > 0 Then
            CboAffectsSal.SelectedValue = Selected_val
        Else
            CboAffectsSal.SelectedIndex = -1

        End If

    End Sub

    Public Shared Function GetCboAffectsSalDataTable() As DataTable
        Dim DT_AttReg As DataTable = New DataTable
        DT_AttReg.Columns.Add("Code", GetType(Int16))
        DT_AttReg.Columns.Add("Name", GetType(String))

        Dim DR As DataRow = DT_AttReg.NewRow()
        DR("Name") = "Yes"
        DR("Code") = 1
        DT_AttReg.Rows.Add(DR)

        DR = DT_AttReg.NewRow()
        DR("Name") = "No"
        DR("Code") = 0
        DT_AttReg.Rows.Add(DR)

        DT_AttReg.AcceptChanges()

        Return DT_AttReg
    End Function

    Public Shared Function GetCboLeaveTypeDedDataTable() As DataTable
        Dim DT_LeaveTypeDed As DataTable = New DataTable
        DT_LeaveTypeDed.Columns.Add("Code", GetType(Int16))
        DT_LeaveTypeDed.Columns.Add("Name", GetType(String))

        Dim DR As DataRow = DT_LeaveTypeDed.NewRow()
        DR("Name") = "Yes"
        DR("Code") = 1
        DT_LeaveTypeDed.Rows.Add(DR)

        DR = DT_LeaveTypeDed.NewRow()
        DR("Name") = "No"
        DR("Code") = 0
        DT_LeaveTypeDed.Rows.Add(DR)

        DT_LeaveTypeDed.AcceptChanges()

        Return DT_LeaveTypeDed
    End Function

    Private Sub cboLeaveTypeDed_Enter(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim Selected_val As String = String.Empty

        If cboLeaveTypeDed.SelectedIndex > -1 Then
            Selected_val = CboAffectsSal.SelectedValue
        End If

        cboLeaveTypeDed.DataSource = GetCboLeaveTypeDedDataTable()
        cboLeaveTypeDed.ValueMember = "Code"
        cboLeaveTypeDed.DisplayMember = "Name"

        If Selected_val.Length > 0 Then
            cboLeaveTypeDed.SelectedValue = Selected_val
        Else
            cboLeaveTypeDed.SelectedIndex = -1
        End If
    End Sub

End Class
