'--18/10/2013--form Add By- Pradeep Sharma ---------
'updated @ Ticket No .:BM00000000704
Imports common
Imports System.Data
Imports System.Data.SqlClient
Imports XpertERPEngine
Imports Telerik.WinControls.UI

Public Class frmAttendanceMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String

#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        Save()
    End Sub

    Public Sub Save()
        If AllowToSave() Then

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmAttendanceMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            Dim obj As New clsAttendanceMaster()
            obj.Code = txtCode.Value
            obj.Description = txtDescription.Text
            obj.Name = txtName.Text
            obj.SALARY_DEPENDENT_ON_ATTEN = clsCommon.myCstr(cboSalaryDep.SelectedValue)
            obj.OT_CODE = clsCommon.myCstr(txtOTCode.Value)
            obj.CALC_SAL_ON = clsCommon.myCstr(cboSalaryCalOnDay.SelectedValue)
            obj.ATTN_REGISTER_TYPE = clsCommon.myCstr(cboAttRegType.SelectedValue)

            If (obj.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow("Data Saved Successfully")
                LoadData(obj.Code, NavigatorType.Current)
                'Else
                '    common.clsCommon.MyMessageBoxShow("This '" & obj.Code & "' already exist ")
            End If

        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnSave.Enabled = True
        btnDelete.Enabled = True
        isNewEntry = False
        Dim obj As New clsAttendanceMaster()
        obj = clsAttendanceMaster.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            txtCode.Value = obj.Code
            txtName.Text = obj.Name
            txtDescription.Text = obj.Description
            cboSalaryDep.SelectedValue = clsCommon.myCstr(obj.SALARY_DEPENDENT_ON_ATTEN)
            txtOTCode.Value = clsCommon.myCstr(obj.OT_CODE)
            lblOTCode.Text = clsCommon.myCstr(obj.OT_Name)
            cboSalaryCalOnDay.SelectedValue = clsCommon.myCstr(obj.CALC_SAL_ON)
            cboAttRegType.SelectedValue = clsCommon.myCstr(obj.ATTN_REGISTER_TYPE)
        End If

    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
            myMessages.blankValue("Code")
            txtCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtName.Text) <= 0 Then
            myMessages.blankValue(" Name")
            txtName.Focus()
            Return False
        ElseIf clsCommon.myLen(cboSalaryDep.SelectedValue) <= 0 Then
            myMessages.blankValue("Salary Depandency")
            txtName.Focus()
            Return False
            'ElseIf clsCommon.myLen(txtOTCode.Value) <= 0 Then
            '    myMessages.blankValue(" OT Code")
            '    txtName.Focus()
            '    Return False
        ElseIf clsCommon.myLen(cboSalaryCalOnDay.SelectedValue) <= 0 Then
            myMessages.blankValue(" Salary Calculated on Days")
            txtName.Focus()
            Return False
        ElseIf clsCommon.myLen(cboAttRegType.SelectedValue) <= 0 Then
            myMessages.blankValue(" Attendenc Register Type ")
            txtName.Focus()
            Return False

        End If
        Return True
    End Function


    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow("You Cannot Delete Record")
            Exit Sub
        End If
        'Dim discCode As String
        'discCode = clsDBFuncationality.getSingleValue("select ATTENDANCE_CODE  from TSPL_SHIPMENT_DETAILS  where ATTENDANCE_CODE ='" & txtCode.Value & "'")
        'If clsCommon.myLen(discCode) > 0 Then
        '    common.clsCommon.MyMessageBoxShow("This record can't be deleted.It is used in another process")
        '    Exit Sub
        'End If
        '' Code Ends 
        funDelete()
    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsAttendanceMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow("Data Deleted Successfully ")
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub frmAttendanceMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isNewEntry = True

        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        '  ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")

    End Sub

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmAttendanceMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 01/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            MenuItemImport.Enabled = True
            MenuItemExport.Enabled = True
        Else
            MenuItemImport.Enabled = False
            MenuItemExport.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        txtName.Text = ""
        txtDescription.Text = ""
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = True

        txtOTCode.Value = ""
        lblOTCode.Text = ""

        cboSalaryDep.DataSource = clsAttendanceMaster.GetCboSalaryDepDataTable()
        cboSalaryDep.ValueMember = "Code"
        cboSalaryDep.DisplayMember = "Name"
        cboSalaryDep.SelectedIndex = -1

        cboAttRegType.DataSource = clsAttendanceMaster.GetCboAttRegDataTable()
        cboAttRegType.ValueMember = "Code"
        cboAttRegType.DisplayMember = "Name"
        cboAttRegType.SelectedIndex = -1

        cboSalaryCalOnDay.DataSource = clsAttendanceMaster.GetCboSalaryCalOnDayDataTable()
        cboSalaryCalOnDay.ValueMember = "Code"
        cboSalaryCalOnDay.DisplayMember = "Name"
        cboSalaryCalOnDay.SelectedIndex = -1
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()

    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating

        Dim str As String = "select count(*) from TSPL_ATTENDANCE_MASTER where ATTENDANCE_CODE ='" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtCode.MyReadOnly = False
            'txtCode.Value = ""
            '' common.clsCommon.MyMessageBoxShow("Value doesn't exist ")
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = "select ATTENDANCE_CODE as Code, ATTENDANCE_NAME as Name, DESCRIPTION as Description, SALARY_DEPENDENT_ON_ATTEN as 'Salary Dependency', OT_CODE as 'OT Code' , CALC_SAL_ON as 'Salary Calculation on Days', ATTN_REGISTER_TYPE as 'Attendance Register Type'  from TSPL_ATTENDANCE_MASTER"
            'txtCode.Value = clsCommon.ShowSelectForm("ATTENDANCE_MASTER", qry, "Code", "", txtCode.Value, "ATTENDANCE_CODE", isButtonClicked)
            txtCode.Value = clsAttendanceMaster.getFinder("", txtCode.Value, isButtonClicked)
            If txtCode.Value <> "" Then
                LoadData(txtCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If


    End Sub

    Sub funFill()

    End Sub


    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub frmAttendanceMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub MenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Name", "Description", "Salary Dependency", "OT Code", "Salary Calculation on Days", "Attendance Register Type") Then
            ' Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsAttendanceMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.Code = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells(1).Value)
                    If strName.Length > 100 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Name can not be blank or incorrect.")
                    End If
                    obj.Name = strName

                    Dim strDes As String = clsCommon.myCstr(grow.Cells(2).Value)
                    If strDes.Length > 200 Then
                        Throw New Exception("Description can not be blank or incorrect.")
                    End If
                    obj.Description = strDes

                    strDes = clsCommon.myCstr(grow.Cells(3).Value)
                    If strDes.Length > 30 Then
                        Throw New Exception("Salary Dependency can not be blank or incorrect.")
                    End If
                    obj.SALARY_DEPENDENT_ON_ATTEN = strDes

                    strDes = clsCommon.myCstr(grow.Cells(4).Value)
                    If strDes.Length > 30 Then
                        Throw New Exception("OT Code can not be blank or incorrect.")
                    End If
                    obj.OT_CODE = strDes

                    strDes = clsCommon.myCstr(grow.Cells(5).Value)
                    If strDes.Length > 30 Then
                        Throw New Exception("Salary Calculation on Days can not be blank or incorrect.")
                    End If
                    obj.CALC_SAL_ON = strDes

                    strDes = clsCommon.myCstr(grow.Cells(6).Value)
                    If strDes.Length > 200 Then
                        Throw New Exception("Attendance Register Type can not be blank or incorrect.")
                    End If
                    obj.ATTN_REGISTER_TYPE = strDes

                    obj.SaveData(obj, clsAttendanceMaster.CheckNewEntry(obj.Code))
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub MenuItemExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemExport.Click
        Dim str As String
        str = "select ATTENDANCE_CODE as Code, ATTENDANCE_NAME as Name, DESCRIPTION as Description, SALARY_DEPENDENT_ON_ATTEN as 'Salary Dependency', OT_CODE as 'OT Code' , CALC_SAL_ON as 'Salary Calculation on Days', ATTN_REGISTER_TYPE as 'Attendance Register Type'  from TSPL_ATTENDANCE_MASTER"
        transportSql.ExporttoExcel(str, Me)

    End Sub

    Private Sub MenuItemClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemClose.Click
        funClose()

    End Sub

    Private Sub txtOTCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtOTCode._MYValidating
        Dim qry As String = " select OT_CODE as Code, OT_NAME as Name, DESCRIPTION as Description  ,HOUR_MULTIPLIER as 'Hours Multiplier', OT_RATE as 'OT Rate',IS_ASPER_ACTUAL_CALC  as 'Is as per actual calculation' from TSPL_OT_MASTER"
        txtOTCode.Value = clsCommon.ShowSelectForm("OT_FINDER", qry, "Code", "", txtOTCode.Value, "OT_CODE", isButtonClicked)
        lblOTCode.Text = clsOTMaster.GetName(txtOTCode.Value, Nothing)
    End Sub

    Private Sub cboAttRegType_Enter(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cboAttRegType.Enter
        Dim Selected_val As String = String.Empty

        If cboAttRegType.SelectedIndex > -1 Then
            Selected_val = cboAttRegType.SelectedValue
        End If

        cboAttRegType.DataSource = clsAttendanceMaster.GetCboAttRegDataTable()
        cboAttRegType.ValueMember = "Code"
        cboAttRegType.DisplayMember = "Name"

        If Selected_val.Length > 0 Then
            cboAttRegType.SelectedValue = Selected_val
        End If
    End Sub

    Private Sub cboSalaryDep_Enter(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cboSalaryDep.Enter
        Dim Selected_val As String = String.Empty

        If cboSalaryDep.SelectedIndex > -1 Then
            Selected_val = cboSalaryDep.SelectedValue
        End If

        cboSalaryDep.DataSource = clsAttendanceMaster.GetCboSalaryDepDataTable()
        cboSalaryDep.ValueMember = "Code"
        cboSalaryDep.DisplayMember = "Name"
        If Selected_val.Length > 0 Then
            cboSalaryDep.SelectedValue = Selected_val
        End If

    End Sub

    Private Sub cboSalaryCalOnDay_Enter(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cboSalaryCalOnDay.Enter
        Dim Selected_val As String = String.Empty

        If cboSalaryCalOnDay.SelectedIndex > -1 Then
            Selected_val = cboSalaryCalOnDay.SelectedValue
        End If

        cboSalaryCalOnDay.DataSource = clsAttendanceMaster.GetCboSalaryCalOnDayDataTable()
        cboSalaryCalOnDay.ValueMember = "Code"
        cboSalaryCalOnDay.DisplayMember = "Name"
        If Selected_val.Length > 0 Then
            cboSalaryCalOnDay.SelectedValue = Selected_val
        End If

    End Sub
End Class
