'--11/10/2013--form Add By- Pradeep Sharma ---------
'---Preeti Gupta--ticket no-[BM00000003144]
Imports common
Imports System.Data
Imports System.Data.SqlClient
Imports XpertERPEngine
Imports Telerik.WinControls.UI

Public Class frmBonusMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String

#End Region

    Private Sub frmBonusMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isNewEntry = True

        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        LoadCalculationMethod()
    End Sub

    Sub LoadCalculationMethod() ''BHA/25/01/19-000791 by balwinder on 29/01/2019
        Dim dt As DataTable = New DataTable()
        dt.Columns.Add("Code", GetType(String))
        dt.Columns.Add("Name", GetType(String))

        Dim dr As DataRow = dt.NewRow()
        dr("Code") = "Basic"
        dr("Name") = "Basic Pay"
        dt.Rows.Add(dr)

        dr = dt.NewRow()
        dr("Code") = "Net"
        dr("Name") = "Net Pay"
        dt.Rows.Add(dr)

        cboCalculationMethod.DataSource = dt
        cboCalculationMethod.ValueMember = "Code"
        cboCalculationMethod.DisplayMember = "Name"
    End Sub

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        Save()
    End Sub

    Public Sub Save()
        If AllowToSave() Then

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmBonusMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            Dim obj As New clsBonusMaster()
            obj.Code = txtCode.Value
            obj.Description = txtDescription.Text
            obj.Name = txtName.Text
            obj.COND_BASIC_PER_MONTH = txtCOND_BASIC_PER_MONTH.Text
            obj.COND_MAX_EARNING_PER_MONTH = txtCOND_MAX_EARNING_PER_MONTH.Text
            obj.COND_MAX_BONUS_PER_YEAR = txtCOND_MAX_BONUS_PER_YEAR.Text
            obj.BONUS_RATE = txtBONUS_RATE.Text
            obj.Calculation_Method = clsCommon.myCstr(cboCalculationMethod.SelectedValue)
            obj.Is_Consider_Pay_Days = chkConsiderPayDays.Checked
            If (obj.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                LoadData(obj.Code, NavigatorType.Current)
                'Else
                '    common.clsCommon.MyMessageBoxShow("This '" & obj.Code & "' already exist ")
            End If

        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnSave.Enabled = True
        btnDelete.Enabled = True
        isNewEntry = False
        Dim obj As New clsBonusMaster()
        obj = clsBonusMaster.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            txtCode.Value = obj.Code
            txtName.Text = obj.Name
            txtDescription.Text = obj.Description
            txtCOND_BASIC_PER_MONTH.Text = obj.COND_BASIC_PER_MONTH
            txtCOND_MAX_EARNING_PER_MONTH.Text = obj.COND_MAX_EARNING_PER_MONTH
            txtCOND_MAX_BONUS_PER_YEAR.Text = obj.COND_MAX_BONUS_PER_YEAR
            txtBONUS_RATE.Text = obj.BONUS_RATE
            cboCalculationMethod.SelectedValue = obj.Calculation_Method
            chkConsiderPayDays.Checked = obj.Is_Consider_Pay_Days
        End If

    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
            myMessages.blankValue(Me, "Code", Me.Text)
            txtCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtName.Text) <= 0 Then
            myMessages.blankValue(Me, "Name", Me.Text)
            txtName.Focus()
            Return False
        ElseIf clsCommon.myLen(txtCOND_BASIC_PER_MONTH.Text) <= 0 Then
            myMessages.blankValue(Me, "Per Month Basic Amount for Bonus Applicable", Me.Text)
            txtCOND_BASIC_PER_MONTH.Focus()
            Return False
        ElseIf clsCommon.myLen(txtCOND_MAX_EARNING_PER_MONTH.Text) <= 0 Then
            myMessages.blankValue(Me, "Maximum Earning per month for bonus applicable", Me.Text)
            txtCOND_MAX_EARNING_PER_MONTH.Focus()
            Return False
        ElseIf clsCommon.myLen(txtCOND_MAX_BONUS_PER_YEAR.Text) <= 0 Then
            myMessages.blankValue(Me, "Maximum Bonus per year", Me.Text)
            txtCOND_MAX_BONUS_PER_YEAR.Focus()
            Return False
        ElseIf clsCommon.myLen(txtBONUS_RATE.Text) <= 0 Then
            myMessages.blankValue(Me, "Bonus Rate", Me.Text)
            txtBONUS_RATE.Focus()
            Return False



        End If
        Return True
    End Function

    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub

    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "You Cannot Delete Record", Me.Text)
            Exit Sub
        End If
        'Dim discCode As String
        'discCode = clsDBFuncationality.getSingleValue("select BONUS_CODE  from TSPL_SHIPMENT_DETAILS  where BONUS_CODE ='" & txtCode.Value & "'")
        'If clsCommon.myLen(discCode) > 0 Then
        '    common.clsCommon.MyMessageBoxShow("This record can't be deleted.It is used in another process")
        '    Exit Sub
        'End If
        '' Code Ends 
        funDelete()
    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsBonusMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmBonusMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 01/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            MenuItemImport.Enabled = True
            MenuItemExport.Enabled = True
        Else
            MenuItemImport.Enabled = False
            MenuItemExport.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        txtName.Text = ""
        txtDescription.Text = ""
        txtCOND_BASIC_PER_MONTH.Text = ""
        txtCOND_MAX_EARNING_PER_MONTH.Text = ""
        txtCOND_MAX_BONUS_PER_YEAR.Text = ""
        txtBONUS_RATE.Text = ""
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = True
        cboCalculationMethod.SelectedValue = "Basic"
        chkConsiderPayDays.Checked = False
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()

    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating

        Dim str As String = "select count(*) from TSPL_BONUS_MASTER where BONUS_CODE ='" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtCode.MyReadOnly = False
            'txtCode.Value = ""
            '' common.clsCommon.MyMessageBoxShow("Value doesn't exist ")
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = " select BONUS_CODE AS Code, BONUS_NAME as Name, DESCRIPTION AS Description from TSPL_BONUS_MASTER "
            'txtCode.Value = clsCommon.ShowSelectForm("Bonus_Master", qry, "Code", "", txtCode.Value, "BONUS_CODE", isButtonClicked)
            txtCode.Value = clsBonusMaster.getFinder("", txtCode.Value, isButtonClicked)
            If txtCode.Value <> "" Then
                LoadData(txtCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If


    End Sub

    Sub funFill()

    End Sub

    Private Sub txtCode_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCode.KeyPress
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub frmBonusMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub MenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Name", "Description", "Basic Amount for Bonus Applicable / Month", "Maximum Earning for bonus applicable / Month", "Maximum Bonus / Year", "Bonus Rate", "Calculation Method[Basic/Net]", "Consider Pay Days[Y/N]") Then
            Try
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsBonusMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.Code = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells(1).Value)
                    If strName.Length > 100 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Name can not be blank or incorrect.")
                    End If
                    obj.Name = strName

                    Dim strDes As String = clsCommon.myCstr(grow.Cells(2).Value)
                    If strDes.Length > 200 Then
                        Throw New Exception("Description can not be blank or incorrect.")
                    End If
                    obj.Description = strDes

                    strDes = clsCommon.myCstr(grow.Cells(3).Value)
                    If strDes.Length > 20 Then
                        Throw New Exception("Basic Amount for Bonus Applicable / Month can not be blank or incorrect.")
                    End If
                    obj.COND_BASIC_PER_MONTH = strDes

                    strDes = clsCommon.myCstr(grow.Cells(4).Value)
                    If strDes.Length > 20 Then
                        Throw New Exception("Maximum Earning for bonus applicable / Month can not be blank or incorrect.")
                    End If
                    obj.COND_MAX_EARNING_PER_MONTH = strDes

                    strDes = clsCommon.myCstr(grow.Cells(5).Value)
                    If strDes.Length > 20 Then
                        Throw New Exception("Maximum Bonus / Year can not be blank or incorrect.")
                    End If
                    obj.COND_MAX_BONUS_PER_YEAR = strDes

                    strDes = clsCommon.myCstr(grow.Cells(6).Value)
                    If strDes.Length > 200 Then
                        Throw New Exception("Bonus Rate can not be blank or incorrect.")
                    End If
                    obj.BONUS_RATE = strDes

                    obj.Calculation_Method = clsCommon.myCstr(grow.Cells("Calculation Method[Basic/Net]").Value)
                    If Not (clsCommon.CompairString(obj.Calculation_Method, "Basic") = CompairStringResult.Equal OrElse clsCommon.CompairString(obj.Calculation_Method, "Net") = CompairStringResult.Equal) Then
                        Throw New Exception("Calculatioin Method should be Basic/Net.")
                    End If
                    obj.Is_Consider_Pay_Days = (clsCommon.CompairString(clsCommon.myCstr(grow.Cells("Consider Pay Days[Y/N]").Value), "Y") = CompairStringResult.Equal)
                    obj.SaveData(obj, clsBonusMaster.CheckNewEntry(obj.Code))
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)

    End Sub

    Private Sub MenuItemExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemExport.Click
        Dim str As String
        str = "select BONUS_CODE AS Code, BONUS_NAME as Name, DESCRIPTION AS Description, COND_BASIC_PER_MONTH as 'Basic Amount for Bonus Applicable / Month', COND_MAX_EARNING_PER_MONTH as 'Maximum Earning for bonus applicable / Month', COND_MAX_BONUS_PER_YEAR AS 'Maximum Bonus / Year' ,BONUS_RATE AS 'Bonus Rate',Calculation_Method as 'Calculation Method[Basic/Net]',case when Is_Consider_Pay_Days=1 then 'Y' else 'N' end as 'Consider Pay Days[Y/N]' from TSPL_BONUS_MASTER "
        transportSql.ExporttoExcel(str, Me)

    End Sub

    Private Sub MenuItemClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemClose.Click
        funClose()
    End Sub

End Class
