'--18/10/2013--form Add By- Pradeep Sharma ---------
Imports common
Imports System.Data
Imports System.Data.SqlClient
Imports XpertERPEngine
Imports Telerik.WinControls.UI

Public Class frmBranchMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String

#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        Save()
    End Sub

    Public Sub Save()
        If AllowToSave() Then

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmBranchMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            Dim obj As New clsBranchMaster()
            obj.Code = txtCode.Value
            obj.Name = txtName.Text
            obj.BRANCH_ADDRESS = txtAddress.Text
            obj.COUNTRY_CODE = TxtCountry.Value
            obj.STATE_CODE = TxtState.Value
            obj.CITY_CODE = txtCityCode.Value
            obj.PHONE_NO = txtPhoneNo.Text
            obj.FAX_NO = txtFax.Text
            obj.EMAIL_ID = txtEmail.Text
            obj.RESPONSIBLE_PERSION_NAME = txtperson.Text
            If (obj.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                LoadData(obj.Code, NavigatorType.Current)
                'Else
                '    common.clsCommon.MyMessageBoxShow("This '" & obj.Code & "' already exist ")
            End If

        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnSave.Enabled = True
        btnDelete.Enabled = True
        isNewEntry = False
        Dim obj As New clsBranchMaster()
        obj = clsBranchMaster.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            txtCode.Value = obj.Code
            txtName.Text = obj.Name
            txtAddress.Text = obj.BRANCH_ADDRESS
            TxtCountry.Value = obj.COUNTRY_CODE
            TxtState.Value = obj.STATE_CODE
            txtCityCode.Value = obj.CITY_CODE
            lblCountry.Text = obj.COUNTRY_NAME
            lblState.Text = obj.STATE_NAME
            lblCityName.Text = obj.CITY_NAME
            txtPhoneNo.Text = obj.PHONE_NO
            txtFax.Text = obj.FAX_NO
            txtEmail.Text = obj.EMAIL_ID
            txtperson.Text = obj.RESPONSIBLE_PERSION_NAME
        End If

    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
            myMessages.blankValue(Me, "Code", Me.Text)
            txtCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtName.Text) <= 0 Then
            myMessages.blankValue(Me, " Name", Me.Text)
            txtName.Focus()
            Return False
        ElseIf clsCommon.myLen(txtAddress.Text) <= 0 Then
            myMessages.blankValue(Me, " Address ", Me.Text)
            txtAddress.Focus()
            Return False
        ElseIf clsCommon.myLen(TxtCountry.Value) <= 0 Then
            myMessages.blankValue(Me, "Country code", Me.Text)
            TxtCountry.Focus()
            Return False
        ElseIf clsCommon.myLen(TxtState.Value) <= 0 Then
            myMessages.blankValue(Me, "State Code", Me.Text)
            TxtState.Focus()
            Return False
        ElseIf clsCommon.myLen(txtperson.Text) <= 0 Then
            myMessages.blankValue(Me, "Responsible Person/Manager", Me.Text)
            txtperson.Focus()
            Return False
        ElseIf clsCommon.myLen(txtCityCode.Value) <= 0 Then
            myMessages.blankValue(Me, "City Code ", Me.Text)
            txtCityCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtPhoneNo.Text) <= 0 Then
            myMessages.blankValue(Me, "Phone No", Me.Text)
            txtPhoneNo.Focus()
            Return False
        ElseIf clsCommon.myLen(txtFax.Text) <= 0 Then
            myMessages.blankValue(Me, "Fax No ", Me.Text)
            txtFax.Focus()
            Return False
        ElseIf clsCommon.myLen(txtEmail.Text) <= 0 Then
            myMessages.blankValue(Me, " Email Id", Me.Text)
            txtEmail.Focus()
            Return False

        End If
        Return True
    End Function


    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "You Cannot Delete Record", Me.Text)
            Exit Sub
        End If
        'Dim discCode As String
        'discCode = clsDBFuncationality.getSingleValue("select BRANCH_CODE  from TSPL_SHIPMENT_DETAILS  where BRANCH_CODE ='" & txtCode.Value & "'")
        'If clsCommon.myLen(discCode) > 0 Then
        '    common.clsCommon.MyMessageBoxShow("This record can't be deleted.It is used in another process")
        '    Exit Sub
        'End If
        '' Code Ends 
        funDelete()
    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsBranchMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub frmBranchMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isNewEntry = True

        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        '  ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")

    End Sub

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmBranchMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 02/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            MenuItemImport.Enabled = True
            MenuItemExport.Enabled = True
        Else
            MenuItemImport.Enabled = False
            MenuItemExport.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        txtName.Text = ""
        txtperson.Text = ""
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = True
        txtAddress.Text = ""
        TxtCountry.Value = ""
        TxtState.Value = ""
        lblCountry.Text = ""
        lblState.Text = ""
        txtPhoneNo.Text = ""
        txtFax.Text = ""
        txtEmail.Text = ""
        txtperson.Text = ""
        txtCityCode.Value = ""
        lblCityName.Text = ""

    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()

    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating

        Dim str As String = "select count(*) from TSPL_BRANCH_MASTER where BRANCH_CODE ='" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtCode.MyReadOnly = False
            'txtCode.Value = ""
            '' common.clsCommon.MyMessageBoxShow("Value doesn't exist ")
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = "select BRANCH_CODE as Code, BRANCH_NAME as Name,RESPONSIBLE_PERSION_NAME as 'Responsible Persion', BRANCH_ADDRESS as 'Branch Address', CITY_CODE as 'City Code', STATE_CODE as 'State Code' , COUNTRY_CODE as 'Country Code', PHONE_NO as 'Phone No',FAX_NO as 'Fax No', EMAIL_ID as 'Email Id'  from TSPL_BRANCH_MASTER"
            'txtCode.Value = clsCommon.ShowSelectForm("BRANCH_MASTER", qry, "Code", "", txtCode.Value, "BRANCH_CODE", isButtonClicked)
            txtCode.Value = clsBranchMaster.getFinder("", txtCode.Value, isButtonClicked)
            If txtCode.Value <> "" Then
                LoadData(txtCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If


    End Sub

    Sub funFill()

    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub frmBranchMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub MenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Name", "Responsible Persion", "Branch Address", "City Code", "State Code", "Country Code", "Phone No", "Fax No", "Email Id") Then
            '  Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsBranchMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.Code = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells(1).Value)
                    If strName.Length > 100 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Name can not be blank or incorrect.")
                    End If
                    obj.Name = strName

                    Dim strDes As String = clsCommon.myCstr(grow.Cells(2).Value)
                    If strDes.Length > 200 Then
                        Throw New Exception("Responsible Persion can not be blank or incorrect.")
                    End If
                    obj.RESPONSIBLE_PERSION_NAME = strDes

                    strDes = clsCommon.myCstr(grow.Cells(3).Value)
                    If strDes.Length > 200 Then
                        Throw New Exception(" Branch Address can not be blank or incorrect.")
                    End If
                    obj.BRANCH_ADDRESS = strDes

                    strDes = clsCommon.myCstr(grow.Cells(4).Value)
                    If strDes.Length > 30 Then
                        Throw New Exception("City Code can not be blank or incorrect.")
                    End If
                    obj.CITY_CODE = strDes

                    strDes = clsCommon.myCstr(grow.Cells(5).Value)
                    If strDes.Length > 30 Then
                        Throw New Exception("State Code can not be blank or incorrect.")
                    End If
                    obj.STATE_CODE = strDes

                    strDes = clsCommon.myCstr(grow.Cells(6).Value)
                    If strDes.Length > 30 Then
                        Throw New Exception("Country Code can not be blank or incorrect.")
                    End If
                    obj.COUNTRY_CODE = strDes

                    strDes = clsCommon.myCstr(grow.Cells(7).Value)
                    If strDes.Length > 30 Then
                        Throw New Exception("Phone No can not be blank or incorrect.")
                    End If
                    obj.PHONE_NO = strDes

                    strDes = clsCommon.myCstr(grow.Cells(8).Value)
                    If strDes.Length > 30 Then
                        Throw New Exception("Fax No can not be blank or incorrect.")
                    End If
                    obj.FAX_NO = strDes

                    strDes = clsCommon.myCstr(grow.Cells(9).Value)
                    If strDes.Length > 30 Then
                        Throw New Exception("Email Id can not be blank or incorrect.")
                    End If
                    obj.EMAIL_ID = strDes

                    obj.SaveData(obj, True)
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub MenuItemExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemExport.Click
        Dim str As String
        str = "select BRANCH_CODE as Code, BRANCH_NAME as Name,RESPONSIBLE_PERSION_NAME as 'Responsible Persion', BRANCH_ADDRESS as 'Branch Address', CITY_CODE as 'City Code', STATE_CODE as 'State Code' , COUNTRY_CODE as 'Country Code', PHONE_NO as 'Phone No',FAX_NO as 'Fax No', EMAIL_ID as 'Email Id'  from TSPL_BRANCH_MASTER"
        transportSql.ExporttoExcel(str, Me)

    End Sub

    Private Sub MenuItemClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemClose.Click
        funClose()

    End Sub

    Private Sub txtCityCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCityCode._MYValidating
        Dim qry As String = " select City_Code As Code,City_Name  as [City Name]from TSPL_City_MASTER "
        txtCityCode.Value = clsCommon.ShowSelectForm("frmCity", qry, "Code", "STATE_CODE = '" + TxtState.Value + "'", txtCityCode.Value, "", isButtonClicked)
        lblCityName.Text = clsCityMaster.GetName(txtCityCode.Value)
    End Sub

    Private Sub TxtCountry__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles TxtCountry._MYValidating
        Dim qry As String = " select COUNTRY_CODE as Code, COUNTRY_NAME as Name from TSPL_COUNTRY_MASTER "
        TxtCountry.Value = clsCommon.ShowSelectForm("COUNTRY_MASTER", qry, "Code", "", TxtCountry.Value, "COUNTRY_CODE", isButtonClicked)
        lblCountry.Text = clsCountryMaster.GetName(TxtCountry.Value, Nothing)
    End Sub
    Private Sub TxtState__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles TxtState._MYValidating
        Dim qry As String = "select STATE_CODE AS Code, STATE_NAME as Name from TSPL_STATE_MASTER"
        TxtState.Value = clsCommon.ShowSelectForm("STATE_MASTER", qry, "Code", "COUNTRY_CODE= '" + TxtCountry.Value + "' ", TxtState.Value, "STATE_CODE", isButtonClicked)
        lblState.Text = clsStateMaster.GetName(TxtState.Value)
    End Sub

End Class
