'--14/10/2013--form Add By- Pradeep Sharma ---------
Imports common
Imports System.Data
Imports System.Data.SqlClient
Imports XpertERPEngine
Imports Telerik.WinControls.UI

Public Class frmESIRulesMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String

#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        Save()
    End Sub

    Public Sub Save()
        If AllowToSave() Then

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmESIRulesMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            Dim obj As New clsESIRulesMaster()
            obj.Code = txtCode.Value
            obj.APPLICABLE_FROM = txtAppDate.Value.ToLongDateString()
            obj.COESI_PER = txtCOESI_PER.Text
            obj.COESI_ROUNDOFF_YPE = cboESIRound.SelectedValue
            obj.EMPESI_PER = txtEMPESI_PER.Text
            obj.TOTALEARNING_MAX = txtTOTALEARNING_MAX.Text

            If (obj.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow("Data Saved Successfully")
                LoadData(obj.Code, NavigatorType.Current)
                'Else
                '    common.clsCommon.MyMessageBoxShow("This '" & obj.Code & "' already exist ")
            End If

        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnSave.Enabled = True
        btnDelete.Enabled = True
        isNewEntry = False
        Dim obj As New clsESIRulesMaster()
        obj = clsESIRulesMaster.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            txtCode.Value = obj.Code
            txtAppDate.Value = obj.APPLICABLE_FROM
            txtCOESI_PER.Text = obj.COESI_PER
            cboESIRound.SelectedValue = obj.COESI_ROUNDOFF_YPE
            txtEMPESI_PER.Text = obj.EMPESI_PER
            txtTOTALEARNING_MAX.Text = obj.TOTALEARNING_MAX
        End If

    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(txtCode.Value) <= 0 Then
                myMessages.blankValue("Code")
                txtCode.Focus()
                Return False
            End If
        End If
        Return True
    End Function


    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow("You Cannot Delete Record")
            Exit Sub
        End If
        'Dim discCode As String
        'discCode = clsDBFuncationality.getSingleValue("select SKILL_CODE  from TSPL_SHIPMENT_DETAILS  where SKILL_CODE ='" & txtCode.Value & "'")
        'If clsCommon.myLen(discCode) > 0 Then
        '    common.clsCommon.MyMessageBoxShow("This record can't be deleted.It is used in another process")
        '    Exit Sub
        'End If
        '' Code Ends 
        funDelete()
    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsESIRulesMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow("Data Deleted Successfully ")
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub frmESIRulesMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isNewEntry = True
        funReset()
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        '  ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")

    End Sub

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmESIRulesMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 02/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            MenuItemImport.Enabled = True
            MenuItemExport.Enabled = True
        Else
            MenuItemImport.Enabled = False
            MenuItemExport.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()

        Dim dt_Cbo As DataTable = clsFixedParameter.GetCboDataTable("CboRound", Nothing)
        cboESIRound.DataSource = dt_Cbo.Copy()
        cboESIRound.ValueMember = "Code"
        cboESIRound.DisplayMember = "DESCRIPTION"
        cboESIRound.SelectedIndex = -1

        txtCOESI_PER.Text = "0.00"
        txtEMPESI_PER.Text = "0.00"
        txtTOTALEARNING_MAX.Text = "0.00"
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = True
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()

    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating

        Dim str As String = "select count(*) from TSPL_ESI_RULE_MASTER where ESIRULE_CODE ='" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtCode.MyReadOnly = False
            'txtCode.Value = ""
            '' common.clsCommon.MyMessageBoxShow("Value doesn't exist ")
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then


            'Dim qry As String = "select ESIRULE_CODE as Code ,APPLICABLE_FROM AS 'From Date' from TSPL_ESI_RULE_MASTER"
            'txtCode.Value = clsCommon.ShowSelectForm("ESI_RULES_MASTER", qry, "Code", "", txtCode.Value, "ESIRULE_CODE", isButtonClicked)
            txtCode.Value = clsESIRulesMaster.getFinder("", txtCode.Value, isButtonClicked)
            If txtCode.Value <> "" Then
                LoadData(txtCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If


    End Sub

    Sub funFill()

    End Sub

    Private Sub txtCode_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCode.KeyPress
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub frmESIRulesMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub MenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "From Date", "Company ESI Share(%)", "ESI Round Off Type", "Employee ESI Share(%)", "Max Salary Limit for ESI") Then
            ' Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsESIRulesMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.Code = strCode

                    If clsCommon.myCstr(grow.Cells(1).Value).Length > 10 Then
                        If (String.IsNullOrEmpty(clsCommon.myCstr(grow.Cells(1).Value))) Then
                            Throw New Exception("From Date can not be blank or incorrect.")
                        End If
                    End If
                    obj.APPLICABLE_FROM = clsCommon.GetPrintDate(grow.Cells(1).Value, "dd/MMM/yyyy")

                    strCode = clsCommon.myCstr(grow.Cells(2).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Company ESI Share(%) can not be blank or incorrect.")
                    End If
                    obj.COESI_PER = strCode

                    strCode = clsCommon.myCstr(grow.Cells(3).Value)
                    If strCode.Length >= 2 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("ESI Round Off Type can not be blank or incorrect.")
                    End If
                    obj.COESI_ROUNDOFF_YPE = strCode

                    strCode = clsCommon.myCstr(grow.Cells(4).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Employee ESI Share(%) can not be blank or incorrect.")
                    End If
                    obj.EMPESI_PER = strCode

                    strCode = clsCommon.myCstr(grow.Cells(5).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Max Salary Limit for ESI can not be blank or incorrect.")
                    End If
                    obj.TOTALEARNING_MAX = strCode

                    obj.SaveData(obj, clsESIRulesMaster.CheckNewEntry(obj.Code))
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub MenuItemExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemExport.Click

        Dim str As String
        str = " select ESIRULE_CODE as Code ,APPLICABLE_FROM AS 'From Date', COESI_PER as 'Company ESI Share(%)', COESI_ROUNDOFF_YPE as 'ESI Round Off Type', EMPESI_PER as 'Employee ESI Share(%)', TOTALEARNING_MAX as 'Max Salary Limit for ESI' from TSPL_ESI_RULE_MASTER"
        transportSql.ExporttoExcel(str, Me)

    End Sub

    Private Sub MenuItemClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemClose.Click
        funClose()

    End Sub



End Class
