'--11/10/2013--form Add By- Pradeep Sharma ---------
Imports common
Imports System.Data
Imports System.Data.SqlClient
Imports XpertERPEngine
Imports Telerik.WinControls.UI

Public Class frmPFRulesMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String
    Dim dt_Cbo As DataTable
#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        Save()
    End Sub

    Public Sub Save()
        If AllowToSave() Then

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmPFRulesMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            Dim obj As New clsPFRulesMaster()
            obj.Code = txtCode.Value
            obj.APPLICABLE_FROM = txtAppDate.Value.ToLongDateString()
            obj.COEPF_PER = txtCOEPF_PER.Text
            obj.COEPF_ROUNDOFF_YPE = cboCoEPFRound.SelectedValue
            obj.COEPS_PER = txtCOEPS_PER.Text
            obj.EPS_MAX = txtEPS_MAX.Text
            obj.EMPEPF_PER = txtEMPEPF_PER.Text
            obj.EMPEPF_MAX = txtEMPEPF_MAX.Text
            obj.EMPEPF_ROUNDOFF_YPE = CboEmpRound.SelectedValue
            obj.ACCOEPF_PER = txtACCOEPF_PER.Text
            obj.COEDLI_PER = txtCOEDLI_PER.Text
            obj.ACCOEPF_MAX = txtACCOEPF_MAX.Text
            obj.COEDLI_MAX = txtCOEDLI_MAX.Text
            obj.ACCOEDLI_PER = txtACCOEDLI_PER.Text
            obj.ACCOEDLI_MAX = txtACCOEDLI_MAX.Text
            obj.ACCOEDLI_MIN = txtACCOEDLI_MIN.Text
            obj.OC = txtOC.Text
            obj.OC_MAX = txtOC_MAX.Text
            obj.OTH_ROUNDOFF_YPE = CboEmpRound.SelectedValue
            If (obj.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                LoadData(obj.Code, NavigatorType.Current)
                'Else
                '    common.clsCommon.MyMessageBoxShow("This '" & obj.Code & "' already exist ")
            End If

        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnSave.Enabled = True
        btnDelete.Enabled = True
        isNewEntry = False
        Dim obj As New clsPFRulesMaster()
        obj = clsPFRulesMaster.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            txtCode.Value = obj.Code
            txtAppDate.Value = obj.APPLICABLE_FROM
            txtCOEPF_PER.Text = obj.COEPF_PER
            cboCoEPFRound.SelectedValue = obj.COEPF_ROUNDOFF_YPE
            txtCOEPS_PER.Text = obj.COEPS_PER
            txtEPS_MAX.Text = obj.EPS_MAX
            txtEMPEPF_PER.Text = obj.EMPEPF_PER
            txtEMPEPF_MAX.Text = obj.EMPEPF_MAX
            CboEmpRound.SelectedValue = obj.EMPEPF_ROUNDOFF_YPE
            txtACCOEPF_PER.Text = obj.ACCOEPF_PER
            txtCOEDLI_PER.Text = obj.COEDLI_PER
            txtACCOEPF_MAX.Text = obj.ACCOEPF_MAX
            txtCOEDLI_MAX.Text = obj.COEDLI_MAX
            txtACCOEDLI_PER.Text = obj.ACCOEDLI_PER
            txtACCOEDLI_MAX.Text = obj.ACCOEDLI_MAX
            txtACCOEDLI_MIN.Text = obj.ACCOEDLI_MIN
            txtOC.Text = obj.OC
            txtOC_MAX.Text = obj.OC_MAX
            CboOCRound.SelectedValue = obj.OTH_ROUNDOFF_YPE
        End If

    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(txtCode.Value) <= 0 Then
                myMessages.blankValue(Me, "Code", Me.Text)
                txtCode.Focus()
                Return False
            End If
        End If
        Return True
    End Function


    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "You Cannot Delete Record", Me.Text)
            Exit Sub
        End If
        'Dim discCode As String
        'discCode = clsDBFuncationality.getSingleValue("select SKILL_CODE  from TSPL_SHIPMENT_DETAILS  where SKILL_CODE ='" & txtCode.Value & "'")
        'If clsCommon.myLen(discCode) > 0 Then
        '    common.clsCommon.MyMessageBoxShow("This record can't be deleted.It is used in another process")
        '    Exit Sub
        'End If
        '' Code Ends 
        funDelete()
    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsPFRulesMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub frmPFRulesMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isNewEntry = True
        funReset()
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        '  ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")


    End Sub

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmPFRulesMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 02/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            MenuItemImport.Enabled = True
            MenuItemExport.Enabled = True
        Else
            MenuItemImport.Enabled = False
            MenuItemExport.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = True

        'txtAppDate.Value = obj.APPLICABLE_FROM
        txtCOEPF_PER.Text = "0.00"
        txtCOEPS_PER.Text = "0.00"
        txtEPS_MAX.Text = "0.00"
        txtEMPEPF_PER.Text = "0.00"
        txtEMPEPF_MAX.Text = "0.00"
        txtACCOEPF_PER.Text = "0.00"
        txtCOEDLI_PER.Text = "0.00"
        txtACCOEPF_MAX.Text = "0.00"
        txtCOEDLI_MAX.Text = "0.00"
        txtACCOEDLI_PER.Text = "0.00"
        txtACCOEDLI_MAX.Text = "0.00"
        txtACCOEDLI_MIN.Text = "0.00"
        txtOC.Text = "0.00"
        txtOC_MAX.Text = "0.00"

        dt_Cbo = clsFixedParameter.GetCboDataTable("CboRound", Nothing)
        cboCoEPFRound.DataSource = dt_Cbo.Copy()
        cboCoEPFRound.ValueMember = "Code"
        cboCoEPFRound.DisplayMember = "DESCRIPTION"
        cboCoEPFRound.SelectedIndex = -1

        CboEmpRound.DataSource = dt_Cbo.Copy()
        CboEmpRound.ValueMember = "Code"
        CboEmpRound.DisplayMember = "DESCRIPTION"
        CboEmpRound.SelectedIndex = -1

        CboOCRound.DataSource = dt_Cbo.Copy()
        CboOCRound.ValueMember = "Code"
        CboOCRound.DisplayMember = "DESCRIPTION"
        CboOCRound.SelectedIndex = -1

    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()

    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating

        Dim str As String = "select count(*) from TSPL_PF_RULE_MASTER where PFRULE_CODE ='" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtCode.MyReadOnly = False
            'txtCode.Value = ""
            '' common.clsCommon.MyMessageBoxShow("Value doesn't exist ")
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = "select PFRULE_CODE as Code, APPLICABLE_FROM AS Date  from TSPL_PF_RULE_MASTER"
            'txtCode.Value = clsCommon.ShowSelectForm("PFRULES_MASTER", qry, "Code", "", txtCode.Value, "PFRULE_CODE", isButtonClicked)
            txtCode.Value = clsPFRulesMaster.getFinder("", txtCode.Value, isButtonClicked)
            If txtCode.Value <> "" Then
                LoadData(txtCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If

    End Sub

    Sub funFill()

    End Sub

    Private Sub txtCode_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCode.KeyPress
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub frmPFRulesMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub MenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Date", "Company EPF Share(%)", "Company EPF Round Off Type", "Company EPS Share(%)", "Max EPS Amount", "Company Admin Charges on EPF(ACEPF)", "Max amount of ACEPF", "EDLI Paid by Company", "Max of EDLI", "Admin Charges on EDLI(ACEDLI)", "Max of ACEDLI", "Min of ACEDLI", "Employee EPF Share(%)", "Max EPF Amount", "Employee EPF Round Off Type", "Other Charges(OC)", "Other Charges Round off type", "Max of Other Charges(OC)") Then
            'Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsPFRulesMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.Code = strCode

                    If clsCommon.myCstr(grow.Cells(1).Value).Length > 10 Then
                        If (String.IsNullOrEmpty(clsCommon.myCstr(grow.Cells(1).Value))) Then
                            Throw New Exception("Apply Date can not be blank or incorrect.")
                        End If
                    End If
                    obj.APPLICABLE_FROM = clsCommon.GetPrintDate(grow.Cells(1).Value, "dd/MMM/yyyy")

                    strCode = clsCommon.myCstr(grow.Cells(2).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Company EPF Share(%) can not be blank or incorrect.")
                    End If
                    obj.COEPF_PER = strCode

                    strCode = clsCommon.myCstr(grow.Cells(3).Value)
                    If strCode.Length >= 2 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Company EPF Round Off Type can not be blank or incorrect.")
                    End If
                    obj.COEPF_ROUNDOFF_YPE = strCode

                    strCode = clsCommon.myCstr(grow.Cells(4).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Company EPS Share(%) can not be blank or incorrect.")
                    End If
                    obj.COEPS_PER = strCode

                    strCode = clsCommon.myCstr(grow.Cells(5).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Max EPS Amount can not be blank or incorrect.")
                    End If
                    obj.EPS_MAX = strCode

                    strCode = clsCommon.myCstr(grow.Cells(6).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Company Admin Charges on EPF(ACEPF) can not be blank or incorrect.")
                    End If
                    obj.ACCOEPF_PER = strCode

                    strCode = clsCommon.myCstr(grow.Cells(7).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Max amount of ACEPF can not be blank or incorrect.")
                    End If
                    obj.ACCOEPF_MAX = strCode

                    strCode = clsCommon.myCstr(grow.Cells(8).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("EDLI Paid by Company can not be blank or incorrect.")
                    End If
                    obj.COEDLI_PER = strCode

                    strCode = clsCommon.myCstr(grow.Cells(9).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Max of EDLI can not be blank or incorrect.")
                    End If
                    obj.COEDLI_MAX = strCode

                    strCode = clsCommon.myCstr(grow.Cells(10).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Admin Charges on EDLI(ACEDLI) can not be blank or incorrect.")
                    End If
                    obj.ACCOEDLI_PER = strCode

                    strCode = clsCommon.myCstr(grow.Cells(11).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Max of ACEDLI can not be blank or incorrect.")
                    End If
                    obj.ACCOEDLI_MAX = strCode

                    strCode = clsCommon.myCstr(grow.Cells(11).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Min of ACEDLI can not be blank or incorrect.")
                    End If
                    obj.ACCOEDLI_MIN = strCode


                    strCode = clsCommon.myCstr(grow.Cells(12).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Employee EPF Share(%) can not be blank or incorrect.")
                    End If
                    obj.EMPEPF_PER = strCode

                    strCode = clsCommon.myCstr(grow.Cells(13).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Max amount of ACEPF can not be blank or incorrect.")
                    End If
                    obj.EMPEPF_MAX = strCode

                    strCode = clsCommon.myCstr(grow.Cells(14).Value)
                    If strCode.Length >= 2 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Employee EPF Round Off Type can not be blank or incorrect.")
                    End If
                    obj.EMPEPF_ROUNDOFF_YPE = strCode

                    strCode = clsCommon.myCstr(grow.Cells(15).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Other Charges(OC) can not be blank or incorrect.")
                    End If
                    obj.OC = strCode


                    strCode = clsCommon.myCstr(grow.Cells(16).Value)
                    If strCode.Length >= 2 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Other Charges Round off type can not be blank or incorrect.")
                    End If
                    obj.OTH_ROUNDOFF_YPE = strCode

                    strCode = clsCommon.myCstr(grow.Cells(17).Value)
                    If strCode.Length > 10 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Max of Other Charges(OC) can not be blank or incorrect.")
                    End If
                    obj.OC_MAX = strCode

                    obj.SaveData(obj, clsPFRulesMaster.CheckNewEntry(obj.Code))
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub MenuItemExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemExport.Click

        Dim str As String
        str = " select PFRULE_CODE as Code, APPLICABLE_FROM AS Date,[COEPF_PER] as 'Company EPF Share(%)', [COEPF_ROUNDOFF_YPE] as 'Company EPF Round Off Type',[COEPS_PER] as 'Company EPS Share(%)',[EPS_MAX] as 'Max EPS Amount',"
        str += " [ACCOEPF_PER] as 'Company Admin Charges on EPF(ACEPF)',[ACCOEPF_MAX] as 'Max amount of ACEPF',[COEDLI_PER] as 'EDLI Paid by Company',[COEDLI_MAX] as 'Max of EDLI', "
        str += " [ACCOEDLI_PER] as 'Admin Charges on EDLI(ACEDLI)' ,[ACCOEDLI_MAX] as 'Max of ACEDLI',[ACCOEDLI_MIN] as 'Min of ACEDLI', "
        str += " [EMPEPF_PER] as 'Employee EPF Share(%)',[EMPEPF_MAX] as 'Max EPF Amount',[EMPEPF_ROUNDOFF_YPE] as 'Employee EPF Round Off Type', "
        str += " [OC] as 'Other Charges(OC)', OTH_ROUNDOFF_YPE as 'Other Charges Round off type',[OC_MAX] as 'Max of Other Charges(OC)' from TSPL_PF_RULE_MASTER"
        transportSql.ExporttoExcel(str, Me)

    End Sub

    Private Sub MenuItemClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemClose.Click
        funClose()

    End Sub


End Class
