'--11/10/2013--form Add By- Pradeep Sharma ---------
'updated @ BM00000000705
Imports common
Imports System.Data
Imports System.Data.SqlClient
Imports XpertERPEngine
Imports Telerik.WinControls.UI

Public Class frmShiftMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String

#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        Save()
    End Sub

    Public Sub Save()
        If AllowToSave() Then

            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmShiftMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            Dim obj As New clsShiftMaster()
            obj.Code = txtCode.Value
            Dim dtt As New DateTime()
            dtt = dtpTo.Value
            obj.ToTime = dtt.TimeOfDay.ToString()
            dtt = dtpFrom.Value()
            obj.FromTime = dtt.TimeOfDay.ToString()
            obj.Name = txtName.Text
            dtt = DtpIntervalTime.Value()
            obj.INTERVAL_Time = dtt.TimeOfDay.ToString()
            obj.FSTHALF_ADJUST_MIN = txtFstAdjMin.Value
            obj.SECHALF_ADJUST_MIN = txtSndAdjMin.Value

            If (obj.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                LoadData(obj.Code, NavigatorType.Current)
                'Else
                '    common.clsCommon.MyMessageBoxShow("This '" & obj.Code & "' already exist ")
            End If

        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnSave.Enabled = True
        btnDelete.Enabled = True
        isNewEntry = False
        Dim obj As New clsShiftMaster()
        obj = clsShiftMaster.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            txtCode.Value = obj.Code
            txtName.Text = obj.Name

            Dim strTemp() As String
            strTemp = Split(obj.FromTime, ":")
            If strTemp.Length > 1 Then
                Dim dtt As New DateTime(2013, 1, 1, Convert.ToInt16(strTemp(0)), Convert.ToInt16(strTemp(1)), Convert.ToInt16(strTemp(2).Substring(0, 2)))
                dtpFrom.Value = dtt
            End If

            strTemp = Split(obj.ToTime, ":")
            If strTemp.Length > 1 Then
                Dim dtt2 As New DateTime(2013, 1, 1, Convert.ToInt16(strTemp(0)), Convert.ToInt16(strTemp(1)), Convert.ToInt16(strTemp(2).Substring(0, 2)))
                dtpTo.Value = dtt2
            End If

            strTemp = Split(obj.INTERVAL_Time, ":")
            If strTemp.Length > 1 Then
                Dim dtt3 As New DateTime(2013, 1, 1, Convert.ToInt16(strTemp(0)), Convert.ToInt16(strTemp(1)), Convert.ToInt16(strTemp(2).Substring(0, 2)))
                DtpIntervalTime.Value = dtt3
            End If

            txtFstAdjMin.Value = obj.FSTHALF_ADJUST_MIN
            txtSndAdjMin.Value = obj.SECHALF_ADJUST_MIN
        End If

    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
             myMessages.blankValue("Code")
            txtCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtName.Text) <= 0 Then
            myMessages.blankValue("Shift Name")
            txtName.Focus()
            Return False

        ElseIf clsCommon.myLen(dtpTo.Value.ToLongTimeString()) <= 0 Then
            myMessages.blankValue("To Time")
            dtpTo.Focus()
            Return False
        ElseIf clsCommon.myLen(dtpFrom.Value.ToLongTimeString()) <= 0 Then
            myMessages.blankValue("From Time")
            dtpFrom.Focus()
            Return False
        ElseIf clsCommon.myLen(DtpIntervalTime.Value.ToLongTimeString()) <= 0 Then
            myMessages.blankValue("From Time")
            DtpIntervalTime.Focus()
            Return False

        End If
        Return True
    End Function


    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "You Cannot Delete Record", Me.Text)
            Exit Sub
        End If
        'Dim discCode As String
        'discCode = clsDBFuncationality.getSingleValue("select SHIFT_CODE  from TSPL_SHIPMENT_DETAILS  where SHIFT_CODE ='" & txtCode.Value & "'")
        'If clsCommon.myLen(discCode) > 0 Then
        '    common.clsCommon.MyMessageBoxShow("This record can't be deleted.It is used in another process")
        '    Exit Sub
        'End If
        '' Code Ends 
        funDelete()
    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsShiftMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub frmShiftMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isNewEntry = True

        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        '  ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")

    End Sub

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmShiftMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 02/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            MenuItemImport.Enabled = True
            MenuItemExport.Enabled = True
        Else
            MenuItemImport.Enabled = False
            MenuItemExport.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        txtName.Text = ""

        dtpTo.Value = Now
        'dtpTo.Value = DateTime.Now.ToLongTimeString()
        dtpFrom.Value = Now
        'dtpFrom.Value = DateTime.Now.ToLongTimeString()
        'DtpIntervalTime.Value = DateTime.Now.ToLongTimeString()
        DtpIntervalTime.Value = Now
        txtSndAdjMin.Value = Nothing
        txtFstAdjMin.Value = Nothing
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = True
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()

    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating

        Dim str As String = "select count(*) from TSPL_SHIFT_MASTER where SHIFT_CODE ='" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtCode.MyReadOnly = False
            'txtCode.Value = ""
            '' common.clsCommon.MyMessageBoxShow("Value doesn't exist ")
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then


            'Dim qry As String = "select SHIFT_CODE as Code, SHIFT_NAME AS Name, FROM_Time AS 'From Time', TO_Time AS 'To Time'  from TSPL_SHIFT_MASTER"
            'txtCode.Value = clsCommon.ShowSelectForm("SHIFT_Master", qry, "Code", "", txtCode.Value, "SHIFT_CODE", isButtonClicked)
            txtCode.Value = clsShiftMaster.getFinder("", txtCode.Value, isButtonClicked)
            If txtCode.Value <> "" Then
                LoadData(txtCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If


    End Sub

    Sub funFill()

    End Sub

    Private Sub txtCode_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCode.KeyPress
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub frmShiftMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub MenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Shift Name", "From Time", "To Time", "Interval Time", "Ist Half Adjust Min", "IInd Half Adjust Min") Then
            ' Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsShiftMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.Code = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells(1).Value)
                    If strName.Length > 100 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Name can not be blank or incorrect.")
                    End If
                    obj.Name = strName

                    Dim strTemp() As String
                    strTemp = Split(clsCommon.myCstr(grow.Cells(2).Value), ":")
                    If strTemp.Length > 1 Then
                        Dim dtt As New DateTime(2013, 1, 1, Convert.ToInt16(strTemp(0)), Convert.ToInt16(strTemp(1)), Convert.ToInt16(strTemp(2).Substring(0, 2)))
                        obj.FromTime = dtt.TimeOfDay.ToString()
                    End If

                    strTemp = Split(clsCommon.myCstr(grow.Cells(3).Value), ":")
                    If strTemp.Length > 1 Then
                        Dim dtt2 As New DateTime(2013, 1, 1, Convert.ToInt16(strTemp(0)), Convert.ToInt16(strTemp(1)), Convert.ToInt16(strTemp(2).Substring(0, 2)))
                        obj.ToTime = dtt2.TimeOfDay.ToString()
                    End If

                    strTemp = Split(clsCommon.myCstr(grow.Cells(4).Value), ":")
                    If strTemp.Length > 1 Then
                        Dim dtt3 As New DateTime(2013, 1, 1, Convert.ToInt16(strTemp(0)), Convert.ToInt16(strTemp(1)), Convert.ToInt16(strTemp(2).Substring(0, 2)))
                        obj.INTERVAL_Time = dtt3.TimeOfDay.ToString()
                    End If

                    obj.FSTHALF_ADJUST_MIN = Convert.ToInt16(clsCommon.myCdbl(grow.Cells(5).Value))
                    obj.SECHALF_ADJUST_MIN = Convert.ToInt16(clsCommon.myCdbl(grow.Cells(6).Value))

                    obj.SaveData(obj, clsShiftMaster.CheckNewEntry(obj.Code))
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub MenuItemExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemExport.Click

        Dim str As String
        str = "select SHIFT_CODE as Code, SHIFT_NAME AS [Shift Name], CONVERT( varchar(20),FROM_Time,108) AS [From Time],CONVERT( varchar(20),TO_Time,108) AS [To Time], CONVERT( varchar(20),INTERVAL_Time,108) AS [Interval Time], FSTHALF_ADJUST_MIN as 'Ist Half Adjust Min' , SECHALF_ADJUST_MIN as 'IInd Half Adjust Min' from TSPL_SHIFT_MASTER"
        transportSql.ExporttoExcel(str, Me)

    End Sub

    Private Sub MenuItemClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemClose.Click
        funClose()

    End Sub
End Class
