Imports common
Imports System.Data.SqlClient
Imports XpertERPEngine
Imports Telerik.WinControls.UI
Imports Telerik.WinControls

Public Class FrmAMAcquisitionCode
    Inherits FrmMainTranScreen

#Region "Variables"
    Private isNewEntry As Boolean = False
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim strSql As String
#End Region
    Private Sub SetUserMgmtNew()

        '' Anubhooti 17-July-2014 BM00000003126
        'MyBase.SetUserMgmt(clsUserMgtCode.FrmAMAcquisitionCode)
        If Not (MyBase.isReadFlag) Then
            'common.clsCommon.MyMessageBoxShow("Permission Denied")
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnSave.Visible = MyBase.isModifyFlag
        btnDelete.Visible = MyBase.isDeleteFlag
        '--------richa Ticket no. BM00000003014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            rmExport.Enabled = True
            rmImport.Enabled = True
        Else
            rmExport.Enabled = False
            rmImport.Enabled = False
        End If
        '--------------------------------------------------
    End Sub

    Private Sub FrmAMAcquisitionCode_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnAddNew.Enabled Then
            AddNew()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C AndAlso btnClose.Enabled Then
            CloseForm()
        End If
    End Sub
    Private Sub FrmAMAcquisitionCode_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(btnAddNew, "Press Alt+N Adding New Trasnaction")
        AddNew()
        SetLength()
    End Sub
    Sub SetLength()
        txtAcqCode.MyMaxLength = 30
        txtDesc.MaxLength = 100

    End Sub

    Sub AddNew()
        txtAcqCode.MyReadOnly = False
        BlankAllControls()
        isNewEntry = True
        btnSave.Text = "Save"
    End Sub

    Sub BlankAllControls()
        txtAcqCode.Value = ""
        txtDesc.Text = ""
        cmbAcqWith.Text = "AP"
        cmbType.Text = "Create A/P Invoice"
        txtAccount.Value = ""
        txtVendor.Value = ""
        lblDefaultAcct.Text = ""
        lblVendorName.Text = ""
    End Sub
    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(txtAcqCode.Value) <= 0 Then
                common.clsCommon.MyMessageBoxShow(Me, "Please Enter Code", Me.Text)
                txtAcqCode.Focus()
                Return False
            End If
        End If
        If clsCommon.myLen(txtDesc.Text) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "Please Enter Description", Me.Text)
            txtDesc.Focus()
            Return False
        End If
        If clsCommon.myLen(txtAccount.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "Please Enter Default Account", Me.Text)
            txtAccount.Focus()
            Return False
        End If

        Return True
    End Function

    Private Sub SaveData()
        Try
            If (AllowToSave()) Then
                Dim obj As New clsAcquisitionCodes()
                obj.Code = txtAcqCode.Value
                obj.Description = txtDesc.Text
                obj.Acqu_with = cmbAcqWith.Text
                obj.Type = cmbType.Text
                obj.Default_Account = txtAccount.Value
                obj.Vendor_Code = txtVendor.Value

                If obj.SaveData(obj, isNewEntry) Then
                    clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                    LoadData(obj.Code, NavigatorType.Current)
                End If
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Try
            isNewEntry = False
            btnSave.Text = "Update"
            BlankAllControls()
            txtAcqCode.MyReadOnly = True
            Dim obj As New clsAcquisitionCodes()
            obj = clsAcquisitionCodes.GetData(strCode, NavTyep, Nothing)
            If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
                txtAcqCode.Value = obj.Code
                txtDesc.Text = obj.Description
                cmbAcqWith.Text = obj.Acqu_with
                cmbType.Text = obj.Type

                txtAccount.Value = obj.Default_Account
                lblDefaultAcct.Text = clsGLAccount.GetName(obj.Default_Account)
                txtVendor.Value = obj.Vendor_Code
                If txtVendor.Value <> "" Then
                    lblVendorName.Text = clsVendorMaster.GetName(obj.Vendor_Code, Nothing)
                End If
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub txtAcqCode__MYNavigator(ByVal sender As Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtAcqCode._MYNavigator
        LoadData(txtAcqCode.Value, NavType)
    End Sub

    Private Sub txtAcqCode__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles txtAcqCode._MYValidating
        Try
            strSql = "select count(*) from TSPL_ACQUISITION_CODES where Code='" + txtAcqCode.Value + "'"
            Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(strSql))
            If count = 0 Then
                txtAcqCode.MyReadOnly = False
            Else
                txtAcqCode.MyReadOnly = True
            End If
            If txtAcqCode.MyReadOnly OrElse isButtonClicked Then

                'strSql = "select Code,Description from TSPL_ACQUISITION_CODES"
                'LoadData(clsCommon.ShowSelectForm("AcquisitionCode", strSql, "Code", "", txtAcqCode.Value, "Code", isButtonClicked), NavigatorType.Current)
                LoadData(clsAcquisitionCodes.getFinder("", txtAcqCode.Value, isButtonClicked), NavigatorType.Current)
                LoadData(txtAcqCode.Value, NavigatorType.Current)
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub

    Sub DeleteData()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsAcquisitionCodes.DeleteData(txtAcqCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully", Me.Text)
                    AddNew()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        CloseForm()
    End Sub

    Sub CloseForm()
        Me.Close()
    End Sub

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        SaveData()
    End Sub

    Private Sub btnAddNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnAddNew.Click
        AddNew()
    End Sub

    Private Sub txtVendor__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles txtVendor._MYValidating
        Try
            'strSql = "select Vendor_Code as Code,Vendor_Name as Name,TSPL_VENDOR_MASTER.add1 +case when len(TSPL_VENDOR_MASTER.add2)>0 then ', '+TSPL_VENDOR_MASTER.add2 else '' end +case when LEN(isnull(TSPL_VENDOR_MASTER.Add3,''))>0 then ', '+isnull(TSPL_VENDOR_MASTER.Add3,'') else ' ' end + case when LEN(TSPL_VENDOR_MASTER.City_Code_Desc)>0 then ', '+TSPL_VENDOR_MASTER.City_Code_Desc else ' ' end + case when len(TSPL_VENDOR_MASTER.State )>0 then TSPL_VENDOR_MASTER.State else '' end  as Address,Terms_Code as [Term Code] ,Terms_Code_Desc as [Term Description] ,Tax_Group as [Tax Group],Tax_Group_Desc as [Tax Group Description] from TSPL_VENDOR_MASTER"
            'txtVendor.Value = clsCommon.ShowSelectForm("POVendorFndr", strSql, "Code", "", txtVendor.Value, "Code", isButtonClicked)
            txtVendor.Value = clsVendorMaster.getFinder("", txtVendor.Value, isButtonClicked)
            strSql = "select  Vendor_Code,Vendor_Name,Terms_Code,Terms_Code_Desc ,Vendor_Account ,Tax_Group,Tax_Group_Desc from TSPL_VENDOR_MASTER where Vendor_Code ='" + txtVendor.Value + "'"
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(strSql)
            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
                lblVendorName.Text = clsCommon.myCstr(dt.Rows(0)("Vendor_Name"))
            Else
                lblVendorName.Text = ""
            End If
        Catch ex As Exception
            RadMessageBox.Show(ex.Message)
        End Try
    End Sub

    Private Sub txtAccount__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles txtAccount._MYValidating
        Try
            'strSql = " select  Account_Code , Description  from TSPL_GL_ACCOUNTS"
            'txtAccount.Value = clsCommon.ShowSelectForm("Account Finder", strSql, "Account_Code", "", txtAcqCode.Value, "Account_Code", isButtonClicked)
            txtAccount.Value = clsGLAccount.getFinder("", txtAccount.Value, isButtonClicked)
            If clsCommon.myLen(txtAccount.Value) > 0 Then
                lblDefaultAcct.Text = clsGLAccount.GetName(txtAccount.Value)
            Else
                lblDefaultAcct.Text = ""
            End If


            'strSql = clsERPFuncationality.glaccountquery()
            'Dim dt As DataTable = clsDBFuncationality.GetDataTable(strSql)
            'If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            '    lblDefaultAcct.Text = clsCommon.myCstr(dt.Rows(0)("Description"))
            'Else
            '    lblDefaultAcct.Text = ""
            'End If
        Catch ex As Exception
            RadMessageBox.Show(ex.Message)
        End Try
    End Sub

    Private Sub txtAccount_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles txtAccount.Load

    End Sub

    Private Sub cmbAcqWith_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As Telerik.WinControls.UI.Data.PositionChangedEventArgs) Handles cmbAcqWith.SelectedIndexChanged
        If cmbAcqWith.Text = "AP" Then
            cmbType.Visible = True
            lblType.Visible = True
            lblVenor.Visible = True
            lblVendorName.Visible = False
            txtVendor.Visible = False
        Else
            cmbType.Visible = False
            lblType.Visible = False
            lblVenor.Visible = False
            lblVendorName.Visible = False
            txtVendor.Visible = False
        End If
    End Sub

    Private Sub rmImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim trans As SqlTransaction = Nothing
        'trans = clsDBFuncationality.GetTransactin()
        If transportSql.importExcel(gv, "code", "Description", "Acqu with", "Type", "Default Account", "Vendor Code") Then
            Dim linno As Integer = 0
            Try

                connectSql.OpenConnection()

                clsCommon.ProgressBarShow()

                For Each grow1 As GridViewRowInfo In gv.Rows

                    Dim strDefaultAccount As String = clsCommon.myCstr(grow1.Cells("Default Account").Value)
                    Dim strDefaultVendor As String = clsCommon.myCstr(grow1.Cells("Vendor Code").Value)
                    If (String.IsNullOrEmpty(strDefaultAccount)) Or clsCommon.myLen(strDefaultAccount) > 0 Then
                        If CheckDefaultAccount(strDefaultAccount, trans) = False Then
                            Exit Sub
                        End If

                    End If
                    If (String.IsNullOrEmpty(strDefaultVendor)) Or clsCommon.myLen(strDefaultVendor) > 0 Then
                        If CheckDefaultVendor(strDefaultVendor, trans) = False Then
                            Exit Sub
                        End If

                    End If

                Next

                Dim obj As New clsAcquisitionCodes()


                For Each grow As GridViewRowInfo In gv.Rows


                    linno += 1
                    Dim strcode As String = clsCommon.myCstr(grow.Cells("Code").Value)
                    If (String.IsNullOrEmpty(strcode)) Or clsCommon.myLen(strcode) > 30 Then
                        Throw New Exception("Length of  Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Code = strcode

                    Dim strDescription As String = clsCommon.myCstr(grow.Cells("Description").Value)
                    If (String.IsNullOrEmpty(strDescription)) Or clsCommon.myLen(strDescription) > 100 Then
                        Throw New Exception("Length of Name should be max. 100 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Description = strDescription

                    Dim strAcquWith As String = clsCommon.myCstr(grow.Cells("Acqu with").Value)
                    If (String.IsNullOrEmpty(strAcquWith)) Or clsCommon.myLen(strAcquWith) > 30 Then
                        Throw New Exception("Length of  Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    ElseIf clsCommon.CompairString(strAcquWith, "AP") = CompairStringResult.Equal Or clsCommon.CompairString(strAcquWith, "GL") = CompairStringResult.Equal Then
                    Else
                        Throw New Exception("Acquisition With should be amoung 'AP','GL' At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Acqu_with = strAcquWith

                    Dim strType As String = clsCommon.myCstr(grow.Cells("Type").Value)
                    If (String.IsNullOrEmpty(strType)) Or clsCommon.myLen(strType) > 30 Then
                        Throw New Exception("Length of Name should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    ElseIf clsCommon.CompairString(strType, "Create A/P Invoice") = CompairStringResult.Equal Or clsCommon.CompairString(strType, "Create Misc Payment") = CompairStringResult.Equal Then
                    Else
                        Throw New Exception("Type should be amoung 'Create A/P Invoice','Create Misc Payment' At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If

                    obj.Type = strType

                    Dim strDefaultAccount As String = clsCommon.myCstr(grow.Cells("Default Account").Value)
                    If (String.IsNullOrEmpty(strDefaultAccount)) Or clsCommon.myLen(strDefaultAccount) > 50 Then
                        Throw New Exception("Length of  Code should be max. 50 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Default_Account = strDefaultAccount

                    Dim strVendorCode As String = clsCommon.myCstr(grow.Cells("Vendor Code").Value)
                    If (String.IsNullOrEmpty(strVendorCode)) Or clsCommon.myLen(strVendorCode) > 50 Then
                        Throw New Exception("Length of Name should be max. 50 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Vendor_Code = strVendorCode
                    'Dim trans As SqlTransaction
                    If clsCommon.myLen(strcode) > 0 AndAlso clsDBFuncationality.getSingleValue("Select count(*) from TSPL_ACQUISITION_CODES where code='" + strcode + "' ", trans) > 0 Then
                        isNewEntry = False
                    Else
                        isNewEntry = True

                    End If


                    obj.SaveData(obj, isNewEntry)

                Next

                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception

                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub rmExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmExport.Click
        Dim str As String
        str = "select code as [code],Description as [Description],Acqu_with as [Acqu with],Type as [Type],"
        str += " Default_Account as [Default Account],Vendor_Code as [Vendor Code]  from TSPL_ACQUISITION_CODES"
        transportSql.ExporttoExcel(str, Me)
    End Sub

    Private Function CheckDefaultAccount(ByVal AccountCode As String, ByVal trans As SqlTransaction) As Boolean

        Try
            If clsCommon.myLen(AccountCode) > 0 AndAlso clsDBFuncationality.getSingleValue("Select count(*) from TSPL_GL_ACCOUNTS where Account_Code='" + AccountCode + "' ", trans) > 0 Then
                Return True
            Else
                Throw New Exception("Default Account is Invalid,It Could Not Found in  Master")
                Return False
            End If

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
    Private Function CheckDefaultVendor(ByVal VendorCode As String, ByVal trans As SqlTransaction) As Boolean

        Try
            If clsCommon.myLen(VendorCode) > 0 AndAlso clsDBFuncationality.getSingleValue("Select count(*) from TSPL_VENDOR_MASTER where Vendor_Code='" + VendorCode + "' ", trans) > 0 Then
                Return True
            Else
                Throw New Exception("Default Vendor is Invalid,It Could Not Found in Vendor Master")
                Return False
            End If

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function

End Class
