Imports System.Data.SqlClient
Imports common
Imports XpertERPEngineFine

Public Class FrmBankGroupMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim str As String
    Public Property import As Object
    Public Property Export As Object

    Private Sub SetUserMgmtNew()
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
        End If
        btnSave.Visible = MyBase.isModifyFlag
        'If btnSave.Visible = True Then
        '    import.Enabled = True
        '    Export.Enabled = True
        'Else
        '    import.Enabled = False
        '    Export.Enabled = False
        'End If
        '--------------------------------------------------
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub frmbankgroupmaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        funreset()
        SetUserMgmtNew()
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New Trasnaction")
    End Sub
    Private Sub btnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        SaveData()
    End Sub
    Public Sub SaveData()
        'Dim trans As SqlTransaction = Nothing
        Try
            If AllowToSave() Then
                Dim obj As New clsBankGroupMaster()
                obj.BANK_GROUP_CODE = txtCode.Value
                obj.Description = txtName.Text
                Dim trans As SqlTransaction = Nothing
                If (obj.SaveData(obj, isNewEntry, trans)) Then
                    trans = clsDBFuncationality.GetTransactin()
                    trans.Commit()
                    common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                    ' LoadData(obj.BANK_CODE, NavigatorType.Current)
                Else
                    trans.Rollback()
                End If
            End If

        Catch ex As Exception
            'trans.Rollback()
            myMessages.myExceptions(ex)
        End Try
    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
            myMessages.blankValue("bankgroupmaster")
            txtCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtName.Text) <= 0 Then
            myMessages.blankValue("Description")
            txtName.Focus()
            Return False
        End If
        Return True
    End Function

    'Delete funtion call on delete button
    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Public Sub DeleteData()
        If btnDelete.Enabled = False Then
            Exit Sub
        End If
        If txtCode.Value = "" Then
            myMessages.blankValue(txtCode.MyLinkLable1.Text)
            txtCode.Focus()
        ElseIf myMessages.deleteConfirm() Then
            If (clsBankGroupMaster.DeleteData(txtCode.Value)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully", Me.Text)
                funreset()
            End If
        End If
    End Sub

    Private Sub btnnew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funreset()
    End Sub
    'It will reset all the controls in screens
    Public Sub funreset()
        txtCode.Value = Nothing
        txtCode.MyReadOnly = False
        isNewEntry = True
        txtName.Text = ""
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = True
    End Sub
    'closing of current window form
    Private Sub btnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        Me.Close()
    End Sub

    'For Import functionality 
    Private Sub import_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) 'Handles import.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Break Down Code", "Break Down Name") Then
            Dim trans As SqlTransaction = Nothing

            Dim linno As Integer = 0
            Dim TempNewRecord As Boolean = False
            Try
                ' connectSql.OpenConnection()
                trans = clsDBFuncationality.GetTransactin()

                clsCommon.ProgressBarShow()

                Dim strcode As String = ""
                Dim strname As String = ""

                For Each grow As GridViewRowInfo In gv.Rows
                    linno += 1
                    strcode = clsCommon.myCstr(grow.Cells(0).Value)
                    If (String.IsNullOrEmpty(strcode)) Or clsCommon.myLen(strcode) > 30 Then
                        Throw New Exception("Length of Bank Group Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    strname = clsCommon.myCstr(grow.Cells(1).Value)
                    If (String.IsNullOrEmpty(strname)) Or clsCommon.myLen(strname) > 200 Then
                        Throw New Exception("Length of Bank Group Name should be max. 200 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If

                    Dim obj As Object = New clsBankGroupMaster()
                    obj.Code = strcode
                    obj.Name = strname


                    Dim Count1 As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue("Select COunt(*) from TSPL_BANK_GROUP_MASTER WHERE code='" + clsCommon.myCstr(grow.Cells(0).Value) + "'", trans))
                    If Count1 <= 0 Then
                        obj.SaveData(obj, True, trans)
                    Else
                        obj.SaveData(obj, False, trans)
                    End If


                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                trans.Rollback()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub
    Public Sub closeform()
        Me.Close()
    End Sub

    Private Sub frmbankgroupmaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            closeform()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funreset()
        ElseIf e.Alt AndAlso e.Shift AndAlso e.Control And e.KeyCode = Keys.F12 Then
            ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update Trasnaction" + Environment.NewLine +
                                                             "TSPL_BANK_GROUP_MASTER")
        End If
    End Sub


    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        Dim qst As String = "select count(*) from TSPL_BANK_GROUP_MASTER where BANK_GROUP_CODE='" + txtCode.Value + "'"
        Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qst))
        If count = 0 Then
            txtCode.MyReadOnly = False
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then
            Dim whrClas As String = ""
            Dim qry As String = " select BANK_GROUP_CODE as [BANK_GROUP_CODE],DESCRIPTION as [DESCRIPTION],Created_By as [Created By],Created_Date as [Created Date],Modify_By as [Modify By],Modify_Date as [Modify Date],Comp_Code as [Company Code] from TSPL_BANK_GROUP_MASTER  "
            txtCode.Value = clsCommon.ShowSelectForm("RPTBDMST", qry, "BANK_GROUP_CODE", whrClas, txtCode.Value, "BANK_GROUP_CODE", isButtonClicked)
            LoadData(txtCode.Value, NavigatorType.Current)
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try

    End Sub
    Public Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Try
            txtCode.MyReadOnly = True
            btnSave.Enabled = True
            btnDelete.Enabled = True
            isNewEntry = False
            Dim obj As Object = New clsBankGroupMaster()
            obj = clsBankGroupMaster.GetData(strCode, NavTyep)
            If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.BANK_GROUP_CODE) > 0) Then
                funreset()
                isNewEntry = False
                btnSave.Text = "Update"
                txtCode.Value = obj.BANK_GROUP_CODE
                txtName.Text = obj.DESCRIPTION
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
End Class
