Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports Telerik.WinControls.Data
Imports System.Text.RegularExpressions
Imports common
'preeti gupta ticket no[BM00000003974]
'created by --> Vipin
'createddate --> 20/05/2011
'modifiedby --> Vipin
'Modified date -->03/06/2011
'Tables Used --> tspl_city_master
'Modify by pradeep -->11/07/2012
''RICHA AGARWAL AGAINST TICKET NO BM00000004602 12/11/2014

Public Class frmCityMaster
    Inherits FrmMainTranScreen
    Const colSelect As String = "SELECT"
    Const colCompCode As String = "COMPCODE"
    Const colCompName As String = "COMPNAME"
    Const colDataBaseName As String = "DATABASE"
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String
    Dim str As String

    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub

    Private Sub SetUserMgmtNew()
        '' Anubhooti 30-July-2014 BM00000003131
        'MyBase.SetUserMgmt(clsUserMgtCode.cityMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnsave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 03/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnsave.Visible = True Then
            cityimport.Enabled = True
            cityexport.Enabled = True
        Else
            cityimport.Enabled = False
            cityexport.Enabled = False
        End If
        '--------------------------------------------------
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub CityMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        funreset()
        SetUserMgmtNew()
        SetDataBaseGrid()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnnew, "Press Alt+N Adding New Trasnaction")
        ToolTipcity.SetToolTip(btnnew, "New")
        btnsave.Enabled = True
        btndelete.Enabled = False
    End Sub

    'Keypress validation on finder and converting lower case to upper case
    Public Sub key_press(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If
    End Sub
    'Validation on save button click and calling funinsert,funupdate
    Private Sub btnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click
        SaveData()
    End Sub
    Public Sub SaveData()
        If MyBase.isModifyonPasswordFlag Then
            If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.cityMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
            Else
                Return
            End If
        End If
        ' Dim trans As SqlTransaction = Nothing
        Try
            If AllowToSave() Then
                '    trans = clsDBFuncationality.GetTransactin
                Dim obj As New clsCityMaster()
                obj.City_Code = fndcity.Value
                obj.City_Name = txtdes.Text
                obj.STATE_CODE = txtState.Value
                obj.regioncode = clsCommon.myCstr(txtregioncode.Text)
                obj.DISTRICT_Code = txtDistrict.Value
                obj.IsDefault = IIf(chkIsDefault.Checked = True, 1, 0)
                If (obj.SaveData(obj, isNewEntry)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                    'trans.Commit()
                    LoadData(obj.City_Code, NavigatorType.Current)
                    'Else
                    '    common.clsCommon.MyMessageBoxShow("This '" & obj.Code & "' already exist ")
                End If
            End If
        Catch ex As Exception
            '  trans.Rollback()
            myMessages.myExceptions(ex)
        End Try
    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(fndcity.Value) <= 0 Then
            myMessages.blankValue("City Code")
            fndcity.Focus()
            Return False
        ElseIf clsCommon.myLen(txtdes.Text) <= 0 Then
            myMessages.blankValue("Description")
            txtdes.Focus()
            Return False
        ElseIf clsCommon.myLen(txtState.Value) <= 0 Then
            myMessages.blankValue("State")
            txtState.Focus()
            Return False
        End If
        Return True
    End Function

    'Delete funtion call on delete button
    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub
    Public Sub DeleteData()
        If btndelete.Enabled = False Then
            Exit Sub
        End If
        If fndcity.Value = "" Then
            myMessages.blankValue("Transporter code")
        ElseIf myMessages.deleteConfirm() Then
            If (clsCityMaster.DeleteData(fndcity.Value)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                funreset()
            End If
        End If
    End Sub

    Private Sub btnnew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnnew.Click
        funreset()
    End Sub
    'It will reset all the controls in screens
    Public Sub funreset()
        txtregioncode.Text = ""
        txtregionname.Text = ""
        fndcity.Value = Nothing
        fndcity.MyReadOnly = False
        isNewEntry = True
        txtdes.Text = ""
        txtState.Value = Nothing
        lblState.Text = ""
        chkIsDefault.Checked = False
        btnsave.Text = "Save"
        btnsave.Enabled = True
        btndelete.Enabled = True
        For i As Integer = 0 To gvDB.Rows.Count - 1
            If gvDB.Rows(i).Cells(0).Value = True Then
                gvDB.Rows(i).Cells(0).Value = False
            End If
        Next
    End Sub
    'closing of current window form
    Private Sub btnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        Me.Close()
    End Sub
    Private Sub cityexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cityexport.Click
        Dim str As String
        str = "select city_Code As [City Code], city_name as [City Name],STATE_CODE as [State Code],Region_code as [Region Code],DISTRICT_Code as [District Code] from tspl_city_master"

        ListImpExpColumnsMandatory = New List(Of String)({"City Code", "City Name", "State Code"})
        ListImpExpColumnsSuperMandatory = New List(Of String)({"City Code"})
        transportSql.ExporttoExcel(str, "", "", Me, ListImpExpColumnsMandatory, ListImpExpColumnsSuperMandatory, MyBase.Form_ID)
    End Sub
    'For Import functionality 
    Private Sub cityimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cityimport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "City Code", "City Name", "State Code", "Region Code", "District Code") Then
            ' Dim trans As SqlTransaction = Nothing
            Dim linno As Integer = 0
            Try
                ' connectSql.OpenConnection()
                ' trans = clsDBFuncationality.GetTransactin()

                clsCommon.ProgressBarShow()


                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsCityMaster()
                    linno += 1
                    Dim strcode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If (String.IsNullOrEmpty(strcode)) Or clsCommon.myLen(strcode) > 50 Then
                        Throw New Exception("Length of City Code should be max. 50 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.City_Code = strcode

                    Dim strname As String = clsCommon.myCstr(grow.Cells(1).Value)
                    If (String.IsNullOrEmpty(strname)) Or clsCommon.myLen(strname) > 50 Then
                        Throw New Exception("Length of City Name should be max. 50 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.City_Name = strname

                    Dim strState As String = clsCommon.myCstr(grow.Cells(2).Value)
                    If (String.IsNullOrEmpty(strState)) Or clsCommon.myLen(strState) > 30 Then
                        Throw New Exception("Length of State Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.STATE_CODE = strState

                    obj.regioncode = clsCommon.myCstr(grow.Cells("region code").Value)
                    If clsCommon.myLen(obj.regioncode) > 30 Then
                        Throw New Exception("Length of Region Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If

                    obj.DISTRICT_Code = clsCommon.myCstr(grow.Cells("District Code").Value)

                    If clsCommon.myLen(obj.DISTRICT_Code) > 0 Then
                        If clsCommon.myLen(obj.DISTRICT_Code) > 30 Then
                            Throw New Exception("Length of District Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                        End If

                        obj.DISTRICT_Code = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Code from TSPL_DISTRICT_MASTER where Code='" + obj.DISTRICT_Code + "'"))
                        If clsCommon.myLen(obj.DISTRICT_Code) <= 0 Then
                            Throw New Exception("Not valid District Code : " + clsCommon.myCstr(grow.Cells("District Code").Value) + " . " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If


                    Dim dtCheck As DataTable = clsDBFuncationality.GetDataTable("select 1 from TSPL_STATE_MASTER_DETAIL where STATE_CODE='" + obj.STATE_CODE + "'")
                    If dtCheck IsNot Nothing AndAlso dtCheck.Rows.Count > 0 Then
                        dtCheck = clsDBFuncationality.GetDataTable("select 1 from TSPL_STATE_MASTER_DETAIL where STATE_CODE='" + obj.STATE_CODE + "' and Region_Code='" + obj.regioncode + "'")
                        If dtCheck Is Nothing OrElse dtCheck.Rows.Count <= 0 Then
                            Throw New Exception("State-" + obj.STATE_CODE + " Region-" + obj.regioncode + "  is not mapped in state master.")
                        End If
                    End If
                    obj.SaveData(obj, True)
                Next
                'trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                'trans.Rollback()
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub
    'For closing current screen by menu strip Close
    Private Sub cityclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cityclose.Click
        closeform()
    End Sub
    Public Sub closeform()
        Me.Close()
    End Sub

    Private Sub frmCityMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            closeform()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funreset()
        End If
    End Sub

    Private Function GetReplecateCompaniesDataBase() As List(Of String)
        Dim arrDBName As New List(Of String)
        arrDBName.Add(objCommonVar.CurrDatabase)
        For ii As Integer = 0 To gvDB.Rows.Count - 1
            If (clsCommon.myCBool(gvDB.Rows(ii).Cells(colSelect).Value)) Then
                arrDBName.Add(clsCommon.myCstr(gvDB.Rows(ii).Cells(colDataBaseName).Value))
            End If
        Next
        Return arrDBName
    End Function

    Sub SetDataBaseGrid()
        gvDB.Rows.Clear()
        gvDB.Columns.Clear()

        Dim repoSelect As GridViewCheckBoxColumn = New GridViewCheckBoxColumn()
        repoSelect.FormatString = ""
        repoSelect.HeaderText = "Select"
        repoSelect.Name = colSelect
        repoSelect.Width = 50
        repoSelect.ReadOnly = False
        repoSelect.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
        gvDB.MasterTemplate.Columns.Add(repoSelect)

        Dim repoCompCode As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoCompCode.FormatString = ""
        repoCompCode.HeaderText = "Company Code"
        repoCompCode.Name = colCompCode
        repoCompCode.Width = 150
        repoCompCode.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoCompCode)

        Dim repoCompName As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoCompName.FormatString = ""
        repoCompName.HeaderText = "Company Name"
        repoCompName.Name = colCompName
        repoCompName.Width = 150
        repoCompName.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoCompName)

        Dim repoDB As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoDB.FormatString = ""
        repoDB.HeaderText = "Database Name"
        repoDB.Name = colDataBaseName
        repoDB.IsVisible = False
        repoDB.ReadOnly = True
        gvDB.MasterTemplate.Columns.Add(repoDB)

        Dim qry As String = "SELECT Comp_Code,Comp_Name,DataBase_Name from TSPL_COMPANY_MASTER where len(isnull(DataBase_Name,''))>0 and Comp_Code not in ('" + objCommonVar.CurrentCompanyCode + "')"
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            For Each dr As DataRow In dt.Rows
                gvDB.Rows.AddNew()
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colSelect).Value = False
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colCompCode).Value = clsCommon.myCstr(dr("Comp_Code"))
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colCompName).Value = clsCommon.myCstr(dr("Comp_Name"))
                gvDB.Rows(gvDB.Rows.Count - 1).Cells(colDataBaseName).Value = clsCommon.myCstr(dr("DataBase_Name"))
            Next
        End If
    End Sub

    Private Sub fndcity__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndcity._MYValidating
        Dim qst As String = "select count(*) from TSPL_City_MASTER where City_Code='" + fndcity.Value + "'"
        Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qst))
        If count = 0 Then
            fndcity.MyReadOnly = False
        Else
            fndcity.MyReadOnly = True
        End If
        If fndcity.MyReadOnly OrElse isButtonClicked Then
            'Dim qry As String = " select City_Code As Code,City_Name  as [City Name] ,STATE_CODE as [State Code] from TSPL_City_MASTER "
            'fndcity.Value = clsCommon.ShowSelectForm("frmCity", qry, "Code", "", fndcity.Value, "", isButtonClicked)
            fndcity.Value = clsCityMaster.getFinder("", fndcity.Value, isButtonClicked)
            LoadData(fndcity.Value, NavigatorType.Current)
        End If
    End Sub

    Private Sub fndcity__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndcity._MYNavigator
        Try
            LoadData(fndcity.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try

    End Sub
    Public Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Try
            fndcity.MyReadOnly = True
            btnsave.Enabled = True
            btndelete.Enabled = True
            isNewEntry = False
            Dim obj As New clsCityMaster()
            obj = clsCityMaster.GetData(strCode, NavTyep)
            If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.City_Code) > 0) Then
                funreset()
                isNewEntry = False
                btnsave.Text = "Update"
                fndcity.Value = obj.City_Code
                txtdes.Text = obj.City_Name
                txtState.Value = obj.STATE_CODE
                lblState.Text = obj.STATE_NAME
                txtregioncode.Text = obj.regioncode
                txtregionname.Text = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select region_name from tspl_region_master where region_code='" + obj.regioncode + "'"))
                txtDistrict.Value = obj.DISTRICT_Code
                lblDistrictName.Text = clsDistrictMaster.GetName(obj.DISTRICT_Code)
                chkIsDefault.Checked = IIf(obj.IsDefault = 1, True, False)
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub

    Private Sub gvDB_UserDeletingRow(ByVal sender As System.Object, ByVal e As Telerik.WinControls.UI.GridViewRowCancelEventArgs) Handles gvDB.UserDeletingRow
        If common.clsCommon.MyMessageBoxShow(Me, "Delete The Current Row." + Environment.NewLine + "Are you sure?", Me.Text, MessageBoxButtons.YesNo) = System.Windows.Forms.DialogResult.No Then
            e.Cancel = True
        End If
    End Sub

    Private Sub txtState__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtState._MYValidating
        Try
            Dim qry As String = " select TSPL_State_MASTER.STATE_CODE as [Code],TSPL_State_MASTER.STATE_NAME as [State Name],TSPL_State_MASTER.COUNTRY_CODE as [Country Code],TSPL_State_MASTER_detail.region_code as [Region Code],tspl_region_master.region_name as [Region Name] ,TSPL_State_MASTER.Created_By as [Created By],TSPL_State_MASTER.Created_Date as [Created Date],TSPL_State_MASTER.Modified_By as [Modify By],TSPL_State_MASTER.Modified_Date as [Modify Date]  from TSPL_State_MASTER left outer join TSPL_State_MASTER_detail on TSPL_State_MASTER.state_code=TSPL_State_MASTER_detail.state_code left outer join tspl_region_master on tspl_region_master.region_code=TSPL_State_MASTER_detail.region_code"
            Dim dr As DataRow = clsCommon.ShowSelectFormForRow("STATE_MASTER", qry)

            If dr IsNot Nothing Then
                txtState.Value = clsCommon.myCstr(dr("code"))
                lblState.Text = clsCommon.myCstr(dr("state name"))
                txtregioncode.Text = clsCommon.myCstr(dr("region code"))
                txtregionname.Text = clsCommon.myCstr(dr("region name"))
            End If

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try

    End Sub


    Private Sub txtDistrict__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtDistrict._MYValidating
        Try
            Dim qry As String = "select TSPL_DISTRICT_MASTER.Code as Code,TSPL_DISTRICT_MASTER.Name as DistrictName,TSPL_State_MASTER.STATE_CODE as [State Code] ,TSPL_State_MASTER.STATE_NAME as [State],TSPL_State_MASTER.COUNTRY_CODE as [Country Code] " & _
            " from TSPL_DISTRICT_MASTER " & _
            " left outer join TSPL_State_MASTER  on TSPL_State_MASTER.STATE_CODE=TSPL_DISTRICT_MASTER.State_Code " & _
            " left outer join TSPL_State_MASTER_detail on TSPL_State_MASTER.state_code=TSPL_State_MASTER_detail.state_code "

            txtDistrict.Value = clsCommon.ShowSelectForm("CityMasterDis", qry, "Code", "", txtDistrict.Value, "", isButtonClicked)
            lblDistrictName.Text = clsDistrictMaster.GetName(txtDistrict.Value)
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Sub

    Private Sub btnHistory_Click(sender As Object, e As EventArgs) Handles btnHistory.Click
        Try
            If clsCommon.myLen(fndcity.Value) <= 0 Then
                clsCommon.MyMessageBoxShow(Me, "Select City Code", Me.Text)
                Exit Sub
            End If
            clsERPFuncationalityOLD.ShowHistoryData(fndcity.Value, "City_Code", "TSPL_CITY_MASTER")
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Sub
End Class

