'Developed By -BibhuPrasad Parida
'Database - TSPLERP
'Table - TSPL_COMPANY_MASTER
'Start Date -
'End Date -
'---changs by Preeti gupta ,Ticket No.[BM00000003287]
'----changes by shivani tyagi ,,,,Ticket no.[BM00000003433](format of telephone)
''  updation by richa agarwal add I.E. Code BM00000005492,BHA/19/06/18-000058
'--------------BM00000003569--------------------------------------
'' work done by Parteek Against ticket no. TEC/07/01/19-000390
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports System.Data
Imports System.Data.SqlClient
Imports System.Windows.Forms
Imports System.Configuration
Imports Excel = Microsoft.Office.Interop.Excel
Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Drawing
Imports Telerik.WinControls.Data
Imports Telerik.Data
Imports Telerik.WinControls.Enumerations
Imports System.Text.RegularExpressions
Imports common
Imports System.IO


Public Class FrmCompanyMaster
    Inherits FrmMainTranScreen

    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim userCode, companyCode As String

    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub
#Region "Variables"
    Dim sql As String
    Dim ds As DataSet
    Dim dt As DataTable
    Dim isInsideLoadData As Boolean = False
    Dim strRemarks As String = Nothing
    Dim IsModifyOnPwd As Boolean = False
    Dim AllowGSTApplicable As Boolean = False

#End Region

#Region "Methods"
    ' 'insert into company master 
    Private Sub funInsert()

        Dim abc As String = ddlModeofTransp.Text
        Dim check As Match = Regex.Match(txtEmail.Text, "\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*")
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(fndCompanyCode.Value) <= 0 Then
            myMessages.blankValue(Me, "Company Code", Me.Text)
            fndCompanyCode.Focus()
            Return
        ElseIf txtCompanyName.Text = "" Then
            ' common.clsCommon.MyMessageBoxShow("Company Name cannot be blank.")
            myMessages.blankValue(Me, "Company Name", Me.Text)
            txtCompanyName.Focus()
        ElseIf check.Success = False And txtEmail.Text <> "" Then
            common.clsCommon.MyMessageBoxShow(Me, "Please insert the proper format of e-mail address", Me.Text)
            txtEmail.Text = ""
            txtEmail.Focus()
            '' Anubhooti 01-Sep-2014 BM00000003428 (Add CIN No.)
        ElseIf clsCommon.myLen(txtCIN.Text) = 0 Then
            myMessages.blankValue(Me, "CIN No.", Me.Text)
            txtCIN.Text = ""
            txtCIN.Focus()
        Else
            Dim strCform As String
            If chkCformRequiredTN.Checked = True Then
                strCform = "Y"
            Else
                strCform = "N"
            End If
            Try
                Dim com As String = ""
                If txtCECommissionerate.Text = "" Then
                    com = "0"
                Else
                    com = clsCommon.myCdbl(txtCECommissionerate.Text)
                End If
                Dim strmodeoftrans As String
                If ddlModeofTransp.Text = "      -----Select-----" Then

                    strmodeoftrans = ""
                Else
                    strmodeoftrans = ddlModeofTransp.Text
                End If
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_COMPANY_MASTER where Comp_Code='" & fndCompanyCode.Value & "'")
                    If ChkNewEntry = 0 Then
                        fndCompanyCode.Value = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.CompanyMaster, "", "")
                        If clsCommon.myLen(fndCompanyCode.Value) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsDBFuncationality.UpdateInAllDatabase("sp_TSPL_COMPANY_MASTER_insert", clsCommon.myCstr(cboDataBase.SelectedValue), New SqlParameter("@CompCode", fndCompanyCode.Value), New SqlParameter("@CompName", txtCompanyName.Text), New SqlParameter("@Add1", txtAdd1.Text), New SqlParameter("@Add2", txtAdd2.Text), New SqlParameter("@Add3", txtAdd3.Text), New SqlParameter("@CityCode", txtCity.Text), New SqlParameter("@Phone1", txtTelephone1.Text), New SqlParameter("@Phone2", txtTelephone2.Text), New SqlParameter("@Fax", txtFax.Text), New SqlParameter("@Email", txtEmail.Text), New SqlParameter("@PinCode", txtPinCode.Text), New SqlParameter("@State", txtState.Value), New SqlParameter("@TinNo", txtTinNo.Text), New SqlParameter("@CstLst", txtCstLst.Text), New SqlParameter("@RegdNo", txtRegdNo.Text), New SqlParameter("@CForm", strCform), New SqlParameter("@ModeofTransport", strmodeoftrans), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate()), New SqlParameter("@ModifiedBy", userCode), New SqlParameter("@ModifiedDate", connectSql.serverDate()), New SqlParameter("@CompCode1", companyCode), New SqlParameter("@DBName", clsCommon.myCstr(cboDataBase.SelectedValue)), New SqlParameter("@VatRegNo", txtVatRegNo.Text), New SqlParameter("@ServiceTaxReg", txtServiceTaxRegNo.Text), New SqlParameter("@EccNo", txtEccNo.Text), New SqlParameter("@CERange", txtCERange.Text), New SqlParameter("@CECommissionerate", com), New SqlParameter("@CEDivision", txtCEDivision.Text), New SqlParameter("@PanNo", txtPanNo.Text), New SqlParameter("@TanNo", txtTanNo.Text), New SqlParameter("@TCanNo", txtTcanNo.Text), New SqlParameter("@CircleNo", txtCircleNo.Text), New SqlParameter("@WardNo", txtWardNo.Text), New SqlParameter("@AccessOfficer", txtAccessOfficer.Text))
                ' , New SqlParameter("@PFNo", txtPFNO.Text), New SqlParameter("@ESICNo", txtESICNO.Text)

                ''======================for insurance======================
                Dim xcheckInsurance As String = ""
                If clsCommon.myLen(txtInsurance_Comp_Name.Text) > 0 Then
                    xcheckInsurance = ",Insurance_No='" & txtinsuranceno.Text & "',Insurance_Comp_Name='" & txtInsurance_Comp_Name.Text & "',Insurance_Valid_Date='" & clsCommon.GetPrintDate(dtpInsurance_Valid_Date.Text, "dd/MMM/yyyy") & "' "
                Else
                    xcheckInsurance = ",Insurance_No=NULL,Insurance_Comp_Name=NULL,Insurance_Valid_Date=NULL "
                End If
                ''=============================================

                clsDBFuncationality.ExecuteNonQuery(" UPDATE TSPL_COMPANY_MASTER SET Comp_ESIC_NO = '" & txtESICNO.Text & "' ,Comp_PF_NO ='" & txtPFNO.Text & "',Employer_Name='" & TxtEmployerName.Text & "',Employer_Desg='" & TxtEmployerDesg.Text & "',Employer_Add1='" & TxtEmployerAdd1.Text & "',Employer_Add2='" & TxtEmployerAdd2.Text & "',Employer_Add3='" & TxtEmployerAdd3.Text & "' " + xcheckInsurance + ",Bank_Name='" & txtBankName.Text & "',BankAccountNo='" & TxtBankAccountNo.Text & "',BankIFSCCode='" & txtifsccode.Text & "',BankBranchAddress='" & txtbranchAddress.Text & "' WHERE Comp_Code ='" + fndCompanyCode.Value + "'")
                '===SANJEET(24/11/2016)=TinNo Issue date and PanNo Issue Date=========
                clsDBFuncationality.ExecuteNonQuery(" UPDATE TSPL_COMPANY_MASTER SET TinNo_Issue_Date = '" & clsCommon.GetPrintDate(dtTinIssueDate.Text, "dd/MMM/yyyy") & "' ,PanNo_Issue_Date ='" & clsCommon.GetPrintDate(dtPanIssueDate.Text, "dd/MMM/yyyy") & "',comp_code1='" & txtcomp_code1.Text & "' WHERE Comp_Code ='" + fndCompanyCode.Value + "'")
                UpdateCompanyMaster()

                ''----GST Function
                If AllowGSTApplicable = True Then
                    clsDBFuncationality.ExecuteNonQuery(" UPDATE TSPL_COMPANY_MASTER SET GSTReg_No = '" & clsCommon.myCstr(TxtGstReg.Text) & "' ,GSTINNo ='" & clsCommon.myCstr(TxtGstInNo.Text) & "' WHERE Comp_Code ='" + fndCompanyCode.Value + "'")
                End If

                SaveImage()
                SaveBackGroundImage()
                myMessages.insert()

                btnSave.Text = "Update"
                btnDelete.Enabled = True
            Catch ex As Exception
                If ex.Message.ToUpper.Contains("DUPLICATE") Then
                    clsCommon.MyMessageBoxShow(Me, "Record Already Exits..", Me.Text)
                Else
                    myMessages.myExceptions(ex)
                End If

            End Try
        End If

    End Sub
    Sub UpdateCompanyMaster()
        If clsCommon.myLen(fndBaseCurrency.Value) > 0 Then
            clsDBFuncationality.ExecuteNonQuery(" update TSPL_COMPANY_MASTER set BaseCurrencyCode = '" + clsCommon.myCstr(fndBaseCurrency.Value) + "' ,ApplyMultiCurrency =" & IIf(chkApplyMultiCurrency.Checked = True, 1, 0) & " where Comp_Code ='" + fndCompanyCode.Value + "'")

        Else
            clsDBFuncationality.ExecuteNonQuery(" update TSPL_COMPANY_MASTER set ApplyMultiCurrency =" & IIf(chkApplyMultiCurrency.Checked = True, 1, 0) & " where Comp_Code ='" + fndCompanyCode.Value + "'")
        End If

        Dim main_comp As String = "0"
        If chk_main_company.Checked Then
            main_comp = "1"
        End If
        '' Anubhooti 01-Sep-2014 (BM00000003428 Update CINNo also in query)
        clsDBFuncationality.ExecuteNonQuery(" update TSPL_COMPANY_MASTER set CINNo='" + clsCommon.myCstr(txtCIN.Text) + "' ,DataBase_Name = '" + clsCommon.myCstr(cboDataBase.SelectedValue) + "',cust_code='" + clsCommon.myCstr(txtcust_code.Value) + "',Is_Main_Company='" + main_comp + "',IECode='" & clsCommon.myCstr(TxtIECode.Text) & "' where Comp_Code ='" + fndCompanyCode.Value + "'")

    End Sub

    '  'update company master
    Private Sub funUpdate()
        Dim check As Match = Regex.Match(txtEmail.Text, "\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*")
        If fndCompanyCode.Value = "" Then
            ' common.clsCommon.MyMessageBoxShow("Company Code cannot be blank.")
            myMessages.blankValue(Me, "Company Code", Me.Text)
        ElseIf txtCompanyName.Text = "" Then
            'common.clsCommon.MyMessageBoxShow("Company Name cannot be blank.")
            myMessages.blankValue(Me, "Company Name", Me.Text)
        ElseIf check.Success = False And txtEmail.Text <> "" Then
            common.clsCommon.MyMessageBoxShow(Me, "Please insert the proper format of e-mail address", Me.Text)
            txtEmail.Text = ""
            txtEmail.Focus()
            '' Anubhooti 01-Sep-2014 (Add CIN No.)
        ElseIf clsCommon.myLen(txtCIN.Text) = 0 Then
            myMessages.blankValue(Me, "CIN No.", Me.Text)
            txtCIN.Text = ""
            txtCIN.Focus()
        Else
            Dim strCform As String
            If chkCformRequiredTN.Checked = True Then
                strCform = "Y"
            Else
                strCform = "N"
            End If
            Try
                Dim com As String = ""
                If txtCECommissionerate.Text = "" Then
                    com = "0"
                Else
                    com = txtCECommissionerate.Text
                End If
                Dim strmodeoftrans As String
                If ddlModeofTransp.Text = "      -----Select-----" Then

                    strmodeoftrans = ""
                Else
                    strmodeoftrans = ddlModeofTransp.Text
                End If

                'connectSql.RunSp("sp_TSPL_COMPANY_MASTER_update", New SqlParameter("@CompCode", fndCompanyCode.txtValue.Text), New SqlParameter("@CompName", txtCompanyName.Text), New SqlParameter("@Add1", txtAdd1.Text), New SqlParameter("@Add2", txtAdd2.Text), New SqlParameter("@Add3", txtAdd3.Text), New SqlParameter("@CityCode", txtCity.Text), New SqlParameter("@Phone1", txtTelephone1.Text), New SqlParameter("@Phone2", txtTelephone2.Text), New SqlParameter("@Fax", txtFax.Text), New SqlParameter("@Email", txtEmail.Text), New SqlParameter("@PinCode", txtPinCode.Text), New SqlParameter("@State", txtState.Value), New SqlParameter("@TinNo", txtTinNo.Text), New SqlParameter("@CstLst", txtCstLst.Text), New SqlParameter("@RegdNo", txtRegdNo.Text), New SqlParameter("@CForm", strCform), New SqlParameter("@ModeofTransport", strmodeoftrans), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate()), New SqlParameter("@ModifiedBy", userCode), New SqlParameter("@ModifiedDate", connectSql.serverDate()), New SqlParameter("@CompCode1", companyCode), New SqlParameter("@DBName", clsCommon.myCstr(cboDataBase.SelectedValue)), New SqlParameter("@VatRegNo", txtVatRegNo.Text), New SqlParameter("@ServiceTaxReg", txtServiceTaxRegNo.Text), New SqlParameter("@EccNo", txtEccNo.Text), New SqlParameter("@CERange", txtCERange.Text), New SqlParameter("@CECommissionerate", txtCECommissionerate.Text), New SqlParameter("@CEDivision", txtCEDivision.Text), New SqlParameter("@PanNo", txtPanNo.Text), New SqlParameter("@TanNo", txtTanNo.Text), New SqlParameter("@TCanNo", txtTcanNo.Text), New SqlParameter("@CircleNo", txtCircleNo.Text), New SqlParameter("@WardNo", txtWardNo.Text), New SqlParameter("@AccessOfficer", txtAccessOfficer.Text))
                clsDBFuncationality.UpdateInAllDatabase("sp_TSPL_COMPANY_MASTER_update", New SqlParameter("@CompCode", fndCompanyCode.Value), New SqlParameter("@CompName", txtCompanyName.Text), New SqlParameter("@Add1", txtAdd1.Text), New SqlParameter("@Add2", txtAdd2.Text), New SqlParameter("@Add3", txtAdd3.Text), New SqlParameter("@CityCode", txtCity.Text), New SqlParameter("@Phone1", txtTelephone1.Text), New SqlParameter("@Phone2", txtTelephone2.Text), New SqlParameter("@Fax", txtFax.Text), New SqlParameter("@Email", txtEmail.Text), New SqlParameter("@PinCode", txtPinCode.Text), New SqlParameter("@State", txtState.Value), New SqlParameter("@TinNo", txtTinNo.Text), New SqlParameter("@CstLst", txtCstLst.Text), New SqlParameter("@RegdNo", txtRegdNo.Text), New SqlParameter("@CForm", strCform), New SqlParameter("@ModeofTransport", strmodeoftrans), New SqlParameter("@CreatedBy", userCode), New SqlParameter("@CreatedDate", connectSql.serverDate()), New SqlParameter("@ModifiedBy", userCode), New SqlParameter("@ModifiedDate", connectSql.serverDate()), New SqlParameter("@CompCode1", companyCode), New SqlParameter("@DBName", clsCommon.myCstr(cboDataBase.SelectedValue)), New SqlParameter("@VatRegNo", txtVatRegNo.Text), New SqlParameter("@ServiceTaxReg", txtServiceTaxRegNo.Text), New SqlParameter("@EccNo", txtEccNo.Text), New SqlParameter("@CERange", txtCERange.Text), New SqlParameter("@CECommissionerate", com), New SqlParameter("@CEDivision", txtCEDivision.Text), New SqlParameter("@PanNo", txtPanNo.Text), New SqlParameter("@TanNo", txtTanNo.Text), New SqlParameter("@TCanNo", txtTcanNo.Text), New SqlParameter("@CircleNo", txtCircleNo.Text), New SqlParameter("@WardNo", txtWardNo.Text), New SqlParameter("@AccessOfficer", txtAccessOfficer.Text))
                'If chkIntegrateWithTally.Checked Then
                '    clsDBFuncationality.ExecuteNonQuery(" update TSPL_COMPANY_MASTER set NameInTally = '" + txtCompanyNameTally.Text + "' ,IntegrateWithTally =1 where Comp_Code ='" + fndCompanyCode.Value + "'")
                'Else
                '    clsDBFuncationality.ExecuteNonQuery(" update TSPL_COMPANY_MASTER set NameInTally = '' ,IntegrateWithTally =0 where Comp_Code ='" + fndCompanyCode.Value + "'")
                'End If , New SqlParameter("@PFNo", txtPFNO.Text), New SqlParameter("@ESICNo", txtESICNO.Text)

                ''======================for insurance======================
                Dim xcheckInsurance As String = ""
                If clsCommon.myLen(txtInsurance_Comp_Name.Text) > 0 Then
                    xcheckInsurance = ",Insurance_No='" & txtinsuranceno.Text & "',Insurance_Comp_Name='" & txtInsurance_Comp_Name.Text & "',Insurance_Valid_Date='" & clsCommon.GetPrintDate(dtpInsurance_Valid_Date.Text, "dd/MMM/yyyy") & "' "
                Else
                    xcheckInsurance = ",Insurance_No=NULL,Insurance_Comp_Name=NULL,Insurance_Valid_Date=NULL "
                End If
                ''=============================================

                clsDBFuncationality.ExecuteNonQuery(" UPDATE TSPL_COMPANY_MASTER SET Comp_ESIC_NO = '" & txtESICNO.Text & "' ,Comp_PF_NO ='" & txtPFNO.Text & "',Employer_Name='" & TxtEmployerName.Text & "',Employer_Desg='" & TxtEmployerDesg.Text & "',Employer_Add1='" & TxtEmployerAdd1.Text & "',Employer_Add2='" & TxtEmployerAdd2.Text & "',Employer_Add3='" & TxtEmployerAdd3.Text & "' " + xcheckInsurance + ",Bank_Name='" & txtBankName.Text & "',BankAccountNo='" & TxtBankAccountNo.Text & "',BankIFSCCode='" & txtifsccode.Text & "',BankBranchAddress='" & txtbranchAddress.Text & "'  WHERE Comp_Code ='" + fndCompanyCode.Value + "'")

                '===SANJEET(24/11/2016)=TinNo Issue date and PanNo Issue Date=========
                clsDBFuncationality.ExecuteNonQuery(" UPDATE TSPL_COMPANY_MASTER SET TinNo_Issue_Date = '" & clsCommon.GetPrintDate(dtTinIssueDate.Text, "dd/MMM/yyyy") & "' ,PanNo_Issue_Date ='" & clsCommon.GetPrintDate(dtPanIssueDate.Text, "dd/MMM/yyyy") & "',comp_code1='" & txtcomp_code1.Text & "' WHERE Comp_Code ='" + fndCompanyCode.Value + "'")

                ''=-----GST Function
                If AllowGSTApplicable = True Then
                    clsDBFuncationality.ExecuteNonQuery(" UPDATE TSPL_COMPANY_MASTER SET GSTReg_No = '" & clsCommon.myCstr(TxtGstReg.Text) & "' ,GSTINNo ='" & clsCommon.myCstr(TxtGstInNo.Text) & "' WHERE Comp_Code ='" + fndCompanyCode.Value + "'")
                End If
                ''--====End
                UpdateCompanyMaster()
                SaveImage()
                SaveBackGroundImage()
                myMessages.update()

            Catch ex As Exception
                myMessages.myExceptions(ex)
            End Try
        End If

    End Sub
    ''fill company details
    Private Sub funFill()
        cboDataBase.SelectedIndex = 0
        dt = clsDBFuncationality.GetDataTable("select  Comp_Name,Add1,Add2,Add3,City_Code ,Phone1 ,Phone2 ,Fax,Email ,Pincode ,State ,Tin_No ,CST_LST ,Regn_No ,Cform ,Mode_of_Trans ,DataBase_Name ,Logo_Img ,Logo_Img2 ,Vat_Reg_No ,ServiceTax_Reg_No ,Ecc_No ,CE_Range ,CE_Commissionerate,CE_Division ,Pan_No ,Tan_No ,Tcan_No ,Circle_No ,Ward_No ,Access_Officer,NameInTally,IntegrateWithTally,BaseCurrencyCode,ApplyMultiCurrency,cust_code,Is_Main_Company,CINNo,IECode ,Comp_PF_NO,Comp_ESIC_NO,ISNULL(Employer_Name,'') AS Employer_Name,ISNULL(Employer_Desg,'') AS Employer_Desg,ISNULL(Employer_Add1,'') AS Employer_Add1,ISNULL(Employer_Add2,'') AS Employer_Add2,ISNULL(Employer_Add3,'') AS Employer_Add3,Insurance_No,insurance_comp_name,insurance_valid_date,TinNo_Issue_Date,PanNo_Issue_Date,GSTINNo,GSTReg_No,Bank_Name,BankAccountNo,BankIFSCCode,BankBranchAddress,comp_code1 from TSPL_COMPANY_MASTER  where Comp_Code='" + fndCompanyCode.Value + "'")
        'While dr.Read()
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then

            isInsideLoadData = True
            For Each dr As DataRow In dt.Rows
                txtCompanyName.Text = dr(0).ToString()
                txtAdd1.Text = dr(1).ToString()
                txtAdd2.Text = dr(2).ToString()
                txtAdd3.Text = dr(3).ToString()
                txtCity.Text = dr(4).ToString()
                txtTelephone1.Text = dr(5).ToString()
                txtTelephone2.Text = dr(6).ToString()
                txtFax.Text = dr(7).ToString()
                txtEmail.Text = dr(8).ToString()
                txtPinCode.Text = dr(9).ToString()
                txtState.Value = dr(10).ToString()
                txtTinNo.Text = dr(11).ToString()
                txtCstLst.Text = dr(12).ToString()
                txtRegdNo.Text = dr(13).ToString()
                Dim strchk As String = dr(14).ToString()
                If strchk = "Y" Then
                    chkCformRequiredTN.Checked = True
                Else
                    chkCformRequiredTN.Checked = False
                End If
                ddlModeofTransp.Text = dr(15).ToString()

                txtVatRegNo.Text = dr(19).ToString()
                txtServiceTaxRegNo.Text = dr(20).ToString()
                txtEccNo.Text = dr(21).ToString()
                txtCERange.Text = dr(22).ToString()
                txtCECommissionerate.Text = dr(23).ToString()
                txtCEDivision.Text = dr(24).ToString()
                txtPanNo.Text = dr(25).ToString()
                txtTanNo.Text = dr(26).ToString()
                txtTcanNo.Text = dr(27).ToString()
                txtCircleNo.Text = dr(28).ToString()
                txtWardNo.Text = dr(29).ToString()
                txtAccessOfficer.Text = dr(30).ToString()
                cboDataBase.SelectedValue = clsCommon.myCstr(dr("DataBase_Name"))
                If dr(15).ToString() <> "" Then
                    ddlModeofTransp.Text = dr(15).ToString()
                Else
                    ddlModeofTransp.Text = "      -----Select-----"
                End If
                Me.fndBaseCurrency.Value = clsCommon.myCstr(dr("BaseCurrencyCode"))
                Me.chkApplyMultiCurrency.Checked = clsCommon.myCstr(dr("ApplyMultiCurrency"))
                fndBaseCurrency.Enabled = False
                'If clsCommon.myCBool(dr("IntegrateWithTally")) Then
                '    chkIntegrateWithTally.Checked = clsCommon.myCBool(dr("IntegrateWithTally"))
                '    txtCompanyNameTally.Text = clsCommon.myCstr(dr("NameInTally"))
                'Else
                '    chkIntegrateWithTally.Checked = False
                '    txtCompanyNameTally.Text = ""
                'End If

                txtInsurance_Comp_Name.Text = clsCommon.myCstr(dr("insurance_comp_name"))
                txtinsuranceno.Text = clsCommon.myCstr(dr("Insurance_No"))
                dtpInsurance_Valid_Date.Checked = False
                If clsCommon.myLen(txtInsurance_Comp_Name.Text) > 0 AndAlso dr("insurance_valid_date") IsNot Nothing AndAlso clsCommon.myLen(dr("insurance_valid_date")) > 0 Then
                    dtpInsurance_Valid_Date.Checked = True
                    dtpInsurance_Valid_Date.Text = clsCommon.myCDate(dr("insurance_valid_date"))
                End If

                chk_main_company.Checked = False
                If clsCommon.CompairString(clsCommon.myCstr(dr("Is_Main_Company")), "1") = CompairStringResult.Equal Then
                    chk_main_company.Checked = True
                End If

                txtcust_code.Value = clsCommon.myCstr(dr("cust_code"))
                txtcust_name.Text = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select customer_name from tspl_customer_master where cust_code='" + txtcust_code.Value + "'"))
                '' Anubhooti 01-Sep-2014 
                txtCIN.Text = clsCommon.myCstr(dr("CINNo"))
                TxtIECode.Text = clsCommon.myCstr(dr("IECode"))
                txtESICNO.Text = clsCommon.myCstr(dr("Comp_ESIC_NO"))
                txtPFNO.Text = clsCommon.myCstr(dr("Comp_PF_NO"))

                TxtEmployerName.Text = clsCommon.myCstr(dr("Employer_Name"))
                TxtEmployerDesg.Text = clsCommon.myCstr(dr("Employer_Desg"))
                TxtEmployerAdd1.Text = clsCommon.myCstr(dr("Employer_Add1"))
                TxtEmployerAdd2.Text = clsCommon.myCstr(dr("Employer_Add2"))
                TxtEmployerAdd3.Text = clsCommon.myCstr(dr("Employer_Add3"))

                btnSave.Text = "Update"
                btnDelete.Enabled = True

                'KUNAL > DATE : 4-JAN-2016 > CLIENT : KDIL > BUG ORIGINATOR : SANJEET > TICKETS : ASSIGNED BY PANCHRAJ SIR ON VERBAL DISCUSSION
                If dr("TinNo_Issue_Date") IsNot Nothing AndAlso clsCommon.myLen(dr("TinNo_Issue_Date")) > 0 Then
                    dtTinIssueDate.Text = clsCommon.myCDate(dr("TinNo_Issue_Date"))
                End If
                'KUNAL > DATE : 4-JAN-2016 > CLIENT : KDIL > BUG ORIGINATOR : SANJEET > TICKETS : ASSIGNED BY PANCHRAJ SIR ON VERBAL DISCUSSION
                If dr("PanNo_Issue_Date") IsNot Nothing AndAlso clsCommon.myLen(dr("PanNo_Issue_Date")) > 0 Then
                    dtPanIssueDate.Text = clsCommon.myCDate(dr("PanNo_Issue_Date"))
                End If

                TxtGstInNo.Text = clsCommon.myCstr(dr("GSTINNo"))
                TxtGstReg.Text = clsCommon.myCstr(dr("GSTReg_No"))

                txtBankName.Text = clsCommon.myCstr(dr("Bank_Name"))
                TxtBankAccountNo.Text = clsCommon.myCstr(dr("BankAccountNo"))
                txtifsccode.Text = clsCommon.myCstr(dr("BankIFSCCode"))
                txtbranchAddress.Text = clsCommon.myCstr(dr("BankBranchAddress"))
                txtcomp_code1.Text = clsCommon.myCstr(dr("comp_code1"))
                'If userCode <> "ADMIN" Then
                '    If funSetUserAccess() = False Then Exit Sub
                'End If
                ' End While
            Next
        End If
        isInsideLoadData = False
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If

    End Sub
    ''delete company master
    Private Sub funDelete()
        Try
            'connectSql.RunSp("sp_TSPL_COMPANY_MASTER_delete", New SqlParameter("@CompCode", fndCompanyCode.txtValue.Text))
            clsDBFuncationality.UpdateInAllDatabase("sp_TSPL_COMPANY_MASTER_delete", New SqlParameter("@CompCode", fndCompanyCode.Value))
            myMessages.delete()
            btnSave.Text = "Save"
            btnDelete.Enabled = False

        Catch ex As Exception
            myMessages.myExceptions(ex)

        End Try
    End Sub
    '' Reset company master details
    Private Sub funReset()
        fndCompanyCode.Value = ""
        fndCompanyCode.MyReadOnly = False
        fndCompanyCode.Focus()
        txtCompanyName.Text = ""
        txtAdd1.Text = ""
        txtAdd2.Text = ""
        txtAdd3.Text = ""
        txtCity.Text = ""
        txtEmail.Text = ""
        txtFax.Text = ""
        txtTelephone1.Text = "(+__)__________"
        txtTelephone2.Text = "(+__)__________"
        fndBaseCurrency.Enabled = True
        ddlModeofTransp.Text = "      -----Select-----"
        txtPinCode.Text = ""
        txtState.Value = Nothing
        txtTinNo.Text = ""
        txtCstLst.Text = ""
        txtRegdNo.Text = ""
        txtVatRegNo.Text = ""
        txtPanNo.Text = ""
        txtServiceTaxRegNo.Text = ""
        txtTanNo.Text = ""
        txtAccessOfficer.Text = ""
        txtTcanNo.Text = ""
        txtCircleNo.Text = ""
        txtCERange.Text = ""
        txtCECommissionerate.Text = "0"
        txtWardNo.Text = ""
        txtCEDivision.Text = ""
        txtEccNo.Text = ""
        txtCIN.Text = ""
        TxtIECode.Text = ""
        'chkIntegrateWithTally.Checked = False
        'txtCompanyNameTally.Text = ""
        Me.fndBaseCurrency.Value = Nothing
        Me.chkApplyMultiCurrency.Checked = False

        txtinsuranceno.Text = ""
        txtInsurance_Comp_Name.Text = ""
        dtpInsurance_Valid_Date.Checked = False
        dtpInsurance_Valid_Date.Text = clsCommon.GETSERVERDATE()

        txtcust_code.Value = ""
        txtcust_name.Text = ""
        chk_main_company.Checked = False
        txtESICNO.Text = ""
        txtPFNO.Text = ""
        TxtEmployerName.Text = ""
        TxtEmployerDesg.Text = ""
        TxtEmployerAdd1.Text = ""
        TxtEmployerAdd2.Text = ""
        TxtEmployerAdd3.Text = ""
        chkCformRequiredTN.Checked = False
        cboDataBase.SelectedIndex = 0
        btnSave.Enabled = True
        btnSave.Text = "Save"
        btnDelete.Enabled = False
        dtTinIssueDate.Text = clsCommon.GETSERVERDATE()
        dtPanIssueDate.Text = clsCommon.GETSERVERDATE()
        TxtGstInNo.Text = ""
        TxtGstReg.Text = ""
        txtBankName.Text = ""
        TxtBankAccountNo.Text = ""
        txtifsccode.Text = ""
        txtbranchAddress.Text = ""
        txtcomp_code1.Text = ""
    End Sub
    'priti added on 01-06-2011 --- To implement the access control
    'Private Function funSetUserAccess() As Boolean
    '    Try
    '        'If funCheckLoginStatus() = False Then Exit Function
    '        Dim strRights As String
    '        Dim strTemp() As String
    '        Dim strProgCode = "COMPANY-M"
    '        strRights = enuUserRights.enuRead & "," & enuUserRights.enuModify & "," & enuUserRights.enuDelete
    '        strRights = modUserMgt.funGetPermissions(strRights, strProgCode)
    '        strTemp = Split(strRights, ",")
    '        If strTemp(0) = "0" Then
    '            MsgBox("Permission Denied", MsgBoxStyle.Critical, Me.Text)
    '            funSetUserAccess = False
    '            blnRead = False
    '            Me.Close()
    '            Exit Function
    '        Else
    '            blnRead = True
    '        End If
    '        If strTemp(1) = "0" Then 'Grant modify access
    '            btnSave.Enabled = False
    '        End If
    '        If strTemp(2) = "0" Then 'Grant modify access
    '            btnDelete.Enabled = False
    '        End If

    '        funSetUserAccess = True
    '    Catch er As Exception

    '    End Try
    'End Function
    'Code ends here
#End Region

#Region "keyPress Event"
    'Private Sub txtCity_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCity.KeyPress
    '    If IsNumeric(e.KeyChar) = True Then
    '        e.Handled = False
    '    ElseIf Microsoft.VisualBasic.Asc(e.KeyChar) = 8 Then
    '    Else
    '        e.Handled = True
    '    End If
    'End Sub
    Private Sub fndCompanyCode_keypress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)

        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If

    End Sub
#End Region

#Region "Page Load"
    Public Sub SetLength()
        fndCompanyCode.MyMaxLength = 8
        txtCompanyName.MaxLength = 100
        txtAdd1.MaxLength = 50
        txtAdd2.MaxLength = 50
        txtAdd3.MaxLength = 50
        txtCity.MaxLength = 50
        txtFax.MaxLength = 12
        txtEmail.MaxLength = 50
        txtPinCode.MaxLength = 20
        'txtState.MaxLength = 30
        txtTinNo.MaxLength = 20
        txtCstLst.MaxLength = 30
        txtRegdNo.MaxLength = 30
        txtVatRegNo.MaxLength = 30
        txtServiceTaxRegNo.MaxLength = 30
        txtEccNo.MaxLength = 30
        txtCERange.MaxLength = 30
        txtCEDivision.MaxLength = 30
        txtPanNo.MaxLength = 30
        txtTanNo.MaxLength = 30
        txtTcanNo.MaxLength = 30
        txtCircleNo.MaxLength = 30
        txtWardNo.MaxLength = 30
        txtAccessOfficer.MaxLength = 30
        TxtIECode.MaxLength = 30
        txtESICNO.MaxLength = 30
        txtPFNO.MaxLength = 30
        TxtEmployerName.Text = 50
        TxtEmployerDesg.Text = 50
        TxtEmployerAdd1.Text = 50
        TxtEmployerAdd2.Text = 50
        TxtEmployerAdd3.Text = 50
    End Sub
    Private Sub FrmCompanyMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetLength()
        SetUserMgmtNew()
        funReset()
        RadPageView1.SelectedPage = RadPageViewPage1
        LoadDataBase()
        ' globalFunc.mandatoryText(fndCompanyCode.Value, txtCompanyName)
        globalFunc.mandatoryDropdown(cboDataBase)

        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New Trasnaction")
        AddHandler fndCompanyCode.KeyPress, AddressOf fndCompanyCode_keypress
        AddHandler fndCompanyCode.TextChanged, AddressOf fndCompanyCode_textchanged
        'fndCompanyCode.txtValue.CharacterCasing = CharacterCasing.Upper
        fndCompanyCode.Focus()
        'fndCompanyCode.txtValue.MaxLength = 12
        btnDelete.Enabled = False
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
        ''=====Sanjeet(24/11/2016)(change Accessing Office Lable text as FSSAI LIC NO And TCAN NO AS Website)===========
        dtTinIssueDate.Text = clsCommon.GETSERVERDATE()
        dtPanIssueDate.Text = clsCommon.GETSERVERDATE()
        '===========================
        AllowGSTApplicable = IIf(clsCommon.myCdbl(clsFixedParameter.GetData(clsFixedParameterType.GSTApplicable, clsFixedParameterCode.GSTApplicable, Nothing)) = 1, True, False)
        If AllowGSTApplicable = True Then
            RadPageViewPage5.Enabled = True
        End If
    End Sub
#End Region
    'Private Function funSetUserAccess() As Boolean
    '    Try
    '        Dim strRights As String
    '        Dim strTemp() As String
    '        Dim strProgCode = "COMPANY-M"
    '        strRights = enuUserRights.enuRead & "," & enuUserRights.enuModify & "," & enuUserRights.enuDelete & "," & enuUserRights.enuAuthorised
    '        strRights = modUserMgt.funGetPermissions(strRights, strProgCode)
    '        strTemp = Split(strRights, ",")
    '        If strTemp(0) = "0" Then
    '            MsgBox("Permission Denied", MsgBoxStyle.Critical, Me.Text)
    '            funSetUserAccess = False
    '            blnRead = False
    '            Me.Close()
    '            Exit Function
    '        Else
    '            blnRead = True
    '        End If
    '        If strTemp(1) = "0" Then 'Grant modify access
    '            btnSave.Enabled = False
    '        End If
    '        If strTemp(2) = "0" Then 'Grant modify access
    '            btnDelete.Enabled = False
    '        End If
    '        If strTemp(3) = "0" Then 'Grant Authorize access
    '            ' btnPost.Enabled = False
    '        End If
    '        funSetUserAccess = True
    '    Catch er As Exception
    '        common.clsCommon.MyMessageBoxShow(er.Message.ToString())
    '    End Try
    'End Function

    Sub LoadDataBase()
        Dim qry As String = "SELECT NAME as CODE,NAME FROM sys.databases order by name"
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        Dim dr As DataRow = dt.NewRow()
        dr("Code") = ""
        dr("Name") = "---Select---"
        dt.Rows.InsertAt(dr, 0)
        cboDataBase.DataSource = dt
        cboDataBase.ValueMember = "CODE"
        cboDataBase.DisplayMember = "Name"
    End Sub

#Region "TextChanged Event"

    Private Sub fndCompanyCode_textchanged(ByVal sender As System.Object, ByVal e As System.EventArgs)
        dt = clsDBFuncationality.GetDataTable("select   Comp_Code from TSPL_COMPANY_MASTER where Comp_Code='" + fndCompanyCode.Value + "'")
        Dim s As String = ""
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            For Each dr As DataRow In dt.Rows
                'While dr.Read()
                s = dr(0).ToString()
                ' End While
            Next
        End If
        ' dr.Close()
        If s <> fndCompanyCode.Value Then
            txtCompanyName.Text = ""
            txtAdd1.Text = ""
            txtAdd2.Text = ""
            txtAdd3.Text = ""
            txtCity.Text = ""
            txtEmail.Text = ""
            txtFax.Text = ""
            txtTelephone1.Text = ""
            txtTelephone2.Text = ""
            ddlModeofTransp.Text = "      -----Select-----"
            txtPinCode.Text = ""
            txtState.Value = Nothing
            txtTinNo.Text = ""
            txtCstLst.Text = ""
            txtRegdNo.Text = ""

            txtVatRegNo.Text = ""
            txtPanNo.Text = ""
            txtServiceTaxRegNo.Text = ""
            txtTanNo.Text = ""
            txtAccessOfficer.Text = ""
            txtTcanNo.Text = ""
            txtCircleNo.Text = ""
            txtCERange.Text = ""
            txtCECommissionerate.Text = "0"
            txtWardNo.Text = ""
            txtCEDivision.Text = ""
            txtEccNo.Text = ""
            txtCIN.Text = ""
            'chkIntegrateWithTally.Checked = False
            'txtCompanyNameTally.Text = ""

            chkCformRequiredTN.Checked = False
            cboDataBase.SelectedIndex = 0
            btnSave.Enabled = True
            btnSave.Text = "&Save"
        Else
            funFill()
        End If
        If fndCompanyCode.Value = "" Then
            funReset()
        End If
        LoadImage()
        LoadBackgroundImage()
    End Sub
#End Region

#Region "Export"
    ''export company details 
    'Anubhooti 02-Sep-2014 BM00000003428 (Fetch CINNo.)
    Private Sub menuExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles menuExport.Click
        sql = "select Comp_Code,Comp_Name,Add1,Add2,Add3,City_Code,Phone1,Phone2,Fax,Email,Pincode,State,Tin_No,Cst_Lst,Regn_No,Cform,Mode_of_Trans,CINNo,IECode,Insurance_Comp_name,Insurance_No,Insurance_Valid_Date from TSPL_COMPANY_MASTER"
        transportSql.ExporttoExcel(sql, Me)
    End Sub
#End Region

#Region "Finder Load"
    'Private Sub fndCompanyCode_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
    '    fndCompanyCode.ConnectionString = connectSql.SqlCon()
    '    fndCompanyCode.Query = "select Comp_Code as [Company Code],Comp_Name  as [Company Name] from TSPL_COMPANY_MASTER order by Comp_Code"
    '    fndCompanyCode.ValueToSelect = "Company Code"
    '    fndCompanyCode.ValueToSelect1 = "Company Name"
    '    fndCompanyCode.Caption = "Company Details"
    'End Sub
#End Region
    Private Sub SetUserMgmtNew()
        '' Anubhooti 31-July-2014 BM00000003131
        'MyBase.SetUserMgmt(clsUserMgtCode.FrmCompanyMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnSave.Visible = MyBase.isModifyFlag
        IsModifyOnPwd = MyBase.isModifyonPasswordFlag
        '--------richa Ticket no. BM00000003014 03/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            menuExport.Enabled = True
        Else
            menuExport.Enabled = False
        End If
        '--------------------------------------------------
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

#Region "Button Click Event"
    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Public Sub DeleteData()
        If (clsCommon.myLen(cboDataBase.SelectedValue) <= 0) Then
            common.clsCommon.MyMessageBoxShow(Me, "Please select Database Name", Me.Text)
            cboDataBase.Focus()
            Return
        End If
        If myMessages.deleteConfirm() Then
            funDelete()
        Else

        End If

    End Sub


    ''insert or update acording to button text
    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        SaveData()
    End Sub
    Public Sub SaveData()
        If (clsCommon.myLen(cboDataBase.SelectedValue) <= 0) Then
            common.clsCommon.MyMessageBoxShow(Me, "Please select Database Name", Me.Text)
            cboDataBase.Focus()
            Return
        End If

        ''==============================================================================
        If clsCommon.myLen(txtInsurance_Comp_Name.Text) > 0 AndAlso clsCommon.myLen(txtinsuranceno.Text) <= 0 Then
            txtinsuranceno.Focus()
            txtinsuranceno.Select()
            clsCommon.MyMessageBoxShow(Me, "Please fill Insurance No.", Me.Text)
            Return
        End If
        If clsCommon.myLen(txtInsurance_Comp_Name.Text) <= 0 AndAlso clsCommon.myLen(txtinsuranceno.Text) > 0 Then
            txtInsurance_Comp_Name.Focus()
            txtInsurance_Comp_Name.Select()
            clsCommon.MyMessageBoxShow(Me, "Please fill Insurance Company Name.", Me.Text)
            Return
        End If
        If clsCommon.myLen(txtInsurance_Comp_Name.Text) > 0 AndAlso dtpInsurance_Valid_Date.Checked = False Then
            dtpInsurance_Valid_Date.Focus()
            dtpInsurance_Valid_Date.Select()
            clsCommon.MyMessageBoxShow(Me, "Please select Insurance Valid Upto with valid date.", Me.Text)
            Return
        End If
        ''====================================================================

        '-----------------------same database can not assign to multiple companies---------
        Dim qry As String = "select count(*) from tspl_company_master where database_name='" + cboDataBase.SelectedValue + "' and comp_code<>'" + fndCompanyCode.Value + "'"
        Dim check As Integer = clsDBFuncationality.getSingleValue(qry)

        If check > 0 Then
            clsCommon.MyMessageBoxShow(Me, "Selected database is already mapped with other company." + Environment.NewLine + "Select the other database.")
            Return
        End If
        '--------------------------------------------------------------------------

        'SaveImage()

        If MyBase.isModifyonPasswordFlag Then
            If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.FrmCompanyMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
            Else
                Return
            End If
        End If
        If btnSave.Text = "Save" Then
            'Ticket No : TEC/13/08/19-000991 By Prabhakar
            Dim isCompanyExist As Boolean = clsCommon.myCBool(clsDBFuncationality.getSingleValue("select count (*) from TSPL_COMPANY_MASTER"))
            If isCompanyExist = True Then
                clsCommon.MyMessageBoxShow(Me, "One company already exist,You can not create another company.", Me.Text)
                Return
            End If
            funInsert()
        ElseIf btnSave.Text = "Update" Then
            funUpdate()
        End If
    End Sub
    'Private Sub FunSaveLogo()

    '    Try
    '        'First we need to make sure an image name was provided. If
    '        'none is provided we need to show a message to the user
    '        'and exit the function
    '        If IsNullOrEmpty(img) Then
    '            MessageBox.Show("Please provide an image to save.")
    '            Exit Sub
    '        End If

    '        'FileInfo instance so we can get all the
    '        'information we need regarding the image
    '        Dim fInfo As New FileInfo(imgName)
    '        'Get the length of the image for the byte array
    '        'we create later in the function       
    '        Dim len As Long = fInfo.Length

    '        'This is the connections tring connecting to your database
    '        '** NOTE: This needs to be changed to YOUR connection string **
    '        Dim connString As String = "YourConnectionString"
    '        'Open a FileStream the length of the image being inserted
    '        Using stream As New FileStream(img.Trim(), FileMode.Open)
    '            'Create a new byte array the size of the length of the file
    '            Dim imgData() As Byte = New Byte(Convert.ToInt32(len - 1)) {}

    '            'Read the byte array into the buffer
    '            stream.Read(imgData, 0, len)

    '            'Create our Sql connection
    '            Using con As New SqlConnection(connString)
    '                'Create the command object that will do
    '                'the database work
    '                Using cmd As New SqlCommand()
    '                    con.Open()
    '                    'Set the properties of ouor connection object
    '                    cmd.Connection = con
    '                    cmd.CommandType = CommandType.StoredProcedure
    '                    cmd.CommandText = storedProc
    '                    'Add the parameters for the stored procedure
    '                    cmd.Parameters.AddWithValue("@image_data", imgData)
    '                    cmd.Parameters.AddWithValue("@image_name", imgName)
    '                    'Execute the Stored Procedure
    '                    cmd.ExecuteNonQuery()
    '                    Return True
    '                End Using
    '            End Using
    '        End Using
    '    Catch ex As SqlException
    '        MessageBox.Show(ex.ToString)
    '        Return False
    '    Catch ex As Exception
    '        MessageBox.Show(ex.ToString)
    '        Return False
    '    End Try
    'End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub
    ''close company master form
    Private Sub menuClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles menuClose.Click
        Me.Close()
    End Sub
    ''close company master form
    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        closeform()
    End Sub
    Public Sub closeform()
        Me.Close()
    End Sub
#End Region

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs)
        ' Label1.Text = clsERPFuncationality.GetNextCode(Nothing, "Purchase Invoice", "Normal", "Delhi")
    End Sub
    Private Sub SaveBackGroundImage()
        Try
            Dim qry As String = ""
            If clsCommon.myLen(fndCompanyCode.Value) > 0 Then
                If BGImage.Image IsNot Nothing Then
                    Dim bm As New Bitmap(BGImage.Image)

                    Dim ms As New MemoryStream()
                    BGImage.Image.Save(ms, BGImage.Image.RawFormat)
                    If BGImage.Image.Width <= 1300 Then
                        clsCommon.MyMessageBoxShow(Me, "Image Width not match please increase width 1300 ", Me.Text)
                        Exit Sub
                    ElseIf BGImage.Image.Height <= "800" Then
                        clsCommon.MyMessageBoxShow(Me, "Image height not match please increase height 800 ", Me.Text)
                        Exit Sub
                    End If

                    Dim data As Byte() = ms.GetBuffer()
                    clsDBFuncationality.UpdateImage("BackgroundImage", data, "TSPL_COMPANY_MASTER", "Comp_Code='" + fndCompanyCode.Value + "'")
                    ''richa agarwal regarding memory leakage
                    ms.Close()
                    ms.Dispose()
                Else
                    clsDBFuncationality.ExecuteNonQuery("Update TSPL_COMPANY_MASTER set BackgroundImage=null where  Comp_Code='" + fndCompanyCode.Value + "'")
                End If
            End If

        Catch ex As Exception
            '  MsgBox(ex.Message.ToString())
        End Try
    End Sub
    Private Sub SaveImage()

        Try
            Dim qry As String = ""
            If clsCommon.myLen(fndCompanyCode.Value) > 0 Then
                If PictureBox1.Image IsNot Nothing Then
                    'Sanjay Ticket No-MIL/01/04/19-000058
                    'Dim bm As New Bitmap(PictureBox1.Image)

                    Dim ms As New MemoryStream()
                    'bm.Save(ms, System.Drawing.Imaging.ImageFormat.MemoryBmp)
                    PictureBox1.Image.Save(ms, PictureBox1.Image.RawFormat)
                    Dim data As Byte() = ms.GetBuffer()
                    clsDBFuncationality.UpdateImage("logo_Img", data, "TSPL_COMPANY_MASTER", "Comp_Code='" + fndCompanyCode.Value + "'")
                    ''richa agarwal regarding memory leakage
                    ms.Close()
                    ms.Dispose()


                Else
                    clsDBFuncationality.ExecuteNonQuery("Update TSPL_COMPANY_MASTER set logo_Img=null where  Comp_Code='" + fndCompanyCode.Value + "'")
                End If
                If PictureBox2.Image IsNot Nothing Then
                    Dim ms As New MemoryStream()
                    PictureBox2.Image.Save(ms, PictureBox2.Image.RawFormat)
                    Dim data As Byte() = ms.GetBuffer()
                    clsDBFuncationality.UpdateImage("logo_Img2", data, "TSPL_COMPANY_MASTER", "Comp_Code='" + fndCompanyCode.Value + "'")
                    ''richa agarwal regarding memory leakage
                    ms.Close()
                    ms.Dispose()
                Else
                    clsDBFuncationality.ExecuteNonQuery("Update TSPL_COMPANY_MASTER set logo_Img2=null where Comp_Code='" + fndCompanyCode.Value + "'")

                End If
              
            End If
        Catch ex As Exception
            '  MsgBox(ex.Message.ToString())
        End Try
    End Sub
    Private Sub LoadImage()
        Try
            PictureBox1.Image = Nothing
            PictureBox2.Image = Nothing
            Dim qry As String = "select logo_Img,logo_Img2 from TSPL_COMPANY_MASTER where Comp_Code='" + fndCompanyCode.Value + "'"
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
            If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                If (clsCommon.myLen(dt.Rows(0)("logo_Img")) > 0) Then
                    Dim data As Byte() = DirectCast(dt.Rows(0)("logo_Img"), Byte())
                    Dim ms As New MemoryStream(data)
                    PictureBox1.Image = Image.FromStream(ms)
                    ''PictureBox1.SizeMode = PictureBoxSizeMode.StretchImage

                    ''RICHA agarwal regarding memory leakage 
                    ms.Close()
                    ms.Dispose()

                End If
                If (clsCommon.myLen(dt.Rows(0)("logo_Img2")) > 0) Then
                    Dim data As Byte() = DirectCast(dt.Rows(0)("logo_Img2"), Byte())
                    Dim ms As New MemoryStream(data)
                    PictureBox2.Image = Image.FromStream(ms)
                    ''PictureBox2.SizeMode = PictureBoxSizeMode.StretchImage

                    ''RICHA agarwal regarding memory leakage 
                    ms.Close()
                    ms.Dispose()
                End If

            End If

        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub btnSelectPath_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSelectPath1.Click, btnSelectPath2.Click
        Try
            OpenFileDialog1.Filter = " image |*.gif;  *.jpg;  *.bmp;  *.png;"
            OpenFileDialog1.ShowDialog()
            If clsCommon.CompairString(clsCommon.myCstr(sender.Name), "btnSelectPath1") = CompairStringResult.Equal Then
                PictureBox1.Image = Image.FromFile(OpenFileDialog1.FileName)
            ElseIf clsCommon.CompairString(clsCommon.myCstr(sender.Name), "btnSelectPath2") = CompairStringResult.Equal Then
                PictureBox2.Image = Image.FromFile(OpenFileDialog1.FileName)
            End If
        Catch ex As Exception
        End Try
       
    End Sub

    Private Sub btnClearLogo1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClearLogo1.Click, btnClearLogo2.Click
        Try
            If clsCommon.CompairString(clsCommon.myCstr(sender.Name), "btnClearLogo1") = CompairStringResult.Equal Then
                PictureBox1.Image = Nothing
            ElseIf clsCommon.CompairString(clsCommon.myCstr(sender.Name), "btnClearLogo2") = CompairStringResult.Equal Then
                PictureBox2.Image = Nothing
            End If
        Catch ex As Exception

        End Try
       
    End Sub
    Private Sub btnBackgroundselect_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnBackgroundselect.Click
        Try
            OpenFileDialog1.Filter = " image |*.gif;  *.jpg;  *.bmp;  *.png;"
        OpenFileDialog1.ShowDialog()
            If clsCommon.CompairString(clsCommon.myCstr(sender.Name), "btnBackgroundselect") = CompairStringResult.Equal Then
                BGImage.Image = Image.FromFile(OpenFileDialog1.FileName)
            End If

        Catch ex As Exception

        End Try
    End Sub

    Private Sub btnBGClear_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnBGClear.Click
        If clsCommon.CompairString(clsCommon.myCstr(sender.Name), "btnBGClear") = CompairStringResult.Equal Then
            BGImage.Image = Nothing
        End If
    End Sub

    Private Sub LoadBackgroundImage()
        Try
            BGImage.Image = Nothing
            Dim qry As String = "select Backgroundimage from TSPL_COMPANY_MASTER where Comp_Code='" + fndCompanyCode.Value + "'"
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
            If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                If (clsCommon.myLen(dt.Rows(0)("Backgroundimage")) > 0) Then
                    Dim data As Byte() = DirectCast(dt.Rows(0)("Backgroundimage"), Byte())
                    Dim ms As New MemoryStream(data)
                    BGImage.Image = Image.FromStream(ms)
                    ms.Close()
                    ms.Dispose()

                End If
            End If

        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    'Private Sub txtCECommissionerate_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCECommissionerate.KeyPress
    '    If ((e.KeyChar >= Chr(48) And e.KeyChar <= Chr(57)) Or e.KeyChar = Chr(8) Or e.KeyChar = Chr(48) Or e.KeyChar = Chr(45)) Then
    '    Else
    '        e.Handled = True
    '    End If
    'End Sub

    Private Sub FrmCompanyMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            closeform()

        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub fndCompanyCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndCompanyCode._MYValidating
        Dim qst As String = "select count(*) from TSPL_COMPANY_MASTER where Comp_Code='" + fndCompanyCode.Value + "'"
        Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qst))
        If count = 0 Then
            fndCompanyCode.MyReadOnly = False
        Else
            fndCompanyCode.MyReadOnly = True
        End If

        If fndCompanyCode.MyReadOnly OrElse isButtonClicked Then
            Dim qry As String '= "select Comp_Code as Code,Comp_Name  as [Company Name] from TSPL_COMPANY_MASTER "
            'fndCompanyCode.Value = clsCommon.ShowSelectForm("frmCompanycode", qry, "Code", "", fndCompanyCode.Value, "Comp_Code", isButtonClicked)
            fndCompanyCode.Value = clsCompanyMaster.getFinder("", fndCompanyCode.Value, isButtonClicked)
            qry = "select Comp_Name  from TSPL_COMPANY_MASTER where Comp_Code ='" + fndCompanyCode.Value + "'"
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
                txtCompanyName.Text = clsCommon.myCstr(dt.Rows(0)("Comp_Name"))
            Else
                txtCompanyName.Text = ""
            End If
            LoadData()
        End If
    End Sub

    Private Sub fndCompanyCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndCompanyCode._MYNavigator
        Dim qst As String = " select Comp_Code as [Company Code],Comp_Name  as [Company Name] from TSPL_COMPANY_MASTER  where 2=2"
        Select Case NavType
            Case NavigatorType.Current
                qst += " and TSPL_COMPANY_MASTER .Comp_Code in ('" + fndCompanyCode.Value + "')"
            Case NavigatorType.Next
                qst += " and TSPL_COMPANY_MASTER .Comp_Code in (select min(Comp_Code) from TSPL_COMPANY_MASTER where Comp_Code  >'" + fndCompanyCode.Value + "')"
            Case NavigatorType.First
                qst += " and TSPL_COMPANY_MASTER .Comp_Code in (select MIN(Comp_Code) from TSPL_COMPANY_MASTER)"

            Case NavigatorType.Last
                qst += " and TSPL_COMPANY_MASTER .Comp_Code in (select Max(Comp_Code) from TSPL_COMPANY_MASTER)"
            Case NavigatorType.Previous
                qst += " and TSPL_COMPANY_MASTER .Comp_Code in (select Max(Comp_Code) from TSPL_COMPANY_MASTER where Comp_Code  <'" + fndCompanyCode.Value + "')"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            fndCompanyCode.Value = clsCommon.myCstr(dt.Rows(0)("Company Code"))
            txtCompanyName.Text = clsCommon.myCstr(dt.Rows(0)("Company Name"))
        End If
        LoadData()
    End Sub
    Public Sub LoadData()
        dt = clsDBFuncationality.GetDataTable("select   Comp_Code from TSPL_COMPANY_MASTER where Comp_Code='" + fndCompanyCode.Value + "'")
        Dim s As String = ""
        ' While dr.Read()
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            For Each dr As DataRow In dt.Rows
                s = dr(0).ToString()
                ' End While
            Next
        End If
        ' dr.Close()
        '=====================update by preeti gupta===============================
        If clsCommon.CompairString(s, fndCompanyCode.Value) <> CompairStringResult.Equal Then
            txtCompanyName.Text = ""
            txtAdd1.Text = ""
            txtAdd2.Text = ""
            txtAdd3.Text = ""
            txtCity.Text = ""
            txtEmail.Text = ""
            txtFax.Text = ""
            txtTelephone2.Text = ""
            txtTelephone1.Text = ""

            ddlModeofTransp.Text = "      -----Select-----"
            txtPinCode.Text = ""
            txtState.Value = Nothing
            txtTinNo.Text = ""
            txtCstLst.Text = ""
            txtRegdNo.Text = ""
            txtcomp_code1.Text = ""
            txtVatRegNo.Text = ""
            txtPanNo.Text = ""
            txtServiceTaxRegNo.Text = ""
            txtTanNo.Text = ""
            txtAccessOfficer.Text = ""
            txtTcanNo.Text = ""
            txtCircleNo.Text = ""
            txtCERange.Text = ""
            txtCECommissionerate.Text = "0"
            txtWardNo.Text = ""
            txtCEDivision.Text = ""
            txtEccNo.Text = ""
            txtCIN.Text = ""
            TxtIECode.Text = ""
            Me.fndBaseCurrency.Value = Nothing
            Me.chkApplyMultiCurrency.Checked = False

            'chkIntegrateWithTally.Checked = False
            'txtCompanyNameTally.Text = ""

            chkCformRequiredTN.Checked = False
            cboDataBase.SelectedIndex = 0
            btnSave.Enabled = True
            btnSave.Text = "&Save"
        Else
            funFill()
        End If
        If fndCompanyCode.Value = "" Then
            funReset()
        End If
        LoadImage()
        LoadBackgroundImage()
    End Sub
    Private Sub txtState__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtState._MYValidating
        'Dim qry As String = "select STATE_CODE AS Code, STATE_NAME as Name from TSPL_STATE_MASTER"
        'txtState.Value = clsCommon.ShowSelectForm("STATE_MASTER", qry, "Code", "", txtState.Value, "STATE_CODE", isButtonClicked)
        txtState.Value = clsStateMaster.getFinder("", txtState.Value, isButtonClicked)

    End Sub

    Private Sub fndBaseCurrency__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndBaseCurrency._MYValidating
        'Dim qry As String = "select CURRENCY_CODE AS Code, CURRENCY_NAME as Name from TSPL_CURRENCY_MASTER"
        'fndBaseCurrency.Value = clsCommon.ShowSelectForm("CURRENCY_MASTER", qry, "Code", "", fndBaseCurrency.Value, "CURRENCY_CODE", isButtonClicked)

        fndBaseCurrency.Value = clsCurrencyMaster.getFinder("", fndBaseCurrency.Value, isButtonClicked)
    End Sub

    'Private Sub txtTelephone1_KeyPress(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
    '    If Not IsNumeric(e.KeyChar) And e.KeyChar <> "-" And e.KeyChar <> ControlChars.Back Then
    '        e.Handled = True
    '    End If
    'End Sub

    Private Sub chk_main_company_ToggleStateChanged(ByVal sender As System.Object, ByVal args As Telerik.WinControls.UI.StateChangedEventArgs) Handles chk_main_company.ToggleStateChanged
        Try
            If isInsideLoadData = True Then
                Return
            End If

            If chk_main_company.Checked Then
                Dim qry As String = "select count(*) from tspl_company_master where isnull(Is_Main_Company,'0')='1' and comp_code<>'" + fndCompanyCode.Value + "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)

                If check > 0 Then
                    chk_main_company.Checked = False
                    Throw New Exception("There is already a main company exist.")
                End If

            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub


    Private Sub txtcust_code__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtcust_code._MYValidating
        Try
            txtcust_code.Value = clsCustomerMaster.getFinder("", txtcust_code.Value, isButtonClicked)

            If clsCommon.myLen(txtcust_code.Value) > 0 Then
                Dim qry As String = "select count(*) from tspl_company_master where cust_code='" + txtcust_code.Value + "' and comp_code<>'" + fndCompanyCode.Value + "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)

                If check > 0 Then
                    txtcust_code.Value = ""
                    Throw New Exception("Selected customer already mapped with other company." + Environment.NewLine + "Select the other customer.")
                End If

                txtcust_name.Text = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select customer_name from tspl_customer_master where cust_code='" + txtcust_code.Value + "'"))
            Else
                txtcust_code.Value = ""
                txtcust_name.Text = ""
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub





End Class
