'--29/11/2013--form Add By- Pradeep Sharma @ BM00000001277
Imports common
Imports System.Data
Imports System.Data.SqlClient

Public Class frmCurrencyConversion
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String
    Public StrCode As String
#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        Save()
    End Sub

    Public Sub Save()
       

        If AllowToSave() Then
            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd("", clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If

            Dim obj As New clsCurrencyConversion()
            obj.Code = txtCode.Value
            obj.DESCRIPTION = txtDescription.Text
            obj.FROM_CURRENCY = txtFromCurrency.Value
            obj.TO_CURRENCY = txtToCurrency.Value
            obj.FROM_DATE = dtpFromDate.Value
            obj.TO_DATE = dtpToDate.Value
            obj.Rate = txtRate.Value
            If (obj.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                LoadData(obj.Code, NavigatorType.Current)
                'Else
                '    common.clsCommon.MyMessageBoxShow("This '" & obj.Code & "' already exist ")
            End If
        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnSave.Enabled = True
        btnDelete.Enabled = True
        isNewEntry = False
        Dim obj As New clsCurrencyConversion()
        obj = clsCurrencyConversion.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            txtCode.Value = obj.Code
            txtFromCurrency.Value = obj.FROM_CURRENCY
            lblFromCurrency.Text = clsCurrencyMaster.GetCurrencyName(txtFromCurrency.Value, Nothing)
            txtToCurrency.Value = obj.TO_CURRENCY
            lblToCurrency.Text = clsCurrencyMaster.GetCurrencyName(txtToCurrency.Value, Nothing)
            dtpFromDate.Value = obj.FROM_DATE
            dtpToDate.Value = obj.TO_DATE
            txtRate.Value = obj.Rate
            txtDescription.Text = obj.DESCRIPTION
        End If
    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
            myMessages.blankValue("Code")
            txtCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtFromCurrency.Value) <= 0 Then
            myMessages.blankValue("From Currency")
            txtFromCurrency.Focus()
            Return False
        ElseIf clsCommon.myLen(txtToCurrency.Value) <= 0 Then
            myMessages.blankValue("To Currency")
            txtToCurrency.Focus()
            Return False
        End If

        Dim StrQry As String = " select Code from TSPL_CURRENCY_CONVERSION_RATE " & _
                               " where FROM_CURRENCY = '" + clsCommon.myCstr(txtFromCurrency.Value) + "' and TO_CURRENCY ='" + clsCommon.myCstr(txtToCurrency.Value) + "' " & _
                               " and ( (FROM_DATE between '" + clsCommon.GetPrintDate(dtpFromDate.Value, "dd/MMM/yyyy") + "' and '" + clsCommon.GetPrintDate(dtpToDate.Value, "dd/MMM/yyyy") + "')" & _
                               " OR  (TO_DATE between '" + clsCommon.GetPrintDate(dtpFromDate.Value, "dd/MMM/yyyy") + "' and '" + clsCommon.GetPrintDate(dtpToDate.Value, "dd/MMM/yyyy") + "'))" & _
                               " and Code <> '" + clsCommon.myCstr(txtCode.Value) + "'"
        Dim strCodeEx As String = clsDBFuncationality.getSingleValue(StrQry)

        If clsCommon.myLen(strCodeEx) > 0 Then
            clsCommon.MyMessageBoxShow(Me, "Conversion rate for given date and Currency already define in Conversion Code : " + strCodeEx)
            Return False
        End If

        Return True
    End Function

    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub

    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "You Cannot Delete Record", Me.Text)
            Exit Sub
        End If
        funDelete()
    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsCurrencyConversion.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub

    Private Sub frmCurrencyConversion_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        If clsCommon.myLen(StrCode) > 0 Then
            LoadData(StrCode, NavigatorType.Current)
        End If
        isNewEntry = True
        Me.txtToCurrency.Value = objCommonVar.BaseCurrencyCode
        Me.txtToCurrency.MyReadOnly = True
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")
        '  ButtonToolTip.SetToolTip(btnPrint, "Press Alt+R for Print Preview")
    End Sub

    Private Sub SetUserMgmtNew()
        '' Anubhooti 31-July-2014 BM00000003131
        'MyBase.SetUserMgmt(clsUserMgtCode.frmCurrencyConversion)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnSave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 03/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnSave.Visible = True Then
            RadMenuItem1.Enabled = True
            RadMenuItem2.Enabled = True
        Else
            RadMenuItem1.Enabled = False
            RadMenuItem2.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub

    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        txtFromCurrency.Value = ""
        lblFromCurrency.Text = ""
        txtToCurrency.Value = ""
        lblToCurrency.Text = ""
        txtRate.Value = 0
        dtpFromDate.Value = clsCommon.GETSERVERDATE()
        dtpToDate.Value = clsCommon.GETSERVERDATE()
        txtDescription.Text = ""
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = True
        Me.txtToCurrency.Value = objCommonVar.BaseCurrencyCode
        Me.txtToCurrency.MyReadOnly = True
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()
    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        Dim str As String = "select count(*) from TSPL_CURRENCY_CONVERSION_RATE where Code = '" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtCode.MyReadOnly = False
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then
            'Dim qry As String = "select Code, FROM_CURRENCY as [From Currency],TO_CURRENCY as [To Currency], FROM_DATE as [From Date],TO_DATE as [To Date], DESCRIPTION as [Description] from TSPL_CURRENCY_CONVERSION_RATE"
            'txtCode.Value = clsCommon.ShowSelectForm("Curr_Con", qry, "Code", "", txtCode.Value, "Code", isButtonClicked)
            txtCode.Value = clsCurrencyConversion.getFinder("", txtCode.Value, isButtonClicked)
            If txtCode.Value <> "" Then
                LoadData(txtCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If
    End Sub

    Sub funFill()

    End Sub

    Private Sub txtCode_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCode.KeyPress
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub frmCurrencyConversion_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isModifyFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub txtFromCurrency__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtFromCurrency._MYValidating
        Try
            'Dim qry As String = " select CURRENCY_CODE AS Code, CURRENCY_NAME AS Name, DESCRIPTION from TSPL_CURRENCY_MASTER"
            'txtFromCurrency.Value = clsCommon.ShowSelectForm("CURRENCY_MASTER", qry, "Code", "", txtFromCurrency.Value, "CURRENCY_CODE", isButtonClicked)
            txtFromCurrency.Value = clsCurrencyMaster.getFinder("", txtFromCurrency.Value, isButtonClicked)
            'Dim clsemp As New clsEmployeeMaster
            lblFromCurrency.Text = clsCurrencyMaster.GetCurrencyName(txtFromCurrency.Value, Nothing)
        Catch ex As Exception
        End Try
    End Sub

    Private Sub txtToCurrency__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtToCurrency._MYValidating
        Try

            'Dim qry As String = " select CURRENCY_CODE AS Code, CURRENCY_NAME AS Name, DESCRIPTION from TSPL_CURRENCY_MASTER"
            'txtToCurrency.Value = clsCommon.ShowSelectForm("CURRENCY_MASTER", qry, "Code", "", txtToCurrency.Value, "CURRENCY_CODE", isButtonClicked)
            txtToCurrency.Value = clsCurrencyMaster.getFinder("", txtToCurrency.Value, isButtonClicked)
            'Dim clsemp As New clsEmployeeMaster
            lblToCurrency.Text = clsCurrencyMaster.GetCurrencyName(txtToCurrency.Value, Nothing)
        Catch ex As Exception
        End Try
    End Sub

    Private Sub RadMenuItem1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenuItem1.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "From Currency", "To Currency", "From Date", "To Date", "Description") Then
            'Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsCurrencyConversion()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Code can not be blank or incorrect.")
                    End If
                    obj.Code = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells(1).Value)
                    If strName.Length > 30 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("From Currency can not be blank or incorrect.")
                    End If
                    obj.FROM_CURRENCY = strName

                    strName = clsCommon.myCstr(grow.Cells(2).Value)
                    If strName.Length > 30 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("To Currency can not be blank or incorrect.")
                    End If
                    obj.TO_CURRENCY = strName

                    Dim fDate As Date = clsCommon.myCDate(grow.Cells(3).Value)
                    If fDate.Year < 1900 Then
                        Throw New Exception("From Date can not be blank or incorrect.")
                    End If
                    obj.FROM_DATE = fDate

                    Dim TDate As Date = clsCommon.myCDate(grow.Cells(4).Value)
                    If TDate.Year < 1900 Then
                        Throw New Exception("To Date can not be blank or incorrect.")
                    End If
                    obj.TO_DATE = TDate

                    Dim strDes As String = clsCommon.myCstr(grow.Cells(2).Value)
                    If strDes.Length > 200 Then
                        Throw New Exception("Description can not be blank or incorrect.")
                    End If
                    obj.DESCRIPTION = strDes

                    obj.SaveData(obj, True)
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)

    End Sub

    Private Sub RadMenuItem2_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenuItem2.Click
        Dim str As String
        str = " select Code, FROM_CURRENCY as [From Currency], TO_CURRENCY as [To Currency], FROM_DATE as [From Date], TO_DATE as [To Date], DESCRIPTION as [Description] from TSPL_CURRENCY_CONVERSION_RATE "
        transportSql.ExporttoExcel(str, Me)
    End Sub
End Class
