'--11/10/2013--form Add By- Pradeep Sharma ---------
Imports common
Imports System.Data
Imports System.Data.SqlClient

Public Class frmDistrictMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
#Region "Variable"
    Private isNewEntry As Boolean = False
    Private isInsideLoadData As Boolean = False
    Dim Qry As String

#End Region

    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        Save()
    End Sub

    Public Sub Save()
       
        If AllowToSave() Then
            If MyBase.isModifyonPasswordFlag Then
                If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.DistrictMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
                Else
                    Return
                End If
            End If
            Dim obj As New clsDistrictMaster()
            obj.Code = txtCode.Value
            obj.Name = txtName.Text
            obj.State_Code = txtState.Value
            obj.Region_Code = txtRegion.Value
            If (clsDistrictMaster.SaveData(obj, isNewEntry, Nothing)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                LoadData(obj.Code, NavigatorType.Current)
                btnSave.Text = "Update"
                btnDelete.Enabled = True
            Else
                btnSave.Text = "Save"
                btnDelete.Enabled = False
            End If

        End If
    End Sub

    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode.MyReadOnly = True
        btnSave.Enabled = True
        btnDelete.Enabled = True
        isNewEntry = False
        Dim obj As New clsDistrictMaster()
        obj = clsDistrictMaster.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            btnDelete.Enabled = True
            txtCode.Value = obj.Code
            txtName.Text = obj.Name
            txtState.Value = obj.State_Code
            lblState.Text = obj.State_Name
            txtRegion.Value = obj.Region_Code
            lblRegion.Text = obj.Region_Name
        End If
    End Sub

    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtCode.Value) <= 0 Then
            myMessages.blankValue(Me, "Code", Me.Text)
            txtCode.Focus()
            Return False
            'If clsCommon.myLen(txtCode.Value) <= 0 Then
            '    myMessages.blankValue("Code")
            '    txtCode.Focus()
            '    Return False
        ElseIf clsCommon.myLen(txtName.Text) <= 0 Then
            myMessages.blankValue(Me, "Name", Me.Text)
            txtName.Focus()
            Return False
        ElseIf clsCommon.myLen(txtRegion.Value) <= 0 Then
            myMessages.blankValue(Me, "Region Name", Me.Text)
            txtRegion.Focus()
            Return False
        ElseIf clsCommon.myLen(txtState.Value) <= 0 Then
            myMessages.blankValue(Me, "State Name", Me.Text)
            txtState.Focus()
            Return False
        End If
        Return True
    End Function


    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(txtCode.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "You Cannot Delete Record", Me.Text)
            Exit Sub
        End If
        Dim discCode As String
        discCode = clsDBFuncationality.getSingleValue("select STATE_CODE  from tspl_city_master  where STATE_CODE ='" & txtCode.Value & "'")
        If clsCommon.myLen(discCode) > 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "This record can't be deleted.It is used in another process", Me.Text)
            Exit Sub
        End If
        discCode = clsDBFuncationality.getSingleValue("select STATE_CODE  from tspl_village_master  where STATE_CODE ='" & txtCode.Value & "'")
        If clsCommon.myLen(discCode) > 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "This record can't be deleted.It is used in another process", Me.Text)
            Exit Sub
        End If
        ' Code Ends 
        funDelete()
    End Sub

    Sub funDelete()
        Try
            If (myMessages.deleteConfirm()) Then
                If (clsDistrictMaster.DeleteData(txtCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub frmStateMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        isNewEntry = True

        funReset()
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update ")
        ' ButtonToolTip.SetToolTip(btnPost, "Press Alt+P for  Post")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnNew, "Press Alt+N Adding New ")

    End Sub

    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.DistrictMaster)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
        End If
        btnSave.Visible = MyBase.isModifyFlag
        If btnSave.Visible = True Then
            MenuItemImport.Enabled = True
            MenuItemExport.Enabled = True
        Else
            MenuItemImport.Enabled = False
            MenuItemExport.Enabled = False
        End If
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub

    Private Sub btnNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnNew.Click
        funReset()
    End Sub



    Sub funReset()
        isNewEntry = True
        txtCode.MyReadOnly = False
        txtCode.Value = Nothing
        txtCode.Focus()
        txtName.Text = ""
        txtState.Value = ""
        lblState.Text = ""

        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = False
        lblRegion.Text = ""
        txtRegion.Value = ""
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()

    End Sub

    Sub funClose()
        Me.Close()
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating

        Dim str As String = "select count(*) from TSPL_STATE_MASTER where STATE_CODE ='" + txtCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtCode.MyReadOnly = False
        Else
            txtCode.MyReadOnly = True
        End If
        If txtCode.MyReadOnly OrElse isButtonClicked Then
            txtCode.Value = clsDistrictMaster.getFinder("", txtCode.Value, isButtonClicked)
            If txtCode.Value <> "" Then
                LoadData(txtCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If


    End Sub

    Sub funFill()

    End Sub

    Private Sub txtCode_KeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles txtCode.KeyPress
        If (e.KeyChar = Chr(39)) Then
            e.Handled = True
        End If
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        Try
            LoadData(txtCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub frmStateMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.N AndAlso btnNew.Enabled Then
            funReset()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            Save()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub txtCountry__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtState._MYValidating
        txtState.Value = clsStateMaster.getFinder("", txtState.Value, isButtonClicked)
        lblState.Text = clsStateMaster.GetName(txtState.Value)
    End Sub

    Private Sub MenuItemImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Name", "State_Code", "Region_Code") Then
            Try
                clsCommon.ProgressBarShow()
                Dim tran As SqlTransaction = clsDBFuncationality.GetTransactin()
                Dim ii As Integer = 0
                Try
                    For Each grow As GridViewRowInfo In gv.Rows
                        ii = ii + 1
                        Dim obj As New clsDistrictMaster()
                        obj.Code = clsCommon.myCstr(grow.Cells("Code").Value)
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Code can not be blank or incorrect.")
                        End If

                        obj.Name = clsCommon.myCstr(grow.Cells("Name").Value)
                        If clsCommon.myLen(obj.Name) <= 0 Then
                            Throw New Exception("Name can not be blank or incorrect.")
                        End If

                        obj.Region_Code = clsCommon.myCstr(grow.Cells("Region_Code").Value)
                        If clsCommon.myLen(obj.Region_Code) <= 0 Then
                            Throw New Exception("Region Code can not be blank.")
                        End If
                        obj.Region_Code = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select region_code from tspl_region_master where region_code='" + obj.Region_Code + "'", tran))
                        If clsCommon.myLen(obj.Region_Code) <= 0 Then
                            Throw New Exception("Region Code is not valid.")
                        End If


                        obj.State_Code = clsCommon.myCstr(grow.Cells("State_Code").Value)
                        If clsCommon.myLen(obj.Region_Code) <= 0 Then
                            Throw New Exception("State Code can not be blank")
                        End If
                        obj.State_Code = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select STATE_CODE from TSPL_STATE_MASTER where STATE_CODE='" + obj.State_Code + "'", tran))
                        If clsCommon.myLen(obj.State_Code) <= 0 Then
                            Throw New Exception("State Code is not valid.")
                        End If

                        clsDistrictMaster.SaveData(obj, clsDistrictMaster.CheckNewEntry(obj.Code, tran), tran)
                    Next
                Catch ex As Exception
                    tran.Rollback()
                    Throw New Exception("At Row No" + clsCommon.myCstr(ii) + ex.Message)
                End Try
                tran.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub


    Private Sub MenuItemExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MenuItemExport.Click
        Dim str As String
        str = "select Code, Name, State_Code,Region_Code from TSPL_DISTRICT_MASTER"
        transportSql.ExporttoExcel(str, Me)

    End Sub

    Private Sub txtRegion__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtRegion._MYValidating
        txtRegion.Value = ClsRegionMaster.getFinder("", txtRegion.Value, isButtonClicked)
        lblRegion.Text = ClsRegionMaster.getName(txtRegion.Value)
    End Sub
End Class
