Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls.Data
Imports Telerik.Data
Imports Telerik.WinControls.Enumerations
Imports Telerik.WinControls
Imports System.Text.RegularExpressions
Imports common
Public Class FrmTaxRates
    Inherits FrmMainTranScreen
    Const colGLCode As String = "colGLCode"
    Const colGLAccountName As String = "colGLAccountName"

    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim userCode, companyCode As String
    Dim GstApplicable As Boolean = False
    Dim ShowOnlyActiveTaxRateGroup As Boolean = False

    'Argument form constructor for usercode and companycode
    Public Sub New(ByVal user As String, ByVal company As String)
        InitializeComponent()
        userCode = user
        companyCode = company
    End Sub

    Private Sub SetUserMgmtNew()
        '' Anubhooti 30-July-2014 BM00000003131
        'MyBase.SetUserMgmt(clsUserMgtCode.taxRate)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")
            'Me.Close()
            'Exit Function
        End If
        btnAdd.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 03/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnAdd.Visible = True Then
            menuImport.Enabled = True
            menuExport.Enabled = True
        Else
            menuImport.Enabled = False
            menuExport.Enabled = False
        End If
        '--------------------------------------------------
        '         btnclose.Visible = MyBase.isDeleteFlag
        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub
    Public Sub SetLength()
        findTaxAuthority.MyMaxLength = 12
    End Sub
#Region "Page Events"
    Private Sub FrmTaxRates_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        ' globalFunc.mandatoryText(findTaxAuthority.Value)
    

        SetLength()
        findTaxAuthority.MyMaxLength = 12
        fillTransactionType()
        SetUserMgmtNew()
        ButtonToolTip.SetToolTip(btnAdd, "Press Alt+S for Save/Update Trasnaction")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D Delete Trasnaction")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnReset, "Press Alt+N Adding New Trasnaction")
        'AddHandler findTaxAuthority.Value.TextChanged, AddressOf findTaxAuthority_TextChanged
        ' AddHandler findTaxAuthority.Value.KeyPress, AddressOf keyPress1
        btnAdd.Enabled = False
        btnDelete.Enabled = False
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
        '' Anubhooti 10-Dec-2014 BM00000004507 (Call Reset)
        reset()
        ''
        Dim repoType As GridViewComboBoxColumn = New GridViewComboBoxColumn()
        repoType.FormatString = ""
        repoType.HeaderText = "Type"
        repoType.Name = "Type"
        repoType.Width = 100
        repoType.ReadOnly = False
        repoType.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft
        repoType.DataSource = clsFormMaster.GetFormTypes()
        repoType.ValueMember = "Code"
        repoType.DisplayMember = "Name"
        gvTaxRates.MasterTemplate.Columns.Add(repoType)



        GstApplicable = clsCommon.myCBool(IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.GSTApplicable, clsFixedParameterCode.GSTApplicable, Nothing)) = "1", True, False))
        ShowOnlyActiveTaxRateGroup = clsCommon.myCBool(IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.GSTActiveTaxesRatesGroup, clsFixedParameterCode.GSTActiveTaxesRatesGroup, Nothing)) = "1", True, False))
        If GstApplicable Then
            chkGSTActive.Enabled = True
        Else
            chkGSTActive.Enabled = False
        End If
    End Sub


#End Region


#Region "Variables"
    Dim sql As String
    Dim ds As DataSet
    Dim dr As DataTable

    Dim tableName As String = "TSPL_TAX_RATES"
    Dim tableCode As String = "Tax_Rate_Code"
    Dim codePrefix As String = "RC"
#End Region

#Region " events"
    Public Sub savedata()
        If MyBase.isModifyonPasswordFlag Then
            If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.taxRate, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
            Else
                Return
            End If
        End If
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(findTaxAuthority.Value) <= 0 Then
                common.clsCommon.MyMessageBoxShow("Tax Authority Can not be Left Blank")
                findTaxAuthority.Focus()
                Exit Sub
            End If
        End If
        Dim GSTActive As Integer
        If chkGSTActive.Checked = True Then
            GSTActive = 1
        Else
            GSTActive = 0
        End If

        Dim con As SqlConnection = connectSql.OpenConnection()
        Dim trans As SqlTransaction = con.BeginTransaction()
        If validate1(trans) Then
            If btnAdd.Text = "Save" Then
                Try
                    If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                        Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_TAX_RATES where Tax_Code='" & findTaxAuthority.Value & "'", trans)
                        If ChkNewEntry = 0 Then
                            findTaxAuthority.Value = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.TaxRates, "", "")
                            If clsCommon.myLen(findTaxAuthority.Value) <= 0 Then
                                Throw New Exception("Error in Code Generation")
                            End If
                        End If
                    End If
                    If (gvTaxRates.RowCount <> 0) Then
                        Dim linno As Integer = 0
                        For Each grow As GridViewRowInfo In gvTaxRates.Rows
                            linno += 1
                            If clsCommon.myLen(grow.Cells(5).Value) <= 0 Then
                                Throw New Exception("Please fill type at line no. " & linno & "")
                            End If
                            connectSql.RunSpTransaction(trans, "sp_TSPL_TAX_RATES_INSERT", New SqlParameter("@Tax_Code", findTaxAuthority.Value), New SqlParameter("@Tax_Type", ddlTransType.SelectedValue), New SqlParameter("@Tax_Rate_Desc", grow.Cells(0).Value), New SqlParameter("@Tax_Rate", clsCommon.myCdbl(grow.Cells(1).Value)), New SqlParameter("@Tax_Rate_Code", grow.Index + 1), New SqlParameter("@Created_By", userCode), New SqlParameter("@Created_Date", connectSql.serverDate(trans)), New SqlParameter("@Modify_By", userCode), New SqlParameter("@Modify_Date", connectSql.serverDate(trans)), New SqlParameter("@Comp_Code", companyCode), New SqlParameter("@GL_Account_Code", clsCommon.myCstr(grow.Cells(colGLCode).Value)), New SqlParameter("@Type", grow.Cells(5).Value))

                            Dim coll As New Hashtable()
                            clsCommon.AddColumnsForChange(coll, "GSTActive", clsCommon.myCdbl(GSTActive))
                            clsCommonFunctionality.UpdateDataTable(coll, "TSPL_TAX_RATES", OMInsertOrUpdate.Update, "TSPL_TAX_RATES.Tax_Code='" + findTaxAuthority.Value + "' and Tax_Type='" + ddlTransType.SelectedValue + "'", trans)
                        Next
                        trans.Commit()
                        myMessages.insert()
                        btnAdd.Text = "Update"
                        btnDelete.Enabled = True
                    Else
                        myMessages.zeroGridRow()
                        trans.Rollback()
                        con.Close()
                    End If

                Catch ex As Exception
                    myMessages.myExceptions(ex)
                    trans.Rollback()
                    con.Close()
                End Try
            ElseIf btnAdd.Text = "Update" Then
                Try
                    If (gvTaxRates.RowCount <> 0) Then
                        connectSql.RunSpTransaction(trans, "sp_TSPL_TAX_RATES_DELETE", New SqlParameter("@Tax_Code", findTaxAuthority.Value), New SqlParameter("@Tax_Type", ddlTransType.SelectedValue))
                        Dim linno As Integer = 0
                        For Each grow As GridViewRowInfo In gvTaxRates.Rows
                            '' Anubhooti 10-Dec-2014 BM00000004507
                            linno += 1
                            If clsCommon.myLen(grow.Cells(5).Value) <= 0 Then
                                Throw New Exception("Please fill type at line no. " & linno & "")
                            End If
                            connectSql.RunSpTransaction(trans, "sp_TSPL_TAX_RATES_INSERT", New SqlParameter("@Tax_Code", findTaxAuthority.Value), New SqlParameter("@Tax_Type", ddlTransType.SelectedValue), New SqlParameter("@Tax_Rate_Desc", grow.Cells(0).Value), New SqlParameter("@Tax_Rate", clsCommon.myCdbl(grow.Cells(1).Value)), New SqlParameter("@Tax_Rate_Code", grow.Index + 1), New SqlParameter("@Created_By", userCode), New SqlParameter("@Created_Date", connectSql.serverDate(trans)), New SqlParameter("@Modify_By", userCode), New SqlParameter("@Modify_Date", connectSql.serverDate(trans)), New SqlParameter("@Comp_Code", companyCode), New SqlParameter("@GL_Account_Code", clsCommon.myCstr(grow.Cells(colGLCode).Value)), New SqlParameter("@Type", grow.Cells(5).Value))

                            Dim coll As New Hashtable()
                            clsCommon.AddColumnsForChange(coll, "GSTActive", clsCommon.myCdbl(GSTActive))
                            clsCommonFunctionality.UpdateDataTable(coll, "TSPL_TAX_RATES", OMInsertOrUpdate.Update, "TSPL_TAX_RATES.Tax_Code='" + findTaxAuthority.Value + "' and Tax_Type='" + ddlTransType.SelectedValue + "'", trans)
                        Next
                        trans.Commit()
                        myMessages.update()
                        btnAdd.Text = "Update"
                    Else
                        myMessages.zeroGridRow()
                        trans.Rollback()
                        con.Close()
                    End If
                Catch ex As Exception
                    myMessages.myExceptions(ex)
                    trans.Rollback()
                End Try
            End If
        End If
    End Sub
    Private Sub btnAdd_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnAdd.Click
        savedata()
    End Sub
    Public Sub deletedata()
        If clsCommon.myLen(findTaxAuthority.Value) <= 0 Then
            Exit Sub
        End If
        Dim trans As SqlTransaction = Nothing
        If myMessages.deleteConfirm() Then
            Try
                connectSql.OpenConnection()
                trans = clsDBFuncationality.GetTransactin()
                connectSql.RunSpTransaction(trans, "sp_TSPL_TAX_RATES_DELETE", New SqlParameter("@Tax_Code", findTaxAuthority.Value), New SqlParameter("@Tax_Type", ddlTransType.SelectedValue))
                trans.Commit()
                myMessages.delete()
                reset()
            Catch ex As Exception
                myMessages.myExceptions(ex)
                trans.Rollback()

            End Try
        End If
    End Sub
    Private Sub btnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        deletedata()
    End Sub
    Private Sub btnReset_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnReset.Click
        reset()
    End Sub

    Private Sub btnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClose.Click
        Me.Close()
    End Sub
    Private Sub ddlTransType_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As Telerik.WinControls.UI.Data.PositionChangedEventArgs) Handles ddlTransType.SelectedIndexChanged
        If (findTaxAuthority.Value <> "") Then
            fillControls()
        End If
    End Sub

    Private Sub gvTaxRates_CellBeginEdit(ByVal sender As System.Object, ByVal e As Telerik.WinControls.UI.GridViewCellCancelEventArgs) Handles gvTaxRates.CellBeginEdit
        If TypeOf Me.gvTaxRates.CurrentColumn Is GridViewTextBoxColumn Then
            Dim editor As RadTextBoxEditor = DirectCast(Me.gvTaxRates.ActiveEditor, RadTextBoxEditor)
            Dim editorElement As RadTextBoxElement = DirectCast(editor.EditorElement, RadTextBoxElement)
            If e.ColumnIndex = 0 Then
                AddHandler editorElement.KeyPress, AddressOf keyPress1
            End If
        End If
    End Sub

    Private Sub RateKeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
        e.Handled = globalFunc.TrapKey(Asc(e.KeyChar))
    End Sub
    Private Sub keyPress1(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
        If Microsoft.VisualBasic.Asc(e.KeyChar) = 39 Then
            e.Handled = True
        End If
    End Sub

#End Region

#Region "Finders"
    Private Sub findTaxAuthority_TextChanged()
        fillControls()
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
        If findTaxAuthority.Value = String.Empty Then
            btnAdd.Enabled = False
            btnDelete.Enabled = False
        End If
    End Sub
    'Private Sub findTaxAuthority_Load(ByVal sender As System.Object, ByVal e As System.EventArgs)
    '    findTaxAuthority.ConnectionString = connectSql.SqlCon()
    '    findTaxAuthority.Query = "select TAX_code as 'Tax Authority',Tax_Code_Desc as 'Description' from tspl_tax_master"
    '    findTaxAuthority.ValueToSelect = "Tax Authority"
    '    findTaxAuthority.ValueToSelect1 = "Description"
    '    findTaxAuthority.Caption = "Tax Authority"
    'End Sub
#End Region

#Region "Methods"

    ''This will check the authorization of user to access the screen.If authorize then it will allow user to access the screen.
    'Private Function funSetUserAccess() As Boolean
    '    Try
    '        Dim strRights As String
    '        Dim strTemp() As String
    '        Dim strProgCode = "TAX-RATE-M"
    '        strRights = enuUserRights.enuRead & "," & enuUserRights.enuModify & "," & enuUserRights.enuDelete
    '        strRights = modUserMgt.funGetPermissions(strRights, strProgCode)
    '        strTemp = Split(strRights, ",")
    '        If strTemp(0) = "0" Then
    '            common.clsCommon.MyMessageBoxShow("Permission Denied", Me.Text, MessageBoxButtons.OK)
    '            funSetUserAccess = False
    '            blnRead = False
    '            Me.Close()
    '            Exit Function
    '        Else
    '            blnRead = True
    '        End If
    '        If strTemp(1) = "0" Then 'Grant modify access
    '            btnAdd.Enabled = False
    '        End If
    '        If strTemp(2) = "0" Then 'Grant modify access
    '            btnDelete.Enabled = False
    '        End If

    '        funSetUserAccess = True
    '    Catch er As Exception
    '        myMessages.myExceptions(er)
    '    End Try
    'End Function

    Private Sub NumericKeyPress(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
        e.Handled = globalFunc.TrapKey(Asc(e.KeyChar))
    End Sub

    Private Sub fillTransactionType()
        Dim dataTableTransType As New DataTable()
        dataTableTransType.Columns.Add("TransDesc")
        dataTableTransType.Columns.Add("TransValue")
        dataTableTransType.Rows.Add("Sales", "S")
        dataTableTransType.Rows.Add("Purchase", "P")
        dataTableTransType.Rows.Add("Transfer", "T")
        dataTableTransType.Rows.Add("HR And Payroll", "H")
        ddlTransType.DisplayMember = "TransDesc"
        ddlTransType.ValueMember = "TransValue"
        ddlTransType.DataSource = dataTableTransType
        ddlTransType.SelectedValue = "S"
    End Sub
    Private Sub reset()
        findTaxAuthority.Value = ""
        findTaxAuthority.MyReadOnly = False
        ddlTransType.SelectedValue = "S"
        btnAdd.Text = "Save"
        btnAdd.Enabled = True
        gvTaxRates.DataSource = Nothing
        gvTaxRates.Rows.Clear()
    End Sub
    Private Sub fillControls()
        gvTaxRates.DataSource = Nothing
        gvTaxRates.Rows.Clear()
        sql = "select " + tableName + ".Tax_Rate_Code," + tableName + ".Tax_Rate_Desc," + tableName + ".Tax_Rate," + tableName + ".GL_Account_Code,TSPL_GL_ACCOUNTS.Description as GLAccountName," & tableName & "._Type ," & tableName & ".GSTActive FROM  " + tableName + " left outer join TSPL_GL_ACCOUNTS on TSPL_GL_ACCOUNTS.Account_Code=" + tableName + ".GL_Account_Code  where " + tableName + ".Tax_Code='" + findTaxAuthority.Value + "' and " + tableName + ".Tax_Type='" + ddlTransType.SelectedValue + "'"
        ds = connectSql.RunSQLReturnDS(sql)
        For Each drow As DataRow In ds.Tables(0).Rows
            gvTaxRates.Rows.Add(drow(1).ToString(), drow(2).ToString(), drow(1).ToString(), clsCommon.myCstr(drow("GL_Account_Code")), clsCommon.myCstr(drow("GLAccountName")), clsCommon.myCstr(drow("_Type")))
        Next
        chkIsGLReadonly.Checked = True
        If clsCommon.CompairString(clsCommon.myCstr(ddlTransType.SelectedValue), "S") = CompairStringResult.Equal Then
            chkIsGLReadonly.Checked = False
        ElseIf clsCommon.CompairString(clsCommon.myCstr(ddlTransType.SelectedValue), "P") = CompairStringResult.Equal Then
            sql = "select Tax_Recoverable from tspl_tax_master where Tax_Code='" + findTaxAuthority.Value + "'"
            If clsCommon.CompairString(clsCommon.myCstr(clsDBFuncationality.getSingleValue(sql)), "Y") = CompairStringResult.Equal Then
                chkIsGLReadonly.Checked = False
            End If
        End If
        If ds.Tables(0).Rows.Count > 0 Then
            If clsCommon.myCdbl(ds.Tables(0).Rows(0)("GSTActive")) = 1 Then
                chkGSTActive.Checked = True
            Else
                chkGSTActive.Checked = False
            End If
        End If


        If (gvTaxRates.Rows.Count <> 0) Then
            btnAdd.Text = "Update"
            btnDelete.Enabled = True
            btnAdd.Enabled = True
        Else
            btnAdd.Text = "Save"
            btnAdd.Enabled = True
            btnDelete.Enabled = False
            'If userCode <> "ADMIN" Then
            '    If funSetUserAccess() = False Then Exit Sub
            'End If
        End If
    End Sub
    Function validate1(ByVal trans As SqlTransaction) As Boolean
        sql = "select TAX_code from tspl_tax_master where Tax_Code='" + findTaxAuthority.Value + "'"
        dr = clsDBFuncationality.GetDataTable(sql, trans)
        If dr.Rows Is Nothing AndAlso dr.Rows.Count <= 0 Then
            common.clsCommon.MyMessageBoxShow("Tax Autority is not valid.")
            findTaxAuthority.Focus()
            Return False
        End If
        ''richa agarwal 12 Nov,2016
        If clsCommon.CompairString(clsCommon.myCstr(findTaxAuthority.Value).ToUpper(), "WCT") = CompairStringResult.Equal Then
            Dim dbltaxrate As Integer = 0
            For i As Integer = 0 To gvTaxRates.Rows.Count - 1
                If clsCommon.myLen(gvTaxRates.Rows(i).Cells(0).Value) <> 0 Then
                    dbltaxrate = clsCommon.myCdbl(gvTaxRates.Rows(i).Cells(1).Value)
                    If dbltaxrate >= 0 Then
                        common.clsCommon.MyMessageBoxShow("Tax rate must be in -ve for WCT type.")
                        Return False
                    End If
                End If
            Next
        End If
        ''--------
        Return True
    End Function
#End Region

#Region "Menu Events"
    Private Sub menuExit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles menuExit.Click
        Me.Close()
    End Sub

#Region "Import/Export"

    Private Sub menuExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles menuExport.Click
        sql = "Select Tax_Code as 'Tax Authority',(Case when Tax_Type='S' then 'Sales' when Tax_Type='P' then  'Purchase' when Tax_Type='T' then 'Transfer' else '' end) as 'Tax Type'," & _
        "Tax_Rate_Code as 'Rate Code',Tax_Rate_Desc as 'Rate Description',Tax_Rate as 'Tax Rate' "
        If GstApplicable And ShowOnlyActiveTaxRateGroup Then
            sql += " ,GSTActive as 'GST Active' "
        End If
        sql += " from TSPL_TAX_RATES"

        ListImpExpColumnsMandatory = New List(Of String)({"Tax Authority", "Tax Type", "Rate Code", "Rate Description", "Tax Rate"})
        ListImpExpColumnsSuperMandatory = New List(Of String)({"Tax Authority", "Tax Type", "Rate Code"})
        transportSql.ExporttoExcel(sql, "", "", Me, ListImpExpColumnsMandatory, ListImpExpColumnsSuperMandatory, MyBase.Form_ID)
    End Sub
    Private Sub menuImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles menuImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim Input() As String = {}

        If GstApplicable And ShowOnlyActiveTaxRateGroup Then
            Input = {"Tax Authority", "Tax Type", "Rate Code", "Rate Description", "Tax Rate", "GST Active"}
        Else
            Input = {"Tax Authority", "Tax Type", "Rate Code", "Rate Description", "Tax Rate"}
        End If
        Dim strInputlist As List(Of String) = New List(Of String)(Input)
        If transportSql.importExcel(gv, strInputlist.ToArray()) Then
            Dim trans As SqlTransaction = Nothing
            Try
                connectSql.OpenConnection()
                trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim strTaxCode As String = grow.Cells(0).Value
                    Dim strTaxType As String = grow.Cells(1).Value
                    Dim strRateCode As String = grow.Cells(2).Value
                    Dim strRateDesc As String = grow.Cells(3).Value
                    Dim strRate As String
                    If IsDBNull(grow.Cells(4).Value) Then
                        strRate = ""
                    Else
                        strRate = grow.Cells(4).Value
                    End If
                    Dim strGSTActive As Integer = 0
                    If GstApplicable And ShowOnlyActiveTaxRateGroup Then
                        If Not IsDBNull(grow.Cells(5).Value) Then
                            strGSTActive = clsCommon.myCdbl(grow.Cells(5).Value)
                        Else
                            Throw New Exception("GST Aactive should be 0 or 1")
                            trans.Rollback()
                            Me.Controls.Remove(gv)
                            Exit Sub
                        End If
                    End If
                    If strGSTActive <> 1 AndAlso strGSTActive <> 0 Then
                        Throw New Exception("GST Aactive should be 0 or 1")
                        trans.Rollback()
                        Me.Controls.Remove(gv)
                        Exit Sub
                    End If


                    If String.IsNullOrEmpty(strTaxCode) Or strTaxCode.Length > 12 Then
                        Throw New Exception("Tax Authority has some incorrect values")
                        trans.Rollback()
                        Me.Controls.Remove(gv)
                        Exit Sub
                    End If
                    If (strTaxType = "Sales") Then
                        strTaxType = "S"
                    ElseIf (strTaxType = "Purchase") Then
                        strTaxType = "P"
                    ElseIf (strTaxType = "Transfer") Then
                        strTaxType = "T"
                    Else
                        Throw New Exception("Tax Type has some incorrect values")
                        trans.Rollback()
                        Me.Controls.Remove(gv)
                        Exit Sub
                    End If
                    If String.IsNullOrEmpty(strRateCode) Or strRateCode.Length > 6 Then
                        Throw New Exception("Tax Rate Code has some incorrect values")
                        trans.Rollback()
                        Me.Controls.Remove(gv)
                        Exit Sub
                    End If
                    If String.IsNullOrEmpty(strRateDesc) Or strRateDesc.Length > 50 Then
                        Throw New Exception("Tax Rate Description has some incorrect values")
                        trans.Rollback()
                        Me.Controls.Remove(gv)
                        Exit Sub
                    End If
                    If String.IsNullOrEmpty(strRate) Or strRate.Length > 50 Then
                        Throw New Exception("Tax Rate has some incorrect values")
                        trans.Rollback()
                        Me.Controls.Remove(gv)
                        Exit Sub
                    End If
                    Dim re As Regex = New Regex("(^[0-9]+$)")
                    If Not IsNumeric(strRate) Then
                        Throw New Exception("Tax Rate has some incorrect values")
                        trans.Rollback()
                        Me.Controls.Remove(gv)
                        Exit Sub
                    End If
                    Try
                        connectSql.RunSpTransaction(trans, "sp_TSPL_TAX_RATES_INSERT", New SqlParameter("@Tax_Code", strTaxCode), New SqlParameter("@Tax_Type", strTaxType), New SqlParameter("@Tax_Rate_Desc", strRateDesc), New SqlParameter("@Tax_Rate", strRate), New SqlParameter("@Tax_Rate_Code", strRateCode), New SqlParameter("@Created_By", userCode), New SqlParameter("@Created_Date", connectSql.serverDate(trans)), New SqlParameter("@Modify_By", userCode), New SqlParameter("@Modify_Date", connectSql.serverDate(trans)), New SqlParameter("@Comp_Code", companyCode), New SqlParameter("@GL_Account_Code", ""), New SqlParameter("@Type", ""))
                        If GstApplicable And ShowOnlyActiveTaxRateGroup Then
                            Dim coll As New Hashtable()
                            clsCommon.AddColumnsForChange(coll, "GSTActive", clsCommon.myCdbl(strGSTActive))
                            clsCommonFunctionality.UpdateDataTable(coll, "TSPL_TAX_RATES", OMInsertOrUpdate.Update, "TSPL_TAX_RATES.Tax_Code='" + strTaxCode + "' and Tax_Type='" + strTaxType + "'", trans)
                        End If
                    Catch ex As Exception
                        If ex.Message.Contains("Violation of PRIMARY KEY") Then
                            sql = "UPDATE TSPL_TAX_RATES SET Tax_Rate_Desc='" + strRateDesc + "',Tax_Rate='" + strRate + "' WHERE Tax_Code='" + strTaxCode + "' and Tax_Type='" + strTaxType + "' and Tax_Rate_Code='" + strRateCode + "'"
                            connectSql.RunSqlTransaction(trans, sql)
                        End If
                    End Try
                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception

                trans.Rollback()
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)

            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub
#End Region
#End Region

    Private Sub FrmTaxRates_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnAdd.Enabled Then
            savedata()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            deletedata()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            reset()

        End If
    End Sub

    Private Sub findTaxAuthority__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles findTaxAuthority._MYValidating
        Dim qst As String = ""
        If GstApplicable And ShowOnlyActiveTaxRateGroup Then
            qst = "select count(*) from tspl_tax_master where TAX_code='" + findTaxAuthority.Value + "' and GSTActive=1 "
        Else
            qst = "select count(*) from tspl_tax_master where TAX_code='" + findTaxAuthority.Value + "'"
        End If
        Dim count As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(qst))
        If count = 0 Then
            findTaxAuthority.MyReadOnly = False
        Else
            findTaxAuthority.MyReadOnly = True
        End If

        If findTaxAuthority.MyReadOnly OrElse isButtonClicked Then
            'Dim qry As String = "select TAX_code as 'TaxAuthority',Tax_Code_Desc as 'Description' from tspl_tax_master"
            'findTaxAuthority.Value = clsCommon.ShowSelectForm("frmTaxAuty", qry, "TaxAuthority", "", findTaxAuthority.Value, "TAX_code", isButtonClicked)
            Dim strwhrcls As String = ""
            If GstApplicable And ShowOnlyActiveTaxRateGroup Then
                strwhrcls = " GSTActive=1"
            End If
            findTaxAuthority.Value = clsTaxMaster.getFinder(strwhrcls, findTaxAuthority.Value, isButtonClicked)
            LoadData()
        End If
    End Sub

    Private Sub findTaxAuthority__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles findTaxAuthority._MYNavigator
        Dim strwhrcls As String = ""
        Dim strwhrcls2 As String = ""
        Dim qst As String = "select TAX_code as 'Tax Authority',Tax_Code_Desc as 'Description' from tspl_tax_master where 2=2 "
        If GstApplicable And ShowOnlyActiveTaxRateGroup Then
            strwhrcls = " and GSTActive=1 "
            strwhrcls2 = " where GSTActive=1"
        End If
        Select Case NavType
            Case NavigatorType.Current
                qst += " and tspl_tax_master .TAX_code in ('" + findTaxAuthority.Value + "') " + strwhrcls + ""
            Case NavigatorType.Next
                qst += " and tspl_tax_master .TAX_code in (select min(TAX_code) from tspl_tax_master where TAX_code  >'" + findTaxAuthority.Value + "'  " + strwhrcls + ")"
            Case NavigatorType.First
                qst += " and tspl_tax_master .TAX_code in (select MIN(TAX_code) from tspl_tax_master  " + strwhrcls2 + " )"

            Case NavigatorType.Last
                qst += " and tspl_tax_master .TAX_code in (select Max(TAX_code) from tspl_tax_master " + strwhrcls2 + ")"
            Case NavigatorType.Previous
                qst += " and tspl_tax_master .TAX_code in (select Max(TAX_code) from tspl_tax_master where TAX_code  <'" + findTaxAuthority.Value + "' " + strwhrcls + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qst)
        If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
            findTaxAuthority.Value = clsCommon.myCstr(dt.Rows(0)("Tax Authority"))
        End If
        LoadData()
    End Sub
    Public Sub LoadData()
        fillControls()
        'If userCode <> "ADMIN" Then
        '    If funSetUserAccess() = False Then Exit Sub
        'End If
        If findTaxAuthority.Value = String.Empty Then
            btnAdd.Enabled = False
            btnDelete.Enabled = False
        End If
    End Sub

    Private Sub gvTaxRates_UserDeletingRow(ByVal sender As System.Object, ByVal e As Telerik.WinControls.UI.GridViewRowCancelEventArgs) Handles gvTaxRates.UserDeletingRow
        If common.clsCommon.MyMessageBoxShow("Delete The Current Row." + Environment.NewLine + "Are you sure?", Me.Text, MessageBoxButtons.YesNo) = System.Windows.Forms.DialogResult.No Then
            e.Cancel = True
        End If
    End Sub
    Private isInsideLoadData As Boolean = False
    Private isCellValueChangedOpen As Boolean = False
    Private Sub gvTaxRates_CellValueChanged(ByVal sender As System.Object, ByVal e As Telerik.WinControls.UI.GridViewCellEventArgs) Handles gvTaxRates.CellValueChanged
        If (Not isInsideLoadData) Then
            If Not isCellValueChangedOpen Then
                If (clsCommon.CompairString(e.Column.Name, colGLCode) = CompairStringResult.Equal) Then
                    OpenGLAccount(False)
                End If
            End If
        End If
    End Sub

    Private Sub OpenGLAccount(ByVal isButtonClick As Boolean)
        Dim qry As String
        Dim whrcls As String
        Dim arr As New ArrayList()
      
        arr = clsERPFuncationality.glaccountquery(objCommonVar.CurrentUserCode)
        qry = arr.Item(0) + " inner join TSPL_GL_STRUCTURE on TSPL_GL_ACCOUNTS.Str_Code=TSPL_GL_STRUCTURE.Str_Code "
        whrcls = arr.Item(1)

        If whrcls = "" Then

        Else
            whrcls = "(" + whrcls + ")"
        End If
        If whrcls Is Nothing OrElse whrcls = "" Then
            whrcls = " 1<>(Seg_No1 +Seg_No2 +Seg_No3 +Seg_No4 +Seg_No5 +Seg_No6 +Seg_No7 +Seg_No8 +Seg_No9 +Seg_No10 )"
        Else
            whrcls = whrcls + " and 1<>(Seg_No1 +Seg_No2 +Seg_No3 +Seg_No4 +Seg_No5 +Seg_No6 +Seg_No7 +Seg_No8 +Seg_No9 +Seg_No10 )"
        End If
        whrcls += " and TSPL_GL_ACCOUNTS.ControlAccount='N' "
        ''gvTaxRates.CurrentColumn = gvTaxRates.Columns(colAmt)
        gvTaxRates.CurrentRow.Cells(colGLCode).Value = clsCommon.ShowSelectForm("TaxRateChangFND", qry, "Account_Code", whrcls, clsCommon.myCstr(gvTaxRates.CurrentRow.Cells(colGLCode).Value), "Account_Code", isButtonClick)
        gvTaxRates.CurrentRow.Cells(colGLAccountName).Value = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Description from TSPL_GL_ACCOUNTS where Account_Code='" + clsCommon.myCstr(gvTaxRates.CurrentRow.Cells(colGLCode).Value) + "'"))
    End Sub

    Private Sub gvTaxRates_CellFormatting(ByVal sender As System.Object, ByVal e As Telerik.WinControls.UI.CellFormattingEventArgs) Handles gvTaxRates.CellFormatting
        Try
            If e.Column.Index >= 0 Then
                If e.Column Is gvTaxRates.Columns(colGLCode) Then
                    gvTaxRates.CurrentRow.Cells(colGLCode).ReadOnly = chkIsGLReadonly.Checked
                End If
            End If
        Catch ex As Exception

        End Try
    End Sub
End Class
