Imports System.Data.SqlClient
Imports common
Public Class clsCostType
#Region "variables"
    Public COST_TYPE_CODE As String = ""
    Public DESCRIPTION As String = ""
    Public COST_CLASS As String = ""
    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing

#End Region
#Region "Functions"
    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_PJC_COST_TYPE.COST_TYPE_CODE as [Code] ,TSPL_PJC_COST_TYPE.DESCRIPTION as [Description] ,TSPL_PJC_COST_TYPE.COST_CLASS as [Cost Class] ,TSPL_PJC_COST_TYPE.Created_By as [Created By] ,TSPL_PJC_COST_TYPE.Created_Date as [Created Date] ,TSPL_PJC_COST_TYPE.Modified_By as [Modified By] ,TSPL_PJC_COST_TYPE.Modified_Date as [Modified Date]  From TSPL_PJC_COST_TYPE  "
        str = clsCommon.ShowSelectForm("COSTTYPEFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function SaveData(ByVal obj As clsCostType, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""

        Try

            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "COST_CLASS", obj.COST_CLASS)
            clsCommon.AddColumnsForChange(coll, "Description", obj.DESCRIPTION)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_PJC_COST_TYPE where COST_TYPE_CODE='" & obj.COST_TYPE_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.COST_TYPE_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.CostType, "", "")
                        If clsCommon.myLen(obj.COST_TYPE_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "COST_TYPE_CODE", obj.COST_TYPE_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PJC_COST_TYPE", OMInsertOrUpdate.Insert, "", trans)
            Else
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PJC_COST_TYPE", OMInsertOrUpdate.Update, "TSPL_PJC_COST_TYPE.COST_TYPE_CODE='" + obj.COST_TYPE_CODE + "'", trans)
            End If

        Catch err As Exception
            Return False
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsCostType
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsCostType
        Dim obj As clsCostType = Nothing
        Dim Arr As List(Of clsCostType) = Nothing
        Dim qry As String = "select COST_TYPE_CODE ,DESCRIPTION,DESCRIPTION,COST_CLASS from TSPL_PJC_COST_TYPE where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_PJC_COST_TYPE.COST_TYPE_CODE = (select MIN(COST_TYPE_CODE) from TSPL_PJC_COST_TYPE WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_PJC_COST_TYPE.COST_TYPE_CODE = (select Max(COST_TYPE_CODE) from TSPL_PJC_COST_TYPE WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_PJC_COST_TYPE.COST_TYPE_CODE = (select top 1 COST_TYPE_CODE from TSPL_PJC_COST_TYPE WHERE 1=1 " + whrclas + " and COST_TYPE_CODE='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_PJC_COST_TYPE.COST_TYPE_CODE = (select Min(COST_TYPE_CODE) from TSPL_PJC_COST_TYPE where COST_TYPE_CODE>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_PJC_COST_TYPE.COST_TYPE_CODE = (select Max(COST_TYPE_CODE) from TSPL_PJC_COST_TYPE where COST_TYPE_CODE<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsCostType()
            obj.COST_TYPE_CODE = clsCommon.myCstr(dt.Rows(0)("COST_TYPE_CODE"))
            obj.DESCRIPTION = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.DESCRIPTION = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.COST_CLASS = clsCommon.myCstr(dt.Rows(0)("COST_CLASS"))
        End If
        Return obj
    End Function
    Public Shared Function GetCostTypeTable() As DataTable
        Dim DT_CostType As DataTable = New DataTable
        DT_CostType.Columns.Add("Code", GetType(String))
        DT_CostType.Columns.Add("Name", GetType(String))

        Dim DR As DataRow = DT_CostType.NewRow()
        DR("Name") = "Labour"
        DR("Code") = "Labour"
        DT_CostType.Rows.Add(DR)

        DR = DT_CostType.NewRow()
        DR("Name") = "Material"
        DR("Code") = "Material"
        DT_CostType.Rows.Add(DR)

        DR = DT_CostType.NewRow()
        DR("Name") = "Equipment"
        DR("Code") = "Equipment"
        DT_CostType.Rows.Add(DR)

        DR = DT_CostType.NewRow()
        DR("Name") = "SubContractor"
        DR("Code") = "SubContractor"
        DT_CostType.Rows.Add(DR)

        DR = DT_CostType.NewRow()
        DR("Name") = "Overhead"
        DR("Code") = "Overhead"
        DT_CostType.Rows.Add(DR)

        DR = DT_CostType.NewRow()
        DR("Name") = "Miscellaneous"
        DR("Code") = "Miscellaneous"
        DT_CostType.Rows.Add(DR)

        DT_CostType.AcceptChanges()

        Return DT_CostType
    End Function

    Public Shared Function CheckCostType(ByVal CostTypeCode As String, Optional ByVal trans As SqlTransaction = Nothing) As Boolean
        Dim strq As String
        strq = "select COST_TYPE_CODE from TSPL_PJC_COST_TYPE where COST_TYPE_CODE='" & CostTypeCode & "'"
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(strq, trans)
        If dt.Rows.Count > 0 Then
            Return True
        Else
            Return False
        End If
    End Function
#End Region

End Class
