Imports System.Data.SqlClient
Imports common
Public Class clsPJCAccountSet
#Region "variables"
    Public ACCOUNT_SET_CODE As String = Nothing
    Public DESCRIPTION As String = Nothing
    Public GL_WIP As String = Nothing
    Public GL_SALES_COST As String = Nothing
    Public GL_BILLINGS As String = Nothing
    Public GL_REVENUE As String = Nothing
    Public GL_PAYROLL_EXPENSE As String = Nothing
    Public GL_EMPLOYEE_EXPENSE As String = Nothing
    Public GL_LABOR As String = Nothing
    Public GL_OVERHEAD As String = Nothing
    Public GL_EQUIPMENT As String = Nothing
    Public GL_COST As String = Nothing

    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing
#End Region
#Region "Functions"
    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_PJC_ACCOUNTSETS.ACCOUNT_SET_CODE as [Code] ,TSPL_PJC_ACCOUNTSETS.DESCRIPTION as [Description] ,TSPL_PJC_ACCOUNTSETS.GL_WIP as [GL Wip] ,TSPL_PJC_ACCOUNTSETS.GL_SALES_COST as [GL Sales Cost] ,TSPL_PJC_ACCOUNTSETS.GL_BILLINGS as [GL Billings] ,TSPL_PJC_ACCOUNTSETS.GL_REVENUE as [GL Revenue] ,TSPL_PJC_ACCOUNTSETS.GL_PAYROLL_EXPENSE as [GL Payroll Expense] ,TSPL_PJC_ACCOUNTSETS.GL_EMPLOYEE_EXPENSE as [GL Employee Expense] ,TSPL_PJC_ACCOUNTSETS.GL_LABOR as [GL Labor] ,TSPL_PJC_ACCOUNTSETS.GL_OVERHEAD as [GL Overhead] ,TSPL_PJC_ACCOUNTSETS.GL_EQUIPMENT as [GL Equipment] ,TSPL_PJC_ACCOUNTSETS.GL_COST as [GL Cost] ,TSPL_PJC_ACCOUNTSETS.Created_By as [Created By] ,TSPL_PJC_ACCOUNTSETS.Created_Date as [Created Date] ,TSPL_PJC_ACCOUNTSETS.Modified_By as [Modified By] ,TSPL_PJC_ACCOUNTSETS.Modified_Date as [Modified Date]  From TSPL_PJC_ACCOUNTSETS   "
        str = clsCommon.ShowSelectForm("PJCACSET", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function SaveData(ByVal obj As clsPJCAccountSet, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "comp_code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "DESCRIPTION", obj.DESCRIPTION)

            If obj.GL_WIP <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_WIP", obj.GL_WIP)
            End If
            If obj.GL_SALES_COST <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_SALES_COST", obj.GL_SALES_COST)
            End If
            If obj.GL_BILLINGS <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_BILLINGS", obj.GL_BILLINGS)
            End If
            If obj.GL_REVENUE <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_REVENUE", obj.GL_REVENUE)
            End If
            If obj.GL_PAYROLL_EXPENSE <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_PAYROLL_EXPENSE", obj.GL_PAYROLL_EXPENSE)
            End If
            If obj.GL_EMPLOYEE_EXPENSE <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_EMPLOYEE_EXPENSE", obj.GL_EMPLOYEE_EXPENSE)
            End If
            If obj.GL_LABOR <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_LABOR", obj.GL_LABOR)
            End If
            If obj.GL_OVERHEAD <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_OVERHEAD", obj.GL_OVERHEAD)
            End If
            If obj.GL_EQUIPMENT <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_EQUIPMENT", obj.GL_EQUIPMENT)
            End If
            If obj.GL_COST <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_COST", obj.GL_COST)
            End If

            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_PJC_ACCOUNTSETS where ACCOUNT_SET_CODE='" & obj.ACCOUNT_SET_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.ACCOUNT_SET_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.PJCAccountSet, "", "")
                        If clsCommon.myLen(obj.ACCOUNT_SET_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "ACCOUNT_SET_CODE", obj.ACCOUNT_SET_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PJC_ACCOUNTSETS", OMInsertOrUpdate.Insert, "", trans)
            Else

                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PJC_ACCOUNTSETS", OMInsertOrUpdate.Update, "TSPL_PJC_ACCOUNTSETS.ACCOUNT_SET_CODE='" + obj.ACCOUNT_SET_CODE + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsPJCAccountSet
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsPJCAccountSet
        Dim obj As clsPJCAccountSet = Nothing
        Dim Arr As List(Of clsPJCAccountSet) = Nothing
        Dim qry As String = "select ACCOUNT_SET_CODE ,DESCRIPTION ,GL_WIP,GL_SALES_COST ,GL_BILLINGS ,GL_REVENUE ,GL_PAYROLL_EXPENSE ,GL_EMPLOYEE_EXPENSE ,GL_LABOR,GL_OVERHEAD,GL_EQUIPMENT,GL_COST from TSPL_PJC_ACCOUNTSETS where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_PJC_ACCOUNTSETS.ACCOUNT_SET_CODE = (select MIN(ACCOUNT_SET_CODE) from TSPL_PJC_ACCOUNTSETS WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_PJC_ACCOUNTSETS.ACCOUNT_SET_CODE = (select Max(ACCOUNT_SET_CODE) from TSPL_PJC_ACCOUNTSETS WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_PJC_ACCOUNTSETS.ACCOUNT_SET_CODE = (select top 1 ACCOUNT_SET_CODE from TSPL_PJC_ACCOUNTSETS WHERE 1=1 " + whrclas + " and ACCOUNT_SET_CODE='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_PJC_ACCOUNTSETS.ACCOUNT_SET_CODE = (select Min(ACCOUNT_SET_CODE) from TSPL_PJC_ACCOUNTSETS where ACCOUNT_SET_CODE>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_PJC_ACCOUNTSETS.ACCOUNT_SET_CODE = (select Max(ACCOUNT_SET_CODE) from TSPL_PJC_ACCOUNTSETS where ACCOUNT_SET_CODE<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsPJCAccountSet()
            obj.ACCOUNT_SET_CODE = clsCommon.myCstr(dt.Rows(0)("ACCOUNT_SET_CODE"))
            obj.DESCRIPTION = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.GL_EMPLOYEE_EXPENSE = clsCommon.myCstr(dt.Rows(0)("GL_EMPLOYEE_EXPENSE"))
            obj.GL_PAYROLL_EXPENSE = clsCommon.myCstr(dt.Rows(0)("GL_PAYROLL_EXPENSE"))
            obj.GL_LABOR = clsCommon.myCstr(dt.Rows(0)("GL_LABOR"))
            obj.GL_BILLINGS = clsCommon.myCstr(dt.Rows(0)("GL_BILLINGS"))
            obj.GL_SALES_COST = clsCommon.myCstr(dt.Rows(0)("GL_SALES_COST"))
            obj.GL_REVENUE = clsCommon.myCstr(dt.Rows(0)("GL_REVENUE"))
            obj.GL_WIP = clsCommon.myCstr(dt.Rows(0)("GL_WIP"))
            obj.GL_OVERHEAD = clsCommon.myCstr(dt.Rows(0)("GL_OVERHEAD"))
            obj.GL_EQUIPMENT = clsCommon.myCstr(dt.Rows(0)("GL_EQUIPMENT"))
            obj.GL_COST = clsCommon.myCstr(dt.Rows(0)("GL_COST"))

        End If
        Return obj
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isDelete As Boolean
        Try
            isDelete = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_PJC_ACCOUNTSETS where ACCOUNT_SET_CODE ='" + strCode + "'"
            isDelete = clsDBFuncationality.ExecuteNonQuery(qry)
        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isDelete
    End Function
    Public Shared Function checkGLAccount(ByVal AccountCode As String, Optional ByVal Trans As SqlTransaction = Nothing) As Boolean
        Dim strq As String
        strq = "select Account_Code from TSPL_GL_ACCOUNTS where Account_Code='" & AccountCode & "'"
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(strq, Trans)
        If dt.Rows.Count > 0 Then
            Return True
        Else
            Return False
        End If
    End Function
#End Region
End Class
