Imports System.Data.SqlClient
Imports common
Public Class clsPJCSettings
#Region "variables"
    Public SETTING_CODE As String = ""
    Public LEVEL As String = ""
    Public AUTO_TASK_CREATE As Boolean
    Public BANK_CODE As String = ""
    Public BANK_NAME As String = ""
    Public Created_By As String = ""
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = ""
    Public Modified_Date As Date? = Nothing

#End Region
#Region "Functions"

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_PJC_SETTINGS.SETTING_CODE as [Code] ,TSPL_PJC_SETTINGS.LEVEL as [Level] ,TSPL_PJC_SETTINGS.AUTO_TASK_CREATE as [Auto Task Create] ,TSPL_PJC_SETTINGS.BANK_CODE as [Bank Code] ,TSPL_PJC_SETTINGS.Created_By as [Created By] ,TSPL_PJC_SETTINGS.Created_Date as [Created Date] ,TSPL_PJC_SETTINGS.Modified_By as [Modified By] ,TSPL_PJC_SETTINGS.Modified_Date as [Modified Date]  From TSPL_PJC_SETTINGS  "
        str = clsCommon.ShowSelectForm("PJCSETFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function SaveData(ByVal obj As clsPJCSettings, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""

        Try
            
            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "LEVEL", obj.LEVEL)
            clsCommon.AddColumnsForChange(coll, "BANK_CODE", obj.BANK_CODE, True)
            clsCommon.AddColumnsForChange(coll, "AUTO_TASK_CREATE", obj.AUTO_TASK_CREATE)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_PJC_SETTINGS where SETTING_CODE='" & obj.SETTING_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.SETTING_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.PJCSetting, "", "")
                        If clsCommon.myLen(obj.SETTING_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "SETTING_CODE", obj.SETTING_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PJC_SETTINGS", OMInsertOrUpdate.Insert, "", trans)
            Else
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PJC_SETTINGS", OMInsertOrUpdate.Update, "TSPL_PJC_SETTINGS.SETTING_CODE='" + obj.SETTING_CODE + "'", trans)
            End If

        Catch err As Exception

            Throw New Exception(err.Message)
        End Try
        Return True
    End Function


    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsPJCSettings
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsPJCSettings
        Dim obj As clsPJCSettings = Nothing
        Dim Arr As List(Of clsPJCSettings) = Nothing
        Dim qry As String = "select TSPL_PJC_SETTINGS.SETTING_CODE ,TSPL_PJC_SETTINGS.LEVEL,TSPL_PJC_SETTINGS.AUTO_TASK_CREATE,TSPL_PJC_SETTINGS.BANK_CODE,TSPL_BANK_MASTER.description from TSPL_PJC_SETTINGS left join TSPL_BANK_MASTER on TSPL_PJC_SETTINGS.bank_code=TSPL_BANK_MASTER.bank_code where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_PJC_SETTINGS.SETTING_CODE = (select MIN(SETTING_CODE) from TSPL_PJC_SETTINGS WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_PJC_SETTINGS.SETTING_CODE = (select Max(SETTING_CODE) from TSPL_PJC_SETTINGS WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_PJC_SETTINGS.SETTING_CODE = (select top 1 SETTING_CODE from TSPL_PJC_SETTINGS WHERE 1=1 " + whrclas + " and SETTING_CODE='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_PJC_SETTINGS.SETTING_CODE = (select Min(SETTING_CODE) from TSPL_PJC_SETTINGS where SETTING_CODE>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_PJC_SETTINGS.SETTING_CODE = (select Max(SETTING_CODE) from TSPL_PJC_SETTINGS where SETTING_CODE<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsPJCSettings()
            obj.SETTING_CODE = clsCommon.myCstr(dt.Rows(0)("SETTING_CODE"))
            obj.LEVEL = clsCommon.myCstr(dt.Rows(0)("LEVEL"))
            obj.AUTO_TASK_CREATE = clsCommon.myCstr(dt.Rows(0)("AUTO_TASK_CREATE"))
            obj.BANK_CODE = clsCommon.myCstr(dt.Rows(0)("BANK_CODE"))
            obj.BANK_NAME = clsCommon.myCstr(dt.Rows(0)("description"))
        End If
        Return obj
    End Function
    Public Shared Function GetLevelsTable() As DataTable
        Dim DT_Level As DataTable = New DataTable
        DT_Level.Columns.Add("Code", GetType(String))
        DT_Level.Columns.Add("Name", GetType(String))

        Dim DR As DataRow = DT_Level.NewRow()
        DR("Name") = "Level1"
        DR("Code") = "Level1"
        DT_Level.Rows.Add(DR)

        DR = DT_Level.NewRow()
        DR("Name") = "Level2"
        DR("Code") = "Level2"
        DT_Level.Rows.Add(DR)

        DR = DT_Level.NewRow()
        DR("Name") = "Level3"
        DR("Code") = "Level3"
        DT_Level.Rows.Add(DR)

        Return DT_Level
    End Function


#End Region

End Class
