Imports common
Imports System.Data
Imports System.Data.SqlClient

Public Class ClsHirerachyLevelMaster
#Region "Variables"
    Public HIRERACHY_CODE As String = Nothing
    Public Description As String = Nothing
    Public Level As String = Nothing
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "select TSPL_HIRERACHY_LEVEL_MASTER.HIRERACHY_CODE as [Code] ,TSPL_HIRERACHY_LEVEL_MASTER.Description as [Description],TSPL_HIRERACHY_LEVEL_MASTER.Level as [Level] ,TSPL_HIRERACHY_LEVEL_MASTER.Created_By as [Created By] ,CONVERT(VARCHAR,TSPL_HIRERACHY_LEVEL_MASTER.Created_Date,103) as [Created Date] ,TSPL_HIRERACHY_LEVEL_MASTER.Modified_By as [Modified By] ,CONVERT(VARCHAR,TSPL_HIRERACHY_LEVEL_MASTER.Modified_Date,103) as [Modified Date]  From TSPL_HIRERACHY_LEVEL_MASTER  "
        str = clsCommon.ShowSelectForm("HIRCFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    Public Shared Function GetName(ByVal HCode As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "SELECT Description FROM TSPL_HIRERACHY_LEVEL_MASTER where HIRERACHY_CODE= '" & HCode & "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function SaveData(ByVal obj As ClsHirerachyLevelMaster, ByVal strCode As String) As Boolean
        Try
            Dim issaved As Boolean = True
            'Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
            Dim coll As New Hashtable()

            Dim qry As String = "SELECT Count(*) FROM TSPL_HIRERACHY_LEVEL_MASTER where HIRERACHY_CODE= '" & obj.HIRERACHY_CODE & "'"
            Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
            If check > 0 Then
                'qry = "delete from TSPL_HIRERACHY_LEVEL_MASTER where HIRERACHY_CODE='" + obj.HIRERACHY_CODE + "'"
                'clsDBFuncationality.ExecuteNonQuery(qry)
            End If

            clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
            clsCommon.AddColumnsForChange(coll, "Level", obj.Level)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)

            If check = 0 Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    obj.HIRERACHY_CODE = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.HirerachyLevelMaster, "", "")
                End If
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy hh:mm tt"))
                clsCommon.AddColumnsForChange(coll, "HIRERACHY_CODE", obj.HIRERACHY_CODE)
                issaved = issaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_HIRERACHY_LEVEL_MASTER", OMInsertOrUpdate.Insert, "")
            Else
                issaved = issaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_HIRERACHY_LEVEL_MASTER", OMInsertOrUpdate.Update, "HIRERACHY_CODE='" + obj.HIRERACHY_CODE + "'")
            End If

            Return True
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsHirerachyLevelMaster
        Try
            Dim obj As ClsHirerachyLevelMaster = Nothing
            Dim qry As String = "select * from TSPL_HIRERACHY_LEVEL_MASTER where 2=2"
            Select Case NavType
                Case NavigatorType.First
                    qry += " and HIRERACHY_CODE = (select MIN(HIRERACHY_CODE) from TSPL_HIRERACHY_LEVEL_MASTER)"
                Case NavigatorType.Last
                    qry += " and HIRERACHY_CODE = (select Max(HIRERACHY_CODE) from TSPL_HIRERACHY_LEVEL_MASTER)"
                Case NavigatorType.Next
                    qry += " and HIRERACHY_CODE = (select Min(HIRERACHY_CODE) from TSPL_HIRERACHY_LEVEL_MASTER where  HIRERACHY_CODE>'" + strCode + "')"
                Case NavigatorType.Previous
                    qry += " and HIRERACHY_CODE = (select Max(HIRERACHY_CODE) from TSPL_HIRERACHY_LEVEL_MASTER where HIRERACHY_CODE<'" + strCode + "')"
                Case NavigatorType.Current
                    qry += " and HIRERACHY_CODE = '" + strCode + "'"

            End Select
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)

            If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
                obj = New ClsHirerachyLevelMaster()
                obj.HIRERACHY_CODE = clsCommon.myCstr(dt.Rows(0)("HIRERACHY_CODE"))
                obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
                obj.Level = clsCommon.myCstr(dt.Rows(0)("Level"))
            End If
            Return obj
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isSaved As Boolean

        Try
            isSaved = False
            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_HIRERACHY_LEVEL_MASTER where HIRERACHY_CODE ='" + strCode + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry)

        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isSaved
    End Function
End Class
