Imports System.Data.SqlClient
Imports common

Public Class ClsRequisitSubTypeMaster

#Region "Variables"
    Public Code As String = Nothing
    Public Description As String = Nothing
    Public Type As String = Nothing
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_Requisit_SubType_Master.Code as [Code] ,TSPL_Requisit_SubType_Master.DESCRIPTION as [Description] ,TSPL_Requisit_SubType_Master.Type as [Type]  From TSPL_Requisit_SubType_Master  "
        str = clsCommon.ShowSelectForm("REQSUBTYPEMS", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Function SaveData(ByVal obj As ClsRequisitSubTypeMaster, ByVal isNewEntry As Boolean) As Boolean
        Dim trans As SqlTransaction = Nothing
        Try
            trans = clsDBFuncationality.GetTransactin()
            If SaveData(obj, trans, isNewEntry) Then
                trans.Commit()
            End If
        Catch ex As Exception
            trans.Rollback()
            Throw New Exception(ex.Message)
        End Try
        Return True
    End Function

    Public Function SaveData(ByVal obj As ClsRequisitSubTypeMaster, ByVal trans As SqlTransaction, ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "comp_code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
            clsCommon.AddColumnsForChange(coll, "Type", obj.Type)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_Requisit_SubType_Master where Code='" & obj.Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.RequisitSubTypeMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_Requisit_SubType_Master", OMInsertOrUpdate.Insert, "", trans)
            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_Requisit_SubType_Master", OMInsertOrUpdate.Update, "code='" + obj.Code + "'", trans)

            End If
        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return isSaved
    End Function


    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As common.NavigatorType) As ClsRequisitSubTypeMaster
        Dim obj As ClsRequisitSubTypeMaster = Nothing
        Dim qry As String = "SELECT code,description,type from TSPL_Requisit_SubType_Master where  2=2"

        Select Case NavType
            Case NavigatorType.First
                qry += " and code=(select MIN(code) from TSPL_Requisit_SubType_Master Where 1=1 )"
            Case NavigatorType.Last
                qry += " and code=(select Max(code) from TSPL_Requisit_SubType_Master Where 1=1 )"
            Case NavigatorType.Next
                qry += " and code=(select Min(code) from TSPL_Requisit_SubType_Master where code > '" + strCode + "' )"
            Case NavigatorType.Previous
                qry += " and code=(select Max(code) from TSPL_Requisit_SubType_Master where code < '" + strCode + "' )"
            Case NavigatorType.Current
                qry += " and code='" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsRequisitSubTypeMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("description"))
            obj.Type = clsCommon.myCstr(dt.Rows(0)("type"))
        End If
        Return obj
    End Function


    Public Shared Function DeleteData(ByVal code As String) As Boolean

        Try
            clsDBFuncationality.ExecuteNonQuery("Delete From TSPL_Requisit_SubType_Master where code='" + code + "'")

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return True
    End Function
End Class
