Imports System.Data.SqlClient
Imports common
Public Class clsTaskMaster
#Region "variables"
    Public TASK_CODE As String = ""
    Public DESCRIPTION As String = ""
    Public UNIT_CODE As String = ""
    Public UNIT_DESC As String = ""
    Public BILLING_RATE As Decimal
    Public UNIT_COST As Decimal
    Public TASK_TYPE As String = ""
    Public COST_TYPE_CODE As String = ""
    Public COST_TYPE_DESC As String = ""
    Public JOB_CODE As String = ""

    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing

    Public Form_ID As String = ""
    Public arrCustomFields As List(Of clsCustomFieldValues) = Nothing

#End Region
#Region "Functions"

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_PJC_TASK.TASK_CODE as [Code] ,TSPL_PJC_TASK.DESCRIPTION as [Description] ,TSPL_PJC_TASK.UNIT_CODE as [Unit Code] ,TSPL_PJC_TASK.BILLING_RATE as [Billing Rate] ,TSPL_PJC_TASK.UNIT_COST as [Unit Cost] ,TSPL_PJC_TASK.COST_TYPE_CODE as [Cost Type Code] ,TSPL_PJC_TASK.TASK_TYPE as [Task Type] ,TSPL_PJC_TASK.JOB_CODE as [Job Code] ,TSPL_PJC_TASK.Created_By as [Created By] ,TSPL_PJC_TASK.Created_Date as [Created Date] ,TSPL_PJC_TASK.Modified_By as [Modified By] ,TSPL_PJC_TASK.Modified_Date as [Modified Date]  From TSPL_PJC_TASK   "
        str = clsCommon.ShowSelectForm("TSKMSTFND", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function SaveData(ByVal obj As clsTaskMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""

        Try

            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "Description", obj.DESCRIPTION)
            clsCommon.AddColumnsForChange(coll, "UNIT_CODE", obj.UNIT_CODE, True)
            clsCommon.AddColumnsForChange(coll, "BILLING_RATE", obj.BILLING_RATE)
            clsCommon.AddColumnsForChange(coll, "UNIT_COST", obj.UNIT_COST)
            clsCommon.AddColumnsForChange(coll, "COST_TYPE_CODE", obj.COST_TYPE_CODE, True)
            clsCommon.AddColumnsForChange(coll, "TASK_TYPE", obj.TASK_TYPE, True)
            clsCommon.AddColumnsForChange(coll, "JOB_CODE", obj.JOB_CODE, True)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_PJC_TASK where TASK_CODE='" & obj.TASK_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.TASK_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.TaskMaster, "", "")
                        If clsCommon.myLen(obj.TASK_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "TASK_CODE", obj.TASK_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PJC_TASK", OMInsertOrUpdate.Insert, "", trans)
            Else
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PJC_TASK", OMInsertOrUpdate.Update, "TSPL_PJC_TASK.TASK_CODE='" + obj.TASK_CODE + "'", trans)
            End If
            clsCustomFieldValues.SaveData(obj.Form_ID, obj.TASK_CODE, obj.arrCustomFields, trans)

        Catch err As Exception

            Throw New Exception(err.Message)
        End Try
        Return True
    End Function


    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsTaskMaster
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsTaskMaster
        Dim obj As clsTaskMaster = Nothing
        Dim Arr As List(Of clsTaskMaster) = Nothing
        Dim qry As String = "select TSPL_PJC_TASK.TASK_CODE ,TSPL_PJC_TASK.DESCRIPTION,TSPL_PJC_TASK.UNIT_CODE,TSPL_PJC_TASK.BILLING_RATE, " & _
        " TSPL_PJC_TASK.UNIT_COST,TSPL_PJC_TASK.COST_TYPE_CODE,TSPL_PJC_TASK.TASK_TYPE,TSPL_PJC_TASK.JOB_CODE, " & _
        " TSPL_PJC_COST_TYPE.DESCRIPTION AS COST_TYPE_DESC,TSPL_UNIT_MASTER.UNIT_DESC from TSPL_PJC_TASK LEFT JOIN TSPL_PJC_COST_TYPE " & _
        " ON TSPL_PJC_TASK.COST_TYPE_CODE=TSPL_PJC_COST_TYPE.COST_TYPE_CODE " & _
        " LEFT JOIN TSPL_UNIT_MASTER ON TSPL_UNIT_MASTER.Unit_Code=TSPL_PJC_TASK.UNIT_CODE where 2=2 "

        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_PJC_TASK.TASK_CODE = (select MIN(TASK_CODE) from TSPL_PJC_TASK WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_PJC_TASK.TASK_CODE = (select Max(TASK_CODE) from TSPL_PJC_TASK WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_PJC_TASK.TASK_CODE = (select top 1 TASK_CODE from TSPL_PJC_TASK WHERE 1=1 " + whrclas + " and TASK_CODE='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_PJC_TASK.TASK_CODE = (select Min(TASK_CODE) from TSPL_PJC_TASK where TASK_CODE>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_PJC_TASK.TASK_CODE = (select Max(TASK_CODE) from TSPL_PJC_TASK where TASK_CODE<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsTaskMaster()
            obj.TASK_CODE = clsCommon.myCstr(dt.Rows(0)("TASK_CODE"))
            obj.DESCRIPTION = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.UNIT_CODE = clsCommon.myCstr(dt.Rows(0)("UNIT_CODE"))
            obj.BILLING_RATE = clsCommon.myCdbl(dt.Rows(0)("BILLING_RATE"))
            obj.UNIT_COST = clsCommon.myCdbl(dt.Rows(0)("UNIT_COST"))
            obj.COST_TYPE_CODE = clsCommon.myCstr(dt.Rows(0)("COST_TYPE_CODE"))
            obj.TASK_TYPE = clsCommon.myCstr(dt.Rows(0)("TASK_TYPE"))
            obj.JOB_CODE = clsCommon.myCstr(dt.Rows(0)("JOB_CODE"))
            obj.COST_TYPE_DESC = clsCommon.myCstr(dt.Rows(0)("COST_TYPE_DESC"))
            obj.UNIT_DESC = clsCommon.myCstr(dt.Rows(0)("UNIT_DESC"))
        End If
        Return obj
    End Function
    Public Shared Function GetTaskTypeTable() As DataTable
        Dim DT_TaskType As DataTable = New DataTable
        DT_TaskType.Columns.Add("Code", GetType(String))
        DT_TaskType.Columns.Add("Name", GetType(String))

        Dim DR As DataRow = DT_TaskType.NewRow()
        DR("Name") = "Internal"
        DR("Code") = "Internal"
        DT_TaskType.Rows.Add(DR)

        DR = DT_TaskType.NewRow()
        DR("Name") = "External"
        DR("Code") = "External"
        DT_TaskType.Rows.Add(DR)

        DT_TaskType.AcceptChanges()

        Return DT_TaskType
    End Function
    Public Shared Function CheckUom(ByVal UnitCode As String, Optional ByVal trans As SqlTransaction = Nothing) As Boolean
        Dim strq As String
        strq = "select unit_code from TSPL_UNIT_MASTER where unit_code='" & UnitCode & "'"
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(strq, trans)
        If dt.Rows.Count > 0 Then
            Return True
        Else
            Return False
        End If
    End Function
    

#End Region

End Class
