Imports common
Imports System.Data.SqlClient

Public Class FrmCostCentreFinancial
    Inherits FrmMainTranScreen
#Region "Variables"
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String
    Const colCostLSelect As String = "SELECT"
    Const COST_CENTRE_HIRERACHY_CODE As String = "COST_CENTRE_HIRERACHY_CODE"
    Const HIRERACHY_LEVEL_CODE1 As String = "HIRERACHY_LEVEL_CODE1"
    Const HIRERACHY_LEVEL_CODE2 As String = "HIRERACHY_LEVEL_CODE2"
    Const HIRERACHY_LEVEL_CODE3 As String = "HIRERACHY_LEVEL_CODE3"

    'Const colCostCentreFCode As String = "CostCentreFCODE"
    'Const colCostCentreFDesc As String = "Description"
    'Const colCostCFLCode As String = "COOSTCENTREFLCODE"
    'Const colCostCFLDesc As String = "FinLDescription"
    'Const colHirerachyCode As String = "HirerchayLCODE"
    'Const colHirerachyDesc As String = "HirerchayLDesc"
    Const colHirerachyLevel As String = "Level"
    Dim EnableHirerachyCostCentre As Double = False
#End Region

    Private Sub txtcostcenter__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtcostcenter._MYValidating
        Dim Qry As String = "select  CostCenter_Code , Description  from TSPL_COST_CENTRE_GROUP_MASTER "
        txtcostcenter.Value = clsCommon.ShowSelectForm("ccgrpfin", Qry, "CostCenter_Code", "", txtcostcenter.Value, "CostCenter_Code", isButtonClicked)
        If clsCommon.myLen(txtcostcenter.Value) > 0 Then
            lblCostDesp.Text = clsDBFuncationality.getSingleValue("Select Description from TSPL_COST_CENTRE_GROUP_MASTER Where CostCenter_Code='" + txtcostcenter.Value + "' ")
        Else
            lblCostDesp.Text = ""
        End If
    End Sub

    Private Sub FrmCostCentreFinancial_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnSave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btnDelete.Enabled Then
            DeleteData()
        ElseIf e.Alt And e.KeyCode = Keys.C Then
            funClose()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            funReset()
        End If
    End Sub

    Private Sub FrmCostCentreFinancial_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        SetUserMgmtNew()
        EnableHirerachyCostCentre = clsCommon.myCdbl(clsFixedParameter.GetData(clsFixedParameterType.EnableHirerachyCostCentre, clsFixedParameterCode.EnableHirerachyCostCentre, Nothing))
        funReset()
        ButtonToolTip.SetToolTip(btnSave, "Press Alt+S for Save/Update Transaction")
        ButtonToolTip.SetToolTip(btnDelete, "Press Alt+D for Delete Transaction")
        ButtonToolTip.SetToolTip(btnClose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(rdbtnreset, "Press Alt+N for New Transaction")
    End Sub
    Private Sub SetUserMgmtNew()
        ''MyBase.SetUserMgmt(clsUserMgtCode.CostCentreFinancial)
        If Not (MyBase.isReadFlag) Then
            Throw New Exception("Permission Denied")

        End If
        btnSave.Visible = MyBase.isModifyFlag

        If btnSave.Visible = True Then
            rmExport.Enabled = True
            rmImport.Enabled = True
        Else
            rmExport.Enabled = False
            rmImport.Enabled = False
        End If

        btnDelete.Visible = MyBase.isDeleteFlag
    End Sub
    Function AllowToSave() As Boolean
        btnSave.Focus()
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(fndCode.Value) <= 0 Then
            myMessages.blankValue("Code")
            fndCode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtdescription.Text) <= 0 Then
            myMessages.blankValue("Description")
            txtdescription.Focus()
            Return False
            '==============update by preeti gupta against ticket no[BM00000009038]
            'ElseIf clsCommon.myLen(txtcostcenter.Value) <= 0 Then
            '    myMessages.blankValue("Cost center group")
            '    txtcostcenter.Focus()
            '    Return False
        ElseIf clsCommon.myLen(TxtHirerachyLevel.Value) <= 0 Then
            myMessages.blankValue("Hirerachy level")
            TxtHirerachyLevel.Focus()
            Return False
        End If
        If clsCommon.myLen(txtcostcenter.Value) > 0 Then
            Dim qry As String = "select count(*) As Row from TSPL_COST_CENTRE_GROUP_MASTER where CostCenter_Code='" + txtcostcenter.Value + "'"
            Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
            If check <= 0 Then
                clsCommon.MyMessageBoxShow("'" & clsCommon.myCstr(txtcostcenter.Value) & "' code does not exists.First create cost centre group stores entry")
                txtcostcenter.Focus()
                Return False
            End If
        End If
        If EnableHirerachyCostCentre = 0 Then
            If clsCommon.myLen(TxtHirerachyLevel.Value) > 0 Then
                If clsCommon.CompairString(LblLevel.Text, "1") <> CompairStringResult.Equal AndAlso clsCommon.myLen(TxtCostCentreLevel.Value) <= 0 Then
                    myMessages.blankValue("Cost centre level")
                    TxtCostCentreLevel.Focus()
                    Return False
                End If
            End If
        Else
            If clsCommon.CompairString(LblLevel.Text, "1") <> CompairStringResult.Equal Then
                Dim Count As Integer = 0
                For ii As Integer = 0 To gv1.RowCount - 1
                    If (clsCommon.myCBool(gv1.Rows(ii).Cells(colCostLSelect).Value)) Then
                        Count += 1
                        Exit For
                    End If
                Next
                If Count = 0 Then
                    clsCommon.MyMessageBoxShow(Me, "Please Select Cost Centre Level", Me.Text)
                    Return False
                End If
            End If
        End If
        Return True
    End Function
    Private Sub DeleteData()
        Try
            If (deleteConfirm()) Then
                If (ClsCostCentreFinancial.DeleteData(fndCode.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Sub funReset()
        If EnableHirerachyCostCentre = 1 Then
            MyLabel2.Visible = False
            TxtCostCentreLevel.Visible = False
            LblCostCentre.Visible = False
            RadGroupBox1.Visible = True
            gv1.Visible = True
            gv1.DataSource = Nothing
        Else
            MyLabel2.Visible = True
            TxtCostCentreLevel.Visible = True
            LblCostCentre.Visible = True
            RadGroupBox1.Visible = False
            gv1.Visible = False
        End If
        isNewEntry = True
        fndCode.MyReadOnly = False
        fndCode.Value = Nothing
        fndCode.Focus()
        txtdescription.Text = ""
        txtcostcenter.Value = ""
        lblCostDesp.Text = ""
        TxtCostCentreLevel.Value = ""
        LblCostCentre.Text = ""
        TxtHirerachyLevel.Value = ""
        LblHirerachy.Text = ""
        LblLevel.Text = ""
        btnSave.Text = "Save"
        btnSave.Enabled = True
        btnDelete.Enabled = False
        LoadBlankGridDetail()
    End Sub
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        LoadBlankGridDetail()
        Dim obj As New ClsCostCentreFinancial()
        obj = ClsCostCentreFinancial.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Cost_Center_Fin_Code) > 0) Then
            funReset()
            isNewEntry = False
            btnSave.Text = "Update"
            fndCode.Value = obj.Cost_Center_Fin_Code
            txtdescription.Text = obj.Cost_Center_Fin_Name
            txtcostcenter.Value = obj.Cost_Center_Group
            If clsCommon.myLen(txtcostcenter.Value) > 0 Then
                lblCostDesp.Text = clsDBFuncationality.getSingleValue("select Description from TSPL_COST_CENTRE_GROUP_MASTER where CostCenter_Code='" + clsCommon.myCstr(txtcostcenter.Value) + "'")
            Else
                lblCostDesp.Text = ""
            End If
            TxtHirerachyLevel.Value = obj.Hirerachy_Level_Code
            If clsCommon.myLen(TxtHirerachyLevel.Value) > 0 Then
                LblHirerachy.Text = clsDBFuncationality.getSingleValue("select ISNULL( Description,'') AS Description from TSPL_HIRERACHY_LEVEL_MASTER where Hirerachy_Code='" + clsCommon.myCstr(TxtHirerachyLevel.Value) + "'")
                LblLevel.Text = clsDBFuncationality.getSingleValue("select ISNULL(Level,'') AS Level from TSPL_HIRERACHY_LEVEL_MASTER where Hirerachy_Code='" + clsCommon.myCstr(TxtHirerachyLevel.Value) + "'")
            Else
                LblHirerachy.Text = ""
                LblLevel.Text = ""
            End If
            If EnableHirerachyCostCentre = 0 Then
                TxtCostCentreLevel.Value = obj.Cost_Centre_Fin_Level_Code
                If clsCommon.myLen(TxtCostCentreLevel.Value) > 0 Then
                    LblCostCentre.Text = clsDBFuncationality.getSingleValue("select Cost_Center_Fin_Name from TSPL_COST_CENTRE_FINANCIAL where Cost_Center_Fin_Code='" + clsCommon.myCstr(TxtCostCentreLevel.Value) + "'")
                Else
                    LblCostCentre.Text = ""
                End If
            Else
                If obj.Arr IsNot Nothing AndAlso obj.Arr.Count > 0 Then
                    For Each objTr As ClsCostCentreFinancialDetail In obj.Arr
                        If clsCommon.myLen(clsCommon.myCstr(objTr.COST_CENTRE_HIRERACHY_CODE)) > 0 Then

                            gv1.Rows.AddNew()
                            gv1.Rows(gv1.Rows.Count - 1).Cells(colCostLSelect).Value = objTr.FLAG
                            gv1.Rows(gv1.Rows.Count - 1).Cells(COST_CENTRE_HIRERACHY_CODE).Value = clsCommon.myCstr(objTr.COST_CENTRE_HIRERACHY_CODE)
                            gv1.Rows(gv1.Rows.Count - 1).Cells(HIRERACHY_LEVEL_CODE1).Value = clsCommon.myCstr(objTr.HIRERACHY_LEVEL_CODE1)
                            gv1.Rows(gv1.Rows.Count - 1).Cells(HIRERACHY_LEVEL_CODE2).Value = clsCommon.myCstr(objTr.HIRERACHY_LEVEL_CODE2)
                            gv1.Rows(gv1.Rows.Count - 1).Cells(HIRERACHY_LEVEL_CODE3).Value = clsCommon.myCstr(objTr.HIRERACHY_LEVEL_CODE3)
                            gv1.Rows(gv1.Rows.Count - 1).Cells(colHirerachyLevel).Value = clsCommon.myCstr(objTr.HIRERACHY_LEVEL)

                        End If
                    Next
                End If
            End If
            btnSave.Enabled = True
            btnDelete.Enabled = True
            fndCode.MyReadOnly = True
            RefreshHeaderText()
        End If

    End Sub
    Public Sub SaveData()
        If AllowToSave() Then
            Dim obj As New ClsCostCentreFinancial()
            obj.Cost_Center_Fin_Code = fndCode.Value
            obj.Cost_Center_Fin_Name = txtdescription.Text
            obj.Cost_Center_Group = txtcostcenter.Value
            obj.Hirerachy_Level_Code = TxtHirerachyLevel.Value
            obj.Hirerachy_Level = LblLevel.Text
            obj.EnableHirerachyCostCentre = EnableHirerachyCostCentre
            If EnableHirerachyCostCentre = 0 Then
                obj.Cost_Centre_Fin_Level_Code = TxtCostCentreLevel.Value
            Else
                If clsCommon.CompairString(LblLevel.Text, "1") = CompairStringResult.Equal Then
                    obj.Arr = New List(Of ClsCostCentreFinancialDetail)
                    Dim objTr As New ClsCostCentreFinancialDetail()
                    objTr.COST_CENTRE_HIRERACHY_CODE = ""
                    objTr.HIRERACHY_LEVEL_CODE1 = ""
                    objTr.HIRERACHY_LEVEL_CODE2 = ""
                    objTr.HIRERACHY_LEVEL_CODE3 = ""
                    objTr.HIRERACHY_LEVEL = clsCommon.myCstr(LblLevel.Text)
                    obj.Arr.Add(objTr)
                Else
                    obj.Arr = New List(Of ClsCostCentreFinancialDetail)
                    For ii As Integer = 0 To gv1.RowCount - 1
                        Dim objTr As New ClsCostCentreFinancialDetail()
                        If (clsCommon.myCBool(gv1.Rows(ii).Cells(colCostLSelect).Value)) Then

                            If clsCommon.CompairString(clsCommon.myCstr(LblLevel.Text), "2") = CompairStringResult.Equal Then
                                objTr.HIRERACHY_LEVEL_CODE1 = clsCommon.myCstr(gv1.Rows(ii).Cells(COST_CENTRE_HIRERACHY_CODE).Value)
                            End If
                            If clsCommon.CompairString(clsCommon.myCstr(LblLevel.Text), "3") = CompairStringResult.Equal Then
                                objTr.HIRERACHY_LEVEL_CODE1 = clsCommon.myCstr(gv1.Rows(ii).Cells(HIRERACHY_LEVEL_CODE1).Value)
                                objTr.HIRERACHY_LEVEL_CODE2 = clsCommon.myCstr(gv1.Rows(ii).Cells(COST_CENTRE_HIRERACHY_CODE).Value)
                            End If
                            If clsCommon.CompairString(clsCommon.myCstr(LblLevel.Text), "4") = CompairStringResult.Equal Then
                                objTr.HIRERACHY_LEVEL_CODE1 = clsCommon.myCstr(gv1.Rows(ii).Cells(HIRERACHY_LEVEL_CODE1).Value)
                                objTr.HIRERACHY_LEVEL_CODE2 = clsCommon.myCstr(gv1.Rows(ii).Cells(HIRERACHY_LEVEL_CODE2).Value)
                                objTr.HIRERACHY_LEVEL_CODE3 = clsCommon.myCstr(gv1.Rows(ii).Cells(COST_CENTRE_HIRERACHY_CODE).Value)
                            End If
                            objTr.HIRERACHY_LEVEL = clsCommon.myCstr(LblLevel.Text)

                            obj.Arr.Add(objTr)
                        End If
                    Next
                End If
            End If
            If (ClsCostCentreFinancial.SaveData(obj, isNewEntry)) Then
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                LoadData(obj.Cost_Center_Fin_Code, NavigatorType.Current)
            End If

        End If
    End Sub
    Sub funClose()
        Me.Close()
        GC.Collect()
    End Sub
    Private Sub rmImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        Dim IsLevel As Boolean = False
        If transportSql.importExcel(gv, "Cost Center Fin Code", "Cost Center Fin Name", "Hirerachy Level Code", "Hirerachy Level", "Cost Centre Level") Then
            Dim linno As Integer = 0
            Dim trans As SqlTransaction = Nothing
            Try
                clsCommon.ProgressBarPercentShow()
                trans = clsDBFuncationality.GetTransactin()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New ClsCostCentreFinancial()
                    linno += 1
                    Dim strCode As String = clsCommon.myCstr(grow.Cells("Cost Center Fin Code").Value)
                    If strCode.Length <= 0 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception("Cost Center Fin Code can not be blank at line no. " + clsCommon.myCstr(linno) + ".")
                    ElseIf strCode.Length > 30 Then
                        Throw New Exception("Cost Center Fin Code length can not be more than 30 at line no. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Cost_Center_Fin_Code = strCode

                    Dim strName As String = clsCommon.myCstr(grow.Cells("Cost Center Fin Name").Value)
                    If strName.Length <= 0 Or (String.IsNullOrEmpty(strName)) Then
                        Throw New Exception("Cost Center Fin Name can not be blank at line no. " + clsCommon.myCstr(linno) + ".")
                    ElseIf strName.Length > 100 Then
                        Throw New Exception("Cost Center Fin Name length can not be more than 100 at line no. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.Cost_Center_Fin_Name = strName

                    'Dim strCostCentreGrp As String = clsCommon.myCstr(grow.Cells("Cost Center Group").Value)
                    'If strCostCentreGrp.Length <= 0 Or (String.IsNullOrEmpty(strCostCentreGrp)) Then
                    '    Throw New Exception("Cost Centre Group can not be blank at line no. " + clsCommon.myCstr(linno) + ".")
                    'End If
                    'If clsCommon.myLen(strCostCentreGrp) > 0 Then
                    '    Dim qry As String = "select count(*) As Row from TSPL_COST_CENTRE_GROUP_MASTER where CostCenter_Code='" + strCostCentreGrp + "'"
                    '    Dim check As Integer = clsDBFuncationality.getSingleValue(qry, trans)
                    '    If check <= 0 Then
                    '        Throw New Exception("'" & clsCommon.myCstr(strCostCentreGrp) & "' code does not exists at line no. " + clsCommon.myCstr(linno) + ".First create cost centre group stores entry")
                    '    End If
                    'End If
                    'obj.Cost_Center_Group = strCostCentreGrp.ToUpper()

                    '' Anubhooti 02-Apr-2015
                    Dim strHirerachyCode As String = clsCommon.myCstr(grow.Cells("Hirerachy Level Code").Value)
                    If clsCommon.myLen(strHirerachyCode) > 0 Then
                        Dim qry As String = "select count(*) As Row from TSPL_HIRERACHY_LEVEL_MASTER where Hirerachy_Code='" + strHirerachyCode + "'"
                        Dim check As Integer = clsDBFuncationality.getSingleValue(qry, trans)
                        If check <= 0 Then
                            Throw New Exception("'" & clsCommon.myCstr(strHirerachyCode) & "' code does not exists at line no. " + clsCommon.myCstr(linno) + ".First create hirerachy level entry")
                        End If
                    Else
                        Throw New Exception("Please fill hirerachy level at line no. " + clsCommon.myCstr(linno))
                    End If
                    obj.Hirerachy_Level_Code = strHirerachyCode
                    obj.Hirerachy_Level = clsCommon.myCstr(clsDBFuncationality.getSingleValue("SELECT ISNULL(Level,'') AS HLevel FROM TSPL_HIRERACHY_LEVEL_MASTER WHERE Hirerachy_Code ='" + strHirerachyCode + "'", trans))

                    If clsCommon.CompairString(obj.Hirerachy_Level, "1") <> CompairStringResult.Equal Then
                        Dim strCostCentreLevelCode As String = clsCommon.myCstr(grow.Cells("Cost Centre Level").Value)
                        If clsCommon.myLen(strCostCentreLevelCode) > 0 Then
                            Dim qry As String = "select count(*) As Row from TSPL_COST_CENTRE_FINANCIAL where Cost_Center_Fin_Code='" + strCostCentreLevelCode + "'"
                            Dim check As Integer = clsDBFuncationality.getSingleValue(qry, trans)
                            If check <= 0 Then
                                Throw New Exception("'" & clsCommon.myCstr(strCostCentreLevelCode) & "' code does not exists at line no. " + clsCommon.myCstr(linno) + ".First create cost centre financial entry")
                            End If
                            Dim Levelqry As String = "select Cost_Center_Fin_Code from TSPL_COST_CENTRE_FINANCIAL where Hirerachy_Level='" + clsCommon.myCstr(clsCommon.myCdbl(obj.Hirerachy_Level - 1)) + "' AND Cost_Center_Fin_Code <> '" + clsCommon.myCstr(strCode) + "'"
                            ' Dim XLLevel As String = clsDBFuncationality.getSingleValue(Levelqry, trans)
                            Dim dt As DataTable = clsDBFuncationality.GetDataTable(Levelqry, trans)

                            If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                                For Each dr As DataRow In dt.Rows
                                    If clsCommon.CompairString(clsCommon.myCstr(dr("Cost_Center_Fin_Code")), strCostCentreLevelCode) = CompairStringResult.Equal Then
                                        IsLevel = True
                                    End If
                                Next
                            End If
                            If IsLevel = False Then
                                Throw New Exception("Please map cost centre level according to hirerachy at line no. " + clsCommon.myCstr(linno))
                            End If
                        Else
                            If clsCommon.CompairString(obj.Hirerachy_Level, "1") <> CompairStringResult.Equal Then
                                Throw New Exception("Please fill cost centre level at line no. " + clsCommon.myCstr(linno))
                            End If
                        End If
                        obj.Cost_Centre_Fin_Level_Code = strCostCentreLevelCode
                    End If
                    ''
                    isNewEntry = ClsCostCentreFinancial.CheckNewEntry(obj.Cost_Center_Fin_Code, trans)

                    ClsCostCentreFinancial.SaveData(obj, isNewEntry, trans)

                    ''==================Sanjeet(For Detail Section Insert)==============
                    'If EnableHirerachyCostCentre = 1 Then
                    '    Dim qry1 As String = "DELETE FROM TSPL_COST_CENTRE_HIRERACHY_DETAIL WHERE COST_CENTRE_HIRERACHY_CODE='" + obj.Cost_Center_Fin_Code + "' and Cost_Center_Fin_Level_Code='" + obj.Cost_Centre_Fin_Level_Code + "'"
                    '    clsDBFuncationality.ExecuteNonQuery(qry1, trans)
                    '    Dim Cost_Center_Fin_Level_Name As String = Nothing
                    '    If clsCommon.CompairString(obj.Hirerachy_Level, "1") <> CompairStringResult.Equal Then
                    '        Dim qryfin_name As String = "SELECT TSPL_COST_CENTRE_FINANCIAL.Cost_Center_Fin_Name FROM TSPL_COST_CENTRE_FINANCIAL WHERE TSPL_COST_CENTRE_FINANCIAL.Cost_Center_Fin_Code"
                    '        Cost_Center_Fin_Level_Name = clsDBFuncationality.getSingleValue(qryfin_name, trans)
                    '    End If
                    '    Dim coll As New Hashtable()
                    '    clsCommon.AddColumnsForChange(coll, "Cost_Center_Fin_Code", obj.Cost_Center_Fin_Code)
                    '    clsCommon.AddColumnsForChange(coll, "Cost_Center_Fin_Level_Code", obj.Cost_Centre_Fin_Level_Code)
                    '    clsCommon.AddColumnsForChange(coll, "Cost_Center_Fin_Level_Name", Cost_Center_Fin_Level_Name)
                    '    clsCommon.AddColumnsForChange(coll, "Hirerachy_Level_Code", obj.Hirerachy_Level_Code)
                    '    clsCommon.AddColumnsForChange(coll, "Hirerachy_Level", obj.Hirerachy_Level)

                    '    clsCommonFunctionality.UpdateDataTable(coll, "TSPL_COST_CENTRE_FINANCIAL_DETAIL", OMInsertOrUpdate.Insert, "TSPL_COST_CENTRE_FINANCIAL_DETAIL.Cost_Center_Fin_Code='" + obj.Cost_Center_Fin_Code + "' ", trans)
                    'End If
                    ''========================End=========================
                Next

                trans.Commit()
                clsCommon.ProgressBarPercentHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                trans.Rollback()
                clsCommon.ProgressBarPercentHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub rmExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmExport.Click
        Dim str As String
        str = "select Cost_Center_Fin_Code as [Cost Center Fin Code],Cost_Center_Fin_Name As [Cost Center Fin Name],Hirerachy_Level_Code AS [Hirerachy Level Code],Hirerachy_Level AS [Hirerachy Level],Cost_Centre_Fin_Level_Code AS [Cost Centre Level] from TSPL_COST_CENTRE_FINANCIAL"
        ListImpExpColumnsMandatory = New List(Of String)({"Cost Center Fin Code", "Cost Center Fin Name", "Hirerachy Level Code"})
        ListImpExpColumnsSuperMandatory = New List(Of String)({"Cost Center Fin Code"})
        transportSql.ExporttoExcel(str, "", "", Me, ListImpExpColumnsMandatory, ListImpExpColumnsSuperMandatory, MyBase.Form_ID)
    End Sub

    Private Sub fndCode__MYNavigator(ByVal sender As Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndCode._MYNavigator
        Try
            LoadData(fndCode.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub fndCode__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndCode._MYValidating
        Dim str As String = "select count(*) from TSPL_COST_CENTRE_FINANCIAL where Cost_Center_Fin_Code ='" + fndCode.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            fndCode.MyReadOnly = False
        Else
            fndCode.MyReadOnly = True
        End If
        If fndCode.MyReadOnly OrElse isButtonClicked Then
            fndCode.Value = ClsCostCentreFinancial.getFinder("", fndCode.Value, isButtonClicked)
            If fndCode.Value <> "" Then
                LoadData(fndCode.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If
    End Sub

    Private Sub btnClose_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnClose.Click
        funClose()
    End Sub

    Private Sub btnSave_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnSave.Click
        SaveData()
    End Sub

    Private Sub btnDelete_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnDelete.Click
        DeleteData()
    End Sub

    Private Sub rdbtnreset_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles rdbtnreset.Click
        funReset()
    End Sub

    Private Sub TxtHirerachyLevel__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles TxtHirerachyLevel._MYValidating
        TxtCostCentreLevel.Value = ""
        LblCostCentre.Text = ""
        TxtHirerachyLevel.Value = ClsHirerachyLevelMaster.getFinder("", TxtHirerachyLevel.Value, isButtonClicked)
        If clsCommon.myLen(TxtHirerachyLevel.Value) > 0 Then
            LblHirerachy.Text = clsDBFuncationality.getSingleValue("Select ISNULL(Description,'') AS Desp from TSPL_HIRERACHY_LEVEL_MASTER Where HIRERACHY_CODE='" + TxtHirerachyLevel.Value + "' ")
            LblLevel.Text = clsDBFuncationality.getSingleValue("Select ISNULL(Level,'') AS Level from TSPL_HIRERACHY_LEVEL_MASTER Where HIRERACHY_CODE='" + TxtHirerachyLevel.Value + "' ")
            Dim Level As String = clsCommon.myCstr(clsCommon.myCdbl(LblLevel.Text) - 1)
            If EnableHirerachyCostCentre = 1 Then
                If clsCommon.CompairString(LblLevel.Text, "1") <> CompairStringResult.Equal Then
                    BindCostCentreLevel(Level)
                End If
            End If
        Else
            LblHirerachy.Text = ""
            LblLevel.Text = ""
        End If
    End Sub

    Private Sub TxtCostCentreLevel__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles TxtCostCentreLevel._MYValidating
        TxtCostCentreLevel.Value = ClsCostCentreFinancial.getFinder(" Hirerachy_Level = '" + clsCommon.myCstr(clsCommon.myCdbl(LblLevel.Text) - 1) + "' AND Cost_Center_Fin_Code <> '" + clsCommon.myCstr(fndCode.Value) + "'", TxtCostCentreLevel.Value, isButtonClicked)
        If clsCommon.myLen(TxtCostCentreLevel.Value) > 0 Then
            LblCostCentre.Text = clsDBFuncationality.getSingleValue("Select Cost_Center_Fin_Name from TSPL_COST_CENTRE_FINANCIAL Where Cost_Center_Fin_Code='" + TxtCostCentreLevel.Value + "' ")
        Else
            LblCostCentre.Text = ""
        End If
    End Sub

    Sub BindCostCentreLevel(ByVal Hirerachy_Level As String)
        Try
            LoadBlankGridDetail()
            Dim qry As String = Nothing
            qry = "SELECT CAST(0 as bit) as Sel,COST_CENTRE_HIRERACHY_CODE,HIRERACHY_LEVEL_CODE1,HIRERACHY_LEVEL_CODE2,HIRERACHY_LEVEL_CODE3" & _
                " ,HIRERACHY_LEVEL FROM TSPL_COST_CENTRE_HIRERACHY_DETAIL WHERE HIRERACHY_LEVEL='" + Hirerachy_Level + "' "

            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, Nothing)
            If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                For Each dr As DataRow In dt.Rows
                    gv1.Rows.AddNew()

                    gv1.Rows(gv1.Rows.Count - 1).Cells(colCostLSelect).Value = dr("SEL")
                    gv1.Rows(gv1.Rows.Count - 1).Cells(COST_CENTRE_HIRERACHY_CODE).Value = clsCommon.myCstr(dr("COST_CENTRE_HIRERACHY_CODE"))
                    gv1.Rows(gv1.Rows.Count - 1).Cells(HIRERACHY_LEVEL_CODE1).Value = clsCommon.myCstr(dr("HIRERACHY_LEVEL_CODE1"))
                    gv1.Rows(gv1.Rows.Count - 1).Cells(HIRERACHY_LEVEL_CODE2).Value = clsCommon.myCstr(dr("HIRERACHY_LEVEL_CODE2"))
                    gv1.Rows(gv1.Rows.Count - 1).Cells(HIRERACHY_LEVEL_CODE3).Value = clsCommon.myCstr(dr("HIRERACHY_LEVEL_CODE3"))
                    gv1.Rows(gv1.Rows.Count - 1).Cells(colHirerachyLevel).Value = clsCommon.myCdbl(dr("HIRERACHY_LEVEL"))

                Next
            Else
                gv1.DataSource = Nothing
            End If
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Sub
    Sub LoadBlankGridDetail()
        gv1.Rows.Clear()
        gv1.Columns.Clear()

        Dim repoSelect As GridViewCheckBoxColumn = New GridViewCheckBoxColumn()
        repoSelect.HeaderText = " "
        repoSelect.Name = colCostLSelect
        repoSelect.ReadOnly = False
        repoSelect.Width = 25
        repoSelect.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter
        gv1.MasterTemplate.Columns.Add(repoSelect)

        Dim repoCode As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoCode.FormatString = ""
        repoCode.HeaderText = "COST CENTRE CODE"
        repoCode.Name = COST_CENTRE_HIRERACHY_CODE
        repoCode.Width = 130
        repoCode.ReadOnly = True
        gv1.MasterTemplate.Columns.Add(repoCode)

        Dim repoHL1 As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoHL1.FormatString = ""
        repoHL1.HeaderText = "HIRERACHY LEVEL 1"
        repoHL1.Name = HIRERACHY_LEVEL_CODE1
        repoHL1.Width = 130
        repoHL1.ReadOnly = True
        gv1.MasterTemplate.Columns.Add(repoHL1)

        Dim repoHL2 As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoHL2.FormatString = ""
        repoHL2.HeaderText = "HIRERACHY LEVEL 2"
        repoHL2.Name = HIRERACHY_LEVEL_CODE2
        repoHL2.Width = 130
        repoHL2.ReadOnly = True
        gv1.MasterTemplate.Columns.Add(repoHL2)

        Dim repoHL3 As GridViewTextBoxColumn = New GridViewTextBoxColumn()
        repoHL3.FormatString = ""
        repoHL3.HeaderText = "HIRERACHY LEVEL 3"
        repoHL3.Name = HIRERACHY_LEVEL_CODE3
        repoHL3.Width = 130
        repoHL3.ReadOnly = True
        repoHL3.IsVisible = False
        gv1.MasterTemplate.Columns.Add(repoHL3)

        Dim repoLevel As GridViewDecimalColumn = New GridViewDecimalColumn()
        repoLevel.FormatString = ""
        repoLevel.HeaderText = "Level"
        repoLevel.Name = colHirerachyLevel
        repoLevel.ReadOnly = True
        repoLevel.IsVisible = False
        repoLevel.Width = 50
        repoLevel.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
        gv1.MasterTemplate.Columns.Add(repoLevel)

        RefreshHeaderText()

        gv1.AllowAddNewRow = False
        gv1.AllowDeleteRow = False
        gv1.ShowGroupPanel = False
        gv1.AllowColumnReorder = True
        gv1.AllowRowReorder = True
        gv1.EnableSorting = False
        gv1.MasterTemplate.ShowRowHeaderColumn = False
        gv1.MasterTemplate.ShowColumnHeaders = True
        gv1.EnableAlternatingRowColor = True
        gv1.EnableFiltering = True
        gv1.ShowFilteringRow = True
        gv1.TableElement.TableHeaderHeight = 40
    End Sub

    Sub RefreshHeaderText()
        If clsCommon.myLen(LblLevel.Text) > 0 Then
            Dim dt As DataTable = clsDBFuncationality.GetDataTable("select Description from TSPL_HIRERACHY_LEVEL_MASTER where Level<'" + clsCommon.myCstr(clsCommon.myCdbl(LblLevel.Text)) + "' order by level desc")
            If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                If dt.Rows.Count > 0 Then
                    gv1.Columns(COST_CENTRE_HIRERACHY_CODE).HeaderText = clsCommon.myCstr(dt.Rows(0)("Description"))
                    If dt.Rows.Count > 1 Then
                        gv1.Columns(HIRERACHY_LEVEL_CODE1).HeaderText = clsCommon.myCstr(dt.Rows(1)("Description"))
                        If dt.Rows.Count > 2 Then
                            gv1.Columns(HIRERACHY_LEVEL_CODE2).HeaderText = clsCommon.myCstr(dt.Rows(2)("Description"))
                            If dt.Rows.Count > 3 Then
                                gv1.Columns(HIRERACHY_LEVEL_CODE3).HeaderText = clsCommon.myCstr(dt.Rows(3)("Description"))
                            End If
                        Else
                            gv1.Columns(HIRERACHY_LEVEL_CODE2).IsVisible = False
                            gv1.Columns(HIRERACHY_LEVEL_CODE3).IsVisible = False
                        End If
                    Else
                        gv1.Columns(HIRERACHY_LEVEL_CODE1).IsVisible = False
                        gv1.Columns(HIRERACHY_LEVEL_CODE2).IsVisible = False
                        gv1.Columns(HIRERACHY_LEVEL_CODE3).IsVisible = False
                    End If
                Else
                    RadGroupBox1.Visible = False
                End If
            Else
                RadGroupBox1.Visible = False
            End If
        End If
    End Sub

End Class
