Imports System.Data.SqlClient
Imports common
Public Class ClsItemCategoryForproduction
#Region "variables"
    Public PROD_ITEM_CATEGORY_CODE As String = Nothing
    Public PROD_ITEM_CATEGORY_NAME As String = Nothing
    Public DESCRIPTION As String = Nothing
    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing
    Public ITEM_GROUP As String = Nothing
#End Region
#Region "Functions"

    Public Shared Function SaveData(ByVal obj As ClsItemCategoryForproduction, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""

        Try
            'If isNewEntry Then
            '    qry = "select  MAX(PROD_ITEM_CATEGORY_CODE)  from TSPL_MF_PRODUCTION_ITEM_CATEGORY"
            '    obj.PROD_ITEM_CATEGORY_CODE = clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
            '    If clsCommon.myLen(obj.PROD_ITEM_CATEGORY_CODE) <= 0 Then
            '        obj.PROD_ITEM_CATEGORY_CODE = "IM00000000001"
            '    Else
            '        obj.PROD_ITEM_CATEGORY_CODE = clsCommon.incval(obj.PROD_ITEM_CATEGORY_CODE)
            '    End If
            'End If
            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "comp_code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "PROD_ITEM_CATEGORY_NAME", obj.PROD_ITEM_CATEGORY_NAME)
            clsCommon.AddColumnsForChange(coll, "ITEM_GROUP", obj.ITEM_GROUP)
            clsCommon.AddColumnsForChange(coll, "Description", obj.DESCRIPTION)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_MF_PRODUCTION_ITEM_CATEGORY where PROD_ITEM_CATEGORY_CODE='" & obj.PROD_ITEM_CATEGORY_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.PROD_ITEM_CATEGORY_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.ItemCategoryForProduction, "", "")
                        If clsCommon.myLen(obj.PROD_ITEM_CATEGORY_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommon.AddColumnsForChange(coll, "PROD_ITEM_CATEGORY_CODE", obj.PROD_ITEM_CATEGORY_CODE)
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_MF_PRODUCTION_ITEM_CATEGORY", OMInsertOrUpdate.Insert, "", trans)
            Else
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_MF_PRODUCTION_ITEM_CATEGORY", OMInsertOrUpdate.Update, "TSPL_MF_PRODUCTION_ITEM_CATEGORY.PROD_ITEM_CATEGORY_CODE='" + obj.PROD_ITEM_CATEGORY_CODE + "'", trans)
            End If
            trans.Commit()
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function


    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsItemCategoryForproduction
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsItemCategoryForproduction
        Dim obj As ClsItemCategoryForproduction = Nothing
        Dim Arr As List(Of ClsItemCategoryForproduction) = Nothing
        Dim qry As String = "select PROD_ITEM_CATEGORY_CODE ,PROD_ITEM_CATEGORY_NAME,DESCRIPTION,ITEM_GROUP from TSPL_MF_PRODUCTION_ITEM_CATEGORY where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_MF_PRODUCTION_ITEM_CATEGORY.PROD_ITEM_CATEGORY_CODE = (select MIN(PROD_ITEM_CATEGORY_CODE) from TSPL_MF_PRODUCTION_ITEM_CATEGORY WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_MF_PRODUCTION_ITEM_CATEGORY.PROD_ITEM_CATEGORY_CODE = (select Max(PROD_ITEM_CATEGORY_CODE) from TSPL_MF_PRODUCTION_ITEM_CATEGORY WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_MF_PRODUCTION_ITEM_CATEGORY.PROD_ITEM_CATEGORY_CODE = (select top 1 PROD_ITEM_CATEGORY_CODE from TSPL_MF_PRODUCTION_ITEM_CATEGORY WHERE 1=1 " + whrclas + " and PROD_ITEM_CATEGORY_CODE='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_MF_PRODUCTION_ITEM_CATEGORY.PROD_ITEM_CATEGORY_CODE = (select Min(PROD_ITEM_CATEGORY_CODE) from TSPL_MF_PRODUCTION_ITEM_CATEGORY where PROD_ITEM_CATEGORY_CODE>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_MF_PRODUCTION_ITEM_CATEGORY.PROD_ITEM_CATEGORY_CODE = (select Max(PROD_ITEM_CATEGORY_CODE) from TSPL_MF_PRODUCTION_ITEM_CATEGORY where PROD_ITEM_CATEGORY_CODE<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsItemCategoryForproduction()
            obj.PROD_ITEM_CATEGORY_CODE = clsCommon.myCstr(dt.Rows(0)("PROD_ITEM_CATEGORY_CODE"))
            obj.PROD_ITEM_CATEGORY_NAME = clsCommon.myCstr(dt.Rows(0)("PROD_ITEM_CATEGORY_NAME"))
            obj.DESCRIPTION = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.ITEM_GROUP = clsCommon.myCstr(dt.Rows(0)("ITEM_GROUP"))
        End If
        Return obj
    End Function
    Public Shared Function GetProdItemGroupTable() As DataTable
        Dim DT_prod_itm_group As DataTable = New DataTable
        DT_prod_itm_group.Columns.Add("Code", GetType(String))
        DT_prod_itm_group.Columns.Add("Name", GetType(String))

        Dim DR As DataRow = DT_prod_itm_group.NewRow()
        DR("Name") = "Glass"
        DR("Code") = "GLASS"
        DT_prod_itm_group.Rows.Add(DR)

        DR = DT_prod_itm_group.NewRow()
        DR("Name") = "Slice Glass"
        DR("Code") = "SLICE GLASS"
        DT_prod_itm_group.Rows.Add(DR)

        DR = DT_prod_itm_group.NewRow()
        DR("Name") = "Pet"
        DR("Code") = "PET"
        DT_prod_itm_group.Rows.Add(DR)

        DR = DT_prod_itm_group.NewRow()
        DR("Name") = "BIBS"
        DR("Code") = "BIBS"
        DT_prod_itm_group.Rows.Add(DR)

        DR = DT_prod_itm_group.NewRow()
        DR("Name") = "Can"
        DR("Code") = "CAN"
        DT_prod_itm_group.Rows.Add(DR)

        DR = DT_prod_itm_group.NewRow()
        DR("Name") = "Others"
        DR("Code") = "OTHERS"
        DT_prod_itm_group.Rows.Add(DR)

        DT_prod_itm_group.AcceptChanges()

        Return DT_prod_itm_group
    End Function

    'Public Shared Function FinderForCategory(ByVal strCode As String, ByVal isButtonClicked As Boolean) As ClsItemCategoryForproduction
    '    Dim qry As String = "select PROD_ITEM_CATEGORY_CODE as Code,DESCRIPTION from TSPL_MF_PRODUCTION_ITEM_CATEGORY "
    '    Dim WhrCls As String = ""

    '    Return clsCommon.ShowSelectForm("category", qry, "Code", WhrCls, strCode, "Code", isButtonClicked)
    'End Function
#End Region
  

End Class
