Imports System.Data.SqlClient
Imports common
Public Class ClsMFToolType
#Region "variables"
    Public TOOL_TYPE_CODE As String = Nothing
    Public DESCRIPTION As String = Nothing
    Public STATUS As String = Nothing
    Public INACTIVE_DATE As Date? = Nothing
    Public UNIT_CODE As String = Nothing

    Public COST_PER_UNIT As String = Nothing
    Public COMMENTS As String = Nothing
    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing
#End Region
#Region "Functions"
    Public Shared Function SaveData(ByVal obj As ClsMFToolType, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "comp_code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "DESCRIPTION", obj.DESCRIPTION)
            clsCommon.AddColumnsForChange(coll, "STATUS", obj.STATUS)
            clsCommon.AddColumnsForChange(coll, "INACTIVE_DATE", clsCommon.GetPrintDate(obj.INACTIVE_DATE, "dd/MMM/yyyy"))
            clsCommon.AddColumnsForChange(coll, "COMMENTS", obj.COMMENTS)
            clsCommon.AddColumnsForChange(coll, "COST_PER_UNIT", obj.COST_PER_UNIT)
            clsCommon.AddColumnsForChange(coll, "UNIT_CODE", obj.UNIT_CODE)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_MF_tool_type where TOOL_TYPE_CODE='" & obj.TOOL_TYPE_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.TOOL_TYPE_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.MFToolType, "", "")
                        If clsCommon.myLen(obj.TOOL_TYPE_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "TOOL_TYPE_CODE", obj.TOOL_TYPE_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_MF_tool_type", OMInsertOrUpdate.Insert, "", trans)
            Else

                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_MF_tool_type", OMInsertOrUpdate.Update, "TSPL_MF_tool_type.TOOL_TYPE_CODE='" + obj.TOOL_TYPE_CODE + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsMFToolType
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsMFToolType
        Dim obj As ClsMFToolType = Nothing
        Dim Arr As List(Of ClsMFToolType) = Nothing
        Dim qry As String = "select * from TSPL_MF_tool_type where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_MF_tool_type.TOOL_TYPE_CODE = (select MIN(TOOL_TYPE_CODE) from TSPL_MF_tool_type WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_MF_tool_type.TOOL_TYPE_CODE = (select Max(TOOL_TYPE_CODE) from TSPL_MF_tool_type WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_MF_tool_type.TOOL_TYPE_CODE = (select top 1 TOOL_TYPE_CODE from TSPL_MF_tool_type WHERE 1=1 " + whrclas + " and TOOL_TYPE_CODE='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_MF_tool_type.TOOL_TYPE_CODE = (select Min(TOOL_TYPE_CODE) from TSPL_MF_tool_type where TOOL_TYPE_CODE>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_MF_tool_type.TOOL_TYPE_CODE = (select Max(TOOL_TYPE_CODE) from TSPL_MF_tool_type where TOOL_TYPE_CODE<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsMFToolType()
            obj.TOOL_TYPE_CODE = clsCommon.myCstr(dt.Rows(0)("TOOL_TYPE_CODE"))
            obj.DESCRIPTION = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.UNIT_CODE = clsCommon.myCstr(dt.Rows(0)("UNIT_CODE"))
            obj.COST_PER_UNIT = clsCommon.myCstr(dt.Rows(0)("COST_PER_UNIT"))
            obj.INACTIVE_DATE = clsCommon.myCstr(dt.Rows(0)("INACTIVE_DATE"))
        obj.STATUS = clsCommon.myCstr(dt.Rows(0)("STATUS"))
            obj.COMMENTS = clsCommon.myCstr(dt.Rows(0)("COMMENTS"))
        End If
        Return obj
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isDelete As Boolean
        Try
            isDelete = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_MF_tool_type where TOOL_TYPE_CODE ='" + strCode + "'"
            isDelete = clsDBFuncationality.ExecuteNonQuery(qry)
        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isDelete
    End Function
#End Region
End Class
