Imports System.Data.SqlClient
Imports common
Public Class ClsMFAccountSet
#Region "variables"
 Public ACCOUNT_SET_CODE As String = Nothing
    Public DESCRIPTION As String = Nothing
    Public WIP_CATEGORY As String = Nothing
    Public GL_WIP As String = Nothing
    Public GL_SETUP_LABOR As String = Nothing
    Public GL_RUN_LABOR As String = Nothing
    Public GL_SUBCONTRACT As String = Nothing
    Public GL_OVERHEAD As String = Nothing
    Public GL_MATERIAL_VARIANCE As String = Nothing
    Public GL_PRODUCTION_VARIANCE As String = Nothing
    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing
#End Region
#Region "Functions"
    Public Shared Function SaveData(ByVal obj As ClsMFAccountSet, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "DESCRIPTION", obj.DESCRIPTION)
            If obj.WIP_CATEGORY <> "" Then
                clsCommon.AddColumnsForChange(coll, "WIP_CATEGORY", obj.WIP_CATEGORY)
            End If
            If obj.GL_WIP <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_WIP", obj.GL_WIP)
            End If
            If obj.GL_WIP <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_SETUP_LABOR", obj.GL_SETUP_LABOR)
            End If
            If obj.GL_SETUP_LABOR <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_RUN_LABOR", obj.GL_RUN_LABOR)
            End If
            If obj.GL_SUBCONTRACT <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_SUBCONTRACT", obj.GL_SUBCONTRACT)
            End If
            If obj.GL_OVERHEAD <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_OVERHEAD", obj.GL_OVERHEAD)
            End If
            If obj.GL_MATERIAL_VARIANCE <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_MATERIAL_VARIANCE", obj.GL_MATERIAL_VARIANCE)
            End If
            If obj.GL_PRODUCTION_VARIANCE <> "" Then
                clsCommon.AddColumnsForChange(coll, "GL_PRODUCTION_VARIANCE", obj.GL_PRODUCTION_VARIANCE)
            End If
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_MF_ACCOUNTSETS where ACCOUNT_SET_CODE='" & obj.ACCOUNT_SET_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.ACCOUNT_SET_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.MFAccountSet, "", "")
                        If clsCommon.myLen(obj.ACCOUNT_SET_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "ACCOUNT_SET_CODE", obj.ACCOUNT_SET_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_MF_ACCOUNTSETS", OMInsertOrUpdate.Insert, "", trans)
            Else

                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_MF_ACCOUNTSETS", OMInsertOrUpdate.Update, "TSPL_MF_ACCOUNTSETS.ACCOUNT_SET_CODE='" + obj.ACCOUNT_SET_CODE + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsMFAccountSet
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsMFAccountSet
        Dim obj As ClsMFAccountSet = Nothing
        Dim Arr As List(Of ClsMFAccountSet) = Nothing
        Dim qry As String = "select ACCOUNT_SET_CODE ,DESCRIPTION,WIP_CATEGORY ,GL_WIP,GL_SETUP_LABOR ,GL_RUN_LABOR ,GL_SUBCONTRACT ,GL_OVERHEAD ,GL_MATERIAL_VARIANCE ,GL_PRODUCTION_VARIANCE from TSPL_MF_ACCOUNTSETS where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_MF_ACCOUNTSETS.ACCOUNT_SET_CODE = (select MIN(ACCOUNT_SET_CODE) from TSPL_MF_ACCOUNTSETS WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_MF_ACCOUNTSETS.ACCOUNT_SET_CODE = (select Max(ACCOUNT_SET_CODE) from TSPL_MF_ACCOUNTSETS WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_MF_ACCOUNTSETS.ACCOUNT_SET_CODE = (select top 1 ACCOUNT_SET_CODE from TSPL_MF_ACCOUNTSETS WHERE 1=1 " + whrclas + " and ACCOUNT_SET_CODE='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_MF_ACCOUNTSETS.ACCOUNT_SET_CODE = (select Min(ACCOUNT_SET_CODE) from TSPL_MF_ACCOUNTSETS where ACCOUNT_SET_CODE>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_MF_ACCOUNTSETS.ACCOUNT_SET_CODE = (select Max(ACCOUNT_SET_CODE) from TSPL_MF_ACCOUNTSETS where ACCOUNT_SET_CODE<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsMFAccountSet()
            obj.ACCOUNT_SET_CODE = clsCommon.myCstr(dt.Rows(0)("ACCOUNT_SET_CODE"))
            obj.DESCRIPTION = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.GL_MATERIAL_VARIANCE = clsCommon.myCstr(dt.Rows(0)("GL_MATERIAL_VARIANCE"))
            obj.GL_OVERHEAD = clsCommon.myCstr(dt.Rows(0)("GL_OVERHEAD"))
            obj.GL_PRODUCTION_VARIANCE = clsCommon.myCstr(dt.Rows(0)("GL_PRODUCTION_VARIANCE"))
            obj.GL_RUN_LABOR = clsCommon.myCstr(dt.Rows(0)("GL_RUN_LABOR"))
            obj.GL_SETUP_LABOR = clsCommon.myCstr(dt.Rows(0)("GL_SETUP_LABOR"))
            obj.GL_SUBCONTRACT = clsCommon.myCstr(dt.Rows(0)("GL_SUBCONTRACT"))
            obj.GL_WIP = clsCommon.myCstr(dt.Rows(0)("GL_WIP"))
            obj.WIP_CATEGORY = clsCommon.myCstr(dt.Rows(0)("WIP_CATEGORY"))
           End If
        Return obj
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isDelete As Boolean
        Try
            isDelete = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_MF_ACCOUNTSETS where ACCOUNT_SET_CODE ='" + strCode + "'"
            isDelete = clsDBFuncationality.ExecuteNonQuery(qry)
        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isDelete
    End Function
#End Region
End Class
