Imports System.Data.SqlClient
Imports common
Public Class ClsMFToolMaster
#Region "variables"
    Public TOOL_CODE As String = Nothing
    Public DESCRIPTION As String = Nothing
    Public STATUS As String = Nothing
    Public INACTIVE_DATE As Date? = Nothing
    Public TOOL_TYPE_CODE As String = Nothing
    Public RECEIPT_DATE As Date? = Nothing
    Public RECEIVED_BY As String = Nothing
    Public MAINTAINED_BY As String = Nothing
    Public SUPPLIER As String = Nothing
    Public RECEIPT_NUMBER As String = Nothing
    Public PO_NUMBER As String = Nothing
    Public SERIAL_NUMBER As String = Nothing
    Public CUSTODIAN As String = Nothing
    Public REPLACEMENT_DATE As Date? = Nothing
    Public COMMENTS As String = Nothing
    Public COST_PER_UNIT As String = Nothing
    Public ORIGINAL_QUANTITY As String = Nothing
    Public CONSUMED As String = Nothing
    Public ON_HAND_QUANTITY As String = Nothing
    Public ON_HAND_COST As String = Nothing
    Public UNIT_CODE As String = Nothing
    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing
#End Region
#Region "Functions"
    Public Shared Function SaveData(ByVal obj As ClsMFToolMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Try
            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "comp_code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "DESCRIPTION", obj.DESCRIPTION)
            clsCommon.AddColumnsForChange(coll, "STATUS", obj.STATUS)
            clsCommon.AddColumnsForChange(coll, "MAINTAINED_BY", obj.MAINTAINED_BY)
            clsCommon.AddColumnsForChange(coll, "INACTIVE_DATE", clsCommon.GetPrintDate(obj.INACTIVE_DATE, "dd/MMM/yyyy"))
            clsCommon.AddColumnsForChange(coll, "TOOL_TYPE_CODE", obj.TOOL_TYPE_CODE)
            If clsCommon.myLen(obj.RECEIPT_DATE) > 0 Then
                clsCommon.AddColumnsForChange(coll, "RECEIPT_DATE", clsCommon.GetPrintDate(obj.RECEIPT_DATE, "dd/MMM/yyyy"))
            End If
            clsCommon.AddColumnsForChange(coll, "RECEIVED_BY", obj.RECEIVED_BY)
            clsCommon.AddColumnsForChange(coll, "SUPPLIER", obj.SUPPLIER)
            clsCommon.AddColumnsForChange(coll, "RECEIPT_NUMBER", obj.RECEIPT_NUMBER)
            clsCommon.AddColumnsForChange(coll, "PO_NUMBER", obj.PO_NUMBER)
            clsCommon.AddColumnsForChange(coll, "SERIAL_NUMBER", obj.SERIAL_NUMBER)
            clsCommon.AddColumnsForChange(coll, "CUSTODIAN", obj.CUSTODIAN)
            If clsCommon.myLen(obj.REPLACEMENT_DATE) > 0 Then
                clsCommon.AddColumnsForChange(coll, "REPLACEMENT_DATE", clsCommon.GetPrintDate(obj.REPLACEMENT_DATE, "dd/MMM/yyyy"))
            End If
            clsCommon.AddColumnsForChange(coll, "COMMENTS", obj.COMMENTS)
            clsCommon.AddColumnsForChange(coll, "COST_PER_UNIT", obj.COST_PER_UNIT)
            clsCommon.AddColumnsForChange(coll, "ORIGINAL_QUANTITY", obj.ORIGINAL_QUANTITY)
            clsCommon.AddColumnsForChange(coll, "CONSUMED", obj.CONSUMED)
            clsCommon.AddColumnsForChange(coll, "ON_HAND_QUANTITY", obj.ON_HAND_QUANTITY)
            clsCommon.AddColumnsForChange(coll, "ON_HAND_COST", obj.ON_HAND_COST)
            clsCommon.AddColumnsForChange(coll, "UNIT_CODE", obj.UNIT_CODE)

            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_MF_TOOL_MASTER where TOOL_CODE='" & obj.TOOL_CODE & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.TOOL_CODE = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.MFToolMaster, "", "")
                        If clsCommon.myLen(obj.TOOL_CODE) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "TOOL_CODE", obj.TOOL_CODE)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_MF_TOOL_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else

                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_MF_TOOL_MASTER", OMInsertOrUpdate.Update, "TSPL_MF_TOOL_MASTER.TOOL_CODE='" + obj.TOOL_CODE + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsMFToolMaster
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsMFToolMaster
        Dim obj As ClsMFToolMaster = Nothing
        Dim Arr As List(Of ClsMFToolMaster) = Nothing
        Dim qry As String = "select * from TSPL_MF_TOOL_MASTER where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_MF_TOOL_MASTER.TOOL_CODE = (select MIN(TOOL_CODE) from TSPL_MF_TOOL_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_MF_TOOL_MASTER.TOOL_CODE = (select Max(TOOL_CODE) from TSPL_MF_TOOL_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_MF_TOOL_MASTER.TOOL_CODE = (select top 1 TOOL_CODE from TSPL_MF_TOOL_MASTER WHERE 1=1 " + whrclas + " and TOOL_CODE='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_MF_TOOL_MASTER.TOOL_CODE = (select Min(TOOL_CODE) from TSPL_MF_TOOL_MASTER where TOOL_CODE>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_MF_TOOL_MASTER.TOOL_CODE = (select Max(TOOL_CODE) from TSPL_MF_TOOL_MASTER where TOOL_CODE<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsMFToolMaster()
            obj.TOOL_CODE = clsCommon.myCstr(dt.Rows(0)("TOOL_CODE"))
            obj.DESCRIPTION = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.SUPPLIER = clsCommon.myCstr(dt.Rows(0)("SUPPLIER"))
            obj.TOOL_TYPE_CODE = clsCommon.myCstr(dt.Rows(0)("TOOL_TYPE_CODE"))
            obj.UNIT_CODE = clsCommon.myCstr(dt.Rows(0)("UNIT_CODE"))
            obj.CONSUMED = clsCommon.myCstr(dt.Rows(0)("CONSUMED"))
            obj.COST_PER_UNIT = clsCommon.myCstr(dt.Rows(0)("COST_PER_UNIT"))
            obj.CUSTODIAN = clsCommon.myCstr(dt.Rows(0)("CUSTODIAN"))
            obj.RECEIVED_BY = clsCommon.myCstr(dt.Rows(0)("RECEIVED_BY"))
            obj.MAINTAINED_BY = clsCommon.myCstr(dt.Rows(0)("MAINTAINED_BY"))
            obj.ON_HAND_COST = clsCommon.myCstr(dt.Rows(0)("ON_HAND_COST"))
            obj.ON_HAND_QUANTITY = clsCommon.myCstr(dt.Rows(0)("ON_HAND_QUANTITY"))
            obj.ORIGINAL_QUANTITY = clsCommon.myCstr(dt.Rows(0)("ORIGINAL_QUANTITY"))
            obj.RECEIVED_BY = clsCommon.myCstr(dt.Rows(0)("RECEIVED_BY"))
            obj.SERIAL_NUMBER = clsCommon.myCstr(dt.Rows(0)("SERIAL_NUMBER"))
            obj.INACTIVE_DATE = clsCommon.myCstr(dt.Rows(0)("INACTIVE_DATE"))
            If (dt.Rows(0)("RECEIPT_DATE")) IsNot DBNull.Value Then
                obj.RECEIPT_DATE = clsCommon.myCDate(dt.Rows(0)("RECEIPT_DATE"))
            End If
            If (dt.Rows(0)("REPLACEMENT_DATE")) IsNot DBNull.Value Then
                obj.REPLACEMENT_DATE = clsCommon.myCDate(dt.Rows(0)("REPLACEMENT_DATE"))
            End If
            obj.STATUS = clsCommon.myCstr(dt.Rows(0)("STATUS"))
            obj.COMMENTS = clsCommon.myCstr(dt.Rows(0)("COMMENTS"))
            obj.PO_NUMBER = clsCommon.myCstr(dt.Rows(0)("PO_NUMBER"))

            obj.RECEIPT_NUMBER = clsCommon.myCstr(dt.Rows(0)("RECEIPT_NUMBER"))
        End If
        Return obj
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isDelete As Boolean
        Try
            isDelete = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_MF_TOOL_MASTER where TOOL_CODE ='" + strCode + "'"
            isDelete = clsDBFuncationality.ExecuteNonQuery(qry)
        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isDelete
    End Function
#End Region
End Class
