Imports System.Data.SqlClient
Imports common

Public Class ClsStageMaster

#Region "Variables"
    Public Stage_Code As String = Nothing
    Public Description As String = Nothing
    Public Created_By As String = Nothing
    Public Created_Date As Date? = Nothing
    Public Modified_By As String = Nothing
    Public Modified_Date As Date? = Nothing
    Public Stage_Type As String = "None"
#End Region
    Public Shared Function GetCboStageTypeTable() As DataTable
        Dim DT As DataTable = New DataTable
        DT.Columns.Add("Code", GetType(String))
        DT.Columns.Add("Name", GetType(String))
        Dim DR As DataRow = DT.NewRow()
        'DR("Code") = "None"
        'DR("Name") = "None"
        'DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "STD"
        DR("Name") = "Standardization"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "SP"
        DR("Name") = "Stage Process"
        DT.Rows.Add(DR)

        DR = DT.NewRow()
        DR("Code") = "PE"
        DR("Name") = "Production Entry"
        DT.Rows.Add(DR)

        DT.AcceptChanges()
        Return DT
    End Function
    Public Shared Function GetFinder(ByVal whrCls As String, ByVal CurrCode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "select Stage_Code as Code,Description,Stage_Type as [Stage Type],created_by as [Created By],created_date as [Created Date],modified_by as [Modified By],modified_Date as [Modified Date] from TSPL_STAGE_MASTER"

        str = clsCommon.ShowSelectForm("STAFND", qry, "Code", whrCls, CurrCode, "Code", isButtonClicked)
        Return str
    End Function
    Public Shared Function GetStageType(ByVal Stage_Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select Stage_Type from TSPL_STAGE_MASTER where stage_code='" & Stage_Code & "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
    End Function

    Public Shared Function SaveData(ByVal obj As ClsStageMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""
        Dim IsSaved As Boolean = False
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
            clsCommon.AddColumnsForChange(coll, "Stage_Type", obj.Stage_Type)

            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_STAGE_MASTER where Stage_Code='" & obj.Stage_Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Stage_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.StageMaster, "", "")
                        If clsCommon.myLen(obj.Stage_Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"))
                clsCommon.AddColumnsForChange(coll, "Stage_Code", obj.Stage_Code)
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_STAGE_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else
                IsSaved = clsCommonFunctionality.UpdateDataTable(coll, "TSPL_STAGE_MASTER", OMInsertOrUpdate.Update, "TSPL_STAGE_MASTER.Stage_Code='" + obj.Stage_Code + "'", trans)
            End If

        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return IsSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsStageMaster
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsStageMaster
        Dim obj As ClsStageMaster = Nothing
        Dim Arr As List(Of ClsStageMaster) = Nothing
        Dim qry As String = "select Stage_Code ,Description,Stage_Type from TSPL_STAGE_MASTER where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_STAGE_MASTER.Stage_Code = (select MIN(Stage_Code) from TSPL_STAGE_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_STAGE_MASTER.Stage_Code = (select Max(Stage_Code) from TSPL_STAGE_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_STAGE_MASTER.Stage_Code = (select TOP 1 Stage_Code from TSPL_STAGE_MASTER WHERE 1=1 " + whrclas + " and Stage_Code='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_STAGE_MASTER.Stage_Code = (select Min(Stage_Code) from TSPL_STAGE_MASTER where Stage_Code > '" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_STAGE_MASTER.Stage_Code = (select Max(Stage_Code) from TSPL_STAGE_MASTER where Stage_Code < '" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsStageMaster()
            obj.Stage_Code = clsCommon.myCstr(dt.Rows(0)("Stage_Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
            obj.Stage_Type = clsCommon.myCstr(dt.Rows(0)("Stage_Type"))
        End If
        Return obj
    End Function
End Class

Public Class clsDeliveryTermsMaster
#Region "Variables"
    Public Code As String = Nothing
    Public Description As String = Nothing
#End Region

    Public Shared Function GetFinder(ByVal whrCls As String, ByVal strCurrCode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = "select Code,Description from TSPL_DELIVERY_TERMS_MASTER "
        str = clsCommon.ShowSelectForm("DLVTRMFND", qry, "Code", whrCls, strCurrCode, "Code", isButtonClicked)

        Return str
    End Function

    Public Shared Function SaveData(ByVal obj As clsDeliveryTermsMaster, ByVal isNewEntry As Boolean) As Boolean
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            SaveData(obj, isNewEntry, trans)
            trans.Commit()

            Return True
        Catch ex As Exception
            trans.Rollback()
            Throw New Exception(ex.Message)
        End Try
    End Function

    Public Shared Function SaveData(ByVal obj As clsDeliveryTermsMaster, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Try
            If isNewEntry Then
                Dim qry As String = "select max(code) from TSPL_DELIVERY_TERMS_MASTER"
                obj.Code = clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))

                If clsCommon.myLen(obj.Code) > 0 Then
                    obj.Code = clsCommon.incval(obj.Code)
                Else
                    obj.Code = "DLTR0000000000000001"
                End If
            End If

            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
            clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
            clsCommon.AddColumnsForChange(coll, "modified_by", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "modified_date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"))

            If isNewEntry Then
                clsCommon.AddColumnsForChange(coll, "created_by", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "created_date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"))

                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_DELIVERY_TERMS_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_DELIVERY_TERMS_MASTER", OMInsertOrUpdate.Update, " Code='" + obj.Code + "'", trans)
            End If

            Return True
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsDeliveryTermsMaster
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            Dim obj As clsDeliveryTermsMaster = GetData(strCode, NavType, trans)
            trans.Commit()

            Return obj
        Catch ex As Exception
            trans.Rollback()
            Throw New Exception(ex.Message)
        End Try
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsDeliveryTermsMaster
        Try
            Dim obj As New clsDeliveryTermsMaster()
            Dim qry As String = "select * from TSPL_DELIVERY_TERMS_MASTER "

            Select Case NavType
                Case NavigatorType.Current
                    qry += " where code='" + strCode + "'"
                Case NavigatorType.First
                    qry += " where code in (select min(code) from TSPL_DELIVERY_TERMS_MASTER)"
                Case NavigatorType.Last
                    qry += " where code in (select max(code) from TSPL_DELIVERY_TERMS_MASTER)"
                Case NavigatorType.Next
                    qry += " where code in (select min(code) from TSPL_DELIVERY_TERMS_MASTER where code>'" + strCode + "')"
                Case NavigatorType.Previous
                    qry += " where code in (select max(code from TSPL_DELIVERY_TERMS_MASTER where code<'" + strCode + "')"
            End Select
            Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

            If dt IsNot Nothing AndAlso dt.Rows.Count > 0 Then
                obj.Code = clsCommon.myCstr(dt.Rows(0)("code"))
                obj.Description = clsCommon.myCstr(dt.Rows(0)("description"))
            End If

            Return obj
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function

    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            DeleteData(strCode, trans)
            trans.Commit()

            Return True
        Catch ex As Exception
            trans.Rollback()
            Throw New Exception(ex.Message)
        End Try
    End Function

    Public Shared Function DeleteData(ByVal strCode As String, ByVal trans As SqlTransaction) As Boolean
        Try
            Dim qry As String = "delete from TSPL_DELIVERY_TERMS_MASTER where code='" + strCode + "'"
            clsDBFuncationality.ExecuteNonQuery(qry, trans)

            Return True
        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
    End Function
End Class