'Created By---> Monika
'Created Date--->31/Mar/2014
Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.OleDb
Imports System.Drawing
Imports System.IO
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls.Data
Imports Telerik.Data
Imports Telerik.WinControls.Enumerations
Imports Telerik.WinControls
Imports System.Text.RegularExpressions
Imports Telerik.WinControls.UI.Export
Imports Telerik.WinControls.UI.Export.ExportToExcelML
Imports Excel = Microsoft.Office.Interop.Excel
Imports System.Globalization
Imports common
Imports System.Threading
Imports XpertERPEngine

Public Class frmItemChargeCategoryMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim obj As New clsItemchargecategorymaster()
    Sub Reset()
        Try
            txtchrdesc.Text = ""
            txtGLCode.Value = ""
            lblGLDesc.Text = ""
            fndchrcat.Value = ""
            fndchrcat.MyReadOnly = False
            btnsave.Text = "Save"
            btndelete.Enabled = False
            fndchrcat.Focus()
            fndchrcat.Select()
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmItemChargeCategoryMaster)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied", Me.Text)
            Me.Close()
            Exit Sub
        End If
        btnsave.Visible = MyBase.isModifyFlag
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Public Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If (clsCommon.myLen(fndchrcat.Value) = 0) Then
                clsCommon.MyMessageBoxShow("Please Insert Charge Category Code", Me.Text)
                fndchrcat.Focus()
                fndchrcat.Select()
                Return False
            End If
        End If

        'If (clsCommon.myLen(txtchrdesc.Text) = 0) Then
        '    clsCommon.MyMessageBoxShow("Enter Suitable Description For The Charge Category")
        '    txtchrdesc.Focus()
        '    txtchrdesc.Select()
        '    Return False
        'End If
        If (clsCommon.myLen(txtGLCode.Value) = 0) Then
            clsCommon.MyMessageBoxShow("Select GL Account", Me.Text)
            txtGLCode.Focus()
            txtGLCode.Select()
            Return False
        End If

        'Dim qry As String = "select count(*) from TSPL_Charge_Category where charge_cat_code='" + fndchrcat.Value + "'"
        '    Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry)
        '    If check1 = 0 Then
        '        clsCommon.MyMessageBoxShow("Invalid Charge Category Code")
        '        Return False
        'End If
        Return True

    End Function
    Private Sub btnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click
        If AllowToSave() Then SaveData()
    End Sub

    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub

    Private Sub btnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        Me.Close()
    End Sub

    Private Sub frmItemChargeCategoryMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        Reset()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update ")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D  for Delete ")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        SetUserMgmtNew()
    End Sub

    Private Sub btnnew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnnew.Click
        Reset()
        fndchrcat.MyReadOnly = False
        btnsave.Text = "Save"
        btndelete.Enabled = False
    End Sub
    Public Sub SaveData()

        If MyBase.isModifyonPasswordFlag Then
            If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.frmItemChargeCategoryMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
            Else
                Return
            End If
        End If

        obj = New clsItemchargecategorymaster()
        obj.chrcategorycode = fndchrcat.Value
        obj.chrcategorydesc = txtchrdesc.Text.Replace("'", "`")
        obj.glacccode = txtGLCode.Value
        obj.glaccdesc = lblGLDesc.Text.Replace("'", "`")

        If btnsave.Text <> "Save" Then
            Dim qry As String = "select count(*) from tspl_charge_category where charge_cat_code='" + fndchrcat.Value + "'"
            Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
            If check = 0 Then
                clsCommon.MyMessageBoxShow("No Data Found", Me.Text)
                Reset()
                Return
            End If
        End If

        If AllowToSave() Then
            Dim isSaved As Boolean = clsItemchargecategorymaster.SaveData(obj, IIf(btnsave.Text = "Save", True, False), Nothing)
            If isSaved Then
                common.clsCommon.MyMessageBoxShow("Data Saved Successfully", Me.Text)
                fndchrcat.Value = obj.chrcategorycode
                btnsave.Text = "Update"
                fndchrcat.MyReadOnly = True
                btndelete.Enabled = True
            Else
                btnsave.Text = "Save"
                fndchrcat.MyReadOnly = False
                btndelete.Enabled = False
                common.clsCommon.MyMessageBoxShow("Data Could Not Saved", Me.Text)
            End If
        End If
    End Sub
    Sub DeleteData()
        If clsCommon.myLen(fndchrcat.Value) <= 0 Then
            clsCommon.MyMessageBoxShow("No Data Found For Deletion", Me.Text)
            'Return False
        ElseIf clsCommon.myLen(fndchrcat.Value) > 0 Then
            Dim chck As Integer = clsDBFuncationality.getSingleValue("select count(*) from TSPL_ITEM_FRANCHISE_MAPPING where charge_cat_code='" + fndchrcat.Value + "'")
            If chck > 0 Then
                clsCommon.MyMessageBoxShow("Data Is In Use,First Delete All Its Referances", Me.Text)
                'Return False
            End If
        End If
        If Not (common.clsCommon.MyMessageBoxShow("Delete the Charge Category Code " + fndchrcat.Value + "" + Environment.NewLine + "Are you sure?", Me.Text, MessageBoxButtons.YesNo, RadMessageIcon.Question) = DialogResult.Yes) Then
            'Return False
        End If

        If clsItemchargecategorymaster.DeleteData(fndchrcat.Value) Then
            common.clsCommon.MyMessageBoxShow("Data Deleted Sucessfully", Me.Text)
            Reset()
            'Return True
        End If
    End Sub
    Private Sub LoadData()
        obj = New clsItemchargecategorymaster()
        obj = clsItemchargecategorymaster.GetData(fndchrcat.Value, NavigatorType.Current)
        If obj IsNot Nothing AndAlso clsCommon.myLen(obj.chrcategorycode) > 0 Then
            fndchrcat.MyReadOnly = True
            fndchrcat.Value = obj.chrcategorycode
            txtchrdesc.Text = obj.chrcategorydesc
            txtGLCode.Value = obj.glacccode
            lblGLDesc.Text = obj.glaccdesc
        End If
    End Sub
    Private Sub frmItemChargeCategoryMaster_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            Reset()
        End If
    End Sub

    Private Sub fndchrcat__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndchrcat._MYNavigator
        Try
            obj = New clsItemchargecategorymaster()
            obj = clsItemchargecategorymaster.GetData(fndchrcat.Value, NavType)
            If obj IsNot Nothing Then
                fndchrcat.Value = obj.chrcategorycode
                txtchrdesc.Text = obj.chrcategorydesc
                txtGLCode.Value = obj.glacccode
                lblGLDesc.Text = obj.glaccdesc
                fndchrcat.MyReadOnly = True
                btnsave.Text = "Update"
                btndelete.Enabled = True
                fndchrcat.MyReadOnly = True

            End If
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Sub

    Private Sub fndchrcat__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles fndchrcat._MYValidating
        Dim str As String = "select count(*) from tspl_charge_category where charge_cat_code ='" + fndchrcat.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 Then
            fndchrcat.MyReadOnly = False
        Else
            fndchrcat.MyReadOnly = True
        End If
        If fndchrcat.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = "select Charge_Cat_Code as [Code],Description,gl_code as [Account Code],gl_desc as [Account Description] from tspl_charge_category "
            'fndchrcat.Value = clsCommon.ShowSelectForm("CHARGECATFND", qry, "code", "", fndchrcat.Value, "", isButtonClicked)
            fndchrcat.Value = clsItemchargecategorymaster.getFinder("", fndchrcat.Value, isButtonClicked)
            txtchrdesc.Text = clsDBFuncationality.getSingleValue("Select description from tspl_charge_category where charge_cat_code='" + fndchrcat.Value + "'")
            txtGLCode.Value = clsDBFuncationality.getSingleValue("Select gl_code from tspl_charge_category where charge_cat_code='" + fndchrcat.Value + "'")
            lblGLDesc.Text = clsDBFuncationality.getSingleValue("Select gl_desc from tspl_charge_category where charge_cat_code='" + fndchrcat.Value + "'")
            If fndchrcat.Value IsNot Nothing AndAlso fndchrcat.Value <> "" Then
                btndelete.Enabled = True
                btnsave.Text = "Update"
                fndchrcat.MyReadOnly = True
            Else
                btnsave.Text = "Save"
                btndelete.Enabled = False
                fndchrcat.MyReadOnly = False
            End If

        End If
    End Sub

    Private Sub txtGLCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtGLCode._MYValidating
        Try
            If isButtonClicked Then
                Dim qry As String = "select Account_Code as [Code] ,Description,account_type as [Account Type],account_group_desc as [Group Desc] from TSPL_GL_Accounts "
                txtGLCode.Value = clsCommon.ShowSelectForm("ACCIDFND", qry, "code", "", txtGLCode.Value, "", isButtonClicked)

                If clsCommon.myLen(txtGLCode.Value) > 0 Then
                    lblGLDesc.Text = clsDBFuncationality.getSingleValue("Select description from TSPL_GL_Accounts where Account_Code='" + txtGLCode.Value + "'")
                End If
            ElseIf clsCommon.myLen(txtGLCode.Value) = 0 Then
                lblGLDesc.Text = ""
            End If
        Catch ex As Exception
        End Try
    End Sub

    Private Sub Rdmenuexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Rdmenuexport.Click
        Dim str As String
        str = "select charge_cat_code as 'Charge Category Code' ,tspl_charge_category.Description, gl_Code as 'Account Code',TSPL_GL_ACCOUNTS.description as 'Account Description' from tspl_charge_category left outer join TSPL_GL_ACCOUNTS on TSPL_GL_ACCOUNTS.account_code=tspl_charge_category.gl_code"
        transportSql.ExporttoExcel(str, Me)
    End Sub

    Private Sub Rdmenuimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Rdmenuimport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Charge Category Code", "Description", "Account Code", "Account Description") Then
            'Dim trans As SqlTransaction
            Try

                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsItemchargecategorymaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception(" Charge Category Code can not be blank or incorrect.")
                    End If
                    obj.chrcategorycode = strCode

                    Dim strDec As String = clsCommon.myCstr(grow.Cells(1).Value)

                    obj.chrcategorydesc = strDec
                    Dim strcode2 As String = clsCommon.myCstr(grow.Cells(2).Value)
                    If strcode2.Length > 30 Or (String.IsNullOrEmpty(strcode2)) Or clsDBFuncationality.getSingleValue("SELECT Count(*) FROM tspl_gl_accounts where account_code = '" & strcode2 & "'") = 0 Then
                        Throw New Exception(" Invalid Account Code ")
                    End If
                    obj.glacccode = strcode2

                    Dim strDec1 As String = clsCommon.myCstr(grow.Cells(3).Value)

                    obj.glaccdesc = strDec1

                    clsItemchargecategorymaster.SaveData(obj, clsPrimaryReasonMaster.CheckNewEntry(obj.chrcategorycode), Nothing)
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub rbmenuexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbmenuexit.Click
        Me.Close()
    End Sub

    Private Sub SplitContainer1_SplitterMoved(ByVal sender As System.Object, ByVal e As System.Windows.Forms.SplitterEventArgs) Handles SplitContainer1.SplitterMoved

    End Sub

    Private Sub RadGroupBox1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadGroupBox1.Click

    End Sub
End Class
