'Created By---> Pankaj Jha
'Created Date--->27/mar/2014
Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.OleDb
Imports System.Drawing
Imports System.IO
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls.Data
Imports Telerik.Data
Imports Telerik.WinControls.Enumerations
Imports Telerik.WinControls
Imports System.Text.RegularExpressions
Imports Telerik.WinControls.UI.Export
Imports Telerik.WinControls.UI.Export.ExportToExcelML
Imports Excel = Microsoft.Office.Interop.Excel
Imports System.Globalization
Imports common
Imports System.Threading
Imports XpertERPEngine

Public Class FrmPrimaryReasonMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Dim ReasonCode, Description, CompGroupCode, CompDesc As String
    Dim obj As New clsPrimaryReasonMaster
    Private Sub frmPrimaryReasonMaster_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso rbtnSave.Enabled Then
                saveData()

            ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso rbtnDelete.Enabled Then
                deleteData()
            ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
                Close()
            ElseIf e.Alt And e.KeyCode = Keys.N Then
                Reset()
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub


    Private Sub frmPrimaryReasonMaster_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            fndReasonID.MyMaxLength = 30
            txtDescription.MaxLength = 500

            ButtonToolTip.SetToolTip(rbtnSave, "Press Alt+S for Save/Update ")
            ButtonToolTip.SetToolTip(rbtnDelete, "Press Alt+D  for Delete ")
            ButtonToolTip.SetToolTip(rbtnClose, "Press Alt+C Close the Window")
            Reset()
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub
    Private Sub Reset()
        Try
            fndReasonID.Value = ""
            txtDescription.Text = ""
            txtComplaintGroupCode.Value = ""
            lblComplaintGroupDesc.Text = ""
            rbtnDelete.Enabled = False
            fndReasonID.Focus()
            rbtnSave.Text = "Save"
            fndReasonID.MyReadOnly = False
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.frmPrimaryReasonMaster)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        rbtnSave.Visible = MyBase.isModifyFlag
        rbtnDelete.Visible = MyBase.isDeleteFlag
    End Sub


    Private Sub rbtnClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnClose.Click
        Me.Close()
    End Sub

    Private Sub rbtnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnSave.Click
        If AllowToSave() Then saveData()
    End Sub
    Public Function AllowToSave() As Boolean
        Try
            If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
                If clsCommon.myLen(fndReasonID.Value) = 0 Then
                    common.clsCommon.MyMessageBoxShow("Please Enter Reason Code")
                    Return False
                End If
            End If
            If clsCommon.myLen(txtDescription.Text) = 0 Then
                common.clsCommon.MyMessageBoxShow("Please Enter Description")
                Return False
            End If
            If clsCommon.myLen(txtComplaintGroupCode.Value) = 0 Then
                common.clsCommon.MyMessageBoxShow("Please Enter Complaint Group Code")
                Return False
            End If
            Dim qry1 As String = "SELECT Count(*) FROM TSPL_COMPLAINT_GROUP_MASTER where COMPLAINT_Code = '" & txtComplaintGroupCode.Value & "'"
            Dim check1 As Integer = clsDBFuncationality.getSingleValue(qry1)
            If check1 = 0 Then
                common.clsCommon.MyMessageBoxShow("Invalid Complaint Group Code")
                Return False
            End If
            'Return True
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
            Return False
        End Try
        Return True
    End Function
    Sub saveData()
        Try
            obj = New clsPrimaryReasonMaster()
            obj.Reason_Code = fndReasonID.Value
            obj.description = txtDescription.Text.Trim
            obj.CompCode = txtComplaintGroupCode.Value
            obj.CompDesc = lblComplaintGroupDesc.Text.Trim

            Dim isSaved As Boolean = obj.SaveData(obj, IIf(rbtnSave.Text = "Save", True, False), Nothing)
            If isSaved Then
                common.clsCommon.MyMessageBoxShow("Data Saved Successfully")
                rbtnSave.Text = "Update"
                rbtnDelete.Enabled = True
            Else
                rbtnSave.Text = "Save"
                rbtnDelete.Enabled = False
                common.clsCommon.MyMessageBoxShow("Data Could Not Saved")
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try

    End Sub
    Sub deleteData()
        Try
            If clsCommon.myLen(fndReasonID.Value) <= 0 Then
                common.clsCommon.MyMessageBoxShow("No Reason Code found to Delete", Me.Name)
                'Return False
            ElseIf Not (common.clsCommon.MyMessageBoxShow("Delete the Reason Code " + fndReasonID.Value + Environment.NewLine + " Are you sure?", Me.Text, MessageBoxButtons.YesNo, RadMessageIcon.Question) = DialogResult.Yes) Then
                'Return False
            End If
            If (clsPrimaryReasonMaster.DeleteData(fndReasonID.Value)) Then
                common.clsCommon.MyMessageBoxShow("Data Deleted Sucessfully", Me.Name)
                Reset()
                'Return True
            End If

        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try

    End Sub
    Private Sub loadData()
        Try
            obj = New clsPrimaryReasonMaster()
            obj = clsPrimaryReasonMaster.GetData(fndReasonID.Value, NavigatorType.Current)
            If obj IsNot Nothing AndAlso clsCommon.myLen(obj.Reason_Code) > 0 Then
                fndReasonID.Value = obj.Reason_Code
                txtDescription.Text = obj.description
                txtComplaintGroupCode.Value = obj.CompCode
                lblComplaintGroupDesc.Text = obj.description
            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub fndReasonID__MYNavigator(ByVal sender As Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles fndReasonID._MYNavigator
        Try
            obj = New clsPrimaryReasonMaster()
            obj = clsPrimaryReasonMaster.GetData(fndReasonID.Value, NavType)
            If obj IsNot Nothing Then
                fndReasonID.Value = obj.Reason_Code
                txtDescription.Text = obj.description
                txtComplaintGroupCode.Value = obj.CompCode
                lblComplaintGroupDesc.Text = obj.CompDesc
                rbtnSave.Text = "Update"
                rbtnDelete.Enabled = True
                fndReasonID.MyReadOnly = True

            End If
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try

    End Sub

    Private Sub fndReasonID__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles fndReasonID._MYValidating
        Try
            Dim str As String = "select count(*) from TSPL_PRIMARY_REASON_MASTER where Reason_code ='" + fndReasonID.Value + "' "
            Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
            If no = 0 Then
                fndReasonID.MyReadOnly = False
            Else
                fndReasonID.MyReadOnly = True
            End If
            If fndReasonID.MyReadOnly OrElse isButtonClicked Then

                'Dim qry As String = "select Reason_Code as 'Code',Description,Complaint_Code as 'Complaint Code' from   TSPL_PRIMARY_REASON_MASTER "
                'fndReasonID.Value = clsCommon.ShowSelectForm("RESONIDFND", qry, "Code", "", fndReasonID.Value, "", isButtonClicked)
                fndReasonID.Value = clsPrimaryReasonMaster.getFinder("", fndReasonID.Value, isButtonClicked)
                txtDescription.Text = clsDBFuncationality.getSingleValue("Select description from TSPL_PRIMARY_REASON_MASTER where Reason_Code='" + fndReasonID.Value + "'")
                txtComplaintGroupCode.Value = clsDBFuncationality.getSingleValue("Select Complaint_Code from TSPL_PRIMARY_REASON_MASTER where Reason_Code='" + fndReasonID.Value + "'")
                lblComplaintGroupDesc.Text = clsDBFuncationality.getSingleValue("Select description from TSPL_COMPLAINT_GROUP_MASTER where Complaint_Code='" + txtComplaintGroupCode.Value + "'")
                If clsCommon.myLen(fndReasonID.Value) > 0 Then
                    rbtnDelete.Enabled = True
                    rbtnSave.Text = "Update"
                    fndReasonID.MyReadOnly = True
                Else
                    rbtnSave.Text = "Save"
                    rbtnDelete.Enabled = False
                    fndReasonID.MyReadOnly = False
                End If

            End If
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub rbtnDelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnDelete.Click
        deleteData()
    End Sub

    Private Sub rbtnReset_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rbtnReset.Click
        Reset()
    End Sub

    Private Sub txtComplaintGroupCode__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles txtComplaintGroupCode._MYValidating
        Try
            If isButtonClicked Then
                Dim qry As String = "select Complaint_Code ,description from   TSPL_COMPLAINT_GROUP_MASTER "
                txtComplaintGroupCode.Value = clsCommon.ShowSelectForm("CMPIDFND", qry, "Complaint_Code", "", txtComplaintGroupCode.Value, "", isButtonClicked)
                lblComplaintGroupDesc.Text = clsDBFuncationality.getSingleValue("Select description from TSPL_COMPLAINT_GROUP_MASTER where Complaint_Code='" + txtComplaintGroupCode.Value + "'")
            Else
                lblComplaintGroupDesc.Text = clsDBFuncationality.getSingleValue("Select description from TSPL_COMPLAINT_GROUP_MASTER where Complaint_Code='" + txtComplaintGroupCode.Value + "'")
            End If
        Catch ex As Exception
        End Try

    End Sub


    Private Sub rdmenuexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexit.Click
        Me.Close()
    End Sub

    Private Sub rdmenuexport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuexport.Click
        Try
            Dim str As String
            str = "select Reason_Code as 'Reason Code' ,Description, Complaint_Code as 'Complaint Code' from   TSPL_Primary_Reason_MASTER "
            transportSql.ExporttoExcel(str, Me)
        Catch ex As Exception
            clsCommon.MyMessageBoxShow(ex.Message)
        End Try
    End Sub

    Private Sub rdmenuimport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rdmenuimport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Reason Code", "Description", "Complaint Code") Then
            ' Dim trans As SqlTransaction
            Try
                'connectSql.OpenConnection()
                'trans = clsDBFuncationality.GetTransactin()
                clsCommon.ProgressBarShow()
                For Each grow As GridViewRowInfo In gv.Rows
                    Dim obj As New clsPrimaryReasonMaster()

                    Dim strCode As String = clsCommon.myCstr(grow.Cells(0).Value)
                    If strCode.Length > 30 Or (String.IsNullOrEmpty(strCode)) Then
                        Throw New Exception(" Reason Code can not be blank or incorrect.")
                    End If
                    obj.Reason_Code = strCode

                    Dim strDec As String = clsCommon.myCstr(grow.Cells(1).Value)

                    obj.description = strDec
                    Dim strcode2 As String = clsCommon.myCstr(grow.Cells(2).Value)
                    If strcode2.Length > 30 Or (String.IsNullOrEmpty(strcode2)) Or clsDBFuncationality.getSingleValue("SELECT Count(*) FROM TSPL_COMPLAINT_GROUP_MASTER where COMPLAINT_Code = '" & strcode2 & "'") = 0 Then
                        Throw New Exception(" Invalid Complaint Code ")
                    End If
                    obj.CompCode = strcode2

                    obj.SaveData(obj, clsPrimaryReasonMaster.CheckNewEntry(obj.Reason_Code), Nothing)
                Next
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try

        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub RadMenufile_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadMenufile.Click

    End Sub
End Class
