' ----------------- Created By Anubhooti On 3-July-2014 Against BM00000003068 -------------------- '
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports Telerik.WinControls.Data
Imports System.Text.RegularExpressions
Imports common

Public Class FrmZoneMaster
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String

#Region "Functions"
    Private Sub SetUserMgmtNew()
        'MyBase.SetUserMgmt(clsUserMgtCode.FrmZoneMaster)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied")
            Me.Close()
        End If
        btnsave.Visible = MyBase.isModifyFlag
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Dim obj As ClsZoneMaster = ClsZoneMaster.GetData(strCode, NavTyep)
        If obj IsNot Nothing Then
            isNewEntry = False
            txtCode.Value = obj.Zone_Code
            txtdes.Text = obj.Description
            txtdesHindi.Text = obj.Description_Hindi
            txtCode.MyReadOnly = True
            txtCity.Value = obj.Location_CODE
            lblCity.Text = clsLocation.GetName(obj.Location_CODE, Nothing) 'clsCityMaster.GetName(obj.City_Code)
            fndRSM.Value = obj.RSM_CODE
            If clsCommon.myLen(obj.RSM_CODE) > 0 Then
                lblRSM.Text = clsDBFuncationality.getSingleValue("Select Emp_Name as Name from  TSPL_EMPLOYEE_MASTER  where EMP_CODE = '" + obj.RSM_CODE + "'")
            Else
                lblRSM.Text = ""
            End If

        End If
    End Sub
    Sub SaveData()

        If MyBase.isModifyonPasswordFlag Then
            If clsPasswordCheckForMasters.CheckMasterPwd(clsUserMgtCode.FrmZoneMaster, clsCommon.myCstr(objCommonVar.CurrentCompanyCode)) Then
            Else
                Return
            End If
        End If
        If AllowToSave() Then
            Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
            Try
                Dim obj As New ClsZoneMaster()
                obj.Zone_Code = txtCode.Value
                obj.Description = txtdes.Text
                obj.Description_Hindi = txtdesHindi.Text
                obj.Location_CODE = txtCity.Value
                obj.RSM_CODE = fndRSM.Value
                Dim qry As Integer = clsDBFuncationality.getSingleValue("select count(Zone_Code) from TSPL_ZONE_MASTER where Zone_Code='" + obj.Zone_Code + "'", trans)
                If (qry = 0) Then
                    isNewEntry = True
                Else
                    isNewEntry = False
                End If
                If (ClsZoneMaster.SaveData(obj, isNewEntry, trans)) Then
                    trans.Commit()
                    clsCommon.MyMessageBoxShow("Data saved Successfully", Me.Text)
                    LoadData(obj.Zone_Code, NavigatorType.Current)
                End If
            Catch ex As Exception
                trans.Rollback()
                clsCommon.MyMessageBoxShow(ex.Message, Me.Text)
            End Try
        End If
    End Sub
    Private Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(clsCommon.myCstr(txtCode.Value)) <= 0 Then
                txtCode.Focus()
                Throw New Exception("Please Fill Code")
            End If
            If clsCommon.myLen(clsCommon.myCstr(txtCity.Value)) <= 0 Then
                txtCity.Focus()
                Throw New Exception("Please Fill Location")
            End If
        End If

        Return True
    End Function
    Private Sub DeleteData()
        Try
            If clsCommon.myLen(txtCode.Value) <= 0 Then
                Throw New Exception("Code not found to delete")
            End If
            If clsCommon.MyMessageBoxShow("Do you want to delete  Code '" + txtCode.Value + "'", Me.Text, MessageBoxButtons.YesNo) = System.Windows.Forms.DialogResult.Yes Then

                Dim qry As String = "DELETE FROM TSPL_ZONE_MASTER WHERE Zone_Code='" + txtCode.Value + "'"
                clsDBFuncationality.ExecuteNonQuery(qry)
                clsCommon.MyMessageBoxShow("Successfully Deleted", Me.Text)
                AddNew()
            End If
        Catch ex As Exception
            If (clsCommon.CompairString(clsCommon.myCstr(ex.Message), "Cost Code not found to delete") <> CompairStringResult.Equal) Then
                clsCommon.MyMessageBoxShow("Current Cost Code is in use")
            Else
                clsCommon.MyMessageBoxShow(ex.Message)
            End If
        End Try
    End Sub
    Sub AddNew()
        txtCode.Value = ""
        txtdes.Text = ""
        txtdesHindi.Text = ""
        'txtCode.MyReadOnly = False
        'txtCity.Value = ""
        fndRSM.Value = ""
        ' lblCity.Text = ""
        lblRSM.Text = ""
    End Sub
#End Region

#Region "Events"
    Private Sub FrmZoneMaster_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            AddNew()
        End If
    End Sub
    Private Sub FrmZoneMaster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        txtdesHindi.Visible = False
        MyLabel2.Visible = False
        fndRSM.Visible = False
        lblRSM.Visible = False
        If clsCommon.myLen(objCommonVar.strCurrUserLocations) > 0 Then
            txtCity.Value = clsDBFuncationality.getSingleValue("select Location_Code from TSPL_Location_Master where Location_Code in(" + clsCommon.myCstr(objCommonVar.strCurrUserLocations) + ")") 'clsCommon.myCstr(objCommonVar.strCurrUserLocations)
            lblCity.Text = clsLocation.GetName(txtCity.Value, Nothing)
        End If
    End Sub
    Private Sub btnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click
        SaveData()
    End Sub
    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub
    Private Sub btnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        Me.Close()
    End Sub
    Private Sub txtCode__MYNavigator(ByVal sender As Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        LoadData(txtCode.Value, NavType)
    End Sub
    Private Sub txtCode__MYValidating(ByVal sender As Object, ByVal e As System.EventArgs, ByVal isButtonClicked As Boolean) Handles txtCode._MYValidating
        If txtCode.MyReadOnly OrElse isButtonClicked Then
            Dim qry As String = "select Zone_Code As Code,Description from  TSPL_ZONE_MASTER"
            txtCode.Value = clsCommon.ShowSelectForm("TSPL_ZONE_MASTER", qry, "Code", "", txtCode.Value, "", isButtonClicked)
            LoadData(txtCode.Value, NavigatorType.Current)
        End If
    End Sub
    Private Sub btnnew_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnnew.Click
        AddNew()
    End Sub
#End Region

    Private Sub txtCity__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtCity._MYValidating
        Dim WhrCls As String = " 2=2"
        If clsCommon.myLen(objCommonVar.strCurrUserLocations) > 0 Then
            WhrCls += " and Location_Code in(" + clsCommon.myCstr(objCommonVar.strCurrUserLocations) + ")"
        End If
        txtCity.Value = clsLocation.getFinder(WhrCls, txtCity.Value, isButtonClicked)

        lblCity.Text = clsLocation.GetName(txtCity.Value, Nothing)
    End Sub

    Private Sub Import_Click(sender As Object, e As EventArgs) Handles Import.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        Dim AutoGenerateDocCode As Boolean = IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)
        'If transportSql.importExcel(gv, "Zone Code", "Zone Description", "City Code", "City Name", "RSM CODE", "RSM Name") Then
        If transportSql.importExcel(gv, "Zone Code", "Zone Description", "Location Code", "Location Name") Then
            Dim trans As SqlTransaction = Nothing

            Dim linno As Integer = 0
            Dim TempNewRecord As Boolean = False
            Try
                ' connectSql.OpenConnection()
                trans = clsDBFuncationality.GetTransactin()

                clsCommon.ProgressBarShow()

                Dim strcode As String = ""
                Dim strname As String = ""

                For Each grow As GridViewRowInfo In gv.Rows
                    linno += 1
                    strcode = clsCommon.myCstr(grow.Cells("Zone Code").Value)

                    If AutoGenerateDocCode = False Then
                        If clsCommon.myLen(strcode) <= 0 Then
                            Throw New Exception("Fill Zone Code At Line No. " + clsCommon.myCstr(linno) + ".")
                        End If
                        If clsCommon.myLen(strcode) > 30 Then
                            Throw New Exception("Length of Zone Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    If clsCommon.myLen(grow.Cells("Location Code").Value) > 0 Then
                        Dim CityCode As String = ""
                        CityCode = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select Location_Code from TSPL_Location_MASTER where Location_Code='" + clsCommon.myCstr(grow.Cells("Location Code").Value) + "'", trans))
                        If clsCommon.myLen(CityCode) <= 0 Then
                            Throw New Exception("Not a valid Location Code At Line No. " + clsCommon.myCstr(linno) + ".")
                        End If
                    End If

                    'If clsCommon.myLen(grow.Cells("RSM CODE").Value) > 0 Then
                    '    Dim RSMCode As String = ""
                    '    RSMCode = clsCommon.myCstr(clsDBFuncationality.getSingleValue("select EMP_CODE from TSPL_EMPLOYEE_MASTER where EMP_CODE='" + clsCommon.myCstr(grow.Cells("RSM CODE").Value) + "'", trans))
                    '    If clsCommon.myLen(RSMCode) <= 0 Then
                    '        Throw New Exception("Not a valid RSM Code At Line No. " + clsCommon.myCstr(linno) + ".")
                    '    End If
                    'End If


                    Dim obj As New ClsZoneMaster()
                    obj.Zone_Code = strcode
                    obj.Description = clsCommon.myCstr(grow.Cells("Zone Description").Value)
                    obj.Location_CODE = clsCommon.myCstr(grow.Cells("Location Code").Value)
                    'obj.RSM_CODE = clsCommon.myCstr(grow.Cells("RSM CODE").Value)
                    Dim Count1 As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue("Select COunt(*) from TSPL_ZONE_MASTER WHERE zone_code='" + clsCommon.myCstr(strcode) + "'", trans))
                    If Count1 <= 0 Then
                        ClsZoneMaster.SaveData(obj, True, trans)
                    Else
                        ClsZoneMaster.SaveData(obj, False, trans)
                    End If

                Next
                trans.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                trans.Rollback()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub fndRSM__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles fndRSM._MYValidating
        Try
            Dim qry As String = " Select EMP_CODE as Code,Emp_Name as Name from TSPL_EMPLOYEE_MASTER  "
            fndRSM.Value = clsCommon.ShowSelectForm("RSM@Finder@ZoneMaster", qry, "Code", "", fndRSM.Value, "Code", isButtonClicked)
            If clsCommon.myLen(fndRSM.Value) > 0 Then
                lblRSM.Text = clsDBFuncationality.getSingleValue("Select Emp_Name as Name from  TSPL_EMPLOYEE_MASTER  where EMP_CODE = '" + fndRSM.Value + "'")
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try

    End Sub

    Private Sub txtdesHindi_Leave(sender As Object, e As EventArgs) Handles txtdesHindi.Leave
        clsMccMaster.ToEnglishInput()
    End Sub

    Private Sub txtdesHindi_Enter(sender As Object, e As EventArgs) Handles txtdesHindi.Enter
        clsMccMaster.ToHindiInput()
    End Sub

    Private Sub Export_Click(sender As Object, e As EventArgs) Handles Export.Click
        Try
            Dim str As String
            'str = "select TSPL_ZONE_MASTER.zone_code as [Zone Code],TSPL_ZONE_MASTER.Description as [Zone Description],TSPL_ZONE_MASTER.City_Code as [City Code],TSPL_CITY_MASTER.City_Name as [City Name], RSM_CODE as [RSM CODE] , TSPL_EMPLOYEE_MASTER.Emp_Name as [RSM Name]  from TSPL_ZONE_MASTER left outer join TSPL_CITY_MASTER on TSPL_CITY_MASTER.City_Code=TSPL_ZONE_MASTER.City_Code left outer join TSPL_EMPLOYEE_MASTER on  TSPL_EMPLOYEE_MASTER.EMP_CODE = TSPL_ZONE_MASTER.RSM_CODE "
            str = "select TSPL_ZONE_MASTER.zone_code as [Zone Code],TSPL_ZONE_MASTER.Description as [Zone Description],TSPL_ZONE_MASTER.Location_Code as [Location Code],TSPL_Location_MASTER.Location_Desc as [Location Name]  from TSPL_ZONE_MASTER left outer join TSPL_Location_MASTER on TSPL_Location_MASTER.Location_Code=TSPL_ZONE_MASTER.Location_Code "
            ListImpExpColumnsMandatory = New List(Of String)({"Zone Code"})
            ListImpExpColumnsSuperMandatory = New List(Of String)({"Zone Code"})
            transportSql.ExporttoExcel(str, "", "", Me, ListImpExpColumnsMandatory, ListImpExpColumnsSuperMandatory, MyBase.Form_ID)
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
End Class
