Imports common
Imports System.Data
Imports System.Data.SqlClient



Public Class frmGSTunitMeasure
    Inherits FrmMainTranScreen

    Private isNewEntry As Boolean = False
    'Private Sub btnSave1_Click(sender As Object, e As EventArgs)
    '    Try

    '    Catch ex As Exception

    '    End Try
    'End Sub

    Sub funReset()
        isNewEntry = True
        txtCode1.MyReadOnly = False
        txtCode1.Value = Nothing
        txtCode1.Focus()
        txtName1.Text = ""
        btnSave1.Text = "Save"
        btnSave1.Enabled = True
        btnDelete1.Enabled = False
    End Sub
    Private Sub btnSave1_Click(sender As Object, e As EventArgs) Handles btnSave1.Click
        If clsCommon.myLen(txtcode1.Value) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "Please Enter  Code.", Me.Text)
            lblcode.Focus()
            Exit Sub
        End If
        If clsCommon.myLen(txtName1.Text) <= 0 Then
            common.clsCommon.MyMessageBoxShow(Me, "Please select Name", Me.Text)
            txtName1.Focus()
            Exit Sub
        End If
        Try
            If AllowToSave() Then
                Dim isNewEntry As Boolean = False
                Dim trans As SqlTransaction = Nothing
                Dim obj As New clsGstunitMeasure()
                obj.Code = txtcode1.Value
                obj.Description = txtName1.Text

                If clsCommon.myLen(txtcode1.Value) > 0 Then
                    Dim sqlqry As String = "select Code, Description from TSPL_EINVOICE_UOM where Code='" + obj.Code + "'"
                    Dim dt As DataTable = clsDBFuncationality.GetDataTable(sqlqry)
                    If dt.Rows.Count > 0 Then
                        isNewEntry = False
                    Else
                        isNewEntry = True
                    End If
                End If
                clsGstunitMeasure.SaveData(obj, isNewEntry, trans)
                common.clsCommon.MyMessageBoxShow(Me, "Data Saved Successfully", Me.Text)
                btnSave1.Text = "Save"
                btnDelete1.Enabled = True
            Else
                btnSave1.Text = "Save"
                btnDelete1.Enabled = False
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
    End Sub
    Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) AndAlso clsCommon.myLen(txtcode1.Value) <= 0 Then
            myMessages.blankValue(Me, "Code", Me.Text)
            lblcode.Focus()
            Return False
            'End If
        ElseIf clsCommon.myLen(txtcode1.Value) > 30 Then
            clsCommon.MyMessageBoxShow(Me, "Code Max Length should be 30", Me.Text)
            lblcode.Focus()
            Return False
        ElseIf clsCommon.myLen(txtName1.Text) <= 0 Then
            myMessages.blankValue(Me, "Description", Me.Text)
            txtName1.Focus()
            Return False
        End If
        Return True
    End Function
    'Public Sub Save()
    '    Try
    '        If AllowToSave() Then
    '            Dim isNewEntry As Boolean = False
    '            Dim trans As SqlTransaction = Nothing
    '            Dim obj As New clsGstunitMeasure()
    '            obj.Code = txtCode1.Value
    '            obj.Description = txtName1.Text

    '            If clsCommon.myLen(txtCode1.Value) > 0 Then
    '                Dim sqlqry As String = "select Code, Description from TSPL_EINVOICE_UOM where Code='" + obj.Code + "'"
    '                Dim dt As DataTable = clsDBFuncationality.GetDataTable(sqlqry)
    '                If dt.Rows.Count > 0 Then
    '                    isNewEntry = False
    '                Else
    '                    isNewEntry = True
    '                End If
    '            End If
    '            clsGstunitMeasure.SaveData(obj, isNewEntry, trans)
    '            'clsGstunitMeasure.SaveDataMeasure(obj, isNewEntry, trans)

    '            'If clsCommon.myLen(txtCode1.Value) > 0 Then
    '            '    Dim sqlqry As String = "select Code, Description from TSPL_EINVOICE_UOM "
    '            '    'Dim sqlqry As String = " Update TSPL_EINVOICE_UOM Set Code ='" & clsCommon.myCstr(txtCode1.Value) & "'  where Code='" + txtCode1.Value + "'"
    '            '    clsDBFuncationality.ExecuteNonQuery(sqlqry)
    '            'End If
    '            'If clsCommon.myLen(txtCode1.Value) > 0 Then
    '            '    'Dim sqlqry As String = "select Code as code, Description as Description from TSPL_EINVOICE_UOM "
    '            '    Dim qry As String = "insert into TSPL_EINVOICE_UOM(Code, Description) values('" & clsCommon.myCstr(txtCode1.Value) & "','" & clsCommon.myCstr(txtName1.Text) & "' ) "
    '            '    'Dim qry As String = "insert into TSPL_EINVOICE_UOM(Code, Description) values('" + txtCode1.Value + "','" + txtName1.Text + "' ) "
    '            '    'Dim sqlqry As String = " Update TSPL_EINVOICE_UOM Set Code ='" & clsCommon.myCstr(txtCode1.Value) & "'  where Code='" + txtCode1.Value + "'"
    '            '    clsDBFuncationality.ExecuteNonQuery(qry)
    '            'End If
    '            common.clsCommon.MyMessageBoxShow("Data Saved Successfully")
    '            btnSave1.Text = "Save"
    '            btnDelete1.Enabled = True
    '        Else
    '            btnSave1.Text = "Save"
    '            btnDelete1.Enabled = False
    '        End If
    '    Catch ex As Exception
    '        myMessages.myExceptions(ex)
    '    End Try
    'End Sub
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        txtCode1.MyReadOnly = True
        btnSave1.Enabled = True
        btnDelete1.Enabled = True
        isNewEntry = False
        Dim obj As New clsGstunitMeasure()
        obj = clsGstunitMeasure.GetData(strCode, NavTyep)
        If (obj IsNot Nothing AndAlso clsCommon.myLen(obj.Code) > 0) Then
            'funReset()
            isNewEntry = False
            btnSave1.Text = "Update"
            btnDelete1.Enabled = True
            txtCode1.Value = obj.Code
            txtName1.Text = obj.Description
        End If
    End Sub

    Private Sub btnDelete1_Click(sender As Object, e As EventArgs) Handles btnDelete1.Click
        Try
            If clsCommon.myLen(txtcode1.Value) <= 0 Then
                common.clsCommon.MyMessageBoxShow(Me, "You Cannot Delete Record", Me.Text)
                Exit Sub
            End If
            If (myMessages.deleteConfirm()) Then
                If (clsGstunitMeasure.DeleteData(txtcode1.Value)) Then
                    common.clsCommon.MyMessageBoxShow(Me, "Data Deleted Successfully ", Me.Text)
                    funReset()
                End If
            End If
        Catch ex As Exception
            myMessages.myExceptions(ex)
        End Try
        'DeleteData()
    End Sub
    'Sub DeleteData()
    '    If clsCommon.myLen(txtCode1.Value) <= 0 Then
    '        common.clsCommon.MyMessageBoxShow("You Cannot Delete Record")
    '        Exit Sub
    '    End If
    '    ' Code Ends 
    '    'funDelete()

    'End Sub
    'Sub funDelete()
    '    Try
    '        If (myMessages.deleteConfirm()) Then
    '            If (clsGstunitMeasure.DeleteDataMeasure(txtCode1.Value)) Then
    '                common.clsCommon.MyMessageBoxShow(me,"Data Deleted Successfully ",me.text)
    '                funReset()
    '            End If
    '        End If
    '    Catch ex As Exception
    '        myMessages.myExceptions(ex)
    '    End Try

    'End Sub
    'Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsGstunitMeasure
    '    Dim obj As clsGstunitMeasure = Nothing
    '    Dim qry As String = "select TSPL_EINVOICE_UOM.* from TSPL_EINVOICE_UOM  where 2=2 "
    '    Dim whrclas As String = ""
    '    Select Case NavType
    '        Case NavigatorType.First
    '            qry += " and TSPL_EINVOICE_UOM.Code = (select MIN(Code) from TSPL_EINVOICE_UOM WHERE 1=1 " + whrclas + " )"
    '        Case NavigatorType.Last
    '            qry += " and TSPL_EINVOICE_UOM.Code = (select Max(Code) from TSPL_EINVOICE_UOM WHERE 1=1 " + whrclas + " )"
    '        Case NavigatorType.Current
    '            qry += " and TSPL_EINVOICE_UOM.Code = (select TOP 1 Code from TSPL_EINVOICE_UOM WHERE 1=1 " + whrclas + " and Code='" + strCode + "' )"
    '        Case NavigatorType.Next
    '            qry += " and TSPL_EINVOICE_UOM.Code = (select Min(Code) from TSPL_EINVOICE_UOM where Code > '" + strCode + "' " + whrclas + ")"
    '        Case NavigatorType.Previous
    '            qry += " and TSPL_EINVOICE_UOM.Code = (select Max(Code) from TSPL_EINVOICE_UOM where Code < '" + strCode + "' " + whrclas + ")"
    '    End Select
    '    Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry)
    '    'If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
    '    '    obj = New clsUnitMaster()
    '    '    obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
    '    '    obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))

    '    'End If
    '    Return obj
    'End Function

    Private Sub btnreset_Click(sender As Object, e As EventArgs)
        funReset()
    End Sub
    'Sub funReset1()
    '    isNewEntry = True
    '    txtCode1.MyReadOnly = False
    '    txtCode1.Value = Nothing
    '    txtCode1.Focus()
    '    txtName1.Text = ""
    '    btnSave1.Text = "Save"
    '    btnSave1.Enabled = True
    '    btnDelete1.Enabled = False
    'End Sub


    Private Sub txtCode1__MYValidating(sender As Object, e As EventArgs, isButtonClicked As Boolean) Handles txtcode1._MYValidating
        Dim str As String = "select count(*) from TSPL_EINVOICE_UOM where Code ='" + txtcode1.Value + "' "
        Dim no As Integer = clsCommon.myCdbl(clsDBFuncationality.getSingleValue(str))
        If no = 0 AndAlso isButtonClicked = False Then
            txtcode1.MyReadOnly = False
        Else
            txtcode1.MyReadOnly = True
        End If
        If txtcode1.MyReadOnly OrElse isButtonClicked Then
            txtcode1.Value = clsGstunitMeasure.getFinder("", txtcode1.Value, isButtonClicked)
            If txtcode1.Value <> "" Then
                LoadData(txtcode1.Value, NavigatorType.Current)
            Else
                funReset()
            End If
        End If

    End Sub

    Private Sub txtCode1__MYNavigator(sender As Object, e As EventArgs, NavType As NavigatorType) Handles txtcode1._MYNavigator
        Try
            LoadData(txtcode1.Value, NavType)
        Catch ex As Exception
            common.clsCommon.MyMessageBoxShow(Me, ex.Message, Me.Text)
        End Try
    End Sub

    Private Sub btnclose1_Click(sender As Object, e As EventArgs) Handles btnClose1.Click
        Me.Close()
    End Sub

    Private Sub MenuItemImport_Click(sender As Object, e As EventArgs) Handles MenuItemImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)
        Dim currentdate As Date = Date.Today
        If transportSql.importExcel(gv, "Code", "Description") Then
            Try
                clsCommon.ProgressBarShow()
                Dim tran As SqlTransaction = clsDBFuncationality.GetTransactin()
                Dim ii As Integer = 0
                Try
                    For Each grow As GridViewRowInfo In gv.Rows
                        ii = ii + 1
                        Dim obj As New clsGstunitMeasure()
                        obj.Code = clsCommon.myCstr(grow.Cells("Code").Value)
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Code can not be blank or incorrect.")
                        End If

                        obj.Description = clsCommon.myCstr(grow.Cells("Description").Value)
                        If clsCommon.myLen(obj.Description) <= 0 Then
                            Throw New Exception("Description can not be blank or incorrect.")
                        End If

                        clsGstunitMeasure.SaveData(obj, clsGstunitMeasure.CheckNewEntry(obj.Code, tran), tran)
                    Next
                Catch ex As Exception
                    tran.Rollback()
                    Throw New Exception("At Row No" + clsCommon.myCstr(ii) + ex.Message)
                End Try
                tran.Commit()
                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow(Me, "Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception
                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)
    End Sub

    Private Sub MenuItemExport_Click(sender As Object, e As EventArgs) Handles MenuItemExport.Click
        Dim str As String
        str = "select Code, Description from TSPL_EINVOICE_UOM"
        transportSql.ExporttoExcel(str, Me)
    End Sub

    Private Sub btnNew1_Click(sender As Object, e As EventArgs) Handles btnNew1.Click
        funReset()
    End Sub
End Class