
Imports System.Data.SqlClient
Imports common
Public Class ClsCostCenter
#Region "variables"
    Public Cost_Code As String = Nothing
    Public Cost_name As String = Nothing
    Public CostCenter_Code As String = Nothing
    Public GL_Account_Code As String = Nothing
#End Region


    '' Anubhooti 08-Sep-2014 (Fetches ,TSPL_CostCenter_MASTER.CostCenter_Code AS [Cost Center Group],TSPL_CostCenter_MASTER.GL_Account_Code As [GL Account Code])
    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_CostCenter_MASTER.Cost_Code as [Code] ,TSPL_CostCenter_MASTER.Cost_name as [Cost Name],TSPL_CostCenter_MASTER.CostCenter_Code AS [Cost Center Group],TSPL_CostCenter_MASTER.GL_Account_Code As [GL Account Code]  From TSPL_CostCenter_MASTER   "
        str = clsCommon.ShowSelectForm("CSTCNTRMST", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function SaveData(ByVal obj As ClsCostCenter, ByVal isNewEntry As Boolean) As Boolean
        Dim qry As String = ""
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            SaveData(obj, isNewEntry, trans)
            trans.Commit()
        Catch err As Exception
            trans.RollBack()
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function

    Public Shared Function SaveData(ByVal obj As ClsCostCenter, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""

        Try
            'If isNewEntry Then
            '    qry = "select  MAX(Cost_Code)  from TSPL_CostCenter_MASTER"
            '    obj.Cost_Code = clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
            '    If clsCommon.myLen(obj.Cost_Code) <= 0 Then
            '        obj.Cost_Code = "IM00000000001"
            '    Else
            '        obj.Cost_Code = clsCommon.incval(obj.Cost_Code)
            '    End If
            'End If
            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "Cost_name", obj.Cost_name)
            clsCommon.AddColumnsForChange(coll, "CostCenter_Code", obj.CostCenter_Code, True)
            clsCommon.AddColumnsForChange(coll, "GL_Account_Code", obj.GL_Account_Code, True)
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
           
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
            If isNewEntry Then
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy hh:mm tt"))
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_CostCenter_MASTER where Cost_Code='" & obj.Cost_Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Cost_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.CostCenter, "", "")
                        If clsCommon.myLen(obj.Cost_Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Cost_Code", obj.Cost_Code)
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_CostCenter_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_CostCenter_MASTER", OMInsertOrUpdate.Update, "TSPL_CostCenter_MASTER.Cost_Code='" + obj.Cost_Code + "'", trans)
            End If
        Catch err As Exception
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function


    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsCostCenter
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsCostCenter
        Dim obj As ClsCostCenter = Nothing
        Dim Arr As List(Of ClsCostCenter) = Nothing
        Dim qry As String = "select Cost_Code ,Cost_name,CostCenter_Code,GL_Account_Code from TSPL_CostCenter_MASTER where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_CostCenter_MASTER.Cost_Code = (select MIN(Cost_Code) from TSPL_CostCenter_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_CostCenter_MASTER.Cost_Code = (select Max(Cost_Code) from TSPL_CostCenter_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_CostCenter_MASTER.Cost_Code = (select top 1 Cost_Code from TSPL_CostCenter_MASTER WHERE 1=1 " + whrclas + " and Cost_Code='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_CostCenter_MASTER.Cost_Code = (select Min(Cost_Code) from TSPL_CostCenter_MASTER where Cost_Code>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_CostCenter_MASTER.Cost_Code = (select Max(Cost_Code) from TSPL_CostCenter_MASTER where Cost_Code<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsCostCenter()
            obj.Cost_Code = clsCommon.myCstr(dt.Rows(0)("Cost_Code"))
            obj.Cost_name = clsCommon.myCstr(dt.Rows(0)("Cost_name"))
            '' Anubhooti 08-Sep-2014 (Fetch CostCenter_Code,GL_Account_Code)
            obj.CostCenter_Code = clsCommon.myCstr(dt.Rows(0)("CostCenter_Code"))
            obj.GL_Account_Code = clsCommon.myCstr(dt.Rows(0)("GL_Account_Code"))
        End If
        Return obj
    End Function

    Public Shared Function GetCostCenterDesc(ByVal CostCenterCode As String) As String
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(" Select Cost_name From TSPL_CostCenter_MASTER Where TSPL_CostCenter_MASTER.Cost_Code= '" + CostCenterCode + "'"))
    End Function
End Class
Public Class ClsFACostCenter
#Region "variables"
    Public Cost_Code As String = Nothing
    Public Cost_name As String = Nothing
#End Region

    Public Shared Function SaveData(ByVal obj As ClsFACostCenter, ByVal isNewEntry As Boolean, ByVal trans As SqlTransaction) As Boolean
        Dim qry As String = ""

        Try
            'If isNewEntry Then
            '    qry = "select  MAX(Cost_Code)  from TSPL_FA_COST_CENTER_MASTER"
            '    obj.Cost_Code = clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
            '    If clsCommon.myLen(obj.Cost_Code) <= 0 Then
            '        obj.Cost_Code = "IM00000000001"
            '    Else
            '        obj.Cost_Code = clsCommon.incval(obj.Cost_Code)
            '    End If
            'End If
            Dim coll As New Hashtable()

            clsCommon.AddColumnsForChange(coll, "CostCenter_Name", obj.Cost_name)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_FA_COST_CENTER_MASTER where CostCenter_Code='" & obj.Cost_Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Cost_Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.FACostCenter, "", "")
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommon.AddColumnsForChange(coll, "CostCenter_Code", obj.Cost_Code)
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_FA_COST_CENTER_MASTER", OMInsertOrUpdate.Insert, "", trans)
            Else
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_FA_COST_CENTER_MASTER", OMInsertOrUpdate.Update, "TSPL_FA_COST_CENTER_MASTER.CostCenter_Code='" + obj.Cost_Code + "'", trans)
            End If

        Catch err As Exception

            Throw New Exception(err.Message)
        End Try
        Return True
    End Function


    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsFACostCenter
        Return GetData(strCode, NavType, Nothing)
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsFACostCenter
        Dim obj As ClsFACostCenter = Nothing
        Dim Arr As List(Of ClsFACostCenter) = Nothing
        Dim qry As String = "select CostCenter_Code ,CostCenter_Name from TSPL_FA_COST_CENTER_MASTER where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_FA_COST_CENTER_MASTER.CostCenter_Code = (select MIN(CostCenter_Code) from TSPL_FA_COST_CENTER_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_FA_COST_CENTER_MASTER.CostCenter_Code = (select Max(CostCenter_Code) from TSPL_FA_COST_CENTER_MASTER WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_FA_COST_CENTER_MASTER.CostCenter_Code = (select top 1 CostCenter_Code from TSPL_FA_COST_CENTER_MASTER WHERE 1=1 " + whrclas + " and CostCenter_Code='" + strCode + "' )"
            Case NavigatorType.Next
                qry += " and TSPL_FA_COST_CENTER_MASTER.CostCenter_Code = (select Min(CostCenter_Code) from TSPL_FA_COST_CENTER_MASTER where CostCenter_Code>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_FA_COST_CENTER_MASTER.CostCenter_Code = (select Max(CostCenter_Code) from TSPL_FA_COST_CENTER_MASTER where CostCenter_Code<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsFACostCenter()
            obj.Cost_Code = clsCommon.myCstr(dt.Rows(0)("CostCenter_Code"))
            obj.Cost_name = clsCommon.myCstr(dt.Rows(0)("CostCenter_name"))

        End If
        Return obj
    End Function

    Public Shared Function GetCostCenterDesc(ByVal CostCenterCode As String) As String
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(" Select CostCenter_name From TSPL_FA_COST_CENTER_MASTER Where TSPL_FA_COST_CENTER_MASTER.CostCenter_Code= '" + CostCenterCode + "'"))
    End Function
End Class
