Imports common
Imports System.Data
Imports System.Data.SqlClient
Public Class clsOTMaster

#Region "Variables"
    Public Code As String
    Public Description As String
    Public Name As String
    Public HOUR_MULTIPLIER As Double
    Public OT_RATE As Double
    Public IS_ASPER_ACTUAL_CALC As Int16

#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_OT_MASTER.OT_CODE as [Code] ,TSPL_OT_MASTER.OT_NAME as [OT Name] ,TSPL_OT_MASTER.HOUR_MULTIPLIER as [Hour Multiplier] ,TSPL_OT_MASTER.OT_RATE as [OT Rate] ,TSPL_OT_MASTER.IS_ASPER_ACTUAL_CALC as [Is As Per Actual Calculation] ,TSPL_OT_MASTER.DESCRIPTION as [Description] ,TSPL_OT_MASTER.Created_By as [Created By] ,TSPL_OT_MASTER.Created_Date as [Created Date] ,TSPL_OT_MASTER.Modified_By as [Modified By] ,TSPL_OT_MASTER.Modified_Date as [Modified Date]  From TSPL_OT_MASTER   "
        str = clsCommon.ShowSelectForm("OTMST", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    '----------------End of Code For Get Finder--------------------------------------------------------------'
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As clsOTMaster
        Return GetData(strCode, NavType, Nothing)
    End Function
    Public Shared Function DeleteData(ByVal strCode As String) As Boolean
        Dim isSaved As Boolean

        Try
            isSaved = False

            If (clsCommon.myLen(strCode) <= 0) Then
                Throw New Exception("Code not found to Delete")
            End If

            Dim qry As String
            qry = "delete from TSPL_OT_MASTER where OT_CODE ='" + strCode + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry)


        Catch ex As Exception

            common.clsCommon.MyMessageBoxShow(ex.Message.ToString())
        End Try
        Return isSaved
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As clsOTMaster
        Dim obj As clsOTMaster = Nothing
        Dim qry As String = "select * from TSPL_OT_MASTER where 2=2"
        Select Case NavType
            Case NavigatorType.First
                qry += " and OT_CODE = (select MIN(OT_CODE) from TSPL_OT_MASTER)"
            Case NavigatorType.Last
                qry += " and OT_CODE = (select Max(OT_CODE) from TSPL_OT_MASTER)"
            Case NavigatorType.Next
                qry += " and OT_CODE = (select Min(OT_CODE) from TSPL_OT_MASTER where  OT_CODE>'" + strCode + "')"
            Case NavigatorType.Previous
                qry += " and OT_CODE = (select Max(OT_CODE) from TSPL_OT_MASTER where OT_CODE<'" + strCode + "')"
            Case NavigatorType.Current
                qry += " and OT_CODE = '" + strCode + "'"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)

        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New clsOTMaster()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("OT_CODE"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("DESCRIPTION"))
            obj.Name = clsCommon.myCstr(dt.Rows(0)("OT_NAME"))
            obj.HOUR_MULTIPLIER = clsCommon.myCdbl(dt.Rows(0)("HOUR_MULTIPLIER"))
            obj.OT_RATE = clsCommon.myCdbl(dt.Rows(0)("OT_RATE"))
            obj.IS_ASPER_ACTUAL_CALC = Convert.ToInt32(clsCommon.myCdbl(dt.Rows(0)("IS_ASPER_ACTUAL_CALC")))
            
        End If
        Return obj


    End Function

    Public Function SaveData(ByVal obj As clsOTMaster, ByVal isNewEntry As Boolean) As Boolean
        Dim isSaved As Boolean = True
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "OT_NAME", obj.Name)
            clsCommon.AddColumnsForChange(coll, "DESCRIPTION", obj.Description)
            clsCommon.AddColumnsForChange(coll, "HOUR_MULTIPLIER", obj.HOUR_MULTIPLIER)
            clsCommon.AddColumnsForChange(coll, "OT_RATE", obj.OT_RATE)
            clsCommon.AddColumnsForChange(coll, "IS_ASPER_ACTUAL_CALC", obj.IS_ASPER_ACTUAL_CALC)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_OT_MASTER where OT_CODE='" & obj.Code & "'")
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(Nothing, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MM/yyyy"), clsDocType.OTMaster, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "OT_CODE", obj.Code)
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(), "dd/MMM/yyyy"))
                Dim qry As String = "SELECT Count(*) FROM TSPL_OT_MASTER where OT_CODE= '" & obj.Code & "'"
                Dim check As Integer = clsDBFuncationality.getSingleValue(qry)
                If check = 0 Then
                    isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_OT_MASTER", OMInsertOrUpdate.Insert, "")
                Else
                    Throw New Exception("This Code Is Already Exist")

                End If

            Else
                isSaved = isSaved AndAlso clsCommonFunctionality.UpdateDataTable(coll, "TSPL_OT_MASTER", OMInsertOrUpdate.Update, "OT_CODE='" + obj.Code + "'")
            End If

        Catch ex As Exception
            Throw New Exception(ex.Message)
        End Try
        Return isSaved
    End Function

    Public Shared Function GetName(ByVal strCode As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "select OT_NAME from TSPL_OT_MASTER where OT_CODE = '" + strCode + "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
    End Function
    Public Shared Function GetOTRate_ByOTCode(ByVal strCode As String, ByVal trans As SqlTransaction) As String
        Dim qry As String = "select OT_RATE from TSPL_OT_MASTER where OT_CODE = '" + strCode + "'"
        Return clsCommon.myCstr(clsDBFuncationality.getSingleValue(qry, trans))
    End Function

    Public Shared Function CheckNewEntry(ByVal Code As String, Optional ByVal trans As SqlTransaction = Nothing) As String
        Dim qry As String = "select OT_CODE from TSPL_OT_MASTER where OT_CODE ='" + Code + "'   "
        Dim dt As DataTable
        dt = clsDBFuncationality.GetDataTable(qry)
        If dt.Rows.Count > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
End Class
