'--------Created By Richa 10/12/2014 Against Ticket No BM00000004964

Imports common
Imports System.Data.SqlClient
Public Class ClsMerchantPaymentTerms
#Region "variables"
    Public Code As String = Nothing
    Public Description As String = Nothing
    Public TermsType As String = Nothing
#End Region

    '----------------Code For Get Finder--------------------------------------------------------------------'
    Public Shared Function getFinder(ByVal whrcls As String, ByVal curcode As String, ByVal isButtonClicked As Boolean) As String
        Dim str As String = ""
        Dim qry As String = " select TSPL_PAYMENT_TERMS_MASTER_MT.Code,TSPL_PAYMENT_TERMS_MASTER_MT.Description,CASE WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='A' THEN 'Advance' WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='O' THEN 'On Account' WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='L' THEN 'LC' WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='B' THEN 'Balance Payment' WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='R' THEN 'Retained' WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='C' THEN 'CAD'  WHEN TSPL_PAYMENT_TERMS_MASTER_MT.TermsType='CI' THEN 'CIF' ELSE '' END AS [Terms Type] , TSPL_PAYMENT_TERMS_MASTER_MT.Created_By as [Created By] ,convert(varchar,TSPL_PAYMENT_TERMS_MASTER_MT.Created_Date,103) as [Created Date],TSPL_PAYMENT_TERMS_MASTER_MT.Modified_By as [Modified By],convert(Varchar,TSPL_PAYMENT_TERMS_MASTER_MT.Modified_Date,103) as [Modified Date] ,TSPL_PAYMENT_TERMS_MASTER_MT.Comp_Code as [Comp Code] from TSPL_PAYMENT_TERMS_MASTER_MT"
        str = clsCommon.ShowSelectForm("MPaymentTerms", qry, "Code", whrcls, curcode, "Code", isButtonClicked)
        Return str
    End Function
    Public Shared Function SaveData(ByVal obj As ClsMerchantPaymentTerms, ByVal isNewEntry As Boolean) As Boolean
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Try
            Dim coll As New Hashtable()
            clsCommon.AddColumnsForChange(coll, "Description", obj.Description)
            clsCommon.AddColumnsForChange(coll, "TermsType", obj.TermsType)
            clsCommon.AddColumnsForChange(coll, "Comp_Code", objCommonVar.CurrentCompanyCode)
            clsCommon.AddColumnsForChange(coll, "Modified_By", objCommonVar.CurrentUserCode)
            clsCommon.AddColumnsForChange(coll, "Modified_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
            If isNewEntry Then
                If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, trans)) = "1", True, False)) Then
                    Dim ChkNewEntry As String = clsDBFuncationality.getSingleValue("Select count(*) from TSPL_PAYMENT_TERMS_MASTER_MT where Code='" & obj.Code & "'", trans)
                    If ChkNewEntry = 0 Then
                        obj.Code = clsERPFuncationality.GetNextCode(trans, clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MM/yyyy"), clsDocType.MerchantPaymentTerms, "", "")
                        If clsCommon.myLen(obj.Code) <= 0 Then
                            Throw New Exception("Error in Code Generation")
                        End If
                    End If
                End If
                clsCommon.AddColumnsForChange(coll, "Created_By", objCommonVar.CurrentUserCode)
                clsCommon.AddColumnsForChange(coll, "Created_Date", clsCommon.GetPrintDate(clsCommon.GETSERVERDATE(trans), "dd/MMM/yyyy"))
                clsCommon.AddColumnsForChange(coll, "Code", obj.Code)
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PAYMENT_TERMS_MASTER_MT", OMInsertOrUpdate.Insert, "", trans)
            Else
                clsCommonFunctionality.UpdateDataTable(coll, "TSPL_PAYMENT_TERMS_MASTER_MT", OMInsertOrUpdate.Update, "TSPL_PAYMENT_TERMS_MASTER_MT.Code='" + obj.Code + "'", trans)
            End If
            trans.Commit()
        Catch err As Exception
            trans.Rollback()
            Throw New Exception(err.Message)
        End Try
        Return True
    End Function

    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType) As ClsMerchantPaymentTerms
        Return GetData(strCode, NavType, Nothing)
    End Function
    Public Shared Function GetData(ByVal strCode As String, ByVal NavType As NavigatorType, ByVal trans As SqlTransaction) As ClsMerchantPaymentTerms
        Dim obj As ClsMerchantPaymentTerms = Nothing
        Dim Arr As List(Of ClsMerchantPaymentTerms) = Nothing
        Dim qry As String = "select TSPL_PAYMENT_TERMS_MASTER_MT.Code,TSPL_PAYMENT_TERMS_MASTER_MT.Description,TSPL_PAYMENT_TERMS_MASTER_MT.TermsType from TSPL_PAYMENT_TERMS_MASTER_MT where 2=2 "
        Dim whrclas As String = ""
        Select Case NavType
            Case NavigatorType.First
                qry += " and TSPL_PAYMENT_TERMS_MASTER_MT.Code = (select MIN(Code) from TSPL_PAYMENT_TERMS_MASTER_MT WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Last
                qry += " and TSPL_PAYMENT_TERMS_MASTER_MT.Code = (select Max(Code) from TSPL_PAYMENT_TERMS_MASTER_MT WHERE 1=1 " + whrclas + " )"
            Case NavigatorType.Current
                qry += " and TSPL_PAYMENT_TERMS_MASTER_MT.Code = '" + strCode + "' "
            Case NavigatorType.Next
                qry += " and TSPL_PAYMENT_TERMS_MASTER_MT.Code = (select Min(Code) from TSPL_PAYMENT_TERMS_MASTER_MT where Code>'" + strCode + "' " + whrclas + ")"
            Case NavigatorType.Previous
                qry += " and TSPL_PAYMENT_TERMS_MASTER_MT.Code = (select Max(Code) from TSPL_PAYMENT_TERMS_MASTER_MT where Code<'" + strCode + "' " + whrclas + ")"
        End Select
        Dim dt As DataTable = clsDBFuncationality.GetDataTable(qry, trans)
        If (dt IsNot Nothing AndAlso dt.Rows.Count > 0) Then
            obj = New ClsMerchantPaymentTerms()
            obj.Code = clsCommon.myCstr(dt.Rows(0)("Code"))
            obj.Description = clsCommon.myCstr(dt.Rows(0)("Description"))
            obj.TermsType = clsCommon.myCstr(dt.Rows(0)("TermsType"))

        End If
        Return obj
    End Function
    Public Shared Function DeleteData(ByVal strDocNo As String) As Boolean
        Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
        Dim isSaved As Boolean = False
        If (clsCommon.myLen(strDocNo) <= 0) Then
            Throw New Exception("Document No not found to Delete")
        End If
        Try
            Dim qry As String = "delete from TSPL_PAYMENT_TERMS_MASTER_MT where Code='" + strDocNo + "'"
            isSaved = clsDBFuncationality.ExecuteNonQuery(qry, trans)
            trans.Commit()
        Catch ex As Exception
            trans.Rollback()
            Throw New Exception(ex.Message)
        End Try

        Return isSaved
    End Function
End Class
