Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.WinControls.UI
Imports Telerik.WinControls
Imports Telerik.WinControls.Data
Imports System.Text.RegularExpressions
Imports common
'''' <summary>
'''' ''''''''''''''''''''''''TicketNo='BM00000000480''''''''''''''''''''''''''''''''''''''''
'''' </summary>
'''' <remarks></remarks>

Public Class FrmItemProductionCategory
    Inherits FrmMainTranScreen
    Dim ButtonToolTip As ToolTip = New ToolTip()
    Private isNewEntry As Boolean = False
    Dim userCode, companyCode As String
#Region "Functions"
    Private Sub SetUserMgmtNew()
        ''MyBase.SetUserMgmt(clsUserMgtCode.ITEMCATEGORY)
        If Not (MyBase.isReadFlag) Then
            common.clsCommon.MyMessageBoxShow("Permission Denied")
            Me.Close()
            Exit Sub
        End If
        btnsave.Visible = MyBase.isModifyFlag
        '--------richa Ticket no. BM00000003014 02/07/2014 to enable/disable import/export option acc. to user mgmt setting -----------
        If btnsave.Visible = True Then
            rmExport.Enabled = True
            rmImport.Enabled = True
        Else
            rmExport.Enabled = False
            rmImport.Enabled = False
        End If
        '--------------------------------------------------
        'btnPost.Visible = MyBase.isPostFlag
        btndelete.Visible = MyBase.isDeleteFlag
    End Sub
    Sub LoadData(ByVal strCode As String, ByVal NavTyep As NavigatorType)
        Dim obj As ClsItemCategoryForproduction = ClsItemCategoryForproduction.GetData(strCode, NavTyep)
        If obj IsNot Nothing Then
            isNewEntry = False
            txtCode.Value = obj.PROD_ITEM_CATEGORY_CODE
            txtdes.Text = obj.DESCRIPTION
            txtName.Text = obj.PROD_ITEM_CATEGORY_NAME
            Me.cboItemGroup.SelectedValue = obj.ITEM_GROUP
            txtCode.MyReadOnly = True
        End If
    End Sub
    Sub SaveData()
        If AllowToSave() Then
            Dim trans As SqlTransaction = clsDBFuncationality.GetTransactin()
            Try
                Dim obj As New ClsItemCategoryForproduction()
                obj.PROD_ITEM_CATEGORY_CODE = txtCode.Value
                obj.PROD_ITEM_CATEGORY_NAME = txtName.Text
                obj.DESCRIPTION = txtdes.Text
                obj.ITEM_GROUP = Me.cboItemGroup.SelectedValue
                Dim qry As Integer = clsDBFuncationality.getSingleValue("select count(PROD_ITEM_CATEGORY_CODE) from TSPL_MF_PRODUCTION_ITEM_CATEGORY where PROD_ITEM_CATEGORY_CODE='" + obj.PROD_ITEM_CATEGORY_CODE + "'", trans)
                If (qry = 0) Then
                    isNewEntry = True
                Else
                    isNewEntry = False
                End If
                If (ClsItemCategoryForproduction.SaveData(obj, isNewEntry, trans)) Then
                    'trans.Commit()
                    clsCommon.MyMessageBoxShow("Data saved Successfully", Me.Text)
                    LoadData(obj.PROD_ITEM_CATEGORY_CODE, NavigatorType.Current)

                End If
        Catch ex As Exception
            trans.Rollback()
            clsCommon.MyMessageBoxShow(ex.Message, Me.Text)
            End Try
        End If
    End Sub

    Private Function AllowToSave() As Boolean
        If (IIf(clsCommon.myCstr(clsFixedParameter.GetData(clsFixedParameterType.AllowAutoGenerateDocNoInMaster, clsFixedParameterCode.AllowAutoGenerateDocNoInMaster, Nothing)) = "1", True, False) = False) Then
            If clsCommon.myLen(clsCommon.myCstr(txtCode.Value)) <= 0 Then
                txtCode.Focus()
                Throw New Exception("Please Fill  Code")
            End If
        End If
        If clsCommon.myLen(clsCommon.myCstr(txtName.Text)) <= 0 Then
            txtdes.Focus()
            Throw New Exception("Please Fill  Name")
        End If
        Return True
    End Function
    Private Sub DeleteData()
        Try
            If clsCommon.myLen(txtCode.Value) <= 0 Then
                Throw New Exception("  Code not found to delete")

            End If
            If clsCommon.MyMessageBoxShow("Do you want to delete  Code '" + txtCode.Value + "'", Me.Text, MessageBoxButtons.YesNo) = System.Windows.Forms.DialogResult.Yes Then

                Dim qry As String = "delete from TSPL_MF_PRODUCTION_ITEM_CATEGORY where PROD_ITEM_CATEGORY_CODE='" + txtCode.Value + "'"
                clsDBFuncationality.ExecuteNonQuery(qry)
                clsCommon.MyMessageBoxShow("Successfully Deleted", Me.Text)
                AddNew()
            End If
        Catch ex As Exception
            If (clsCommon.CompairString(clsCommon.myCstr(ex.Message), "Cost Code not found to delete") <> CompairStringResult.Equal) Then
                clsCommon.MyMessageBoxShow("Current Cost Code is in use")

            Else
                clsCommon.MyMessageBoxShow(ex.Message)
            End If
        End Try
    End Sub
    Sub AddNew()
        txtCode.Value = ""
        txtdes.Text = ""
        txtCode.MyReadOnly = False
        txtName.Text = ""
        Me.cboItemGroup.DataSource = ClsItemCategoryForproduction.GetProdItemGroupTable
        Me.cboItemGroup.DisplayMember = "Name"
        Me.cboItemGroup.ValueMember = "Code"
    End Sub

#End Region
#Region "Events"

    Private Sub btnsave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnsave.Click
        SaveData()
    End Sub

    Private Sub btndelete_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btndelete.Click
        DeleteData()
    End Sub

    Private Sub btnclose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnclose.Click
        Me.Close()
    End Sub

    Private Sub btnnew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnnew.Click
        AddNew()
    End Sub

    Private Sub txtCode__MYNavigator(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal NavType As common.NavigatorType) Handles txtCode._MYNavigator
        LoadData(txtCode.Value, NavType)
    End Sub

    Private Sub txtCode__MYValidating(ByVal sender As System.Object, ByVal e As System.EventArgs, ByVal isButtonClicked As System.Boolean) Handles txtCode._MYValidating
        If txtCode.MyReadOnly OrElse isButtonClicked Then

            'Dim qry As String = "select PROD_ITEM_CATEGORY_CODE as Code,PROD_ITEM_CATEGORY_NAME as Name from  TSPL_MF_PRODUCTION_ITEM_CATEGORY"
            'txtCode.Value = clsCommon.ShowSelectForm("TSPL_MF_PRODUCTION_ITEM_CATEGORY", qry, "Code", "", txtCode.Value, "", isButtonClicked)
            txtCode.Value = clsproductionItemCategory.getFinder("", txtCode.Value, isButtonClicked)
            LoadData(txtCode.Value, NavigatorType.Current)
        End If
    End Sub
    Private Sub FrmItemProductionCategory_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        SetUserMgmtNew()
        ButtonToolTip.SetToolTip(btnsave, "Press Alt+S for Save/Update ")
        ButtonToolTip.SetToolTip(btndelete, "Press Alt+D Delete ")
        ButtonToolTip.SetToolTip(btnclose, "Press Alt+C Close the Window")
        ButtonToolTip.SetToolTip(btnnew, "Press Alt+N Adding New ")
        ' globalFunc.mandatoryText(fnddesig.txtValue, txtdes)
        AddNew()
    End Sub

    Private Sub FrmItemProductionCategory_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.Alt AndAlso e.KeyCode = Keys.S AndAlso MyBase.isModifyFlag AndAlso btnsave.Enabled Then
            SaveData()
            'ElseIf e.Alt AndAlso e.KeyCode = Keys.P AndAlso MyBase.isPostFlag Then
            '    PostData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.D AndAlso MyBase.isDeleteFlag AndAlso btndelete.Enabled Then
            DeleteData()
        ElseIf e.Alt AndAlso e.KeyCode = Keys.C Then
            Close()
        ElseIf e.Alt And e.KeyCode = Keys.N Then
            AddNew()
        End If
    End Sub
#End Region
    '--------Preeti gupta--Ticket No.-BM00000002845--

    Private Sub rmImport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmImport.Click
        Dim gv As New RadGridView()
        Me.Controls.Add(gv)

        If transportSql.importExcel(gv, "PROD ITEM CATEGORY CODE", "PROD ITEM CATEGORY NAME", "DESCRIPTION", "ITEM GROUP") Then
            Dim linno As Integer = 0
            Try
                connectSql.OpenConnection()
                clsCommon.ProgressBarShow()

                Dim obj As New ClsItemCategoryForproduction()

                For Each grow As GridViewRowInfo In gv.Rows
                    linno += 1
                    Dim strItemCategorycode As String = clsCommon.myCstr(grow.Cells("PROD ITEM CATEGORY CODE").Value)
                    If (String.IsNullOrEmpty(strItemCategorycode)) Or clsCommon.myLen(strItemCategorycode) > 30 Then
                        Throw New Exception("Length of  Category Code should be max. 30 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.PROD_ITEM_CATEGORY_CODE = strItemCategorycode

                    Dim strCategoryName As String = clsCommon.myCstr(grow.Cells("PROD ITEM CATEGORY NAME").Value)
                    If (String.IsNullOrEmpty(strCategoryName)) Or clsCommon.myLen(strCategoryName) > 50 Then
                        Throw New Exception("Length of Category Name should be max. 50 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    End If
                    obj.PROD_ITEM_CATEGORY_NAME = strCategoryName

                    Dim strDescription As String = clsCommon.myCstr(grow.Cells("DESCRIPTION").Value)
                    obj.DESCRIPTION = strDescription

                    Dim strItemGroup As String = clsCommon.myCstr(grow.Cells("ITEM GROUP").Value)



                    If (String.IsNullOrEmpty(strItemGroup)) Or clsCommon.myLen(strItemGroup) > 50 Then
                        Throw New Exception("Length of Remarks should be max. 50 character At Line No. " + clsCommon.myCstr(linno) + ".")
                    ElseIf clsCommon.CompairString(strItemGroup, "GLASS") = CompairStringResult.Equal Or clsCommon.CompairString(strItemGroup, "Slice Glass") = CompairStringResult.Equal Or clsCommon.CompairString(strItemGroup, "Pet") = CompairStringResult.Equal Or clsCommon.CompairString(strItemGroup, "BIBS") = CompairStringResult.Equal Or clsCommon.CompairString(strItemGroup, "Can") = CompairStringResult.Equal Or clsCommon.CompairString(strItemGroup, "Others") = CompairStringResult.Equal Then
                    Else
                        Throw New Exception("Item Group should be amoung 'GLASS','SLICE GLASS','PET','BIBS','CAN,'OTHERS' At Line No. " + clsCommon.myCstr(linno) + ".")

                    End If
                    obj.ITEM_GROUP = strItemGroup
                    Dim trans As SqlTransaction
                    trans = clsDBFuncationality.GetTransactin()
                    If clsCommon.myLen(strItemCategorycode) > 0 AndAlso clsDBFuncationality.getSingleValue("Select count(*) from TSPL_MF_PRODUCTION_ITEM_CATEGORY where PROD_ITEM_CATEGORY_CODE='" + strItemCategorycode + "' ", trans) > 0 Then
                        isNewEntry = False
                    Else
                        isNewEntry = True

                    End If
                    ClsItemCategoryForproduction.SaveData(obj, isNewEntry, trans)

                Next


                clsCommon.ProgressBarHide()
                common.clsCommon.MyMessageBoxShow("Data Transfer Completed!", Me.Text, MessageBoxButtons.OK)
            Catch ex As Exception

                clsCommon.ProgressBarHide()
                myMessages.myExceptions(ex)
            End Try
        End If
        Me.Controls.Remove(gv)

    End Sub


    Private Sub rmExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rmExport.Click
        Dim str As String
        str = "select PROD_ITEM_CATEGORY_CODE as [PROD ITEM CATEGORY CODE],"
        str += "PROD_ITEM_CATEGORY_NAME as [PROD ITEM CATEGORY NAME],"
        str += "DESCRIPTION as [DESCRIPTION],"
        str += "ITEM_GROUP as [ITEM GROUP] from TSPL_MF_PRODUCTION_ITEM_CATEGORY "
        transportSql.ExporttoExcel(str, Me)
    End Sub
    '------------End

End Class
